PATCH /api/2.5/tenders/0aac695e27804293a2854dff7bed4be8/qualifications/81988da3ce1f4cfdba7afe53020a62e6?acc_token=82d005b2183e43fe8edbb00cc6eb36c1 HTTP/1.0
Authorization: Bearer broker
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "c72b35cfbfd84d7a980f772c02d025f6", 
    "date": "2020-05-15T01:00:00+03:00", 
    "id": "81988da3ce1f4cfdba7afe53020a62e6"
  }
}

