PATCH /api/2.5/tenders/28db6af763c74fceaedc98e147fed6cb/qualifications/f47839b389674e57bd1a69f0de41e383?acc_token=4d8039c4e08d4c278190842955a84ce4 HTTP/1.0
Authorization: Bearer broker
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active",
    "qualified": true,
    "eligible": true
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "f47839b389674e57bd1a69f0de41e383",
    "bidID": "9f572f6770254b01b919e923bbbd86ab",
    "lotID": "8b60d0525e2a40b9954d740b5b68c4ef",
    "status": "active",
    "date": "2023-10-10T01:00:00+03:00",
    "qualified": true,
    "eligible": true
  }
}

