POST /api/2.5/tenders/e234fb168a9a4eae96cf2776aac2c690/awards/6d8761429900453cb8704cd91058fe4a/complaints/e7af09300cbb4a29993e850a48c26a66/posts HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 281
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "recipient": "complaint_owner", 
    "description": "Відсутній документ", 
    "title": "Уточнення по вимозі"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e234fb168a9a4eae96cf2776aac2c690/awards/6d8761429900453cb8704cd91058fe4a/complaints/e7af09300cbb4a29993e850a48c26a66/posts/1c9923a9a2f3432d8ebbd6f2df85bec5
{
  "data": {
    "description": "Відсутній документ", 
    "title": "Уточнення по вимозі", 
    "author": "aboveThresholdReviewers", 
    "datePublished": "2020-05-01T01:00:03+03:00", 
    "recipient": "complaint_owner", 
    "id": "1c9923a9a2f3432d8ebbd6f2df85bec5"
  }
}

