POST /api/2.5/tenders/e234fb168a9a4eae96cf2776aac2c690/awards/739fa985f3794c99876d853763bce6b9/complaints?acc_token=f877b151148e4600916ce4b50a92cc7f HTTP/1.0
Authorization: Bearer broker
Content-Length: 1345
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Недостатньо інформації", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "Вінницька область", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e234fb168a9a4eae96cf2776aac2c690/awards/739fa985f3794c99876d853763bce6b9/complaints/93f5af4e14ec411cbbd16e7434517662
{
  "access": {
    "transfer": "c44efab2da82484694abfdbf31a73069", 
    "token": "b4feec497ff04b68b96492fbe8adadba"
  }, 
  "data": {
    "status": "draft", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "Вінницька область", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "complaintID": "UA-2020-05-01-000001.10", 
    "date": "2020-05-01T01:00:03+03:00", 
    "type": "claim", 
    "id": "93f5af4e14ec411cbbd16e7434517662"
  }
}

