GET /api/2.5/tenders/c11a2140a8964d45bebcd82401c7dd25/bids/fddbccd750014e65a6931fd69f0991a0/financial_documents?acc_token=31109c8bae014a29829bb2bb7c7da290 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "financial_doc.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f92632a5c1ab489db6deba5d2d313753?Signature=ngE4pkDIsSVDd4FtpLl6wtym9yJA7ryCZ6klMuLE2OmW1GlaU20TfS94LAsLawJb%2BG0SRv3GxdnWg07AowB8Bw%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "feb708021761446490d6d59b44953fa0",
      "confidentiality": "public",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "dateModified": "2023-10-10T01:00:00+03:00"
    },
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "financial_doc2.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6213288a9dc8448e9d55b5684ce9c0f2?Signature=VagGJ5qPJ4mU6iGXxVClHZk60pm18WTzdvlJjdBxWRPA1TrZP5d0WDipfHusVAXkb%2BbD7U0G5rYz2wDyz1A7BQ%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "c0a9342a75944353be8235704cecfe3f",
      "confidentiality": "public",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "dateModified": "2023-10-10T01:00:00+03:00"
    }
  ]
}

