GET /api/2.5/tenders/324708a9889241218b0477f49c77da70/cancellations/066b2e148cf449fda5547a47b013426d/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2020-05-01T01:00:00+03:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4cababe69b5c455db44c406579260b64?KeyID=a8968c46&Signature=DpVGhaBRZhQGx11e%252BX7LbodWlOyZ3aY1R%252ByQEb7pwMSNPAskds3kCLHtQwu8n13%2Fb6lag6JEccye3E2yS1%252BTCg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2020-05-01T01:00:00+03:00", 
          "id": "9e7b038acbfe4c38bca39ccad97108a8", 
          "dateModified": "2020-05-01T01:00:00+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5fefa91450c14942bb0d38995812a59d?KeyID=a8968c46&Signature=FVWOBvmQt4hq1nelCIBg32%252Bdqb8xSH3TrtGg28dPs8gHe%2F5Q7MZCN%252B2VKXXs1WSQMqBQObudf0fhrdoxohFyAQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2020-05-01T01:00:00+03:00", 
          "id": "a948680ab0524c138f788a12d5a30a3b", 
          "dateModified": "2020-05-01T01:00:00+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "tendererAction": "Умови виправлено", 
      "tendererActionDate": "2020-05-01T01:00:00+03:00", 
      "dateSubmitted": "2020-05-01T01:00:00+03:00", 
      "complaintID": "UA-2020-05-01-000001.1", 
      "date": "2020-05-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "57c25369e0cf415c9939c0a910006ca1"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2020-05-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "dateSubmitted": "2020-05-01T01:00:00+03:00", 
      "complaintID": "UA-2020-05-01-000001.2", 
      "date": "2020-05-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "fe2aecd3832e40fa946d7449a5250f6a"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2020-05-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "dateSubmitted": "2020-05-01T01:00:00+03:00", 
      "complaintID": "UA-2020-05-01-000001.3", 
      "date": "2020-05-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "e69509bc26d34e60969600cd90d9f24c"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2020-05-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "decision": "Тендер скасовується замовником", 
      "title": "Недостатньо інформації", 
      "dateCanceled": "2020-05-01T01:00:00+03:00", 
      "dateSubmitted": "2020-05-01T01:00:00+03:00", 
      "complaintID": "UA-2020-05-01-000001.4", 
      "date": "2020-05-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "ed7ae1a2d0674612bad91da2fb473b90"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2020-05-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "decision": "Тендер скасовується замовником", 
      "title": "Недостатньо інформації", 
      "dateCanceled": "2020-05-01T01:00:00+03:00", 
      "dateSubmitted": "2020-05-01T01:00:00+03:00", 
      "complaintID": "UA-2020-05-01-000001.5", 
      "date": "2020-05-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "701d2a172529421899a04411e1966299"
    }
  ]
}

