POST /api/2.5/tenders/a41032bbcdec47df9273af568f595c1d/complaints/8db347bde49040188e3ed9a12bc4ac0a/documents?acc_token=4ab12c970f5348628048eaa1b26c6f4b HTTP/1.0
Authorization: Bearer broker
Content-Length: 157
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/a41032bbcdec47df9273af568f595c1d/complaints/8db347bde49040188e3ed9a12bc4ac0a/documents/066328ca101d4a3c8a6bacc113a5cbbe
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bdb4ff530fb74e1f9e0e548ce00e15bb?KeyID=a8968c46&Signature=Dm5WnP%252BnXSj3%2Fpr7gIEnxTNaPkxOB4HC9EW3v55kOmIbPwmHh4o7p94KDyNJy56GmM7V2tpZGRyrBSxMDhluBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-10-25T01:00:00+03:00", 
    "id": "066328ca101d4a3c8a6bacc113a5cbbe", 
    "dateModified": "2019-10-25T01:00:00+03:00"
  }
}

