PATCH /api/2.5/tenders/0aac695e27804293a2854dff7bed4be8/cancellations/f70b99c60e434b2393fbd1d1f318d482?acc_token=82d005b2183e43fe8edbb00cc6eb36c1 HTTP/1.0
Authorization: Bearer broker
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/22c561662fb8400bbcce5acc4d681e08?KeyID=a8968c46&Signature=3Au7UrT7q06%2FWGKS3ktBI6koSZp3jkisH%252BTK%252BWcjoQv%2FYRrCZYCXUtkRuTr7pJss3z8XERI%2FfPkZHD1X3Fd%2FBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-09-08T01:00:01+03:00", 
        "author": "tender_owner", 
        "id": "ce91e0d62c0e452bae98e7c93705d883", 
        "dateModified": "2020-09-08T01:00:01+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c1a4abf107a8485eb4bb3fe88d0a010c?KeyID=a8968c46&Signature=ZWh%2FqRO6X7SLBffg7CgjfHorFXjCCregtmi%2FHfHpv3lRBMK6iZT2YsfMe2GG8KTYKV0nGl5Iab1MUvGpUzIgBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-09-08T01:00:01+03:00", 
        "author": "tender_owner", 
        "id": "ce91e0d62c0e452bae98e7c93705d883", 
        "dateModified": "2020-09-08T01:00:01+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2020-09-08T01:00:01+03:00", 
      "endDate": "2020-09-19T00:00:00+03:00"
    }, 
    "reason": "cancellation reason", 
    "reasonType": "expensesCut", 
    "date": "2020-09-08T01:00:01+03:00", 
    "cancellationOf": "tender", 
    "id": "f70b99c60e434b2393fbd1d1f318d482"
  }
}

