POST /api/2.5/tenders/3dc3a680d9564656a49e22ae78aef1e9/qualifications/bf17b04f7def40c9bc888a0ed6a6920a/complaints/9b833b528894421bb65c60de041ebfc9/posts?acc_token=b255a84bbe774546a39ed18052afe160 HTTP/1.0
Authorization: Bearer broker
Content-Length: 667
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "recipient": "aboveThresholdReviewers", 
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e5ea880dbf214857880bc550547e9ea5?KeyID=a8968c46&Signature=Y0aq6Jr2zV%2BCNMcl5HqVmPzbBe1QDSGlRYnhvBJBtfNoMyXYe3pPfFAwkN3BUiyqsSSgvDwDIu%2BFjgCdPy%2FCAg%3D%3D", 
        "title": "post_document_tender.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "relatedPost": "56ed6a36cd494adf845a55c1e0fe06a0", 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/3dc3a680d9564656a49e22ae78aef1e9/qualifications/bf17b04f7def40c9bc888a0ed6a6920a/complaints/9b833b528894421bb65c60de041ebfc9/posts/70c9e6a8dcf74dfd86c94c0bb94cc721
{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "post_document_tender.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e5ea880dbf214857880bc550547e9ea5?KeyID=a8968c46&Signature=Y0aq6Jr2zV%2BCNMcl5HqVmPzbBe1QDSGlRYnhvBJBtfNoMyXYe3pPfFAwkN3BUiyqsSSgvDwDIu%2BFjgCdPy%2FCAg%3D%3D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-05-01T01:00:01+03:00", 
        "id": "9e2c740ff5744bfbb8fbadd2987d48b9", 
        "dateModified": "2020-05-01T01:00:01+03:00"
      }
    ], 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі", 
    "author": "tender_owner", 
    "datePublished": "2020-05-01T01:00:01+03:00", 
    "relatedPost": "56ed6a36cd494adf845a55c1e0fe06a0", 
    "recipient": "aboveThresholdReviewers", 
    "id": "70c9e6a8dcf74dfd86c94c0bb94cc721"
  }
}

