POST /api/2.5/tenders/0aac695e27804293a2854dff7bed4be8/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 1000
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "selfQualified": true, 
    "value": {
      "contractDuration": {
        "days": 200, 
        "years": 12
      }, 
      "yearlyPaymentsPercentage": 0.85, 
      "annualCostsReduction": [
        400, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900
      ]
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "Львівська область", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0aac695e27804293a2854dff7bed4be8/bids/c72b35cfbfd84d7a980f772c02d025f6
{
  "access": {
    "transfer": "a91de4c425bc4bc09ae040f2a987d0ce", 
    "token": "a3322ea4c3e5495ebd9a1d928ea546d7"
  }, 
  "data": {
    "status": "pending", 
    "value": {
      "yearlyPaymentsPercentage": 0.85, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 9457.12, 
      "contractDuration": {
        "days": 200, 
        "years": 12
      }, 
      "amountPerformance": 750.92, 
      "annualCostsReduction": [
        400.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0
      ]
    }, 
    "id": "c72b35cfbfd84d7a980f772c02d025f6", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "Львівська область", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2020-05-15T01:00:00+03:00", 
    "selfQualified": true
  }
}

