POST /api/2.5/tenders/501cb77768e446f39265deb722b208a3/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 1571
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro"
      }
    ],
    "value": {
      "annualCostsReduction": [
        500,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000
      ],
      "yearlyPaymentsPercentage": 0.9,
      "contractDuration": {
        "years": 10,
        "days": 74
      }
    },
    "status": "draft",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "selfQualified": true
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/501cb77768e446f39265deb722b208a3/bids/658a2d2b9721494887a952371db42b5a
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "status": "draft",
    "value": {
      "currency": "UAH",
      "valueAddedTaxIncluded": true,
      "yearlyPaymentsPercentage": 0.9,
      "annualCostsReduction": [
        500,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000
      ],
      "contractDuration": {
        "years": 10,
        "days": 74
      },
      "amountPerformance": 801.01,
      "amount": 8734.93
    },
    "selfQualified": true,
    "id": "658a2d2b9721494887a952371db42b5a",
    "date": "2023-01-01T00:00:00+02:00"
  },
  "access": {
    "token": "6624fd96edbc46c1b84b5ca323e4e239",
    "transfer": "195064e4e9594045acc8da8c5e63a614"
  }
}

