POST /api/2.5/tenders/28db6af763c74fceaedc98e147fed6cb/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 3223
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Львів",
          "postalCode": "79013",
          "region": "Львівська область",
          "streetAddress": "вул. Островського, 34"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "name": "Андрій Олексюк",
          "telephone": "+380322916930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Книга»",
        "scale": "sme"
      }
    ],
    "value": {
      "annualCostsReduction": [
        200,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800
      ],
      "yearlyPaymentsPercentage": 0.86,
      "contractDuration": {
        "years": 13,
        "days": 40
      }
    },
    "documents": [
      {
        "title": "Proposal_part1.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f81e2b85d5a042bb8c1b3c523318cd3e?Signature=O2FTtc57TCvUFC0GEHigAGVpQjIVvOry%2FQ%2BUFFyzc5rV%2Bwc1XV%2BBrURbYF9yZ3wp8Q2viY8LOYA9UxCXtpFjDQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      },
      {
        "title": "Proposal_part2.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/78c7dc59da6a46d8ac24150e98d5678c?Signature=eu6t69JSbWyLShgA6rWfHkLOFWQOGEEuZKTFeV3OFAnA0wa%2B99u%2BwtYosYPxTfyIHcIyJ84HOBTNpCxulSHxCQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair."
      }
    ],
    "eligibilityDocuments": [
      {
        "title": "eligibility_doc.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dc8dbe727ce64eb894c3ce3465b3eece?Signature=RhyJ5Iw3gVd3R2pRyLp%2B%2B0N8RV7wmoU6dwNQeaL%2B%2BxhcMqwYBybPmo8x2NhyT3KLrJFUktviVnePC6gztlOHBQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "financialDocuments": [
      {
        "title": "financial_doc.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/683b0938ab734403b45a0e5047209d93?Signature=XueuoIlayeyHbtSh%2FoEptrWZcPmZaVvEwxjJ2U30gu5PJ9KA0JhowLeLp3tkVW0bEziPXJbuZQDf3JnrhvJNAg%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "qualificationDocuments": [
      {
        "title": "qualification_document.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7dd8f77db81d4e95803276f2c2b6b50f?Signature=%2BaCbUVaZEnPAWg3z1iCBZDixm7VRl9F0Q35H8e2LGEwTmYj%2FYzMMwKrMHOR6yJB8sxHOnQ8PyPXNQyU9zxf0CQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "selfQualified": true,
    "status": "draft"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/28db6af763c74fceaedc98e147fed6cb/bids/e56918aa665d46ae9a9061708a7a83a0

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "telephone": "+380322916930",
          "name": "Андрій Олексюк"
        },
        "scale": "sme"
      }
    ],
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f81e2b85d5a042bb8c1b3c523318cd3e?Signature=uiNtquKo2jbbYA4L5zjsSi3JhYhamYzu0iWMz5Wr5TuvFQUZe3wP6fe2%2B17xwNF7ZD2D0e%2Fy2HlHnqNAasaXDw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "4ff8f1b97e3f4c808690e1c00427199a",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      },
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "documentOf": "tender",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair.",
        "language": "uk",
        "id": "b22bc9fa2afa4b62a0e5e99a300f93bf",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ],
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/28db6af763c74fceaedc98e147fed6cb/bids/e56918aa665d46ae9a9061708a7a83a0/financial_documents/b3f32bf9874a4478a482fcede3a86c85?download=683b0938ab734403b45a0e5047209d93",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "b3f32bf9874a4478a482fcede3a86c85",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ],
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "eligibility_doc.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/28db6af763c74fceaedc98e147fed6cb/bids/e56918aa665d46ae9a9061708a7a83a0/eligibility_documents/0de8e16617f0418f97771e3eb5e5523a?download=dc8dbe727ce64eb894c3ce3465b3eece",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "0de8e16617f0418f97771e3eb5e5523a",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ],
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "qualification_document.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/28db6af763c74fceaedc98e147fed6cb/bids/e56918aa665d46ae9a9061708a7a83a0/qualification_documents/a322c8a1eb7c4e7d8b1f3be96ad5b091?download=7dd8f77db81d4e95803276f2c2b6b50f",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "a322c8a1eb7c4e7d8b1f3be96ad5b091",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ],
    "status": "draft",
    "value": {
      "currency": "UAH",
      "valueAddedTaxIncluded": true,
      "yearlyPaymentsPercentage": 0.86,
      "annualCostsReduction": [
        200,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800,
        800
      ],
      "contractDuration": {
        "years": 13,
        "days": 40
      },
      "amountPerformance": 562.72,
      "amount": 8505.28
    },
    "selfQualified": true,
    "id": "e56918aa665d46ae9a9061708a7a83a0",
    "date": "2023-01-01T00:00:00+02:00"
  },
  "access": {
    "token": "37e5e571320649e9aaad2719b31c3101",
    "transfer": "e7307c1476564546850c92bc9c8fd25f"
  }
}

