PATCH /api/2.5/tenders/7378acd602f14dc498b14cc6198a6995/qualifications/75ff1c03d8cb45ddaa953765af93a1a3?acc_token=cdb0d97ad6324ce1b99843f3f2959aa4 HTTP/1.0
Authorization: Bearer broker
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "75ff1c03d8cb45ddaa953765af93a1a3",
    "bidID": "1869f759d3fa418ea2c3162b6fe5fd9c",
    "status": "unsuccessful",
    "date": "2021-03-16T00:00:00+02:00",
    "qualified": false,
    "eligible": false
  }
}

