GET /api/2.5/tenders/7378acd602f14dc498b14cc6198a6995/bids/1869f759d3fa418ea2c3162b6fe5fd9c?acc_token=cdb0d97ad6324ce1b99843f3f2959aa4 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "requirementResponses": [
      {
        "id": "87b2e4d05506485d8746769b51674e54",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "bea5855e88174f688de439861b20c3cb",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True"
      },
      {
        "id": "5b43954eaac54a42abe4f6385f3b052f",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "4a931e128a41434ba9c11038e2bf9ac7",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True"
      },
      {
        "id": "5a426a864d09455596110c7ab21bc72d",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "6d89fd6e9de84fce88ae5039bc2e5acd",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True"
      },
      {
        "id": "038564ca237f424ca615cb6d8dc35eac",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "4636a1acfdf344f9b4a5f4c7680a80a8",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True"
      },
      {
        "id": "81339009cf414f7095caa39f0f1451ec",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "0d109a6e22a647d99bed419517406eb3",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True"
      },
      {
        "id": "71ee5de187f14a10a9ab872174b63c24",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "ec32c0f64d5b45978fbd222d37dcf185",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True"
      },
      {
        "id": "d1a4e33f1b3344ad919d340ac1f91ed7",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "91d4974590024e3a9f49b3e45d36929e",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True"
      },
      {
        "id": "e641c4a8076942779643f2486f79c869",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "b7d2166496e4442ba8a94b599eb732da",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True"
      },
      {
        "id": "e554cd2d186644af95ffd1fa181b7e94",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "eddaf9e968254910b5d3f2df928fb4c7",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True"
      },
      {
        "id": "3457efb50d1f42a19630b24dbb14e63d",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "634a8423f3f246baabbaabeb0b8a022e",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True"
      },
      {
        "id": "177971d89f974a50a773a475cbe3ac50",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "1589ec2d45b34af999625b04e6a5a223",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True"
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "telephone": "+380322916930",
          "name": "Андрій Олексюк"
        },
        "scale": "sme"
      }
    ],
    "id": "1869f759d3fa418ea2c3162b6fe5fd9c",
    "documents": [
      {
        "id": "36b62b03423c4ff994c7b502402e9eb0",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/990290f4487844639797e1f0adf02bc3?Signature=rOXN3tFVHoQCpMt2DSVVNl%2FvV6DOQUbzdFR0SblLD6LbwpfADRlJyqoONJi60r2C0BrDVvvzEycUAUVf4cu9Aw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      },
      {
        "id": "0ee2143a609e40b3b7a15264d50c4556",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7378acd602f14dc498b14cc6198a6995/bids/1869f759d3fa418ea2c3162b6fe5fd9c/documents/0ee2143a609e40b3b7a15264d50c4556?download=9428cc919ddc46249fe7f4aedbd3e329",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair.",
        "language": "uk"
      }
    ],
    "eligibilityDocuments": [
      {
        "id": "7124a56704d44eae808e35ccc25ef011",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "eligibility_doc.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7378acd602f14dc498b14cc6198a6995/bids/1869f759d3fa418ea2c3162b6fe5fd9c/eligibility_documents/7124a56704d44eae808e35ccc25ef011?download=f20fb61ed9de43a39a775b9f82d2faaf",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      }
    ],
    "status": "unsuccessful",
    "selfQualified": true
  }
}

