PATCH /api/2.5/tenders/552fdec279c740ab85e2b30af7a37d37/qualifications/ff4e936e38554009b213d7aa6e6885d1?acc_token=4d8039c4e08d4c278190842955a84ce4 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "unsuccessful"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "ff4e936e38554009b213d7aa6e6885d1",
    "bidID": "6bd262aa39ce4fd1b77f93239ba8ec51",
    "lotID": "8b60d0525e2a40b9954d740b5b68c4ef",
    "status": "unsuccessful",
    "date": "2023-10-10T01:00:00+03:00",
    "qualified": false,
    "eligible": false
  }
}

