GET /api/2.5/tenders/3eed1dac730f4b268ef8a2a9186faaba/documents/f94764f8702e4cf7bdc3414212d68cd4?acc_token=0f883e2ec1a5435f884f057009b67294 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "confidentiality": "public",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/24ab7b02c104473dbe8a5ea32a297be2?Signature=2mqIIVZZZz0xdgPdnJS3IH8kxNLl%2BBMT4kVoXy2jmreEeyDvsbF4jF06FMnb9g5vyN0%2BBk8JpW1wqh44T%2BZvBw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "f94764f8702e4cf7bdc3414212d68cd4",
    "datePublished": "2027-01-01T00:00:00+02:00",
    "dateModified": "2027-01-01T00:00:00+02:00",
    "author": "tender_owner"
  }
}

