GET /api/2.5/tenders/28db6af763c74fceaedc98e147fed6cb/documents?acc_token=871fba7d0f2840d48ed2394d778a5004 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "Notice.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/24ab7b02c104473dbe8a5ea32a297be2?Signature=2mqIIVZZZz0xdgPdnJS3IH8kxNLl%2BBMT4kVoXy2jmreEeyDvsbF4jF06FMnb9g5vyN0%2BBk8JpW1wqh44T%2BZvBw%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "id": "44d8ad8fc1c142148381c3fee2507ff7",
      "datePublished": "2023-01-01T00:00:00+02:00",
      "dateModified": "2023-01-01T00:00:00+02:00",
      "author": "tender_owner"
    },
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "AwardCriteria.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f429b74ab3cd42789419eb507330852a?Signature=ooFtwpzXUsHXdkZ1GVU51xa%2BraDLUswEAZNNKtnzVk63tn9Jp4nsasjB%2F6RQNokW0mv5tzhfaEEPV2nC%2Bn7hBQ%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "id": "0633ecf79c054219a562daf0883419c7",
      "datePublished": "2023-01-01T00:00:00+02:00",
      "dateModified": "2023-01-01T00:00:00+02:00",
      "author": "tender_owner"
    }
  ]
}

