GET /api/2.5/tenders/0aac695e27804293a2854dff7bed4be8/contracts/b24337545a6c4c25843d326ae2a60645/documents HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/24594c4842774b41b3749343a697fe95?KeyID=a8968c46&Signature=SZivFL8GcsJbRh3K%252BqGH%252Ba7yrkuGK4%252BPcO4xX5tSz1yr861izL9SZaASoCMMDn3RuHlr3OnMf2hzPeK0WIXLDA%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2020-09-08T01:00:01+03:00", 
      "id": "47b23474081c4136bd54bb6f7b9fbbfa", 
      "dateModified": "2020-09-08T01:00:01+03:00"
    }
  ]
}

