POST /api/2.5/tenders/7378acd602f14dc498b14cc6198a6995/contracts/50fd544f07894953927212c4e2a4cb9c/documents?acc_token=cdb0d97ad6324ce1b99843f3f2959aa4 HTTP/1.0
Authorization: Bearer broker
Content-Length: 343
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "contract_second_document.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/792d7aebb56f48358b4e622f9772f169?Signature=d5NF6aSRjiSK3tMHQMlwWj1hwJ0I8mftKTEp1GoLSatOOR8M4s7D%2Fsopl42GjjTue%2B3Fm46zZXMpg7TrIw5RAA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7378acd602f14dc498b14cc6198a6995/contracts/50fd544f07894953927212c4e2a4cb9c/documents/c1a1bfaeaa0e4d6d960a9a2f35458ce1
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "contract_second_document.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/792d7aebb56f48358b4e622f9772f169?Signature=SI4fYHug25uPTLELzIDikO8cvFLNuUfpUhWtsu8P4gbva04%2FDL3kuNnswkQ2VbyRJ0OytB6Wjg5DQOj11d8gDg%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "id": "c1a1bfaeaa0e4d6d960a9a2f35458ce1",
    "datePublished": "2023-01-01T00:00:01+02:00",
    "dateModified": "2023-01-01T00:00:01+02:00"
  }
}

