POST /api/2.5/tenders/501cb77768e446f39265deb722b208a3/bids/658a2d2b9721494887a952371db42b5a/financial_documents?acc_token=6624fd96edbc46c1b84b5ca323e4e239 HTTP/1.0
Authorization: Bearer broker
Content-Length: 331
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "financial_doc.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/55caeebab78045959bdf295a177ca980?Signature=%2BuQeSapdTnxA1Nqb5IG4szQ1b6%2FYVnS7TbEY%2FHQYU2DJfgTPh5bcKK9wKQGthbDLTsJ7JSxQYtHBFIiQLg1NBg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/501cb77768e446f39265deb722b208a3/bids/658a2d2b9721494887a952371db42b5a/financial_documents/74a99c3d03bd4b3a8fb9a07060fd8561

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "financial_doc.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/55caeebab78045959bdf295a177ca980?Signature=GgZlbGXozSZkmMS5CQiPEG87kW5ylVGtf7NxAtI8o2spziVfIaOBPvJr9VqEFUBTcDXeW%2BxrlFBzguIu0FEaBw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "confidentiality": "public",
    "language": "uk",
    "id": "74a99c3d03bd4b3a8fb9a07060fd8561",
    "datePublished": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:00+02:00"
  }
}

POST /api/2.5/tenders/501cb77768e446f39265deb722b208a3/bids/658a2d2b9721494887a952371db42b5a/financial_documents?acc_token=6624fd96edbc46c1b84b5ca323e4e239 HTTP/1.0
Authorization: Bearer broker
Content-Length: 336
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "financial_doc2.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/668b8ebe1fbc423a880d331641a3f909?Signature=L48TbwDOQUcUIVuzZxSrUTjxrJNH%2FDGBXNpqTe%2FfzHe%2BQpxQ0y%2FYHSmg7uFBa0xkSq16%2FZjlRLuojc7TFEbSAQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/501cb77768e446f39265deb722b208a3/bids/658a2d2b9721494887a952371db42b5a/financial_documents/2ca63b8584054860b2f7543e1876ffb1

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "financial_doc2.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/668b8ebe1fbc423a880d331641a3f909?Signature=NR2qBKA5c8OKsKq3Ynav61HVoLmIh3Sm7QP1ru7nyRyhq3aYjDGKCT6bBhkboaM0W1fWxPovqVLikGOA9EbxBA%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "confidentiality": "public",
    "language": "uk",
    "id": "2ca63b8584054860b2f7543e1876ffb1",
    "datePublished": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:00+02:00"
  }
}

