POST /api/2.5/tenders/0aac695e27804293a2854dff7bed4be8/documents?acc_token=82d005b2183e43fe8edbb00cc6eb36c1 HTTP/1.0
Authorization: Bearer broker
Content-Length: 142
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0aac695e27804293a2854dff7bed4be8/documents/e323c662598b43edbef1a87032f99012
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d1f06f07711e4e8c8d934da1f688987c?KeyID=a8968c46&Signature=j%2F%252BPlE6yiFmVfMFLZMOlMF3x34ibMwo%2F2lua8xdYl%2FaWTT2z6sww%2FOFaZPz%252B11ou38HHjy%2FUB1M9msoDFHilBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2020-09-08T01:00:00+03:00", 
    "id": "e323c662598b43edbef1a87032f99012", 
    "dateModified": "2020-09-08T01:00:00+03:00"
  }
}

