POST /api/2.5/tenders/33f610abd0a54c8bb1da547c377a3324/documents?acc_token=7cb87b2d0f3d446993a6da1f03746396 HTTP/1.0
Authorization: Bearer broker
Content-Length: 149
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="AwardCriteria.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/33f610abd0a54c8bb1da547c377a3324/documents/428e9ce6dfe44fdc8fabf3d3ec0ae851
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "428e9ce6dfe44fdc8fabf3d3ec0ae851",
    "hash": "md5:00000000000000000000000000000000",
    "title": "AwardCriteria.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/be2dcea392744ec3bfc7b53161fabc61?Signature=MezoP%2BI%2Fm2XEuRfqInNFFvuk5wxW96eZrt21hwexze5P6yb4JA8P2xcGnlE8zs881veHw1BR5e%2Fc2qmuyIvjBQ%3D%3D&KeyID=a8968c46",
    "datePublished": "2021-03-16T00:00:00+02:00",
    "dateModified": "2021-03-16T00:00:00+02:00",
    "author": "tender_owner",
    "documentOf": "tender",
    "language": "uk"
  }
}

