POST /api/2.5/tenders/3eed1dac730f4b268ef8a2a9186faaba/bids/f781bfc8c3b24fcc95c01833bbc26d18/eligibility_documents?acc_token=f9c83851a3614d86873ce2ac65218f2b HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "eligibility_doc.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c3fdae8c71e84606ba09ae07517475bf?Signature=n3bMflNvabOiTAntrk3fbeySK4qkV%2FoB5psCm84yHEeFK4nuSWsctGNYj9GFlaacF%2FXXkNqiU9EnaNdtE6bdAw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/3eed1dac730f4b268ef8a2a9186faaba/bids/f781bfc8c3b24fcc95c01833bbc26d18/eligibility_documents/d26b55f807c64f618d6d40d7d9021932

{
  "data": {
    "confidentiality": "public",
    "hash": "md5:00000000000000000000000000000000",
    "title": "eligibility_doc.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c3fdae8c71e84606ba09ae07517475bf?Signature=GuvuNTb2t0pdrym7dvoqqxi5eWRpvl6jvc3cfuW6KFFp%2BupfDxPjO%2Fd4D8G9LAjG%2BBVhAwbnLBk2PNfs9SIoAw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "d26b55f807c64f618d6d40d7d9021932",
    "datePublished": "2027-01-01T00:00:00+02:00",
    "dateModified": "2027-01-01T00:00:00+02:00"
  }
}

