GET /api/2.5/tenders/37cb590308a242a9836f51a9994c7492/agreements HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "0fea7d7c4c8649f5a499885d630671f5",
      "agreementID": "UA-2021-03-16-000001-774f515207d840bbb2291a27f848ca611",
      "date": "2021-03-16T00:00:00+02:00",
      "items": [
        {
          "id": "fb692f97b807462b94668d4091b2779b",
          "description": "футляри до державних нагород",
          "additionalClassifications": [
            {
              "scheme": "ДКПП",
              "id": "17.21.1",
              "description": "папір і картон гофровані, паперова й картонна тара"
            }
          ],
          "quantity": 5.0,
          "relatedLot": "52815e9d01914c7a9bf4ba18ebb5e783",
          "classification": {
            "description": "Cartons",
            "scheme": "ДК021",
            "id": "44617100-9"
          },
          "description_en": "Cases for state awards",
          "deliveryDate": {
            "startDate": "2018-06-27T13:39:09.362837+03:00",
            "endDate": "2018-06-30T13:39:09.362837+03:00"
          },
          "deliveryAddress": {
            "streetAddress": "вул. Банкова 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "79000",
            "countryName": "Україна"
          },
          "unit": {
            "name": "item",
            "code": "KGM"
          }
        },
        {
          "id": "eda37d51e2854d93aedc7e1d31e01cea",
          "description": "футляри до державних нагород",
          "additionalClassifications": [
            {
              "scheme": "ДКПП",
              "id": "17.21.1",
              "description": "папір і картон гофровані, паперова й картонна тара"
            }
          ],
          "quantity": 5.0,
          "relatedLot": "52815e9d01914c7a9bf4ba18ebb5e783",
          "classification": {
            "description": "Cartons",
            "scheme": "ДК021",
            "id": "44617100-9"
          },
          "description_en": "Cases for state awards",
          "deliveryDate": {
            "startDate": "2018-06-27T13:39:09.362837+03:00",
            "endDate": "2018-06-30T13:39:09.362837+03:00"
          },
          "deliveryAddress": {
            "streetAddress": "вул. Банкова 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "79000",
            "countryName": "Україна"
          },
          "unit": {
            "name": "item",
            "code": "GRM"
          }
        }
      ],
      "status": "pending",
      "contracts": [
        {
          "id": "edb78279aaec40d3be65c96c5c5eb0db",
          "status": "active",
          "suppliers": [
            {
              "name": "«Снігур»",
              "identifier": {
                "scheme": "UA-EDR",
                "id": "00137227",
                "uri": "http://www.sc.gov.ua/"
              },
              "address": {
                "streetAddress": "вул. Островського, 35",
                "locality": "м. Львів",
                "region": "Львівська область",
                "postalCode": "79013",
                "countryName": "Україна"
              },
              "contactPoint": {
                "name": "Іван Іваненко",
                "email": "fake@mail.com",
                "telephone": "+380322123456"
              },
              "scale": "mid"
            }
          ],
          "unitPrices": [
            {
              "relatedItem": "fb692f97b807462b94668d4091b2779b",
              "value": {
                "currency": "UAH",
                "valueAddedTaxIncluded": true
              }
            },
            {
              "relatedItem": "eda37d51e2854d93aedc7e1d31e01cea",
              "value": {
                "currency": "UAH",
                "valueAddedTaxIncluded": true
              }
            }
          ],
          "awardID": "6efdbaca87454c56a43f66a0b2479c78",
          "bidID": "f2396c5eb7dc40e986705a3de1cdc13b",
          "date": "2021-03-16T00:00:00+02:00"
        },
        {
          "id": "4ffc79bd176541f7a1aa8bdd26bc5a87",
          "status": "active",
          "suppliers": [
            {
              "name": "ДКП «Книга»",
              "identifier": {
                "scheme": "UA-EDR",
                "id": "00137226",
                "uri": "http://www.sc.gov.ua/"
              },
              "address": {
                "streetAddress": "вул. Островського, 34",
                "locality": "м. Львів",
                "region": "Львівська область",
                "postalCode": "79013",
                "countryName": "Україна"
              },
              "contactPoint": {
                "name": "Андрій Олексюк",
                "email": "aagt@gmail.com",
                "telephone": "+380322916930"
              },
              "scale": "sme"
            }
          ],
          "unitPrices": [
            {
              "relatedItem": "fb692f97b807462b94668d4091b2779b",
              "value": {
                "currency": "UAH",
                "valueAddedTaxIncluded": true
              }
            },
            {
              "relatedItem": "eda37d51e2854d93aedc7e1d31e01cea",
              "value": {
                "currency": "UAH",
                "valueAddedTaxIncluded": true
              }
            }
          ],
          "awardID": "d2527d5a606e4e96a27c7716be0d54bf",
          "bidID": "5502be861ff24fa281a68247002d018c",
          "date": "2021-03-16T00:00:00+02:00"
        },
        {
          "id": "4b5cb6ae595b43a48a5a1ac2001d1dcb",
          "status": "active",
          "suppliers": [
            {
              "name": "ДКП «Школяр»",
              "identifier": {
                "scheme": "UA-EDR",
                "id": "00137256",
                "uri": "http://www.sc.gov.ua/"
              },
              "address": {
                "streetAddress": "вул. Островського, 33",
                "locality": "м. Вінниця",
                "region": "Вінницька область",
                "postalCode": "21100",
                "countryName": "Україна"
              },
              "contactPoint": {
                "name": "Сергій Олексюк",
                "email": "soleksuk@gmail.com",
                "telephone": "+380432216930"
              },
              "scale": "micro"
            }
          ],
          "unitPrices": [
            {
              "relatedItem": "fb692f97b807462b94668d4091b2779b",
              "value": {
                "currency": "UAH",
                "valueAddedTaxIncluded": true
              }
            },
            {
              "relatedItem": "eda37d51e2854d93aedc7e1d31e01cea",
              "value": {
                "currency": "UAH",
                "valueAddedTaxIncluded": true
              }
            }
          ],
          "awardID": "8c1e3d2462f1441b85241f4957ab7094",
          "bidID": "b142414a5dc84ec0a828ba7e3d5f3513",
          "date": "2021-03-16T00:00:00+02:00"
        }
      ]
    }
  ]
}

