PATCH /api/2.5/tenders/dea691b943a946a8957e9be95bc51a06/qualifications/06288b758a524a9bbe729309e4c63db1?acc_token=a4dab218398a4cc8a8004a91d3ba9744 HTTP/1.0
Authorization: Bearer broker
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active",
    "qualified": true,
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "06288b758a524a9bbe729309e4c63db1",
    "bidID": "c37e1f57bb514ac38787d82c6de256e7",
    "lotID": "52815e9d01914c7a9bf4ba18ebb5e783",
    "status": "active",
    "date": "2023-01-01T00:00:00+02:00",
    "qualified": true,
    "eligible": true
  }
}

