PATCH /api/2.5/tenders/6427779ef1904a858ed980c275f8eac4/awards/2cd8cb64955b4bd29f141e1ccb226448/complaints/f04e480d25a64953a951c4dce690202c HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 33
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "0da753f5904c4a159f596f5f86fd0fb7", 
    "status": "satisfied", 
    "dateDecision": "2019-10-25T01:00:01+03:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/80f0065382d6460a870876011111d1ed?KeyID=a8968c46&Signature=9x14XZzzaXJxvvcdYDJZixU98NUV%2F90OWS7FGpbidK%252B7lU5RGWkfnSNXtZVql9NlxtlDz92WTTeE5KecXkFYCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:01+03:00", 
        "id": "a8d80d3b699342378aa2b8ee276d6f42", 
        "dateModified": "2019-10-25T01:00:01+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/aa0c3e49da12435fa6eb413104db067f?KeyID=a8968c46&Signature=ON7PQyfhI4niuUJniQykCFkwZKW9eh4N15WQ03AAhLCkyIXI6ytINO2vwoyefk0YFz4ka2CzR5L6Fjh1BoZXDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:01+03:00", 
        "id": "f924e2289d45408b983c305a1cf6bd6e", 
        "dateModified": "2019-10-25T01:00:01+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateAccepted": "2019-10-25T01:00:01+03:00", 
    "dateSubmitted": "2019-10-25T01:00:01+03:00", 
    "complaintID": "UA-2019-10-25-000001.1", 
    "date": "2019-10-25T01:00:01+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "f04e480d25a64953a951c4dce690202c"
  }
}

