GET /api/2.5/tenders/b69c06ceeeb145a4b5cc46d3d56de4d2/bids/6bf64eb443e54b8db51e4156558d97e0/documents?acc_token=2d0fd5fb837f4974a51ca1f675b37dfd HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "Proposal.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/566a898dcb5e4d6cbac7c19df3f2255d?Signature=uRLkxT9CU4hrZUvYjGFb1R3jqEVUUstlAOBI3Qcw0AYoq21jRnXFMBrr%2B2%2B%2B5Kr1qdf%2B9WSx003edlY64PwqAw%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "confidentiality": "public",
      "language": "uk",
      "id": "0d21d618935a400e86d27bba46bbbf9e",
      "datePublished": "2023-01-01T00:00:00+02:00",
      "dateModified": "2023-01-01T00:00:00+02:00"
    },
    {
      "id": "be92d5521e8845e5881db6c777f095d0",
      "datePublished": "2023-01-01T00:00:00+02:00",
      "hash": "md5:00000000000000000000000000000000",
      "title": "Proposal_top_secrets.pdf",
      "format": "application/pdf",
      "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b69c06ceeeb145a4b5cc46d3d56de4d2/bids/6bf64eb443e54b8db51e4156558d97e0/documents/be92d5521e8845e5881db6c777f095d0?download=a4fc3e46d4b34911bd554c3e3420e9d4",
      "documentOf": "tender",
      "dateModified": "2023-01-01T00:00:00+02:00",
      "confidentiality": "buyerOnly",
      "confidentialityRationale": "Only our company sells badgers with pink hair.",
      "language": "uk"
    }
  ]
}

