PATCH /api/2.5/tenders/8eb7f95b22bc45039c746b7f7da19d90/cancellations/5605ca0fd464454094dbbd2c5dd3a81a/complaints/9c9530ebd6e44c65b50e2a686cdd6e30?acc_token=4dce6df1aec648749cbbcd36cd662958 HTTP/1.0
Authorization: Bearer broker
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

