POST /api/2.5/tenders/eb9e3bc5967c4db0b2dac4faca46fa52/complaints/da7be586ca294103bc5a0ca6b78ccd69/posts?acc_token=9994f105653c4ebfb56a92c1b8b523aa HTTP/1.0
Authorization: Bearer broker
Content-Length: 668
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "recipient": "aboveThresholdReviewers", 
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/216ebe5dc8e84d3dba17dda20bb1e851?KeyID=a8968c46&Signature=2OekQm6Kwrb8l3iFh4uAJxCZXCHz6DM03l%2F%2BS2YP2QmXQgNJna62guUSo60bmBROUdXNJ9HvrTXerFmkcThpDQ%3D%3D", 
        "title": "post_document_complaint.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "relatedPost": "1f2a681216a4414ea7e1b1674b0b53f2", 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/eb9e3bc5967c4db0b2dac4faca46fa52/complaints/da7be586ca294103bc5a0ca6b78ccd69/posts/fa2765c98ed244849a0767eec20fb80d
{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "post_document_complaint.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/216ebe5dc8e84d3dba17dda20bb1e851?KeyID=a8968c46&Signature=2OekQm6Kwrb8l3iFh4uAJxCZXCHz6DM03l%2F%2BS2YP2QmXQgNJna62guUSo60bmBROUdXNJ9HvrTXerFmkcThpDQ%3D%3D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-05-01T01:00:00+03:00", 
        "id": "fd58de0e56fc4ea2854b1b9464cf253a", 
        "dateModified": "2020-05-01T01:00:00+03:00"
      }
    ], 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі", 
    "author": "complaint_owner", 
    "datePublished": "2020-05-01T01:00:00+03:00", 
    "relatedPost": "1f2a681216a4414ea7e1b1674b0b53f2", 
    "recipient": "aboveThresholdReviewers", 
    "id": "fa2765c98ed244849a0767eec20fb80d"
  }
}

