POST /api/2.5/tenders/30730028a07b4aee97ed094ebd250c58/cancellations?acc_token=216c4c5722b74bbbaaaf1498070dc772 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reason": "cancellation reason",
    "reasonType": "noDemand"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/30730028a07b4aee97ed094ebd250c58/cancellations/e9ce3aa4b15a410c89e11683450d44c8

{
  "data": {
    "reasonType": "noDemand",
    "reason": "cancellation reason",
    "id": "e9ce3aa4b15a410c89e11683450d44c8",
    "date": "2023-10-10T01:03:03+03:00",
    "cancellationOf": "tender",
    "status": "draft"
  }
}

