POST /api/2.5/tenders/5a06577d0adb4c42907931f3b9b03b2c/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 1422
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro"
      }
    ],
    "status": "draft",
    "lotValues": [
      {
        "value": {
          "amount": 500
        },
        "relatedLot": "9dea7e57fca24c0fa6c43f752611342d"
      }
    ],
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "selfQualified": true
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5a06577d0adb4c42907931f3b9b03b2c/bids/381f5658b23a448ea820b823934eeb79

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "lotValues": [
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "9dea7e57fca24c0fa6c43f752611342d",
        "status": "pending",
        "date": "2023-01-01T00:00:00+02:00"
      }
    ],
    "selfQualified": true,
    "status": "draft",
    "id": "381f5658b23a448ea820b823934eeb79",
    "date": "2023-01-01T00:00:00+02:00"
  },
  "access": {
    "token": "3ad252bcc1b04cfea53da4697044d594",
    "transfer": "4e797ef975644ee7865c9dd88a857283"
  }
}

