GET /api/2.5/tenders/37cb590308a242a9836f51a9994c7492/bids/eac6e323ccd84f588542f76867850060?acc_token=fbb49b806b484733bc09390b0e01078d HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "«Снігур»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137227",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 35",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Іван Іваненко",
          "email": "fake@mail.com",
          "telephone": "+380322123456"
        },
        "scale": "mid"
      }
    ],
    "id": "eac6e323ccd84f588542f76867850060",
    "requirementResponses": [
      {
        "id": "8c57eb166e04443cad4aac981bd5b9d7",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "eac3813d0a9546b8a345454efdf78730",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True"
      },
      {
        "id": "664434fa7e554b37b40d4222de69a4ae",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "7d82f51226134d83a257e2eda3462ca1",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True"
      },
      {
        "id": "031e3b514c47431fafb02e05139d81f3",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "5de056a1a9e940bca07f12530d18b7bc",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True"
      },
      {
        "id": "82c8466df30449d6893f11bee2a222f9",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "c414eff2894b4e55a106375506c85759",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True"
      },
      {
        "id": "4719898b6a8f419fa8781a57d1f364ad",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "f3938a407ddf4b6a89451a002a477c66",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True"
      },
      {
        "id": "049b4f7c671a479796620517cd5dd6de",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "ab603c2969b04ee3bcf6af9faf1f5d8d",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True"
      },
      {
        "id": "3c5ce4fcc54644aeaae393f7a84789e7",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "556860681c0243528408ead7e5284373",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True"
      },
      {
        "id": "c93733231988472cb8e471dd2b97cabf",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "078a074ea9804b5e8235d60651d49d66",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True"
      },
      {
        "id": "2978cde5e3d940b5b1f32dc32d9637f6",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "6cc1b284e72a43b49f9173cfd4a8af23",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True"
      },
      {
        "id": "92d40082b82d4a9b9bdba99840874913",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "de22ef7caea74245bf9667e7562fc4c0",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True"
      },
      {
        "id": "d5e187d3ea744450866cb1683e5884ac",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "2c1d35d6969444839472c80773c6abc7",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True"
      }
    ],
    "documents": [
      {
        "id": "e69a71de908d4c4a8f9c69e527938b69",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c1779fafc15841d3a83131dee57a4640?Signature=%2BhrD5a0ABwsMn60xLG5karTIWa%2BwjvMewCmI%2B%2BoDDUQqfLk8khBp%2FiicUw3LeTRcnRt1GeY9fA8%2BxGOVwLGmBw%3D%3D&KeyID=a8968c46",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk"
      },
      {
        "id": "fadca469c6e44f0ca8086ab778e301e6",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/37cb590308a242a9836f51a9994c7492/bids/eac6e323ccd84f588542f76867850060/documents/fadca469c6e44f0ca8086ab778e301e6?download=256123ec589044029ec3f8823d26d1a4",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "documentOf": "tender",
        "confidentialityRationale": "Only our company sells badgers with pink hair.",
        "confidentiality": "buyerOnly",
        "language": "uk"
      }
    ],
    "eligibilityDocuments": [
      {
        "id": "1973f516b53d40ecbc3f14c979bbb698",
        "hash": "md5:00000000000000000000000000000000",
        "title": "eligibility_doc.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a628e60a5cf141358caec2553308eed1?Signature=%2FMv2r%2BTsXroG95QUwAstCJzfjMmwwhGDVj0kf6D5xT1tAQP4j3tSfKVj7cfc2YxQFs0%2FhQjiKO5zGZdp4kAsAw%3D%3D&KeyID=a8968c46",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk"
      }
    ],
    "selfQualified": true,
    "status": "unsuccessful"
  }
}

