PATCH /api/2.5/tenders/b69c06ceeeb145a4b5cc46d3d56de4d2/agreements/0fea7d7c4c8649f5a499885d630671f5?acc_token=bf73c010063f4fb4a07e775871e11d60 HTTP/1.0
Authorization: Bearer broker
Content-Length: 124
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active",
    "period": {
      "startDate": "2023-01-01T00:00:01+02:00",
      "endDate": "2026-12-31T00:00:01+02:00"
    }
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "0fea7d7c4c8649f5a499885d630671f5",
    "agreementID": "UA-2023-01-01-000001-a-774f515207d840bbb2291a27f848ca611",
    "date": "2023-01-01T00:00:00+02:00",
    "dateSigned": "2023-01-01T00:00:01+02:00",
    "items": [
      {
        "id": "78edae5503b94e0eb20ca906a762bc8d",
        "description": "футляри до державних нагород",
        "classification": {
          "description": "Cartons",
          "scheme": "ДК021",
          "id": "44617100-9"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ],
        "quantity": 5.0,
        "relatedLot": "52815e9d01914c7a9bf4ba18ebb5e783",
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00",
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "description_en": "Cases for state awards",
        "unit": {
          "name": "item",
          "code": "KGM"
        }
      },
      {
        "id": "fc62a07c463c4750b0bdc92dd8787e2a",
        "description": "футляри до державних нагород",
        "classification": {
          "description": "Cartons",
          "scheme": "ДК021",
          "id": "44617100-9"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ],
        "quantity": 5.0,
        "relatedLot": "52815e9d01914c7a9bf4ba18ebb5e783",
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00",
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "description_en": "Cases for state awards",
        "unit": {
          "name": "item",
          "code": "GRM"
        }
      }
    ],
    "period": {
      "startDate": "2023-01-01T00:00:01+02:00",
      "endDate": "2026-12-31T00:00:01+02:00"
    },
    "status": "active",
    "contracts": [
      {
        "id": "edb78279aaec40d3be65c96c5c5eb0db",
        "status": "active",
        "suppliers": [
          {
            "name": "«Снігур»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137227",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 35",
              "locality": "м. Львів",
              "region": "Львівська область",
              "postalCode": "79013",
              "countryName": "Україна"
            },
            "contactPoint": {
              "email": "fake@mail.com",
              "telephone": "+380322123456",
              "name": "Іван Іваненко"
            },
            "scale": "mid"
          }
        ],
        "unitPrices": [
          {
            "relatedItem": "78edae5503b94e0eb20ca906a762bc8d",
            "value": {
              "currency": "UAH",
              "amount": 0.5,
              "valueAddedTaxIncluded": true
            }
          },
          {
            "relatedItem": "fc62a07c463c4750b0bdc92dd8787e2a",
            "value": {
              "currency": "UAH",
              "amount": 0.5,
              "valueAddedTaxIncluded": true
            }
          }
        ],
        "awardID": "2972d86645dc4d31b315bca98fc47858",
        "bidID": "dcda7735b5384d7b803444397600baf1",
        "date": "2023-01-01T00:00:00+02:00"
      },
      {
        "id": "4ffc79bd176541f7a1aa8bdd26bc5a87",
        "status": "active",
        "suppliers": [
          {
            "name": "ДКП «Книга»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137226",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 34",
              "locality": "м. Львів",
              "region": "Львівська область",
              "postalCode": "79013",
              "countryName": "Україна"
            },
            "contactPoint": {
              "email": "aagt@gmail.com",
              "telephone": "+380322916930",
              "name": "Андрій Олексюк"
            },
            "scale": "sme"
          }
        ],
        "unitPrices": [
          {
            "relatedItem": "78edae5503b94e0eb20ca906a762bc8d",
            "value": {
              "currency": "UAH",
              "amount": 0.5,
              "valueAddedTaxIncluded": true
            }
          },
          {
            "relatedItem": "fc62a07c463c4750b0bdc92dd8787e2a",
            "value": {
              "currency": "UAH",
              "amount": 0.5,
              "valueAddedTaxIncluded": true
            }
          }
        ],
        "awardID": "504459d46cbb42baa8b442f6da714db5",
        "bidID": "a9427978bcd440bda085ad41b2547b78",
        "date": "2023-01-01T00:00:00+02:00"
      },
      {
        "id": "4b5cb6ae595b43a48a5a1ac2001d1dcb",
        "status": "active",
        "suppliers": [
          {
            "name": "ДКП «Школяр»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137256",
              "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 33",
              "locality": "м. Вінниця",
              "region": "Вінницька область",
              "postalCode": "21100",
              "countryName": "Україна"
            },
            "contactPoint": {
              "email": "soleksuk@gmail.com",
              "telephone": "+380432216930",
              "name": "Сергій Олексюк"
            },
            "scale": "micro"
          }
        ],
        "unitPrices": [
          {
            "relatedItem": "78edae5503b94e0eb20ca906a762bc8d",
            "value": {
              "currency": "UAH",
              "amount": 0.5,
              "valueAddedTaxIncluded": true
            }
          },
          {
            "relatedItem": "fc62a07c463c4750b0bdc92dd8787e2a",
            "value": {
              "currency": "UAH",
              "amount": 0.5,
              "valueAddedTaxIncluded": true
            }
          }
        ],
        "awardID": "5a20755806ec4ff885e2278e726c8f83",
        "bidID": "6bf64eb443e54b8db51e4156558d97e0",
        "date": "2023-01-01T00:00:00+02:00"
      }
    ],
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "agreement_first_document.doc",
        "format": "application/msdoc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/79e167453f5a401fb8cf408f6e3f2580?Signature=23bscymQYesYOw%2FZpHY7funx9xxU82w8GGZQSF0jYm1mwr9no2e7NHI2oej4xx%2B9tkhdeyxVjXB4ye6L4Kg9DQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "id": "5402687eab9d4ebc9b0f425d9ba8a080",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      },
      {
        "title_en": "Title of Document",
        "description_en": "Description of Document",
        "language": "en",
        "id": "325b32fa41d84a6e9f5cd2a1971255dc",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "agreement_second_document.doc",
        "format": "application/msdoc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/19d8247422d744baac8d227f47d1c28c?Signature=6LIfqdeMREwFZds4MdkMI5It2QgX%2FidPLIeMnHRAZQ2dlg%2FqGMM49QlTd0JISwsMdCs9BVxTYfGxYaUyeF86Ag%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ]
  }
}

