GET /api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/agreements/85b5a0dd7da441c08eb664e2412cc5d5/documents HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "en", 
      "title": "agreement_second_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c2d35e83048c4c27961b80738e51e1d5?KeyID=a8968c46&Signature=0d%2Fi2oukjLG2fU9f8ojsNFHRfh0GBUaVCTLHe6K1rALLul3y6DCnRnRe%2FmNwRfYTuOUfzdinuXmywXVQmN1mDA%253D%253D", 
      "format": "application/msword", 
      "title_en": "Title of Document", 
      "description_en": "Description of Document", 
      "datePublished": "2020-09-08T01:00:00+03:00", 
      "documentOf": "tender", 
      "id": "cdc80289d5c4488595054c8cea9aef2f", 
      "dateModified": "2020-09-08T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "agreement_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a72ff80db95f4c2ea13ec42a383db5b6?KeyID=a8968c46&Signature=uY5Ns6Y%2FFzQHBWcJ5MLpt%2FVslUibSPjnyOIPpWFCAWRBPYausxDxF5uW%252BF6ano35cQ2%2Fs9XQsl%252BV49vUJjWCDg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2020-09-08T01:00:00+03:00", 
      "id": "a6633574e637461988d9b3ce20113a6a", 
      "dateModified": "2020-09-08T01:00:00+03:00"
    }
  ]
}

