GET /api/2.5/tenders/dea691b943a946a8957e9be95bc51a06/agreements/0fea7d7c4c8649f5a499885d630671f5/documents HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "6b3def02d8e044b2a003ce65d16b212a",
      "hash": "md5:00000000000000000000000000000000",
      "title": "agreement_first_document.doc",
      "format": "application/msdoc",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/79e167453f5a401fb8cf408f6e3f2580?Signature=23bscymQYesYOw%2FZpHY7funx9xxU82w8GGZQSF0jYm1mwr9no2e7NHI2oej4xx%2B9tkhdeyxVjXB4ye6L4Kg9DQ%3D%3D&KeyID=a8968c46",
      "datePublished": "2023-01-01T00:00:00+02:00",
      "dateModified": "2023-01-01T00:00:00+02:00",
      "documentOf": "tender"
    },
    {
      "id": "d364676c691744899b1a80f035be06f4",
      "hash": "md5:00000000000000000000000000000000",
      "title": "agreement_second_document.doc",
      "title_en": "Title of Document",
      "description_en": "Description of Document",
      "format": "application/msdoc",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/19d8247422d744baac8d227f47d1c28c?Signature=6LIfqdeMREwFZds4MdkMI5It2QgX%2FidPLIeMnHRAZQ2dlg%2FqGMM49QlTd0JISwsMdCs9BVxTYfGxYaUyeF86Ag%3D%3D&KeyID=a8968c46",
      "datePublished": "2023-01-01T00:00:00+02:00",
      "dateModified": "2023-01-01T00:00:00+02:00",
      "language": "en",
      "documentOf": "tender"
    }
  ]
}

