PUT /api/2.5/tenders/37cb590308a242a9836f51a9994c7492/cancellations/137233c6e7a64b4f89e93ad12e8849af/documents/f9f4f063679a4a05b1b075525e8b3834?acc_token=fbb49b806b484733bc09390b0e01078d HTTP/1.0
Authorization: Bearer broker
Content-Length: 324
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Notice-2.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/79e167453f5a401fb8cf408f6e3f2580?Signature=%2BmP0YLnClR4YuVDd7GOve5wUlt8s7y9MfbVRAR1Coq6OB%2FruCITNZWuptK4kSxNXTN73fSxGjIq1DfFDWaMDAA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "f9f4f063679a4a05b1b075525e8b3834",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice-2.pdf",
    "description": "Changed description",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/79e167453f5a401fb8cf408f6e3f2580?Signature=23bscymQYesYOw%2FZpHY7funx9xxU82w8GGZQSF0jYm1mwr9no2e7NHI2oej4xx%2B9tkhdeyxVjXB4ye6L4Kg9DQ%3D%3D&KeyID=a8968c46",
    "datePublished": "2021-03-16T00:00:01+02:00",
    "dateModified": "2021-03-16T00:00:01+02:00",
    "documentOf": "tender",
    "language": "uk"
  }
}

