POST /api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/cancellations/f35b5fe67e064722b22ccf511efe711b/documents?acc_token=1e40f3cf3fd64b8ebca3076b70a86e71 HTTP/1.0
Authorization: Bearer broker
Content-Length: 142
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/cancellations/f35b5fe67e064722b22ccf511efe711b/documents/4a6e26bf559346d0b4ca0298bf8a61d0
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/42966c9ed4bf41e29e79e88238661d7e?KeyID=a8968c46&Signature=4SN%252B%2F%2FGuneBentek1A2hF8Wo4Lmn19B%252BVrmZZkMNf3XXG3ohrxrS0jIYx4xbOx%2FT6aFhFSQrMMDZY%252Br%2F94oGDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2020-05-15T01:00:01+03:00", 
    "id": "4a6e26bf559346d0b4ca0298bf8a61d0", 
    "dateModified": "2020-05-15T01:00:01+03:00"
  }
}

