POST /api/2.5/tenders/37cb590308a242a9836f51a9994c7492/bids/fa412b9bcd92484d9f8871b0ee0df130/qualification_documents?acc_token=c0c98c22f5594c6e99ba094d5d9a9b63 HTTP/1.0
Authorization: Bearer broker
Content-Length: 158
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="qualification_document.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/37cb590308a242a9836f51a9994c7492/bids/fa412b9bcd92484d9f8871b0ee0df130/qualification_documents/13a99a17b16648f5940131d68841cfc1
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "13a99a17b16648f5940131d68841cfc1",
    "hash": "md5:00000000000000000000000000000000",
    "title": "qualification_document.pdf",
    "format": "application/pdf",
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/37cb590308a242a9836f51a9994c7492/bids/fa412b9bcd92484d9f8871b0ee0df130/qualification_documents/13a99a17b16648f5940131d68841cfc1?download=7cd719b4e43044d99c422791d2008a68",
    "datePublished": "2021-03-16T00:00:00+02:00",
    "dateModified": "2021-03-16T00:00:00+02:00",
    "documentOf": "tender",
    "confidentiality": "public",
    "language": "uk"
  }
}

