POST /api/2.5/tenders/a00c3352983c4c63b2d094cbbe220422/bids/5b7faf5a4e7a49959ae66a4113b80982/documents?acc_token=9799b93b281448ac9708706fc3893f31 HTTP/1.0
Authorization: Bearer broker
Content-Length: 328
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Proposal.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/de9be10474b54e909bf8f48198108df6?Signature=7FIL2IiGavE7qClzXkGABN%2BWd5zhCRjt7uAGQwY7KUMl%2FNAFBt6EoHJeqwltWWa%2FQ9zJLU8%2BzdxX1Dq21PWkAw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/a00c3352983c4c63b2d094cbbe220422/bids/5b7faf5a4e7a49959ae66a4113b80982/documents/d028a2b0104744ea8bceef09934b7e09

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "Proposal.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/de9be10474b54e909bf8f48198108df6?Signature=xjnEVoDUtHK61yxKjLmvLdr27woQeiGDK32aBgDUKaOVk1OvM4ND4p%2F4lAQitRRcYP5zuFi%2FZn6cvz%2BO7z3QAw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "d028a2b0104744ea8bceef09934b7e09",
    "confidentiality": "public",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00"
  }
}

