PUT /api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/544359015fd047a8b79fa81bda0889fc/qualification_documents/a5f1ac003eec457482d9811ca0749c6b?acc_token=7ba8d77208c04422b161882dc2c4b5c2 HTTP/1.0
Authorization: Bearer broker
Content-Length: 159
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="qualification_document2.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "qualification_document2.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/544359015fd047a8b79fa81bda0889fc/qualification_documents/a5f1ac003eec457482d9811ca0749c6b?download=ec5c53daa6e34d7d90cd4cde573c3ed3", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2020-09-08T01:00:00+03:00", 
    "id": "a5f1ac003eec457482d9811ca0749c6b", 
    "dateModified": "2020-09-08T01:00:00+03:00"
  }
}

