POST /api/2.5/tenders/ae2274f0782747918bb1e96f34787c24/bids/6635c3c3fd2a42e5bcdac5aa9882fdf2/documents?acc_token=ace4a353c5094bfaa3c4d20485941548 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Proposal_top_secrets.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c24f82881bbb413090880c729b494aae?Signature=uWM9T3bpxBTsr869wsSriD1jhAOcFEwC96qXPQvo40TVCL0v0Xrb4vhYFei5aD3W1DpdXSleCa%2F9f2BBhJ%2BzCg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ae2274f0782747918bb1e96f34787c24/bids/6635c3c3fd2a42e5bcdac5aa9882fdf2/documents/4863fce439934b57a69fcc1076186e70

{
  "data": {
    "confidentiality": "public",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Proposal_top_secrets.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c24f82881bbb413090880c729b494aae?Signature=app%2BiiGZXRYRV6OZMZaFCDWjMMMDFli1za4%2Fa0SLVWvBPCedtbCeWYiKlYKje%2F2qExFpqXRWRVTawYA6oZQ8Bw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "4863fce439934b57a69fcc1076186e70",
    "datePublished": "2027-01-01T00:00:00+02:00",
    "dateModified": "2027-01-01T00:00:00+02:00"
  }
}

