POST /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Authorization: Bearer broker
Content-Length: 2609
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "profile": "655360-30230000-889652-40000777", 
    "status": "draft", 
    "milestones": [
      {
        "code": "prepayment", 
        "sequenceNumber": 0, 
        "title": "signingTheContract", 
        "duration": {
          "type": "banking", 
          "days": 2
        }, 
        "percentage": 45.55, 
        "type": "financing", 
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      }, 
      {
        "code": "postpayment", 
        "sequenceNumber": 0, 
        "title": "deliveryOfGoods", 
        "duration": {
          "type": "calendar", 
          "days": 900
        }, 
        "percentage": 54.45, 
        "type": "financing"
      }
    ], 
    "mainProcurementCategory": "goods", 
    "tenderPeriod": {
      "endDate": "2020-05-15T01:00:00+03:00"
    }, 
    "title": "Комп’ютерне обладнання", 
    "items": [
      {
        "description": "Комп’ютерне обладнання", 
        "classification": {
          "scheme": "ДК021", 
          "id": "44617100-9", 
          "description": "Cartons"
        }, 
        "additionalClassifications": [
          {
            "scheme": "INN", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2020-05-03T01:00:00+03:00", 
          "endDate": "2020-05-06T01:00:00+03:00"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "priceQuotation", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f0e96a96b177485fa02f9d18fa14e3d2
{
  "access": {
    "transfer": "ffdeed6ba59743d99d1edb70e48d98d0", 
    "token": "de5afae29ca745839a8c09f21f0ddf41"
  }, 
  "data": {
    "procurementMethod": "open", 
    "status": "draft", 
    "milestones": [
      {
        "code": "prepayment", 
        "sequenceNumber": 0, 
        "title": "signingTheContract", 
        "duration": {
          "type": "banking", 
          "days": 2
        }, 
        "percentage": 45.55, 
        "type": "financing", 
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      }, 
      {
        "code": "postpayment", 
        "sequenceNumber": 0, 
        "title": "deliveryOfGoods", 
        "duration": {
          "type": "calendar", 
          "days": 900
        }, 
        "percentage": 54.45, 
        "type": "financing", 
        "id": "14e69daf47a4471ea3ef8d1461aea38c"
      }
    ], 
    "mainProcurementCategory": "goods", 
    "tenderPeriod": {
      "startDate": "2020-05-01T01:00:00+03:00", 
      "endDate": "2020-05-15T01:00:00+03:00"
    }, 
    "title": "Комп’ютерне обладнання", 
    "items": [
      {
        "description": "Комп’ютерне обладнання", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "INN", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2020-05-03T01:00:00+03:00", 
          "endDate": "2020-05-06T01:00:00+03:00"
        }, 
        "id": "d086668e07714e9bace75cbc281d77cb", 
        "quantity": 5.0
      }
    ], 
    "procurementMethodType": "priceQuotation", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2020-05-01T01:00:00+03:00", 
    "profile": "655360-30230000-889652-40000777", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "awardCriteria": "lowestCost", 
    "owner": "broker", 
    "dateModified": "2020-05-01T01:00:00+03:00", 
    "id": "f0e96a96b177485fa02f9d18fa14e3d2", 
    "tenderID": "UA-2020-05-01-000001"
  }
}

