GET /api/2.5/tenders/db4fb6143a5f45b6953e8f010ed8064e/documents HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0897ce4ba17b4ea2a43e11565ebc9bbe?KeyID=a8968c46&Signature=SWZWDphzyXVrcz%252Be%2FfXgHcekUsqHQvSQSWMu%252BmH0Lwznt8ENExLjHT8UNrijpUFjkjMnFXcOB9IBuQ4WOtoDBw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2020-05-01T01:00:01+03:00", 
      "id": "e6d5cc3da78e4c67a6852b122049974f", 
      "dateModified": "2020-05-01T01:00:01+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/05b0d65cf15d46708161e6e0921e5c0b?KeyID=a8968c46&Signature=%252BQ9bByohdJRHWPSOzLhKTQ8Ltbog6s6UL2VaWt7O758QSaOo0XeYqe6j43yE6RssXzDlheYdrEFw55JsrBdCDQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2020-05-01T01:00:01+03:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "8f9bc7ee6d724b70b462e09ca10d1993", 
      "dateModified": "2020-05-01T01:00:01+03:00"
    }
  ]
}

