stages:
  - build
  - security
  - deploy
  - check
  - test

include:
  # build and deploy stages
  - project: 'cdb/openprocurement.api-ci'
    ref: 'master'
    file: '.gitlab-ci.api.yml'
  # check and test stages
  - local: '.gitlab/ci/check.yml'
  - local: '.gitlab/ci/test.yml'
