GET /api/2.5/agreements?opt_fields=status,procuringEntity HTTP/1.0
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "status": "active",
      "procuringEntity": {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037256",
          "legalName": "Назва організації"
        },
        "address": {
          "countryName": "Україна",
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000",
          "email": "aa@aa.com"
        },
        "kind": "defense"
      },
      "dateModified": "2023-10-10T01:00:00+03:00",
      "id": "84e5a3fd2a244df7af98316bcb7e4b5a"
    }
  ],
  "next_page": {
    "offset": "1696888800.0000000009.1.dd978d2389a7000bc2c2cc0983fdc9c9",
    "path": "/api/2.5/agreements?opt_fields=procuringEntity%2Cstatus&offset=1696888800.0000000009.1.dd978d2389a7000bc2c2cc0983fdc9c9",
    "uri": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/agreements?opt_fields=procuringEntity%2Cstatus&offset=1696888800.0000000009.1.dd978d2389a7000bc2c2cc0983fdc9c9"
  }
}

