GET /api/2.5/tenders/94170d1f620a487e8f4ffcc37ee8f2df/awards HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c4087a504904433ca2224fa31614bd0e?KeyID=a8968c46&Signature=bjX%252B5FOq9uzfpKCEuieeVkBabMkG2M4HmQHiQ4lE6xwrl78acB46%2F7DHQyOyfgB12o9hRlj3tWu0gJFe5uqgCA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2020-05-01T01:00:00+03:00", 
          "id": "5eebee63bc33464f870b39c9874f1b15", 
          "dateModified": "2020-05-01T01:00:00+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2020-05-01T01:00:00+03:00", 
        "endDate": "2020-05-01T01:00:01+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "scale": "micro", 
          "name": "ДКП «Школяр»", 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "Вінницька область", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "697e150f2b9442f49714a71c74f37db2", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2020-05-01T01:00:01+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e55bd0cbdb214899a3bc41c036451dc6?KeyID=a8968c46&Signature=sKar7aqK3NIsXwWy8a4Wgfd2rgrqXOPf7EZolZwKlkRrUuvGM0xBj52UJe0B1mf5kYV%252BFVNg7qU8SkODumFUCA%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2020-05-01T01:00:01+03:00", 
              "id": "ccf172362f3e4e69853506fcf14d0cb7", 
              "dateModified": "2020-05-01T01:00:01+03:00"
            }
          ], 
          "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "Вінницька область", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "Недостатньо інформації", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2020-05-01T01:00:01+03:00", 
          "tendererActionDate": "2020-05-01T01:00:01+03:00", 
          "dateSubmitted": "2020-05-01T01:00:01+03:00", 
          "complaintID": "UA-2020-05-01-000001.5", 
          "date": "2020-05-01T01:00:01+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "81b1c6e4fb1e416d9ed8c9aca0ab08b5"
        }, 
        {
          "status": "resolved", 
          "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
          "title": "Недостатньо інформації", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "Вінницька область", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2020-05-01T01:00:01+03:00", 
          "dateSubmitted": "2020-05-01T01:00:01+03:00", 
          "complaintID": "UA-2020-05-01-000001.6", 
          "date": "2020-05-01T01:00:01+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "7bb4b99511cb40e8bb0ac2c4731a1733"
        }, 
        {
          "status": "resolved", 
          "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
          "title": "Недостатньо інформації", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "Вінницька область", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2020-05-01T01:00:01+03:00", 
          "dateSubmitted": "2020-05-01T01:00:01+03:00", 
          "complaintID": "UA-2020-05-01-000001.7", 
          "date": "2020-05-01T01:00:01+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "2f12ac4878114b69b562a52d95aa86fb"
        }, 
        {
          "status": "resolved", 
          "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
          "title": "Недостатньо інформації", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "Вінницька область", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2020-05-01T01:00:01+03:00", 
          "dateSubmitted": "2020-05-01T01:00:01+03:00", 
          "complaintID": "UA-2020-05-01-000001.8", 
          "date": "2020-05-01T01:00:01+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "354f93df82d24dc49a0e6db3034ae976"
        }
      ], 
      "id": "364af56690df4704aa730f1266eca60e"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2020-05-01T01:00:00+03:00", 
        "endDate": "2020-05-01T01:00:01+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "scale": "micro", 
          "name": "Державне управління справами", 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "d850cb39e84048e184629c29800ef1cb", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2020-05-01T01:00:00+03:00", 
      "id": "d4bb74fe816c4fcdaeebdb1c1f1f1c1c"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Cancellation_Reason.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/202da44fbd4a476ab11b90bd9ced7836?KeyID=a8968c46&Signature=rehA9N6KolRKnxG5ygjtgzct88rEE5YUxJJ7HaBbKiGVgFdmfyPPUMqb%2Fi43kxXqgQYOtAsGveBR1aBura4kBw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2020-05-01T01:00:00+03:00", 
          "id": "4344cd13743b4c93bf4c5750a99b40e2", 
          "dateModified": "2020-05-01T01:00:00+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2020-05-01T01:00:00+03:00", 
        "endDate": "2020-05-01T01:00:01+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "scale": "micro", 
          "name": "Державне управління справами", 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "d850cb39e84048e184629c29800ef1cb", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2020-05-01T01:00:01+03:00", 
      "id": "c155ff07d1a54734b7e9c5d63567f47b"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2020-05-01T01:00:00+03:00", 
        "endDate": "2020-05-01T01:00:01+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "scale": "micro", 
          "name": "ДКП «Школяр»", 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "Вінницька область", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "a38e4ff74331493a9edc8f777960b3f0", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2020-05-01T01:00:01+03:00", 
      "id": "8fc90d5f0964459cac72318786f73db4"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2020-05-01T01:00:01+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "scale": "micro", 
          "name": "ДКП «Школяр»", 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "Вінницька область", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "697e150f2b9442f49714a71c74f37db2", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2020-05-01T01:00:01+03:00", 
      "id": "d6a67dd62fe240bab54e834805ee8644"
    }
  ]
}

