POST /api/2.5/plans?opt_pretty=1 HTTP/1.0
Authorization: Bearer broker
Content-Length: 1898
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "draft", 
    "buyers": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "111983", 
          "legalName": "ДП Державне Управління Справами"
        }, 
        "name": "ДУС"
      }
    ], 
    "classification": {
      "scheme": "ДК021", 
      "description": "Seeds", 
      "id": "03111000-2"
    }, 
    "items": [
      {
        "description": "Насіння гірчиці", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Mustard seeds", 
          "id": "03111600-8"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "01.11.92", 
            "description": "Насіння гірчиці"
          }
        ], 
        "deliveryDate": {
          "endDate": "2019-11-09T01:00:00+03:00"
        }, 
        "unit": {
          "code": "KGM", 
          "name": "кг"
        }, 
        "quantity": 1000
      }
    ], 
    "budget": {
      "breakdown": [
        {
          "description": "Breakdown other description.", 
          "value": {
            "currency": "UAH", 
            "amount": 1500
          }, 
          "title": "other"
        }
      ], 
      "amountNet": 12222, 
      "description": "budget_description", 
      "period": {
        "startDate": "2020-01-01T00:00:00", 
        "endDate": "2020-12-31T00:00:00"
      }, 
      "project": {
        "name": "proj_name", 
        "id": "123"
      }, 
      "currency": "UAH", 
      "amount": 10000, 
      "id": "12303111000-2"
    }, 
    "additionalClassifications": [
      {
        "scheme": "КЕКВ", 
        "id": "1", 
        "description": "-"
      }
    ], 
    "procuringEntity": {
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "111111", 
        "legalName": "ДП Центральний закупівельний орган №1"
      }, 
      "name": "ЦЗО №1"
    }, 
    "tender": {
      "procurementMethod": "open", 
      "procurementMethodType": "belowThreshold", 
      "tenderPeriod": {
        "startDate": "2019-11-01T01:00:00+03:00"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/plans/77cf582ab7284fb1a0e748ea7fe9033f
{
  "access": {
    "transfer": "eefdeb1e2e984f22a62ddb137dceba45", 
    "token": "b1fb3396cb2041f9812f66f4c4ddd2c7"
  }, 
  "data": {
    "status": "draft", 
    "buyers": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "111983", 
          "legalName": "ДП Державне Управління Справами"
        }, 
        "name": "ДУС"
      }
    ], 
    "classification": {
      "scheme": "ДК021", 
      "description": "Seeds", 
      "id": "03111000-2"
    }, 
    "items": [
      {
        "description": "Насіння гірчиці", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Mustard seeds", 
          "id": "03111600-8"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "01.11.92", 
            "description": "Насіння гірчиці"
          }
        ], 
        "deliveryDate": {
          "endDate": "2019-11-09T01:00:00+03:00"
        }, 
        "id": "20af24c61dc7451a9205eca2dac56d65", 
        "unit": {
          "code": "KGM", 
          "name": "кг"
        }, 
        "quantity": 1000.0
      }
    ], 
    "planID": "UA-P-2019-05-02-000001", 
    "budget": {
      "breakdown": [
        {
          "title": "other", 
          "description": "Breakdown other description.", 
          "value": {
            "currency": "UAH", 
            "amount": 1500.0
          }, 
          "id": "f0d2c36b24ed47169ca75a7803897a2d"
        }
      ], 
      "amountNet": 12222.0, 
      "description": "budget_description", 
      "period": {
        "startDate": "2020-01-01T00:00:00+02:00", 
        "endDate": "2020-12-31T00:00:00+02:00"
      }, 
      "project": {
        "id": "123", 
        "name": "proj_name"
      }, 
      "currency": "UAH", 
      "amount": 10000.0, 
      "id": "12303111000-2"
    }, 
    "datePublished": "2019-05-02T04:00:00+03:00", 
    "tender": {
      "procurementMethod": "open", 
      "procurementMethodType": "belowThreshold", 
      "tenderPeriod": {
        "startDate": "2019-11-01T01:00:00+03:00"
      }
    }, 
    "additionalClassifications": [
      {
        "scheme": "КЕКВ", 
        "id": "1", 
        "description": "-"
      }
    ], 
    "procuringEntity": {
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "111111", 
        "legalName": "ДП Центральний закупівельний орган №1"
      }, 
      "name": "ЦЗО №1"
    }, 
    "owner": "broker", 
    "dateModified": "2019-05-02T04:00:00+03:00", 
    "id": "77cf582ab7284fb1a0e748ea7fe9033f"
  }
}

