POST /api/2.5/plans?opt_pretty=1 HTTP/1.0
Authorization: Bearer broker
Content-Length: 3049
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "rationale": {
      "description": "Недостатньо змістовне обгрунтування"
    },
    "tender": {
      "procurementMethod": "open",
      "procurementMethodType": "belowThreshold",
      "tenderPeriod": {
        "startDate": "2023-10-17T00:00:00+02:00"
      }
    },
    "items": [
      {
        "deliveryDate": {
          "endDate": "2023-10-25T00:00:00+02:00"
        },
        "deliveryAddress": {
          "countryName": "Україна",
          "postalCode": "79000",
          "region": "м. Київ",
          "locality": "м. Київ",
          "streetAddress": "вул. Банкова 1"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "01.11.92",
            "description": "Насіння гірчиці"
          }
        ],
        "unit": {
          "code": "KGM",
          "name": "кг"
        },
        "classification": {
          "scheme": "ДК021",
          "description": "Mustard seeds",
          "id": "03111600-8"
        },
        "quantity": 1000,
        "description": "Насіння гірчиці"
      }
    ],
    "classification": {
      "scheme": "ДК021",
      "description": "Seeds",
      "id": "03111000-2"
    },
    "additionalClassifications": [
      {
        "scheme": "КЕКВ",
        "id": "1",
        "description": "-"
      }
    ],
    "procuringEntity": {
      "identifier": {
        "scheme": "UA-EDR",
        "id": "111111",
        "legalName": "ДП Центральний закупівельний орган №1"
      },
      "name": "ЦЗО №1",
      "address": {
        "countryName": "Україна",
        "postalCode": "01220",
        "region": "м. Київ",
        "locality": "м. Київ",
        "streetAddress": "вул. Банкова, 1"
      },
      "kind": "central"
    },
    "buyers": [
      {
        "identifier": {
          "scheme": "UA-EDR",
          "id": "111983",
          "legalName": "ДП Державне Управління Справами"
        },
        "name": "ДУС",
        "address": {
          "countryName": "Україна",
          "postalCode": "01220",
          "region": "м. Київ",
          "locality": "м. Київ",
          "streetAddress": "вул. Банкова, 11, корпус 1"
        },
        "kind": "general"
      }
    ],
    "budget": {
      "project": {
        "name": "proj_name",
        "id": "123"
      },
      "amount": 10000,
      "amountNet": 12222,
      "currency": "UAH",
      "id": "12303111000-2",
      "description": "budget_description",
      "period": {
        "startDate": "2023-01-01T00:00:00",
        "endDate": "2023-12-31T00:00:00"
      },
      "breakdown": [
        {
          "title": "other",
          "description": "Breakdown other description.",
          "value": {
            "amount": 1500,
            "currency": "UAH"
          }
        }
      ]
    },
    "status": "draft"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/plans/eb26a3adc64548c4b3aae8df399ed59f

{
  "data": {
    "status": "draft",
    "procuringEntity": {
      "id": "a6e22c1e974b428488ab4efcd3cc985b",
      "name": "ЦЗО №1",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "111111",
        "legalName": "ДП Центральний закупівельний орган №1"
      },
      "address": {
        "streetAddress": "вул. Банкова, 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "kind": "central"
    },
    "tender": {
      "procurementMethod": "open",
      "procurementMethodType": "belowThreshold",
      "tenderPeriod": {
        "startDate": "2023-10-17T00:00:00+02:00"
      }
    },
    "budget": {
      "id": "12303111000-2",
      "description": "budget_description",
      "amount": 10000.0,
      "currency": "UAH",
      "amountNet": 12222.0,
      "project": {
        "id": "123",
        "name": "proj_name"
      },
      "period": {
        "startDate": "2023-01-01T00:00:00+02:00",
        "endDate": "2023-12-31T00:00:00+02:00"
      },
      "breakdown": [
        {
          "id": "c96d28cbe3454d70a81c269d96fda2c8",
          "title": "other",
          "description": "Breakdown other description.",
          "value": {
            "amount": 1500.0,
            "currency": "UAH"
          }
        }
      ]
    },
    "classification": {
      "description": "Seeds",
      "scheme": "ДК021",
      "id": "03111000-2"
    },
    "additionalClassifications": [
      {
        "scheme": "КЕКВ",
        "id": "1",
        "description": "-"
      }
    ],
    "items": [
      {
        "id": "485533ab54674a5db2b8244e0d8e7988",
        "classification": {
          "description": "Mustard seeds",
          "scheme": "ДК021",
          "id": "03111600-8"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "01.11.92",
            "description": "Насіння гірчиці"
          }
        ],
        "unit": {
          "name": "кг",
          "code": "KGM"
        },
        "quantity": 1000.0,
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "deliveryDate": {
          "endDate": "2023-10-25T00:00:00+02:00"
        },
        "description": "Насіння гірчиці"
      }
    ],
    "buyers": [
      {
        "id": "fbb0ef9be1d54cfeaf4e89e32dc911a1",
        "name": "ДУС",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "111983",
          "legalName": "ДП Державне Управління Справами"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "kind": "general"
      }
    ],
    "rationale": {
      "description": "Недостатньо змістовне обгрунтування",
      "date": "2023-10-10T01:00:00+03:00"
    },
    "planID": "UA-P-2023-10-10-000001-a",
    "owner": "broker",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "dateCreated": "2023-10-10T01:00:00+03:00",
    "id": "eb26a3adc64548c4b3aae8df399ed59f"
  },
  "access": {
    "token": "ef8025edf3df47a9a4a0f4599f00d7a4",
    "transfer": "ec2255c4456e4be6b66841e4e1c0861a"
  }
}

