PATCH /api/2.5/plans/ccabf835a75648e5b86d7ffc168cba8f/milestones/390a85e9b9d94b89920c41dd715d8bcb?acc_token=583e6285b176451ab4f7fd7c9196bd43 HTTP/1.0
Authorization: Bearer broker
Content-Length: 226
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "met",
    "description": "Доповнений опис відповіді",
    "dueDate": "2023-10-10T01:00:07+03:00"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "390a85e9b9d94b89920c41dd715d8bcb",
    "status": "met",
    "title": "Підготовка до проведення процедури",
    "description": "Доповнений опис відповіді",
    "type": "approval",
    "dueDate": "2023-10-10T01:00:07+03:00",
    "author": {
      "id": "abd4f7ed7a0941cf949fd779278bc7b2",
      "name": "ЦЗО №1",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "111111",
        "legalName": "ДП Центральний закупівельний орган №1"
      },
      "address": {
        "streetAddress": "вул. Банкова, 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "kind": "central"
    },
    "dateModified": "2023-10-10T01:00:06+03:00",
    "owner": "broker",
    "dateMet": "2023-10-10T01:00:06+03:00"
  }
}

