PATCH /api/2.5/plans/1be4169566db4d9d931b6056c5814240?acc_token=f15e08182e584559a27c58ce66508445 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "scheduled"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "status": "scheduled",
    "procuringEntity": {
      "id": "473320227d9d4e959c81266ac1862f55",
      "name": "ЦЗО №1",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "111111",
        "legalName": "ДП Центральний закупівельний орган №1"
      },
      "address": {
        "streetAddress": "вул. Банкова, 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "kind": "central"
    },
    "tender": {
      "procurementMethod": "open",
      "procurementMethodType": "belowThreshold",
      "tenderPeriod": {
        "startDate": "2023-10-17T00:00:00+02:00"
      }
    },
    "budget": {
      "id": "12303111000-2",
      "description": "budget_description",
      "amount": 10000.0,
      "currency": "UAH",
      "amountNet": 12222.0,
      "project": {
        "id": "123",
        "name": "proj_name"
      },
      "period": {
        "startDate": "2023-01-01T00:00:00+02:00",
        "endDate": "2023-12-31T00:00:00+02:00"
      },
      "breakdown": [
        {
          "id": "9b211ce8a6a646ffb43f49e0bbf010a0",
          "title": "other",
          "description": "Breakdown other description.",
          "value": {
            "amount": 1500.0,
            "currency": "UAH"
          }
        }
      ]
    },
    "classification": {
      "description": "Seeds",
      "scheme": "ДК021",
      "id": "03111000-2"
    },
    "additionalClassifications": [
      {
        "scheme": "КЕКВ",
        "id": "1",
        "description": "-"
      }
    ],
    "planID": "UA-P-2023-10-10-000001-a",
    "items": [
      {
        "id": "80a3a54e309a4c8a8085f740da8652bc",
        "classification": {
          "description": "Mustard seeds",
          "scheme": "ДК021",
          "id": "03111600-8"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "01.11.92",
            "description": "Насіння гірчиці"
          }
        ],
        "unit": {
          "name": "кг",
          "code": "KGM"
        },
        "quantity": 1000.0,
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "deliveryDate": {
          "endDate": "2023-10-25T00:00:00+02:00"
        },
        "description": "Насіння гірчиці"
      }
    ],
    "buyers": [
      {
        "id": "e9b0fc29f3f04736be502e2a9ac44775",
        "name": "ДУС",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "111983",
          "legalName": "ДП Державне Управління Справами"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "kind": "general"
      }
    ],
    "rationale": {
      "description": "Недостатньо змістовне обгрунтування",
      "date": "2023-10-10T01:00:00+03:00"
    },
    "owner": "broker",
    "dateCreated": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:01+03:00",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "id": "1be4169566db4d9d931b6056c5814240"
  }
}

