PATCH /api/2.5/plans/395b7a73bc484239a97c959b2210442d/milestones/38af1af8923e4f2ab7bdda3b7d94c002?acc_token=583e6285b176451ab4f7fd7c9196bd43 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "met",
    "description": "Доповнений опис відповіді",
    "dueDate": "2023-10-10T01:00:07+03:00"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "38af1af8923e4f2ab7bdda3b7d94c002",
    "status": "met",
    "title": "Підготовка до проведення процедури",
    "description": "Доповнений опис відповіді",
    "type": "approval",
    "dueDate": "2023-10-10T01:00:07+03:00",
    "author": {
      "id": "73a703c6efc84140ad4e9d8a9b08b94d",
      "name": "ЦЗО №1",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "111111",
        "legalName": "ДП Центральний закупівельний орган №1"
      },
      "address": {
        "streetAddress": "вул. Банкова, 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "kind": "central"
    },
    "dateModified": "2023-10-10T01:00:06+03:00",
    "owner": "broker",
    "dateMet": "2023-10-10T01:00:06+03:00"
  }
}

