POST /api/2.5/plans/2c376a06cbf7476b8c229e6955bd8194/milestones HTTP/1.0
Authorization: Bearer broker
Content-Length: 1623
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Підготовка до проведення процедури",
    "description": "Узагальнення та аналіз отриманної інформації щодо проведення закупівель товарів, послуг (крім поточного ремонту) в інтересах замовників",
    "type": "approval",
    "author": {
      "identifier": {
        "scheme": "UA-EDR",
        "id": "111111",
        "legalName": "ДП Центральний закупівельний орган №1"
      },
      "name": "ЦЗО №1",
      "address": {
        "countryName": "Україна",
        "postalCode": "01220",
        "region": "м. Київ",
        "locality": "м. Київ",
        "streetAddress": "вул. Банкова, 1"
      },
      "kind": "central"
    },
    "dueDate": "2023-01-01T00:00:04+02:00"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/plans/2c376a06cbf7476b8c229e6955bd8194/milestones/15a9ab37fec7476aa9ef10890b9b2f4a

{
  "data": {
    "id": "15a9ab37fec7476aa9ef10890b9b2f4a",
    "title": "Підготовка до проведення процедури",
    "description": "Узагальнення та аналіз отриманної інформації щодо проведення закупівель товарів, послуг (крім поточного ремонту) в інтересах замовників",
    "type": "approval",
    "dueDate": "2023-01-01T00:00:04+02:00",
    "status": "scheduled",
    "author": {
      "id": "223cf816f2d343d2ba8d7a038fafc659",
      "name": "ЦЗО №1",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "111111",
        "legalName": "ДП Центральний закупівельний орган №1"
      },
      "address": {
        "streetAddress": "вул. Банкова, 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "kind": "central"
    },
    "dateModified": "2023-01-01T00:00:03+02:00",
    "owner": "broker"
  },
  "access": {
    "token": "e7245cb4e7ef4e5aa4252c7e90f07af2"
  }
}

