PATCH /api/2.5/tenders/c9f66fb872ea4fb9ae61feaf0933c01b/bids/6b30b2e81c3f40adaceda00b3a546154?acc_token=8a6db39829dc4a848f731e970d98c7df HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "lotValues": [
      {
        "subcontractingDetails": "ДКП «Орфей»",
        "value": {
          "amount": 500
        },
        "relatedLot": "f71d1f65bf044639a5f93937d4fddc6f"
      }
    ],
    "status": "pending"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a7acbccdf3354e2d909f8cef92bc6988",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True",
        "id": "7c5ea77cacd74cc58b9d8b2384012b11"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "bed24a74fada43719f1e49e03c3e1a82",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True",
        "id": "3497e5cb04c347ff8df079ed877d06ee"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "d3324d3016ac422490850ae535acb97e",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True",
        "id": "f1f46d3d76d444e3b7cdd14628d397a3"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "cec5d30b94a840419796e61f222e7c01",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True",
        "id": "bcd3c435893447239e51300c5450474f"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "ad6509e20bdf4a929e5a05ed2185efc0",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True",
        "id": "be41d8d523954c3cb7ee165be8a440d8"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "721a64fdf1b94caebc7e84e7f7389a2c",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True",
        "id": "a90b0f98bd7d4adf9ea4b234b3f6559d"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "eaaf07c3fdc94dcfbb5ab2c3a5cdc5a2",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True",
        "id": "992894bed4294547b5c95d001c0d1536"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a7ab52941926496292fd8d67e7b9229d",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True",
        "id": "7082d118128d462d8ccaab544baa7f80"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "96466398117e42988163332503053c56",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True",
        "id": "75c6cee93135445c83e46fe4b58c971b"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "96341b49548d40c184b205703ed10f4e",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True",
        "id": "f3c2ad75567a471b99b0babfb1175127"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "c6f7bd53e621435484dd7f1ab07cc3b9",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True",
        "id": "3a97faa3d5db4c87bbc3c95862e90c7e"
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "scale": "micro",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        }
      }
    ],
    "status": "pending",
    "id": "6b30b2e81c3f40adaceda00b3a546154",
    "date": "2023-10-10T01:00:00+03:00",
    "lotValues": [
      {
        "relatedLot": "f71d1f65bf044639a5f93937d4fddc6f",
        "status": "pending",
        "date": "2023-10-10T01:00:00+03:00",
        "subcontractingDetails": "ДКП «Орфей»",
        "value": {
          "currency": "UAH",
          "valueAddedTaxIncluded": true,
          "amount": 6068.55,
          "amountPerformance": 1382.96,
          "yearlyPaymentsPercentage": 0.87,
          "annualCostsReduction": [
            200,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000,
            1000
          ],
          "contractDuration": {
            "years": 7,
            "days": 0
          }
        }
      }
    ],
    "selfQualified": true
  }
}

