PATCH /api/2.5/tenders/db8f78603c144a8aac15730f9c763584/bids/c036a6fb3127425ca2dc1bd343aad078?acc_token=1eefabf7d7e741df9f88509718bac900 HTTP/1.0
Authorization: Bearer broker
Content-Length: 124
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "45d538b502bd4124bff52a374958e9ea", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "45d538b502bd4124bff52a374958e9ea", 
        "date": "2020-05-15T01:00:00+03:00", 
        "status": "pending", 
        "value": {
          "yearlyPaymentsPercentage": 0.9, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 9802.6, 
          "contractDuration": {
            "days": 0, 
            "years": 7
          }, 
          "amountPerformance": 2031.2, 
          "annualCostsReduction": [
            700.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0
          ]
        }
      }
    ], 
    "id": "c036a6fb3127425ca2dc1bd343aad078", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "Львівська область", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2020-05-15T01:00:00+03:00", 
    "selfQualified": true
  }
}

