POST /api/2.5/tenders/db8f78603c144a8aac15730f9c763584/lots?acc_token=cf69efce7aca41c2b952f04d86d7fb90 HTTP/1.0
Authorization: Bearer broker
Content-Length: 175
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "fundingKind": "other", 
    "description": "Опис Лот №1", 
    "minimalStepPercentage": 0.006, 
    "title": "Лот №1"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/db8f78603c144a8aac15730f9c763584/lots/45d538b502bd4124bff52a374958e9ea
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "fundingKind": "other", 
    "title": "Лот №1", 
    "auctionPeriod": {
      "shouldStartAfter": "2020-07-20T00:00:00+02:00"
    }, 
    "minValue": {
      "currency": "UAH", 
      "amount": 0.0, 
      "valueAddedTaxIncluded": true
    }, 
    "minimalStepPercentage": 0.006, 
    "yearlyPaymentsPercentageRange": 0.8, 
    "date": "2020-05-15T01:00:00+03:00", 
    "id": "45d538b502bd4124bff52a374958e9ea"
  }
}

