PATCH /api/2.5/tenders/8a0700259bce4187b9c2cee3b9167b19/lots/ae36b7ca7b4a44d8b3c015a3e4043f4f?acc_token=4ce0e72a69954a87b19385c16717eecc HTTP/1.0
Authorization: Bearer broker
Content-Length: 39
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "minValue": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "ae36b7ca7b4a44d8b3c015a3e4043f4f",
    "title": "Лот №2",
    "description": "Опис Лот №2",
    "date": "2021-03-16T00:00:00+02:00",
    "status": "active",
    "minValue": {
      "amount": 0.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "minimalStepPercentage": 0.006,
    "fundingKind": "other",
    "yearlyPaymentsPercentageRange": 0.8
  }
}

