GET /api/2.5/tenders/c9f66fb872ea4fb9ae61feaf0933c01b HTTP/1.0
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "title_en": "Services in school canteens",
    "date": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "dateCreated": "2023-10-10T01:00:00+03:00",
    "tenderID": "UA-2023-10-10-000001-a",
    "owner": "broker",
    "title": "Послуги шкільних їдалень",
    "mainProcurementCategory": "services",
    "procurementMethod": "open",
    "awardCriteria": "ratedCriteria",
    "submissionMethod": "electronicAuction",
    "procurementMethodType": "esco",
    "status": "draft",
    "minimalStepPercentage": 0.006,
    "minValue": {
      "amount": 0.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "yearlyPaymentsPercentageRange": 0.8,
    "NBUdiscountRate": 0.22986,
    "fundingKind": "other",
    "procuringEntity": {
      "name": "ЗОСШ #10 м.Вінниці",
      "address": {
        "streetAddress": "вул. Стахурського. 22",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21027",
        "countryName": "Україна"
      },
      "name_en": "School #10 of Vinnytsia",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "21725150",
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\"",
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\""
      },
      "contactPoint": {
        "name": "Куца Світлана Валентинівна",
        "telephone": "+380432465302",
        "url": "http://sch10.edu.vn.ua/",
        "name_en": "Kutsa Svitlana V.",
        "availableLanguage": "uk"
      },
      "kind": "general"
    },
    "lots": [
      {
        "title": "Лот №1",
        "description": "Опис Лот №1",
        "status": "active",
        "id": "f71d1f65bf044639a5f93937d4fddc6f",
        "date": "2023-10-10T01:00:00+03:00",
        "minValue": {
          "amount": 0.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "minimalStepPercentage": 0.006,
        "fundingKind": "other",
        "yearlyPaymentsPercentageRange": 0.8
      },
      {
        "title": "Лот №2",
        "description": "Опис Лот №2",
        "status": "active",
        "id": "aaf17a73e8404d39916b9c992d5bae3a",
        "date": "2023-10-10T01:00:00+03:00",
        "minValue": {
          "amount": 0.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "minimalStepPercentage": 0.006,
        "fundingKind": "other",
        "yearlyPaymentsPercentageRange": 0.8
      }
    ],
    "items": [
      {
        "id": "6ddbb7da4ee64de08a3d8cf5d9f4dd15",
        "description": "Послуги шкільних їдалень",
        "description_en": "Services in school canteens",
        "classification": {
          "description": "Test",
          "scheme": "ДК021",
          "id": "37810000-9"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "relatedLot": "f71d1f65bf044639a5f93937d4fddc6f"
      },
      {
        "id": "9268a2d304c142009c039a17de12f181",
        "description": "Послуги шкільних їдалень",
        "description_en": "Services in school canteens",
        "classification": {
          "description": "Test",
          "scheme": "ДК021",
          "id": "37810000-9"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "relatedLot": "aaf17a73e8404d39916b9c992d5bae3a"
      }
    ],
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "type": "financing",
        "code": "prepayment",
        "percentage": 45.55,
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 0
      },
      {
        "id": "47095c6c25b240488e0bcf8fa49286a8",
        "title": "deliveryOfGoods",
        "type": "financing",
        "code": "postpayment",
        "percentage": 54.45,
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 0
      }
    ],
    "tenderPeriod": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2023-11-10T00:00:00+02:00"
    },
    "enquiryPeriod": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2023-10-31T00:00:00+02:00",
      "clarificationsUntil": "2023-11-03T00:00:00+02:00",
      "invalidationDate": "2023-10-10T01:00:00+03:00"
    },
    "complaintPeriod": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2023-11-06T00:00:00+02:00"
    },
    "id": "c9f66fb872ea4fb9ae61feaf0933c01b"
  },
  "config": {
    "hasAuction": true,
    "hasAwardingOrder": true,
    "hasValueRestriction": true,
    "valueCurrencyEquality": true,
    "hasPrequalification": true,
    "minBidsNumber": 2,
    "hasPreSelectionAgreement": false,
    "hasTenderComplaints": true,
    "hasAwardComplaints": true,
    "hasCancellationComplaints": true,
    "restricted": false
  }
}

