PATCH /api/2.5/tenders/bb8949e735294cbaa864bd3bc68a1e5f/cancellations/b8df861cb4fb4cc89dede539bbfda71f?acc_token=d3c6750ff65148df856b59e65feba396 HTTP/1.0
Authorization: Bearer broker
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "b8df861cb4fb4cc89dede539bbfda71f",
    "status": "active",
    "date": "2023-01-01T00:00:03+02:00",
    "reasonType": "expensesCut",
    "reason": "cancellation reason",
    "cancellationOf": "tender",
    "documents": [
      {
        "description": "Changed description",
        "id": "528099b752024dd9962c6648e44d19d3",
        "datePublished": "2023-01-01T00:00:03+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Notice.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bb8949e735294cbaa864bd3bc68a1e5f/cancellations/b8df861cb4fb4cc89dede539bbfda71f/documents/528099b752024dd9962c6648e44d19d3?download=959d70778a9f4662bc47e36354ae60c7",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:03+02:00"
      },
      {
        "description": "Changed description",
        "id": "528099b752024dd9962c6648e44d19d3",
        "datePublished": "2023-01-01T00:00:03+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Notice-2.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bb8949e735294cbaa864bd3bc68a1e5f/cancellations/b8df861cb4fb4cc89dede539bbfda71f/documents/528099b752024dd9962c6648e44d19d3?download=456ee005dc5c4af0a04ba389e782dd33",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:03+02:00"
      }
    ]
  }
}

