GET /api/2.5/tenders/3f38940af1314712ac29867b3e4eced4/bids?acc_token=3f07ab10456e4f519a3cf51c24d19c80 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "id": "b8994ac5b9f340da9a0620b8a7b2d8fc",
      "date": "2024-01-01T00:00:01+02:00",
      "submissionDate": "2024-01-01T00:00:01+02:00",
      "documents": [
        {
          "confidentiality": "public",
          "documentType": "proposal",
          "id": "8eeccb3aef1d4373844028cddf65bc15",
          "datePublished": "2024-01-01T00:00:01+02:00",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal.p7s",
          "format": "sign/p7s",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7abe246945c74a798ef5abd6f6c3eacc?Signature=ix%2BAtoVHTr7n%2BtlzacHRzW5MXhg6cNDGh1H06A%2B%2Be5QADUguPxtLtZv0azfvgcsDePmEaAiMOiXEgsOVUNfIDw%3D%3D&KeyID=a8968c46",
          "documentOf": "tender",
          "dateModified": "2024-01-01T00:00:01+02:00",
          "language": "uk"
        }
      ],
      "tenderers": [
        {
          "name": "Державне управління справами",
          "identifier": {
            "scheme": "UA-IPN",
            "id": "00037256",
            "uri": "http://www.dus.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Банкова, 11, корпус 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "01220",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Державне управління справами",
            "telephone": "+0440000000"
          },
          "scale": "micro"
        }
      ],
      "value": {
        "amount": 459.0,
        "currency": "UAH",
        "valueAddedTaxIncluded": true
      },
      "requirementResponses": [
        {
          "requirement": {
            "id": "8cac9e406b954b80b22aec9a77e63593",
            "title": "Діагональ екрану"
          },
          "value": 23.8,
          "id": "1871609cced142738eeb41d12296fa97",
          "unit": {
            "code": "INH",
            "name": "дюйм"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "17d57e334aed49d19de4fd5b27b3b314",
            "title": "Роздільна здатність"
          },
          "values": [
            "1920x1080"
          ],
          "id": "af163878a04d4137ab60d84c1978bf53",
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "08ac3b62c1114ed1918bbde211047916",
            "title": "Співвідношення сторін"
          },
          "values": [
            "16:9"
          ],
          "id": "61427122b98145b6bbbddee0fbbe353e",
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "0cbbfa2735324fe8bd172bfe98510c39",
            "title": "Яскравість дисплея"
          },
          "value": 0,
          "id": "55ae8cdd399840d2b8a2aa7239a31428",
          "unit": {
            "code": "A24",
            "name": "кд/м²"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "6b78fd178786471ebff1faf01277c285",
            "title": "Контрастність (статична)"
          },
          "values": [
            "1000:1"
          ],
          "id": "90a999525b9949a0999ef88f21a181db",
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "6d027700fb9646968fed97d3291e487a",
            "title": "Кількість портів HDMI"
          },
          "value": 1,
          "id": "cdde082ef6c743b184f8dff9aeb8a0fa",
          "unit": {
            "code": "H87",
            "name": "штук"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "ce5247fff13a4a5bb8cc27b5c9edc972",
            "title": "Кількість портів D-sub"
          },
          "value": 1,
          "id": "2b272ddae7a94ceab825f1f1c605783b",
          "unit": {
            "code": "H87",
            "name": "штук"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "3a028e0e6ea34ccebfcd214944fb439a",
            "title": "Кабель для під’єднання"
          },
          "values": [
            "HDMI"
          ],
          "id": "8e560c0b1a314860b6bea63be99d804d",
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "68f8023f5da1456789a9b355f67022f9",
            "title": "Гарантія"
          },
          "value": 36,
          "id": "d42a28bfa9e24540915ba0f42fe17b67",
          "unit": {
            "code": "MON",
            "name": "місяців"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        }
      ],
      "status": "active",
      "items": [
        {
          "id": "b9d12bf323eb4d539fc49c3d7d1c6446",
          "description": "футляри до державних нагород",
          "unit": {
            "name": "кг",
            "value": {
              "amount": 110.0,
              "currency": "UAH",
              "valueAddedTaxIncluded": false
            },
            "code": "KGM"
          },
          "quantity": 4.0,
          "product": "bee4548f9f344b8db47807229189394f"
        }
      ],
      "initialValue": {
        "amount": 459.0,
        "currency": "UAH",
        "valueAddedTaxIncluded": true
      }
    },
    {
      "id": "70bec639abd44364ae412469587562fc",
      "date": "2024-01-01T00:00:01+02:00",
      "documents": [
        {
          "confidentiality": "public",
          "id": "c64943624014487886d46bf483924faa",
          "datePublished": "2024-01-01T00:00:01+02:00",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal_part1.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0ec8fd2dc59a45c4a279f23fb91b2572?Signature=ogddqQNir075wYIRhUPZ6oI5BUvzCD30E0FvQqiiXat9Qib4uMcaop9PnCuO%2BH7lRvmqEqZSraQo3AifEAl8DA%3D%3D&KeyID=a8968c46",
          "documentOf": "tender",
          "dateModified": "2024-01-01T00:00:01+02:00",
          "language": "uk"
        },
        {
          "confidentiality": "public",
          "id": "e14bacfe84894a77ab379a1c28e189f8",
          "datePublished": "2024-01-01T00:00:01+02:00",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal_part2.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ec3cbabab3334b0f9405d0b48698fee7?Signature=qBVCZkrQZf2v6sbyohuyI5iQ37pvbp2baN2rdLaaHZkgB5P7KyYmNcfEe1tOEs5WB0P%2B1udLNbUMVs9KEFPIDQ%3D%3D&KeyID=a8968c46",
          "documentOf": "tender",
          "dateModified": "2024-01-01T00:00:01+02:00",
          "language": "uk"
        }
      ],
      "tenderers": [
        {
          "name": "Державне управління справами",
          "identifier": {
            "scheme": "UA-IPN",
            "id": "00037256",
            "uri": "http://www.dus.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Банкова, 11, корпус 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "01220",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Державне управління справами",
            "telephone": "+0440000000"
          },
          "scale": "micro"
        }
      ],
      "value": {
        "amount": 479.0,
        "currency": "UAH",
        "valueAddedTaxIncluded": true
      },
      "requirementResponses": [
        {
          "requirement": {
            "id": "8cac9e406b954b80b22aec9a77e63593",
            "title": "Діагональ екрану"
          },
          "value": 23.8,
          "id": "7c0ef0c48ee5437cac2a224970d33353",
          "unit": {
            "code": "INH",
            "name": "дюйм"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "17d57e334aed49d19de4fd5b27b3b314",
            "title": "Роздільна здатність"
          },
          "values": [
            "1920x1080"
          ],
          "id": "2a965fd795174d3dbde7bec316c2754a",
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "08ac3b62c1114ed1918bbde211047916",
            "title": "Співвідношення сторін"
          },
          "values": [
            "16:9"
          ],
          "id": "bf53dfe243744cbb95a450d9b81ab28a",
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "0cbbfa2735324fe8bd172bfe98510c39",
            "title": "Яскравість дисплея"
          },
          "value": 0,
          "id": "78f36e49974f4f12bf44f5cae5b59bd5",
          "unit": {
            "code": "A24",
            "name": "кд/м²"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "6b78fd178786471ebff1faf01277c285",
            "title": "Контрастність (статична)"
          },
          "values": [
            "1000:1"
          ],
          "id": "4f505499ff8d40cd960ff22c2e36f619",
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "6d027700fb9646968fed97d3291e487a",
            "title": "Кількість портів HDMI"
          },
          "value": 1,
          "id": "95c8716eeadc4ebbacb8f091bb666be4",
          "unit": {
            "code": "H87",
            "name": "штук"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "ce5247fff13a4a5bb8cc27b5c9edc972",
            "title": "Кількість портів D-sub"
          },
          "value": 1,
          "id": "13fe13153cf749c5a2f4fc311b862d6e",
          "unit": {
            "code": "H87",
            "name": "штук"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "3a028e0e6ea34ccebfcd214944fb439a",
            "title": "Кабель для під’єднання"
          },
          "values": [
            "HDMI"
          ],
          "id": "e4fa8eb548824d25b4edc868da25db53",
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        },
        {
          "requirement": {
            "id": "68f8023f5da1456789a9b355f67022f9",
            "title": "Гарантія"
          },
          "value": 36,
          "id": "6851cc13fe044c8899e2e26dc06c65b9",
          "unit": {
            "code": "MON",
            "name": "місяців"
          },
          "classification": {
            "scheme": "ESPD211",
            "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
          }
        }
      ],
      "status": "active",
      "items": [
        {
          "id": "b9d12bf323eb4d539fc49c3d7d1c6446",
          "description": "футляри до державних нагород",
          "unit": {
            "name": "кг",
            "value": {
              "amount": 110.0,
              "currency": "UAH",
              "valueAddedTaxIncluded": false
            },
            "code": "KGM"
          },
          "quantity": 4.0,
          "product": "308b6fa8fb944b308b6e8088ba9fe43d"
        }
      ],
      "submissionDate": "2024-01-01T00:00:01+02:00",
      "initialValue": {
        "amount": 479.0,
        "currency": "UAH",
        "valueAddedTaxIncluded": true
      }
    },
    {
      "id": "959df55b73cd4bb09dd7fb17be8d0c51",
      "status": "invalid"
    }
  ]
}

