GET /api/2.5/tenders/3f38940af1314712ac29867b3e4eced4/awards HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "status": "pending",
      "suppliers": [
        {
          "name": "Державне управління справами",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00037256",
            "uri": "http://www.dus.gov.ua/"
          },
          "scale": "micro",
          "address": {
            "streetAddress": "вул. Банкова, 11, корпус 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "01220",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Державне управління справами",
            "telephone": "+0440000000"
          }
        }
      ],
      "bid_id": "e1e5b10f2f544862978912218b1bcb35",
      "value": {
        "amount": 459.0,
        "currency": "UAH",
        "valueAddedTaxIncluded": true
      },
      "date": "2023-09-20T01:00:01+03:00",
      "id": "dcf5db2bd67c47faaf0b9cc04f6539fe"
    }
  ]
}

