GET /api/2.5/tenders/2874d5c2acd649bbb8679e9439621113/bids/072ccda057404889a0cd2009ccf1f8f9?acc_token=4b182a91a2864791a3088e84e44e6f08 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 404 Not Found
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "url",
      "name": "bid_id",
      "description": "Not Found"
    }
  ]
}

