PATCH /api/2.5/tenders/2874d5c2acd649bbb8679e9439621113/bids/d948edc4cb6e40fda39035b61fd70ac6?acc_token=0484ed15231c4703bd9ddf87eb9575e8 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "value": {
      "amount": 470
    }
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "d948edc4cb6e40fda39035b61fd70ac6",
    "date": "2024-01-01T00:00:01+02:00",
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro"
      }
    ],
    "value": {
      "amount": 470.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "requirementResponses": [
      {
        "requirement": {
          "id": "143eb8ba1ad8447b89fdf984e8550cdd",
          "title": "Діагональ екрану"
        },
        "value": 23.8,
        "id": "bb00c016c4cc460cb18fbf59da676525",
        "unit": {
          "code": "INH",
          "name": "дюйм"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "b3bc205afbb246fa9049119cdec737df",
          "title": "Роздільна здатність"
        },
        "values": [
          "1920x1080"
        ],
        "id": "6fbb8ed38855448db53299b6e612af77",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "05ee5b8bd46c4f2dbda8fc5c140f6420",
          "title": "Співвідношення сторін"
        },
        "values": [
          "16:9"
        ],
        "id": "bc9cb2f23a8749ea9f656166f60dd413",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "3b6af92914a047b2bd2c1bfd714adcf6",
          "title": "Яскравість дисплея"
        },
        "value": 0,
        "id": "af27f64a7f144d7782b309eb9a39c82e",
        "unit": {
          "code": "A24",
          "name": "кд/м²"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "383761af47964f29a6ed2754b88dd4d1",
          "title": "Контрастність (статична)"
        },
        "values": [
          "1000:1"
        ],
        "id": "b352e5e3c11f483596953570a3554342",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "1949b1aac38b41e99615052120f9c4a1",
          "title": "Кількість портів HDMI"
        },
        "value": 1,
        "id": "3d98a1df5e3d4d83910aaa1523b3a8b0",
        "unit": {
          "code": "H87",
          "name": "штук"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "7a4f29925a8f430fb6094b40cd1c171f",
          "title": "Кількість портів D-sub"
        },
        "value": 1,
        "id": "d62ec2a653de4cf793c92a227a18e865",
        "unit": {
          "code": "H87",
          "name": "штук"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "622b7a53db2d4b76b9b48643fc1f65ec",
          "title": "Кабель для під’єднання"
        },
        "values": [
          "HDMI"
        ],
        "id": "c4f74b5d2fe34933af4849d846e3a171",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "c5675ebbd1164923b2c8ca8dbc158258",
          "title": "Гарантія"
        },
        "value": 36,
        "id": "400be1b441524e9abdfe0d0a50afea94",
        "unit": {
          "code": "MON",
          "name": "місяців"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "47c1d3250c0644f9a26e8fb5d656b066",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": true,
        "id": "d5a248a28cd34659a8b8f335eef85cad",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.TERRORIST_OFFENCES"
        }
      },
      {
        "requirement": {
          "id": "27ee2ce8b1eb4faba58664bb63a164dc",
          "title": "Учасник процедури закупівлі не мав з цим самим замовником договорів достроково розірваних через невиконання (учасником) своїх зобов'язань через що було застосовано санкції у вигляді штрафів та/або відшкодування збитків"
        },
        "value": true,
        "id": "40b0679fbc694badb9192d759643cdce",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.EARLY_TERMINATION"
        }
      }
    ],
    "status": "draft",
    "items": [
      {
        "id": "30c4edcb5705460a9ca5fd7985bfe56c",
        "description": "Комп’ютерне обладнання",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 93.8,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 5.0,
        "product": "320701ea170c4dd0ade069195433631b"
      }
    ]
  }
}

