POST /api/2.5/tenders/d129be7cbe054d18a179ea11a7141a52/cancellations?acc_token=3f07ab10456e4f519a3cf51c24d19c80 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reason": "cancellation reason",
    "reasonType": "noDemand"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/d129be7cbe054d18a179ea11a7141a52/cancellations/da9483f553b8494a9afcef5c051634f4

{
  "data": {
    "reasonType": "noDemand",
    "reason": "cancellation reason",
    "id": "da9483f553b8494a9afcef5c051634f4",
    "date": "2023-09-20T01:00:01+03:00",
    "cancellationOf": "tender",
    "status": "draft"
  }
}

