PATCH /api/2.5/tenders/c2ca2d7ec5d64dc1ae93f640fbbed6ca?acc_token=88f0c288a4ae425aafa90ecaba7797b1 HTTP/1.0
Authorization: Bearer broker
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "draft.publishing"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "date": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:00+02:00",
    "dateCreated": "2023-01-01T00:00:00+02:00",
    "tenderID": "UA-2023-01-01-000001-a",
    "owner": "broker",
    "title": "Комп’ютерне обладнання",
    "mainProcurementCategory": "goods",
    "procurementMethodType": "priceQuotation",
    "procurementMethod": "selective",
    "submissionMethod": "electronicAuction",
    "awardCriteria": "lowestCost",
    "status": "draft.publishing",
    "agreement": {
      "id": "2e14a78a2074952d5a2d256c3c004dda"
    },
    "value": {
      "amount": 22000.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderPeriod": {
      "startDate": "2023-01-01T00:00:00+02:00",
      "endDate": "2023-01-15T00:00:00+02:00"
    },
    "procuringEntity": {
      "name": "Державне управління справами",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00037256",
        "uri": "http://www.dus.gov.ua/"
      },
      "address": {
        "streetAddress": "вул. Банкова, 11, корпус 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "contactPoint": {
        "telephone": "+0440000000",
        "name": "Державне управління справами"
      },
      "kind": "general"
    },
    "items": [
      {
        "id": "9702a5b870924319b48309dc4acd7d21",
        "description": "Комп’ютерне обладнання",
        "classification": {
          "description": "Cartons",
          "scheme": "ДК021",
          "id": "44617100-9"
        },
        "quantity": 5.0,
        "deliveryDate": {
          "startDate": "2023-01-03T00:00:00+02:00",
          "endDate": "2023-01-06T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "additionalClassifications": [
          {
            "scheme": "INN",
            "id": "17.21.1",
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ],
        "unit": {
          "name": "кг",
          "value": {
            "amount": 6.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": true
          },
          "code": "KGM"
        },
        "profile": "655360-30230000-889652-40000777"
      }
    ],
    "criteria": [
      {
        "id": "5e08c98f0d5a47618082ba90d214f651",
        "title": "Форма випуску",
        "description": "Форма випуску",
        "requirementGroups": [
          {
            "id": "4e95ed3deb91479abafa88adafe00f3a",
            "description": "Форма випуску",
            "requirements": [
              {
                "id": "6c768e4c59364a58ab7071feda51cb42",
                "title": "Форма випуску",
                "dataType": "string",
                "expectedValue": "Розчин для інфузій"
              }
            ]
          }
        ]
      },
      {
        "id": "92612f47f7944789bf05487ae15f1b50",
        "title": "Доза діючої речовини",
        "description": "Доза діючої речовини",
        "requirementGroups": [
          {
            "id": "c5032ccc53d94d17b290d016ea731660",
            "description": "Доза діючої речовини",
            "requirements": [
              {
                "id": "555076d24f7a4a95b01d6f2f84569523",
                "title": "Доза діючої речовини",
                "dataType": "integer",
                "unit": {
                  "code": "KGM",
                  "name": "кілограми"
                },
                "minValue": 5
              }
            ]
          }
        ]
      },
      {
        "id": "549ba3ac51614b40ba22d2b099360b2a",
        "title": "Форма випуску",
        "description": "Форма випуску",
        "requirementGroups": [
          {
            "id": "4219c7ea5c5846b091eb4fed2d8fe30a",
            "description": "Форма випуску",
            "requirements": [
              {
                "id": "38e20956305847ceb4058592a65072c0",
                "title": "Форма випуску",
                "dataType": "string",
                "expectedValues": [
                  "Відповідь1",
                  "Відповідь2",
                  "Відповідь3",
                  "Відповідь4"
                ],
                "expectedMinItems": 2,
                "expectedMaxItems": 3
              }
            ]
          }
        ]
      }
    ],
    "noticePublicationDate": "2023-01-01T00:00:00+02:00",
    "id": "c2ca2d7ec5d64dc1ae93f640fbbed6ca"
  }
}

