POST /api/2.5/tenders/09b9ff4fc8654d1bb24fb14572e88f1c/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 2043
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "countryName": "Україна",
          "postalCode": "01220",
          "region": "м. Київ",
          "locality": "м. Київ",
          "streetAddress": "вул. Банкова, 11, корпус 1"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro"
      }
    ],
    "value": {
      "amount": 479,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "requirementResponses": [
      {
        "requirement": {
          "id": "999fca7c01414e4ab35c88a02388582f"
        },
        "value": "Розчин для інфузій"
      },
      {
        "requirement": {
          "id": "0d6ac61303dc41609c2773d09e6593ef"
        },
        "value": 5
      },
      {
        "requirement": {
          "id": "2688fb5d39c84f618f45ade09c04d8f1"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ]
      }
    ],
    "documents": [
      {
        "title": "Proposal_part1.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/192b7b24d38d4de6bc9a6b1e6c77960b?Signature=KZvg8%2BrfogEUWyFgSzDTkGRGEnKYenxZZFGYsF4%2FGgTlwcqr2Ce3l59X68OVJ0Q%2BM7LHNy67BE5p45F%2Bc%2B2mCg%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      },
      {
        "title": "Proposal_part2.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e6ac8b976a3445839cd998263b5ffb42?Signature=zvZOxC7UDz%2BEdfbTEGPVBorDfc%2FN93QjOxcBJ6NKcalH0dgUdGOUMCkuJs%2Ba5QU6zg7SFUFwM11FS9T%2BZcuDDA%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/09b9ff4fc8654d1bb24fb14572e88f1c/bids/e0950a264cbb4e31b09fab7b5ec714f8
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "telephone": "+0440000000",
          "name": "Державне управління справами"
        },
        "scale": "micro"
      }
    ],
    "status": "draft",
    "value": {
      "amount": 479.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/192b7b24d38d4de6bc9a6b1e6c77960b?Signature=CVZKWk94K98I8qC6AG1vXsG0a%2FevBdstqBn5YpFW41JCULXAM2vtaFWQsNTa5zbc%2BatZ9y4F0ewJk9%2FrxUDLBw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "id": "62c232fa4eb24520bacea4d72a041bdb",
        "datePublished": "2023-01-01T00:00:01+02:00",
        "dateModified": "2023-01-01T00:00:01+02:00"
      },
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e6ac8b976a3445839cd998263b5ffb42?Signature=VCjd%2BsC5JO5dsnfKlP9NMTUwhUOAFwPWrRWHJknfgB0NZ81mf7OwZLG1oVrd2EKQ8G9ZQh8hXngt7%2BbwawjsCQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "id": "81196303df3a401dac7a6f56ed1b8a27",
        "datePublished": "2023-01-01T00:00:01+02:00",
        "dateModified": "2023-01-01T00:00:01+02:00"
      }
    ],
    "requirementResponses": [
      {
        "id": "aae84e1040e049aea5fc9a0304bc5548",
        "requirement": {
          "id": "999fca7c01414e4ab35c88a02388582f"
        },
        "value": "Розчин для інфузій"
      },
      {
        "id": "bd7a608d841b403e9feabf56a8a73d8b",
        "requirement": {
          "id": "0d6ac61303dc41609c2773d09e6593ef"
        },
        "value": 5
      },
      {
        "id": "113a36a6f490424aa5dfa5bd7b825592",
        "requirement": {
          "id": "2688fb5d39c84f618f45ade09c04d8f1"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ]
      }
    ],
    "id": "e0950a264cbb4e31b09fab7b5ec714f8",
    "date": "2023-01-01T00:00:01+02:00"
  },
  "access": {
    "token": "07de8722ab3e4408a88ba0a16dfe418d",
    "transfer": "2b2e66e2a6af44b8a65e84f9f3eb44da"
  }
}

