POST /api/2.5/tenders/e821f507458c4e99bdd9928981355ffa/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 2173
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "countryName": "Україна",
          "postalCode": "01220",
          "region": "м. Київ",
          "locality": "м. Київ",
          "streetAddress": "вул. Банкова, 11, корпус 1"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro"
      }
    ],
    "value": {
      "amount": 479,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "requirementResponses": [
      {
        "value": "23.8",
        "requirement": {
          "id": "655360-0001-001-01"
        }
      },
      {
        "value": "1920x1080",
        "requirement": {
          "id": "655360-0002-001-01"
        }
      },
      {
        "value": "16:9",
        "requirement": {
          "id": "655360-0003-001-01"
        }
      },
      {
        "value": 250,
        "requirement": {
          "id": "655360-0004-001-01"
        }
      },
      {
        "value": "1000:1",
        "requirement": {
          "id": "655360-0005-001-01"
        }
      },
      {
        "value": 1,
        "requirement": {
          "id": "655360-0006-001-01"
        }
      },
      {
        "value": 1,
        "requirement": {
          "id": "655360-0007-001-01"
        }
      },
      {
        "value": "HDMI",
        "requirement": {
          "id": "655360-0008-001-01"
        }
      },
      {
        "value": 36,
        "requirement": {
          "id": "655360-0009-001-01"
        }
      }
    ],
    "documents": [
      {
        "title": "Proposal_part1.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/192b7b24d38d4de6bc9a6b1e6c77960b?Signature=KZvg8%2BrfogEUWyFgSzDTkGRGEnKYenxZZFGYsF4%2FGgTlwcqr2Ce3l59X68OVJ0Q%2BM7LHNy67BE5p45F%2Bc%2B2mCg%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      },
      {
        "title": "Proposal_part2.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e6ac8b976a3445839cd998263b5ffb42?Signature=zvZOxC7UDz%2BEdfbTEGPVBorDfc%2FN93QjOxcBJ6NKcalH0dgUdGOUMCkuJs%2Ba5QU6zg7SFUFwM11FS9T%2BZcuDDA%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e821f507458c4e99bdd9928981355ffa/bids/62632b90b4c44ebd81073e2fc9dbc000
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro"
      }
    ],
    "date": "2021-03-16T00:00:01+02:00",
    "id": "62632b90b4c44ebd81073e2fc9dbc000",
    "value": {
      "amount": 479.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "documents": [
      {
        "id": "02fd6af18f5e49a99a68ff73f0169903",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e821f507458c4e99bdd9928981355ffa/bids/62632b90b4c44ebd81073e2fc9dbc000/documents/02fd6af18f5e49a99a68ff73f0169903?download=192b7b24d38d4de6bc9a6b1e6c77960b",
        "datePublished": "2021-03-16T00:00:01+02:00",
        "dateModified": "2021-03-16T00:00:01+02:00",
        "documentOf": "tender"
      },
      {
        "id": "59edf3c71d23491eb00428e8efe3b9ce",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e821f507458c4e99bdd9928981355ffa/bids/62632b90b4c44ebd81073e2fc9dbc000/documents/59edf3c71d23491eb00428e8efe3b9ce?download=e6ac8b976a3445839cd998263b5ffb42",
        "datePublished": "2021-03-16T00:00:01+02:00",
        "dateModified": "2021-03-16T00:00:01+02:00",
        "documentOf": "tender"
      }
    ],
    "requirementResponses": [
      {
        "id": "b77debb00fc84b3eacc5b1805c4cd4a7",
        "requirement": {
          "id": "655360-0001-001-01"
        },
        "value": "23.8"
      },
      {
        "id": "7557b12547334e7d843968e671e7d62b",
        "requirement": {
          "id": "655360-0002-001-01"
        },
        "value": "1920x1080"
      },
      {
        "id": "da6ad23a4cd149a193da0e23c5574b5d",
        "requirement": {
          "id": "655360-0003-001-01"
        },
        "value": "16:9"
      },
      {
        "id": "d2d262620d534dca8229a5df601d394f",
        "requirement": {
          "id": "655360-0004-001-01"
        },
        "value": "250"
      },
      {
        "id": "95a2d29a4bb04e8db719f74ab7aa2ec1",
        "requirement": {
          "id": "655360-0005-001-01"
        },
        "value": "1000:1"
      },
      {
        "id": "65cc255132c344a2919b8367e30c56c6",
        "requirement": {
          "id": "655360-0006-001-01"
        },
        "value": "1"
      },
      {
        "id": "560c11fc0b014f948780865d8456dc39",
        "requirement": {
          "id": "655360-0007-001-01"
        },
        "value": "1"
      },
      {
        "id": "5a3d7f1509bc41e19235d3ea774e8f2f",
        "requirement": {
          "id": "655360-0008-001-01"
        },
        "value": "HDMI"
      },
      {
        "id": "17346ca5a1d74950831f84be42c62db0",
        "requirement": {
          "id": "655360-0009-001-01"
        },
        "value": "36"
      }
    ],
    "status": "draft"
  },
  "access": {
    "token": "3a9b10d6d5544c5ab63ca47f59595980",
    "transfer": "f01b1affbdb64995941c2f15baccecf4"
  }
}

