POST /api/2.5/tenders/db4fb6143a5f45b6953e8f010ed8064e/contracts/d83498cb2ab24c89b96447ddef5e258d/documents?acc_token=151a30932ee245e989771be867bc8235 HTTP/1.0
Authorization: Bearer broker
Content-Length: 342
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ae8aa265abc14f87ac488057a2223e5b?KeyID=a8968c46&Signature=eFkiREyzyPgkHkp7Qff7tuXSMR8P1JOUNbcp9f03507801z5hCqTTSkGJMg2624n8deKlrf1J6PGS%2BpcV0%2FYAg%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/db4fb6143a5f45b6953e8f010ed8064e/contracts/d83498cb2ab24c89b96447ddef5e258d/documents/26a79e8ffd684b638b28e472efd912b2
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_first_document.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ae8aa265abc14f87ac488057a2223e5b?KeyID=a8968c46&Signature=LBhaXoX3LRxqDOt6Be3hhvgc62NkQiRA%252BM%252BhqEGj25CYSEWbHWJKeXv4KX8KZwMxBF1ntynCOnQ%2F%252BQ0XeeqTDA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2020-05-15T01:00:03+03:00", 
    "id": "26a79e8ffd684b638b28e472efd912b2", 
    "dateModified": "2020-05-15T01:00:03+03:00"
  }
}

