GET /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "dateModified": "2023-01-01T00:00:01+02:00",
      "id": "09b9ff4fc8654d1bb24fb14572e88f1c"
    }
  ],
  "next_page": {
    "offset": 1672524001.0,
    "path": "/api/2.5/tenders?offset=1672524001.0",
    "uri": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders?offset=1672524001.0"
  }
}

