GET /api/2.5/tenders/85818863b7a4458ea02e3893422b0a0d HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active.tendering", 
    "procurementMethod": "selective", 
    "mainProcurementCategory": "goods", 
    "tenderPeriod": {
      "startDate": "2020-05-15T01:00:00+03:00", 
      "endDate": "2020-05-29T01:00:00+03:00"
    }, 
    "title": "Комп’ютерне обладнання", 
    "items": [
      {
        "description": "Комп’ютерне обладнання", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Комп’ютерне обладнанн", 
          "id": "30230000-0"
        }, 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2020-05-17T01:00:00+03:00", 
          "endDate": "2020-05-20T01:00:00+03:00"
        }, 
        "id": "98c87e3a8f2b48fa887616989dcf8294", 
        "unit": {
          "code": "H87", 
          "name": "штук"
        }, 
        "quantity": 1.0
      }
    ], 
    "procurementMethodType": "priceQuotation", 
    "value": {
      "currency": "UAH", 
      "amount": 22000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "shortlistedFirms": [
      {
        "status": "active", 
        "scale": "large", 
        "name": "Товариство з обмеженою відповідальністю «Пікселі»", 
        "address": {
          "postalCode": "01100", 
          "countryName": "Україна", 
          "streetAddress": "бул.Дружби Народів, 8", 
          "region": "Київська область", 
          "locality": "м.Київ"
        }, 
        "contactPoint": {
          "email": "contact@pixel.pix", 
          "telephone": "(067) 123-45-67", 
          "name": "Оксана Піксель"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "12345678", 
          "legalName": "Товариство з обмеженою відповідальністю «Пікселі»"
        }, 
        "id": "UA-EDR-12345678"
      }, 
      {
        "status": "active", 
        "scale": "large", 
        "name": "Товариство з обмеженою відповідальністю «Штекер-Пекер»", 
        "address": {
          "postalCode": "46000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Кластерна, 777-К", 
          "region": "Тернопільська область", 
          "locality": "м.Тернопіль"
        }, 
        "contactPoint": {
          "email": "info@shteker.pek", 
          "telephone": "(095) 123-45-67", 
          "name": "Олег Штекер"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "87654321", 
          "legalName": "Товариство з обмеженою відповідальністю «Штекер-Пекер»"
        }, 
        "id": "UA-EDR-87654321"
      }
    ], 
    "date": "2020-05-15T01:00:00+03:00", 
    "noticePublicationDate": "2020-05-15T01:00:00+03:00", 
    "profile": "655360-30230000-889652-40000777", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dateModified": "2020-05-15T01:00:00+03:00", 
    "criteria": [
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "number", 
                "title": "Діагональ екрану", 
                "id": "655360-0001-001-01", 
                "unit": {
                  "code": "INH", 
                  "name": "дюйм"
                }, 
                "minValue": "23.8"
              }
            ], 
            "id": "655360-0001-001", 
            "description": "Діагональ екрану, не менше 23.8 дюймів"
          }
        ], 
        "title": "Діагональ екрану", 
        "description": "Діагональ екрану", 
        "id": "655360-0001"
      }, 
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "string", 
                "id": "655360-0002-001-01", 
                "expectedValue": "1920x1080", 
                "title": "Роздільна здатність"
              }
            ], 
            "id": "655360-0002-001", 
            "description": "Роздільна здатність - 1920x1080"
          }
        ], 
        "title": "Роздільна здатність", 
        "description": "Роздільна здатність", 
        "id": "655360-0002"
      }, 
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "string", 
                "id": "655360-0003-001-01", 
                "expectedValue": "16:9", 
                "title": "Співвідношення сторін"
              }
            ], 
            "id": "655360-0003-001", 
            "description": "Співвідношення сторін"
          }
        ], 
        "title": "Співвідношення сторін", 
        "description": "Співвідношення сторін", 
        "id": "655360-0003"
      }, 
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "integer", 
                "title": "Яскравість дисплея", 
                "id": "655360-0004-001-01", 
                "unit": {
                  "code": "A24", 
                  "name": "кд/м²"
                }, 
                "minValue": "250"
              }
            ], 
            "id": "655360-0004-001", 
            "description": "Яскравість дисплея, не менше 250 кд/м²"
          }
        ], 
        "title": "Яскравість дисплея", 
        "description": "Яскравість дисплея", 
        "id": "655360-0004"
      }, 
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "string", 
                "id": "655360-0005-001-01", 
                "expectedValue": "1000:1", 
                "title": "Контрастність (статична)"
              }
            ], 
            "id": "655360-0005-001", 
            "description": "Контрастність (статична) - 1000:1"
          }, 
          {
            "requirements": [
              {
                "dataType": "string", 
                "id": "655360-0005-002-01", 
                "expectedValue": "3000:1", 
                "title": "Контрастність (статична)"
              }
            ], 
            "id": "655360-0005-002", 
            "description": "Контрастність (статична) - 3000:1"
          }
        ], 
        "title": "Контрастність (статична)", 
        "description": "Контрастність (статична)", 
        "id": "655360-0005"
      }, 
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "integer", 
                "title": "Кількість портів HDMI", 
                "id": "655360-0006-001-01", 
                "unit": {
                  "code": "H87", 
                  "name": "штук"
                }, 
                "minValue": "1"
              }
            ], 
            "id": "655360-0006-001", 
            "description": "Кількість портів HDMI, не менше 1 шт."
          }
        ], 
        "title": "Кількість портів HDMI", 
        "description": "Кількість портів HDMI", 
        "id": "655360-0006"
      }, 
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "integer", 
                "title": "Кількість портів D-sub", 
                "id": "655360-0007-001-01", 
                "unit": {
                  "code": "H87", 
                  "name": "штук"
                }, 
                "minValue": "1"
              }
            ], 
            "id": "655360-0007-001", 
            "description": "Кількість портів D-sub, не менше 1 шт."
          }
        ], 
        "title": "Кількість портів D-sub", 
        "description": "Кількість портів D-sub", 
        "id": "655360-0007"
      }, 
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "string", 
                "id": "655360-0008-001-01", 
                "expectedValue": "HDMI", 
                "title": "Кабель для під’єднання"
              }
            ], 
            "id": "655360-0008-001", 
            "description": "Кабель для під’єднання"
          }
        ], 
        "title": "Кабель для під’єднання", 
        "description": "Кабель для під’єднання", 
        "id": "655360-0008"
      }, 
      {
        "requirementGroups": [
          {
            "requirements": [
              {
                "dataType": "integer", 
                "title": "Гарантія", 
                "id": "655360-0009-001-01", 
                "unit": {
                  "code": "MON", 
                  "name": "місяців"
                }, 
                "minValue": "36"
              }
            ], 
            "id": "655360-0009-001", 
            "description": "Гарантія, не менше 36 місяців"
          }
        ], 
        "title": "Гарантія", 
        "description": "Строк дії гарантії", 
        "id": "655360-0009"
      }
    ], 
    "owner": "broker", 
    "next_check": "2020-05-29T01:00:00+03:00", 
    "awardCriteria": "lowestCost", 
    "id": "85818863b7a4458ea02e3893422b0a0d", 
    "tenderID": "UA-2020-05-15-000001"
  }
}

