PATCH /api/2.5/tenders/09b9ff4fc8654d1bb24fb14572e88f1c/contracts/3d625008dcea45cb9ce2c6f803c32511?acc_token=6e52619ae5794a8aae414350e5f3cd4b HTTP/1.0
Authorization: Bearer broker
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "3d625008dcea45cb9ce2c6f803c32511",
    "awardID": "2457dbf1f0fa43daaf6148695865ce39",
    "contractID": "UA-2023-01-01-000001-a-1",
    "contractNumber": "contract #13111",
    "status": "active",
    "period": {
      "startDate": "2023-01-01T00:00:03+02:00",
      "endDate": "2024-01-01T00:00:03+02:00"
    },
    "value": {
      "amount": 238.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true,
      "amountNet": 230.0
    },
    "items": [
      {
        "id": "0e1d572c4dde4ad1ae9da7927fa5e824",
        "description": "Комп’ютерне обладнання",
        "classification": {
          "description": "Комп’ютерне обладнанн",
          "scheme": "ДК021",
          "id": "30230000-0"
        },
        "additionalClassifications": [
          {
            "scheme": "INN",
            "id": "17.21.1",
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ],
        "unit": {
          "name": "штук",
          "value": {
            "amount": 6.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": true
          },
          "code": "H87"
        },
        "quantity": 5.0,
        "deliveryDate": {
          "startDate": "2023-01-03T00:00:00+02:00",
          "endDate": "2023-01-06T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        }
      }
    ],
    "suppliers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "telephone": "+0440000000",
          "name": "Державне управління справами"
        },
        "scale": "micro"
      }
    ],
    "date": "2023-01-01T00:00:03+02:00",
    "documents": [
      {
        "id": "08b7fda8f31b4bbe8b7d1a1ff4c44a70",
        "datePublished": "2023-01-01T00:00:03+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "contract_first_document.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/960b479e1b2b4495a032df428e5d3ebf?Signature=tpwVsdEVJkXH8DdrT99YRB8Fyyu2HmLh065tDRBZ%2BMMgjFWYRDY0R%2FQ6vWjjT%2FHWctDBe%2BI%2FO5cGrA8%2B08E1Bw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:03+02:00"
      },
      {
        "id": "383b02ea064e43919678b17b9d833fbe",
        "datePublished": "2023-01-01T00:00:03+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "contract_second_document.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/36ebea29c5e54ccfaa107cd5e67ab7b9?Signature=b4z4J55fJKAxzkpB8Rej0%2FBdrDLxqAIULTNrqMlQ9wCQj53d1r%2BpS%2FPRMzVT5HhqA3TxniiLKRU8D9IlWUbsAg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:03+02:00"
      }
    ],
    "dateSigned": "2023-01-01T00:00:03+02:00"
  }
}

