PATCH /api/2.5/tenders/7e23f3f26faf4146af5f668247cf04f4?acc_token=1fa15f3780344958b25159593e9b4836 HTTP/1.0
Authorization: Bearer broker
Content-Length: 161
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "milestones": [
      {}, 
      {
        "description": "Підозрілий опис", 
        "title": "anotherEvent"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "milestones": [
      {
        "code": "prepayment", 
        "sequenceNumber": 0, 
        "title": "signingTheContract", 
        "duration": {
          "type": "banking", 
          "days": 5
        }, 
        "percentage": 45.55, 
        "type": "financing", 
        "id": "fefc9f6e15a84b86b2fddc14f6591d99"
      }, 
      {
        "code": "postpayment", 
        "description": "Підозрілий опис", 
        "sequenceNumber": 1, 
        "title": "anotherEvent", 
        "duration": {
          "type": "calendar", 
          "days": 7
        }, 
        "percentage": 54.45, 
        "type": "financing", 
        "id": "38783ac1487a4f55abd2e61b58497e22"
      }
    ], 
    "mainProcurementCategory": "goods", 
    "tenderPeriod": {
      "startDate": "2020-05-22T01:00:00+03:00", 
      "endDate": "2020-05-29T01:00:00+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 15.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2020-05-17T01:00:00+03:00", 
          "endDate": "2020-05-20T01:00:00+03:00"
        }, 
        "id": "59416cdafac94b998fbf6bdec61facf2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2020-05-15T01:00:00+03:00", 
    "next_check": "2020-05-22T01:00:00+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне управління справами", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "awardCriteria": "lowestCost", 
    "enquiryPeriod": {
      "startDate": "2020-05-15T01:00:00+03:00", 
      "endDate": "2020-05-22T01:00:00+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2020-05-15T01:00:00+03:00", 
    "id": "7e23f3f26faf4146af5f668247cf04f4", 
    "tenderID": "UA-2020-05-15-000001"
  }
}

