GET /api/2.5/tenders/16198a81806a4fd9bf0d5b437bc44f7a/bids/03e8ecacaef043e9b20f1a36a5279ac7/documents?acc_token=873c24dbb920470291a301faa169ce64 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "Proposal.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/32dacd322185446594eb865b681b975d?Signature=85b5nciCwPI27%2BpzlbJkhTXxKofcDEfqcJBl3NaonZpWyuMxZpx3sqVSNgt4mOL9%2F4%2FqnBEEcq%2FO6AQ6ndybAQ%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "id": "d155a202959247a9b7d090c41ca410e7",
      "datePublished": "2021-03-16T00:00:00+02:00",
      "dateModified": "2021-03-16T00:00:00+02:00"
    }
  ]
}

