GET /api/2.5/tenders/93f4fb7502554ab591dd397e3360b027/bids/17c5c113d17a4e6a82022eed0e27b18e?acc_token=08ecfbcf7ec84690a88cc8407c4b4f7f HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037257",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "telephone": "+0440000000",
          "name": "Державне управління справами"
        },
        "scale": "micro"
      }
    ],
    "status": "active",
    "id": "17c5c113d17a4e6a82022eed0e27b18e",
    "date": "2023-01-01T00:00:00+02:00",
    "documents": [
      {
        "id": "d3a8b92c118646a3adb86846bb67b62b",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6f95f83074884c4793b92674ecbf017d?Signature=QoHCra37U%2FEXoEYg1Srz%2B%2BHfziG7TmHsS1Kwof8nkEHMWsbVlY%2BKnuoZbhVUBdcBnfmDucQGTJIjynfLt3wnAQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00"
      },
      {
        "id": "684eb6ef4cab45a9bf98593cc81e9a50",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/634443ba221c4aec9e80218dce5d9898?Signature=mtYQ%2BQUtqn3VyRg2qigXiCQOJfMEg%2BRShGSWo%2FvohBcnk2ajfiLnZJNPsiMteYmwwhdGgs6kU9vbSfMfOIdnCw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ],
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE",
        "value": 0.1
      },
      {
        "code": "OCDS-123454-YEARS",
        "value": 0.1
      }
    ],
    "lotValues": [
      {
        "value": {
          "amount": 499.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "f2599a519a45416db792d9ee833a8e5a",
        "date": "2023-01-01T00:00:00+02:00",
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/93f4fb7502554ab591dd397e3360b027_f2599a519a45416db792d9ee833a8e5a?key_for_bid=17c5c113d17a4e6a82022eed0e27b18e"
      }
    ]
  }
}

