PATCH /api/2.5/tenders/e23dee5896254eb4ac3364a9a854c3fe/awards/f0d8a8043da446fbb890c7c072975f15?acc_token=5585cd490cac4cb68cd03d747b3c247c HTTP/1.0
Authorization: Bearer broker
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "f0d8a8043da446fbb890c7c072975f15",
    "status": "active",
    "date": "2023-01-01T00:00:00+02:00",
    "value": {
      "amount": 499.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "weightedValue": {
      "amount": 388.11,
      "currency": "UAH",
      "valueAddedTaxIncluded": true,
      "denominator": 1.286
    },
    "suppliers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037258",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "telephone": "+0440000000",
          "name": "Державне управління справами"
        },
        "scale": "micro"
      }
    ],
    "bid_id": "cac5717cd00c4786ab92d1e93fe315ac",
    "lotID": "50fc7d0cb4e3423491c35387a046af42"
  }
}

