PATCH /api/2.5/tenders/16198a81806a4fd9bf0d5b437bc44f7a/cancellations/f44b7cc2783f44b8960e691080112d97/documents/82590e293cf5481bb59ac71a12ba8eeb?acc_token=89feea896bda4b28a07b1efd0cf55f66 HTTP/1.0
Authorization: Bearer broker
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "82590e293cf5481bb59ac71a12ba8eeb",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice.pdf",
    "description": "Changed description",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/17537bfab84747faa7a87a734a068e14?Signature=q7vhOUQqsOrTNg1kzFvJUecuDDxLGaYUF5kdc5uv%2FgqjMVr5j%2FMbDLWUdaKrnsPLtiqf6V%2B41vForlOH8KpFBQ%3D%3D&KeyID=a8968c46",
    "datePublished": "2021-03-16T00:00:00+02:00",
    "dateModified": "2021-03-16T00:00:00+02:00",
    "documentOf": "tender"
  }
}

