PATCH /api/2.5/tenders/b4bcd8f9ee82480fb413c261d6cea972/cancellations/9bd1f8dc532a494c823fc51ca4386ecf/documents/3f4526c35da14b70a9ec520bbb456061?acc_token=71a2cd2ca3764e0ba43ac51484c2c194 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "description": "Changed description"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "confidentiality": "public",
    "description": "Changed description",
    "id": "3f4526c35da14b70a9ec520bbb456061",
    "datePublished": "2027-01-01T00:01:00+02:00",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4234daa316364795b45fa893dc7ede7e?Signature=8ceglBTUZmrmlwopAj86%2Bw4OZmQCr%2B4%2B2BA%2Bq0F0UKe8UJtDDwUxSAU3YiuTRaDosf%2BFG5fzWvlUBWGJPZKbCQ%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "dateModified": "2027-01-01T00:01:00+02:00",
    "language": "uk"
  }
}

