POST /api/2.5/tenders/1e7fc0d4cb8943b985627a6dc1c42c8a/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 1376
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro"
      }
    ],
    "status": "draft",
    "lotValues": [
      {
        "value": {
          "amount": 500
        },
        "relatedLot": "f2599a519a45416db792d9ee833a8e5a"
      }
    ],
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE",
        "value": 0.1
      },
      {
        "code": "OCDS-123454-YEARS",
        "value": 0.1
      }
    ]
  }
}

Response: 403 Forbidden
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Bid is not a member of agreement"
    }
  ]
}

