PATCH /api/2.5/tenders/93f4fb7502554ab591dd397e3360b027/contracts/4280842259bb406781243e55a76040c6?acc_token=3f8107537abc4a978698af4ddbbe2cde HTTP/1.0
Authorization: Bearer broker
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "4280842259bb406781243e55a76040c6",
    "contractID": "UA-2023-01-01-000004-a-2",
    "contractNumber": "contract #13111",
    "status": "active",
    "period": {
      "startDate": "2023-01-01T00:00:00+02:00",
      "endDate": "2024-01-01T00:00:00+02:00"
    },
    "suppliers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00037258",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "telephone": "+0440000000",
          "name": "Державне управління справами"
        },
        "scale": "micro"
      }
    ],
    "date": "2023-01-01T00:00:00+02:00",
    "dateSigned": "2023-01-01T00:00:00+02:00",
    "value": {
      "amount": 238.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true,
      "amountNet": 230.0
    },
    "awardID": "373cdf721e874341bff555fb568a20d4",
    "documents": [
      {
        "id": "a28c699867bc47d2bb8566edb6856d6d",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "contract_first_document.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/683441ad518644979bfdede8405df7c1?Signature=513e2wVWsZdU0BhdzyBYGpoTHxh6t7%2FgKVnNZUAe94PtHC%2B4%2F8OIKLX66EFlfUkoUlG5M3jmaIRlg2MaXiunCA%3D%3D&KeyID=a8968c46",
        "dateModified": "2023-01-01T00:00:00+02:00"
      },
      {
        "id": "c3ef1c7751544ce29baf849cda527f0a",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "contract_second_document.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/524dba59516640b99c1c7f5195c7df77?Signature=tgAJvznHcEubX754JMDqKPitonexJEehSAbWFJjkEOnGW80CewSGiLLKPTJw%2FsyQCwwDaTbz23%2BAPC6xocapCQ%3D%3D&KeyID=a8968c46",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ],
    "items": [
      {
        "id": "1662b0e1d59f4e2f8e2c5bd48e03a7bc",
        "description": "футляри до державних нагород",
        "description_en": "futliary do derzhavnyh nagorod",
        "classification": {
          "description": "New Cartons",
          "scheme": "ДК021",
          "id": "44617100-9"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ],
        "quantity": 6.0,
        "deliveryDate": {
          "startDate": "2023-01-03T00:00:00+02:00",
          "endDate": "2023-01-06T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "relatedLot": "f2599a519a45416db792d9ee833a8e5a",
        "unit": {
          "name": "item",
          "code": "KGM",
          "value": {
            "amount": 6.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": true
          }
        }
      }
    ]
  }
}

