POST /api/2.5/tenders/e23dee5896254eb4ac3364a9a854c3fe/contracts/69b6c04539ef44ed9c066ea9f47142c1/documents?acc_token=5585cd490cac4cb68cd03d747b3c247c HTTP/1.0
Authorization: Bearer broker
Content-Length: 341
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "contract_second_document.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/52885cec7411475ea472a5688d3739f9?Signature=6vsSN7PC7P0QepWvmz5xQ0QltP9f6c0hgg5sHvKaxOGaCFpDL%2FGzTPQ4PUfB5ZGhKqqF60J0xigyxfD0sKEcDg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e23dee5896254eb4ac3364a9a854c3fe/contracts/69b6c04539ef44ed9c066ea9f47142c1/documents/141c6ddfa7f24a9da7291db7fe4f6718

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "contract_second_document.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/52885cec7411475ea472a5688d3739f9?Signature=eCACfBQqTNvM5orOFP9q1lq7%2Bo0kIVneUJC3Hd7cnFgS0ngh8QxWFf3CvXLgVOuLK2jYZLSSwJ2KaPDNI7fcCA%3D%3D&KeyID=a8968c46",
    "id": "141c6ddfa7f24a9da7291db7fe4f6718",
    "datePublished": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:00+02:00"
  }
}

