PUT /api/2.5/tenders/b4bcd8f9ee82480fb413c261d6cea972/cancellations/9bd1f8dc532a494c823fc51ca4386ecf/documents/3f4526c35da14b70a9ec520bbb456061?acc_token=71a2cd2ca3764e0ba43ac51484c2c194 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Notice.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/749ddd6fe0cc4217b3a9d09e5cef2375?Signature=UnxBdqG8udgPPDhIsCNckei6i0X8gBuQG%2F4DLjfNRGeWBOZNnHrrKEXsLT%2FU%2F8Ig6NXlZqSKMjSgyMGm84xrBA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "confidentiality": "public",
    "description": "Changed description",
    "id": "3f4526c35da14b70a9ec520bbb456061",
    "datePublished": "2027-01-01T00:01:00+02:00",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/749ddd6fe0cc4217b3a9d09e5cef2375?Signature=vIvmDaY00xHOl%2B5fqFlTjNAvEc5UqoqwQwUhJjVJwOOhV59s%2FS5M2UH5kEeG2gcMdPYmPWz5APejIr9C4jTIAQ%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "dateModified": "2027-01-01T00:01:00+02:00",
    "language": "uk"
  }
}

