POST /api/2.5/tenders/9c3bab1d2b124303adb40303b401fef6/documents?acc_token=a6cc32f878544fed9009024edd091a24 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "AwardCriteria.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dd09c74752f54370b81db56456d4622c?Signature=7EP5UfK%2BI7IT6JR%2FLpnvQa2MEx8B%2BN6CfTM3Rl%2FJy1QIl%2BNJ0A4pQ9uYbN%2BOJQCaVkdGSEMXbfT1qTQF0zqqDg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/9c3bab1d2b124303adb40303b401fef6/documents/5298dd90eaa24c348dd1244867034ad9

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "AwardCriteria.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dd09c74752f54370b81db56456d4622c?Signature=tSnRb6e0HBpOwpT1iHOjPI9TGBVNiiboyXfwC161eAwy84ICIfE8LARUNwZx50p5QDtRnNFfYqxDJzhn%2FVW%2FDA%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "5298dd90eaa24c348dd1244867034ad9",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "author": "tender_owner"
  }
}

