PATCH /api/2.5/tenders/9eb167a6c08a4130af77258c680e4ebf/awards/7c4e912c78ea46af96c33febe8b597a9/complaints/17d57490b21d4bc48ae2f1e7d0130aaf HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 109
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "accepted",
    "reviewDate": "2021-03-16T00:00:03+02:00",
    "reviewPlace": "Place of review"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "17d57490b21d4bc48ae2f1e7d0130aaf",
    "complaintID": "UA-2021-03-16-000001.1",
    "date": "2021-03-16T00:00:03+02:00",
    "type": "complaint",
    "author": {
      "name": "ДКП «Школяр»",
      "address": {
        "streetAddress": "вул. Островського, 33",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21100",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Сергій Олексюк",
        "email": "soleksuk@gmail.com",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00137256",
        "legalName": "ДКП «Школяр»",
        "uri": "http://www.sc.gov.ua/"
      }
    },
    "title": "Недостатньо інформації",
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "dateSubmitted": "2021-03-16T00:00:03+02:00",
    "value": {
      "amount": 3000.0,
      "currency": "UAH"
    },
    "status": "accepted",
    "acceptance": true,
    "dateAccepted": "2021-03-16T00:00:03+02:00",
    "reviewDate": "2021-03-16T00:00:03+02:00",
    "reviewPlace": "Place of review",
    "documents": [
      {
        "id": "6145a8f4d0734c89bdf81f7490070da6",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Complaint_Attachment.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a92635d325af4c189f379084748c6438?Signature=1FOxCA%2FFB2FgpF98n7ESYr7DL96IPpT18GwLAKyqmZEcpeydMb9Zi0XknAkDFUy2IVxH9uErCUkASamE%2BFcwCA%3D%3D&KeyID=a8968c46",
        "datePublished": "2021-03-16T00:00:03+02:00",
        "dateModified": "2021-03-16T00:00:03+02:00",
        "author": "complaint_owner",
        "documentOf": "tender",
        "language": "uk"
      }
    ]
  }
}

