GET /api/2.5/tenders/eff507bb175146d79ff6ae32a0c94c04/awards/fa643eda48dd450bb2a289aa80f13e85/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "4a38f00694774a2e846f7e2a6535703d",
      "complaintID": "UA-2021-03-16-000001-a.1",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "dateDecision": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "satisfied",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:03+02:00",
      "reviewDate": "2021-03-16T00:00:03+02:00",
      "reviewPlace": "Place of review",
      "documents": [
        {
          "id": "2d5d8d416c1d43cd94df8b95ca39aac2",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Complaint_Attachment.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c4131fd62e1246fe984547bddecceb84?Signature=9QRUeKsj3r1nMsnB9SGcga8ybnoDsYvuADXSmHrtt%2BVG2vv05KN0XKKy4idM%2BSoounPI1UIjiIohfBWiQNdtAQ%3D%3D&KeyID=a8968c46",
          "datePublished": "2021-03-16T00:00:03+02:00",
          "dateModified": "2021-03-16T00:00:03+02:00",
          "author": "complaint_owner",
          "documentOf": "tender",
          "language": "uk"
        },
        {
          "id": "303b92d6aada4e1dbfcef84996e6567f",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ComplaintResolution.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9490e878261f4fd1a919a65843a13df3?Signature=QhRB642BNnFgEyW6IBU89grmEfwAOSpfsSr9U0dcaIl6QPDLAm9bd4bBkawvJ9XKQbqrKCsUH0qjuU7KWiV%2BDQ%3D%3D&KeyID=a8968c46",
          "datePublished": "2021-03-16T00:00:03+02:00",
          "dateModified": "2021-03-16T00:00:03+02:00",
          "author": "aboveThresholdReviewers",
          "documentOf": "tender",
          "language": "uk"
        }
      ]
    },
    {
      "id": "fc2383286ea0471cb51c0fd1b1d3dc87",
      "complaintID": "UA-2021-03-16-000001-a.2",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "dateDecision": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "rejectReason": "alreadyExists",
      "status": "invalid",
      "acceptance": false
    },
    {
      "id": "1934840b9d0b464592d1272058558854",
      "complaintID": "UA-2021-03-16-000001-a.3",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "dateDecision": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "declined",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:03+02:00",
      "reviewDate": "2021-03-16T00:00:03+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "0bc3d41127fd48b186aea4539f7a966a",
      "complaintID": "UA-2021-03-16-000001-a.4",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "accepted",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:03+02:00",
      "reviewDate": "2021-03-16T00:00:03+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "919c0cd060d44c4cafe858bb1371122d",
      "complaintID": "UA-2021-03-16-000001-a.5",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "decision": "Тендер скасовується замовником",
      "dateDecision": "2021-03-16T00:00:03+02:00",
      "dateCanceled": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "rejectReason": "tenderCancelled",
      "status": "stopped",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:03+02:00",
      "reviewDate": "2021-03-16T00:00:03+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "df36b0ae7ee947e4acefcafa990fdc06",
      "complaintID": "UA-2021-03-16-000001-a.6",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "claim",
      "author": {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно",
      "resolutionType": "resolved",
      "dateAnswered": "2021-03-16T00:00:03+02:00",
      "satisfied": true,
      "status": "answered"
    },
    {
      "id": "65c7d6259ac447c48362a0c3b0716958",
      "complaintID": "UA-2021-03-16-000001-a.7",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "claim",
      "author": {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "resolution": "Вимога не відповідає предмету закупівлі",
      "resolutionType": "invalid",
      "dateAnswered": "2021-03-16T00:00:03+02:00",
      "satisfied": false,
      "status": "answered"
    },
    {
      "id": "b4864402ba1d4a8ab6c44010b2f3f4a3",
      "complaintID": "UA-2021-03-16-000001-a.8",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "pending",
      "posts": [
        {
          "id": "2c6df34379e643978a05a8b7bb59beb8",
          "title": "Уточнення по вимозі",
          "description": "Відсутній документ",
          "author": "aboveThresholdReviewers",
          "recipient": "complaint_owner",
          "datePublished": "2021-03-16T00:00:03+02:00"
        },
        {
          "id": "27c30b8c52e3405eb0f233239fd107cf",
          "title": "Уточнення по вимозі",
          "description": "Додано документ",
          "documents": [
            {
              "id": "1fe0798f0605490b8ec76ff460731614",
              "hash": "md5:00000000000000000000000000000000",
              "title": "post_document_complaint.pdf",
              "format": "application/pdf",
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1faeecd6b10d4e23a716730ee30d2778?Signature=Z10%2FC9W1hXiOGU1rT7UXOaQz85H1iXWKoK1JUwLUWQIL73NXj3hNj8jut1cK90gxe0usAHEBMjRMg1BZwQfoAQ%3D%3D&KeyID=a8968c46",
              "datePublished": "2021-03-16T00:00:03+02:00",
              "dateModified": "2021-03-16T00:00:03+02:00",
              "author": "complaint_owner",
              "documentOf": "tender"
            }
          ],
          "author": "complaint_owner",
          "recipient": "aboveThresholdReviewers",
          "datePublished": "2021-03-16T00:00:03+02:00",
          "relatedPost": "2c6df34379e643978a05a8b7bb59beb8"
        },
        {
          "id": "7659937de4ac4686942d28cc4ababd9b",
          "title": "Уточнення по вимозі",
          "description": "Відсутній документ",
          "author": "aboveThresholdReviewers",
          "recipient": "tender_owner",
          "datePublished": "2021-03-16T00:00:03+02:00"
        },
        {
          "id": "76202b5255d5400f8c786bea5f3087ac",
          "title": "Уточнення по вимозі",
          "description": "Додано документ",
          "documents": [
            {
              "id": "53655d0b722949b193438459d66f96d3",
              "hash": "md5:00000000000000000000000000000000",
              "title": "post_document_tender.pdf",
              "format": "application/pdf",
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1658394562ef49b8a00da93cccbef54a?Signature=MK0mEshJldlfLibdoXVsQFsuOcM0QzA%2FzItzgU7qbcKLTbJ1SfO30%2FNjXhpdY0tsSvVRzio4SQHUbddd9QAxDw%3D%3D&KeyID=a8968c46",
              "datePublished": "2021-03-16T00:00:03+02:00",
              "dateModified": "2021-03-16T00:00:03+02:00",
              "author": "tender_owner",
              "documentOf": "tender"
            }
          ],
          "author": "tender_owner",
          "recipient": "aboveThresholdReviewers",
          "datePublished": "2021-03-16T00:00:03+02:00",
          "relatedPost": "7659937de4ac4686942d28cc4ababd9b"
        }
      ]
    },
    {
      "id": "d7a2d592c58a4ca7a483be64b913301b",
      "complaintID": "UA-2021-03-16-000001-a.9",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "claim",
      "author": {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "status": "claim"
    }
  ]
}

