GET /api/2.5/tenders/9eb167a6c08a4130af77258c680e4ebf/awards/7c4e912c78ea46af96c33febe8b597a9/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "17d57490b21d4bc48ae2f1e7d0130aaf",
      "complaintID": "UA-2021-03-16-000001.1",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "dateDecision": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "satisfied",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:03+02:00",
      "reviewDate": "2021-03-16T00:00:03+02:00",
      "reviewPlace": "Place of review",
      "documents": [
        {
          "id": "6145a8f4d0734c89bdf81f7490070da6",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Complaint_Attachment.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a92635d325af4c189f379084748c6438?Signature=1FOxCA%2FFB2FgpF98n7ESYr7DL96IPpT18GwLAKyqmZEcpeydMb9Zi0XknAkDFUy2IVxH9uErCUkASamE%2BFcwCA%3D%3D&KeyID=a8968c46",
          "datePublished": "2021-03-16T00:00:03+02:00",
          "dateModified": "2021-03-16T00:00:03+02:00",
          "author": "complaint_owner",
          "documentOf": "tender",
          "language": "uk"
        },
        {
          "id": "8b722bf7a08741ba97efc55324bff211",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ComplaintResolution.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/62a1520a7e254e8fa1d07138ec8804a1?Signature=%2FFn2xM7hGCcixWpwHBt0gTaV9wXJ5K0MPLybOq9pLCMypfMw1xCSvYfXtS2jiMQYAp59DVwqjil2i%2BaIz9dIDg%3D%3D&KeyID=a8968c46",
          "datePublished": "2021-03-16T00:00:03+02:00",
          "dateModified": "2021-03-16T00:00:03+02:00",
          "author": "aboveThresholdReviewers",
          "documentOf": "tender",
          "language": "uk"
        }
      ]
    },
    {
      "id": "c810a00070bd40cd934c42d88b2b9a37",
      "complaintID": "UA-2021-03-16-000001.2",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "dateDecision": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "rejectReason": "alreadyExists",
      "status": "invalid",
      "acceptance": false
    },
    {
      "id": "66818f2899b04fe2a64483c15fd2656e",
      "complaintID": "UA-2021-03-16-000001.3",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "dateDecision": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "declined",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:03+02:00",
      "reviewDate": "2021-03-16T00:00:03+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "57862bd50abe415ab99f8c499dc613e3",
      "complaintID": "UA-2021-03-16-000001.4",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "accepted",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:03+02:00",
      "reviewDate": "2021-03-16T00:00:03+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "51dd152c70a44075808ddc036b040a58",
      "complaintID": "UA-2021-03-16-000001.5",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "decision": "Тендер скасовується замовником",
      "dateDecision": "2021-03-16T00:00:03+02:00",
      "dateCanceled": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "rejectReason": "tenderCancelled",
      "status": "stopped",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:03+02:00",
      "reviewDate": "2021-03-16T00:00:03+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "c3d356b5eeaf46b980ab69d192b556ab",
      "complaintID": "UA-2021-03-16-000001.6",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "claim",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно",
      "resolutionType": "resolved",
      "dateAnswered": "2021-03-16T00:00:03+02:00",
      "satisfied": true,
      "status": "answered"
    },
    {
      "id": "25d656e8a2b8468d9075c206f83f0a8f",
      "complaintID": "UA-2021-03-16-000001.7",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "claim",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "resolution": "Вимога не відповідає предмету закупівлі",
      "resolutionType": "invalid",
      "dateAnswered": "2021-03-16T00:00:03+02:00",
      "satisfied": false,
      "status": "answered"
    },
    {
      "id": "3a2168662be1471a85b469fb014329da",
      "complaintID": "UA-2021-03-16-000001.8",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "pending",
      "posts": [
        {
          "id": "2c6df34379e643978a05a8b7bb59beb8",
          "title": "Уточнення по вимозі",
          "description": "Відсутній документ",
          "author": "aboveThresholdReviewers",
          "recipient": "complaint_owner",
          "datePublished": "2021-03-16T00:00:03+02:00"
        },
        {
          "id": "27c30b8c52e3405eb0f233239fd107cf",
          "title": "Уточнення по вимозі",
          "description": "Додано документ",
          "documents": [
            {
              "id": "1fe0798f0605490b8ec76ff460731614",
              "hash": "md5:00000000000000000000000000000000",
              "title": "post_document_complaint.pdf",
              "format": "application/pdf",
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1faeecd6b10d4e23a716730ee30d2778?Signature=Z10%2FC9W1hXiOGU1rT7UXOaQz85H1iXWKoK1JUwLUWQIL73NXj3hNj8jut1cK90gxe0usAHEBMjRMg1BZwQfoAQ%3D%3D&KeyID=a8968c46",
              "datePublished": "2021-03-16T00:00:03+02:00",
              "dateModified": "2021-03-16T00:00:03+02:00",
              "author": "complaint_owner",
              "documentOf": "tender"
            }
          ],
          "author": "complaint_owner",
          "recipient": "aboveThresholdReviewers",
          "datePublished": "2021-03-16T00:00:03+02:00",
          "relatedPost": "2c6df34379e643978a05a8b7bb59beb8"
        },
        {
          "id": "7659937de4ac4686942d28cc4ababd9b",
          "title": "Уточнення по вимозі",
          "description": "Відсутній документ",
          "author": "aboveThresholdReviewers",
          "recipient": "tender_owner",
          "datePublished": "2021-03-16T00:00:03+02:00"
        },
        {
          "id": "76202b5255d5400f8c786bea5f3087ac",
          "title": "Уточнення по вимозі",
          "description": "Додано документ",
          "documents": [
            {
              "id": "53655d0b722949b193438459d66f96d3",
              "hash": "md5:00000000000000000000000000000000",
              "title": "post_document_tender.pdf",
              "format": "application/pdf",
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1658394562ef49b8a00da93cccbef54a?Signature=MK0mEshJldlfLibdoXVsQFsuOcM0QzA%2FzItzgU7qbcKLTbJ1SfO30%2FNjXhpdY0tsSvVRzio4SQHUbddd9QAxDw%3D%3D&KeyID=a8968c46",
              "datePublished": "2021-03-16T00:00:03+02:00",
              "dateModified": "2021-03-16T00:00:03+02:00",
              "author": "tender_owner",
              "documentOf": "tender"
            }
          ],
          "author": "tender_owner",
          "recipient": "aboveThresholdReviewers",
          "datePublished": "2021-03-16T00:00:03+02:00",
          "relatedPost": "7659937de4ac4686942d28cc4ababd9b"
        }
      ]
    },
    {
      "id": "a5c65b0cedfd4992b5463cac3a438f6b",
      "complaintID": "UA-2021-03-16-000001.9",
      "date": "2021-03-16T00:00:03+02:00",
      "type": "claim",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:03+02:00",
      "status": "claim"
    }
  ]
}

