GET /api/2.5/tenders/1a7dc160a6954967bfb3fcd1dd4545d3/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "status": "claim", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachment.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/88195d90b49845ea964625844911d6b3?KeyID=a8968c46&Signature=CaCim6yuARQ357wBMUbSOpomz17PKWhIRlXAFm%2FrbcRjJEQLddblay%252BGTVnHGP0iuAJ6L2PbZujvM431w70TBA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2020-09-08T01:00:00+03:00", 
          "id": "a3fea2c93af9474cb7822eecb2017d48", 
          "dateModified": "2020-09-08T01:00:00+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.1", 
      "date": "2020-09-08T01:00:00+03:00", 
      "type": "claim", 
      "id": "7e3dc2500b644c7b92383564424f5273"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2020-09-08T01:00:00+03:00", 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.2", 
      "date": "2020-09-08T01:00:00+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "7e00f6e93d7242f9bf50e4ac8e43ebab"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2020-09-08T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "reviewDate": "2020-09-08T01:00:00+03:00", 
      "acceptance": true, 
      "value": {
        "currency": "UAH", 
        "amount": 2000.0
      }, 
      "dateAccepted": "2020-09-08T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "ДКП «Школяр»", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.3", 
      "date": "2020-09-08T01:00:00+03:00", 
      "type": "complaint", 
      "id": "2b0ac49405584e64b8cc2663d577caad", 
      "reviewPlace": "Place of review"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "claim", 
      "dateAnswered": "2020-09-08T01:00:00+03:00", 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.4", 
      "date": "2020-09-08T01:00:00+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "677db188466c4663a14f762ec4c29a1f"
    }, 
    {
      "status": "resolved", 
      "dateDecision": "2020-09-08T01:00:00+03:00", 
      "tendererActionDate": "2020-09-08T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "reviewDate": "2020-09-08T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "ДКП «Школяр»", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "value": {
        "currency": "UAH", 
        "amount": 2000.0
      }, 
      "id": "7f34a62567884c49aec9b86fc612ef73", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.5", 
      "date": "2020-09-08T01:00:00+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ce22ea1cedaf413da2bfaaa358f20ca4?KeyID=a8968c46&Signature=vw5NmRZc6PJtNTyGA%252BmmvHgMdPRrp3x%2FoTuT0GmXco%252Bk4SHKSYeuwnVWQ8qbFsXqY2t7DobN%2FGPGzHCpefekBw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2020-09-08T01:00:00+03:00", 
          "id": "7488675be5194835a57f33276c471779", 
          "dateModified": "2020-09-08T01:00:00+03:00"
        }
      ], 
      "reviewPlace": "Place of review", 
      "dateAccepted": "2020-09-08T01:00:00+03:00"
    }, 
    {
      "status": "stopped", 
      "dateCanceled": "2020-09-08T01:00:00+03:00", 
      "dateDecision": "2020-09-08T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "value": {
        "currency": "UAH", 
        "amount": 2000.0
      }, 
      "id": "9351998fecfd448b9bbcb83e490db015", 
      "rejectReason": "tenderCancelled", 
      "dateAccepted": "2020-09-08T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "ДКП «Школяр»", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.6", 
      "date": "2020-09-08T01:00:00+03:00", 
      "type": "complaint", 
      "reviewDate": "2020-09-08T01:00:00+03:00", 
      "reviewPlace": "Place of review"
    }, 
    {
      "status": "accepted", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "ДКП «Школяр»", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "reviewDate": "2020-09-08T01:00:00+03:00", 
      "acceptance": true, 
      "value": {
        "currency": "UAH", 
        "amount": 2000.0
      }, 
      "dateAccepted": "2020-09-08T01:00:00+03:00", 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.7", 
      "date": "2020-09-08T01:00:00+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "fdfc380cc9a840e69e4f96ad12e0fe83", 
      "reviewPlace": "Place of review"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2020-09-08T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "ДКП «Школяр»", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "value": {
        "currency": "UAH", 
        "amount": 2000.0
      }, 
      "rejectReason": "alreadyExists", 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.8", 
      "date": "2020-09-08T01:00:00+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "5c0138f4466a4bffb1ed11c4d7751c87"
    }, 
    {
      "status": "mistaken", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "ДКП «Школяр»", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "value": {
        "currency": "UAH", 
        "amount": 2000.0
      }, 
      "rejectReason": "cancelledByComplainant", 
      "complaintID": "UA-2020-09-08-000001.9", 
      "date": "2020-09-08T01:00:00+03:00", 
      "type": "complaint", 
      "id": "f84bf2cb7aae4fdcae0500dd9c43e322"
    }, 
    {
      "status": "pending", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "ДКП «Школяр»", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "posts": [
        {
          "description": "Відсутній документ", 
          "title": "Уточнення по вимозі", 
          "author": "aboveThresholdReviewers", 
          "datePublished": "2020-09-08T01:00:00+03:00", 
          "recipient": "complaint_owner", 
          "id": "7f5d9ea671294d479da2e8a06659e473"
        }, 
        {
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "post_document_complaint.pdf", 
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/648aef3e96d847e7b2cbff7850df6769?KeyID=a8968c46&Signature=MOSDGwDvPzV8o1U%252BbJfIvX26EYaEX908WNHi%2FsNCEaVnKpNkzvZOBdYAQOsi0WZMnFMyx2P3RUxx2wtWUmGZDA%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2020-09-08T01:00:00+03:00", 
              "id": "9e21a93b28e149789e7532884321c3c9", 
              "dateModified": "2020-09-08T01:00:00+03:00"
            }
          ], 
          "description": "Додано документ", 
          "title": "Уточнення по вимозі", 
          "author": "complaint_owner", 
          "datePublished": "2020-09-08T01:00:00+03:00", 
          "relatedPost": "7f5d9ea671294d479da2e8a06659e473", 
          "recipient": "aboveThresholdReviewers", 
          "id": "ce01adb63f4b43aca3a6a8c23c5d8d69"
        }, 
        {
          "description": "Відсутній документ", 
          "title": "Уточнення по вимозі", 
          "author": "aboveThresholdReviewers", 
          "datePublished": "2020-09-08T01:00:00+03:00", 
          "recipient": "tender_owner", 
          "id": "5f3a8481c5e249729644cad200a4c6b5"
        }, 
        {
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "tender_owner", 
              "title": "post_document_tender.pdf", 
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f85b628a9f36450db4e750c3937500e1?KeyID=a8968c46&Signature=Xm%252BrqBE%2FScFDUcQBdaIKAoPHaWOw%2Fs%2Ft9NJNxyzufh2TeowWePRmJlDA8vXsGY1wF8hfLeUUgLxqGXS23z3CDg%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2020-09-08T01:00:00+03:00", 
              "id": "46228e94467144c199dca7d5330c324c", 
              "dateModified": "2020-09-08T01:00:00+03:00"
            }
          ], 
          "description": "Додано документ", 
          "title": "Уточнення по вимозі", 
          "author": "tender_owner", 
          "datePublished": "2020-09-08T01:00:00+03:00", 
          "relatedPost": "5f3a8481c5e249729644cad200a4c6b5", 
          "recipient": "aboveThresholdReviewers", 
          "id": "c2d08c52033645d983c8f7464c26ac99"
        }
      ], 
      "value": {
        "currency": "UAH", 
        "amount": 2000.0
      }, 
      "dateSubmitted": "2020-09-08T01:00:00+03:00", 
      "complaintID": "UA-2020-09-08-000001.10", 
      "date": "2020-09-08T01:00:00+03:00", 
      "type": "complaint", 
      "id": "b77be1c04a754989b602432418f2e453"
    }
  ]
}

