POST /api/2.5/tenders/1a7dc160a6954967bfb3fcd1dd4545d3/complaints/949127b6d2834a5ba8156ffef63a9a3c/posts?acc_token=f3fcbf245b584352b8ee0c06c6298ad4 HTTP/1.0
Authorization: Bearer broker
Content-Length: 663
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "recipient": "aboveThresholdReviewers", 
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f85b628a9f36450db4e750c3937500e1?KeyID=a8968c46&Signature=Cpx2oLosv17EaAtoLrg9zj3uG0UAwlGJmsY7589oTgusoPvo1LGnUxQox3F1nxVmXN8PSr%2BjlpJTN3CroPXgBg%3D%3D", 
        "title": "post_document_tender.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "relatedPost": "a4b61c81a8cc44d6965de32baa8139e1", 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/1a7dc160a6954967bfb3fcd1dd4545d3/complaints/949127b6d2834a5ba8156ffef63a9a3c/posts/a9acd9a9b014433fa6a1eefc37f23b3b
{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "post_document_tender.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f85b628a9f36450db4e750c3937500e1?KeyID=a8968c46&Signature=Xm%252BrqBE%2FScFDUcQBdaIKAoPHaWOw%2Fs%2Ft9NJNxyzufh2TeowWePRmJlDA8vXsGY1wF8hfLeUUgLxqGXS23z3CDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-05-15T01:00:00+03:00", 
        "id": "fde3d09dd48b4ef994e747cc546ae78a", 
        "dateModified": "2020-05-15T01:00:00+03:00"
      }
    ], 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі", 
    "author": "tender_owner", 
    "datePublished": "2020-05-15T01:00:00+03:00", 
    "relatedPost": "a4b61c81a8cc44d6965de32baa8139e1", 
    "recipient": "aboveThresholdReviewers", 
    "id": "a9acd9a9b014433fa6a1eefc37f23b3b"
  }
}

