POST /api/2.5/tenders/0ba5045de21b4930a220df9887be28ec/qualifications/de1fdfe83be64f45a3aa274d8f98a1e9/complaints?acc_token=cc2916bf8ca94a2d8c1bf5cb04d2a654 HTTP/1.0
Authorization: Bearer broker
Content-Length: 1385
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "draft", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "Вінницька область", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0ba5045de21b4930a220df9887be28ec/qualifications/de1fdfe83be64f45a3aa274d8f98a1e9/complaints/82367eb51f0e4686a9f9aa7745b42041
{
  "access": {
    "transfer": "829a4e6247814f0094e9b29552e2fb9c", 
    "token": "f417333f3a02407188551658e8d9dfc6"
  }, 
  "data": {
    "status": "draft", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "Вінницька область", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "value": {
      "currency": "UAH", 
      "amount": 3000
    }, 
    "complaintID": "UA-2020-05-01-000001.1", 
    "date": "2020-05-01T01:00:01+03:00", 
    "type": "complaint", 
    "id": "82367eb51f0e4686a9f9aa7745b42041"
  }
}

