POST /api/2.5/tenders/b61b0e1aaa1f43adba91292fda2cfaf5/qualifications/0ccff2fe5f7a4d998944aa5847bec01c/complaints/f082de37280042168422ffcf1035c4c3/documents?acc_token=8e96ef8b93cf4518918e40f307812f64 HTTP/1.0
Authorization: Bearer broker
Content-Length: 338
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Complaint_Attachment.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/720538aa95fa4a9fad02f6420ef0cc22?Signature=FJibyBh%2BVrcnFcC4iT3sM%2BuGhotfkEA%2FLPVQyLsdFn5EDqSmqViOQMQoAnqwmzYWGBro1H0UrOM8rX1Pt7MLBQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b61b0e1aaa1f43adba91292fda2cfaf5/qualifications/0ccff2fe5f7a4d998944aa5847bec01c/complaints/f082de37280042168422ffcf1035c4c3/documents/eb96d00527d54a9f9f3eb8d3a902006c
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "eb96d00527d54a9f9f3eb8d3a902006c",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Complaint_Attachment.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/720538aa95fa4a9fad02f6420ef0cc22?Signature=zAiHb01B9tN7weejj6IgEYcRaBTqrMbjAh7Jhs4SuqTm%2Bo1rNJ95N2TGJ8xEUu2dNqr806Lsu8Q307ZXOOO1DQ%3D%3D&KeyID=a8968c46",
    "datePublished": "2021-03-16T00:00:01+02:00",
    "dateModified": "2021-03-16T00:00:01+02:00",
    "author": "complaint_owner",
    "documentOf": "tender",
    "language": "uk"
  }
}

