PATCH /api/2.5/tenders/0ba5045de21b4930a220df9887be28ec/qualifications/de1fdfe83be64f45a3aa274d8f98a1e9/complaints/c4eb9209aa72416c8c029a80816be774 HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 252
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "stopped", 
    "rejectReason": "tenderCancelled", 
    "decision": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopped", 
    "dateCanceled": "2020-05-15T01:00:01+03:00", 
    "dateDecision": "2020-05-15T01:00:01+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "decision": "Тендер скасовується замовником", 
    "acceptance": true, 
    "value": {
      "currency": "UAH", 
      "amount": 3000.0
    }, 
    "id": "c4eb9209aa72416c8c029a80816be774", 
    "rejectReason": "tenderCancelled", 
    "dateAccepted": "2020-05-15T01:00:01+03:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "ДКП «Школяр»", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "Вінницька область", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2020-05-15T01:00:01+03:00", 
    "complaintID": "UA-2020-05-15-000001.5", 
    "date": "2020-05-15T01:00:01+03:00", 
    "type": "complaint", 
    "reviewDate": "2020-05-15T01:00:01+03:00", 
    "reviewPlace": "Place of review"
  }
}

