GET /api/2.5/tenders/b61b0e1aaa1f43adba91292fda2cfaf5/qualifications/e55187f774a4459b956756a96aac6406/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "d5df8a022c8d49eba3f98a83c686bc84",
      "complaintID": "UA-2021-03-16-000001.1",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "tendererAction": "Умови виправлено",
      "tendererActionDate": "2021-03-16T00:00:01+02:00",
      "dateDecision": "2021-03-16T00:00:01+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "resolved",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:01+02:00",
      "reviewDate": "2021-03-16T00:00:01+02:00",
      "reviewPlace": "Place of review",
      "documents": [
        {
          "id": "eb96d00527d54a9f9f3eb8d3a902006c",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Complaint_Attachment.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/720538aa95fa4a9fad02f6420ef0cc22?Signature=zAiHb01B9tN7weejj6IgEYcRaBTqrMbjAh7Jhs4SuqTm%2Bo1rNJ95N2TGJ8xEUu2dNqr806Lsu8Q307ZXOOO1DQ%3D%3D&KeyID=a8968c46",
          "datePublished": "2021-03-16T00:00:01+02:00",
          "dateModified": "2021-03-16T00:00:01+02:00",
          "author": "complaint_owner",
          "documentOf": "tender",
          "language": "uk"
        },
        {
          "id": "77dd84f2a6ca4f17a9d29b4f07d5b557",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ComplaintResolution.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bf41b7dcccd54e8686f067364d4646dd?Signature=iQ9S72x4kIW%2Fl3HpwPiqvn2eS1s1HJCku8jGvl4eUGJIcqkw1%2BYSDXq%2F%2FkmEFuwk06mlGj4fkL%2BX5TH8t7vvDg%3D%3D&KeyID=a8968c46",
          "datePublished": "2021-03-16T00:00:01+02:00",
          "dateModified": "2021-03-16T00:00:01+02:00",
          "author": "aboveThresholdReviewers",
          "documentOf": "tender",
          "language": "uk"
        }
      ]
    },
    {
      "id": "f84e604dafd74266b95541e70918cfaf",
      "complaintID": "UA-2021-03-16-000001.2",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "dateDecision": "2021-03-16T00:00:01+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "rejectReason": "alreadyExists",
      "status": "invalid",
      "acceptance": false
    },
    {
      "id": "85044ebfeca44c4795b0d34cde555554",
      "complaintID": "UA-2021-03-16-000001.3",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "dateDecision": "2021-03-16T00:00:01+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "declined",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:01+02:00",
      "reviewDate": "2021-03-16T00:00:01+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "1412d556af2346fab0ecc731b93c6bc5",
      "complaintID": "UA-2021-03-16-000001.4",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "accepted",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:01+02:00",
      "reviewDate": "2021-03-16T00:00:01+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "e6aa474a9d614bc0847e8362d511c729",
      "complaintID": "UA-2021-03-16-000001.5",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "decision": "Тендер скасовується замовником",
      "dateDecision": "2021-03-16T00:00:01+02:00",
      "dateCanceled": "2021-03-16T00:00:01+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "rejectReason": "tenderCancelled",
      "status": "stopped",
      "acceptance": true,
      "dateAccepted": "2021-03-16T00:00:01+02:00",
      "reviewDate": "2021-03-16T00:00:01+02:00",
      "reviewPlace": "Place of review"
    },
    {
      "id": "f401c513a01c4b8e90053cc2a8c29d88",
      "complaintID": "UA-2021-03-16-000001.6",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "claim",
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно",
      "resolutionType": "resolved",
      "dateAnswered": "2021-03-16T00:00:01+02:00",
      "satisfied": true,
      "status": "answered",
      "bid_id": "0d5446bf72764450aa66b24c8172e71d"
    },
    {
      "id": "ab1153b9a7684f14a3c4cf479d2f1786",
      "complaintID": "UA-2021-03-16-000001.7",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "claim",
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "resolution": "Вимога не відповідає предмету закупівлі",
      "resolutionType": "invalid",
      "dateAnswered": "2021-03-16T00:00:01+02:00",
      "satisfied": false,
      "status": "answered",
      "bid_id": "0d5446bf72764450aa66b24c8172e71d"
    },
    {
      "id": "8e25888b9df74ca4872cfa3d3020e761",
      "complaintID": "UA-2021-03-16-000001.8",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "status": "pending",
      "posts": [
        {
          "id": "5232e91d15da421b8330928601470bf3",
          "title": "Уточнення по вимозі",
          "description": "Відсутній документ",
          "author": "aboveThresholdReviewers",
          "recipient": "complaint_owner",
          "datePublished": "2021-03-16T00:00:01+02:00"
        },
        {
          "id": "f7c4c63fe83842d7b68ee15dd7021c0a",
          "title": "Уточнення по вимозі",
          "description": "Додано документ",
          "documents": [
            {
              "id": "dff95a6a2b4e4b039f17b28f804a9c43",
              "hash": "md5:00000000000000000000000000000000",
              "title": "post_document_complaint.pdf",
              "format": "application/pdf",
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f3ade0fbc9f34687b3fb8649c13e1b75?Signature=%2BmS22rGZQy0KAc%2BkNTebwrpSCb5AnZRirVGHNVCUzppse9XMrUsZgzR5gOsCclTRkluh3Q%2F7UI56Jlk8S9ueAA%3D%3D&KeyID=a8968c46",
              "datePublished": "2021-03-16T00:00:01+02:00",
              "dateModified": "2021-03-16T00:00:01+02:00",
              "author": "complaint_owner",
              "documentOf": "tender"
            }
          ],
          "author": "complaint_owner",
          "recipient": "aboveThresholdReviewers",
          "datePublished": "2021-03-16T00:00:01+02:00",
          "relatedPost": "5232e91d15da421b8330928601470bf3"
        },
        {
          "id": "cfeb55a9c3f543579aea3c5ec1bd7c77",
          "title": "Уточнення по вимозі",
          "description": "Відсутній документ",
          "author": "aboveThresholdReviewers",
          "recipient": "tender_owner",
          "datePublished": "2021-03-16T00:00:01+02:00"
        },
        {
          "id": "eba129efd2e746c499b339ac1ec0b77c",
          "title": "Уточнення по вимозі",
          "description": "Додано документ",
          "documents": [
            {
              "id": "5f77f7d488144e5698dbc81bbe2d9eb9",
              "hash": "md5:00000000000000000000000000000000",
              "title": "post_document_tender.pdf",
              "format": "application/pdf",
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/271caeb9055f49a79fb5650656ee0dfb?Signature=xXGOFtFsjG%2Bej%2B3MFLUaOdZgIejvTZqnYpM3z8iavA5MpRTXAyyQj42I16waL5mzwU1ygtqqMqrvwWUUWHuQCw%3D%3D&KeyID=a8968c46",
              "datePublished": "2021-03-16T00:00:01+02:00",
              "dateModified": "2021-03-16T00:00:01+02:00",
              "author": "tender_owner",
              "documentOf": "tender"
            }
          ],
          "author": "tender_owner",
          "recipient": "aboveThresholdReviewers",
          "datePublished": "2021-03-16T00:00:01+02:00",
          "relatedPost": "cfeb55a9c3f543579aea3c5ec1bd7c77"
        }
      ]
    },
    {
      "id": "29f29d48e9a949e19b1e54c8eefe00ec",
      "complaintID": "UA-2021-03-16-000001.9",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "claim",
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "dateSubmitted": "2021-03-16T00:00:01+02:00",
      "status": "claim",
      "bid_id": "0d5446bf72764450aa66b24c8172e71d"
    },
    {
      "id": "e1f508398c204befbe0b08b37779d07b",
      "complaintID": "UA-2021-03-16-000001.10",
      "date": "2021-03-16T00:00:01+02:00",
      "type": "complaint",
      "author": {
        "name": "ДКП «Школяр»",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "ДКП «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        }
      },
      "title": "Недостатньо інформації",
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
      "value": {
        "amount": 3000.0,
        "currency": "UAH"
      },
      "rejectReason": "cancelledByComplainant",
      "status": "mistaken"
    }
  ]
}

