POST /api/2.5/tenders/6441fa52dc6b4f018c96a6adfa1edfc5/qualifications/0ccff2fe5f7a4d998944aa5847bec01c/complaints?acc_token=393d624302c64876a31ef45757c26eb6 HTTP/1.0
Authorization: Bearer broker
Content-Length: 1757
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "title": "Недостатньо інформації",
    "type": "claim",
    "author": {
      "address": {
        "countryName": "Україна",
        "locality": "м. Вінниця",
        "postalCode": "21100",
        "region": "Вінницька область",
        "streetAddress": "вул. Островського, 33"
      },
      "contactPoint": {
        "email": "soleksuk@gmail.com",
        "name": "Сергій Олексюк",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
        "id": "00137256",
        "uri": "http://www.sc.gov.ua/"
      },
      "name": "ДКП «Школяр»"
    },
    "status": "claim"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/6441fa52dc6b4f018c96a6adfa1edfc5/qualifications/0ccff2fe5f7a4d998944aa5847bec01c/complaints/f472589af95e4dee93f8e83f05fd6356
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "f472589af95e4dee93f8e83f05fd6356",
    "complaintID": "UA-2023-01-01-000001-a.6",
    "date": "2023-01-01T00:00:01+02:00",
    "type": "claim",
    "title": "Недостатньо інформації",
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "dateSubmitted": "2023-01-01T00:00:01+02:00",
    "status": "claim",
    "bid_id": "371145a097ed44349ae3ffa5600f24dc"
  },
  "access": {
    "token": "9b25e02e4bae40d2af54fa884e2a2d23",
    "transfer": "492f7cacd3084029bd07aea8c48f3ca8"
  }
}

