GET /violation_reports?offset=1760598968.0.1.402322bdc529b2a2ba4ee53ba1042c99 HTTP/1.0


HTTP/1.0 200 OK
Content-Type: application/json; charset=utf-8
X-Request-ID: 88888888-4444-5555-6666-000000000033
Content-Length: 453

{
  "data": [],
  "next_page": {
    "offset": "1760598968.0.1.402322bdc529b2a2ba4ee53ba1042c99",
    "path": "/violation_reports?offset=1760598968.0.1.402322bdc529b2a2ba4ee53ba1042c99",
    "uri": "http://public-api-sandbox.prozorro.gov.ua/violation_reports?offset=1760598968.0.1.402322bdc529b2a2ba4ee53ba1042c99"
  },
  "prev_page": {
    "offset": "",
    "path": "/violation_reports?descending=1",
    "uri": "http://public-api-sandbox.prozorro.gov.ua/violation_reports?descending=1"
  }
}