PATCH /api/2.5/tenders/2a5accd9090044dfba8773895b0bff51/bids/5cff484ac52046ce96d713e75a6af577?acc_token=7e5769dd84b844439dd9a0fce43ff6bc HTTP/1.0
Authorization: Bearer broker
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "d17829b7e1774888aa4678087b41c55b",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True",
        "id": "99d4d8a08099493daedeba7c480b3fc1"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "f0291818215545e7a917f1720f699213",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True",
        "id": "9a48196ce5f24838895701c2a9a2c589"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "c6dd9492a0d4459bbebf02860996a58b",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True",
        "id": "4bcdcaf355744759ab6ecfe3e365e716"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "e02f115815d04a6a979124d5330f19f6",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True",
        "id": "3767a13a4ea241eb96b634e7e2c4cd8e"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "711533d3e9c0486caa2c82a08648e906",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True",
        "id": "c1052e4e871b4420b9ac6cc79e9d4446"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "b4d2fea0e66d40ff81b7ad24a2ff7fc4",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True",
        "id": "7becadac79e54e47852d1bb9ab8a0614"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "178fcf7e4a944654a4930718c37a512a",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True",
        "id": "53dd653b99de48af997d55ea811fb952"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "bf33eed8ddda41879f730a9c8a7f9d2c",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True",
        "id": "1dd53e3491324955a76ea5e2067c8264"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "c57741fffca74be7a2e105b8bdce230e",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True",
        "id": "b6aaee787e52443d86f2874b7cf7dfad"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "5ad6fcaca04d40d490e577a55f6f076b",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True",
        "id": "fd34f1c6df9e402ba72b3b929f7a023e"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "4f22020708de479fb7dba8c2ad40b3b9",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True",
        "id": "895ffa1910f34b7592a63e5f67e49d07"
      }
    ],
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "status": "active",
    "id": "5cff484ac52046ce96d713e75a6af577",
    "date": "2023-01-01T00:00:00+02:00",
    "selfQualified": true,
    "subcontractingDetails": "ДКП «Орфей», Україна"
  }
}

