PATCH /api/2.5/tenders/2a5accd9090044dfba8773895b0bff51/questions/1f5b9a3ac3d848b6b623baa44fe1689e?acc_token=897e40cd3d56497e91e02203d74510ee HTTP/1.0
Authorization: Bearer broker
Content-Length: 162
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "1f5b9a3ac3d848b6b623baa44fe1689e",
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2023-01-01T00:00:00+02:00",
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
    "questionOf": "tender",
    "dateAnswered": "2023-01-01T00:00:00+02:00"
  }
}

