POST /api/2.5/tenders/59d0b67423864278a983b4169d541645/awards/edb54fc7f3c841ce8353f13333adedba/complaints/332321ea73ed4e0092cb91e8d218cd17/documents HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 155
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/59d0b67423864278a983b4169d541645/awards/edb54fc7f3c841ce8353f13333adedba/complaints/332321ea73ed4e0092cb91e8d218cd17/documents/2cb65ac6751b46bdb7df51abc80b41a6
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/416ef6b75dd2474c96f8ed78ce0ff207?KeyID=a8968c46&Signature=nTKK6rey2FHAJUQDEFZPOz9hZgp1YIlPVDBdz1bfKXk%252Bz29ecFMTfeztGKy%2FHFiWPbDNQNNDnTmtGHYDjlTmBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-10-25T01:00:01+03:00", 
    "id": "2cb65ac6751b46bdb7df51abc80b41a6", 
    "dateModified": "2019-10-25T01:00:01+03:00"
  }
}

