GET /api/2.5/tenders/59d0b67423864278a983b4169d541645/awards/edb54fc7f3c841ce8353f13333adedba/complaints/332321ea73ed4e0092cb91e8d218cd17 HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2019-10-25T01:00:01+03:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/caa374e3c11f45889f80841a95e4750a?KeyID=a8968c46&Signature=X%2FXsiNYO%2FXCGkuhz2coXHl5WjjAc2XMKHV9Pdy8sjDxJUUkAwaF9L1yrRoEi9TRPJVC84Jl3En%2F%252BxnQVau32DQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:01+03:00", 
        "id": "24c6751cfb6b47dfad5764f733acc957", 
        "dateModified": "2019-10-25T01:00:01+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/416ef6b75dd2474c96f8ed78ce0ff207?KeyID=a8968c46&Signature=nTKK6rey2FHAJUQDEFZPOz9hZgp1YIlPVDBdz1bfKXk%252Bz29ecFMTfeztGKy%2FHFiWPbDNQNNDnTmtGHYDjlTmBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:01+03:00", 
        "id": "2cb65ac6751b46bdb7df51abc80b41a6", 
        "dateModified": "2019-10-25T01:00:01+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2019-10-25T01:00:01+03:00", 
    "dateSubmitted": "2019-10-25T01:00:01+03:00", 
    "complaintID": "UA-2019-10-25-000001.1", 
    "date": "2019-10-25T01:00:01+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "332321ea73ed4e0092cb91e8d218cd17"
  }
}

