POST /api/2.5/tenders/59d0b67423864278a983b4169d541645/awards/a39c6a95d2674e949a0bf2c2a69f5978/complaints?acc_token=3a42f851ea6a4103a6f919cb6386f655 HTTP/1.0
Authorization: Bearer broker
Content-Length: 1385
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "draft", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "Вінницька область", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/59d0b67423864278a983b4169d541645/awards/a39c6a95d2674e949a0bf2c2a69f5978/complaints/8739ce20f50c41ecbbb6f8d85c75b391
{
  "access": {
    "transfer": "0e724939ecb743cda75f39374ec4c79e", 
    "token": "bbc78a7b197044719d23a863972b3474"
  }, 
  "data": {
    "status": "draft", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "Вінницька область", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "value": {
      "currency": "UAH", 
      "amount": 3000
    }, 
    "complaintID": "UA-2020-05-01-000001.10", 
    "date": "2020-05-01T01:00:01+03:00", 
    "type": "complaint", 
    "id": "8739ce20f50c41ecbbb6f8d85c75b391"
  }
}

