GET /api/2.5/tenders/a450405f3c6840318420a210894cccb1/bids/020c67f8680340e48ada4a03d9a58f08?acc_token=6c750553f8fa4c8c959a1b8f8bccb7a4 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "7b17d2e06ed6436f8064bb0615958cba",
          "title": "Строк дії тендерної пропозиції із дати кінцевого строку подання тендерних пропозицій"
        },
        "value": 90,
        "id": "0c1780ad77244e608b968ab4743ed7d7",
        "unit": {
          "code": "DAY",
          "name": "день"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.BID.VALIDITY_PERIOD"
        }
      },
      {
        "requirement": {
          "id": "f66a262bc0fc40a58518a1fe61f5c2aa",
          "title": "Мова тендерної пропозиції"
        },
        "values": [
          "ukr"
        ],
        "id": "7de2d8d5370847f592929cb5625be926",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.BID.LANGUAGE"
        }
      },
      {
        "requirement": {
          "id": "dae8256533f847d18157ab3d931e0cd6",
          "title": "Учасник закупівлі спроможний виконати обсяг передбачений закупівлею робіт або послуг"
        },
        "value": true,
        "id": "e4eb67e1935d45d1ad67948003c3a6f0",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.SUBCONTRACTING_PROPORTION"
        }
      },
      {
        "requirement": {
          "id": "4b083934cef64356b87263f00b0c1f7b",
          "title": "Відомості про учасника процедури закупівлі не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": true,
        "id": "b7fb3f5ea03f4c77b3e1f98ede46c179",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "5786eb18cb05438a9d82d4ae52b9372e",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": true,
        "id": "2976ec39612241e891b813337ca13f86",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "847e742f17094681ba7f1e6a86dd10f8",
          "title": "Учасник процедури закупівлі протягом останніх трьох років не притягувався до відповідальності за порушення у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів торгів, аукціонів, конкурсів, тендерів"
        },
        "value": true,
        "id": "43293506e9494a06bc36464723ddf3e0",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
        }
      },
      {
        "requirement": {
          "id": "6f75d00cfdde4f978f1173026e566622",
          "title": "Учасник процедури закупівлі не був засуджений за кримінальне правопорушення, вчинене з корисливих мотивів (зокрема, пов’язане з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": true,
        "id": "0e397d02fa8f4d8c8b1dc970743d7c32",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"
        }
      },
      {
        "requirement": {
          "id": "83234514eb1e4ce6a34d02d7b445af58",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": true,
        "id": "bcb38aff48a646b18b813638494ce020",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY"
        }
      },
      {
        "requirement": {
          "id": "7480e71a6973444aa9822d00f79ee1f2",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": true,
        "id": "0bff60ae339a4c58a4a3d078dd870aeb",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.TERRORIST_OFFENCES"
        }
      },
      {
        "requirement": {
          "id": "6f532bbd16cb4b149fe6ebe0b5925f68",
          "title": "Учасника процедури закупівлі не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": true,
        "id": "11771b7a1320441494f366ccbae2c210",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING"
        }
      },
      {
        "requirement": {
          "id": "6cd047982c8d4c0d88c54ccd60dbe840",
          "title": "Учасник процедури закупівлі не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": true,
        "id": "253203dedc2740fe936b93be64f401a4",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_TAXES"
        }
      },
      {
        "requirement": {
          "id": "060c78f741f04b948958f03920263ef0",
          "title": "Учасник процедури закупівлі не мав з цим самим замовником договорів достроково розірваних через невиконання (учасником) своїх зобов'язань через що було застосовано санкції у вигляді штрафів та/або відшкодування збитків"
        },
        "value": true,
        "id": "365851a8403c4c1c92c322fbcc3f52f0",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.EARLY_TERMINATION"
        }
      },
      {
        "requirement": {
          "id": "ae889f73fcfa42eba9ca7e992048cd2c",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\""
        },
        "value": true,
        "id": "cf04d3fa48d841549dd845b95cd41721",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.NATIONAL.OTHER"
        }
      },
      {
        "requirement": {
          "id": "9c661806fa0e48729327574d97df534e",
          "title": "Текст заповнений користувачем"
        },
        "value": true,
        "id": "f04d81c534ee4aa4a0ec446c613c6d94",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.EQUIPMENT"
        }
      }
    ],
    "lotValues": [
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "1a0da17891e04af7a0eda87d40a4a290",
        "status": "pending",
        "date": "2023-10-10T01:01:00+03:00"
      }
    ],
    "tenderers": [
      {
        "name": "Школяр",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        }
      }
    ],
    "status": "invalid",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "id": "020c67f8680340e48ada4a03d9a58f08",
    "date": "2023-10-10T01:01:00+03:00",
    "submissionDate": "2023-10-10T01:01:00+03:00",
    "documents": [
      {
        "confidentiality": "public",
        "documentType": "proposal",
        "id": "58ca9b186c2846f688eaecf8f821fc09",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal.p7s",
        "format": "sign/p7s",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7f0c077b0665474cad7c427b6e53ab37?Signature=mvP6D4QsriaXbp93rPArpZwko6w0Rt5hwLbV5d74A5QWO2aOZHNSQLbiHjwdbgAoWEGFszXrbJdSNygESE4EBQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:00:00+03:00",
        "language": "uk"
      },
      {
        "confidentiality": "public",
        "documentType": "proposal",
        "id": "58ca9b186c2846f688eaecf8f821fc09",
        "datePublished": "2023-10-10T01:01:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "sign.p7s",
        "format": "sign/p7s",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3f8b6d73df0a4dbf850b517d1b20fd0c?Signature=znlW6U0kgw83w1XpDSYyaGxnxwEcG3cR5RBmXGoMwAEIFQMW4ewZH8TV2RDhqLpyiES33wpy6xaHw9npYLKbCQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:01:00+03:00",
        "language": "uk"
      }
    ],
    "selfQualified": true
  }
}

