POST /api/2.5/tenders/7ca938a74b3b44a7979818052b0a8788/complaints/a9ec53adb2a84e70bd9e27f983435e3e/posts?acc_token=6986befa3fe542119671bc80ff86078d HTTP/1.0
Authorization: Bearer broker
Content-Length: 671
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "recipient": "aboveThresholdReviewers", 
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dc507da9609e4f49a70f730a9a26255a?KeyID=a8968c46&Signature=cyp%2B7a%2Fkfu1W0GrmCX9VMMVg7tkLIo1VDsA%2BxUlC0RUvB5WCv2HYDdPxJniaBntMT%2BEPM4bJP4P%2BMJYLYi4jBA%3D%3D", 
        "title": "post_document_tender.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "relatedPost": "4ef98d8197ba453c8b435ba31a47b9ef", 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7ca938a74b3b44a7979818052b0a8788/complaints/a9ec53adb2a84e70bd9e27f983435e3e/posts/8116704db7a24252ab0d9fc86b80d7ec
{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "post_document_tender.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dc507da9609e4f49a70f730a9a26255a?KeyID=a8968c46&Signature=cyp%2B7a%2Fkfu1W0GrmCX9VMMVg7tkLIo1VDsA%2BxUlC0RUvB5WCv2HYDdPxJniaBntMT%2BEPM4bJP4P%2BMJYLYi4jBA%3D%3D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-05-01T01:00:00+03:00", 
        "id": "9a08a1b7d4dc47ffb8cad5f96e763ce9", 
        "dateModified": "2020-05-01T01:00:00+03:00"
      }
    ], 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі", 
    "author": "tender_owner", 
    "datePublished": "2020-05-01T01:00:00+03:00", 
    "relatedPost": "4ef98d8197ba453c8b435ba31a47b9ef", 
    "recipient": "aboveThresholdReviewers", 
    "id": "8116704db7a24252ab0d9fc86b80d7ec"
  }
}

