POST /api/2.5/tenders/a450405f3c6840318420a210894cccb1/cancellations?acc_token=b67eb5061d5445afa4ea2a1bffb1ee5a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reason": "cancellation reason",
    "reasonType": "unFixable"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/a450405f3c6840318420a210894cccb1/cancellations/7d6320fc124f485baee99ff6f984b1e5

{
  "data": {
    "reasonType": "unFixable",
    "reason": "cancellation reason",
    "id": "7d6320fc124f485baee99ff6f984b1e5",
    "date": "2023-10-10T01:02:01+03:00",
    "cancellationOf": "tender",
    "status": "draft"
  }
}

