PATCH /api/2.5/tenders/bac835240efd4adea01560554d7bfdb4/contracts/1887b19211b94348a8c5810a9a72ae60?acc_token=ecfd2afb0d2844039379a26cddd96d93 HTTP/1.0
Authorization: Bearer broker
Content-Length: 54
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "value": {
      "amount": 238,
      "amountNet": 230
    }
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "1887b19211b94348a8c5810a9a72ae60",
    "contractID": "UA-2021-03-16-000001-1",
    "status": "pending",
    "suppliers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro"
      }
    ],
    "date": "2021-03-16T00:00:00+02:00",
    "value": {
      "amount": 238.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true,
      "amountNet": 230.0
    },
    "awardID": "37e4fa2bc4314dfcb7029e987dbd0549",
    "items": [
      {
        "id": "c8240ac851604470952a8ad2038fd9aa",
        "description": "Послуги шкільних їдалень",
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "quantity": 1.0,
        "classification": {
          "description": "Послуги з харчування у школах",
          "scheme": "ДК021",
          "id": "55523100-3"
        },
        "unit": {
          "name": "папір",
          "code": "KGM",
          "value": {
            "amount": 10.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": true
          }
        },
        "deliveryDate": {
          "startDate": "2021-04-05T00:00:00+02:00",
          "endDate": "2021-05-05T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        }
      }
    ]
  }
}

