PATCH /api/2.5/tenders/afbae9188b434d3bb77426b13e9a5165/cancellations/cf322d6f287a48c9aee34f0552fb2414?acc_token=b67eb5061d5445afa4ea2a1bffb1ee5a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reasonType": "forceMajeure"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "cf322d6f287a48c9aee34f0552fb2414",
    "status": "draft",
    "date": "2027-01-01T00:02:01+02:00",
    "reasonType": "forceMajeure",
    "reason": "cancellation reason",
    "cancellationOf": "tender"
  }
}

