PUT /api/2.5/tenders/afbae9188b434d3bb77426b13e9a5165/documents/f6225b07e8094774b69d16b987ee7456?acc_token=b67eb5061d5445afa4ea2a1bffb1ee5a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "AwardCriteria.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6b685322d12b4938a1485f15d7b8055c?Signature=3Qgbo0RcfT7yjH%2B%2BgtfYbyGD1pyGyDN8ZvTnh0kYG01xDahw0CQQ024eGEulXGd1NeNDmtkJAW1JTqc23OjeBQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "confidentiality": "public",
    "id": "f6225b07e8094774b69d16b987ee7456",
    "datePublished": "2027-01-01T00:00:00+02:00",
    "hash": "md5:00000000000000000000000000000000",
    "title": "AwardCriteria.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6b685322d12b4938a1485f15d7b8055c?Signature=Gqk57hUOrPwtwykDL1i7JDzVqpuQJOvTiHQ3vw9152GolAqDD10cXonoHkNGN%2Byv054UsWYfd33%2Bgze1Mo3EDg%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "dateModified": "2027-01-01T00:00:00+02:00",
    "author": "tender_owner",
    "language": "uk"
  }
}

