POST /api/2.5/tenders/7898ec9992af47ccbc9b8bf1b8539660/bids/338f854402e74ffc9a09603fc72c3d8f/documents?acc_token=209d79fd54db4c518400dd7525b7be77 HTTP/1.0
Authorization: Bearer broker
Content-Length: 144
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Proposal.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7898ec9992af47ccbc9b8bf1b8539660/bids/338f854402e74ffc9a09603fc72c3d8f/documents/07dfe53c1e8448ffb734b2b3695ef6a8
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "bid_owner", 
    "title": "Proposal.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7898ec9992af47ccbc9b8bf1b8539660/bids/338f854402e74ffc9a09603fc72c3d8f/documents/07dfe53c1e8448ffb734b2b3695ef6a8?download=30a1ef5611344de5849e6449f51ff0a2", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2020-09-08T01:00:00+03:00", 
    "id": "07dfe53c1e8448ffb734b2b3695ef6a8", 
    "dateModified": "2020-09-08T01:00:00+03:00"
  }
}

