POST /api/2.5/tenders/cfe5c8353224465681cea90b38b3ba5d/cancellations/e382ef99376b49ffadfbc1d4135e362a/documents?acc_token=0a7070152a044608bc2bafe9dd5c9c6d HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "sign.p7s",
    "documentType": "cancellationReport",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c1cae7d89feb4e7fbc5689c9d28ef218?Signature=LsOzwAii5713sYViN3tTkiknRBZ628Vg76Ra86ht5GnpSCixwk8qXkUufgRlS0f6MVAvb7Guw8DwHXihQxCdBQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pkcs7-signature"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/cfe5c8353224465681cea90b38b3ba5d/cancellations/e382ef99376b49ffadfbc1d4135e362a/documents/c343ca45f2f84abcbb5f404a619f3a7d

{
  "data": {
    "confidentiality": "public",
    "documentType": "cancellationReport",
    "hash": "md5:00000000000000000000000000000000",
    "title": "sign.p7s",
    "format": "application/pkcs7-signature",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c1cae7d89feb4e7fbc5689c9d28ef218?Signature=KLeL93NGr2%2FpRWFWn7zztZop46JFfHNU0OEtiBLRcXYZDztR1Zd3z0fbMs7H%2FJwVhNSwDZLdndgMkI38t8WjCw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "c343ca45f2f84abcbb5f404a619f3a7d",
    "datePublished": "2027-01-01T00:02:01+02:00",
    "dateModified": "2027-01-01T00:02:01+02:00"
  }
}

