PATCH /api/2.5/submissions/9c1ec0cf104142db84d35398c609cd4b?acc_token=2cac1d46cb17481595607b2d32aef48f HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "deleted"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "tenderers": [
      {
        "name": "НАЗВА",
        "scale": "micro",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»"
        },
        "address": {
          "countryName": "Україна",
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "telephone": "+380432216930",
          "email": "soleksuk@gmail.com"
        }
      }
    ],
    "documents": [
      {
        "id": "3c54826fd7094702be0dda50a229e372",
        "datePublished": "2027-01-17T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "submission_docs.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/07db5aa1fd3447f095c5729879cbba50?Signature=NH9XIEgn09VgF1sfuu%2F20ArTAa1mluQh4JRbQwpiui6Zq6KxFlKHN1FWCghmFuRDNHiNvaNLVmZ2UnVgIroZBA%3D%3D&KeyID=a8968c46",
        "dateModified": "2027-01-17T00:00:00+02:00",
        "language": "uk",
        "confidentiality": "public"
      },
      {
        "documentType": "technicalSpecifications",
        "id": "a4316bb364aa4dc293ec34b88166e417",
        "datePublished": "2027-01-17T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "specs.doc",
        "format": "application/msword",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/submissions/9c1ec0cf104142db84d35398c609cd4b/documents/a4316bb364aa4dc293ec34b88166e417?download=7f19dbc3120f4fb7b70d566828100d5c",
        "dateModified": "2027-01-17T00:00:00+02:00",
        "language": "uk",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Дуже конфіденційний файл, треба приховати"
      }
    ],
    "frameworkID": "932c7023588f40f4aec26aef109f4998",
    "status": "deleted",
    "dateModified": "2027-01-17T00:00:00+02:00",
    "date": "2027-01-17T00:00:00+02:00",
    "owner": "broker",
    "submissionType": "internationalFinancialInstitutions",
    "id": "9c1ec0cf104142db84d35398c609cd4b"
  },
  "config": {
    "restricted": false
  }
}

