GET /api/2.5/submissions/995d8a97b6c24a0cbe9ed82fe2cd8e8b/documents HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "submission_docs.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/07db5aa1fd3447f095c5729879cbba50?Signature=NH9XIEgn09VgF1sfuu%2F20ArTAa1mluQh4JRbQwpiui6Zq6KxFlKHN1FWCghmFuRDNHiNvaNLVmZ2UnVgIroZBA%3D%3D&KeyID=a8968c46",
      "language": "uk",
      "confidentiality": "public",
      "id": "8ee0bc18cff7439586d611936ba513a5",
      "datePublished": "2023-10-26T01:00:00+03:00",
      "dateModified": "2023-10-26T01:00:00+03:00"
    }
  ]
}

