PATCH /api/2.5/tenders/118fb7835ef441e7881da132730071d0/bids/491bd82fa1194201a8f22f80bf137f4e?acc_token=66270151439f490aa975e85f2fe2f831 HTTP/1.0
Authorization: Bearer broker
Content-Length: 14525
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "pending",
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "53fbb305ed824ae4835a50317398d070",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a0344f64252a4c61a77f210515c3e74d",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "05a8b6180ce14407802bb89e4d0230eb",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "796563808ab3418790b8c794a71b18d3",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "d2d9e0bcf0cd4964ba3c8e9d03f7046f",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "9bab20cbe9fc4fcebd9f439033528d84",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "f61cadf02b9340f1babc022ae3d7f379",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "53a5f02c0f9743f995d4a73656fe22ab",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "7c4b66f7ea954c7097b040c783a80940",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "0bb396c749d64869a8d17ba7644c2ca8",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "9a74b39165244161bff0bdcbfcd1a76f",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": true
      }
    ]
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "id": "97a17b78625349b3bd2b2267debc8626",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "53fbb305ed824ae4835a50317398d070",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True"
      },
      {
        "id": "ba7bf442544d46c5ab4a66449cdea996",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a0344f64252a4c61a77f210515c3e74d",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True"
      },
      {
        "id": "9a0df4993d5745428462e0bc6283f213",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "05a8b6180ce14407802bb89e4d0230eb",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True"
      },
      {
        "id": "af1bc417b1da4d58a433adaa6f6e42aa",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "796563808ab3418790b8c794a71b18d3",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True"
      },
      {
        "id": "938f026e9e004a61948dd7c557ec643d",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "d2d9e0bcf0cd4964ba3c8e9d03f7046f",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True"
      },
      {
        "id": "30016eb7647c477fbc3786f0eeed3f2f",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "9bab20cbe9fc4fcebd9f439033528d84",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True"
      },
      {
        "id": "40bc5ae078dd4809a852d8ee670de488",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "f61cadf02b9340f1babc022ae3d7f379",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True"
      },
      {
        "id": "3d577f8ca5a944fcbfd970849e22c966",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "53a5f02c0f9743f995d4a73656fe22ab",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True"
      },
      {
        "id": "19a204e9a7a94a238dfbbd27c7641172",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "7c4b66f7ea954c7097b040c783a80940",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True"
      },
      {
        "id": "ace26eeed391444e9291604970390687",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "0bb396c749d64869a8d17ba7644c2ca8",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True"
      },
      {
        "id": "c0357d83f7664942994458219f759d3f",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "9a74b39165244161bff0bdcbfcd1a76f",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True"
      }
    ],
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "id": "491bd82fa1194201a8f22f80bf137f4e",
    "date": "2023-01-01T00:00:00+02:00",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "selfQualified": true,
    "status": "pending"
  }
}

