PATCH /api/2.5/tenders/50c82523038349969f53f3e238932c46/questions/ce4ede90660e4efbaad13eafee008821?acc_token=90e5c1d7c0414b99a392234aee8cd1dc HTTP/1.0
Authorization: Bearer broker
Content-Length: 162
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2020-09-08T01:00:00+03:00", 
    "title": "Калорійність", 
    "date": "2020-09-08T01:00:00+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "ce4ede90660e4efbaad13eafee008821", 
    "questionOf": "tender"
  }
}

