PATCH /api/2.5/tenders/cbf8a18d016440eda7c093c080506a8b/qualifications/d38d108669794b50a50dc2a588371b08?acc_token=2182f06aeee14e949d1047d91b89268d HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active",
    "qualified": true,
    "eligible": true
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "d38d108669794b50a50dc2a588371b08",
    "bidID": "526b7a685a8b4427b01d99ca0954cec5",
    "lotID": "1a0adfbe4ac4403796c2a35d1efaf96b",
    "status": "active",
    "date": "2023-10-10T01:03:00+03:00",
    "qualified": true,
    "eligible": true
  }
}

