PATCH /api/2.5/tenders/50c82523038349969f53f3e238932c46/qualifications/bf3b21221bc845f5bb0ff5238b948c33?acc_token=90e5c1d7c0414b99a392234aee8cd1dc HTTP/1.0
Authorization: Bearer broker
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "529f4dbc517942dc8dd3f040cd17ddc4", 
    "date": "2020-05-15T01:00:00+03:00", 
    "id": "bf3b21221bc845f5bb0ff5238b948c33"
  }
}

