GET /api/2.5/tenders/0ffcd2893dee417cb36ace18bfbd7a09/bids/84f890ac1d8342a9997f42451880fb60?acc_token=74c83964c8d5430297b700027b46fe51 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a62ad5b9f6d04109b857273f1015a44e",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True",
        "id": "49dbf1bcf0de449085b3921ec2b64ef9"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "15312c277ec947ed805c85a47a6f3678",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True",
        "id": "ec80bfa92dae46a980b1d1f5d6aa09a1"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "8e39435e7b704ed987a1d08cd48623a7",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True",
        "id": "5a6d0c89c4c044fab8a9c3fc78ea52db"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "159b7383242b4437b0fd14a05c408309",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True",
        "id": "a9df8bb221984e0891ff4d03fd054edf"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "d8721a5375604b09b88aa567d60d6533",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True",
        "id": "5f47e1e03ebd451c8f42931c123f8db0"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "5ef4cc2dd8624ceaba1d7bf9515db0aa",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True",
        "id": "258d447e77084e6787c958a95a352d4c"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "99f5d0b186c64a538f8a85765245985a",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True",
        "id": "a4e89acbd39e40c19feee5e482565b52"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "ca095e95cc16419ba3e9d5e96f538717",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True",
        "id": "a6b98e9834274e1b9c4c2e24c4dbb690"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "e5498e53e726418eb3c75450d26bc62c",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True",
        "id": "14dc32e24a3e42a484db1694aa59ac4a"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "468788a4733b40a494e2a68ce9efdf2c",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True",
        "id": "e74696818f4647419913e44d6b9ed50a"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "691dd7c4cf33499fad339425a6a12a78",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True",
        "id": "55ad1f1983be41c18fd0529e9d6c21c5"
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "telephone": "+380322916930",
          "name": "Андрій Олексюк"
        },
        "scale": "sme"
      }
    ],
    "status": "active",
    "id": "84f890ac1d8342a9997f42451880fb60",
    "date": "2023-10-10T01:00:00+03:00",
    "lotValues": [
      {
        "value": {
          "amount": 499.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "48bd8a7458e346f1beeb61941fa097f0",
        "status": "active",
        "date": "2023-10-10T01:00:00+03:00",
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/0ffcd2893dee417cb36ace18bfbd7a09_48bd8a7458e346f1beeb61941fa097f0?key_for_bid=84f890ac1d8342a9997f42451880fb60"
      }
    ],
    "selfQualified": true,
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/13b7a37e7fcb4e3c89c6012bb35fbe35?Signature=%2BVgDpYFt8ROko6jp3pcCiLuavdVU0ACe67dPgUWQn98xSPsF1jSvtjv0kZBtfwA7RzZ97Nv%2BW9RzSArbzTflBg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "42960ce9a2954113a3b59023daee0258",
        "confidentiality": "public",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "dateModified": "2023-10-10T01:00:00+03:00"
      },
      {
        "id": "3cf7e30f26154033a97c31c0155b30df",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_top_secrets.pdf",
        "format": "application/pdf",
        "url": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0ffcd2893dee417cb36ace18bfbd7a09/bids/84f890ac1d8342a9997f42451880fb60/documents/3cf7e30f26154033a97c31c0155b30df?download=223e4b63a6f54e16bbbcccd903732318",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:00:00+03:00",
        "language": "uk",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair."
      }
    ],
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4b49141e9b54435fa839b33155b0ad4c?Signature=0m0bjjv%2FE4KW7WfTEwAg0WZoNillo4GBUkWt5RKqlgk%2BYSOP84wpxfeG%2FYW2m8Bhduo3epAux0lRCZmrIb38Ag%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "35ab0da1955346fcb62ead18a6989bf2",
        "confidentiality": "public",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "dateModified": "2023-10-10T01:00:00+03:00"
      },
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc2.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4217b439967f4358be4477c7a01fcf02?Signature=fT10tQJXs1FqPvafKQ50cOalNgAZ5Eq7PM1jkms2BP%2B8nzo62zp66HanQtnT3m03cHXAvlliNN551YfKH%2FHACQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "29dd14774e5643c59a117bfabadd4475",
        "confidentiality": "public",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "dateModified": "2023-10-10T01:00:00+03:00"
      }
    ],
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "qualification_document.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0df47249712b48d281e049c4337b9342?Signature=oarUFrP5FbC9WzdRUJSAvPP5yy0r0%2FVXsVzdk3X05PGjX00oQHK9R5PKjPKLgL7uclBBBcO84gfM6Hgx4qg3Aw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "1acdfdecc3264c169cca9ae920ae36d0",
        "confidentiality": "public",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "dateModified": "2023-10-10T01:00:00+03:00"
      }
    ]
  }
}

