GET /api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/bids/594b1190f9644494a581efb9333648c4?acc_token=2bbf824e16a045ddb68192ea4ab04754 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "requirementResponses": [
      {
        "id": "bdd1989b4dfe479abefd4ff611297127",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "ef61590cd6c84d1e90d08bcdc14bde99",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True"
      },
      {
        "id": "46c331618a864749825bb3c30717915e",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "d4eb8f3ec2ee47ec87753ed69237dd7e",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True"
      },
      {
        "id": "63fa2ef01fcf4ac08651d2a183f8d647",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "df61b388ff6b4aaf8f17240a80e8b0c7",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True"
      },
      {
        "id": "46c74ef4a1c54bc6a4a82282d86287da",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "b0430d6df7134066b6449e49b893f4c2",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True"
      },
      {
        "id": "58424cd6970a4c6a8d993888ea681afc",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "9c6d011a32ab4bc698b6ef7f6cb6c3be",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True"
      },
      {
        "id": "4c7d05024815440c99997d5e03a97ac3",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "73e3bb9cc51a4a249f16e20cb7fa737f",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True"
      },
      {
        "id": "b098d33cfe594a71a8ac94be38a11ccb",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "51d8b757e0af4303bce12a5efebfb60f",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True"
      },
      {
        "id": "2b70de5ae67f43fa8c3531787d9b3f01",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a5120942aa0f41db8986a627d55b4f17",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True"
      },
      {
        "id": "8c69cf3601a84308b84364e37de13800",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "54b0be7dc0b24234abdda8261be1021e",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True"
      },
      {
        "id": "19e07392428443a89d9d62359fd3de65",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "9e733bcccf6c4d348531b1e4e781c64c",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True"
      },
      {
        "id": "37ecabf5da384f0a9a2d00fb1b5ba640",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "c84100953ee34240882ab6aec24c08a3",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True"
      }
    ],
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "id": "594b1190f9644494a581efb9333648c4",
    "date": "2023-01-01T00:00:00+02:00",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "selfQualified": true,
    "status": "active",
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bb090978dbf84b9a974d39d03059affd?Signature=kFCxltNyFmL%2F2TfeGuU0Cb6PifLij10Y3jWc3jbRaAthYaNR%2Bc%2BAru%2F%2BBkZhK3UJpSuey91YkkUlAaRTLsr5Cg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "34c4ef931f0e4a6dbbc855f6c140860d",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      },
      {
        "id": "c1899edef04f4b69a8f4b3b1eee48899",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_top_secrets.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/bids/594b1190f9644494a581efb9333648c4/documents/c1899edef04f4b69a8f4b3b1eee48899?download=882ade01f3164c61bf0da13c86c5875b",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair.",
        "language": "uk"
      }
    ],
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/bids/594b1190f9644494a581efb9333648c4/financial_documents/be767a4080734371bb122f33a5cd9ca7?download=b7721cf2ae9f47dc9af82104e2811f5b",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "be767a4080734371bb122f33a5cd9ca7",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      },
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc2.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/bids/594b1190f9644494a581efb9333648c4/financial_documents/f21afc95f0604ecc8d66de6b0e9d6242?download=ee08fcd8d20c4517a6eddcea3858b952",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "f21afc95f0604ecc8d66de6b0e9d6242",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ],
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "qualification_document.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/bids/594b1190f9644494a581efb9333648c4/qualification_documents/8fecf0bc98bb4f1390e2b35c2bdc0a3f?download=ca91037a2a1f426595675bda680031d1",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "8fecf0bc98bb4f1390e2b35c2bdc0a3f",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ],
    "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/21b59cfa191a41eaaeb418282327d481?key_for_bid=594b1190f9644494a581efb9333648c4"
  }
}

