GET /api/2.5/tenders/1ee782bb9bb14b8e92d250a14317d067/bids/88d8e0d7211445dfbd33d16c77a599c9?acc_token=35cdaa52ee834652b4e862ba44461060 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "647c6218dffe4e81b8512c077d6c145d",
          "title": "Учасник процедури закупівлі протягом останніх трьох років не притягувався до відповідальності за порушення у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів торгів, аукціонів, конкурсів, тендерів"
        },
        "value": true,
        "id": "b054dc1b00c042fe9a995bbc3e85e93a",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
        }
      },
      {
        "requirement": {
          "id": "747dc48786094d8484967bbf58f2d16e",
          "title": "Учасник процедури закупівлі не був засуджений за кримінальне правопорушення, вчинене з корисливих мотивів (зокрема, пов’язане з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": true,
        "id": "b69a8929c40447c08b22a0b5c088af0f",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"
        }
      },
      {
        "requirement": {
          "id": "5de5b486141842eb8b32c7a6756812fb",
          "title": "Відомості про учасника процедури закупівлі не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": true,
        "id": "f482dc04f19d4618b39c47cee7e83037",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "67faea7d02c64ec9be5acda635007911",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": true,
        "id": "7bff31138aa34a90a44a58f072e21dcb",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "2dc41f257f2e4a16ab55563b4af28eb4",
          "title": "Учасника процедури закупівлі не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": true,
        "id": "259608a05c6a4f4c974ebcdc0986676e",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING"
        }
      },
      {
        "requirement": {
          "id": "9eaaf55eb6da4d88a387b6be6be9c96e",
          "title": "Учасник процедури закупівлі не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": true,
        "id": "38db01bfd43444a5ad8b53623595a7cd",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_TAXES"
        }
      },
      {
        "requirement": {
          "id": "bb8c00a2e6b7402590f23f950ea3cfad",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": true,
        "id": "1eb70da48fe541759f8e4d71c25f18db",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY"
        }
      },
      {
        "requirement": {
          "id": "d21f16fb45814b53a825eeee83986558",
          "title": "Учасник процедури закупівлі не мав з цим самим замовником договорів достроково розірваних через невиконання (учасником) своїх зобов'язань через що було застосовано санкції у вигляді штрафів та/або відшкодування збитків"
        },
        "value": true,
        "id": "1dace381fe6f40fcbea4090a99c43396",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.EARLY_TERMINATION"
        }
      },
      {
        "requirement": {
          "id": "1f4134d886b74131937d794e6d2e777a",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": true,
        "id": "f5679643518745e1a92dc93940ff360a",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.TERRORIST_OFFENCES"
        }
      },
      {
        "requirement": {
          "id": "783e724d02314f628b7cc87d3a5a6b36",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\""
        },
        "value": true,
        "id": "c0e3fe18219241229593c11ae6a8632a",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.NATIONAL.OTHER"
        }
      },
      {
        "requirement": {
          "id": "26d5cc3f36f34617bb705ff72a68f270",
          "title": "Мова тендерної пропозиції"
        },
        "values": [
          "Українська"
        ],
        "id": "66922a0bc6a24df28ed082977558b6a8",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.BID.LANGUAGE"
        }
      },
      {
        "requirement": {
          "id": "a0b42be92c6748bfa3480fa851b4335e",
          "title": "Наявність обладнання, матеріально-технічної бази та технологій"
        },
        "value": true,
        "id": "ec686637557146bab7662bd08fa1f72c",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.EQUIPMENT"
        }
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Андрій Олексюк",
          "email": "aagt@gmail.com",
          "telephone": "+380322916930"
        },
        "scale": "sme"
      }
    ],
    "status": "active",
    "id": "88d8e0d7211445dfbd33d16c77a599c9",
    "date": "2023-10-10T01:03:00+03:00",
    "lotValues": [
      {
        "value": {
          "amount": 499.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "48bd8a7458e346f1beeb61941fa097f0",
        "status": "active",
        "date": "2023-10-10T01:03:00+03:00",
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/1ee782bb9bb14b8e92d250a14317d067_48bd8a7458e346f1beeb61941fa097f0?key_for_bid=88d8e0d7211445dfbd33d16c77a599c9"
      }
    ],
    "documents": [
      {
        "confidentiality": "public",
        "documentType": "proposal",
        "id": "3b3a980a0987420ebd5cb7d4a36c4b7c",
        "datePublished": "2023-10-10T01:03:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "sign.p7s",
        "format": "sign/pkcs7-signature",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c4dd69e3a06f48e4bf407f86acce9a2b?Signature=q41gScwkiaqqVxZyTid2WJcC9xf1W6SOzr5gXtDAv%2FR1v5hQf5%2B6gmIy3nWTzR5wMTJsFR3WY7E%2Fu71pUmEJDw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:03:00+03:00",
        "language": "uk"
      }
    ],
    "selfQualified": true,
    "submissionDate": "2023-10-10T01:03:00+03:00"
  }
}

