PATCH /api/2.5/tenders/32fc15855e5d49b2bee16930210e1cc2/bids/39c0a24defd844b1a8ce53f8c551b4a0?acc_token=74c83964c8d5430297b700027b46fe51 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "pending"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

null

