GET /api/2.5/tenders/0ffcd2893dee417cb36ace18bfbd7a09/questions/b47dcaea4b324e62bbee27ceb4f9ece1 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "b47dcaea4b324e62bbee27ceb4f9ece1",
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2023-01-01T00:00:00+02:00",
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
    "questionOf": "tender",
    "dateAnswered": "2023-01-01T00:00:00+02:00"
  }
}

