PATCH /api/2.5/tenders/21b59cfa191a41eaaeb418282327d481?acc_token=b3345f8c5f3c446983b73bbe7f073ab7 HTTP/1.0
Authorization: Bearer broker
Content-Length: 60
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "title_en": "Services in school canteens",
    "date": "2021-03-16T00:00:00+02:00",
    "dateModified": "2021-03-16T00:00:00+02:00",
    "dateCreated": "2021-03-16T00:00:00+02:00",
    "tenderID": "UA-2021-03-16-000016-a.2",
    "bids": [
      {
        "tenderers": [
          {
            "name": "ДКП «Школяр»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137256",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 33",
              "locality": "м. Вінниця",
              "region": "Вінницька область",
              "postalCode": "21100",
              "countryName": "Україна"
            },
            "contactPoint": {
              "email": "soleksuk@gmail.com",
              "telephone": "+380432216930",
              "name": "Сергій Олексюк"
            },
            "scale": "micro"
          }
        ],
        "id": "594b1190f9644494a581efb9333648c4",
        "status": "active",
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000",
            "title": "Proposal.pdf",
            "format": "application/pdf",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bb090978dbf84b9a974d39d03059affd?Signature=kFCxltNyFmL%2F2TfeGuU0Cb6PifLij10Y3jWc3jbRaAthYaNR%2Bc%2BAru%2F%2BBkZhK3UJpSuey91YkkUlAaRTLsr5Cg%3D%3D&KeyID=a8968c46",
            "documentOf": "tender",
            "confidentiality": "public",
            "language": "uk",
            "id": "34c4ef931f0e4a6dbbc855f6c140860d",
            "datePublished": "2021-03-16T00:00:00+02:00",
            "dateModified": "2021-03-16T00:00:00+02:00"
          },
          {
            "id": "c1899edef04f4b69a8f4b3b1eee48899",
            "datePublished": "2021-03-16T00:00:00+02:00",
            "hash": "md5:00000000000000000000000000000000",
            "title": "Proposal_top_secrets.pdf",
            "format": "application/pdf",
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/bids/594b1190f9644494a581efb9333648c4/documents/c1899edef04f4b69a8f4b3b1eee48899?download=882ade01f3164c61bf0da13c86c5875b",
            "documentOf": "tender",
            "dateModified": "2021-03-16T00:00:00+02:00",
            "confidentiality": "buyerOnly",
            "confidentialityRationale": "Only our company sells badgers with pink hair.",
            "language": "uk"
          }
        ]
      },
      {
        "tenderers": [
          {
            "name": "ДКП «Книга»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137226",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 34",
              "locality": "м. Львів",
              "region": "Львівська область",
              "postalCode": "79013",
              "countryName": "Україна"
            },
            "contactPoint": {
              "email": "aagt@gmail.com",
              "telephone": "+380322916930",
              "name": "Андрій Олексюк"
            },
            "scale": "sme"
          }
        ],
        "id": "bf5c030edd214089995057e52f697e4d",
        "status": "active"
      },
      {
        "tenderers": [
          {
            "name": "«Кенгуру»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137228",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Коцюбинського, 15",
              "locality": "м. Запоріжя",
              "region": "Запорізька область",
              "postalCode": "79013",
              "countryName": "Україна"
            },
            "contactPoint": {
              "email": "fake@mail.com",
              "telephone": "+380322123456",
              "name": "Іван Карпенко"
            },
            "scale": "large"
          }
        ],
        "id": "4cbed2f36a114794a29509071e5b4dfd",
        "documents": [
          {
            "id": "b1ca83160a364112b1c3d65f10e2a7f5",
            "datePublished": "2021-03-16T00:00:00+02:00",
            "hash": "md5:00000000000000000000000000000000",
            "title": "Proposal_part1.pdf",
            "format": "application/pdf",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bd22239ca7e843b5a9b78629492dd7ef?Signature=hn64tIoU1SMP2A3RWyThO%2F59nkS2V%2BWRPLPhDALx9aH1K0jIC%2FUaGcadYcO%2BGjNJnKGHwGH%2FR%2Fmi04t2efQPBQ%3D%3D&KeyID=a8968c46",
            "documentOf": "tender",
            "dateModified": "2021-03-16T00:00:00+02:00",
            "confidentiality": "public",
            "language": "uk"
          },
          {
            "id": "73ec12922cc24eba8968fdfe614355e5",
            "datePublished": "2021-03-16T00:00:00+02:00",
            "hash": "md5:00000000000000000000000000000000",
            "title": "Proposal_part2.pdf",
            "format": "application/pdf",
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/bids/4cbed2f36a114794a29509071e5b4dfd/documents/73ec12922cc24eba8968fdfe614355e5?download=f2990cef9058446d95845fcdd7c796d2",
            "documentOf": "tender",
            "dateModified": "2021-03-16T00:00:00+02:00",
            "confidentiality": "buyerOnly",
            "confidentialityRationale": "Only our company sells badgers with pink hair.",
            "language": "uk"
          }
        ],
        "eligibilityDocuments": [
          {
            "id": "a59a7199f0bc41c9b66d74fd7929f2d5",
            "datePublished": "2021-03-16T00:00:00+02:00",
            "hash": "md5:00000000000000000000000000000000",
            "title": "eligibility_doc.pdf",
            "format": "application/pdf",
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/bids/4cbed2f36a114794a29509071e5b4dfd/eligibility_documents/a59a7199f0bc41c9b66d74fd7929f2d5?download=3c13822a2b25429caa740bfe269ec59b",
            "documentOf": "tender",
            "dateModified": "2021-03-16T00:00:00+02:00",
            "confidentiality": "public",
            "language": "uk"
          }
        ],
        "selfQualified": true,
        "status": "unsuccessful"
      }
    ],
    "questions": [
      {
        "id": "5c4d8b539f1f40c4a1f6d18512279013",
        "author": {
          "name": "ДКП «Книга»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137226",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 34",
            "locality": "м. Львів",
            "region": "Львівська область",
            "postalCode": "79013",
            "countryName": "Україна"
          },
          "contactPoint": {
            "email": "aagt@gmail.com",
            "telephone": "+380322916930",
            "name": "Андрій Олексюк"
          }
        },
        "title": "Калорійність",
        "description": "Просимо додати таблицю потрібної калорійності харчування",
        "date": "2021-03-16T00:00:00+02:00",
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
        "questionOf": "tender",
        "dateAnswered": "2021-03-16T00:00:00+02:00"
      }
    ],
    "documents": [
      {
        "language": "uk",
        "id": "1d823c922f63490fb2fff9404b39ad89",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Notice.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0ebab89f70e14ee79ac687594e90aa45?Signature=9aoCYzGqWd6EnH2PO5FddFgVKa0%2BzDPyB5hofn0%2FlwHTA%2BGSMyAGVFqho1BSeRayT%2Bjugg3Z26AyoNAr934UCA%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "author": "tender_owner"
      },
      {
        "language": "uk",
        "id": "e6d422a039bb4bfcae375f549535f250",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "AwardCriteria.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0798ddc1fc8c46dd8a2d87c9f95d7a30?Signature=20AJfOxal2dtOCz4JJxLXz%2FUDNFsjbCPZT527W0cTZ1Ief9CLoyYGbXqyNcEFekRLAHQg5tVz%2Flxff%2Bf0MM4DQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "author": "tender_owner"
      },
      {
        "language": "uk",
        "id": "e6d422a039bb4bfcae375f549535f250",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "AwardCriteria-2.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5473b7fdbe7d4b1f8a060c46741239e3?Signature=mdzbJis%2BvVUrG8DwMH%2Bw%2B9PU858eiWVbtO4rbe0q1YK4nO4tUv7VsKVZ8tIT7kdvNcACnbMJdfUdcDZ15A4fAw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "author": "tender_owner"
      }
    ],
    "owner": "broker",
    "title": "Послуги шкільних їдалень",
    "submissionMethod": "electronicAuction",
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "minimalStep": {
      "amount": 5.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "procuringEntity": {
      "name": "ЗОСШ #10 м.Вінниці",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "21725150",
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\"",
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\""
      },
      "address": {
        "streetAddress": "вул. Стахурського. 22",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21027",
        "countryName": "Україна"
      },
      "name_en": "School #10 of Vinnytsia",
      "contactPoint": {
        "telephone": "+380432465302",
        "url": "http://sch10.edu.vn.ua/",
        "name": "Куца Світлана Валентинівна",
        "name_en": "Kutsa Svitlana V.",
        "availableLanguage": "uk"
      },
      "kind": "general"
    },
    "awardCriteria": "lowestCost",
    "enquiryPeriod": {
      "startDate": "2021-02-13T00:00:00+02:00",
      "endDate": "2021-03-06T00:00:00+02:00",
      "clarificationsUntil": "2021-03-18T00:00:00+02:00",
      "invalidationDate": "2021-03-16T00:00:00+02:00"
    },
    "tenderPeriod": {
      "startDate": "2021-02-13T00:00:00+02:00",
      "endDate": "2021-03-16T00:00:00+02:00"
    },
    "qualificationPeriod": {
      "startDate": "2021-03-16T00:00:00+02:00",
      "endDate": "2021-03-21T00:00:00+02:00"
    },
    "qualifications": [
      {
        "id": "37b5b987176b4b91a1d5894c22777487",
        "bidID": "594b1190f9644494a581efb9333648c4",
        "status": "active",
        "date": "2021-03-16T00:00:00+02:00",
        "qualified": true,
        "eligible": true
      },
      {
        "id": "020c6650d6ff49a88cffac8f06fc97dd",
        "bidID": "bf5c030edd214089995057e52f697e4d",
        "status": "active",
        "date": "2021-03-16T00:00:00+02:00",
        "qualified": true,
        "eligible": true
      },
      {
        "id": "1a5abc583b654e1a954ce9cd81eb5288",
        "bidID": "4cbed2f36a114794a29509071e5b4dfd",
        "status": "unsuccessful",
        "date": "2021-03-16T00:00:00+02:00",
        "qualified": false,
        "eligible": false
      }
    ],
    "complaintPeriod": {
      "startDate": "2021-02-15T00:00:00+02:00",
      "endDate": "2021-03-20T00:00:00+02:00"
    },
    "procurementMethodType": "competitiveDialogueEU.stage2",
    "procurementMethod": "selective",
    "items": [
      {
        "id": "f589bbeaad4d48e0a604e79cfdf6c380",
        "description": "Послуги шкільних їдалень",
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "unit": {
          "name": "кілограм",
          "code": "KGM"
        },
        "quantity": 1.0,
        "deliveryDate": {
          "startDate": "2021-04-05T00:00:00+02:00",
          "endDate": "2021-04-16T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "description_en": "Services in school canteens",
        "classification": {
          "description": "Test",
          "scheme": "ДК021",
          "id": "37810000-9"
        }
      }
    ],
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»"
      },
      {
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Книга»"
      },
      {
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137228",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "«Кенгуру»"
      }
    ],
    "status": "active.pre-qualification.stand-still",
    "next_check": "2021-03-21T00:00:00+02:00",
    "auctionPeriod": {
      "shouldStartAfter": "2021-03-21T00:00:00+02:00"
    },
    "id": "21b59cfa191a41eaaeb418282327d481"
  }
}

