GET /api/2.5/tenders/118fb7835ef441e7881da132730071d0/bids?acc_token=0f712374a39145a1be46d1c686df7376 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "requirementResponses": [
        {
          "id": "97a17b78625349b3bd2b2267debc8626",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "53fbb305ed824ae4835a50317398d070",
            "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
          },
          "value": "True"
        },
        {
          "id": "ba7bf442544d46c5ab4a66449cdea996",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "a0344f64252a4c61a77f210515c3e74d",
            "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
          },
          "value": "True"
        },
        {
          "id": "9a0df4993d5745428462e0bc6283f213",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "05a8b6180ce14407802bb89e4d0230eb",
            "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
          },
          "value": "True"
        },
        {
          "id": "af1bc417b1da4d58a433adaa6f6e42aa",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "796563808ab3418790b8c794a71b18d3",
            "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
          },
          "value": "True"
        },
        {
          "id": "938f026e9e004a61948dd7c557ec643d",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "d2d9e0bcf0cd4964ba3c8e9d03f7046f",
            "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
          },
          "value": "True"
        },
        {
          "id": "30016eb7647c477fbc3786f0eeed3f2f",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "9bab20cbe9fc4fcebd9f439033528d84",
            "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
          },
          "value": "True"
        },
        {
          "id": "40bc5ae078dd4809a852d8ee670de488",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "f61cadf02b9340f1babc022ae3d7f379",
            "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
          },
          "value": "True"
        },
        {
          "id": "3d577f8ca5a944fcbfd970849e22c966",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "53a5f02c0f9743f995d4a73656fe22ab",
            "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
          },
          "value": "True"
        },
        {
          "id": "19a204e9a7a94a238dfbbd27c7641172",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "7c4b66f7ea954c7097b040c783a80940",
            "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
          },
          "value": "True"
        },
        {
          "id": "ace26eeed391444e9291604970390687",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "0bb396c749d64869a8d17ba7644c2ca8",
            "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
          },
          "value": "True"
        },
        {
          "id": "c0357d83f7664942994458219f759d3f",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "9a74b39165244161bff0bdcbfcd1a76f",
            "title": "Мова тендерної пропозиції українська"
          },
          "value": "True"
        }
      ],
      "tenderers": [
        {
          "name": "ДКП «Школяр»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137256",
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930",
            "name": "Сергій Олексюк"
          },
          "scale": "micro"
        }
      ],
      "id": "491bd82fa1194201a8f22f80bf137f4e",
      "status": "active",
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bb090978dbf84b9a974d39d03059affd?Signature=kFCxltNyFmL%2F2TfeGuU0Cb6PifLij10Y3jWc3jbRaAthYaNR%2Bc%2BAru%2F%2BBkZhK3UJpSuey91YkkUlAaRTLsr5Cg%3D%3D&KeyID=a8968c46",
          "documentOf": "tender",
          "confidentiality": "public",
          "language": "uk",
          "id": "fb594dcec512419babb89f84318d84ac",
          "datePublished": "2023-01-01T00:00:00+02:00",
          "dateModified": "2023-01-01T00:00:00+02:00"
        },
        {
          "id": "72ccf506832e43ca805a105cb2ba0f2a",
          "datePublished": "2023-01-01T00:00:00+02:00",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal_top_secrets.pdf",
          "format": "application/pdf",
          "url": "/tenders/118fb7835ef441e7881da132730071d0/bids/491bd82fa1194201a8f22f80bf137f4e/documents/72ccf506832e43ca805a105cb2ba0f2a?download=882ade01f3164c61bf0da13c86c5875b",
          "documentOf": "tender",
          "dateModified": "2023-01-01T00:00:00+02:00",
          "confidentiality": "buyerOnly",
          "confidentialityRationale": "Only our company sells badgers with pink hair.",
          "language": "uk"
        }
      ]
    },
    {
      "requirementResponses": [
        {
          "id": "892d4ec8a2b6489c91a428da0e3078c9",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "53fbb305ed824ae4835a50317398d070",
            "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
          },
          "value": "True"
        },
        {
          "id": "66262ffa42e84db0b15abdfa651ae1f2",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "a0344f64252a4c61a77f210515c3e74d",
            "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
          },
          "value": "True"
        },
        {
          "id": "8bf01825b8ec45f1bec0d7125338e197",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "05a8b6180ce14407802bb89e4d0230eb",
            "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
          },
          "value": "True"
        },
        {
          "id": "acef5bd60ccf4d699e9bfc6136bd4c73",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "796563808ab3418790b8c794a71b18d3",
            "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
          },
          "value": "True"
        },
        {
          "id": "1da79562ffe84be594e6a30bcf9ca900",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "d2d9e0bcf0cd4964ba3c8e9d03f7046f",
            "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
          },
          "value": "True"
        },
        {
          "id": "84023870693345ca81071f858079b5d2",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "9bab20cbe9fc4fcebd9f439033528d84",
            "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
          },
          "value": "True"
        },
        {
          "id": "2821e46e0c994a7a87b15cf4cbdaf0ea",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "f61cadf02b9340f1babc022ae3d7f379",
            "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
          },
          "value": "True"
        },
        {
          "id": "99e72f79a6924916a509814edcef3842",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "53a5f02c0f9743f995d4a73656fe22ab",
            "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
          },
          "value": "True"
        },
        {
          "id": "a8fcb1a2797845c9931903697ab922f4",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "7c4b66f7ea954c7097b040c783a80940",
            "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
          },
          "value": "True"
        },
        {
          "id": "92c0a95e5c274e47971c126eb8ea702e",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "0bb396c749d64869a8d17ba7644c2ca8",
            "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
          },
          "value": "True"
        },
        {
          "id": "fec6b6f9d32b4c1c9d3d1ba5f9eb7507",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "9a74b39165244161bff0bdcbfcd1a76f",
            "title": "Мова тендерної пропозиції українська"
          },
          "value": "True"
        }
      ],
      "tenderers": [
        {
          "name": "ДКП «Книга»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137226",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 34",
            "locality": "м. Львів",
            "region": "Львівська область",
            "postalCode": "79013",
            "countryName": "Україна"
          },
          "contactPoint": {
            "email": "aagt@gmail.com",
            "telephone": "+380322916930",
            "name": "Андрій Олексюк"
          },
          "scale": "sme"
        }
      ],
      "id": "ad24bf7eb4804d98aef598e4cd91f42a",
      "status": "active"
    },
    {
      "requirementResponses": [
        {
          "id": "b5cca2134c364b21b4ca2fd0017d8098",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "53fbb305ed824ae4835a50317398d070",
            "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
          },
          "value": "True"
        },
        {
          "id": "f69f48f2f38b40379268d1790817d830",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "a0344f64252a4c61a77f210515c3e74d",
            "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
          },
          "value": "True"
        },
        {
          "id": "6d314d30985c4a2a957e75c4c3639b53",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "05a8b6180ce14407802bb89e4d0230eb",
            "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
          },
          "value": "True"
        },
        {
          "id": "671628e5dcac4391bf6bfc5b00e74512",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "796563808ab3418790b8c794a71b18d3",
            "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
          },
          "value": "True"
        },
        {
          "id": "dfee6677e4044fa4ba4b317456fb4913",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "d2d9e0bcf0cd4964ba3c8e9d03f7046f",
            "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
          },
          "value": "True"
        },
        {
          "id": "ae546e80685a4f8ebfd375f3e214623e",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "9bab20cbe9fc4fcebd9f439033528d84",
            "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
          },
          "value": "True"
        },
        {
          "id": "d4999aec8b404e90a33ae1d1ba67c5ad",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "f61cadf02b9340f1babc022ae3d7f379",
            "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
          },
          "value": "True"
        },
        {
          "id": "797e45b00a224bfe963085b9fac174b1",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "53a5f02c0f9743f995d4a73656fe22ab",
            "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
          },
          "value": "True"
        },
        {
          "id": "4afa83532dec4713b66750c18bbc1351",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "7c4b66f7ea954c7097b040c783a80940",
            "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
          },
          "value": "True"
        },
        {
          "id": "bfdb48ac90cf482d91b175cb46dcd273",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "0bb396c749d64869a8d17ba7644c2ca8",
            "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
          },
          "value": "True"
        },
        {
          "id": "0964f158ae5c46eb89bbd4bc628d3090",
          "title": "Requirement response",
          "description": "some description",
          "requirement": {
            "id": "9a74b39165244161bff0bdcbfcd1a76f",
            "title": "Мова тендерної пропозиції українська"
          },
          "value": "True"
        }
      ],
      "tenderers": [
        {
          "name": "«Кенгуру»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137228",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Коцюбинського, 15",
            "locality": "м. Запоріжя",
            "region": "Запорізька область",
            "postalCode": "79013",
            "countryName": "Україна"
          },
          "contactPoint": {
            "email": "fake@mail.com",
            "telephone": "+380322123456",
            "name": "Іван Карпенко"
          },
          "scale": "large"
        }
      ],
      "id": "298a392577b04a5db2029b0d9268bb21",
      "documents": [
        {
          "id": "1df0ed09cfca48e6b443b0af7b98b963",
          "datePublished": "2023-01-01T00:00:00+02:00",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal_part1.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bd22239ca7e843b5a9b78629492dd7ef?Signature=hn64tIoU1SMP2A3RWyThO%2F59nkS2V%2BWRPLPhDALx9aH1K0jIC%2FUaGcadYcO%2BGjNJnKGHwGH%2FR%2Fmi04t2efQPBQ%3D%3D&KeyID=a8968c46",
          "documentOf": "tender",
          "dateModified": "2023-01-01T00:00:00+02:00",
          "confidentiality": "public",
          "language": "uk"
        },
        {
          "id": "e323af1de85540e682da85c1b363f58c",
          "datePublished": "2023-01-01T00:00:00+02:00",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal_part2.pdf",
          "format": "application/pdf",
          "url": "/tenders/118fb7835ef441e7881da132730071d0/bids/298a392577b04a5db2029b0d9268bb21/documents/e323af1de85540e682da85c1b363f58c?download=f2990cef9058446d95845fcdd7c796d2",
          "documentOf": "tender",
          "dateModified": "2023-01-01T00:00:00+02:00",
          "confidentiality": "buyerOnly",
          "confidentialityRationale": "Only our company sells badgers with pink hair.",
          "language": "uk"
        }
      ],
      "eligibilityDocuments": [
        {
          "id": "3c2e1f95fad74e51bc2656e1324c4574",
          "datePublished": "2023-01-01T00:00:00+02:00",
          "hash": "md5:00000000000000000000000000000000",
          "title": "eligibility_doc.pdf",
          "format": "application/pdf",
          "url": "/tenders/118fb7835ef441e7881da132730071d0/bids/298a392577b04a5db2029b0d9268bb21/eligibility_documents/3c2e1f95fad74e51bc2656e1324c4574?download=3c13822a2b25429caa740bfe269ec59b",
          "documentOf": "tender",
          "dateModified": "2023-01-01T00:00:00+02:00",
          "confidentiality": "public",
          "language": "uk"
        }
      ],
      "selfQualified": true,
      "status": "unsuccessful"
    }
  ]
}

