POST /api/2.5/tenders/1ee782bb9bb14b8e92d250a14317d067/bids HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Львів",
          "postalCode": "79013",
          "region": "Львівська область",
          "streetAddress": "вул. Островського, 34"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "name": "Андрій Олексюк",
          "telephone": "+380322916930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Книга»",
        "scale": "sme"
      }
    ],
    "selfQualified": true,
    "lotValues": [
      {
        "value": {
          "amount": 499
        },
        "relatedLot": "48bd8a7458e346f1beeb61941fa097f0"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/1ee782bb9bb14b8e92d250a14317d067/bids/88d8e0d7211445dfbd33d16c77a599c9

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Андрій Олексюк",
          "email": "aagt@gmail.com",
          "telephone": "+380322916930"
        },
        "scale": "sme"
      }
    ],
    "status": "draft",
    "lotValues": [
      {
        "status": "pending",
        "value": {
          "amount": 499.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "48bd8a7458e346f1beeb61941fa097f0",
        "date": "2023-10-10T01:03:00+03:00"
      }
    ],
    "selfQualified": true,
    "id": "88d8e0d7211445dfbd33d16c77a599c9",
    "date": "2023-10-10T01:03:00+03:00"
  },
  "access": {
    "token": "35cdaa52ee834652b4e862ba44461060",
    "transfer": "703a4f7f33334e0881df9481f00e1347"
  }
}

