POST /api/2.5/tenders/1ee782bb9bb14b8e92d250a14317d067/bids HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Запоріжя",
          "postalCode": "79013",
          "region": "Запорізька область",
          "streetAddress": "вул. Коцюбинського, 15"
        },
        "contactPoint": {
          "email": "fake@mail.com",
          "name": "Іван Карпенко",
          "telephone": "+380322123456"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137228",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "«Кенгуру»",
        "scale": "large",
        "signerInfo": {
          "name": "Test Testovich",
          "telephone": "+380950000000",
          "email": "example@email.com",
          "iban": "111111111111111",
          "authorizedBy": "Статут компанії",
          "position": "Генеральний директор"
        }
      }
    ],
    "selfQualified": true,
    "documents": [
      {
        "title": "Proposal_part1.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/328d5b2129754795ab3332190744419e?Signature=d3nXqlZF%2FUjCp%2BtIr3RACzQLQzbjekeZGtG%2FFto35t3IVzs3lEfkHPyudpqC6%2FlLwY91i3CrXKFG6UuXNonbDg%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      },
      {
        "title": "Proposal_part2.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/42865ab1b0de4861a16a0b26900142e2?Signature=pP%2BhMle%2FlditTh3PYle3zn9JgnocKK9%2Bxg5FZcgIkqaoZRFTwZK8fvB%2FE6uNjz6%2BQrsRMqBXf2f%2BIHeXOMOVDw%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair."
      }
    ],
    "eligibilityDocuments": [
      {
        "title": "eligibility_doc.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7ac6b69cc8b348fe881ef329f6e3a668?Signature=wa2r8roNNka7dUvnUg%2FItMtkXHXdIspkB6pya1sDhmoE8hq8A4jhRjZv0NmGa0AgnP%2BUZmysDw20Ouu%2B12UmAA%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "financialDocuments": [
      {
        "title": "financial_doc.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3717e8740203445a99d0ba3d4a388920?Signature=IHJ%2BEiaRN1mVFCkeAGGWH2yzU5wmJNMBdBG8cOa42rO%2B3V6Kl5hswvIN2nVRNVFLujjo9IvhxpLp4OBI35CGAA%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "qualificationDocuments": [
      {
        "title": "qualification_document.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e7a65edca6534628ab1450eb548cf02a?Signature=GMeQf6UbZ%2Fat%2BGsX6heeADwovMg5WaMhIe9NCxPwx%2BO%2FWrVFkVv9MiuoCQv93%2FJpWmOH1ra6TN0ahhzWDvG2Dg%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "lotValues": [
      {
        "value": {
          "amount": 5
        },
        "relatedLot": "48bd8a7458e346f1beeb61941fa097f0"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/1ee782bb9bb14b8e92d250a14317d067/bids/48b5b53cabfd47d599a5bb5b9f9ee193

{
  "data": {
    "tenderers": [
      {
        "name": "«Кенгуру»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137228",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Коцюбинського, 15",
          "locality": "м. Запоріжя",
          "region": "Запорізька область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Іван Карпенко",
          "email": "fake@mail.com",
          "telephone": "+380322123456"
        },
        "scale": "large",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        }
      }
    ],
    "status": "draft",
    "lotValues": [
      {
        "status": "pending",
        "value": {
          "amount": 5.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "48bd8a7458e346f1beeb61941fa097f0",
        "date": "2023-10-10T01:03:00+03:00"
      }
    ],
    "documents": [
      {
        "confidentiality": "public",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/328d5b2129754795ab3332190744419e?Signature=%2BfJgYx%2F65LEAbnv6PrgVoI4evhRTul5iYRAJSEP%2B7DPnXuKdz5mV2PgArkfwjW07wnaef2b4jut7%2FQmJSwsbAQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "4f85d91368144a4999f6939b0d47473d",
        "datePublished": "2023-10-10T01:03:00+03:00",
        "dateModified": "2023-10-10T01:03:00+03:00"
      },
      {
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair.",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "documentOf": "tender",
        "language": "uk",
        "id": "8541dc9046f44d258ef24a7ed9509768",
        "datePublished": "2023-10-10T01:03:00+03:00",
        "dateModified": "2023-10-10T01:03:00+03:00"
      }
    ],
    "financialDocuments": [
      {
        "confidentiality": "public",
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3717e8740203445a99d0ba3d4a388920?Signature=5XzSldetRi01hhDNbF3ofKcnB%2Fc1jFGE86GGgt2DyF2TfktCNcIZqt61IsSLouGAIO88F6wM4pPf5wjajYz5Cw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "a76823e385494d0fad7384a067b907d2",
        "datePublished": "2023-10-10T01:03:00+03:00",
        "dateModified": "2023-10-10T01:03:00+03:00"
      }
    ],
    "eligibilityDocuments": [
      {
        "confidentiality": "public",
        "hash": "md5:00000000000000000000000000000000",
        "title": "eligibility_doc.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7ac6b69cc8b348fe881ef329f6e3a668?Signature=nQOxpa2%2FmiCN108r4oO41TPcTWSk793in64eiJcAISpSe5bxBf%2BYlL2ewyvkzEekTNcM5YUIZwyg8r%2Fa%2FDCFAg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "4dce2427bf4a48fbb3762e39386626e7",
        "datePublished": "2023-10-10T01:03:00+03:00",
        "dateModified": "2023-10-10T01:03:00+03:00"
      }
    ],
    "qualificationDocuments": [
      {
        "confidentiality": "public",
        "hash": "md5:00000000000000000000000000000000",
        "title": "qualification_document.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e7a65edca6534628ab1450eb548cf02a?Signature=id0UYGt9ByuxscHlNT85NVUGK8jqVIQwpgwwcyyzaOdWQ6%2BhjxCfiqJMLlUtkGArXop3vMHqBYoVSpc3nhRkAw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "bb6f4fef8da741ffad01a7725faffd44",
        "datePublished": "2023-10-10T01:03:00+03:00",
        "dateModified": "2023-10-10T01:03:00+03:00"
      }
    ],
    "selfQualified": true,
    "id": "48b5b53cabfd47d599a5bb5b9f9ee193",
    "date": "2023-10-10T01:03:00+03:00"
  },
  "access": {
    "token": "36e54dba0c6a4c9e8a739d1c5dc2c540",
    "transfer": "5b1aa7e1c3294a76b9c207f09da06c4f"
  }
}

