PATCH /api/2.5/tenders/aa6cf974e101460589085272d5990056/qualifications/1a5abc583b654e1a954ce9cd81eb5288?acc_token=b3345f8c5f3c446983b73bbe7f073ab7 HTTP/1.0
Authorization: Bearer broker
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "1a5abc583b654e1a954ce9cd81eb5288",
    "bidID": "9ee879e314fd487584383884598ae7c7",
    "status": "unsuccessful",
    "date": "2021-03-16T00:00:00+02:00",
    "qualified": false,
    "eligible": false
  }
}

