GET /api/2.5/tenders/0ffcd2893dee417cb36ace18bfbd7a09/bids/cafec8a6e87645a2bf78d530d93c786c?acc_token=b630da6f0eb34e9eb53e8be052b29ef3 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a62ad5b9f6d04109b857273f1015a44e",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True",
        "id": "1ea93fccacb948d0b553a196d52ce31c"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "15312c277ec947ed805c85a47a6f3678",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True",
        "id": "df9e62473ad7474e8bd100e0917d9964"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "8e39435e7b704ed987a1d08cd48623a7",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True",
        "id": "546e3c696e684ef2a7f11fac248fcadb"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "159b7383242b4437b0fd14a05c408309",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True",
        "id": "2a6ca2033bf54ddaa9d5121b3f3e1117"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "d8721a5375604b09b88aa567d60d6533",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True",
        "id": "94c2eb6c760a442f84e9068a72ef4940"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "5ef4cc2dd8624ceaba1d7bf9515db0aa",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True",
        "id": "7671ef464321471797775f757b40978f"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "99f5d0b186c64a538f8a85765245985a",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True",
        "id": "8703bc4b478c4772b61731760ae1fbde"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "ca095e95cc16419ba3e9d5e96f538717",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True",
        "id": "1946acfb57634883a5eb5362a6a3d33f"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "e5498e53e726418eb3c75450d26bc62c",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True",
        "id": "aea86281272c4f10ab04bb4de24bada7"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "468788a4733b40a494e2a68ce9efdf2c",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True",
        "id": "f4171abc3f194ef49cbcc31aad1913a9"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "691dd7c4cf33499fad339425a6a12a78",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True",
        "id": "cfe79e6ad46a4d119c04a03598bb3324"
      }
    ],
    "tenderers": [
      {
        "name": "«Кенгуру»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137228",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Коцюбинського, 15",
          "locality": "м. Запоріжя",
          "region": "Запорізька область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "fake@mail.com",
          "telephone": "+380322123456",
          "name": "Іван Карпенко"
        },
        "scale": "large"
      }
    ],
    "id": "cafec8a6e87645a2bf78d530d93c786c",
    "documents": [
      {
        "id": "36c88d2c6b274c65883820cffe552a2b",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/328d5b2129754795ab3332190744419e?Signature=%2BfJgYx%2F65LEAbnv6PrgVoI4evhRTul5iYRAJSEP%2B7DPnXuKdz5mV2PgArkfwjW07wnaef2b4jut7%2FQmJSwsbAQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      },
      {
        "id": "7f10a54685ee4f44a0fed9c27346e262",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0ffcd2893dee417cb36ace18bfbd7a09/bids/cafec8a6e87645a2bf78d530d93c786c/documents/7f10a54685ee4f44a0fed9c27346e262?download=42865ab1b0de4861a16a0b26900142e2",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair.",
        "language": "uk"
      }
    ],
    "eligibilityDocuments": [
      {
        "id": "b1164ca7ed164020add2f8d1130d2b56",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "eligibility_doc.pdf",
        "format": "application/pdf",
        "url": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0ffcd2893dee417cb36ace18bfbd7a09/bids/cafec8a6e87645a2bf78d530d93c786c/eligibility_documents/b1164ca7ed164020add2f8d1130d2b56?download=7ac6b69cc8b348fe881ef329f6e3a668",
        "documentOf": "tender",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      }
    ],
    "selfQualified": true,
    "status": "unsuccessful"
  }
}

