PATCH /api/2.5/tenders/db1ddb06a5a44954bc0b9f555776112d/qualifications/2424671f78c54835a110b7dc443c6ca6?acc_token=3ba9d3fdf58a40ac8a19d43f43de9e28 HTTP/1.0
Authorization: Bearer broker
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "2424671f78c54835a110b7dc443c6ca6",
    "bidID": "9ee879e314fd487584383884598ae7c7",
    "status": "unsuccessful",
    "date": "2021-03-16T00:00:00+02:00",
    "qualified": false,
    "eligible": false
  }
}

