PATCH /api/2.5/tenders/21b59cfa191a41eaaeb418282327d481/contracts/175f09d927a54411804c6a2631c56e4f/documents/05012802864b439b9115d9dfec1319db?acc_token=b3345f8c5f3c446983b73bbe7f073ab7 HTTP/1.0
Authorization: Bearer broker
Content-Length: 106
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "language": "en",
    "title_en": "Title of Document",
    "description_en": "Description of Document"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "title_en": "Title of Document",
    "description_en": "Description of Document",
    "language": "en",
    "id": "05012802864b439b9115d9dfec1319db",
    "datePublished": "2023-01-01T00:00:01+02:00",
    "hash": "md5:00000000000000000000000000000000",
    "title": "contract_first_document.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5cce5c020f0b4ba8bf7c5257d58ab07a?Signature=dKo8NxHOP6nIPRJKrdKKlzY8mOu%2BdX9T0Sa99SHcS3HZhb842MsGl2m9HPbHS7NGh%2B0wIMz4THV25Cxl5ZjpDw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "dateModified": "2023-01-01T00:00:01+02:00"
  }
}

