PATCH /api/2.5/tenders/0ffcd2893dee417cb36ace18bfbd7a09/cancellations/b857da1670b74f6fa6b68654701bc76e?acc_token=b630da6f0eb34e9eb53e8be052b29ef3 HTTP/1.0
Authorization: Bearer broker
Content-Length: 37
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reasonType": "unFixable"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "b857da1670b74f6fa6b68654701bc76e",
    "status": "draft",
    "date": "2023-01-01T00:00:01+02:00",
    "reasonType": "unFixable",
    "reason": "cancellation reason",
    "cancellationOf": "tender"
  }
}

