POST /api/2.5/tenders/b29ccfefe77c4e45bc0898315cdb3a6f/bids HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "draft",
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "countryName": "Україна",
          "postalCode": "01220",
          "region": "м. Київ",
          "locality": "м. Київ",
          "streetAddress": "вул. Банкова, 11, корпус 1"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro",
        "contract_owner": "broker6",
        "signerInfo": {
          "name": "Test Testovich",
          "telephone": "+380950000000",
          "email": "example@email.com",
          "iban": "111111111111111",
          "authorizedBy": "Статут компанії",
          "position": "Генеральний директор"
        }
      }
    ],
    "value": {
      "amount": 500
    },
    "requirementResponses": [
      {
        "requirement": {
          "id": "daa74317a63e4218bff3f629c5d27225"
        },
        "values": [
          "Розчин для інфузій"
        ]
      },
      {
        "requirement": {
          "id": "90b36f39999f4082a76c6d350ae6c086"
        },
        "value": 5
      },
      {
        "requirement": {
          "id": "f446c678114f49b99db76e28fd037fbd"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ]
      }
    ],
    "items": [
      {
        "id": "b7fa8976d57c48e9842ede4ef92ccbf3",
        "description": "Комп’ютерне обладнання для біда",
        "quantity": 10,
        "unit": {
          "name": "кг",
          "code": "KGM",
          "value": {
            "amount": 40,
            "valueAddedTaxIncluded": false
          }
        },
        "product": "11111111111111111111111111111111"
      },
      {
        "id": "4a394e96ce404b50b469bc48dd41fbd9",
        "description": "Комп’ютерне обладнання",
        "quantity": 5,
        "unit": {
          "name": "кг",
          "code": "KGM",
          "value": {
            "amount": 20,
            "valueAddedTaxIncluded": false
          }
        },
        "product": "11111111111111111111111111111111"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b29ccfefe77c4e45bc0898315cdb3a6f/bids/2a59363879844618892169c34b3aaa5d

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "daa74317a63e4218bff3f629c5d27225",
          "title": "Форма випуску"
        },
        "values": [
          "Розчин для інфузій"
        ],
        "id": "e31c710621144857a3a7ad89a898bac1",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "90b36f39999f4082a76c6d350ae6c086",
          "title": "Доза діючої речовини"
        },
        "value": 5,
        "id": "b095d8249d134b7f95990359b009f5fb",
        "unit": {
          "code": "KGM",
          "name": "кілограми"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "f446c678114f49b99db76e28fd037fbd",
          "title": "Форма випуску 1"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ],
        "id": "6789e5c276b74eca83a7310d3401eb1f",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      }
    ],
    "items": [
      {
        "id": "b7fa8976d57c48e9842ede4ef92ccbf3",
        "description": "Комп’ютерне обладнання для біда",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 40.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 10.0,
        "product": "11111111111111111111111111111111"
      },
      {
        "id": "4a394e96ce404b50b469bc48dd41fbd9",
        "description": "Комп’ютерне обладнання",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 20.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 5.0,
        "product": "11111111111111111111111111111111"
      }
    ],
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": false
    },
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        },
        "contract_owner": "broker6"
      }
    ],
    "status": "draft",
    "id": "2a59363879844618892169c34b3aaa5d",
    "date": "2027-01-01T00:00:00+02:00"
  },
  "access": {
    "token": "d99543d767fa4ec5bbbd917cc671ddd5",
    "transfer": "c2fb00132ba742a6aef9030dc94958fd"
  }
}

