POST /api/2.5/tenders/b2c76aea070a444fbbec1c1b57823cb0/bids HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "countryName": "Україна",
          "postalCode": "01220",
          "region": "м. Київ",
          "locality": "м. Київ",
          "streetAddress": "вул. Банкова, 11, корпус 1"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "telephone": "+380950000000",
          "email": "example@email.com",
          "iban": "111111111111111",
          "authorizedBy": "Статут компанії",
          "position": "Генеральний директор"
        },
        "contract_owner": "broker6"
      }
    ],
    "value": {
      "amount": 500
    },
    "requirementResponses": [
      {
        "requirement": {
          "id": "f1d112543e944ec4921aed16eeee4d1c"
        },
        "values": [
          "Розчин для інфузій"
        ]
      },
      {
        "requirement": {
          "id": "2654efa2a4c24d97bc8654b1a8e1bd8e"
        },
        "value": 5
      },
      {
        "requirement": {
          "id": "86f6ad38311e4745ae61ef627a742053"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ]
      }
    ],
    "items": [
      {
        "id": "af97fc4b849046d7963f961e8849d8bc",
        "description": "Комп’ютерне обладнання для біда",
        "quantity": 10,
        "unit": {
          "name": "кг",
          "code": "KGM",
          "value": {
            "amount": 40,
            "valueAddedTaxIncluded": false
          }
        },
        "product": "11111111111111111111111111111111"
      },
      {
        "id": "05db985df9a749e2ac8ca5746e30fe9f",
        "description": "Комп’ютерне обладнання",
        "quantity": 5,
        "unit": {
          "name": "кг",
          "code": "KGM",
          "value": {
            "amount": 10,
            "valueAddedTaxIncluded": false
          }
        },
        "product": "11111111111111111111111111111111"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b2c76aea070a444fbbec1c1b57823cb0/bids/3ff1c1aa74244f70a632393fd15c5ab6

{
  "data": {
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        },
        "contract_owner": "broker6"
      }
    ],
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "requirementResponses": [
      {
        "requirement": {
          "id": "f1d112543e944ec4921aed16eeee4d1c",
          "title": "Форма випуску"
        },
        "values": [
          "Розчин для інфузій"
        ],
        "id": "cd1dbc7490e540798a2bd745fd7b958b",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "2654efa2a4c24d97bc8654b1a8e1bd8e",
          "title": "Доза діючої речовини"
        },
        "value": 5,
        "id": "3a32bf7e8cf74523b3b7c9d6448df161",
        "unit": {
          "code": "KGM",
          "name": "кілограми"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "86f6ad38311e4745ae61ef627a742053",
          "title": "Форма випуску 1"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ],
        "id": "360662ec6c524e009943fe6dd5503702",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      }
    ],
    "status": "draft",
    "items": [
      {
        "id": "af97fc4b849046d7963f961e8849d8bc",
        "description": "Комп’ютерне обладнання для біда",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 40.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 10.0,
        "product": "11111111111111111111111111111111"
      },
      {
        "id": "05db985df9a749e2ac8ca5746e30fe9f",
        "description": "Комп’ютерне обладнання",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 10.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 5.0,
        "product": "11111111111111111111111111111111"
      }
    ],
    "id": "3ff1c1aa74244f70a632393fd15c5ab6",
    "date": "2025-06-13T17:52:35.403247+03:00"
  },
  "access": {
    "token": "00307e51bcfc44e797d5b11819d10395",
    "transfer": "ec8e35a015b0470e97fcc8a646a49abe"
  }
}

PATCH /api/2.5/tenders/b2c76aea070a444fbbec1c1b57823cb0/bids/3ff1c1aa74244f70a632393fd15c5ab6?acc_token=00307e51bcfc44e797d5b11819d10395 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "pending"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "3ff1c1aa74244f70a632393fd15c5ab6",
    "date": "2025-06-13T17:52:35.426673+03:00",
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        },
        "contract_owner": "broker6"
      }
    ],
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "requirementResponses": [
      {
        "requirement": {
          "id": "f1d112543e944ec4921aed16eeee4d1c",
          "title": "Форма випуску"
        },
        "values": [
          "Розчин для інфузій"
        ],
        "id": "cd1dbc7490e540798a2bd745fd7b958b",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "2654efa2a4c24d97bc8654b1a8e1bd8e",
          "title": "Доза діючої речовини"
        },
        "value": 5,
        "id": "3a32bf7e8cf74523b3b7c9d6448df161",
        "unit": {
          "code": "KGM",
          "name": "кілограми"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "86f6ad38311e4745ae61ef627a742053",
          "title": "Форма випуску 1"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ],
        "id": "360662ec6c524e009943fe6dd5503702",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      }
    ],
    "status": "pending",
    "items": [
      {
        "id": "af97fc4b849046d7963f961e8849d8bc",
        "description": "Комп’ютерне обладнання для біда",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 40.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 10.0,
        "product": "11111111111111111111111111111111"
      },
      {
        "id": "05db985df9a749e2ac8ca5746e30fe9f",
        "description": "Комп’ютерне обладнання",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 10.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 5.0,
        "product": "11111111111111111111111111111111"
      }
    ],
    "submissionDate": "2025-06-13T17:52:35.426673+03:00"
  }
}

