POST /api/2.5/tenders/016911f3f3d341618c9844a1087e857e/bids HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "draft",
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "countryName": "Україна",
          "postalCode": "01220",
          "region": "м. Київ",
          "locality": "м. Київ",
          "streetAddress": "вул. Банкова, 11, корпус 1"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "telephone": "+380950000000",
          "email": "example@email.com",
          "iban": "111111111111111",
          "authorizedBy": "Статут компанії",
          "position": "Генеральний директор"
        },
        "contract_owner": "broker6"
      }
    ],
    "value": {
      "amount": 500
    },
    "requirementResponses": [
      {
        "requirement": {
          "id": "3d7bd9da05614ac4bb8566e268590160"
        },
        "values": [
          "Розчин для інфузій"
        ]
      },
      {
        "requirement": {
          "id": "02cc402d17c246aab7bc883c4f91666f"
        },
        "value": 5
      },
      {
        "requirement": {
          "id": "ea9f9be22eb04f8791fc97c5c55d08ef"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ]
      }
    ],
    "items": [
      {
        "id": "b7fa8976d57c48e9842ede4ef92ccbf3",
        "description": "Комп’ютерне обладнання для біда",
        "quantity": 10,
        "unit": {
          "name": "кг",
          "code": "KGM",
          "value": {
            "amount": 40,
            "valueAddedTaxIncluded": false
          }
        },
        "product": "11111111111111111111111111111111"
      },
      {
        "id": "4a394e96ce404b50b469bc48dd41fbd9",
        "description": "Комп’ютерне обладнання",
        "quantity": 5,
        "unit": {
          "name": "кг",
          "code": "KGM",
          "value": {
            "amount": 10,
            "valueAddedTaxIncluded": false
          }
        },
        "product": "11111111111111111111111111111111"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/016911f3f3d341618c9844a1087e857e/bids/87a857e2ceb8455e9bf83fcc6abd38a7

{
  "data": {
    "tenderers": [
      {
        "name": "Державне управління справами",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00037256",
          "uri": "http://www.dus.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Банкова, 11, корпус 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "01220",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Державне управління справами",
          "telephone": "+0440000000"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        },
        "contract_owner": "broker6"
      }
    ],
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "requirementResponses": [
      {
        "requirement": {
          "id": "3d7bd9da05614ac4bb8566e268590160",
          "title": "Форма випуску"
        },
        "values": [
          "Розчин для інфузій"
        ],
        "id": "05f7f97d9c9e4d03aee04a2f7ff2da9e",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "02cc402d17c246aab7bc883c4f91666f",
          "title": "Доза діючої речовини"
        },
        "value": 5,
        "id": "533e7f5f79f64ba9b630edb0dbdbefe0",
        "unit": {
          "code": "KGM",
          "name": "кілограми"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      },
      {
        "requirement": {
          "id": "ea9f9be22eb04f8791fc97c5c55d08ef",
          "title": "Форма випуску 1"
        },
        "values": [
          "Відповідь1",
          "Відповідь2"
        ],
        "id": "082aa4e993bf44d3854e4745c0e901bf",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
        }
      }
    ],
    "status": "draft",
    "items": [
      {
        "id": "b7fa8976d57c48e9842ede4ef92ccbf3",
        "description": "Комп’ютерне обладнання для біда",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 40.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 10.0,
        "product": "11111111111111111111111111111111"
      },
      {
        "id": "4a394e96ce404b50b469bc48dd41fbd9",
        "description": "Комп’ютерне обладнання",
        "unit": {
          "name": "кг",
          "value": {
            "amount": 10.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 5.0,
        "product": "11111111111111111111111111111111"
      }
    ],
    "id": "87a857e2ceb8455e9bf83fcc6abd38a7",
    "date": "2023-10-10T01:00:00+03:00"
  },
  "access": {
    "token": "6c3c2e421e1a466e8ab8fa377afd0b96",
    "transfer": "957bc767a13f4f3ba983c4110c30bcf5"
  }
}

