POST /api/2.5/tenders/1f57390f567248e78a17e2dbd55d6a10/awards/4733603c425b4815a5d9e919883dc101/requirement_responses/964e2ab697e7453498a24de1bdaf9f10/evidences?acc_token=01a0e598f3b04f3080aa4ba86237db40 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Requirement response",
    "relatedDocument": {
      "id": "d4388d25ad9d444aa3205e564dceccdb",
      "title": "name.doc"
    },
    "type": "document"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json

{
  "data": {
    "title": "Requirement response",
    "type": "document",
    "relatedDocument": {
      "id": "d4388d25ad9d444aa3205e564dceccdb",
      "title": "name.doc"
    },
    "id": "70fbf2a0a6cd4038bff8f9438ac216f2"
  }
}

