GET /api/2.5/tenders/1f57390f567248e78a17e2dbd55d6a10/awards/e8514568cae0466faad333590224b7cc/requirement_responses HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "requirement": {
        "id": "b9f9c2090e2d4b218f2dacb35b33a3bd",
        "title": "Учасник процедури закупівлі пропонує, дає або погоджується дати прямо чи опосередковано будь-якій службовій (посадовій) особі замовника, іншого державного органу винагороду в будь-якій формі (пропозиція щодо найму на роботу, цінна річ, послуга тощо) з метою вплинути на прийняття рішення щодо визначення переможця процедури закупівлі або застосування замовником певної процедури закупівлі"
      },
      "evidences": [
        {
          "title": "Requirement response",
          "type": "document",
          "relatedDocument": {
            "id": "7db6373a0527432e8ead9806bf100c4d",
            "title": "name.doc"
          },
          "id": "760d5c986eec40ed9cd2fe188706f2be"
        },
        {
          "title": "Update evidence title",
          "type": "document",
          "relatedDocument": {
            "id": "7db6373a0527432e8ead9806bf100c4d",
            "title": "name.doc"
          },
          "id": "73904e7d54e4405ca0054e0957891fb9"
        }
      ],
      "value": false,
      "id": "4ffed579430b463a996cd50c698dc7db",
      "classification": {
        "scheme": "ESPD211",
        "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.MISINTERPRETATION"
      }
    }
  ]
}

