POST /api/2.5/tenders/4a90c1510dc6464b909c12f32d215a78/awards/2120dad2a7424158a5d1186e24b10448/requirement_responses/8bcc5e01db3e4b02be9206593dd86572/evidences?acc_token=01a0e598f3b04f3080aa4ba86237db40 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Requirement response",
    "relatedDocument": {
      "id": "36fe9c990e514a49971a56b9d591f8af",
      "title": "name.doc"
    },
    "type": "document"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json

{
  "data": {
    "title": "Requirement response",
    "type": "document",
    "relatedDocument": {
      "id": "36fe9c990e514a49971a56b9d591f8af",
      "title": "name.doc"
    },
    "id": "d19498e2dc414ecfb9e390dcfb47767f"
  }
}

