PATCH /api/2.5/tenders/8d8242d0ac8c41b7ad9863937fd3ead6/criteria/281238ff60ed49f49ad223f92c10abb9/requirement_groups/3e0a5afcde3a4f4296cb7f7f9159411f/requirements/2c920f9c8b754f7084810fcbf8913ec8?acc_token=1e9cf570ec0c409b89cec0d0656d000a HTTP/1.0
Authorization: Bearer broker
Content-Length: 422
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "eligibleEvidences": [
      {
        "title": "Документальне підтвердження",
        "description": "Довідка в довільній формі",
        "type": "statement",
        "id": "56d2b81c610548ed8fd847fbebe06b16"
      }
    ]
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "title": "Updated title",
    "dataType": "boolean",
    "eligibleEvidences": [
      {
        "title": "Документальне підтвердження",
        "description": "Довідка в довільній формі",
        "type": "statement",
        "id": "56d2b81c610548ed8fd847fbebe06b16"
      }
    ],
    "expectedValue": "true",
    "id": "2c920f9c8b754f7084810fcbf8913ec8",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "status": "active"
  }
}

