GET /api/2.5/tenders/bbc1076896f8436b8dce0f56039ea075/criteria HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "title": "Updated title",
      "description": "Службова (посадова) особа учасника процедури закупівлі, яка підписала тендерну пропозицію (або уповноважена на підписання договору в разі переговорної процедури закупівлі) або фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.OTHER"
      },
      "id": "2832a696b5bd4bf1bee3aa152ba8104c",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.5"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.6"
        }
      ],
      "requirementGroups": [
        {
          "description": "Updated description",
          "requirements": [
            {
              "title": "Updated title",
              "dataType": "boolean",
              "eligibleEvidences": [
                {
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "document",
                  "id": "71b8179cda744ab49c375d4dcd77a85c"
                },
                {
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "statement",
                  "id": "de146cbe00ce498f93ecd841f0121394"
                }
              ],
              "expectedValue": "true",
              "id": "8b19671038034aeab033b9b992ca6948",
              "datePublished": "2023-10-10T01:00:00+03:00",
              "status": "active"
            },
            {
              "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
              "dataType": "boolean",
              "eligibleEvidences": [
                {
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "document",
                  "id": "7f6dba2f457543c499aa0bea55f59dc8"
                }
              ],
              "expectedValue": "true",
              "status": "active",
              "id": "cdbf25b014b747008f7723df802330c4",
              "datePublished": "2023-10-10T01:00:00+03:00"
            }
          ],
          "id": "53e7cc2f43d748f39745ba3da483c820"
        },
        {
          "description": "Учасник фізична особа підтверджує, що",
          "requirements": [
            {
              "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
              "dataType": "boolean",
              "eligibleEvidences": [
                {
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "document",
                  "id": "781ca4a5e32147c28eb8fdd1bd5a56e0"
                }
              ],
              "expectedValue": "true",
              "status": "active",
              "id": "50421b2d2ad94eecb432e4b9729fef2e",
              "datePublished": "2023-10-10T01:00:00+03:00"
            }
          ],
          "id": "85d288db9da74b95837cee5ee63c8e1b"
        }
      ]
    },
    {
      "title": "Вчинення злочинів, учинених з корисливих мотивів",
      "description": "Службова (посадова) особа учасника процедури закупівлі, яка підписала тендерну пропозицію (або уповноважена на підписання договору в разі переговорної процедури закупівлі) або фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
      },
      "id": "bbd85fb6da144b0c984b26da09084968",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.5"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.6"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник фізична особа підтверджує, що",
          "requirements": [
            {
              "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
              "dataType": "boolean",
              "eligibleEvidences": [
                {
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "document",
                  "id": "9b9d1974cd334d40bfea3b7e00cb5f7e"
                }
              ],
              "expectedValue": "true",
              "id": "d6fa6b14c0074edea3282d9de0ce7357",
              "datePublished": "2023-10-10T01:00:00+03:00",
              "status": "active"
            }
          ],
          "id": "27abc4dcfca240b8a44a1f34b9db3b82"
        }
      ]
    }
  ]
}

