PATCH /api/2.5/tenders/e8ac48a7259d4badb25eaebe193c8a4a/qualifications/73f63504520247fa9b86d1bd8882cd4c?acc_token=289610ea5a9b448e9b44db767a3ca67f HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "01ff0316fef0476ebb717b7ac57e8d5b"
        },
        "evidences": [
          {
            "title": "Requirement response",
            "relatedDocument": {
              "id": "8e181d86dd0a49bb86ba68aecc97b2e5",
              "title": "name.doc"
            },
            "type": "document"
          }
        ],
        "value": false
      }
    ]
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "01ff0316fef0476ebb717b7ac57e8d5b",
          "title": "Учасник процедури закупівлі пропонує, дає або погоджується дати прямо чи опосередковано будь-якій службовій (посадовій) особі замовника, іншого державного органу винагороду в будь-якій формі (пропозиція щодо найму на роботу, цінна річ, послуга тощо) з метою вплинути на прийняття рішення щодо визначення переможця процедури закупівлі або застосування замовником певної процедури закупівлі"
        },
        "evidences": [
          {
            "title": "Requirement response",
            "type": "document",
            "relatedDocument": {
              "id": "8e181d86dd0a49bb86ba68aecc97b2e5",
              "title": "name.doc"
            },
            "id": "640e29717bcc4283984059c5adf0fca0"
          }
        ],
        "value": false,
        "id": "88fba652da4d4df6a6c8359d0782d3af",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.MISINTERPRETATION"
        }
      }
    ],
    "id": "73f63504520247fa9b86d1bd8882cd4c",
    "bidID": "1e5a862911ab40f98c27427d3a3c1320",
    "lotID": "5ed94a370bd64d5cadece97b771c5b9e",
    "status": "pending",
    "date": "2023-10-10T01:00:00+03:00",
    "documents": [
      {
        "confidentiality": "public",
        "id": "8e181d86dd0a49bb86ba68aecc97b2e5",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "name.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c0e9ce2d85214717a9a8c36a8b8ead0e?Signature=wvbBm%2F5ovppg8BizL%2FmRQ1N5zsdTrC4p1vL%2FbZ5gGWdUSvfpnyw3jbH1FpYdqAEonMC%2FFLjWUPSi5dLPNvbcAQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:00:00+03:00",
        "author": "tender_owner",
        "language": "uk"
      }
    ],
    "qualified": false,
    "eligible": false
  }
}

