PATCH /api/2.5/tenders/22ce65f78679422981e3ee40eed3ea67/bids/987b40daa8334398a3f222f3fb033be2?acc_token=8a0b1f0e806b43589cebdb9a76747c70 HTTP/1.0
Authorization: Bearer token
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "563124eafd7a483da4fa9dc6c4eca0b8"
        },
        "evidences": [
          {
            "title": "Requirement response",
            "relatedDocument": {
              "id": "ed166e26753444678ed95a3ebd151434",
              "title": "name.doc"
            },
            "type": "document"
          }
        ],
        "value": true
      },
      {
        "requirement": {
          "id": "ffe317de413e48ae97db78b9e602da60"
        },
        "evidences": [
          {
            "title": "Requirement response",
            "relatedDocument": {
              "id": "ed166e26753444678ed95a3ebd151434",
              "title": "name.doc"
            },
            "type": "document"
          }
        ],
        "value": true
      },
      {
        "requirement": {
          "id": "65672e4864a645a78981f701191ff6e2"
        },
        "evidences": [
          {
            "title": "Requirement response",
            "relatedDocument": {
              "id": "ed166e26753444678ed95a3ebd151434",
              "title": "name.doc"
            },
            "type": "document"
          }
        ],
        "value": true
      }
    ]
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "563124eafd7a483da4fa9dc6c4eca0b8",
          "title": "Учасник процедури закупівлі протягом останніх трьох років не притягувався до відповідальності за порушення у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів торгів, аукціонів, конкурсів, тендерів"
        },
        "evidences": [
          {
            "title": "Requirement response",
            "type": "document",
            "relatedDocument": {
              "id": "ed166e26753444678ed95a3ebd151434",
              "title": "name.doc"
            },
            "id": "32d580234b5941d5a0676730c6a67801"
          }
        ],
        "value": true,
        "id": "a0d92461190647889cd23fef400e80f6",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
        }
      },
      {
        "requirement": {
          "id": "ffe317de413e48ae97db78b9e602da60",
          "title": "Учасник процедури закупівлі є нерезидентом"
        },
        "evidences": [
          {
            "title": "Requirement response",
            "type": "document",
            "relatedDocument": {
              "id": "ed166e26753444678ed95a3ebd151434",
              "title": "name.doc"
            },
            "id": "d9213e53844c42b7bfad7135f5af8d9f"
          }
        ],
        "value": true,
        "id": "34f5edd3973f4fc096a799d9d70a3ebf",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.NATIONAL.ANTI-CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "65672e4864a645a78981f701191ff6e2",
          "title": "Учасник процедури закупівлі має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми"
        },
        "evidences": [
          {
            "title": "Requirement response",
            "type": "document",
            "relatedDocument": {
              "id": "ed166e26753444678ed95a3ebd151434",
              "title": "name.doc"
            },
            "id": "73737d3658d747a8919f8ace49a5f647"
          }
        ],
        "value": true,
        "id": "a2e4f64ad89a4cb690a58326773158b0",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.NATIONAL.ANTI-CORRUPTION"
        }
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        }
      }
    ],
    "status": "draft",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "id": "987b40daa8334398a3f222f3fb033be2",
    "date": "2023-10-10T01:00:00+03:00",
    "lotValues": [
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "251405ab88ff4e62806566f189709a65",
        "status": "pending",
        "date": "2023-10-10T01:00:00+03:00"
      }
    ],
    "documents": [
      {
        "confidentiality": "public",
        "id": "ed166e26753444678ed95a3ebd151434",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "name.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/eca1451a57d142f394808a9f0953822a?Signature=A5icXgC%2BjDHMUEXaX29uygDBZX9J6M9cqFFJ2zo16OfslBgPmX65qOyR9HdbASPCIYc%2Fgu5Rv6JBLxngz5v1Aw%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:00:00+03:00",
        "language": "uk"
      }
    ],
    "selfQualified": true
  }
}

