GET /api/2.5/tenders/9cc65ce29e4f4ae0b098f633963efa7f/bids/7878cf456f9640bea5cb979f1fbebeee/requirement_responses/29a781e29c324f888fe28d040b3e6c2d HTTP/1.0
Authorization: Bearer token
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "title": "Updated title",
    "description": "some description",
    "requirement": {
      "id": "2d0f191e424845cea0d0a424258d3d3f",
      "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
    },
    "evidences": [
      {
        "title": "Requirement response",
        "type": "document",
        "relatedDocument": {
          "id": "2e37b10636cb4e53a41b3973f4469c3c",
          "title": "name.doc"
        },
        "id": "3d6506fbe5384fb7bcfe864c3b5eec78"
      },
      {
        "title": "Update evidence title",
        "type": "document",
        "relatedDocument": {
          "id": "2e37b10636cb4e53a41b3973f4469c3c",
          "title": "name.doc"
        },
        "id": "ce6bda104f644fc8ad7c3bd12ede9f54"
      }
    ],
    "value": "True",
    "id": "29a781e29c324f888fe28d040b3e6c2d"
  }
}

