GET /api/2.5/tenders/b25aeafd54e1487bb077be93668f3c21/bids/5abe81cd14f742cb8d4cf0903585d320/requirement_responses/d397dabf99c54c5aafecc6ebaa9716c5/evidences HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "title": "Requirement response",
      "type": "document",
      "relatedDocument": {
        "id": "b4d31b1e52b24a019beb89f0a43f9c9a",
        "title": "name.doc"
      },
      "id": "6040a904824240aab8a0dd72e62ce313"
    },
    {
      "title": "Update evidence title",
      "type": "document",
      "relatedDocument": {
        "id": "b4d31b1e52b24a019beb89f0a43f9c9a",
        "title": "name.doc"
      },
      "id": "92a84cb006144944832f34e9f722cb1f"
    }
  ]
}

