GET /api/2.5/submissions/46bb14b7b4d54f84bb1b6ab1c78afaf7 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "documents": [
      {
        "id": "651780b74635449ebce98a17d0a7848d",
        "hash": "md5:00000000000000000000000000000000",
        "title": "submission_docs.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cfd8e2fb1a074f9a8ce6ff61f6f8586e?Signature=cFsl1wMxnBtH7OrutFGBjC836XSrnj%2B9ziqLbjB4uY1qiA0N5eNd9MIpubkkikLTkGMvBpUN1v1KHQi9B2%2BEBQ%3D%3D&KeyID=a8968c46",
        "datePublished": "2023-01-17T00:00:00+02:00",
        "dateModified": "2023-01-17T00:00:00+02:00"
      }
    ],
    "frameworkID": "019a0935c719454eaa0dbab932c7ad06",
    "dateModified": "2023-01-17T00:00:00+02:00",
    "date": "2023-01-17T00:00:00+02:00",
    "owner": "broker",
    "status": "draft",
    "submissionType": "open",
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "scale": "micro",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        }
      }
    ],
    "id": "46bb14b7b4d54f84bb1b6ab1c78afaf7"
  }
}

