PATCH /api/2.5/tenders/72de65d0bc9e41d5a8c4760d96e68f3c?acc_token=43317e67f7c740c48e3ec786366ee004 HTTP/1.0
Authorization: Bearer broker
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active.tendering"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "criteria": [
      {
        "title": "Вчинення злочинів, учинених з корисливих мотивів",
        "description": "Службова (посадова) особа учасника процедури закупівлі, яка підписала тендерну пропозицію (або уповноважена на підписання договору в разі переговорної процедури закупівлі) або фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
        "source": "tenderer",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " espd211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"
        },
        "id": "c3eea76abfb34505b594dbecfa090fc6",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.5"
          },
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.6"
          }
        ],
        "requirementGroups": [
          {
            "description": "Учасник фізична особа підтверджує, що",
            "requirements": [
              {
                "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
                "dataType": "boolean",
                "eligibleEvidences": [
                  {
                    "title": "Документальне підтвердження",
                    "description": "Довідка в довільній формі",
                    "type": "document",
                    "id": "2cb7bc9b5ec440ad8ac53ecb98e48375"
                  }
                ],
                "expectedValue": "true",
                "status": "active",
                "id": "77a16142763341f28de6533b8699c419",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "c8f7c4c4494549aeb585d12da62f3af5"
          },
          {
            "description": "Учасник юридична особа підтверджує, що",
            "requirements": [
              {
                "title": "Службова (посадова) особа учасника процедури закупівлі, яка підписала тендерну пропозицію (або уповноважена на підписання договору в разі переговорної процедури закупівлі), не була засуджена за злочин, вчинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом, шахрайством та відмиванням коштів), судимість з якої  знято або погашено у встановленому законом порядку",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "f72eeef37a4345d99fb4362aa7dfa23c",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "d2d1723e17bd4409911a71e1cb772a69"
          }
        ]
      },
      {
        "title": "Вчинення економічних правопорушень",
        "description": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів",
        "source": "tenderer",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " espd211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
        },
        "id": "c0abd21e551049e7a87a0674f3e841bc",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.4"
          },
          {
            "version": "2020-02-13",
            "identifier": {
              "id": "2210-III",
              "legalName": "Закон України \"Про захист економічної конкуренції\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/2210-14"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "6.2.4"
          },
          {
            "version": "2020-02-13",
            "identifier": {
              "id": "2210-III",
              "legalName": "Закон України \"Про захист економічної конкуренції\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/2210-14"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "50.1"
          }
        ],
        "requirementGroups": [
          {
            "description": "Учасник підтверджує, що",
            "requirements": [
              {
                "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "f9ed2c08642a427484779355384b3c1d",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "9f9ed8bec0ac41ec852d4d58d5b49683"
          }
        ]
      },
      {
        "title": "Вчинення корупційних правопорушень",
        "description": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення. Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією",
        "source": "tenderer",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " espd211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        },
        "id": "972494c4d6c441898b3cf9904f55f97d",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.2"
          },
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.3"
          }
        ],
        "requirementGroups": [
          {
            "description": "Учасник підтверджує, що",
            "requirements": [
              {
                "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "8a7e34895b2d4045abbfd1c7445c0f85",
                "datePublished": "2023-10-10T01:00:00+03:00"
              },
              {
                "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "9a9542df48a64bdabe344265960cdf00",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "826fa65bd2784aacbf630685aa38163a"
          }
        ]
      },
      {
        "title": "Вчинення правопорушень, пов'язаних з використанням дитячої праці чи будь-якими формами торгівлі людьми",
        "description": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми",
        "source": "tenderer",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " espd211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING"
        },
        "id": "16aa897b6a424fb1b491578fefe0cd04",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.12"
          }
        ],
        "requirementGroups": [
          {
            "description": "Учасник підтверджує, що",
            "requirements": [
              {
                "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "54414432044147a6845b52226d1b43b4",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "7435b781c8c749879b25f9dd70a3eb4e"
          }
        ]
      },
      {
        "title": "Порушення справ про банкрутство",
        "description": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура",
        "source": "tenderer",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " espd211",
          "id": "CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY"
        },
        "id": "fed386acb9234bb5b1e698a2842d03c6",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.8"
          }
        ],
        "requirementGroups": [
          {
            "description": "Учасник підтверджує, що",
            "requirements": [
              {
                "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "6b04b420c76746d684d83381229df9ca",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "9c95af6f28b44df9a336b677b581cf3a"
          }
        ]
      },
      {
        "title": "Виявлення факту зв'язку учасника з іншими учасниками процедури або замовником",
        "description": "Тендерна пропозиція подана учасником конкурентної процедури закупівлі або участь у переговорній процедурі бере учасник, який є пов'язаною особою з іншими учасниками процедури закупівлі та/або з уповноваженою особою (особами), та/або з керівником замовника",
        "source": "procuringEntity",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " espd211",
          "id": "CRITERION.EXCLUSION.MISCONDUCT.MARKET_DISTORTION"
        },
        "id": "8bb60f813fa74e63b5a4a2eb975ab3a1",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.7"
          }
        ],
        "requirementGroups": [
          {
            "description": "Замовник підтверджує, що",
            "requirements": [
              {
                "title": "Тендерна пропозиція подана учасником конкурентної процедури закупівлі або участь у переговорній процедурі бере учасник, який є пов'язаною особою з іншими учасниками процедури закупівлі та/або з уповноваженою особою (особами), та/або з керівником замовника",
                "dataType": "boolean",
                "eligibleEvidences": [
                  {
                    "title": "Документальне підтвердження",
                    "description": "Довідка в довільній формі",
                    "type": "document",
                    "id": "26c5c65483e94dbea084e7a9bd17a385"
                  }
                ],
                "status": "active",
                "id": "bf6038340d4c40dd8c58134f7a5a0ee2",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "f33db85c4de34d6d800135fc054fde3a"
          }
        ]
      },
      {
        "title": "Виявлення факту наміру впливу на прийняття рішення замовника",
        "description": "Замовник має незаперечні докази того, що учасник процедури закупівлі пропонує, дає або погоджується дати прямо чи опосередковано будь-якій службовій (посадовій) особі замовника, іншого державного органу винагороду в будь-якій формі (пропозиція щодо найму на роботу, цінна річ, послуга тощо) з метою вплинути на прийняття рішення щодо визначення переможця процедури закупівлі або застосування замовником певної процедури закупівлі",
        "source": "procuringEntity",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " espd211",
          "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.MISINTERPRETATION"
        },
        "id": "c3a5083993ef4294bb4197065d7e516c",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.1"
          }
        ],
        "requirementGroups": [
          {
            "description": "Замовник підтверджує, що",
            "requirements": [
              {
                "title": "Замовник має незаперечні докази того, що учасник процедури закупівлі пропонує, дає або погоджується дати прямо чи опосередковано будь-якій службовій (посадовій) особі замовника, іншого державного органу винагороду в будь-якій формі (пропозиція щодо найму на роботу, цінна річ, послуга тощо) з метою вплинути на прийняття рішення щодо визначення переможця процедури закупівлі або застосування замовником певної процедури закупівлі",
                "dataType": "boolean",
                "status": "active",
                "id": "7bb17f4bc69c4627a2044bc961f05405",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "c7e7ac265f4541999ae98bbf70094beb"
          }
        ]
      },
      {
        "title": "Наявність інших підстав для відмови в участі у процедурі закупівлі",
        "description": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)",
        "source": "tenderer",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " espd211",
          "id": "CRITERION.EXCLUSION.NATIONAL.OTHER"
        },
        "id": "a2a29becbf6c4a7799d920567f79bdbe",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.9"
          },
          {
            "version": "2020-03-16",
            "identifier": {
              "id": "755-IV",
              "legalName": "Закон України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/755-15"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "9.2.9"
          },
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.10"
          },
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION",
            "article": "17.1.11"
          },
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "1644-VII",
              "legalName": "Закон України \"Про санкції\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/1644-18"
            },
            "type": "NATIONAL_LEGISLATION"
          }
        ],
        "requirementGroups": [
          {
            "description": "Учасник підтверджує, що",
            "requirements": [
              {
                "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "6407857f53e545528dcdec71c7d0239e",
                "datePublished": "2023-10-10T01:00:00+03:00"
              },
              {
                "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "73e223da34e74ec09b69a032acdaf4ef",
                "datePublished": "2023-10-10T01:00:00+03:00"
              },
              {
                "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\"",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "7174384fbe9b42b79a7a0baafe481820",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "6d58d8584d6048308d5717b54e6245f8"
          }
        ]
      },
      {
        "title": "Мова (мови), якою (якими) повинні готуватися тендерні пропозиції",
        "source": "tenderer",
        "relatesTo": "tenderer",
        "classification": {
          "scheme": " ESPD211",
          "id": "CRITERION.OTHER.BID.LANGUAGE"
        },
        "id": "6ff610f2411a45fcae52fc1128511513",
        "legislation": [
          {
            "version": "2020-04-19",
            "identifier": {
              "id": "922-VIII",
              "legalName": "Закон України \"Про публічні закупівлі\"",
              "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
            },
            "type": "NATIONAL_LEGISLATION"
          }
        ],
        "requirementGroups": [
          {
            "description": "Учасник фізична особа підтверджує, що",
            "requirements": [
              {
                "title": "Мова тендерної пропозиції українська",
                "dataType": "boolean",
                "expectedValue": "true",
                "status": "active",
                "id": "55ac8590814f4115a1f19d5b397d70ab",
                "datePublished": "2023-10-10T01:00:00+03:00"
              }
            ],
            "id": "14436d91ac9241b29a6dba815aaad3c9"
          }
        ]
      }
    ],
    "date": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "dateCreated": "2023-10-10T01:00:00+03:00",
    "tenderID": "UA-2023-10-10-000001-a",
    "owner": "broker",
    "title": "футляри до державних нагород",
    "mainProcurementCategory": "services",
    "agreements": [
      {
        "id": "adc832d48d1343a08a9a9d62e45ceb28"
      }
    ],
    "procurementMethod": "selective",
    "submissionMethod": "electronicAuction",
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "minimalStep": {
      "amount": 5.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "lots": [
      {
        "title": "Лот №1",
        "description": "Опис Лот №1",
        "status": "active",
        "id": "0e04ecea261746bc8fbcced833cde77c",
        "date": "2023-10-10T01:00:00+03:00",
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "minimalStep": {
          "amount": 5.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "auctionPeriod": {
          "shouldStartAfter": "2023-10-26T00:00:00+03:00"
        }
      }
    ],
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "type": "financing",
        "code": "prepayment",
        "percentage": 45.55,
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 0
      },
      {
        "id": "a2b3df0720204e3f8c2bed91a3b7be16",
        "title": "deliveryOfGoods",
        "type": "financing",
        "code": "postpayment",
        "percentage": 54.45,
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 0
      }
    ],
    "procuringEntity": {
      "name": "ЗОСШ #10 м.Вінниці",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00037256",
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      },
      "address": {
        "streetAddress": "вул. Стахурського. 22",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21027",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Куца Світлана Валентинівна",
        "telephone": "+380432465302",
        "url": "http://sch10.edu.vn.ua/"
      },
      "kind": "special"
    },
    "status": "active.tendering",
    "procurementMethodType": "competitiveOrdering",
    "awardCriteria": "lowestCost",
    "enquiryPeriod": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2023-10-22T00:00:00+03:00",
      "clarificationsUntil": "2023-10-25T00:00:00+03:00",
      "invalidationDate": "2023-10-10T01:00:00+03:00"
    },
    "tenderPeriod": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2023-10-25T00:00:00+02:00"
    },
    "items": [
      {
        "id": "6bc3447928e14afbb995a90300312b27",
        "description": "Послуги шкільних їдалень",
        "unit": {
          "name": "папір",
          "value": {
            "amount": 10.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": true
          },
          "code": "KGM"
        },
        "quantity": 1.0,
        "classification": {
          "description": "Послуги з харчування у школах",
          "scheme": "ДК021",
          "id": "03111600-8"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "relatedLot": "0e04ecea261746bc8fbcced833cde77c",
        "deliveryDate": {
          "startDate": "2023-10-12T01:00:00+03:00",
          "endDate": "2023-10-15T01:00:00+03:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        }
      }
    ],
    "complaintPeriod": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2023-10-22T00:00:00+03:00"
    },
    "next_check": "2023-10-25T00:00:00+02:00",
    "id": "72de65d0bc9e41d5a8c4760d96e68f3c"
  },
  "config": {
    "hasAuction": true,
    "hasAwardingOrder": true,
    "hasValueRestriction": false,
    "valueCurrencyEquality": true,
    "hasPrequalification": false,
    "minBidsNumber": 1,
    "hasPreSelectionAgreement": true
  }
}

