from openprocurement.tender.competitivedialogue.tests.stage2.qualification import TenderQualificationBaseTestCase
from openprocurement.tender.core.tests.qualification_milestone import TenderQualificationMilestoneMixin


class TenderUAQualificationMilestoneTestCase(TenderQualificationMilestoneMixin, TenderQualificationBaseTestCase):
    pass
