from openprocurement.tender.competitivedialogue.tests.stage2.qualification import TenderQualificationBaseTestCase
from openprocurement.tender.core.tests.qualification_milestone import TenderQualificationMilestone24HMixin


class TenderUAQualificationMilestoneTestCase(TenderQualificationMilestone24HMixin, TenderQualificationBaseTestCase):
    pass
