MIN_QUALIFICATION_DURATION = 30
MAX_QUALIFICATION_DURATION = 1095
ENQUIRY_PERIOD_DURATION = 10
SUBMISSION_STAND_STILL_DURATION = 30
MILESTONE_CONTRACT_STATUSES = {
    "ban": "suspended",
    "terminated": "terminated",
}
