MIN_QUALIFICATION_DURATION = 30
MAX_QUALIFICATION_DURATION = 1095
ENQUIRY_PERIOD_DURATION = 10
SUBMISSION_STAND_STILL_DURATION = 30
MILESTONE_CONTRACT_STATUSES = {
    "ban": "suspended",
    "terminated": "terminated",
}

AGREEMENT_TERMINATION_DETAILS_NOT_ENOUGH_SUBMISSIONS = (
    "Відмінено електронною системою через недостатню кількість заявок"
)
