MIN_QUALIFICATION_DURATION = 30
MAX_QUALIFICATION_DURATION = 1095
ENQUIRY_PERIOD_DURATION = 10
ENQUIRY_STAND_STILL_TIME = 3
SUBMISSION_STAND_STILL_DURATION = 30
DAYS_TO_UNSUCCESSFUL_STATUS = 20
MILESTONE_CONTRACT_STATUSES = {
    "ban": "suspended",
    "terminated": "terminated",
}