POST /api/2.5/tenders/0a1b55130d604a0fb3a385cc00f92b5b/awards/e017e0a26d4049128b6d94ac0b57855c/milestones?acc_token=7d4ea22f43fd4491a6966254069032a6 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "code": "24h",
    "description": "One ring to bring them all and in the darkness bind them"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0a1b55130d604a0fb3a385cc00f92b5b/awards/e017e0a26d4049128b6d94ac0b57855c/milestones/836404c070ed47bfa55339ff1effe9f2

{
  "data": {
    "description": "One ring to bring them all and in the darkness bind them",
    "code": "24h",
    "id": "836404c070ed47bfa55339ff1effe9f2",
    "dueDate": "2023-10-11T01:00:00+03:00",
    "date": "2023-10-10T01:00:00+03:00"
  }
}

