POST /api/2.5/tenders/985f6e927f784969aabb65fd84ff2415/awards/93f2f28f7c40428fa1d64021d5556203/documents?acc_token=fce6c7cfa3c64325baa1e5be7db2ce1c HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "sign.p7s",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fddb39dd595c481e8b47b24009815ba5?Signature=%2FCpYzlbQvZBDyncvJpmvCwEqMyFYWTBbr2AEfSkkZYnopTRpcw6hsXZdxmpnaO4WBenGsfwbIfEM8fQ6tId%2FDA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pkcs7-signature",
    "documentType": "deviationReport"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "documents",
      "description": "deviationReport document in award should be only one"
    }
  ]
}

