POST /api/2.5/tenders/9a224c470b1f4206ab133130ec4b1632/qualifications/12341234123412341234123412341234/milestones?acc_token=329ddef7415f4df7817576527add4c76 HTTP/1.0
Authorization: Bearer broker
Content-Length: 100
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "code": "24h",
    "description": "One ring to bring them all and in the darkness bind them"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/9a224c470b1f4206ab133130ec4b1632/qualifications/12341234123412341234123412341234/milestones/00428832b26543eea1172240468ec37d
X-Content-Type-Options: nosniff
{
  "data": {
    "code": "24h",
    "description": "One ring to bring them all and in the darkness bind them",
    "id": "00428832b26543eea1172240468ec37d",
    "dueDate": "2023-01-02T00:00:03+02:00",
    "date": "2023-01-01T00:00:03+02:00"
  }
}

