PATCH /api/2.5/submissions/2653e869246f4cb6900d45568c0a7e2b?acc_token=229f55581e454056a19a3a5af43ddb15 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "scale": "micro",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»"
        },
        "address": {
          "countryName": "Україна",
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "telephone": "+380432216930",
          "email": "soleksuk@gmail.com"
        }
      }
    ],
    "frameworkID": "79215d0ea54f4a04b04d7fadf4090ca1",
    "status": "active",
    "dateModified": "2027-01-17T00:00:00+02:00",
    "date": "2027-01-17T00:00:00+02:00",
    "owner": "broker",
    "submissionType": "dynamicPurchasingSystem",
    "qualificationID": "6dc22ab2c87f41bb91375ca71951687c",
    "datePublished": "2027-01-17T00:00:00+02:00",
    "id": "2653e869246f4cb6900d45568c0a7e2b"
  },
  "config": {
    "restricted": false
  }
}

