PATCH /api/2.5/qualifications/37edcfe4b6484dee80eecfdb03a03a08?acc_token=2a5f07868aed43bfb10588a5ac40185a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "documents": [
      {
        "documentType": "evaluationReports",
        "id": "6ce5c0793a8a4f0794690b7ab8b73b6b",
        "datePublished": "2023-10-26T01:00:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "sign.p7s",
        "format": "application/pkcs7-signature",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/261302c61582415fa7ca7a5348f275ba?Signature=E9HlVatPIhsGKNuKl097CdZOL0JHUYJkzbzZUpTeYmKpK1ZwoLNg1HPXDA4HZ9N2BWQ8NplM3Mzql3%2BA0eF0Ag%3D%3D&KeyID=a8968c46",
        "dateModified": "2023-10-26T01:00:00+03:00",
        "language": "uk"
      }
    ],
    "submissionID": "d4a1ccc22a504cd1a535ce487642a321",
    "frameworkID": "a00a3b5bdaa0437490c883e4482795b2",
    "status": "active",
    "date": "2023-10-26T01:00:00+03:00",
    "dateModified": "2023-10-26T01:00:00+03:00",
    "qualificationType": "dynamicPurchasingSystem",
    "id": "37edcfe4b6484dee80eecfdb03a03a08"
  },
  "config": {
    "restricted": false,
    "qualificationComplainDuration": 0
  }
}

