GET /api/2.5/submissions/ea3e92079bc345a58805f4c05340fd28 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»"
        },
        "address": {
          "countryName": "Україна",
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "telephone": "+380432216930",
          "email": "soleksuk@gmail.com"
        },
        "scale": "micro"
      }
    ],
    "frameworkID": "a00a3b5bdaa0437490c883e4482795b2",
    "status": "draft",
    "submissionType": "dynamicPurchasingSystem",
    "owner": "broker",
    "date": "2023-10-26T01:00:00+03:00",
    "dateModified": "2023-10-26T01:00:00+03:00",
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "submission_docs.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/46a9cf8cd1034d57b7e550b1c7bb0339?Signature=CV6toqmVNh7aYzT8Sn0JjsdtsYR66FqDDLdqXszr49BvU7fkKFV59qITAmgwNxHwaNZ3mGH6rZH5LtzNFshCAQ%3D%3D&KeyID=a8968c46",
        "language": "uk",
        "id": "d28f60dc1865488d9277bd56070b0733",
        "datePublished": "2023-10-26T01:00:00+03:00",
        "dateModified": "2023-10-26T01:00:00+03:00"
      }
    ],
    "id": "ea3e92079bc345a58805f4c05340fd28"
  },
  "config": {
    "restricted": false
  }
}

