GET /api/2.5/submissions/ea3e92079bc345a58805f4c05340fd28/documents HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "submission_docs.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/46a9cf8cd1034d57b7e550b1c7bb0339?Signature=CV6toqmVNh7aYzT8Sn0JjsdtsYR66FqDDLdqXszr49BvU7fkKFV59qITAmgwNxHwaNZ3mGH6rZH5LtzNFshCAQ%3D%3D&KeyID=a8968c46",
      "language": "uk",
      "id": "d28f60dc1865488d9277bd56070b0733",
      "datePublished": "2023-10-26T01:00:00+03:00",
      "dateModified": "2023-10-26T01:00:00+03:00"
    }
  ]
}

