GET /api/2.5/agreements/07764e512cfd4004b74989fbab149644 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "agreementID": "UA-2023-01-17-000001",
    "status": "active",
    "date": "2023-01-17T00:00:00+02:00",
    "dateCreated": "2023-01-17T00:00:00+02:00",
    "dateModified": "2023-01-17T00:00:00+02:00",
    "owner": "broker",
    "agreementType": "dynamicPurchasingSystem",
    "frameworkID": "866509257c6546a088e0363315140ee0",
    "period": {
      "startDate": "2023-01-17T00:00:00+02:00",
      "endDate": "2023-03-02T00:00:00+02:00"
    },
    "procuringEntity": {
      "name": "Державне управління справами",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00037256",
        "legalName": "Назва організації"
      },
      "address": {
        "countryName": "Україна",
        "streetAddress": "вул. Банкова, 11, корпус 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220"
      },
      "contactPoint": {
        "name": "Державне управління справами",
        "telephone": "+0440000001",
        "email": "aa@aa.com"
      },
      "kind": "general"
    },
    "classification": {
      "description": "Mustard seeds",
      "scheme": "ДК021",
      "id": "03111600-8"
    },
    "additionalClassifications": [
      {
        "scheme": "ДК003",
        "id": "17.21.1",
        "description": "папір і картон гофровані, паперова й картонна тара"
      }
    ],
    "contracts": [
      {
        "id": "ee514fd2ad8c4756b31527c0d91dc86f",
        "qualificationID": "244785d441fa4542b1f6d1b9babfc7a1",
        "status": "active",
        "submissionID": "ebfd95e14c5b4da4b23188bde4945a76",
        "suppliers": [
          {
            "name": "ДКП «Школяр»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137256",
              "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 33",
              "locality": "м. Вінниця",
              "region": "Вінницька область",
              "postalCode": "21100",
              "countryName": "Україна"
            },
            "scale": "micro",
            "contactPoint": {
              "name": "Сергій Олексюк",
              "email": "soleksuk@gmail.com",
              "telephone": "+380432216930"
            }
          }
        ],
        "milestones": [
          {
            "id": "587ec622cfb34b70b84fd3f8b23ef2b9",
            "type": "activation",
            "status": "scheduled",
            "dueDate": "2023-03-02T00:00:00+02:00",
            "dateModified": "2023-01-17T00:00:00+02:00"
          }
        ],
        "date": "2023-01-17T00:00:00+02:00"
      }
    ],
    "id": "07764e512cfd4004b74989fbab149644",
    "next_check": "2023-03-02T00:00:00+02:00"
  }
}

