POST /api/2.5/submissions HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro"
      }
    ],
    "frameworkID": "79215d0ea54f4a04b04d7fadf4090ca1"
  },
  "config": {
    "restricted": false
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/submissions/da4552d132e14fd19dc2d64f1438a0d1

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "scale": "micro",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»"
        },
        "address": {
          "countryName": "Україна",
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "telephone": "+380432216930",
          "email": "soleksuk@gmail.com"
        }
      }
    ],
    "frameworkID": "79215d0ea54f4a04b04d7fadf4090ca1",
    "status": "draft",
    "submissionType": "dynamicPurchasingSystem",
    "owner": "broker",
    "date": "2027-01-17T00:00:00+02:00",
    "dateModified": "2027-01-17T00:00:00+02:00",
    "id": "da4552d132e14fd19dc2d64f1438a0d1"
  },
  "access": {
    "token": "c495172bd73f464e8d3b724b58bf84a8",
    "transfer": "9baefde558414364bb00ac0783abe77b"
  },
  "config": {
    "restricted": false
  }
}

