PATCH /api/2.5/tenders/a543ba8d819945409b40b8161d8d268b/cancellations/d0b4965be9a44219befb84c0d6b51adb/complaints/b30e14156b424a9cac8c369fed3a4056?acc_token=05599106707b4411853a3851edbe03fb HTTP/1.0
Authorization: Bearer broker
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

