POST /api/2.5/tenders/a0f809509dd54bfe812871d67c440661/criteria?acc_token=d104fce0287e495fbf1b01bc8a677617 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": [
    {
      "title": "Технічні, якісні та кількісні характеристики предмета закупівлі",
      "description": "Технічна специфікація повинна містити опис усіх необхідних характеристик товарів, робіт або послуг, що закуповуються, у тому числі їх технічні, функціональні та якісні характеристики. Характеристики товарів, робіт або послуг можуть містити опис конкретного технологічного процесу або технології виробництва чи порядку постачання товару (товарів), виконання необхідних робіт, надання послуги (послуг)",
      "source": "tenderer",
      "classification": {
        "scheme": "ESPD211",
        "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
      },
      "relatesTo": "item",
      "legislation": [
        {
          "version": "2024-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19#n1398"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "22.2.3"
        },
        {
          "version": "2024-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19#n1426"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "23"
        },
        {
          "version": "2023-10-31",
          "identifier": {
            "id": "1135-2023-п",
            "legalName": "Про внесення змін до постанов Кабінету Міністрів України від 14 вересня 2020 р. № 822 і від 12 жовтня 2022 р. № 1178",
            "uri": "https://zakon.rada.gov.ua/laws/show/1135-2023-%D0%BF#n24"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "2.1"
        }
      ],
      "requirementGroups": [
        {
          "description": "Підтверджується, що",
          "requirements": [
            {
              "title": "Діагональ екрану",
              "dataType": "number",
              "minValue": 23.8,
              "unit": {
                "code": "INH",
                "name": "дюйм"
              }
            },
            {
              "title": "Роздільна здатність",
              "dataType": "string",
              "expectedValues": [
                "1920x1080"
              ],
              "expectedMinItems": 1
            },
            {
              "title": "Співвідношення сторін",
              "dataType": "string",
              "expectedValues": [
                "16:9"
              ],
              "expectedMinItems": 1
            },
            {
              "title": "Яскравість дисплея",
              "dataType": "integer",
              "minValue": 0,
              "maxValue": 250,
              "unit": {
                "code": "A24",
                "name": "кд/м²"
              }
            },
            {
              "title": "Контрастність (статична)",
              "dataType": "string",
              "expectedValues": [
                "1000:1"
              ],
              "expectedMinItems": 1
            },
            {
              "title": "Кількість портів HDMI",
              "dataType": "integer",
              "minValue": 1,
              "unit": {
                "code": "H87",
                "name": "штук"
              }
            },
            {
              "title": "Кількість портів D-sub",
              "dataType": "integer",
              "minValue": 1,
              "unit": {
                "code": "H87",
                "name": "штук"
              }
            },
            {
              "title": "Кабель для під’єднання",
              "dataType": "string",
              "expectedValues": [
                "HDMI"
              ],
              "expectedMinItems": 1
            },
            {
              "title": "Гарантія",
              "dataType": "integer",
              "minValue": 36,
              "unit": {
                "code": "MON",
                "name": "місяців"
              }
            }
          ]
        }
      ],
      "relatedItem": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
    }
  ]
}


HTTP/1.0 201 Created
Content-Type: application/json

{
  "data": [
    {
      "id": "02049f19e2ed44df94bfa15b913727ee",
      "description": "Технічна специфікація повинна містити опис усіх необхідних характеристик товарів, робіт або послуг, що закуповуються, у тому числі їх технічні, функціональні та якісні характеристики. Характеристики товарів, робіт або послуг можуть містити опис конкретного технологічного процесу або технології виробництва чи порядку постачання товару (товарів), виконання необхідних робіт, надання послуги (послуг)",
      "source": "tenderer",
      "relatesTo": "item",
      "relatedItem": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "classification": {
        "scheme": "ESPD211",
        "id": "CRITERION.OTHER.SUBJECT_OF_PROCUREMENT.TECHNICAL_FEATURES"
      },
      "title": "Технічні, якісні та кількісні характеристики предмета закупівлі",
      "legislation": [
        {
          "version": "2024-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19#n1398"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "22.2.3"
        },
        {
          "version": "2024-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19#n1426"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "23"
        },
        {
          "version": "2023-10-31",
          "identifier": {
            "id": "1135-2023-п",
            "legalName": "Про внесення змін до постанов Кабінету Міністрів України від 14 вересня 2020 р. № 822 і від 12 жовтня 2022 р. № 1178",
            "uri": "https://zakon.rada.gov.ua/laws/show/1135-2023-%D0%BF#n24"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "2.1"
        }
      ],
      "requirementGroups": [
        {
          "id": "b401dd460ffb47e488a46005bcb0e62d",
          "description": "Підтверджується, що",
          "requirements": [
            {
              "id": "b354612292ec4b0bbae2c3158330b5fb",
              "title": "Діагональ екрану",
              "dataType": "number",
              "status": "active",
              "unit": {
                "code": "INH",
                "name": "дюйм"
              },
              "minValue": 23.8,
              "datePublished": "2023-10-10T01:00:00+03:00"
            },
            {
              "id": "7e174fc0be2949f3b622ff61c5bea5c8",
              "title": "Роздільна здатність",
              "dataType": "string",
              "status": "active",
              "expectedValues": [
                "1920x1080"
              ],
              "expectedMinItems": 1,
              "datePublished": "2023-10-10T01:00:00+03:00"
            },
            {
              "id": "59d5379e4dac42e8a3c8064ae77c4579",
              "title": "Співвідношення сторін",
              "dataType": "string",
              "status": "active",
              "expectedValues": [
                "16:9"
              ],
              "expectedMinItems": 1,
              "datePublished": "2023-10-10T01:00:00+03:00"
            },
            {
              "id": "e27ca8316fac44a2bfcc3e905bb7b3ad",
              "title": "Яскравість дисплея",
              "dataType": "integer",
              "status": "active",
              "unit": {
                "code": "A24",
                "name": "кд/м²"
              },
              "minValue": 0,
              "maxValue": 250,
              "datePublished": "2023-10-10T01:00:00+03:00"
            },
            {
              "id": "fdeb837033674c74b0187d9613793a16",
              "title": "Контрастність (статична)",
              "dataType": "string",
              "status": "active",
              "expectedValues": [
                "1000:1"
              ],
              "expectedMinItems": 1,
              "datePublished": "2023-10-10T01:00:00+03:00"
            },
            {
              "id": "7c65ea5c6671456ab41b666dbd41f0e0",
              "title": "Кількість портів HDMI",
              "dataType": "integer",
              "status": "active",
              "unit": {
                "code": "H87",
                "name": "штук"
              },
              "minValue": 1,
              "datePublished": "2023-10-10T01:00:00+03:00"
            },
            {
              "id": "7063220f61954a3faa7e3b23351b53fa",
              "title": "Кількість портів D-sub",
              "dataType": "integer",
              "status": "active",
              "unit": {
                "code": "H87",
                "name": "штук"
              },
              "minValue": 1,
              "datePublished": "2023-10-10T01:00:00+03:00"
            },
            {
              "id": "d2ed4c6adad744a59669a3e93158656e",
              "title": "Кабель для під’єднання",
              "dataType": "string",
              "status": "active",
              "expectedValues": [
                "HDMI"
              ],
              "expectedMinItems": 1,
              "datePublished": "2023-10-10T01:00:00+03:00"
            },
            {
              "id": "eb779f3cc933489fa79d1fedde13a6d5",
              "title": "Гарантія",
              "dataType": "integer",
              "status": "active",
              "unit": {
                "code": "MON",
                "name": "місяців"
              },
              "minValue": 36,
              "datePublished": "2023-10-10T01:00:00+03:00"
            }
          ]
        }
      ]
    }
  ]
}

