PATCH /api/2.3/tenders/bf450bfcf933416f8205cfcde69d0ee1/qualifications/cf8b24ea298246448211827d96915e4e?acc_token=24df0fd7ada04964a1df8416ecc946b0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "bb2ed90db2a54c768470f4147b9ddce9", 
    "date": "2017-06-20T12:33:58.514727+03:00", 
    "id": "cf8b24ea298246448211827d96915e4e"
  }
}

