GET /api/2.5/qualifications/7996b273586044d7921da96e0d16de5a HTTP/1.0
Authorization: Bearer broker2
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "frameworkID": "baca8568a6e0453f859f1a64c6e0fd50",
    "submissionID": "9d618d8b636b4f07b66cb79856f15c47",
    "qualificationType": "dynamicPurchasingSystem",
    "status": "pending",
    "date": "2023-01-20T00:00:00+02:00",
    "dateModified": "2023-01-20T00:00:00+02:00",
    "id": "7996b273586044d7921da96e0d16de5a"
  },
  "config": {
    "restricted": true
  }
}

