GET /api/2.5/qualifications/f72e3f40acc64e4085046733e60d7ebb HTTP/1.0
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Access restricted for qualification object"
    }
  ]
}

