GET /api/2.5/submissions/2a997181ec504fcdbfaf4c759a02895e HTTP/1.0
Authorization: Bearer broker1
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Access restricted for submission object"
    }
  ]
}

