GET /api/2.5/submissions/e0fc16d4a32e49bbb327106221ee3afe HTTP/1.0
Authorization: Bearer broker2
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "scale": "sme",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Андрій Олексюк",
          "email": "aagt@gmail.com",
          "telephone": "+380322916930"
        }
      }
    ],
    "frameworkID": "6f4f10deaaae4f8b9d117837474a9333",
    "status": "active",
    "dateModified": "2023-01-20T00:00:00+02:00",
    "date": "2023-01-20T00:00:00+02:00",
    "owner": "broker2",
    "submissionType": "dynamicPurchasingSystem",
    "qualificationID": "7996b273586044d7921da96e0d16de5a",
    "datePublished": "2023-01-20T00:00:00+02:00",
    "id": "e0fc16d4a32e49bbb327106221ee3afe"
  },
  "config": {
    "restricted": true
  }
}

