PATCH /api/2.5/tenders/52f1b75138ab4b2c87feff205f2a06f4/bids/ab9e4059fff24d9aa7b0c32166fce3ba?acc_token=765f074dacb14d31b625118945f17413 HTTP/1.0
Authorization: Bearer broker
Content-Length: 124
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "fc297ff6c6a74743a96c6b274bae11c0", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "fc297ff6c6a74743a96c6b274bae11c0", 
        "date": "2020-05-15T01:00:00+03:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "id": "ab9e4059fff24d9aa7b0c32166fce3ba", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "Львівська область", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2020-05-15T01:00:00+03:00", 
    "selfQualified": true
  }
}

