POST /api/2.5/tenders/c3028c9ca7a940518864792509ea9232/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 1497
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "selfQualified": true,
    "status": "draft",
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Львів",
          "postalCode": "79013",
          "region": "Львівська область",
          "streetAddress": "вул. Островського, 34"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "name": "Андрій Олексюк",
          "telephone": "+380322916930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Книга»",
        "scale": "sme"
      }
    ],
    "lotValues": [
      {
        "value": {
          "amount": 500
        },
        "relatedLot": "01598eb9c6d3489494777dc7d4fffb7b"
      },
      {
        "subcontractingDetails": "ДКП «Укр Прінт», Україна",
        "value": {
          "amount": 500
        },
        "relatedLot": "b04396e7a0df411991f9fdf58ee8961d"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/c3028c9ca7a940518864792509ea9232/bids/bd30b0698c984e7096a4df6c2e0ea581

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "telephone": "+380322916930",
          "name": "Андрій Олексюк"
        },
        "scale": "sme"
      }
    ],
    "lotValues": [
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "01598eb9c6d3489494777dc7d4fffb7b",
        "status": "pending",
        "date": "2023-01-01T00:00:00+02:00"
      },
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "b04396e7a0df411991f9fdf58ee8961d",
        "subcontractingDetails": "ДКП «Укр Прінт», Україна",
        "status": "pending",
        "date": "2023-01-01T00:00:00+02:00"
      }
    ],
    "selfQualified": true,
    "status": "draft",
    "id": "bd30b0698c984e7096a4df6c2e0ea581",
    "date": "2023-01-01T00:00:00+02:00"
  },
  "access": {
    "token": "b1a98ec6d6be4b3ba83409fb83db6957",
    "transfer": "b512232f2f194deb9cbdee776fd7129a"
  }
}

