PATCH /api/2.5/tenders/52f1b75138ab4b2c87feff205f2a06f4/bids/28d7b15324514c31b62f48b15a1b0a2c?acc_token=54d541dfa06146e2a6a08281ec8f847a HTTP/1.0
Authorization: Bearer broker
Content-Length: 214
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "fc297ff6c6a74743a96c6b274bae11c0", 
        "value": {
          "amount": 500
        }, 
        "subcontractingDetails": "ДКП «Орфей»"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "fc297ff6c6a74743a96c6b274bae11c0", 
        "date": "2020-05-15T01:00:00+03:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "subcontractingDetails": "ДКП «Орфей»"
      }
    ], 
    "id": "28d7b15324514c31b62f48b15a1b0a2c", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2020-05-15T01:00:00+03:00", 
    "selfQualified": true
  }
}

