POST /api/2.5/tenders/7b32e93503314032810e6dd5a0209cee/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 1497
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "selfQualified": true,
    "status": "draft",
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Львів",
          "postalCode": "79013",
          "region": "Львівська область",
          "streetAddress": "вул. Островського, 34"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "name": "Андрій Олексюк",
          "telephone": "+380322916930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Книга»",
        "scale": "sme"
      }
    ],
    "lotValues": [
      {
        "value": {
          "amount": 500
        },
        "relatedLot": "f5711b9bc6ec4743b53e78759874481a"
      },
      {
        "subcontractingDetails": "ДКП «Укр Прінт», Україна",
        "value": {
          "amount": 500
        },
        "relatedLot": "1a3ccfcc596347ddad9d263e4c05c8e2"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7b32e93503314032810e6dd5a0209cee/bids/96460d40cabd4bc3aad6e6afead0fc53

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "uri": "http://www.sc.gov.ua/"
        },
        "scale": "sme",
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Андрій Олексюк",
          "email": "aagt@gmail.com",
          "telephone": "+380322916930"
        }
      }
    ],
    "status": "draft",
    "lotValues": [
      {
        "status": "pending",
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "f5711b9bc6ec4743b53e78759874481a",
        "date": "2023-10-10T01:00:00+03:00"
      },
      {
        "status": "pending",
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "1a3ccfcc596347ddad9d263e4c05c8e2",
        "subcontractingDetails": "ДКП «Укр Прінт», Україна",
        "date": "2023-10-10T01:00:00+03:00"
      }
    ],
    "selfQualified": true,
    "id": "96460d40cabd4bc3aad6e6afead0fc53",
    "date": "2023-10-10T01:00:00+03:00"
  },
  "access": {
    "token": "19c5ea09514f45bd8285348bb3838335",
    "transfer": "69f70036c31d4bbcab9b97cd101ed8b8"
  }
}

