PATCH /api/2.5/tenders/add2f90809854b4f949c030f5eb3d9ad/bids/701cc13b26a7473bab46f949977b6f77?acc_token=d26e2f23c72e4385b4315d6cefcbc123 HTTP/1.0
Authorization: Bearer broker
Content-Length: 124
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "lotValues": [
      {
        "value": {
          "amount": 500
        },
        "relatedLot": "f5fdc116c69e4821881e9a7e792b8c11"
      }
    ],
    "status": "pending"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "7130e427f64e44bfa2795f268d95b6a8",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True",
        "id": "dc50b9fc3cb44e338312fb0c7b231865"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "094b3dd2bf35446ea5f29e412feaae2e",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True",
        "id": "860916ec42214a89b5996e1d043e540b"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a6054a0507fc4c52b8186b71f7599f19",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True",
        "id": "ead203e90ec04598aec4961cb6ae5128"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "f593d819a26b4df1842ea3bb18be3b4d",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True",
        "id": "2f86b058a94144c4af9d852d198049b1"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "e08fc62031ba48c29f5cc86bdb17d30c",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True",
        "id": "ce0533e025e446218082b9171669d9bd"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "7cf9d42dae734215b77379d13c1c1210",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True",
        "id": "2ae49084ef8843519502a11d320b8c14"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "2ff2b904b29643f2a0bbcbb048976a2e",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True",
        "id": "13c5d911060a49a690dc32eb3e26791b"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "3ad65715a2bd414e9b6b5296d62c1646",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True",
        "id": "f48e31130f2247fbbee8e161047f80f1"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "5b21787372ad4ee395e0ba55dd754464",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True",
        "id": "16fadd1847da43469b07b3ce8c41363f"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "f4b7dabec0694bd2b96621de2b8d9ded",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True",
        "id": "f28cb3f8252e4570b23e7cb32aca1433"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "32056e7fb97d4176a9c9ff528acc639c",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True",
        "id": "6d15e97856f94d159103b22dae60cc3c"
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "telephone": "+380322916930",
          "name": "Андрій Олексюк"
        },
        "scale": "sme"
      }
    ],
    "id": "701cc13b26a7473bab46f949977b6f77",
    "date": "2023-01-01T00:00:00+02:00",
    "lotValues": [
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "f5fdc116c69e4821881e9a7e792b8c11",
        "date": "2023-01-01T00:00:00+02:00",
        "status": "pending"
      }
    ],
    "selfQualified": true,
    "status": "pending"
  }
}

