PATCH /api/2.5/tenders/438aef21947a4a09b39118b30a029983?acc_token=0a7bc93b7888415684a0ce45d6271f2d HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "documents",
      "description": "Document with type 'evaluationReports' and format pkcs7-signature is required"
    }
  ]
}

