GET /api/2.5/tenders/4f6f9f4965ae47e99cd03a167c41c1a0/qualifications?acc_token=446ff1f48bde44b08788bbf0b34f6d62 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "dad5d663985f4e1f89fed69eb21d3b97",
      "bidID": "491e23c37ed44b8b85e972f227307b80",
      "lotID": "5563fbab2bd848b398a5de9cb3ac555b",
      "status": "pending",
      "date": "2021-03-16T00:00:00+02:00",
      "qualified": false,
      "eligible": false
    },
    {
      "id": "eb923e797e5045e78c90c59bdb3fc212",
      "bidID": "6a589730254f47ac99ab0eee03d6770f",
      "lotID": "5563fbab2bd848b398a5de9cb3ac555b",
      "status": "pending",
      "date": "2021-03-16T00:00:00+02:00",
      "qualified": false,
      "eligible": false
    }
  ]
}

