POST /api/2.5/tenders/add2f90809854b4f949c030f5eb3d9ad/criteria?acc_token=f0df40efa0ec47409acf433ef0550506 HTTP/1.0
Authorization: Bearer broker
Content-Length: 51409
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": [
    {
      "title": "Вчинення злочинів, учинених з корисливих мотивів",
      "description": "Службова (посадова) особа учасника процедури закупівлі, яка підписала тендерну пропозицію (або уповноважена на підписання договору в разі переговорної процедури закупівлі) або фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
      "source": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.5"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.6"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник фізична особа підтверджує, що",
          "requirements": [
            {
              "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
              "dataType": "boolean",
              "expectedValue": "true",
              "eligibleEvidences": [
                {
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "document"
                }
              ]
            }
          ]
        },
        {
          "description": "Учасник юридична особа підтверджує, що",
          "requirements": [
            {
              "title": "Службова (посадова) особа учасника процедури закупівлі, яка підписала тендерну пропозицію (або уповноважена на підписання договору в разі переговорної процедури закупівлі), не була засуджена за злочин, вчинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом, шахрайством та відмиванням коштів), судимість з якої  знято або погашено у встановленому законом порядку",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        }
      ]
    },
    {
      "title": "Вчинення економічних правопорушень",
      "description": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів",
      "source": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.4"
        },
        {
          "version": "2020-02-13",
          "identifier": {
            "id": "2210-III",
            "legalName": "Закон України \"Про захист економічної конкуренції\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/2210-14"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "6.2.4"
        },
        {
          "version": "2020-02-13",
          "identifier": {
            "id": "2210-III",
            "legalName": "Закон України \"Про захист економічної конкуренції\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/2210-14"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "50.1"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        }
      ]
    },
    {
      "title": "Вчинення корупційних правопорушень",
      "description": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення. Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією",
      "source": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.2"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.3"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення",
              "dataType": "boolean",
              "expectedValue": "true"
            },
            {
              "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        }
      ]
    },
    {
      "title": "Вчинення правопорушень, пов'язаних з використанням дитячої праці чи будь-якими формами торгівлі людьми",
      "description": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми",
      "source": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.12"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        }
      ]
    },
    {
      "title": "Заборгованість зі сплати податків і зборів (обов'язкових платежів)",
      "description": "Учасник процедури закупівлі не має заборгованості зі сплати податків і зборів (обов'язкових платежів)",
      "source": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_TAXES"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.13"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        },
        {
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "title": "Він має заборгованість зі сплати податків і зборів (обов'язкових платежів)",
              "dataType": "boolean",
              "expectedValue": "true"
            },
            {
              "title": "Сума існуючої заборгованості",
              "dataType": "number"
            },
            {
              "title": "Характер існуючої заборгованості",
              "dataType": "string"
            },
            {
              "title": "Причина виникнення існуючої заборгованості",
              "dataType": "string"
            },
            {
              "title": "Учасник здійснив заходи щодо розстрочення і відстрочення такої заборгованості у порядку та на умовах, визначених законодавством країни реєстрації такого учасника",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        }
      ]
    },
    {
      "title": "Порушення справ про банкрутство",
      "description": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура",
      "source": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.8"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        }
      ]
    },
    {
      "title": "Виявлення факту зв'язку учасника з іншими учасниками процедури або замовником",
      "description": "Тендерна пропозиція подана учасником конкурентної процедури закупівлі або участь у переговорній процедурі бере учасник, який є пов'язаною особою з іншими учасниками процедури закупівлі та/або з уповноваженою особою (особами), та/або з керівником замовника",
      "source": "procuringEntity",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.MISCONDUCT.MARKET_DISTORTION"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.7"
        }
      ],
      "requirementGroups": [
        {
          "description": "Замовник підтверджує, що",
          "requirements": [
            {
              "title": "Тендерна пропозиція подана учасником конкурентної процедури закупівлі або участь у переговорній процедурі бере учасник, який є пов'язаною особою з іншими учасниками процедури закупівлі та/або з уповноваженою особою (особами), та/або з керівником замовника",
              "dataType": "boolean",
              "eligibleEvidences": [
                {
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "document"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "Виявлення факту наміру впливу на прийняття рішення замовника",
      "description": "Замовник має незаперечні докази того, що учасник процедури закупівлі пропонує, дає або погоджується дати прямо чи опосередковано будь-якій службовій (посадовій) особі замовника, іншого державного органу винагороду в будь-якій формі (пропозиція щодо найму на роботу, цінна річ, послуга тощо) з метою вплинути на прийняття рішення щодо визначення переможця процедури закупівлі або застосування замовником певної процедури закупівлі",
      "source": "procuringEntity",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.MISINTERPRETATION"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.1"
        }
      ],
      "requirementGroups": [
        {
          "description": "Замовник підтверджує, що",
          "requirements": [
            {
              "title": "Замовник має незаперечні докази того, що учасник процедури закупівлі пропонує, дає або погоджується дати прямо чи опосередковано будь-якій службовій (посадовій) особі замовника, іншого державного органу винагороду в будь-якій формі (пропозиція щодо найму на роботу, цінна річ, послуга тощо) з метою вплинути на прийняття рішення щодо визначення переможця процедури закупівлі або застосування замовником певної процедури закупівлі",
              "dataType": "boolean"
            }
          ]
        }
      ]
    },
    {
      "title": "Наявність інших підстав для відмови в участі у процедурі закупівлі",
      "description": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)",
      "source": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.NATIONAL.OTHER"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.9"
        },
        {
          "version": "2020-03-16",
          "identifier": {
            "id": "755-IV",
            "legalName": "Закон України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/755-15"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "9.2.9"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.10"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.11"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "1644-VII",
            "legalName": "Закон України \"Про санкції\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/1644-18"
          },
          "type": "NATIONAL_LEGISLATION"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)",
              "dataType": "boolean",
              "expectedValue": "true"
            },
            {
              "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)",
              "dataType": "boolean",
              "expectedValue": "true"
            },
            {
              "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\"",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        }
      ]
    },
    {
      "title": "Мова (мови), якою (якими) повинні готуватися тендерні пропозиції",
      "source": "tenderer",
      "classification": {
        "scheme": " ESPD211",
        "id": "CRITERION.OTHER.BID.LANGUAGE"
      },
      "relatesTo": "tenderer",
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION"
        }
      ],
      "requirementGroups": [
        {
          "description": "Учасник фізична особа підтверджує, що",
          "requirements": [
            {
              "title": "Мова тендерної пропозиції українська",
              "dataType": "boolean",
              "expectedValue": "true"
            }
          ]
        }
      ]
    }
  ]
}

Response: 201 Created
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "3b4c9ca02fef410fbe2aa4c355f0f5d4",
      "title": "Вчинення злочинів, учинених з корисливих мотивів",
      "description": "Службова (посадова) особа учасника процедури закупівлі, яка підписала тендерну пропозицію (або уповноважена на підписання договору в разі переговорної процедури закупівлі) або фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.5"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.6"
        }
      ],
      "requirementGroups": [
        {
          "id": "ec5ec1ee1d124432bbc089643ec7b033",
          "description": "Учасник фізична особа підтверджує, що",
          "requirements": [
            {
              "id": "cae58491788843f7b92a7365efe48291",
              "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку",
              "dataType": "boolean",
              "eligibleEvidences": [
                {
                  "id": "d35ff393c5cc436bbc801bc407b7a120",
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "document"
                }
              ],
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        },
        {
          "id": "15083e0ca7f749798311238ea2902bd0",
          "description": "Учасник юридична особа підтверджує, що",
          "requirements": [
            {
              "id": "977f8bc4f29f498abf530644c293862f",
              "title": "Службова (посадова) особа учасника процедури закупівлі, яка підписала тендерну пропозицію (або уповноважена на підписання договору в разі переговорної процедури закупівлі), не була засуджена за злочин, вчинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом, шахрайством та відмиванням коштів), судимість з якої  знято або погашено у встановленому законом порядку",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "81ed2ce0f3c44c6aa7662a45bab23791",
      "title": "Вчинення економічних правопорушень",
      "description": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.4"
        },
        {
          "version": "2020-02-13",
          "identifier": {
            "id": "2210-III",
            "legalName": "Закон України \"Про захист економічної конкуренції\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/2210-14"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "6.2.4"
        },
        {
          "version": "2020-02-13",
          "identifier": {
            "id": "2210-III",
            "legalName": "Закон України \"Про захист економічної конкуренції\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/2210-14"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "50.1"
        }
      ],
      "requirementGroups": [
        {
          "id": "bc3fe9360f704e9baa1c04a253300432",
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "id": "42233dff2f414d7e9cbc031a2094ce30",
              "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "04d822c0d945428994a72040b3152537",
      "title": "Вчинення корупційних правопорушень",
      "description": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення. Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.2"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.3"
        }
      ],
      "requirementGroups": [
        {
          "id": "6996464a56834263903036b78ce63568",
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "id": "0534592911644cc190b56a70cd80790e",
              "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            },
            {
              "id": "1b634151ad294aac9731b53ffdc3decf",
              "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "a645c68249354a6cb2622c1d75782e91",
      "title": "Вчинення правопорушень, пов'язаних з використанням дитячої праці чи будь-якими формами торгівлі людьми",
      "description": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.12"
        }
      ],
      "requirementGroups": [
        {
          "id": "9725d830bd1d4f48aed3661503695fe4",
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "id": "b55845801416468781bb8f56d95dbb21",
              "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "cff5f0f889bb4967a9741237126cac36",
      "title": "Заборгованість зі сплати податків і зборів (обов'язкових платежів)",
      "description": "Учасник процедури закупівлі не має заборгованості зі сплати податків і зборів (обов'язкових платежів)",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_TAXES"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.13"
        }
      ],
      "requirementGroups": [
        {
          "id": "c7a97da38bc34ea7b89b5e9e2c25456a",
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "id": "efaa1d59eab54b688941c536c98743cf",
              "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        },
        {
          "id": "c1f338985c684bbeba51af574e265c63",
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "id": "7ad9a052c2714696b4c90def57a2e39b",
              "title": "Він має заборгованість зі сплати податків і зборів (обов'язкових платежів)",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            },
            {
              "id": "029d3563f31e400e89a18802b455ade7",
              "title": "Сума існуючої заборгованості",
              "dataType": "number",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            },
            {
              "id": "9e48ca5af60c4d7bb084eeee62630c27",
              "title": "Характер існуючої заборгованості",
              "dataType": "string",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            },
            {
              "id": "f77d36d39b254b03b5af205936a21150",
              "title": "Причина виникнення існуючої заборгованості",
              "dataType": "string",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            },
            {
              "id": "5d4f42b1aff843188c4753f3f8406232",
              "title": "Учасник здійснив заходи щодо розстрочення і відстрочення такої заборгованості у порядку та на умовах, визначених законодавством країни реєстрації такого учасника",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "fa4c8edb6c4b4aafb2ce8849ff57d0d3",
      "title": "Порушення справ про банкрутство",
      "description": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.8"
        }
      ],
      "requirementGroups": [
        {
          "id": "486d6900ee2b4b51ad65861bedcec350",
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "id": "e5c1c691ecf84ac0b87b4f4e7d4d9167",
              "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "86c220edb9db46d78ab703f22b3f5bfd",
      "title": "Виявлення факту зв'язку учасника з іншими учасниками процедури або замовником",
      "description": "Тендерна пропозиція подана учасником конкурентної процедури закупівлі або участь у переговорній процедурі бере учасник, який є пов'язаною особою з іншими учасниками процедури закупівлі та/або з уповноваженою особою (особами), та/або з керівником замовника",
      "source": "procuringEntity",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.MISCONDUCT.MARKET_DISTORTION"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.7"
        }
      ],
      "requirementGroups": [
        {
          "id": "7361ddf8b9dd4ccbab854c53c272e3a0",
          "description": "Замовник підтверджує, що",
          "requirements": [
            {
              "id": "53407c04b1ef43049d8cef010aa39dd3",
              "title": "Тендерна пропозиція подана учасником конкурентної процедури закупівлі або участь у переговорній процедурі бере учасник, який є пов'язаною особою з іншими учасниками процедури закупівлі та/або з уповноваженою особою (особами), та/або з керівником замовника",
              "dataType": "boolean",
              "eligibleEvidences": [
                {
                  "id": "5f17bf4d7fde4f219b847f6d70ee3a8e",
                  "title": "Документальне підтвердження",
                  "description": "Довідка в довільній формі",
                  "type": "document"
                }
              ],
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "580268f4632e4e70bd6489d2af08c1f8",
      "title": "Виявлення факту наміру впливу на прийняття рішення замовника",
      "description": "Замовник має незаперечні докази того, що учасник процедури закупівлі пропонує, дає або погоджується дати прямо чи опосередковано будь-якій службовій (посадовій) особі замовника, іншого державного органу винагороду в будь-якій формі (пропозиція щодо найму на роботу, цінна річ, послуга тощо) з метою вплинути на прийняття рішення щодо визначення переможця процедури закупівлі або застосування замовником певної процедури закупівлі",
      "source": "procuringEntity",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.MISINTERPRETATION"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.1"
        }
      ],
      "requirementGroups": [
        {
          "id": "15b35ca86aec4eb189e74bbdf73ac1c6",
          "description": "Замовник підтверджує, що",
          "requirements": [
            {
              "id": "e9e9556553344335a3371c0ef2a31303",
              "title": "Замовник має незаперечні докази того, що учасник процедури закупівлі пропонує, дає або погоджується дати прямо чи опосередковано будь-якій службовій (посадовій) особі замовника, іншого державного органу винагороду в будь-якій формі (пропозиція щодо найму на роботу, цінна річ, послуга тощо) з метою вплинути на прийняття рішення щодо визначення переможця процедури закупівлі або застосування замовником певної процедури закупівлі",
              "dataType": "boolean",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "3a22440a4f3240c89275d2534aca9369",
      "title": "Наявність інших підстав для відмови в участі у процедурі закупівлі",
      "description": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " espd211",
        "id": "CRITERION.EXCLUSION.NATIONAL.OTHER"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.9"
        },
        {
          "version": "2020-03-16",
          "identifier": {
            "id": "755-IV",
            "legalName": "Закон України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/755-15"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "9.2.9"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.10"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "17.1.11"
        },
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "1644-VII",
            "legalName": "Закон України \"Про санкції\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/1644-18"
          },
          "type": "NATIONAL_LEGISLATION"
        }
      ],
      "requirementGroups": [
        {
          "id": "d033398e5d8647f9bccd49b604ef3256",
          "description": "Учасник підтверджує, що",
          "requirements": [
            {
              "id": "6054d7110e6d4ff0b04a561cc1cbf4d6",
              "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            },
            {
              "id": "f8269378de0b422fb188bec4b2a6e625",
              "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            },
            {
              "id": "32ba2855843c40b5bd5529c4f028b0b5",
              "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\"",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    },
    {
      "id": "a95435c873b54ae9aa1ff4e2c436dbca",
      "title": "Мова (мови), якою (якими) повинні готуватися тендерні пропозиції",
      "source": "tenderer",
      "relatesTo": "tenderer",
      "classification": {
        "scheme": " ESPD211",
        "id": "CRITERION.OTHER.BID.LANGUAGE"
      },
      "legislation": [
        {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
          },
          "type": "NATIONAL_LEGISLATION"
        }
      ],
      "requirementGroups": [
        {
          "id": "cca297e0213142d6a5236165b0d7c66a",
          "description": "Учасник фізична особа підтверджує, що",
          "requirements": [
            {
              "id": "bfddd7a39811425da93fa71507aa8edc",
              "title": "Мова тендерної пропозиції українська",
              "dataType": "boolean",
              "expectedValue": "true",
              "status": "active",
              "datePublished": "2023-01-01T00:00:00+02:00"
            }
          ]
        }
      ]
    }
  ]
}

