PATCH /api/2.5/tenders/4f6f9f4965ae47e99cd03a167c41c1a0/lots/e2a64c7bb22f4a6d838531ede04bc02a?acc_token=446ff1f48bde44b08788bbf0b34f6d62 HTTP/1.0
Authorization: Bearer broker
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "value": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "e2a64c7bb22f4a6d838531ede04bc02a",
    "title": "Лот №2",
    "description": "Опис Лот №2",
    "date": "2021-03-16T00:00:00+02:00",
    "status": "active",
    "value": {
      "amount": 400.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "minimalStep": {
      "amount": 5.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "auctionPeriod": {
      "shouldStartAfter": "2021-05-21T00:00:00+02:00"
    }
  }
}

