GET /api/2.5/tenders/57baff7abc454a00be404f9f6ba19f64 HTTP/1.0
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "title_en": "Services in school canteens",
    "title_ru": "Услуги школьных столовых",
    "description_en": "Services in school canteens",
    "description_ru": "Услуги школьных столовых",
    "date": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "dateCreated": "2023-10-10T01:00:00+03:00",
    "tenderID": "UA-2023-10-10-000001-a",
    "owner": "broker",
    "title": "Послуги шкільних їдалень",
    "mainProcurementCategory": "services",
    "procurementMethod": "limited",
    "procuringEntity": {
      "name": "ЗОСШ #10 м.Вінниці",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "21725150",
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      },
      "address": {
        "streetAddress": "вул. Стахурського. 22",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21027",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Куца Світлана Валентинівна",
        "telephone": "+380432465302",
        "url": "http://sch10.edu.vn.ua/"
      },
      "kind": "special"
    },
    "status": "active",
    "value": {
      "amount": 500000.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "items": [
      {
        "id": "02f14fa680c8460f803c5fefeb3f9a74",
        "description": "Послуги шкільних їдалень",
        "unit": {
          "name": "папір",
          "value": {
            "amount": 10.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": true
          },
          "code": "KGM"
        },
        "quantity": 1.0,
        "classification": {
          "description": "Послуги з харчування у школах",
          "scheme": "ДК021",
          "id": "55523100-3"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "relatedLot": "ca54d1673c8445ac8a53f411406d170c",
        "deliveryDate": {
          "startDate": "2023-10-30T00:00:00+02:00",
          "endDate": "2023-11-29T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        }
      }
    ],
    "causeDescription": "оригінальний тендер не вдався двічі",
    "causeDescription_en": "original tender has failed twice",
    "causeDescription_ru": "оригинальный тендер не получился дважды",
    "lots": [
      {
        "title": "Лот №1",
        "description": "Опис Лот №1",
        "status": "active",
        "id": "ca54d1673c8445ac8a53f411406d170c",
        "date": "2023-10-10T01:00:00+03:00",
        "value": {
          "amount": 500000.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        }
      }
    ],
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "type": "financing",
        "code": "prepayment",
        "percentage": 45.55,
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 0
      },
      {
        "id": "86cf8f5e53964cae99e652b8c0050e5f",
        "title": "deliveryOfGoods",
        "type": "financing",
        "code": "postpayment",
        "percentage": 54.45,
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 0
      }
    ],
    "procurementMethodType": "negotiation.quick",
    "cause": "twiceUnsuccessful",
    "id": "57baff7abc454a00be404f9f6ba19f64"
  },
  "config": {
    "hasAuction": false,
    "hasAwardingOrder": true,
    "hasValueRestriction": true,
    "valueCurrencyEquality": true,
    "hasPrequalification": false,
    "minBidsNumber": 1,
    "hasPreSelectionAgreement": false,
    "hasTenderComplaints": false,
    "hasAwardComplaints": true,
    "hasCancellationComplaints": true,
    "hasValueEstimation": true,
    "restricted": false
  }
}

