POST /api/2.5/tenders/f424e2934d9c4a28a98ace88bd50ea47/awards?acc_token=385a1b964fc04c10a6acb22ee6e53ea6 HTTP/1.0
Authorization: Bearer broker
Content-Length: 916
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending",
    "suppliers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro"
      }
    ],
    "value": {
      "amount": 475000,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "lotID": "9c7ee9a761404c7cad1359f248e41f71"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f424e2934d9c4a28a98ace88bd50ea47/awards/068069057cb14911bb25053f0fd9d0cc
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending",
    "value": {
      "amount": 475000.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "suppliers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "lotID": "9c7ee9a761404c7cad1359f248e41f71",
    "id": "068069057cb14911bb25053f0fd9d0cc",
    "date": "2021-03-16T00:00:00+02:00"
  }
}

