POST /api/2.5/tenders/5df232c51fe546ab9d77b698e74e70e8/lots?acc_token=256c51452b26431bb4013b804989df6c HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Лот №1",
    "description": "Опис Лот №1",
    "value": {
      "amount": 500000,
      "currency": "UAH",
      "valueAddedTaxIncluded": false
    }
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5df232c51fe546ab9d77b698e74e70e8/lots/7ef14321e86047b09378ef9cf3465b9a

{
  "data": {
    "title": "Лот №1",
    "description": "Опис Лот №1",
    "id": "7ef14321e86047b09378ef9cf3465b9a",
    "status": "active",
    "value": {
      "amount": 500000.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "date": "2023-10-10T01:00:00+03:00"
  }
}

