GET /api/2.5/agreements/6305e36dbee94cfd9dd0bab9039a9265/documents?acc_token=9202afaa0bda4d5a8d604c4bac984417 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "0f0e62d22bfb487f862147c5e6574a9f",
      "hash": "md5:00000000000000000000000000000000",
      "title": "agreement_changes.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/942027dcdf104710ae89a8b24ad17b2f?Signature=QeOTNEJAy61PDdhoPsFB05UN76DqJVhf3QNEEkUq0v3EhCCG9czKUpWuTjQWEHRe0ghB6zx8WGIW%2B9wviyqoDQ%3D%3D&KeyID=a8968c46",
      "datePublished": "2021-03-16T00:00:00+02:00",
      "dateModified": "2021-03-16T00:00:00+02:00",
      "relatedItem": "42b702292a4947b6b3872286c6b12996",
      "documentOf": "change"
    },
    {
      "id": "b6d6203d1d7441d7a882d833cf65d99e",
      "hash": "md5:00000000000000000000000000000000",
      "title": "agreement.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f405a07f9bde4172a0e0aae66b334735?Signature=WzT2qvX2qAj8EpcjXb7dzmLf1DJ1ok00el6Wm7%2FhRvbgIkg0S07uRnOC6m1qhbfrmngRbrBnBtVwlbD7Ju9yCA%3D%3D&KeyID=a8968c46",
      "datePublished": "2021-03-16T00:00:00+02:00",
      "dateModified": "2021-03-16T00:00:00+02:00",
      "documentOf": "agreement"
    }
  ]
}

