PATCH /api/2.5/agreements/eb35d61e7cde4a008003f5cd17ddb0c7/changes/5937223446a044e689f16dc9912fed8b?acc_token=76b0c07026994e7089d5f9716acfc3e7 HTTP/1.0
Authorization: Bearer broker
Content-Length: 73
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "dateSigned": "2020-05-15T01:00:00+03:00"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "modifications": [
      {
        "itemId": "54eee06ff6d24b12b8e84dfe65d1b6b7", 
        "factor": 0.1605
      }
    ], 
    "rationaleType": "taxRate", 
    "rationale_en": "Agreement change cause", 
    "dateSigned": "2020-05-15T01:00:00+03:00", 
    "rationale": "Друга і третя поставка має бути розфасована", 
    "date": "2020-05-15T01:00:00+03:00", 
    "id": "5937223446a044e689f16dc9912fed8b"
  }
}

