PATCH /api/2.5/agreements/eb35d61e7cde4a008003f5cd17ddb0c7/documents/b8f02cdfc2cc43c2a6a5f014d524afc6?acc_token=76b0c07026994e7089d5f9716acfc3e7 HTTP/1.0
Authorization: Bearer broker
Content-Length: 85
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "documentOf": "change", 
    "relatedItem": "5937223446a044e689f16dc9912fed8b"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "agreement_changes.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a51bbc22366e41c6b012eeb99b212994?KeyID=a8968c46&Signature=6dYoov%252BfN7fg0%252BkmGHAQPvWlPvpf%2Fj1WIfx5e1YWZhoA7APSP60DFNJ5upL34Ckd3f9JCbUJrK2aR00ums%252BPAA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "change", 
    "datePublished": "2020-05-15T01:00:00+03:00", 
    "id": "b8f02cdfc2cc43c2a6a5f014d524afc6", 
    "relatedItem": "5937223446a044e689f16dc9912fed8b", 
    "dateModified": "2020-05-15T01:00:00+03:00"
  }
}

