PATCH /api/2.5/tenders/c8fbbe1ddf3642a6815bd2c7c26581b1/bids/402838d34bfc4c6399da2eb61eb5f19f?acc_token=abc795ce602148c58b90bf49f1c128f8 HTTP/1.0
Authorization: Bearer broker
Content-Length: 98
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "lotValues": [
      {
        "relatedLot": "3f6334296c1540158ccf4b0a2532048c"
      }
    ],
    "status": "pending"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "85b51548a28140328884d98eef3365ce",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True",
        "id": "634bf3100ee646ff88e8a20db788e34c"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "c774665522474aed8f37e2ff9cde639a",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True",
        "id": "9162d617281b418c96d08fe5189d3372"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "cc49a051ae604ef4a4fd29d0a86ce20c",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True",
        "id": "3ff0fdcbf73a4134b0cf6709b157ede4"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "787e6d37e99e444a993bbabf3a0a3a13",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True",
        "id": "7993313cf4ca4578ae4f93614c4e3a92"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "be06415ab85d4025a0739d61aa043555",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True",
        "id": "454cd24d23da42a08b68f32cc6eb638d"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "e83b27e560b44de7b5c9d1a4b3e04348",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True",
        "id": "b8f80bbebc2f4c04b5b25dcfdfbf7364"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "aa7e40235972472d9f39f87245713e90",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True",
        "id": "3a39485bde3740f4bd28dfec1b2ea245"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "eae847c2b9fb4667a194d308bffccb5e",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True",
        "id": "13a9b736ddd84b0fa0b7e13d65bc793b"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "ee88cdba089d4d738ef0a53c190f32f4",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True",
        "id": "b643d4700e464b05abc3103e71efa190"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "6275bd616be04b1186c42e060f164604",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True",
        "id": "17319ff272e54a9d806383a4dd6e882c"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "8e5ca061fd38468bb67a91c66d893346",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True",
        "id": "aaabd03cf57e4547a22e9269e886345b"
      }
    ],
    "id": "402838d34bfc4c6399da2eb61eb5f19f",
    "date": "2023-01-01T00:00:00+02:00",
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "telephone": "+380322916930",
          "name": "Андрій Олексюк"
        },
        "scale": "sme"
      }
    ],
    "lotValues": [
      {
        "relatedLot": "3f6334296c1540158ccf4b0a2532048c",
        "status": "pending",
        "date": "2023-01-01T00:00:00+02:00"
      }
    ],
    "selfQualified": true,
    "status": "pending"
  }
}

