POST /api/2.5/tenders/0122f7569ef34718a69b5de8643cccfd/lots?acc_token=e179e7123ebc4555bde66499540f5ee6 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Лот №1",
    "description": "Опис Лот №1",
    "value": {
      "currency": "UAH",
      "amount": 500
    },
    "minimalStep": {
      "amount": 5,
      "currency": "UAH"
    }
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0122f7569ef34718a69b5de8643cccfd/lots/176e6033e7af4efc95f6a5c290a3311d

{
  "data": {
    "title": "Лот №1",
    "description": "Опис Лот №1",
    "id": "176e6033e7af4efc95f6a5c290a3311d",
    "status": "active",
    "value": {
      "currency": "UAH",
      "amount": 500.0,
      "valueAddedTaxIncluded": true
    },
    "minimalStep": {
      "currency": "UAH",
      "amount": 5.0,
      "valueAddedTaxIncluded": true
    },
    "date": "2023-10-10T01:00:00+03:00"
  }
}

