GET /api/2.5/tenders/d59e1783dc5149518a3c20a016d652c6 HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "title": "Послуги шкільних їдалень",
    "date": "2021-03-16T00:00:00+02:00",
    "dateModified": "2021-03-16T00:00:00+02:00",
    "tenderID": "UA-2021-03-16-000001",
    "owner": "broker",
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "type": "financing",
        "code": "prepayment",
        "percentage": 45.55,
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 0
      },
      {
        "id": "c59dad417eb54ba3a23e2a223f11673a",
        "title": "deliveryOfGoods",
        "type": "financing",
        "code": "postpayment",
        "percentage": 54.45,
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 0
      }
    ],
    "procurementMethod": "open",
    "submissionMethod": "electronicAuction",
    "value": {
      "amount": 1000.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "minimalStep": {
      "amount": 5.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "title_en": "Services in school canteens",
    "enquiryPeriod": {
      "startDate": "2021-03-16T00:00:00+02:00",
      "endDate": "2021-04-06T00:00:00+02:00",
      "clarificationsUntil": "2021-04-09T00:00:00+02:00",
      "invalidationDate": "2021-03-16T00:00:00+02:00"
    },
    "tenderPeriod": {
      "startDate": "2021-03-16T00:00:00+02:00",
      "endDate": "2021-04-16T00:00:00+02:00"
    },
    "procuringEntity": {
      "name": "ЗОСШ #10 м.Вінниці",
      "name_en": "School #10 of Vinnytsia",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "21725150",
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\"",
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\""
      },
      "address": {
        "streetAddress": "вул. Стахурського. 22",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21027",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Куца Світлана Валентинівна",
        "telephone": "+380 (432) 46-53-02",
        "url": "http://sch10.edu.vn.ua/",
        "name_en": "Kutsa Svitlana V.",
        "availableLanguage": "uk"
      },
      "kind": "general"
    },
    "awardCriteria": "lowestCost",
    "procurementMethodType": "competitiveDialogueEU",
    "status": "active.tendering",
    "lots": [
      {
        "id": "150e2750fa2942ce9315e80ddf78a62a",
        "title": "Лот №1",
        "description": "Опис Лот №1",
        "date": "2021-03-16T00:00:00+02:00",
        "status": "active",
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "minimalStep": {
          "amount": 5.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        }
      },
      {
        "id": "a18842d9d4a349c799437d0102e40965",
        "title": "Лот №2",
        "description": "Опис Лот №2",
        "date": "2021-03-16T00:00:00+02:00",
        "status": "active",
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "minimalStep": {
          "amount": 5.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        }
      }
    ],
    "items": [
      {
        "id": "703253b41d51418297317c843aeb1296",
        "description": "Послуги шкільних їдалень",
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "unit": {
          "name": "item",
          "code": "44617100-9"
        },
        "quantity": 1.0,
        "relatedLot": "150e2750fa2942ce9315e80ddf78a62a",
        "classification": {
          "description": "Test",
          "scheme": "ДК021",
          "id": "37810000-9"
        },
        "deliveryDate": {
          "startDate": "2021-04-05T00:00:00+02:00",
          "endDate": "2021-05-05T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "description_en": "Services in school canteens"
      },
      {
        "id": "5896ec7b8cfb474b9e59135157f705e9",
        "description": "Послуги шкільних їдалень",
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "unit": {
          "name": "item",
          "code": "44617100-9"
        },
        "quantity": 1.0,
        "relatedLot": "a18842d9d4a349c799437d0102e40965",
        "classification": {
          "description": "Test",
          "scheme": "ДК021",
          "id": "37810000-9"
        },
        "deliveryDate": {
          "startDate": "2021-04-05T00:00:00+02:00",
          "endDate": "2021-05-05T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "description_en": "Services in school canteens"
      }
    ],
    "mainProcurementCategory": "services",
    "id": "d59e1783dc5149518a3c20a016d652c6",
    "next_check": "2021-04-16T01:00:00+03:00",
    "complaintPeriod": {
      "startDate": "2021-03-16T00:00:00+02:00",
      "endDate": "2021-04-12T00:00:00+02:00"
    }
  }
}

