GET /api/2.5/tenders/5fd17b367a75453582bffe24ae83b896/bids/06f2567220044d888fd89ce8ed583b34/documents?acc_token=a6961b269f624e39aabccf7327530788 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "Proposal.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3be837e3115f465aa712df8bcef14439?Signature=MI9PnY2SNEsdQCyz7pxKIZAs3mXQJ0Hz%2BZLPkgbTlgq2QhPIBWeixbkL1BjXHfmZh37uwWqvQ3BdV8J6DmLyAg%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "75b07275c0f248a8bc4839d71fd086d3",
      "confidentiality": "public",
      "datePublished": "2023-10-10T01:00:01+03:00",
      "dateModified": "2023-10-10T01:00:01+03:00"
    }
  ]
}

