GET /api/2.5/tenders/3d69f16d617642b88f9248c606bb0723/questions/9fa3cf28eff948acb5937f7742ca8da2 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "9fa3cf28eff948acb5937f7742ca8da2",
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2023-01-01T00:00:00+02:00",
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
    "questionOf": "tender",
    "dateAnswered": "2023-01-01T00:00:00+02:00"
  }
}

