GET /api/2.5/tenders/cafcd819d62040129cffcd9b3f3687df/questions HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "id": "f281a2bdac4b4c978d407f146e274caa",
      "author": {
        "hash": "2c7d8057c1b1d754f45073d505e86c57"
      },
      "title": "Калорійність",
      "description": "Просимо додати таблицю потрібної калорійності харчування",
      "date": "2027-01-01T00:00:00+02:00",
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
      "questionOf": "tender",
      "dateAnswered": "2027-01-01T00:00:00+02:00"
    }
  ]
}

