POST /api/2.5/tenders/3cf3333f00394e93bc3caaea00cbe9e2/cancellations?acc_token=8ffdff061a7a416a9a2b245c75c35190 HTTP/1.0
Authorization: Bearer broker
Content-Length: 69
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reason": "cancellation reason",
    "reasonType": "noDemand"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/3cf3333f00394e93bc3caaea00cbe9e2/cancellations/b4bd632bd0b34acf976ec17197a9aef0

{
  "data": {
    "reasonType": "noDemand",
    "reason": "cancellation reason",
    "id": "b4bd632bd0b34acf976ec17197a9aef0",
    "date": "2023-01-01T00:00:03+02:00",
    "cancellationOf": "tender",
    "status": "draft"
  }
}

