POST /api/2.5/tenders/f8aae737ac8f4d34a52254e2f3416505/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 976
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro"
      }
    ],
    "value": {
      "amount": 500
    },
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "selfQualified": true,
    "selfEligible": true
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f8aae737ac8f4d34a52254e2f3416505/bids/a91aeed6db4a4969982ce37fab972938
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro"
      }
    ],
    "date": "2021-03-16T00:00:01+02:00",
    "id": "a91aeed6db4a4969982ce37fab972938",
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "status": "active",
    "selfQualified": true,
    "selfEligible": true
  },
  "access": {
    "token": "b6333f0eb61e422e8c473bf9f5ba0127",
    "transfer": "be60db29f88e4d2a829d3934ce065b4e"
  }
}

