POST /api/2.5/tenders/3d69f16d617642b88f9248c606bb0723/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 1358
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro"
      }
    ],
    "value": {
      "amount": 500
    },
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "selfQualified": true,
    "selfEligible": true
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/3d69f16d617642b88f9248c606bb0723/bids/7e41227e391e4f3884db7da200779189
X-Content-Type-Options: nosniff
{
  "data": {
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "status": "draft",
    "selfEligible": true,
    "selfQualified": true,
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "id": "7e41227e391e4f3884db7da200779189",
    "date": "2023-01-01T00:00:01+02:00"
  },
  "access": {
    "token": "e038986b62a4477f9eea8a9e132e93e0",
    "transfer": "542f8bcca1b5435292d14bd16ff46fec"
  }
}

