POST /api/2.5/tenders/f8aae737ac8f4d34a52254e2f3416505/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 824
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Львів",
          "postalCode": "79013",
          "region": "Львівська область",
          "streetAddress": "вул. Островського, 34"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "name": "Андрій Олексюк",
          "telephone": "+380 (322) 91-69-30"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Книга»",
        "scale": "sme"
      }
    ],
    "value": {
      "amount": 499
    },
    "selfQualified": true,
    "selfEligible": true
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f8aae737ac8f4d34a52254e2f3416505/bids/c014d12517fb42d689cd9b200fe56668
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Андрій Олексюк",
          "email": "aagt@gmail.com",
          "telephone": "+380 (322) 91-69-30"
        },
        "scale": "sme"
      }
    ],
    "date": "2021-03-16T00:00:01+02:00",
    "id": "c014d12517fb42d689cd9b200fe56668",
    "value": {
      "amount": 499.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "status": "active",
    "selfQualified": true,
    "selfEligible": true
  },
  "access": {
    "token": "833c7cf4dfb34873b1acf90aeaacbda4",
    "transfer": "1de5eef818f34a52b1b0c7bbdac6b0e9"
  }
}

