POST /api/2.5/tenders/f8aae737ac8f4d34a52254e2f3416505/contracts/8a1dfd6aef5e4681a481c9a4744d29e3/documents?acc_token=38dfa7b7e6ef4691b199e71e4247e9dc HTTP/1.0
Authorization: Bearer broker
Content-Length: 156
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="contract_document.doc"
Content-Type: application/msword

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f8aae737ac8f4d34a52254e2f3416505/contracts/8a1dfd6aef5e4681a481c9a4744d29e3/documents/feed2076a94a48e1810496af9b9e403e
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "feed2076a94a48e1810496af9b9e403e",
    "hash": "md5:00000000000000000000000000000000",
    "title": "contract_document.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8a968439bb234638b1981f50cddf8d1e?Signature=0w9B%2FeG%2FHzuWRPG6%2BF3P6%2BSk%2F67N0H4rGoVK%2FQrb7Xz30H%2BzHFPcMOjT7VeksJlGE30PJky1rOuiN5TGoihZCw%3D%3D&KeyID=a8968c46",
    "datePublished": "2021-03-16T00:00:03+02:00",
    "dateModified": "2021-03-16T00:00:03+02:00",
    "documentOf": "tender"
  }
}

