PUT /api/2.5/tenders/f8aae737ac8f4d34a52254e2f3416505/documents/e01aac4af6044a00a7f0771a73b1e814?acc_token=38dfa7b7e6ef4691b199e71e4247e9dc HTTP/1.0
Authorization: Bearer broker
Content-Length: 152
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="AwardCriteria-2.pdf"
Content-Type: application/pdf

content2
-----BOUNDARY--


Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "e01aac4af6044a00a7f0771a73b1e814",
    "hash": "md5:00000000000000000000000000000000",
    "title": "AwardCriteria-2.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d8e239fa45074edd95ddf73a9fc87683?Signature=XkOGMvL3v45e1K30IAPKb32Uc7Q%2FIzf74O%2F6ZNxwF0eSbRw9RiqGOf%2BhwVO0H0%2FXHpr8xLuM7vu4HBZ944h%2BBA%3D%3D&KeyID=a8968c46",
    "datePublished": "2021-03-16T00:00:00+02:00",
    "dateModified": "2021-03-16T00:00:00+02:00",
    "author": "tender_owner",
    "documentOf": "tender"
  }
}

