PATCH /api/2.5/tenders/b2ccf978cbbe4d5998adc7057db41ca4/cancellations/93dc08151b974c71b357910326916c08?acc_token=0686dbcd3079442fb4777eee185e6cd7 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reasonType": "unFixable"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "93dc08151b974c71b357910326916c08",
    "status": "draft",
    "date": "2027-01-01T00:00:01+02:00",
    "reasonType": "unFixable",
    "reason": "cancellation reason",
    "cancellationOf": "tender"
  }
}

