PATCH /api/2.5/tenders/896f80313bfc43d2aa3f0f44fc56a513/questions/056867c680574483a16cbd95402d6870?acc_token=f63fd82030a24dfc961d6995dc3f33d1 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "056867c680574483a16cbd95402d6870",
    "author": {
      "hash": "65a70a373b37b03dd6821a8dfbf6655d"
    },
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2027-01-01T00:00:00+02:00",
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
    "questionOf": "tender",
    "dateAnswered": "2027-01-01T00:00:00+02:00"
  }
}

