PATCH /api/2.5/tenders/69a0774b217e477cb01ddad3849397e2/questions/a3f5a89216114b8b832735eecda80b70?acc_token=2b976b1ceeb542098d70a6eec56c68a8 HTTP/1.0
Authorization: Bearer broker
Content-Length: 162
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "a3f5a89216114b8b832735eecda80b70",
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2023-01-01T00:00:00+02:00",
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
    "questionOf": "tender",
    "dateAnswered": "2023-01-01T00:00:00+02:00"
  }
}

