GET /api/2.5/tenders/cb76d20a62ef4e318ecb101430b63776/bids/1fcbb7ab0a104c228baa39c0c89927fe?acc_token=453f263b90e54cffbad8d3b4f4166931 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "status": "invalid",
    "id": "1fcbb7ab0a104c228baa39c0c89927fe"
  }
}

