GET /api/2.5/tenders/de38bea4a6534e13939a382dfeef92f2/bids/0a2a8fa3f5c84516bc1e79ed64e8b5e5/documents?acc_token=d838be06648343148752cdb7c643774f HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "documentType": "proposal",
      "id": "0273f95d8c8143dcafe478223372f9e7",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "hash": "md5:00000000000000000000000000000000",
      "title": "Proposal.p7s",
      "format": "sign/p7s",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/93575fadc8cb4b498979e82fdcea11d1?Signature=U19Np3Bl%2BlPnQMcJDcq8nryEfhJRyDKN6lh4l%2FNx6sXmTwehTe7dHYE3BZJy11vWj1mvYQjqOPLlqKKQGC6ODA%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "dateModified": "2023-10-10T01:00:00+03:00",
      "language": "uk",
      "confidentiality": "public"
    }
  ]
}

