GET /api/2.5/tenders/4a47e2c36bdc4f3bab60ecf7d8d0700e/awards?acc_token=f63fd82030a24dfc961d6995dc3f33d1 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "milestones": [
        {
          "id": "845189bc29e54ba0ae86e5bbc6941770",
          "code": "alp",
          "description": "найбільш економічно вигідна пропозиція є меншою на 40 або більше відсотків від середньоарифметичного значення ціни/приведеної ціни тендерних пропозицій інших учасників на початковому етапі аукціону / найбільш економічно вигідна пропозиція є меншою на 30 або більше відсотків від наступної ціни/приведеної ціни тендерної пропозиції за результатами проведеного електронного аукціону",
          "date": "2023-10-10T01:00:00+03:00",
          "dueDate": "2023-10-12T00:00:00+03:00"
        }
      ],
      "id": "dc87ba1686ce42babcf6b6452efbd5e6",
      "status": "pending",
      "date": "2023-10-10T01:00:00+03:00",
      "value": {
        "amount": 250.0,
        "currency": "UAH",
        "valueAddedTaxIncluded": true
      },
      "suppliers": [
        {
          "name": "ДКП «Школяр»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137256",
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
            "uri": "http://www.sc.gov.ua/"
          },
          "scale": "micro",
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          }
        }
      ],
      "bid_id": "f5ee9153aadb4ae59874c308815130ad",
      "lotID": "3fdae4595ce746318c81ada140ff94d7",
      "qualified": false,
      "eligible": false
    }
  ]
}

