POST /api/2.5/tenders/cb76d20a62ef4e318ecb101430b63776/bids/1fcbb7ab0a104c228baa39c0c89927fe/documents?acc_token=453f263b90e54cffbad8d3b4f4166931 HTTP/1.0
Authorization: Bearer broker
Content-Length: 352
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "lorem.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dc6cce7e75b44d2cb3d18880fbe458b7?Signature=FuesgBoZeOVKxYJDoHuPjYSlsXguRVkqopwJSVQ9YZC5TMR2D3AhvZNvsAQ2JmgF3mK9IHJ%2Bb%2BjuxEPgAdEtAQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword",
    "documentType": "evidence"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/cb76d20a62ef4e318ecb101430b63776/bids/1fcbb7ab0a104c228baa39c0c89927fe/documents/5690ed53d9684f37a2391548d97bc6fa

{
  "data": {
    "documentType": "evidence",
    "hash": "md5:00000000000000000000000000000000",
    "title": "lorem.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dc6cce7e75b44d2cb3d18880fbe458b7?Signature=UGG%2B0o%2BMiwWJ6yn2fSjv0zh%2B4yTGFr5A1qWbN9Vpeboqk9g5sML9Cmf4aEclnKxyPlVehF5TUkXrXLayjronCQ%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "confidentiality": "public",
    "id": "5690ed53d9684f37a2391548d97bc6fa",
    "datePublished": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:00+02:00"
  }
}

