PATCH /api/2.5/tenders/de38bea4a6534e13939a382dfeef92f2/lots/640d64ff33d440358cc4fd283ed9f58e?acc_token=f63fd82030a24dfc961d6995dc3f33d1 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "value": {
      "currency": "UAH",
      "amount": 400,
      "valueAddedTaxIncluded": true
    }
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "title": "Лот №2",
    "description": "Опис Лот №2",
    "status": "active",
    "id": "640d64ff33d440358cc4fd283ed9f58e",
    "date": "2023-10-10T01:00:00+03:00",
    "value": {
      "currency": "UAH",
      "valueAddedTaxIncluded": true,
      "amount": 400.0
    },
    "minimalStep": {
      "currency": "UAH",
      "valueAddedTaxIncluded": true,
      "amount": 5.0
    },
    "auctionPeriod": {
      "startDate": "2023-10-19T13:01:01.441000+03:00",
      "shouldStartAfter": "2023-10-19T00:00:00+03:00"
    }
  }
}

