PATCH /api/2.5/tenders/01138bc5e7e84ea188d95e681ade9584/lots/118c2e6a259d4958a8081d17effdce7a?acc_token=b9c88c159830478b817a78182b04aad0 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "value": {
      "currency": "UAH",
      "amount": 400,
      "valueAddedTaxIncluded": false
    }
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "title": "Лот №2",
    "description": "Опис Лот №2",
    "status": "active",
    "id": "118c2e6a259d4958a8081d17effdce7a",
    "date": "2027-01-01T00:00:00+02:00",
    "value": {
      "currency": "UAH",
      "valueAddedTaxIncluded": false,
      "amount": 400.0
    },
    "minimalStep": {
      "currency": "UAH",
      "valueAddedTaxIncluded": false,
      "amount": 5.0
    },
    "auctionPeriod": {
      "startDate": "2027-01-11T15:28:52.219000+02:00",
      "shouldStartAfter": "2027-01-09T00:00:00+02:00"
    }
  }
}

