GET /api/2.5/tenders/de38bea4a6534e13939a382dfeef92f2/documents HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "confidentiality": "public",
      "documentType": "notice",
      "id": "eca32be06b724356ab576e6e5462963f",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "hash": "md5:00000000000000000000000000000000",
      "title": "sign.p7s",
      "format": "application/pkcs7-signature",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5cc9e5107bdd435bae2a71979d095dd1?Signature=zw7oPBOVuWHvOqvOgV%2ByjEC03rcuNlT4XyrNuKqQhDtRJgtnYkGDWiKYk%2BTSOScx9UfXHQAJWpeeWcHvSbM2AA%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "dateModified": "2023-10-10T01:00:00+03:00",
      "author": "tender_owner",
      "language": "uk"
    },
    {
      "confidentiality": "public",
      "hash": "md5:00000000000000000000000000000000",
      "title": "Notice.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e0b88d0edb654856ae16c98e63b19165?Signature=GyowoM9XlSYpzheTBkyziAWm2lqnb6VlG0Gv%2B%2BWgpE31UcPSRhsFWcSltW%2FxP3vP75Hm%2FDlAZ6FDnPZ%2BRxhlBA%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "83f9cdd9d4d64566ad023f7e21351be0",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "dateModified": "2023-10-10T01:00:00+03:00",
      "author": "tender_owner"
    },
    {
      "confidentiality": "public",
      "id": "9f17674d1d4a4b7188a0f03d6894918b",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "hash": "md5:00000000000000000000000000000000",
      "title": "AwardCriteria.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e4153a6dcaf64e79b911002305341f6e?Signature=8JQQd35BZz9qGydenYE3Qy2%2F40eLQA5zi0P1NaaJlX6DAepqg4aNUJE9X8s6C%2FwIHkmV7bU6lXJnDSzzSIkFDw%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "dateModified": "2023-10-10T01:00:00+03:00",
      "author": "tender_owner",
      "language": "uk"
    }
  ]
}

