POST /api/2.5/tenders/4a47e2c36bdc4f3bab60ecf7d8d0700e/documents?acc_token=f63fd82030a24dfc961d6995dc3f33d1 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Notice.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e0b88d0edb654856ae16c98e63b19165?Signature=og2MD6TTutuNzjKcxAKNZHwp65YoTvaDnnHRd1%2F%2BrJXqx3x9ze0tsPp5idME%2BHE64Ned4wBJzk4qWd63nFejAw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4a47e2c36bdc4f3bab60ecf7d8d0700e/documents/4c80059e32bf4e99ae7821ccaabb5091

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e0b88d0edb654856ae16c98e63b19165?Signature=GyowoM9XlSYpzheTBkyziAWm2lqnb6VlG0Gv%2B%2BWgpE31UcPSRhsFWcSltW%2FxP3vP75Hm%2FDlAZ6FDnPZ%2BRxhlBA%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "4c80059e32bf4e99ae7821ccaabb5091",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "author": "tender_owner"
  }
}

