POST /api/2.0/tenders/61c3991c14554d5cb809ab22378ab5c5/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 805
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "lotValues": [
      {
        "relatedLot": "63f3908e11994b779d2553b8d7e5b38d", 
        "value": {
          "amount": 500
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/61c3991c14554d5cb809ab22378ab5c5/bids/8f266ae7f82842d7af547b6fe0ab95ed
{
  "access": {
    "token": "15637a9af73347f18b1a2f1c8d57f9fc"
  }, 
  "data": {
    "date": "2016-03-16T12:38:36.726793+02:00", 
    "status": "pending", 
    "id": "8f266ae7f82842d7af547b6fe0ab95ed", 
    "lotValues": [
      {
        "relatedLot": "63f3908e11994b779d2553b8d7e5b38d", 
        "date": "2016-03-16T12:38:36.727818+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

