POST /api/2.3/tenders/54b6d33b9ea94e4ea0478253960cbb88/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 975
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "3de7797e02584b628add6121f00b47da"
      }, 
      {
        "relatedLot": "1d72110b5f1e4197b15f9e59049b5713", 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко", 
          "email": "fake@mail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137227", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 35", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/54b6d33b9ea94e4ea0478253960cbb88/bids/be8cda0ab74840eeae2b1a2cd218208e
{
  "access": {
    "token": "e7fd2b1c992f4927894f68b6b8e595af"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "3de7797e02584b628add6121f00b47da", 
        "date": "2017-06-20T12:33:20.969337+03:00", 
        "status": "pending"
      }, 
      {
        "relatedLot": "1d72110b5f1e4197b15f9e59049b5713", 
        "date": "2017-06-20T12:33:20.969694+03:00", 
        "status": "pending", 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137227", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-06-20T12:33:20.968794+03:00", 
    "id": "be8cda0ab74840eeae2b1a2cd218208e"
  }
}

