POST /api/2.4/tenders/b204841c7ee844019a1038571b96b55a/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1188
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "0b447ad702e64138b2c550dfe583c7f2", 
        "value": {
          "contractDuration": {
            "years": 7
          }, 
          "yearlyPaymentsPercentage": 0.87, 
          "annualCostsReduction": [
            200, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000
          ]
        }, 
        "subcontractingDetails": "ДКП «Орфей», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/b204841c7ee844019a1038571b96b55a/bids/3434c61229b84da2a54e1d942aab149b
{
  "access": {
    "token": "7c1cdef8852b4963827ba7180881a626"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "0b447ad702e64138b2c550dfe583c7f2", 
        "date": "2017-10-03T11:18:05.725574+03:00", 
        "status": "pending", 
        "value": {
          "yearlyPaymentsPercentage": 0.87, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 6051.86301369863, 
          "contractDuration": {
            "days": 0, 
            "years": 7
          }, 
          "amountPerformance": 1483.9856174439371, 
          "annualCostsReduction": [
            200.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0
          ]
        }, 
        "subcontractingDetails": "ДКП «Орфей», Україна"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-10-03T11:18:05.725015+03:00", 
    "id": "3434c61229b84da2a54e1d942aab149b"
  }
}

