GET /api/0.12/tenders/ee511dd9b7d84c19804c17db46c38eba HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-02-15-000001", 
    "tenderPeriod": {
      "startDate": "2016-02-15T14:48:44.128507+02:00", 
      "endDate": "2016-03-17T14:48:42.089429+02:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2016-02-15T14:48:44.128507+02:00", 
      "endDate": "2016-03-14T14:48:42.089429+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-02-15T14:48:44.128507+02:00", 
      "endDate": "2016-03-13T14:48:42.089429+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "lots": [
      {
        "status": "active", 
        "description": "lot description", 
        "title": "lot title", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "05d453ce3511470490a32d64c8d2602a"
      }
    ], 
    "dateModified": "2016-02-15T14:48:44.553973+02:00", 
    "procurementMethodType": "aboveThresholdEU", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "Ukraine", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "items": [
      {
        "relatedLot": "05d453ce3511470490a32d64c8d2602a", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "cef3704721644301ba091a6e0132c808", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "owner": "broker", 
    "next_check": "2016-03-17T14:48:42.089429+02:00", 
    "id": "ee511dd9b7d84c19804c17db46c38eba", 
    "awardCriteria": "lowestCost"
  }
}

