POST /api/2.3/tenders/b2f65ddea9624e6dad58e88f99c61bb6/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 984
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "6868e864385a42c0a731970504b26a8f", 
        "value": {
          "amount": 300
        }, 
        "subcontractingDetails": "ДКП «Орфей», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "Firm can't create bid", 
      "location": "body", 
      "name": "data"
    }
  ]
}

