PATCH /api/2.3/tenders/b2f65ddea9624e6dad58e88f99c61bb6?acc_token=19b7a8b14e4c4edc90fbe0bc4c73d5ce HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.tendering"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "complaintPeriod": {
      "startDate": "2017-06-21T17:05:03.984241+03:00", 
      "endDate": "2017-07-17T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-06-21T17:05:03.984241+03:00", 
      "clarificationsUntil": "2017-07-14T17:05:03.984241+03:00", 
      "endDate": "2017-07-11T17:05:03.984241+03:00", 
      "invalidationDate": "2017-06-21T17:05:04.495221+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-07-21T17:05:03.984241+03:00", 
    "awardCriteria": "lowestCost", 
    "owner": "broker", 
    "id": "b2f65ddea9624e6dad58e88f99c61bb6", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2017-08-26T00:00:00+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2017-06-21T17:05:04.494845+03:00", 
        "id": "064dcd27e2cd4789a5b57519ad77c250"
      }, 
      {
        "status": "active", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2017-08-26T00:00:00+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2017-06-21T17:05:04.494845+03:00", 
        "id": "6868e864385a42c0a731970504b26a8f"
      }
    ], 
    "shortlistedFirms": [
      {
        "lots": [
          {
            "id": "064dcd27e2cd4789a5b57519ad77c250"
          }
        ], 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "lots": [
          {
            "id": "064dcd27e2cd4789a5b57519ad77c250"
          }, 
          {
            "id": "6868e864385a42c0a731970504b26a8f"
          }
        ], 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "lots": [
          {
            "id": "064dcd27e2cd4789a5b57519ad77c250"
          }, 
          {
            "id": "6868e864385a42c0a731970504b26a8f"
          }
        ], 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2017-06-21-000002", 
    "dateModified": "2017-06-21T17:05:04.501370+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-06-21T17:05:03.984241+03:00", 
      "endDate": "2017-07-21T17:05:03.984241+03:00"
    }, 
    "title_en": "Services in school canteens", 
    "procurementMethodType": "competitiveDialogueEU.stage2", 
    "date": "2017-06-21T17:05:04.494845+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "064dcd27e2cd4789a5b57519ad77c250", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-07-11T17:04:37.418546+03:00", 
          "endDate": "2017-08-10T17:04:37.418606+03:00"
        }, 
        "id": "86e73d6393ce4d299ec22102839d5a57", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "6868e864385a42c0a731970504b26a8f", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-07-11T17:04:37.418636+03:00", 
          "endDate": "2017-08-10T17:04:37.418662+03:00"
        }, 
        "id": "c42ed791c4ec450686660281c2a263ce", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

