PATCH /api/2.3/tenders/ada1dee88cae40b7b21762be8520847d?acc_token=0911f65908fd4ab98fda15394f286c42 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2016-03-26T15:45:15.379007+03:00", 
      "endDate": "2016-04-21T15:45:15.379007+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2016-03-26T15:45:15.379007+03:00", 
      "clarificationsUntil": "2016-04-20T15:45:15.379007+03:00", 
      "endDate": "2016-04-15T15:45:15.379007+03:00", 
      "invalidationDate": "2016-04-25T15:45:14.952886+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-04-30T15:45:16.435835+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "ada1dee88cae40b7b21762be8520847d", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2016-04-30T15:45:16.435835+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "40519915046449b6a687074d35391f0b"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "6722811322af42399250b7b8fc7df6cf"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2016-04-25T15:45:15.668562+03:00", 
      "endDate": "2016-04-30T15:45:16.435835+03:00"
    }, 
    "tenderID": "UA-2016-04-25-000001", 
    "dateModified": "2016-04-25T15:45:16.442544+03:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2016-03-26T15:45:15.379007+03:00", 
      "endDate": "2016-04-25T15:45:15.379007+03:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "40519915046449b6a687074d35391f0b", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "b1f84d981136408990ad7439929e7c61", 
        "id": "4905d0bc6ee34710837ddb8111d0add8"
      }, 
      {
        "status": "active", 
        "lotID": "40519915046449b6a687074d35391f0b", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "91dfe5a250724df58ab61d38a3972bb0", 
        "id": "cbd3d8948c414c72aa9475b873b5fa95"
      }
    ], 
    "procurementMethodType": "aboveThresholdEU", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "40519915046449b6a687074d35391f0b", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-05-15T15:44:43.825967+03:00", 
          "endDate": "2016-06-14T15:44:43.826018+03:00"
        }, 
        "id": "b69e20207b4947f1aad8c5744ae7ec04", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "6722811322af42399250b7b8fc7df6cf", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-05-15T15:44:43.826052+03:00", 
          "endDate": "2016-06-14T15:44:43.826077+03:00"
        }, 
        "id": "ac688d7ded4f4a45a13fb8d30d00d29f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "id": "b1f84d981136408990ad7439929e7c61"
      }, 
      {
        "status": "active", 
        "id": "91dfe5a250724df58ab61d38a3972bb0"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

