GET /api/2.0/tenders/8f60a91893414e029899c19aa0723bd6 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-03-16-000001", 
    "tenderPeriod": {
      "startDate": "2016-03-16T14:19:40.235622+02:00", 
      "endDate": "2016-04-16T14:19:09.453986+02:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "complaintPeriod": {
      "startDate": "2016-03-16T14:19:40.235622+02:00", 
      "endDate": "2016-04-12T14:19:09.453986+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 1000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "5337b933aa684d639ee7de80334d9357"
      }, 
      {
        "status": "active", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "b018dac2e9fb434581608ea3800eaf87"
      }
    ], 
    "next_check": "2016-04-16T15:19:09.453986+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "enquiryPeriod": {
      "startDate": "2016-03-16T14:19:40.235622+02:00", 
      "endDate": "2016-04-06T14:19:09.453986+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2016-03-16T14:19:41.076076+02:00", 
    "items": [
      {
        "relatedLot": "5337b933aa684d639ee7de80334d9357", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "166224f5732745bd9a67135cf4d793da", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "b018dac2e9fb434581608ea3800eaf87", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "51c858068d8c468391b99092f2ce6708", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "8f60a91893414e029899c19aa0723bd6", 
    "awardCriteria": "lowestCost"
  }
}

