PATCH /api/2.0/tenders/61c3991c14554d5cb809ab22378ab5c5?acc_token=02219504528646d08d8c409d6bc44e71 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2016-02-15T12:38:37.767665+02:00", 
      "endDate": "2016-03-12T12:38:37.767665+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2016-02-15T12:38:37.767665+02:00", 
      "endDate": "2016-03-06T12:38:37.767665+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-03-26T12:38:38.994970+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "61c3991c14554d5cb809ab22378ab5c5", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2016-03-26T12:38:38.994970+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "63f3908e11994b779d2553b8d7e5b38d"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "ac3482810d2b481ea137e23b37fe9b85"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2016-03-16T12:38:38.090133+02:00", 
      "endDate": "2016-03-26T12:38:38.994970+02:00"
    }, 
    "tenderID": "UA-2016-03-16-000001", 
    "dateModified": "2016-03-16T12:38:39.001424+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2016-02-15T12:38:37.767665+02:00", 
      "endDate": "2016-03-16T12:38:37.767665+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "63f3908e11994b779d2553b8d7e5b38d", 
        "id": "facf65f118704f789b8d21e100a9f292", 
        "bidID": "8f266ae7f82842d7af547b6fe0ab95ed"
      }, 
      {
        "status": "active", 
        "lotID": "63f3908e11994b779d2553b8d7e5b38d", 
        "id": "1d2c16f036854ab9b7a14c3551131188", 
        "bidID": "d115a3b98a0b41968fd4966c2b8da5bc"
      }
    ], 
    "procurementMethodType": "aboveThresholdEU", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "63f3908e11994b779d2553b8d7e5b38d", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "22de1117433d46b6991681b0dabbed91", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "ac3482810d2b481ea137e23b37fe9b85", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "2fc45c5e2d834ad7865bfefa22ea5b88", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "pending", 
        "id": "8f266ae7f82842d7af547b6fe0ab95ed"
      }, 
      {
        "status": "pending", 
        "id": "d115a3b98a0b41968fd4966c2b8da5bc"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

