PATCH /api/0.12/tenders/57543fb90bb842329d1f37f675f74d8b?acc_token=e714aca1ad624710a1207deab27017ef HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 125
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "items": [
      {
        "relatedLot": "143af432be1d4b87a4f277de0858ba94"
      }, 
      {
        "relatedLot": "b277abcf757947e396f278edadfd97dc"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-02-15-000001", 
    "tenderPeriod": {
      "startDate": "2016-02-15T22:53:03.838062+02:00", 
      "endDate": "2016-03-17T22:53:02.055281+02:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2016-02-15T22:53:03.838062+02:00", 
      "endDate": "2016-03-14T22:53:02.055281+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-02-15T22:53:03.838062+02:00", 
      "endDate": "2016-03-13T22:53:02.055281+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 1000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "143af432be1d4b87a4f277de0858ba94"
      }, 
      {
        "status": "active", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "b277abcf757947e396f278edadfd97dc"
      }
    ], 
    "dateModified": "2016-02-15T22:53:04.409604+02:00", 
    "procurementMethodType": "aboveThresholdEU", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "Ukraine", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "items": [
      {
        "relatedLot": "143af432be1d4b87a4f277de0858ba94", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "4205b7ea48fa40edbcadc5bfbee30beb", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "b277abcf757947e396f278edadfd97dc", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "6c1699a54bd74d639bf673a3fcb37d23", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "owner": "broker", 
    "next_check": "2016-03-17T22:53:02.055281+02:00", 
    "id": "57543fb90bb842329d1f37f675f74d8b", 
    "awardCriteria": "lowestCost"
  }
}

