POST /api/2.3/tenders/ada1dee88cae40b7b21762be8520847d/lots?acc_token=0911f65908fd4ab98fda15394f286c42 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 214
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "description": "Опис Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "title": "Лот №1"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/ada1dee88cae40b7b21762be8520847d/lots/40519915046449b6a687074d35391f0b
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-06-30T15:44:43.826103+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "40519915046449b6a687074d35391f0b"
  }
}

