PATCH /api/2.0/tenders/f4c756850aae4aabaa0060d73a7aeae8/lots/f740532b6a814df898eb536781f71ee6?acc_token=d1229925ea354786a714a0617449cb84 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №2", 
    "title": "Лот №2", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 400.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "f740532b6a814df898eb536781f71ee6"
  }
}

