PATCH /api/2.3/tenders/c69bc7d44dbe456e866cdb1e862446c1?acc_token=05afe5e167e8445dbcd2a85b63f4e003 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 125
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "items": [
      {
        "relatedLot": "1f528c20ff7e43d4985064f5825ba98e"
      }, 
      {
        "relatedLot": "412c8c769eea447f8758959ee76830bf"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-10-12-000001", 
    "tenderPeriod": {
      "startDate": "2016-10-12T02:41:14.572372+03:00", 
      "endDate": "2016-11-12T02:40:39.055032+03:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2016-10-12T02:41:14.572372+03:00", 
      "clarificationsUntil": "2016-11-07T02:40:39.055032+03:00", 
      "endDate": "2016-11-02T02:40:39.055032+03:00", 
      "invalidationDate": "2016-10-12T02:41:14.939301+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-10-12T02:41:14.572372+03:00", 
      "endDate": "2016-11-08T00:00:00+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 1000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2016-10-12T02:41:14.663127+03:00", 
    "dateModified": "2016-10-12T02:41:14.941798+03:00", 
    "procurementMethodType": "competitiveDialogueEU", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "items": [
      {
        "relatedLot": "1f528c20ff7e43d4985064f5825ba98e", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-11-01T02:40:39.054697+03:00", 
          "endDate": "2016-12-01T02:40:39.054769+03:00"
        }, 
        "id": "d4942635ec9141feb5a1d50b278baf04", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "412c8c769eea447f8758959ee76830bf", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-11-01T02:40:39.054801+03:00", 
          "endDate": "2016-12-01T02:40:39.054814+03:00"
        }, 
        "id": "20839bd6873a40a48454eb7a5472a3fa", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "owner": "broker", 
    "next_check": "2016-11-12T01:40:39.055032+02:00", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2016-10-12T02:41:14.748406+03:00", 
        "id": "1f528c20ff7e43d4985064f5825ba98e"
      }, 
      {
        "status": "active", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2016-10-12T02:41:14.824322+03:00", 
        "id": "412c8c769eea447f8758959ee76830bf"
      }
    ], 
    "id": "c69bc7d44dbe456e866cdb1e862446c1", 
    "awardCriteria": "lowestCost"
  }
}

