PATCH /api/2.5/tenders/e94eaa64aef8454cbe03535ec53ac9e1/bids/ba2e64eb26a84c1cbc1e6f14c2c2c2c0?acc_token=356f4b9cb93f4453946b57cfa5f49f03 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "3217dbec51ef4c02b49d439542e37b83"
        },
        "value": 90
      },
      {
        "requirement": {
          "id": "b38a0d45871c41c5993071b7b895bdd4"
        },
        "values": [
          "ukr"
        ]
      },
      {
        "requirement": {
          "id": "895250bca80a4706911da6e60c045e7f"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "b629c2e279fa4f73b8825818b29d2742"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "2cc16f6e1d1a4ec69708167f376bc11c"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "d7941c65af964baba1bca5fa089c883b"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "1d1bb5d836b94c29bbd8caac2a72280c"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "c7bbfc5c70ae46eaa3b48d5944cc75aa"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "a03e99bb49eb458481f9be9af01f2377"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "7a825d3266334c6197e6a0235be43dcf"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "a212f66068eb472c8a77bde2e7fcf488"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "2f482f1c2379451b830c79abdccda991"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "a6673e9acc8e4bf7b2492ce7bc9492d0"
        },
        "value": true
      },
      {
        "requirement": {
          "id": "70a3c84e189a472ebf26b4634d1e4145"
        },
        "value": true
      }
    ]
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "3217dbec51ef4c02b49d439542e37b83",
          "title": "Строк дії тендерної пропозиції із дати кінцевого строку подання тендерних пропозицій"
        },
        "value": 90,
        "id": "4e58f75aad3f450ba42ff3e4bb66ad6e",
        "unit": {
          "code": "DAY",
          "name": "день"
        },
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.OTHER.BID.VALIDITY_PERIOD"
        }
      },
      {
        "requirement": {
          "id": "b38a0d45871c41c5993071b7b895bdd4",
          "title": "Мова тендерної пропозиції"
        },
        "values": [
          "ukr"
        ],
        "id": "faea5518f7c64e648acdf0987e77d82e",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.OTHER.BID.LANGUAGE"
        },
        "dataSchema": "ISO 639-3"
      },
      {
        "requirement": {
          "id": "895250bca80a4706911da6e60c045e7f",
          "title": "Відомості про учасника процедури закупівлі не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": true,
        "id": "45e7a4527f934dd992af568c8248048f",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "b629c2e279fa4f73b8825818b29d2742",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": true,
        "id": "6027233d9e2045c283b41d0a7be926ed",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "2cc16f6e1d1a4ec69708167f376bc11c",
          "title": "Учасник процедури закупівлі протягом останніх трьох років не притягувався до відповідальності за порушення у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів торгів, аукціонів, конкурсів, тендерів"
        },
        "value": true,
        "id": "1f3950c327884fc7954f2b2a3dd956db",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
        }
      },
      {
        "requirement": {
          "id": "d7941c65af964baba1bca5fa089c883b",
          "title": "Учасник процедури закупівлі не був засуджений за кримінальне правопорушення, вчинене з корисливих мотивів (зокрема, пов’язане з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": true,
        "id": "71e7162d55b64b9dab2b6e71df2f25fc",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"
        }
      },
      {
        "requirement": {
          "id": "1d1bb5d836b94c29bbd8caac2a72280c",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": true,
        "id": "0b0ce1bcaa9a4bc69aea39fee1a744d5",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY"
        }
      },
      {
        "requirement": {
          "id": "c7bbfc5c70ae46eaa3b48d5944cc75aa",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": true,
        "id": "ed2a38001a48425197cbc5eec90dfa00",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.TERRORIST_OFFENCES"
        }
      },
      {
        "requirement": {
          "id": "a03e99bb49eb458481f9be9af01f2377",
          "title": "Учасника процедури закупівлі не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": true,
        "id": "a31e8dc34f5d401ea08e3072d3c36559",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING"
        }
      },
      {
        "requirement": {
          "id": "7a825d3266334c6197e6a0235be43dcf",
          "title": "Учасник процедури закупівлі не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": true,
        "id": "98e8cc62882c42d8b2b54a9057853fe8",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_TAXES"
        }
      },
      {
        "requirement": {
          "id": "a212f66068eb472c8a77bde2e7fcf488",
          "title": "Учасник процедури закупівлі не мав з цим самим замовником договору про закупівлю, який було достроково розірвано через невиконання учасником своїх зобов’язань із застосуванням санкцій у вигляді штрафів та/або відшкодування збитків протягом трьох років з дати дострокового розірвання такого договору"
        },
        "value": true,
        "id": "c7cb3894b7154e1582c1e867a4c8ac6a",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.EARLY_TERMINATION"
        }
      },
      {
        "requirement": {
          "id": "2f482f1c2379451b830c79abdccda991",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\""
        },
        "value": true,
        "id": "eb39611a2e3e4a1b91792704743cc791",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.EXCLUSION.NATIONAL.OTHER"
        }
      },
      {
        "requirement": {
          "id": "a6673e9acc8e4bf7b2492ce7bc9492d0",
          "title": "Учасник закупівлі, разом із залученими спроможностями субпідрядника/співвиконавця (за наявності), відповідає кваліфікаційним критеріям відповідно до частини третьої статті 16 Закону України від 25.12.2015 № 922-VIII \"Про публічні закупівлі\""
        },
        "value": true,
        "id": "6d4a95fc697e4e6bbf74f1a60d32f4e3",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.SUBCONTRACTING_PROPORTION"
        }
      },
      {
        "requirement": {
          "id": "70a3c84e189a472ebf26b4634d1e4145",
          "title": "Текст заповнений користувачем"
        },
        "value": true,
        "id": "60017f8881fb4295a1f90ca1f0b084d8",
        "classification": {
          "scheme": "LAW922",
          "id": "CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.EQUIPMENT"
        }
      }
    ],
    "items": [
      {
        "id": "8fba10d170794a12a8ccd313990265ea",
        "description": "Послуги шкільних їдалень",
        "description_en": "Services in school canteens",
        "unit": {
          "name": "кілограм",
          "code": "KGM"
        },
        "quantity": 1.0,
        "relatedLot": "aa7e372b99b24b5395149839bde29a63"
      },
      {
        "id": "0cdb5f2ec3e24db4aeadbae3f863056e",
        "description": "Послуги шкільних їдалень",
        "description_en": "Services in school canteens",
        "unit": {
          "name": "упаковка",
          "code": "PK"
        },
        "quantity": 1.0,
        "relatedLot": "aa7e372b99b24b5395149839bde29a63"
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        }
      }
    ],
    "status": "draft",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "id": "ba2e64eb26a84c1cbc1e6f14c2c2c2c0",
    "date": "2027-01-01T00:00:00+02:00",
    "lotValues": [
      {
        "relatedLot": "aa7e372b99b24b5395149839bde29a63",
        "status": "pending",
        "date": "2027-01-01T00:00:00+02:00"
      }
    ]
  }
}

