PATCH /api/2.5/tenders/77e829220cef46c89b232c408c771bff/qualifications/f1c14917633d4811bc506954af4a91fc?acc_token=209807bd7ed9439eaa4a4da4e94c818f HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active",
    "qualified": true,
    "eligible": true
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "f1c14917633d4811bc506954af4a91fc",
    "bidID": "a5186dbf9d814acca7ba6f9fd36493f5",
    "lotID": "1ce862da3d7f4b8ca7160edab3452691",
    "status": "active",
    "date": "2027-01-01T00:03:00+02:00",
    "qualified": true,
    "eligible": true
  }
}

