GET /api/2.5/tenders/77e829220cef46c89b232c408c771bff/bids/6df778e10f1c41b2a438c5e8908fc02e?acc_token=82973044ee7d4a728e0adce0f0ff3a01 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "8ebc930af2ef4fef91d1c9762354253d",
          "title": "Строк дії тендерної пропозиції із дати кінцевого строку подання тендерних пропозицій"
        },
        "value": 90,
        "id": "e0a072fdfcf241b2ac5a5c159d2e5b43",
        "unit": {
          "code": "DAY",
          "name": "день"
        },
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.BID.VALIDITY_PERIOD"
        }
      },
      {
        "requirement": {
          "id": "a61973a8e3804e6997d4621eb35b7037",
          "title": "Мова тендерної пропозиції"
        },
        "values": [
          "ukr"
        ],
        "id": "626c5347515646b19b8a30e4ec0c4bf9",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.OTHER.BID.LANGUAGE"
        }
      },
      {
        "requirement": {
          "id": "668b3a851bcb4726bd8868cbcaab0b4f",
          "title": "Учасник закупівлі, разом із залученими спроможностями субпідрядника/співвиконавця (за наявності), відповідає кваліфікаційним критеріям відповідно до частини третьої статті 16 Закону України від 25.12.2015 № 922-VIII \"Про публічні закупівлі\""
        },
        "value": true,
        "id": "6bb6400064cd4e38be1c4f894310856d",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.SUBCONTRACTING_PROPORTION"
        }
      },
      {
        "requirement": {
          "id": "357eaea052ea459990a5f8166e88dc2c",
          "title": "Відомості про учасника процедури закупівлі не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": true,
        "id": "8d0031549d5c4df3823309ffb14c5cbd",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "67d9482f966343db9cfd56d55cf50f71",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": true,
        "id": "144969719069410bbeb1a55a89a1ec77",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION"
        }
      },
      {
        "requirement": {
          "id": "734a5b6c0253403190d230a1a85ceda5",
          "title": "Учасник процедури закупівлі протягом останніх трьох років не притягувався до відповідальності за порушення у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів торгів, аукціонів, конкурсів, тендерів"
        },
        "value": true,
        "id": "4add445999db4bae82a0c88388510d97",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.FRAUD"
        }
      },
      {
        "requirement": {
          "id": "ba888e628fc14431a737c32ee11812e0",
          "title": "Учасник процедури закупівлі не був засуджений за кримінальне правопорушення, вчинене з корисливих мотивів (зокрема, пов’язане з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": true,
        "id": "2517b62d4f9b46bea251bffb619095dd",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"
        }
      },
      {
        "requirement": {
          "id": "06e16f9447f0401c9137cc8da59f2778",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": true,
        "id": "c1629e2f4b7d4922a1fa975e20372148",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY"
        }
      },
      {
        "requirement": {
          "id": "7d0f1c91b14444c2bd01c56c0545058f",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": true,
        "id": "4ec487fe768d422984f2e0f597eac42b",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.TERRORIST_OFFENCES"
        }
      },
      {
        "requirement": {
          "id": "ee71636da1db4a7086402d0baa432c1e",
          "title": "Учасника процедури закупівлі не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": true,
        "id": "20fda7b0d181402ea6e897ad90283427",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING"
        }
      },
      {
        "requirement": {
          "id": "755b65129fac41a49670e4daaa87b372",
          "title": "Учасник процедури закупівлі не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": true,
        "id": "12e77e210b904dd7984a89a64b8bd6ab",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_TAXES"
        }
      },
      {
        "requirement": {
          "id": "1e05038cb36b468d92f2cdf1cd020b82",
          "title": "Учасник процедури закупівлі не мав з цим самим замовником договорів достроково розірваних через невиконання (учасником) своїх зобов'язань через що було застосовано санкції у вигляді штрафів та/або відшкодування збитків"
        },
        "value": true,
        "id": "f808b400bb3e46498dccc4cb0a1a3f12",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.EARLY_TERMINATION"
        }
      },
      {
        "requirement": {
          "id": "5068057156904746925bf70352173ccc",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\""
        },
        "value": true,
        "id": "689f13dfaec94cc5a791526dc951f1c7",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.EXCLUSION.NATIONAL.OTHER"
        }
      },
      {
        "requirement": {
          "id": "e24375e34aae4c7ea534637b2c655498",
          "title": "Текст заповнений користувачем"
        },
        "value": true,
        "id": "ac7e36eb9c48488eb177a67c37848ca6",
        "classification": {
          "scheme": "ESPD211",
          "id": "CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.EQUIPMENT"
        }
      }
    ],
    "id": "6df778e10f1c41b2a438c5e8908fc02e",
    "date": "2027-01-01T00:01:00+02:00",
    "submissionDate": "2027-01-01T00:01:00+02:00",
    "items": [
      {
        "id": "df38969eb8ad4d558dda2cd874f14ac4",
        "description": "Послуги шкільних їдалень",
        "description_en": "Services in school canteens",
        "unit": {
          "name": "кілограм",
          "code": "KGM"
        },
        "quantity": 1.0,
        "relatedLot": "1ce862da3d7f4b8ca7160edab3452691"
      },
      {
        "id": "ef4a0a84ed77496e89a381ecfcdbf49d",
        "description": "Послуги шкільних їдалень",
        "description_en": "Services in school canteens",
        "unit": {
          "name": "упаковка",
          "code": "PK"
        },
        "quantity": 1.0,
        "relatedLot": "1ce862da3d7f4b8ca7160edab3452691"
      }
    ],
    "tenderers": [
      {
        "name": "Школяр",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        }
      }
    ],
    "lotValues": [
      {
        "relatedLot": "1ce862da3d7f4b8ca7160edab3452691",
        "status": "pending",
        "date": "2027-01-01T00:01:00+02:00"
      }
    ],
    "documents": [
      {
        "confidentiality": "public",
        "documentType": "proposal",
        "id": "03c42c3cf0b04c00adefbdda06535e0a",
        "datePublished": "2027-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal.p7s",
        "format": "sign/p7s",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d55cf7685594417eafcd6a81cf099e54?Signature=1lmwO8FdzkpNV7sfZM8iDPezssL9XWgJxVOAAHMp8fZ%2B%2BOWB2ZCmCQVfIZVSXG1uoVIBfqD8kb9feIK%2Bk6xXCg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2027-01-01T00:00:00+02:00",
        "language": "uk",
        "isDescriptionDecision": false
      },
      {
        "confidentiality": "public",
        "documentType": "proposal",
        "id": "03c42c3cf0b04c00adefbdda06535e0a",
        "datePublished": "2027-01-01T00:01:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "sign.p7s",
        "format": "sign/p7s",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8bc99af3284943cda1dcf1d362c36767?Signature=cdisunJhbJoADi9HRJLyrFEjfgKtlaXa6zLM3FyLWQkj3hskZssC%2BaYkpYcQ05FUee54Xy7JveLugXQME0rpAA%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2027-01-01T00:01:00+02:00",
        "language": "uk",
        "isDescriptionDecision": false
      },
      {
        "confidentiality": "buyerOnly",
        "id": "0d145399f916419c821a3ae83b8cd8c2",
        "datePublished": "2027-01-01T00:01:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "DescriptiveProposal.pdf",
        "format": "application/pdf",
        "url": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/tenders/77e829220cef46c89b232c408c771bff/bids/6df778e10f1c41b2a438c5e8908fc02e/documents/0d145399f916419c821a3ae83b8cd8c2?download=8b781eec9f744181a275c6919de639dc",
        "documentOf": "tender",
        "dateModified": "2027-01-01T00:01:00+02:00",
        "language": "uk",
        "isDescriptionDecision": true
      },
      {
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair.",
        "id": "fef11a18a16a473bac225d24c7bc79db",
        "datePublished": "2027-01-01T00:01:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_top_secrets.pdf",
        "format": "application/pdf",
        "url": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/tenders/77e829220cef46c89b232c408c771bff/bids/6df778e10f1c41b2a438c5e8908fc02e/documents/fef11a18a16a473bac225d24c7bc79db?download=21c9ff3dd5e646208c8dd44b5853a9c0",
        "documentOf": "tender",
        "dateModified": "2027-01-01T00:01:00+02:00",
        "language": "uk",
        "isDescriptionDecision": false
      }
    ],
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "selfQualified": true,
    "status": "invalid"
  }
}

