GET /api/2.5/tenders/bc2c91a2523c470086cae2222065fc32/questions/e591ef51b99043f597ce1b1d419c645e HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "e591ef51b99043f597ce1b1d419c645e",
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2023-01-01T00:00:00+02:00",
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
    "questionOf": "tender",
    "dateAnswered": "2023-01-01T00:00:00+02:00"
  }
}

