PATCH /api/2.5/tenders/bdf767732b5740cc980564940363d11b/bids/18ddc2a79e264e6babef6eb4927ca37c/documents/5daedc87148646f59fc977c8d4c975c5?acc_token=7f38e07aa55f489bb23176a2195c3326 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "isDescriptionDecision": true
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "5daedc87148646f59fc977c8d4c975c5",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "hash": "md5:00000000000000000000000000000000",
    "title": "DescriptiveProposal.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8b781eec9f744181a275c6919de639dc?Signature=IILh4Y63cTxfiu1HvljkhIZl8XtvbMh1vZQWC27xuUK3IU3HuRTUA4dpBHaRniidh38b%2F0z2Q49ReRqizXqRAw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "language": "uk",
    "confidentiality": "public",
    "isDescriptionDecision": true
  }
}

