PATCH /api/2.5/tenders/35f93e8dd5484abb8b90687952c82010?acc_token=67e88a4fa34541c2bbdd1b66c8b11b71 HTTP/1.0
Authorization: Bearer broker
Content-Length: 60
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "mainProcurementCategory": "services", 
    "complaintPeriod": {
      "startDate": "2020-04-14T01:00:00+03:00", 
      "endDate": "2020-05-11T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2020-04-14T01:00:00+03:00", 
      "clarificationsUntil": "2020-05-08T00:00:00+03:00", 
      "endDate": "2020-05-05T00:00:00+03:00", 
      "invalidationDate": "2020-05-15T01:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2020-05-21T00:00:00+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "Вінницька область", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2020-05-15T01:00:00+03:00", 
        "title": "Калорійність", 
        "date": "2020-05-15T01:00:00+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "0541cf2833f347a7a46d919f60289a54", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "35f93e8dd5484abb8b90687952c82010", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4595254e01ba4f178bc3f567f549c368?KeyID=a8968c46&Signature=vATRHadWn0nVBxb0CiMIpgP0xxQIku%252BdiyZ8ihkWO95OatUx1wZ4jP%2FgFmiPl39XpZ20nMbkVtTZ8dyP4BuRCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-05-15T01:00:00+03:00", 
        "id": "588c354ef78f4155a37d4c22dbec1a9d", 
        "dateModified": "2020-05-15T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0d2761804fdb420aa12c0adad1c06c65?KeyID=a8968c46&Signature=sbObhmcEbppKi4eZAllrjNUbkOwWSsKRZU1RLSqTy3LqH9lGOKQ4Vp49qAbw2XU2egbmexaEAcruNXTzaqOiDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-05-15T01:00:00+03:00", 
        "id": "de1a505be7ed4337b657a9a1332b38cb", 
        "dateModified": "2020-05-15T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d3921bb3169f47d4aa0048f2094e1b1a?KeyID=a8968c46&Signature=XMvb4vRCXAclorqdyoEzjjfKzF5Wxu%2FQctqL67LHsm8M%252BpvhBr08ep33esbJbN7CQ%252BBuIaMLfrb9CWEyY0uWDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-05-15T01:00:00+03:00", 
        "id": "de1a505be7ed4337b657a9a1332b38cb", 
        "dateModified": "2020-05-15T01:00:00+03:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2020-05-15T01:00:00+03:00", 
      "endDate": "2020-05-21T00:00:00+03:00"
    }, 
    "tenderID": "UA-2020-05-15-000001", 
    "dateModified": "2020-05-15T01:00:00+03:00", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2020-04-14T01:00:00+03:00", 
      "endDate": "2020-05-15T01:00:00+03:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "799d983fc3ca4f18a3d22ead02ec7826", 
        "date": "2020-05-15T01:00:00+03:00", 
        "id": "688adb9bb70e4d4fbcaf4ba1025e7e1a"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "5c14615bc32a4efea822c166a6fa4023", 
        "date": "2020-05-15T01:00:00+03:00", 
        "id": "be53976fae27403594b3de9b7bdfba6a"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "d3aa2f675e1e4ba28b29163a5e247111", 
        "date": "2020-05-15T01:00:00+03:00", 
        "id": "5ffc4b1c851848199fd66861aa118688"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "80b8867552f446eebf0fbc93b10fbdf5", 
        "date": "2020-05-15T01:00:00+03:00", 
        "id": "21a68f5b2e664a23827a19a669007d33"
      }
    ], 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2020-05-15T01:00:00+03:00", 
    "milestones": [
      {
        "code": "prepayment", 
        "sequenceNumber": 0, 
        "title": "signingTheContract", 
        "duration": {
          "type": "banking", 
          "days": 2
        }, 
        "percentage": 45.55, 
        "type": "financing", 
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      }, 
      {
        "code": "postpayment", 
        "sequenceNumber": 0, 
        "title": "deliveryOfGoods", 
        "duration": {
          "type": "calendar", 
          "days": 900
        }, 
        "percentage": 54.45, 
        "type": "financing", 
        "id": "69a5415ca5f7457ebe20137639f410e0"
      }
    ], 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2020-06-04T00:00:00+02:00", 
          "endDate": "2020-07-04T00:00:00+02:00"
        }, 
        "id": "8bc8ded5746c4badb496d3297fce132c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2020-06-04T00:00:00+02:00", 
          "endDate": "2020-07-04T00:00:00+02:00"
        }, 
        "id": "cbb964e3acb24801b28a9a27ea7efb14", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/752bdc92fce4442596aec7342e050667?KeyID=a8968c46&Signature=D0iV1UCO0gdVQ8XMHwJldRFTsIzTXQ1CjU3x4oKy9fyCVWARZs%252BH1%2FjX7%252BubiW6841KkqEXSVJNz3rlcj2IIAA%253D%253D", 
            "format": "application/pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2020-05-15T01:00:00+03:00", 
            "id": "bdf03760f26641e6b662ddd1eb2e1e1f", 
            "dateModified": "2020-05-15T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "DescriptiveProposal.pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/35f93e8dd5484abb8b90687952c82010/bids/799d983fc3ca4f18a3d22ead02ec7826/documents/b3ba98a293ec412b966a9cb2c035020a?download=ec4c001ffaee4fb494eaa38e6bfe7bd7", 
            "format": "application/pdf", 
            "isDescriptionDecision": true, 
            "documentOf": "tender", 
            "datePublished": "2020-05-15T01:00:00+03:00", 
            "id": "b3ba98a293ec412b966a9cb2c035020a", 
            "dateModified": "2020-05-15T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/35f93e8dd5484abb8b90687952c82010/bids/799d983fc3ca4f18a3d22ead02ec7826/documents/c1b944c8854543e58b0d043843de553c?download=f47657026ea64bf6b5a840519258f836", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2020-05-15T01:00:00+03:00", 
            "id": "c1b944c8854543e58b0d043843de553c", 
            "dateModified": "2020-05-15T01:00:00+03:00"
          }
        ], 
        "id": "799d983fc3ca4f18a3d22ead02ec7826", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "scale": "micro", 
            "name": "ДКП «Школяр»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "Вінницька область", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "5c14615bc32a4efea822c166a6fa4023", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "scale": "sme", 
            "name": "ДКП «Книга»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "Львівська область", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "id": "d3aa2f675e1e4ba28b29163a5e247111", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "scale": "mid", 
            "name": "«Снігур»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "Львівська область", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/19d7c62da8e144799eb146bcd5501b48?KeyID=a8968c46&Signature=FIMSeD6yEWVtDOwH59G9AdzY6%252BG6sMCieLgltXtOaDdFJ%2F%252Bq00eiD0RVWW%2FnXEPn%252BC84bpaMYkE%252BcMWdmtb1DQ%253D%253D", 
            "format": "application/pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2020-05-15T01:00:00+03:00", 
            "id": "4ad15f4646fc4d29a4b63cb9bd25ac01", 
            "dateModified": "2020-05-15T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/35f93e8dd5484abb8b90687952c82010/bids/80b8867552f446eebf0fbc93b10fbdf5/documents/b8516bf8ea92481a8be558849bb81b11?download=9256c48555a442f9991381bf30f8f2c2", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2020-05-15T01:00:00+03:00", 
            "id": "b8516bf8ea92481a8be558849bb81b11", 
            "dateModified": "2020-05-15T01:00:00+03:00"
          }
        ], 
        "id": "80b8867552f446eebf0fbc93b10fbdf5", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Карпенко"
            }, 
            "scale": "large", 
            "name": "«Кенгуру»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137228", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Коцюбинського, 15", 
              "region": "Запорізька область", 
              "locality": "м. Запоріжя"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

