GET /api/2.5/tenders/cce509cd3c324437829f34f6d4d074fb/bids?acc_token=b02a0a0cbe7842149f3fab16c42f0d94 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "tenderers": [
        {
          "name": "ДКП «Школяр»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137256",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380 (432) 21-69-30"
          },
          "scale": "micro"
        }
      ],
      "id": "f2b56144728a41cb898f709142a1cc38",
      "status": "active",
      "documents": [
        {
          "id": "152b6f75a906449c8301d586f336df98",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/650a2e2f970f47d3bb08d89316c71c50?Signature=feUn1vIGH58gkWYNyofuGRXRgBftI97LhfGAmjSYtLX87TIFpYuuAHGFBbaZM2DHCBUlsuUAE%2FFB1EqWw0ssAg%3D%3D&KeyID=a8968c46",
          "datePublished": "2021-03-16T00:00:00+02:00",
          "dateModified": "2021-03-16T00:00:00+02:00",
          "documentOf": "tender",
          "confidentiality": "public",
          "language": "uk",
          "isDescriptionDecision": false
        },
        {
          "id": "5f13a95c29334712a623e60b61762df8",
          "hash": "md5:00000000000000000000000000000000",
          "title": "DescriptiveProposal.pdf",
          "format": "application/pdf",
          "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/cce509cd3c324437829f34f6d4d074fb/bids/f2b56144728a41cb898f709142a1cc38/documents/5f13a95c29334712a623e60b61762df8?download=a360449b0c4a4d61966532403de8287f",
          "datePublished": "2021-03-16T00:00:00+02:00",
          "dateModified": "2021-03-16T00:00:00+02:00",
          "documentOf": "tender",
          "confidentiality": "buyerOnly",
          "language": "uk",
          "isDescriptionDecision": true
        },
        {
          "id": "e6af73717567432c9d5ce0513caff6df",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal_top_secrets.pdf",
          "format": "application/pdf",
          "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/cce509cd3c324437829f34f6d4d074fb/bids/f2b56144728a41cb898f709142a1cc38/documents/e6af73717567432c9d5ce0513caff6df?download=901e3b57b4074d16ab450a026b2a8cea",
          "datePublished": "2021-03-16T00:00:00+02:00",
          "dateModified": "2021-03-16T00:00:00+02:00",
          "documentOf": "tender",
          "confidentialityRationale": "Only our company sells badgers with pink hair.",
          "confidentiality": "buyerOnly",
          "language": "uk",
          "isDescriptionDecision": false
        }
      ]
    },
    {
      "tenderers": [
        {
          "name": "ДКП «Книга»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137226",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 34",
            "locality": "м. Львів",
            "region": "Львівська область",
            "postalCode": "79013",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Андрій Олексюк",
            "email": "aagt@gmail.com",
            "telephone": "+380 (322) 91-69-30"
          },
          "scale": "sme"
        }
      ],
      "id": "a3773f747f5148d58d27cfae4a38b754",
      "status": "active"
    },
    {
      "tenderers": [
        {
          "name": "«Снігур»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137227",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 35",
            "locality": "м. Львів",
            "region": "Львівська область",
            "postalCode": "79013",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Іван Іваненко",
            "email": "fake@mail.com",
            "telephone": "+380 (322) 12-34-56"
          },
          "scale": "mid"
        }
      ],
      "id": "d075f39915d34bb98a8f4abb50f7e3ff",
      "selfQualified": true,
      "status": "unsuccessful"
    },
    {
      "tenderers": [
        {
          "name": "«Кенгуру»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137228",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Коцюбинського, 15",
            "locality": "м. Запоріжя",
            "region": "Запорізька область",
            "postalCode": "79013",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Іван Карпенко",
            "email": "fake@mail.com",
            "telephone": "+380 (322) 12-34-56"
          },
          "scale": "large"
        }
      ],
      "id": "ebac806fe83a4f0492193afac91b47bd",
      "status": "active",
      "documents": [
        {
          "id": "e0e4cbc86f6e4fe8adc624ee62d3b656",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal_part1.pdf",
          "format": "application/pdf",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/18236fa45edb456ca74c8320b4b0d2b8?Signature=2tXvP8ECxXUCuKzXtQhvKzz2gUUTv86aaWK209GAAvOjZ1wEQIGilN5iGCXZaKNvybgsfm2Vb4kphWWkaqFFCA%3D%3D&KeyID=a8968c46",
          "datePublished": "2021-03-16T00:00:00+02:00",
          "dateModified": "2021-03-16T00:00:00+02:00",
          "documentOf": "tender",
          "confidentiality": "public",
          "language": "uk",
          "isDescriptionDecision": false
        },
        {
          "id": "d098a5351cf3493192450f03a0750209",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Proposal_part2.pdf",
          "format": "application/pdf",
          "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/cce509cd3c324437829f34f6d4d074fb/bids/ebac806fe83a4f0492193afac91b47bd/documents/d098a5351cf3493192450f03a0750209?download=aec550f71c1e47f4bb789564fdfa149c",
          "datePublished": "2021-03-16T00:00:00+02:00",
          "dateModified": "2021-03-16T00:00:00+02:00",
          "documentOf": "tender",
          "confidentialityRationale": "Only our company sells badgers with pink hair.",
          "confidentiality": "buyerOnly",
          "language": "uk",
          "isDescriptionDecision": false
        }
      ]
    }
  ]
}

