GET /api/2.5/tenders/77e829220cef46c89b232c408c771bff/qualifications HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "id": "c29fd0e4e9d3459a80c4581fdfa75ef6",
      "bidID": "3ce99d9acadd4392a6e7e5badea84d2f",
      "lotID": "1ce862da3d7f4b8ca7160edab3452691",
      "status": "pending",
      "date": "2027-01-01T00:03:00+02:00",
      "qualified": false,
      "eligible": false
    },
    {
      "id": "f1c14917633d4811bc506954af4a91fc",
      "bidID": "2caee4fba6df43daa9f432069ff4f83e",
      "lotID": "1ce862da3d7f4b8ca7160edab3452691",
      "status": "pending",
      "date": "2027-01-01T00:03:00+02:00",
      "qualified": false,
      "eligible": false
    },
    {
      "id": "292dbf0af55b43f3993d9fcf7278f29e",
      "bidID": "d12a4588000c4f508df566cb85f1eeee",
      "lotID": "1ce862da3d7f4b8ca7160edab3452691",
      "status": "pending",
      "date": "2027-01-01T00:03:00+02:00",
      "qualified": false,
      "eligible": false
    },
    {
      "id": "e7f05581f9e646a5a6e2e1117f4e33d6",
      "bidID": "8f96451aec6a48e4a98b361b7cdecddb",
      "lotID": "1ce862da3d7f4b8ca7160edab3452691",
      "status": "pending",
      "date": "2027-01-01T00:03:00+02:00",
      "qualified": false,
      "eligible": false
    }
  ]
}

