GET /api/2.5/tenders/35f93e8dd5484abb8b90687952c82010/qualifications HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "3743ee6ffa2347c7978a588bff6cfa37", 
      "date": "2020-09-08T01:00:00+03:00", 
      "id": "688adb9bb70e4d4fbcaf4ba1025e7e1a"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "bc5002792d8542b4ad496fdc27d87cec", 
      "date": "2020-09-08T01:00:00+03:00", 
      "id": "be53976fae27403594b3de9b7bdfba6a"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "215c2938873a430ab0ead01f3f7b16dc", 
      "date": "2020-09-08T01:00:00+03:00", 
      "id": "5ffc4b1c851848199fd66861aa118688"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "a9dfbf475786442eb9724e7364d1b6e3", 
      "date": "2020-09-08T01:00:00+03:00", 
      "id": "21a68f5b2e664a23827a19a669007d33"
    }
  ]
}

