POST /api/2.5/tenders/5133e89c95af4bea9a9c805c6e02f950/qualifications/f332dc5d02dc450e99f79515da9560a1/complaints?acc_token=31d9dce5c1df44cb9b7244d6267bbb1a HTTP/1.0
Authorization: Bearer broker
Content-Length: 1298
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Недостатньо інформації", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5133e89c95af4bea9a9c805c6e02f950/qualifications/f332dc5d02dc450e99f79515da9560a1/complaints/2c1728b7a8854d37a7b701160f6e5564
{
  "access": {
    "transfer": "c6639861576842f6a486c5d4f8d20411", 
    "token": "8dff1e7646c14b24ab007f76a849ef02"
  }, 
  "data": {
    "status": "draft", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "b537ad4e27a949fdaa50235bd7a26ac6", 
    "complaintID": "UA-2019-10-25-000001.1", 
    "date": "2019-10-25T01:00:01+03:00", 
    "type": "claim", 
    "id": "2c1728b7a8854d37a7b701160f6e5564"
  }
}

