PATCH /api/2.5/tenders/00653c26796e413c89e22e65cd6da9cd/qualifications/4bd508dc776d43a1916fbbe4c71d026b?acc_token=209807bd7ed9439eaa4a4da4e94c818f HTTP/1.0
Authorization: Bearer broker
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "unsuccessful"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "4bd508dc776d43a1916fbbe4c71d026b",
    "bidID": "4ca517fcb8d84a9a8f56e79897ac1bb1",
    "lotID": "5a98760088b74d2194a86ab2546f20b4",
    "status": "unsuccessful",
    "date": "2023-10-10T01:00:00+03:00",
    "qualified": false,
    "eligible": false
  }
}

