PATCH /api/2.5/tenders/cce509cd3c324437829f34f6d4d074fb/qualifications/685019c58271466dabb599125f990312?acc_token=b02a0a0cbe7842149f3fab16c42f0d94 HTTP/1.0
Authorization: Bearer broker
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "685019c58271466dabb599125f990312",
    "bidID": "d075f39915d34bb98a8f4abb50f7e3ff",
    "status": "unsuccessful",
    "date": "2021-03-16T00:00:00+02:00",
    "qualified": false,
    "eligible": false
  }
}

