GET /api/2.5/tenders/e16419902ba94afd92483305d6369505/bids/c8cf921842b343ae90f0b4666658776e?acc_token=afb4b304b0aa4ea4ba19e1f03725bf1e HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "«Снігур»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137227",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 35",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Іван Іваненко",
          "email": "fake@mail.com",
          "telephone": "+380322123456"
        },
        "scale": "mid"
      }
    ],
    "id": "c8cf921842b343ae90f0b4666658776e",
    "requirementResponses": [
      {
        "id": "41f518cbd471453a913a32fe8dcfe53e",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "57245e0d06d04ef386d78ef733a77d14",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True"
      },
      {
        "id": "0b94547f9bbf4955998c5661409f5213",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "9d2ad26c6aef436090265a8691e5cae4",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True"
      },
      {
        "id": "ec374e01f4a446479d009e418f72dac5",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "5917de018332457bb66c3bbece0bd9c8",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True"
      },
      {
        "id": "b5075bcd1e434360bf788fc0d05e3b51",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "2d52928afaaf46018ed40a83eb0ece13",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True"
      },
      {
        "id": "d867925de878440e9061ad4b5baae44f",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "38c70266277d42639cb1fd8b92656030",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True"
      },
      {
        "id": "58430774a2c64b5596b92818235803fa",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "88b001dcde1c44568c8776d747d72e3d",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True"
      },
      {
        "id": "7384ef27820f45699944b6194f69aef2",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "dfe69d06e46f4bf186b843e3c6e5882a",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True"
      },
      {
        "id": "bca1943114f345e1b6e38fceef1be9a5",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "e19ceabfe09e4568ab530f36b62d11f5",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True"
      },
      {
        "id": "712c68545cea4c63bf15653934042940",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "3bedb2ce2fa544ff8204a478e2e08b8b",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True"
      },
      {
        "id": "3c0a316602f84ca586535d5c1bceeb15",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "892f2866da4e458aa086c403cfe2797b",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True"
      },
      {
        "id": "b3e5e325bb41459287cd0cde249e40a7",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "e15a43cb1c0143c3900a40af4f1e58a9",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True"
      }
    ],
    "status": "unsuccessful"
  }
}

