POST /api/2.5/tenders/8c90145216a24d5aa75953a94a96160d/documents?acc_token=afb4b304b0aa4ea4ba19e1f03725bf1e HTTP/1.0
Authorization: Bearer broker
Content-Length: 329
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "AwardCriteria.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5620292407bb4c8dab640c22d09475b0?Signature=AqiL8tz64uACs5J6xTIlGgEwVSD%2BPIPRYuN0WerllNaFGYd4f1FM50qZhHillmSL8y3tKG%2FGbni4BJncdHCACw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/8c90145216a24d5aa75953a94a96160d/documents/dcd3545e2293415f8afcb323585191bf
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "AwardCriteria.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5620292407bb4c8dab640c22d09475b0?Signature=MHIb%2B50YHwSXW4U5yJ%2Bf3JQwBjDzHaOSym60tDaSUPHGW0tB9%2BzfpVEkbNmhC6%2BJ2FzWqUFZkasHD6BUhuqQDw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "id": "dcd3545e2293415f8afcb323585191bf",
    "datePublished": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:00+02:00",
    "author": "tender_owner"
  }
}

