@startuml


partition "Перший етап" {

    :Створюєтся фреймворк з конфігом hasLegalRegulation = true | false;
    :Завершуєтся відбір / формуются агріменти + контракти;

}

partition "Другий етап" {
    if (В першому етапі був hasLegalRegulation) then (true)
        :Беремо конфіги, що вказані у колонці "Регулюється ЗУ";


    else (false)
        :Беремо конфіг, що вказані у колонці "Не регулюється ЗУ";

    endif
    :Створення тендера з "procurementMethodType": "competitiveOrdering";
}





@enduml