GET /api/2.5/tenders/61a4604114444820b7d85e6dc92c93b3/contracts HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "suppliers": [
        {
          "name": "Державне управління справами",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00037256",
            "legalName": "Державне управління справами",
            "uri": "http://www.dus.gov.ua/"
          },
          "scale": "micro",
          "address": {
            "streetAddress": "вул. Банкова, 11, корпус 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "01220",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Державне управління справами",
            "telephone": "+0440000000"
          }
        }
      ],
      "items": [
        {
          "id": "4e091c16b3374dceb1d05d57ae90e3bf",
          "description": "телевізори",
          "unit": {
            "name": "кг",
            "value": {
              "amount": 6.0,
              "currency": "UAH",
              "valueAddedTaxIncluded": true
            },
            "code": "KGM"
          },
          "quantity": 5.0,
          "classification": {
            "description": "Cartons",
            "scheme": "ДК021",
            "id": "44617100-9"
          },
          "additionalClassifications": [
            {
              "scheme": "ДКПП",
              "id": "17.21.1",
              "description": "папір і картон гофровані, паперова й картонна тара"
            }
          ],
          "deliveryDate": {
            "startDate": "2023-01-03T00:00:00+02:00",
            "endDate": "2023-01-06T00:00:00+02:00"
          },
          "deliveryAddress": {
            "streetAddress": "вул. Банкова 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "79000",
            "countryName": "Україна"
          },
          "relatedBuyer": "11111111111111111111111111111111"
        }
      ],
      "buyerID": "11111111111111111111111111111111",
      "contractID": "UA-2023-01-01-000001-a-1",
      "id": "243c5ce560a84d80b700742a581fe589",
      "status": "pending",
      "awardID": "addb016aac704c2294f1c3eb498f1e8a",
      "date": "2023-01-01T00:00:00+02:00",
      "value": {
        "amount": 0,
        "currency": "UAH",
        "valueAddedTaxIncluded": true,
        "amountNet": 0
      }
    },
    {
      "suppliers": [
        {
          "name": "Державне управління справами",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00037256",
            "legalName": "Державне управління справами",
            "uri": "http://www.dus.gov.ua/"
          },
          "scale": "micro",
          "address": {
            "streetAddress": "вул. Банкова, 11, корпус 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "01220",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Державне управління справами",
            "telephone": "+0440000000"
          }
        }
      ],
      "items": [
        {
          "id": "5791c5ecb8264d1badcc2d7955877c62",
          "description": "портфелі",
          "unit": {
            "name": "кг",
            "value": {
              "amount": 6.0,
              "currency": "UAH",
              "valueAddedTaxIncluded": true
            },
            "code": "KGM"
          },
          "quantity": 5.0,
          "classification": {
            "description": "Cartons",
            "scheme": "ДК021",
            "id": "44617100-9"
          },
          "additionalClassifications": [
            {
              "scheme": "ДКПП",
              "id": "17.21.1",
              "description": "папір і картон гофровані, паперова й картонна тара"
            }
          ],
          "deliveryDate": {
            "startDate": "2023-01-03T00:00:00+02:00",
            "endDate": "2023-01-06T00:00:00+02:00"
          },
          "deliveryAddress": {
            "streetAddress": "вул. Банкова 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "79000",
            "countryName": "Україна"
          },
          "relatedBuyer": "22222222222222222222222222222222"
        },
        {
          "id": "a96de68112fb4c45b7c23d49e6f6ddc3",
          "description": "портфелі",
          "unit": {
            "name": "кг",
            "value": {
              "amount": 6.0,
              "currency": "UAH",
              "valueAddedTaxIncluded": true
            },
            "code": "KGM"
          },
          "quantity": 5.0,
          "classification": {
            "description": "Cartons",
            "scheme": "ДК021",
            "id": "44617100-9"
          },
          "additionalClassifications": [
            {
              "scheme": "ДКПП",
              "id": "17.21.1",
              "description": "папір і картон гофровані, паперова й картонна тара"
            }
          ],
          "deliveryDate": {
            "startDate": "2023-01-03T00:00:00+02:00",
            "endDate": "2023-01-06T00:00:00+02:00"
          },
          "deliveryAddress": {
            "streetAddress": "вул. Банкова 1",
            "locality": "м. Київ",
            "region": "м. Київ",
            "postalCode": "79000",
            "countryName": "Україна"
          },
          "relatedBuyer": "22222222222222222222222222222222"
        }
      ],
      "buyerID": "22222222222222222222222222222222",
      "contractID": "UA-2023-01-01-000001-a-2",
      "id": "45672b610db747b8a84807aa1daf52b4",
      "status": "pending",
      "awardID": "addb016aac704c2294f1c3eb498f1e8a",
      "date": "2023-01-01T00:00:00+02:00",
      "value": {
        "amount": 0,
        "currency": "UAH",
        "valueAddedTaxIncluded": true,
        "amountNet": 0
      }
    }
  ]
}

