GET /api/2.5/tenders/9edb2de5d15247d485a377e07702bc83/contracts/e07c2e4ee19e43c5bce75b127566b232/documents HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "contract_first_document.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fd05000cea6644509133d7a55a6d0eb6?Signature=BGFjPoS7Fy6SJmiIpVychi4qX2I%2FLWV1%2Bq5Hj2XRrdRyYCMhO2KkHlHjL5DS8QqeV38n2bjWlho1wM03cTe6AQ%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "e0dbb5b1ba48444caa87e74919f15684",
      "datePublished": "2023-01-01T00:00:01+02:00",
      "dateModified": "2023-01-01T00:00:01+02:00"
    }
  ]
}

