from openprocurement.api.models import IsoDateTimeType, Model
from openprocurement.tender.core.procedure.models.base import (
    ModelType, ListType,
)
from openprocurement.tender.core.procedure.models.document import Document
from openprocurement.tender.core.procedure.models.identifier import Identifier
from openprocurement.tender.core.procedure.models.organization import Organization
from openprocurement.tender.core.procedure.models.guarantee import Guarantee
from openprocurement.api.context import get_now
from schematics.types import StringType, MD5Type, BaseType, BooleanType
from uuid import uuid4


class ComplaintIdentifier(Identifier):
    id = BaseType(required=True)
    legalName = StringType(required=True)


class ComplaintOrganization(Organization):
    identifier = ModelType(ComplaintIdentifier, required=True)


class Complaint(Model):
    id = MD5Type(required=True, default=lambda: uuid4().hex)
    complaintID = StringType()
    date = IsoDateTimeType(default=get_now)  # autogenerated date of posting
    status = StringType(
        choices=[
            "draft",
            "claim",
            "answered",
            "pending",
            "invalid",
            "resolved",
            "declined",
            "cancelled",
            "ignored",
            "mistaken"
        ]
    )
    documents = ListType(ModelType(Document, required=True))
    type = StringType(
        choices=["claim", "complaint"],
    )  # 'complaint' if status in ['pending'] or 'claim' if status in ['draft', 'claim', 'answered']
    owner_token = StringType()
    transfer_token = StringType()
    owner = StringType()
    relatedLot = MD5Type()
    # complainant
    author = ModelType(ComplaintOrganization, required=True)  # author of claim
    title = StringType(required=True)  # title of the claim
    description = StringType()  # description of the claim
    dateSubmitted = IsoDateTimeType()
    # tender owner
    resolution = StringType()
    resolutionType = StringType(choices=["invalid", "resolved", "declined"])
    dateAnswered = IsoDateTimeType()
    tendererAction = StringType()
    tendererActionDate = IsoDateTimeType()
    # complainant
    satisfied = BooleanType()
    dateEscalated = IsoDateTimeType()
    # reviewer
    decision = StringType()
    dateDecision = IsoDateTimeType()
    # complainant
    cancellationReason = StringType()
    dateCanceled = IsoDateTimeType()

    value = ModelType(Guarantee)
    rejectReason = StringType(choices=[
        "buyerViolationsCorrected",
        "lawNonCompliance",
        "alreadyExists",
        "tenderCancelled",
        "cancelledByComplainant",
        "complaintPeriodEnded",
        "incorrectPayment"
    ])
