PATCH /api/2.3/tenders/6a46e717b72244b687994b70c92240d5/bids/b176d7fbadbd40dc94b280557a12a151?acc_token=41c0e02434b7426ea7c79b73a97ae4bd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/6a46e717b72244b687994b70c92240d5/bids/b176d7fbadbd40dc94b280557a12a151/documents/f6bd90a714df4b1495742bda9da8de53?download=8cf941a2cdb7497cb696cf21217550c1", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-20T12:34:16.996548+03:00", 
        "id": "f6bd90a714df4b1495742bda9da8de53", 
        "dateModified": "2017-06-20T12:34:16.996581+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "b176d7fbadbd40dc94b280557a12a151", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-06-20T12:34:16.793945+03:00", 
    "selfQualified": true
  }
}

