PATCH /api/2.3/tenders/92ad8804586d4edbb98cdb5c7c79412f/cancellations/2efc2a6437da43d0958cb542044e99c2/documents/59838452f64543dea56c62521d090fb3?acc_token=415d188e59964730bee17aae7ed1f7ab HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/a592a276e6a54d829e5516b351b63c7f?KeyID=1b00d854&Signature=sMfPVNKjC6rzYSvyIuWAl9EbZZJxYSpbm6I7zz32SA7cjC23ThUjm8DDPIRsAFQzv%2FH2lcLGRWMvLcni3u%252B8Cg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-06-21T17:05:39.410616+03:00", 
    "id": "59838452f64543dea56c62521d090fb3", 
    "dateModified": "2017-06-21T17:05:39.410655+03:00"
  }
}

