PATCH /api/2.3/tenders/cff7af8207e64d729beeb2df846873bf?acc_token=5ebcd4d769164a98ab864600b9eecc96 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.tendering"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-08-17-000001", 
    "tenderPeriod": {
      "startDate": "2016-08-17T11:57:12.696323+03:00", 
      "endDate": "2016-09-16T11:57:22.752912+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2016-08-17T11:57:12.696323+03:00", 
      "clarificationsUntil": "2016-09-09T11:57:22.752912+03:00", 
      "endDate": "2016-09-06T11:57:22.752912+03:00", 
      "invalidationDate": "2016-08-17T11:57:12.844955+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-08-17T11:57:12.696323+03:00", 
      "endDate": "2016-09-12T00:00:00+03:00"
    }, 
    "procurementMethodType": "competitiveDialogueUA.stage2", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "date": "2016-08-17T11:57:12.846353+03:00", 
    "next_check": "2016-09-16T11:57:22.752912+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-09-17T00:00:00+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2016-08-17T11:57:12.846353+03:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-06T11:56:24.666422+03:00", 
          "endDate": "2016-10-06T11:56:24.666440+03:00"
        }, 
        "id": "033e561e8a534798bdcb519c8e084060", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "cff7af8207e64d729beeb2df846873bf", 
    "awardCriteria": "lowestCost"
  }
}

