PUT /api/2.3/tenders/6a46e717b72244b687994b70c92240d5/documents/7ed8eab0af3b485e960fff0083f5b015?acc_token=5d0fda9cac5540f6847db3d7eb2769f7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy995628699768$
Host: api-sandbox.openprocurement.org


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/62e07eb4fec949709971a62c36c10ac5?KeyID=d98c6de5&Signature=2j%252BCT1Uae6N%2FInM8ql7SCWk043LzaD8ztuEvdKPdDly0P3zvYLQHZaklQry39UpqKqcNE3TiUTaGnXVxz4xoDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-06-20T12:34:15.925520+03:00", 
    "id": "7ed8eab0af3b485e960fff0083f5b015", 
    "dateModified": "2017-06-20T12:34:16.020639+03:00"
  }
}

