POST /api/2.5/agreements/b7536ab0fbe34a1dafa73fe7943ff79c/documents?acc_token=9870067ea6e64d14adf4016d24d15f0c HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "agreement_changes.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6c343bcdd7d241068f88138036b4e52a?Signature=vhFVJH%2BWXh8iggm9ieV4RAxb8cH6Bmf%2F%2BacGhtnigHlLyPezAg2WgaAnhdh211eXDo0T2q%2F22rai3BVdbVH7BQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/agreements/b7536ab0fbe34a1dafa73fe7943ff79c/documents/0ea0d2981ba746a3b63bbdd37c3efbe4

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "agreement_changes.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6c343bcdd7d241068f88138036b4e52a?Signature=cU7WXirw65OUUhuS5lZDppSTLBBAEOZ6GMLIefKy1mqh5Qe9B9T8b%2B%2BfoucGKMRZRL2%2FSJeoZWpypUlbWdU5DA%3D%3D&KeyID=a8968c46",
    "language": "uk",
    "documentOf": "agreement",
    "id": "0ea0d2981ba746a3b63bbdd37c3efbe4",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00"
  }
}

