PATCH /api/2.5/agreements/1746cfba69864f7d996e4bd000858884?acc_token=aab65e490788430f8cce6e18e011268f HTTP/1.0
Authorization: Bearer broker
Content-Length: 34
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "terminated"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "agreementID": "UA-2023-01-01-000001-a-8053c38b861e4d27b6375ab5eb93cc1c1",
    "status": "terminated",
    "dateModified": "2023-01-01T00:00:00+02:00",
    "owner": "broker",
    "changes": [
      {
        "id": "12f43718ecbf474886b7f3545a7debe5",
        "status": "active",
        "date": "2023-01-01T00:00:00+02:00",
        "rationale": "Друга і третя поставка має бути розфасована",
        "rationale_en": "Agreement change cause",
        "dateSigned": "2023-01-01T00:00:00+02:00",
        "rationaleType": "taxRate",
        "modifications": [
          {
            "itemId": "7e815525aab3461e840b13c851f381dd",
            "factor": 0.1605
          }
        ]
      }
    ],
    "documents": [
      {
        "id": "609409e8a6d7475f93a90e94375fb2f2",
        "hash": "md5:00000000000000000000000000000000",
        "title": "agreement_changes.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/711ea6b2fbaf40dca24dafb911e13fc8?Signature=VrEO7RUi2UqTpzKbB75Ae9qBzTyi6n4VMCF7wdNZ%2FJUTns%2BpGDcEFHcaKPlvHeEuPOsk7tczI4Lq10IHYJ%2FuDA%3D%3D&KeyID=a8968c46",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "relatedItem": "12f43718ecbf474886b7f3545a7debe5",
        "documentOf": "change"
      },
      {
        "id": "533dbc0fa33e4847b0347a4214060ced",
        "hash": "md5:00000000000000000000000000000000",
        "title": "agreement.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/37d18c5759474877a074f9fd73d9f309?Signature=QXkoGo7r0SD7Miz0uW75JY5%2BEDXR4J%2Bi7z6UGnP9MoVt0qnwHASpN7g8gs81ZBpbhNUec%2BH2FzjdXySRUaZtCQ%3D%3D&KeyID=a8968c46",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "documentOf": "agreement"
      },
      {
        "id": "b8a98c5d73aa49f0a0fc11f670517f55",
        "hash": "md5:00000000000000000000000000000000",
        "title": "agreement_additional_docs.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/236e52bfd0544af3a63b07325306ef15?Signature=xb3aZmBRE7gbJkxQEN%2FABaUPvwJDHQK8opyRkU5wKogWbwz5pf%2FMc0IsWKc36HYyXYOgWW%2Bk8h8rPKTNvJMCCA%3D%3D&KeyID=a8968c46",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "documentOf": "agreement"
      },
      {
        "id": "b8a98c5d73aa49f0a0fc11f670517f55",
        "hash": "md5:00000000000000000000000000000000",
        "title": "agreement_additional_docs.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3af481ed19e248bba78454fa650169ed?Signature=%2BCzka8hVahNy3sEGewlIeMfyiNJMIH0prWk6bHX4iSOwZisARfC5%2BKJTbuIiirL2RqXRjXbb9xk44rd1HRPsCA%3D%3D&KeyID=a8968c46",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "documentOf": "agreement"
      }
    ],
    "contracts": [
      {
        "id": "ab9b0f04fe08458ab0ea443c5744cb1d",
        "status": "active",
        "suppliers": [
          {
            "name": "Державне управління справами",
            "name_en": "State administration",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00037256",
              "legalName_en": "dus.gov.ua",
              "uri": "http://www.dus.gov.ua/"
            },
            "contactPoint": {
              "name": "Державне управління справами",
              "name_en": "State administration",
              "telephone": "+0440000000"
            },
            "scale": "micro",
            "address": {
              "streetAddress": "вул. Банкова, 11, корпус 1",
              "locality": "м. Київ",
              "region": "м. Київ",
              "postalCode": "01220",
              "countryName": "Україна"
            }
          }
        ],
        "unitPrices": [
          {
            "relatedItem": "7e815525aab3461e840b13c851f381dd",
            "value": {
              "currency": "UAH",
              "valueAddedTaxIncluded": true,
              "amount": 14.93
            }
          }
        ],
        "awardID": "146d55f13a704b11b95275254e00fef4",
        "bidID": "a4aaf72182904a549e80dc4d765040a2",
        "date": "2023-01-01T00:00:00+02:00"
      },
      {
        "id": "cee7f5c4218c4fd085672d17d4785c01",
        "status": "active",
        "suppliers": [
          {
            "name": "Державне управління справами",
            "name_en": "State administration",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00037256",
              "legalName_en": "dus.gov.ua",
              "uri": "http://www.dus.gov.ua/"
            },
            "contactPoint": {
              "name": "Державне управління справами",
              "name_en": "State administration",
              "telephone": "+0440000000"
            },
            "scale": "micro",
            "address": {
              "streetAddress": "вул. Банкова, 11, корпус 1",
              "locality": "м. Київ",
              "region": "м. Київ",
              "postalCode": "01220",
              "countryName": "Україна"
            }
          }
        ],
        "unitPrices": [
          {
            "relatedItem": "7e815525aab3461e840b13c851f381dd",
            "value": {
              "currency": "UAH",
              "valueAddedTaxIncluded": true,
              "amount": 14.93
            }
          }
        ],
        "awardID": "88f3ec5213a7405a92b7bd353549edb1",
        "bidID": "2269d0f299644a87bfd73ac8a065c501",
        "date": "2023-01-01T00:00:00+02:00"
      },
      {
        "id": "ce463db3a53c494897d98b47064e3ad5",
        "status": "active",
        "suppliers": [
          {
            "name": "Державне управління справами",
            "name_en": "State administration",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00037256",
              "legalName_en": "dus.gov.ua",
              "uri": "http://www.dus.gov.ua/"
            },
            "contactPoint": {
              "name": "Державне управління справами",
              "name_en": "State administration",
              "telephone": "+0440000000"
            },
            "scale": "micro",
            "address": {
              "streetAddress": "вул. Банкова, 11, корпус 1",
              "locality": "м. Київ",
              "region": "м. Київ",
              "postalCode": "01220",
              "countryName": "Україна"
            }
          }
        ],
        "unitPrices": [
          {
            "relatedItem": "7e815525aab3461e840b13c851f381dd",
            "value": {
              "currency": "UAH",
              "valueAddedTaxIncluded": true,
              "amount": 14.93
            }
          }
        ],
        "awardID": "f8a353351f6449128fc5be8abba6e67f",
        "bidID": "5aa54309d515431f8edb45ca63c1d1cd",
        "date": "2023-01-01T00:00:00+02:00"
      }
    ],
    "items": [
      {
        "id": "7e815525aab3461e840b13c851f381dd",
        "description": "футляри до державних нагород",
        "quantity": 5.0,
        "relatedLot": "27c4a15dce034406ba16156354632d9b",
        "classification": {
          "description": "Cartons",
          "scheme": "ДК021",
          "id": "44617100-9"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ],
        "description_en": "Cases for state awards",
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00",
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "unit": {
          "name": "item",
          "code": "KGM"
        }
      }
    ],
    "procuringEntity": {
      "name": "Державне управління справами",
      "name_en": "State administration",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00037256",
        "legalName_en": "dus.gov.ua",
        "uri": "http://www.dus.gov.ua/"
      },
      "address": {
        "streetAddress": "вул. Банкова, 11, корпус 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "kind": "general",
      "contactPoint": {
        "name": "Державне управління справами",
        "name_en": "State administration",
        "telephone": "+0440000000",
        "availableLanguage": "uk"
      }
    },
    "tender_id": "d3e312b04f024e00b2ea4a43dfaf661e",
    "id": "1746cfba69864f7d996e4bd000858884",
    "numberOfContracts": 3
  }
}

