GET /api/2.5/agreements/b7536ab0fbe34a1dafa73fe7943ff79c/changes/021c093dc15d4e078ce3061ae63cd514 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "021c093dc15d4e078ce3061ae63cd514",
    "status": "pending",
    "date": "2023-01-01T00:00:00+02:00",
    "rationale": "Опис причини змін егріменту",
    "rationale_en": "Agreement change cause",
    "rationaleType": "taxRate"
  }
}

