GET /api/2.5/agreements/8887db77f71c4a0496b39ac2c4eea78c/changes HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "id": "763394fc5c714348b33cea25674f6916",
      "status": "active",
      "date": "2027-01-01T00:00:00+02:00",
      "rationale": "Друга і третя поставка має бути розфасована",
      "rationale_en": "Agreement change cause",
      "dateSigned": "2027-01-01T00:00:00+02:00",
      "rationaleType": "taxRate",
      "modifications": [
        {
          "itemId": "ce7ee9fee64b4eaa87dd010843796c9a",
          "factor": 0.1605
        }
      ]
    }
  ]
}

