#!/usr/bin/env python3
"""
Static check of the files generated by the docs tests (docs/tests/*.py):

- every generated file (http/csv/json) on disk must be written by some docs test,
- every generated file referenced from the rst sources must be written by some docs test,
- every generated file must be written by a single test, otherwise its content depends on the tests order.

The output paths are collected statically from the docs tests (docs/tests and tests/docs):
``open(TARGET_DIR + "name.http", "w")``, ``file_path=TARGET_CSV_DIR + "name.csv"``,
``filename=TARGET_DIR + "name.http"``; f-strings and ``str.format()`` become glob patterns.
"""

from __future__ import annotations

import ast
import fnmatch
import os
import re
import sys
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = DOCS_DIR.parent
SOURCE_DIR = DOCS_DIR / "source"
TESTS_DIRS = (DOCS_DIR / "tests", REPO_DIR / "tests" / "docs")

GENERATED_SUFFIXES = {".http", ".csv", ".json"}
PATH_KEYWORDS = ("file_path", "filename")

# directories (relative to docs/source) with handwritten files
EXCLUDED_DIRS = (
    "developers",  # examples of the documentation syntax itself
    "medicines-registry",  # documentation of another service
    "tendering/basic-actions/http-handwritten",
    "tendering/basic-actions/http-outdated",  # examples of the removed functionality, frozen by design
)

RST_REFERENCE_RE = re.compile(
    r"^\s*(?:\.\.\s+(?:http:example|literalinclude)::|:file:)\s+(\S+)",
    re.MULTILINE,
)


class PathResolver(ast.NodeVisitor):
    """Resolves module level string constants and path expressions of one docs test module."""

    def __init__(self, module_path: Path):
        self.module_path = module_path
        self.constants: dict[str, str] = {}

    def evaluate(self, node: ast.AST) -> str | None:
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return node.value
        if isinstance(node, ast.Name):
            if node.id == "__file__":
                return str(self.module_path)
            return self.constants.get(node.id)
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
            left, right = self.evaluate(node.left), self.evaluate(node.right)
            if left is not None and right is not None:
                return left + right
            return None
        if isinstance(node, ast.JoinedStr):
            parts = []
            for value in node.values:
                if isinstance(value, ast.FormattedValue):
                    parts.append("*")
                else:
                    part = self.evaluate(value)
                    if part is None:
                        return None
                    parts.append(part)
            return "".join(parts)
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Attribute) and node.func.attr == "format":
                template = self.evaluate(node.func.value)
                return None if template is None else re.sub(r"{[^}]*}", "*", template)
            func = ast.unparse(node.func)
            args = [self.evaluate(arg) for arg in node.args]
            if any(arg is None for arg in args):
                return None
            if func == "os.path.join":
                return os.path.join(*args)
            if func == "os.path.dirname":
                return os.path.dirname(args[0])
            if func == "os.path.abspath":
                return os.path.abspath(args[0])
        return None

    def visit_Assign(self, node: ast.Assign) -> None:
        if len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            value = self.evaluate(node.value)
            if value is not None:
                self.constants[node.targets[0].id] = value


def write_targets(tree: ast.AST) -> list[tuple[ast.AST, str]]:
    """Expressions of paths that docs tests write to, with the name of the enclosing function."""
    parents = {child: node for node in ast.walk(tree) for child in ast.iter_child_nodes(node)}

    def enclosing_function(node: ast.AST) -> str:
        while node in parents:
            node = parents[node]
            if isinstance(node, ast.FunctionDef):
                return node.name
        return "<module>"

    targets = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if isinstance(node.func, ast.Name) and node.func.id == "open" and node.args:
            mode = node.args[1] if len(node.args) > 1 else None
            for keyword in node.keywords:
                if keyword.arg == "mode":
                    mode = keyword.value
            if isinstance(mode, ast.Constant) and str(mode.value).startswith("w"):
                targets.append((node.args[0], enclosing_function(node)))
        for keyword in node.keywords:
            if keyword.arg in PATH_KEYWORDS:
                targets.append((keyword.value, enclosing_function(node)))
    return targets


def relative_to_repo(path: str) -> str:
    if not os.path.isabs(path):
        path = os.path.join(REPO_DIR, path)
    return os.path.relpath(os.path.normpath(path), REPO_DIR)


def collect_generated() -> tuple[dict[str, set[str]], set[str], list[str]]:
    """Returns the writers of every exact generated path, glob patterns and unresolved expressions."""
    writers: dict[str, set[str]] = {}
    patterns, unresolved = set(), []
    for module_path in sorted(path for tests_dir in TESTS_DIRS for path in tests_dir.glob("test_*.py")):
        tree = ast.parse(module_path.read_text(), filename=str(module_path))
        resolver = PathResolver(module_path)
        resolver.visit(tree)
        module = str(module_path.relative_to(REPO_DIR))
        for target, function in write_targets(tree):
            value = resolver.evaluate(target)
            if value is None:
                if not isinstance(target, ast.Name):  # a parameter of a helper function
                    unresolved.append(f"{module}:{target.lineno}: {ast.unparse(target)}")
                continue
            value = relative_to_repo(value)
            if "*" in value:
                patterns.add(value)
            else:
                writers.setdefault(value, set()).add(f"{module}::{function}")
    return writers, patterns, unresolved


def collect_referenced() -> dict[str, list[str]]:
    """Maps every referenced generated file to the rst files referencing it."""
    referenced: dict[str, list[str]] = {}
    for rst_path in sorted(SOURCE_DIR.rglob("*.rst")):
        for match in RST_REFERENCE_RE.finditer(rst_path.read_text()):
            path = relative_to_repo(str(rst_path.parent / match.group(1)))
            if Path(path).suffix in GENERATED_SUFFIXES:
                referenced.setdefault(path, []).append(str(rst_path.relative_to(REPO_DIR)))
    return referenced


def is_excluded(path: str) -> bool:
    relative = Path(path).relative_to(SOURCE_DIR.relative_to(REPO_DIR))
    return any(relative.is_relative_to(excluded) for excluded in EXCLUDED_DIRS)


def is_generated(path: str, exact: set[str], patterns: set[str]) -> bool:
    return path in exact or any(fnmatch.fnmatch(path, pattern) for pattern in patterns)


def main() -> int:
    writers, patterns, unresolved = collect_generated()
    exact = set(writers)
    referenced = collect_referenced()
    errors = 0

    for line in unresolved:
        print(f"{line}: can't resolve the output path statically", file=sys.stderr)
        errors += 1

    for path, tests in sorted(writers.items()):
        if len(tests) > 1 and not is_excluded(path):
            print(f"{path}: written by several tests, {', '.join(sorted(tests))}", file=sys.stderr)
            errors += 1

    on_disk = sorted(
        str(path.relative_to(REPO_DIR))
        for path in SOURCE_DIR.rglob("*")
        if path.is_file() and path.suffix in GENERATED_SUFFIXES
    )
    for path in on_disk:
        if not is_excluded(path) and not is_generated(path, exact, patterns):
            print(f"{path}: not generated by docs tests", file=sys.stderr)
            errors += 1

    for path, rst_files in sorted(referenced.items()):
        if not is_excluded(path) and not is_generated(path, exact, patterns):
            print(f"{path}: referenced in {', '.join(rst_files)} but not generated by docs tests", file=sys.stderr)
            errors += 1

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
