PATCH /api/2.5/contracts/0df8cf97d5cb4ba98a7355f981e0afd2/changes/b9887678ba3c448b977467c0fe3ada31?acc_token=1981a3b3a85d4159aabe55f5be082fd5 HTTP/1.0
Authorization: Bearer broker
Content-Length: 73
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active",
    "dateSigned": "2023-09-01T01:00:00+03:00"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "rationale": "Друга і третя поставка має бути розфасована",
    "rationale_en": "Contract change cause",
    "rationaleTypes": [
      "volumeCuts",
      "priceReduction"
    ],
    "dateSigned": "2023-09-01T01:00:00+03:00",
    "id": "b9887678ba3c448b977467c0fe3ada31",
    "status": "active",
    "date": "2023-09-01T01:00:00+03:00"
  }
}

