GET /api/2.5/contracts?opt_fields=status HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "status": "pending",
      "dateModified": "2027-01-01T00:00:00+02:00",
      "id": "140c1549722f49e2a2ddabb3bf59a8e0"
    }
  ],
  "next_page": {
    "offset": "1798754400.0.1.29401f134708b46e9b34ef62111f6695",
    "path": "/api/2.5/contracts?opt_fields=status&offset=1798754400.0.1.29401f134708b46e9b34ef62111f6695",
    "uri": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/contracts?opt_fields=status&offset=1798754400.0.1.29401f134708b46e9b34ef62111f6695"
  }
}

