POST /api/2.5/contracts/d71a69be5f1a437abf5134881f4c4b98/changes/e3b63c3aac354f6db3fbc8f25d03cc7d/documents?acc_token=47c3f4968e1341499809200105e2aade HTTP/1.0
Authorization: Bearer broker6
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "documentType": "contractSignature",
    "title": "sign.p7s",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9dc6bfe4683b4e63a799bbe366ba9376?Signature=7DWfdBRHAAJ%2B1P1BSGB%2FmCbWTCo%2BtmGS9jsRJ8ZjGLgs3620bu7fab8LAVooJfFR4ddSLVDqvY%2Brn2aywo2TAg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pkcs7-signature"
  }
}


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Can't update contract change in current (cancelled) status"
    }
  ]
}

