GET /api/2.5/contracts/479178eb904d41c5a40be7f83405f22d/documents/c2a8719a164a4f9ab1f86536106f2498?acc_token=3b095197e5f94f76a28bae3a3079c206 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "confidentiality": "public",
    "id": "c2a8719a164a4f9ab1f86536106f2498",
    "hash": "md5:00000000000000000000000000000000",
    "title": "contract_additional_docs.doc",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c2fbdf60afd54cf3acdc89af698f87d2?Signature=kkWFx7aNWwgD%2F3KSmjbnzA%2BYzH4PvTJL1XRiDauwDPCQRsMHTfnUXxTygRpeggxjBENLuks5YIdiYyxxv6yBDg%3D%3D&KeyID=a8968c46",
    "documentOf": "contract",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "previousVersions": [
      {
        "confidentiality": "public",
        "hash": "md5:00000000000000000000000000000000",
        "title": "contract_additional_docs.doc",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/277f219d159f45e1a11923c8b637d463?Signature=EnWBAbSpO74ppQPPbWr9QNTYM%2Fyee5mRc0iwX3fdwZkdZhmNY0oLP6uLF4v9XyU4ouyIjcTdltumSlUyu4%2B4Bg%3D%3D&KeyID=a8968c46",
        "documentOf": "contract",
        "id": "c2a8719a164a4f9ab1f86536106f2498",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "dateModified": "2023-10-10T01:00:00+03:00"
      }
    ]
  }
}

