# Frozen causeDetails dictionaries from standards version 1.0.253
# Otherwize standards dictionaries are used

FROZEN_CAUSE_DETAILS_NEGOTIATION_ALL = {
    "twiceUnsuccessful": {
        "title_uk": "Пункт 4 частини 2 статті 35",
        "title_en": "Clause 4, Part 2, Article 35",
        "description_uk": "Двічі відмінено процедуру відкритих торгів, у тому числі частково (за лотом), через відсутність достатньої кількості тендерних пропозицій, визначеної цим Законом",
        "description_en": "If procuring entity twicely cancelled a tender due to lack of suppliers",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20191201#n548",
        "scheme": "LAW922",
        "archive": True,
    },
    "noCompetition": {
        "title_uk": "Пункт 2 частини 2 статті 35",
        "title_en": "Clause 2, Part 2, Article 35",
        "description_uk": "Роботи, товари чи послуги можуть бути виконані, поставлені чи надані виключно певним суб’єктом господарювання",
        "description_en": "Lack of competition on suited market because of which procurement contract can be established only with one supplier",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20191201#n548",
        "scheme": "LAW922",
        "archive": True,
    },
    "additionalPurchase": {
        "title_uk": "Пункт 4 частини 2 статті 40",
        "title_en": "Clause 4, Part 2, Article 40",
        "description_uk": "Якщо після укладення договору про закупівлю у замовника виникла необхідність у постачанні додаткового обсягу товару у того самого постачальника, якщо в разі зміни постачальника замовник був би вимушений придбати товар з іншими технічними характеристиками, що призвело б до виникнення несумісності, пов’язаної з експлуатацією і технічним обслуговуванням. Закупівля додаткового обсягу товару у того самого постачальника здійснюється протягом трьох років після укладення договору про закупівлю, якщо загальна вартість такого постачання не перевищує 50 відсотків ціни договору про закупівлю",
        "description_en": "If, after concluding a procurement contract, the customer needs to purchase additional goods from the same supplier, because changing suppliers would require purchasing goods with different technical characteristics, which would lead to incompatibility issues related to operation and maintenance. The purchase of additional goods from the same supplier shall be carried out within three years after the conclusion of the procurement contract, if the total cost of such supply does not exceed 50 percent of the price of the procurement contract",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "additionalConstruction": {
        "title_uk": "Пункт 5 частини 2 статті 40",
        "title_en": "Clause 5, Part 2, Article 40",
        "description_uk": "Якщо після укладення договору про закупівлю у замовника виникла необхідність у закупівлі додаткових аналогічних робіт чи послуг у того самого учасника. Можливість і умови таких додаткових робіт чи послуг можуть бути передбачені в основному договорі про закупівлю, який укладений за результатами проведення тендера. Закупівля додаткових аналогічних робіт чи послуг у того самого учасника здійснюється протягом трьох років після укладення договору про закупівлю, якщо загальна вартість таких робіт чи послуг не перевищує 50 відсотків ціни основного договору про закупівлю, укладеного за результатами проведення тендера",
        "description_en": "If, after concluding a procurement contract, the customer needs to purchase additional similar works or services from the same participant. The possibility and conditions for such additional works or services may be provided for in the main procurement contract concluded following the results of the tender. The procurement of additional similar works or services from the same participant shall be carried out within three years after the conclusion of the procurement contract, if the total cost of such works or services does not exceed 50 percent of the price of the main procurement contract concluded based on the results of the tender",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "resolvingInsolvency": {
        "title_uk": "Пункт 6 частини 2 статті 40",
        "title_en": "Clause 6, Part 2, Article 40",
        "description_uk": "Закупівля товарів за процедурою відновлення платоспроможності боржника згідно із законодавством",
        "description_en": "Purchase of goods under the procedure for restoring the debtor's solvency in accordance with the legislation",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": True,
    },
    "stateLegalServices": {
        "title_uk": "Пункт 7 частини 2 статті 40",
        "title_en": "Clause 7, Part 2, Article 40",
        "description_uk": "Закупівля юридичних послуг, пов’язаних із захистом прав та інтересів України, у тому числі з метою захисту національної безпеки і оборони, під час врегулювання спорів щодо розгляду в закордонних юрисдикційних органах справ за участю іноземного суб’єкта та України, на підставі рішення Кабінету Міністрів України або рішень Ради національної безпеки і оборони України, введених в дію в порядку, визначеному законом, а також закупівлі товарів, робіт і послуг у разі участі замовника на підставі рішення Кабінету Міністрів України в міжнародних виставкових заходах",
        "description_en": "Procurement of legal services related to the protection of Ukraine's rights and interests, including for the purpose of protecting national security and defense, during the settlement of disputes over cases involving foreign entities and Ukraine in foreign courts, based on a decision of the Cabinet of Ministers of Ukraine or decisions of the National Security and Defense Council of Ukraine, enacted in accordance with the procedure established by law, as well as the procurement of goods, works, and services in the event of the customer's participation, based on a decision of the Cabinet of Ministers of Ukraine, in international exhibition events",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "artContestIP": {
        "title_uk": "Пункт 1 частини 2 статті 35",
        "title_en": "Clause 1, Part 2, Article 35",
        "description_uk": "Закупівля творів мистецтва або закупівля, пов’язана із захистом прав інтелектуальної власності, або укладення договору про закупівлю з переможцем архітектурного чи мистецького конкурсу",
        "description_en": "Procurement of works of art or procurement related to the protection of intellectual property rights, or conclusion of a procurement contract with the winner of an architectural or artistic competition",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20191201#n548",
        "scheme": "LAW922",
        "archive": True,
    },
    "artPurchase": {
        "title_uk": "Абзац 2 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 2, Clause 2, Part 2, Article 40",
        "description_uk": "Предмет закупівлі полягає у створенні або придбанні витвору мистецтва або художнього виконання",
        "description_en": "The subject of the procurement is the creation or acquisition of a work of art or artistic performance",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "contestWinner": {
        "title_uk": "Абзац 3 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 3, Clause 2, Part 2, Article 40",
        "description_uk": "Укладення договору про закупівлю з переможцем архітектурного або мистецького конкурсу",
        "description_en": "Conclusion of a procurement contract with the winner of an architectural or art competition",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "technicalReasons": {
        "title_uk": "Абзац 4 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 4, Clause 2, Part 2, Article 40",
        "description_uk": "Відсутність конкуренції з технічних причин, яка має бути документально підтверджена замовником",
        "description_en": "Absence of competition for technical reasons, which must be documented by the customer",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "intProperty": {
        "title_uk": "Абзац 5 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 5, Clause 2, Part 2, Article 40",
        "description_uk": "Існує необхідність захисту прав інтелектуальної власності",
        "description_en": "There is a need to protect intellectual property rights",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "lastHope": {
        "title_uk": "Абзац 6 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 6, subparagraph 2, paragraph 2, Article 40",
        "description_uk": 'Укладення договору про закупівлю з постачальником "останньої надії" на постачання електричної енергії або природного газу',
        "description_en": 'Conclusion of a purchase agreement with a supplier of "last resort" for the supply of electricity or natural gas',
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
}

FROZEN_CAUSE_DETAILS_NEGOTIATION_QUICK_ALL = {
    "twiceUnsuccessful": {
        "title_uk": "Пункт 4 частини 2 статті 35",
        "title_en": "Clause 4, Part 2, Article 35",
        "description_uk": "Двічі відмінено процедуру відкритих торгів, у тому числі частково (за лотом), через відсутність достатньої кількості тендерних пропозицій, визначеної цим Законом",
        "description_en": "If procuring entity twicely cancelled a tender due to lack of suppliers",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20191201#n548",
        "scheme": "LAW922",
        "archive": True,
    },
    "noCompetition": {
        "title_uk": "Пункт 2 частини 2 статті 35",
        "title_en": "Clause 2, Part 2, Article 35",
        "description_uk": "Роботи, товари чи послуги можуть бути виконані, поставлені чи надані виключно певним суб’єктом господарювання",
        "description_en": "Lack of competition on suited market because of which procurement contract can be established only with one supplier",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20191201#n548",
        "scheme": "LAW922",
        "archive": True,
    },
    "quick": {
        "title_uk": "Пункт 3 частини 2 статті 40",
        "title_en": "Clause 3, Part 2, Article 40",
        "description_uk": "Якщо у замовника виникла нагальна потреба здійснити закупівлю",
        "description_en": "If the customer has an urgent need to make a purchase",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "additionalPurchase": {
        "title_uk": "Пункт 4 частини 2 статті 40",
        "title_en": "Clause 4, Part 2, Article 40",
        "description_uk": "Якщо після укладення договору про закупівлю у замовника виникла необхідність у постачанні додаткового обсягу товару у того самого постачальника, якщо в разі зміни постачальника замовник був би вимушений придбати товар з іншими технічними характеристиками, що призвело б до виникнення несумісності, пов’язаної з експлуатацією і технічним обслуговуванням. Закупівля додаткового обсягу товару у того самого постачальника здійснюється протягом трьох років після укладення договору про закупівлю, якщо загальна вартість такого постачання не перевищує 50 відсотків ціни договору про закупівлю",
        "description_en": "If, after concluding a procurement contract, the customer needs to purchase additional goods from the same supplier, because changing suppliers would require purchasing goods with different technical characteristics, which would lead to incompatibility issues related to operation and maintenance. The purchase of additional goods from the same supplier shall be carried out within three years after the conclusion of the procurement contract, if the total cost of such supply does not exceed 50 percent of the price of the procurement contract",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "additionalConstruction": {
        "title_uk": "Пункт 5 частини 2 статті 40",
        "title_en": "Clause 5, Part 2, Article 40",
        "description_uk": "Якщо після укладення договору про закупівлю у замовника виникла необхідність у закупівлі додаткових аналогічних робіт чи послуг у того самого учасника. Можливість і умови таких додаткових робіт чи послуг можуть бути передбачені в основному договорі про закупівлю, який укладений за результатами проведення тендера. Закупівля додаткових аналогічних робіт чи послуг у того самого учасника здійснюється протягом трьох років після укладення договору про закупівлю, якщо загальна вартість таких робіт чи послуг не перевищує 50 відсотків ціни основного договору про закупівлю, укладеного за результатами проведення тендера",
        "description_en": "If, after concluding a procurement contract, the customer needs to purchase additional similar works or services from the same participant. The possibility and conditions for such additional works or services may be provided for in the main procurement contract concluded following the results of the tender. The procurement of additional similar works or services from the same participant shall be carried out within three years after the conclusion of the procurement contract, if the total cost of such works or services does not exceed 50 percent of the price of the main procurement contract concluded based on the results of the tender",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "resolvingInsolvency": {
        "title_uk": "Пункт 6 частини 2 статті 40",
        "title_en": "Clause 6, Part 2, Article 40",
        "description_uk": "Закупівля товарів за процедурою відновлення платоспроможності боржника згідно із законодавством",
        "description_en": "Purchase of goods under the procedure for restoring the debtor's solvency in accordance with the legislation",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": True,
    },
    "stateLegalServices": {
        "title_uk": "Пункт 7 частини 2 статті 40",
        "title_en": "Clause 7, Part 2, Article 40",
        "description_uk": "Закупівля юридичних послуг, пов’язаних із захистом прав та інтересів України, у тому числі з метою захисту національної безпеки і оборони, під час врегулювання спорів щодо розгляду в закордонних юрисдикційних органах справ за участю іноземного суб’єкта та України, на підставі рішення Кабінету Міністрів України або рішень Ради національної безпеки і оборони України, введених в дію в порядку, визначеному законом, а також закупівлі товарів, робіт і послуг у разі участі замовника на підставі рішення Кабінету Міністрів України в міжнародних виставкових заходах",
        "description_en": "Procurement of legal services related to the protection of Ukraine's rights and interests, including for the purpose of protecting national security and defense, during the settlement of disputes over cases involving foreign entities and Ukraine in foreign courts, based on a decision of the Cabinet of Ministers of Ukraine or decisions of the National Security and Defense Council of Ukraine, enacted in accordance with the procedure established by law, as well as the procurement of goods, works, and services in the event of the customer's participation, based on a decision of the Cabinet of Ministers of Ukraine, in international exhibition events",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "artContestIP": {
        "title_uk": "Пункт 1 частини 2 статті 35",
        "title_en": "Clause 1, Part 2, Article 35",
        "description_uk": "Закупівля творів мистецтва або закупівля, пов’язана із захистом прав інтелектуальної власності, або укладення договору про закупівлю з переможцем архітектурного чи мистецького конкурсу",
        "description_en": "Procurement of works of art or procurement related to the protection of intellectual property rights, or conclusion of a procurement contract with the winner of an architectural or artistic competition",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20191201#n548",
        "scheme": "LAW922",
        "archive": True,
    },
    "artPurchase": {
        "title_uk": "Абзац 2 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 2, Clause 2, Part 2, Article 40",
        "description_uk": "Предмет закупівлі полягає у створенні або придбанні витвору мистецтва або художнього виконання",
        "description_en": "The subject of the procurement is the creation or acquisition of a work of art or artistic performance",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "contestWinner": {
        "title_uk": "Абзац 3 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 3, Clause 2, Part 2, Article 40",
        "description_uk": "Укладення договору про закупівлю з переможцем архітектурного або мистецького конкурсу",
        "description_en": "Conclusion of a procurement contract with the winner of an architectural or art competition",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "technicalReasons": {
        "title_uk": "Абзац 4 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 4, Clause 2, Part 2, Article 40",
        "description_uk": "Відсутність конкуренції з технічних причин, яка має бути документально підтверджена замовником",
        "description_en": "Absence of competition for technical reasons, which must be documented by the customer",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "intProperty": {
        "title_uk": "Абзац 5 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 5, Clause 2, Part 2, Article 40",
        "description_uk": "Існує необхідність захисту прав інтелектуальної власності",
        "description_en": "There is a need to protect intellectual property rights",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "lastHope": {
        "title_uk": "Абзац 6 пункту 2 частини 2 статті 40",
        "title_en": "Paragraph 6, subparagraph 2, paragraph 2, Article 40",
        "description_uk": 'Укладення договору про закупівлю з постачальником "останньої надії" на постачання електричної енергії або природного газу',
        "description_en": 'Conclusion of a purchase agreement with a supplier of "last resort" for the supply of electricity or natural gas',
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": False,
    },
    "emergency": {
        "title_uk": "Абзац 2 пункту 3 частини 2 статті 40",
        "title_en": "Paragraph 2, Clause 3, Part 2, Article 40",
        "description_uk": "Виникнення особливих економічних чи соціальних обставин, пов’язаних з негайною ліквідацією наслідків надзвичайних ситуацій, що унеможливлюють дотримання замовником строків для проведення тендера",
        "description_en": "The emergence of special economic or social circumstances related to the immediate elimination of the consequences of emergency situations that make it impossible for the customer to comply with the deadlines for conducting the tender",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": True,
    },
    "humanitarianAid": {
        "title_uk": "Абзац 3 пункту 3 частини 2 статті 40",
        "title_en": "Paragraph 3, Clause 3, Part 2, Article 40",
        "description_uk": "Надання у встановленому порядку Україною гуманітарної допомоги іншим державам",
        "description_en": "Provision of humanitarian assistance by Ukraine to other states in accordance with the established procedure",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": True,
    },
    "contractCancelled": {
        "title_uk": "Абзац 4 пункту 3 частини 2 статті 40",
        "title_en": "Paragraph 4, Clause 3, Part 2, Article 40",
        "description_uk": "Розірвання договору про закупівлю з вини учасника на строк, достатній для проведення тендера, в обсязі, що не перевищує 20 відсотків суми, визначеної в договорі про закупівлю, який розірваний з вини такого учасника. Застосування переговорної процедури закупівлі в такому випадку здійснюється за рішенням замовника щодо кожного тендера",
        "description_en": "Termination of the procurement contract due to the fault of the participant for a period sufficient to conduct the tender, in an amount not exceeding 20 percent of the amount specified in the procurement contract, which is terminated due to the fault of such participant. The application of the negotiated procurement procedure in such a case is carried out by the decision of the customer for each tender",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": True,
    },
    "activeComplaint": {
        "title_uk": "Абзац 5 пункту 3 частини 2 статті 40",
        "title_en": "Paragraph 5, Clause 3, Part 2, Article 40",
        "description_uk": "Оскарження прийнятих рішень, дій чи бездіяльності замовника щодо триваючого тендера після розгляду/оцінки тендерних пропозицій учасників, в обсязі, що не перевищує 20 відсотків від очікуваної вартості тендера, що оскаржується",
        "description_en": "Appealing decisions, actions or inactions of the customer regarding an ongoing tender after consideration/evaluation of the tender proposals of the participants, in an amount not exceeding 20 percent of the expected value of the tender being appealed",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n1717",
        "scheme": "LAW922",
        "archive": True,
    },
}

FROZEN_CAUSE_DETAILS_REPORTING_ALL = {
    "naturalGas": {
        "title_uk": "Підпункт 18 пункту 13",
        "title_en": "Subparagraph 18 of paragraph 13",
        "description_uk": 'Здійснюється закупівля природного газу суб’єктом ринку природного газу, на якого Кабінетом Міністрів України відповідно до Закону України "Про ринок природного газу" покладено спеціальні обов’язки для забезпечення загальносуспільних інтересів у процесі функціонування ринку природного газу',
        "description_en": 'Natural gas is purchased by a natural gas market entity, which, in accordance with the Law of Ukraine "On the Natural Gas Market", has been assigned special responsibilities by the Cabinet of Ministers of Ukraine to ensure general public interests in the process of operating the natural gas market',
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "defenceRecruitment": {
        "title_uk": "Підпункт 23 пункту 13",
        "title_en": "Subparagraph 23 of paragraph 13",
        "description_uk": "Здійснюється закупівля послуг, пов’язаних з перевезенням (оформлення документів, що посвідчують особу, віз, проїзних документів, страхування, транспортування тощо) кандидатів для проходження військової служби з числа іноземців або осіб без громадянства з території іноземних держав, їх харчуванням та проживанням",
        "description_en": "The procurement of services related to the transportation (including processing of identity documents, visas, travel documents, insurance, and logistics) of candidates for military service from among foreign nationals or stateless persons from foreign countries, as well as their accommodation and meals, is being carried out",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "defenceVehicles": {
        "title_uk": "Підпункт 24 пункту 13",
        "title_en": "Subparagraph 24 of paragraph 13",
        "description_uk": "Здійснюється закупівля транспортних засобів, що були в користуванні (з типом кузова пікап, мотовсюдиходів (квадроциклів, у тому числі квадроциклів типу багі) та мотоциклів), військовими частинами, що уповноважені згідно з рішеннями державних замовників у сфері оборони на здійснення закупівель та укладення державних контрактів (договорів), за умови наявності штатно-табельної потреби. Вартість таких транспортних засобів визначається на підставі висновку експерта (висновку експертного дослідження) або звіту про оцінку майна",
        "description_en": "Military units are conducting the procurement of used transport vehicles, including pickup trucks, all-terrain vehicles (such as quad bikes and buggy-type ATVs), and motorcycles",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "heatingSeason": {
        "title_uk": "Підпункт 22 пункту 13",
        "title_en": "Subparagraph 22 of paragraph 13",
        "description_uk": "Здійснюється закупівля: парових турбін (на умовах співфінансування), газопоршневих, газотурбінних когенераційних установок, газотурбінних установок та блочно-модульних котелень (їх складових), їх оренда; послуг з оренди (фрахту, лізингу тощо) суден технічного флоту (спеціалізованих суден), на яких встановлені газопоршневі та/або газотурбінні установки, призначені для виробництва електричної енергії, послуг з найму персоналу для таких установок; товарів, робіт та послуг, пов’язаних з будівництвом установок, зазначених у абзацах другому і третьому цього підпункту, введенням в експлуатацію, здійсненням заходів щодо проектування, будівництва та/або реконструкції електричних, газових мереж, необхідних для забезпечення можливості видачі потужності, приєднанням таких установок до електричних, газових та інших мереж; послуг з проектування, обслуговування, планових і позапланових ремонтів таких установок для підприємств паливно-енергетичного комплексу для підготовки до опалювального сезону",
        "description_en": "The following purchases are being made: steam turbines (on co-financing terms), gas piston and gas turbine cogeneration units, gas turbine units and modular boiler rooms (their components), and their lease; services for the rental (charter, leasing, etc.) of technical fleet vessels (specialized vessels) equipped with gas piston and/or gas turbine units designed for the production of electricity, services for the hiring of personnel for such units; goods, works, and services related to the construction of the installations referred to in the second and third paragraphs of this subparagraph, commissioning, implementation of measures for the design, construction, and/or reconstruction of electrical and gas networks necessary to ensure the possibility of power output, connection of such installations to electrical, gas, and other networks; services for the design, maintenance, scheduled and unscheduled repairs of such facilities for fuel and energy complex enterprises in preparation for the heating season",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "openUnsuccessful": {
        "title_uk": "Підпункт 6 пункту 13",
        "title_en": "Subparagraph 6 of paragraph 13",
        "description_uk": "Відмінено відкриті торги через неподання жодної тендерної пропозиції для участі у відкритих торгах у строк, установлений замовником згідно з цими особливостями, у тому числі за лотом. При цьому предмет закупівлі, його технічні, кількісні та якісні характеристики, проект договору про закупівлю, а також вимоги до суб’єкта, з яким укладається договір про закупівлю, не повинні відрізнятися від вимог, що були визначені замовником у тендерній документації (крім вимог, визначених пунктом 47 цих особливостей), та сума договору про закупівлю не може перевищувати очікувану вартість предмета закупівлі, зазначену замовником в оголошенні про проведення відкритих торгів, які відмінено через відсутність достатньої кількості учасників процедури закупівлі (учасника процедури закупівлі), з урахуванням прийнятного відсотка перевищення ціни тендерної пропозиції учасника процедури закупівлі над очікуваною вартістю предмета закупівлі, якщо такий прийнятний відсоток був зазначений у тендерній документації",
        "description_en": "Open tenders are canceled due to the failure to submit any tender proposals for participation in open tenders within the time limit set by the customer in accordance with these specifications, including for the lot. At the same time, the subject of the procurement, its technical, quantitative, and qualitative characteristics, the draft procurement contract, as well as the requirements for the entity with which the procurement contract is concluded, must not differ from the requirements specified by the customer in the tender documentation (except for the requirements specified in paragraph 47 of these special features), and the amount of the procurement contract may not exceed the expected value of the subject of procurement specified by the customer in the announcement of open tenders, which were canceled due to the lack of a sufficient number of participants in the procurement procedure (participants in the procurement procedure), taking into account the acceptable percentage by which the tender offer price of the participant in the procurement procedure exceeds the expected value of the procurement item, if such an acceptable percentage was specified in the tender documentation",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "combatArea": {
        "title_uk": "Підпункт 2 пункту 13",
        "title_en": "Subparagraph 2 of paragraph 13",
        "description_uk": "Замовник або його відокремлений підрозділ, що здійснює закупівлю згідно з абзацом другим пункту 15 цих особливостей, перебуває на території активних бойових дій, які не були завершені на дату укладення договору про закупівлю",
        "description_en": "The customer or its separate division that makes the purchase in accordance with the second paragraph of clause 15 of these special provisions is located in an area of active hostilities that had not ended on the date of conclusion of the purchase agreement",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "legalServices": {
        "title_uk": "Підпункт 9 пункту 13",
        "title_en": "Subparagraph 9 of paragraph 13",
        "description_uk": "Здійснюється закупівля послуг з адвокатської діяльності",
        "description_en": "Procurement of legal services is being carried out",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "sportEvents": {
        "title_uk": "Підпункт 11 пункту 13",
        "title_en": "Subparagraph 11 of paragraph 13",
        "description_uk": "Здійснюється закупівля послуг, необхідних для проведення спортивних заходів, спортивних змагань, заходів з фізичної культури і спорту, фізкультурно-спортивної реабілітації, що включені до Єдиного календарного плану фізкультурно-оздоровчих, спортивних заходів та спортивних змагань України на відповідний рік",
        "description_en": "Procurement of services necessary for holding sporting events, sports competitions, physical culture and sports events, physical culture and sports rehabilitation, which are included in the Unified Calendar Plan of Physical Culture and Health, Sports Events and Sports Competitions of Ukraine for the relevant year",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "criticalInfrastructure": {
        "title_uk": "Підпункт 13 пункту 13",
        "title_en": "Subparagraph 13 of paragraph 13",
        "description_uk": "Здійснюється закупівля товарів, робіт та послуг для/з будівництва, ремонту та інших інженерно-технічних заходів із захисту об’єктів критичної інфраструктури паливно-енергетичного сектору критичної інфраструктури",
        "description_en": "Procurement of goods, works, and services is being conducted for the construction, repair, and other engineering and technical measures aimed at protecting critical infrastructure facilities in the fuel and energy sector",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "civilProtection": {
        "title_uk": "Підпункт 15 пункту 13",
        "title_en": "Subparagraph 15 of paragraph 13",
        "description_uk": "Здійснюється закупівля товарів, робіт і послуг для проведення заходів, спрямованих на забезпечення захисту об’єктів підприємств, установ та організацій електроенергетичного, ядерно-промислового, вугільно-промислового, нафтогазового комплексів та об’єктів критичної інфраструктури підсектору залізничного транспорту сектору транспорту і пошти, у тому числі для організації захисту їх працівників у частині будівництва, створення та облаштування об’єктів фонду захисних споруд цивільного захисту, для відновлення зруйнованих або пошкоджених внаслідок збройної агресії Російської Федерації таких об’єктів, а також для проведення першочергових аварійно-відбудовних робіт на об’єктах залізничної інфраструктури та ремонту тягового і рухомого складу",
        "description_en": "Procurement of goods, works, and services is carried out for measures aimed at ensuring the protection of facilities belonging to enterprises, institutions, and organizations in the electric power, nuclear, coal, oil and gas industries, as well as critical infrastructure facilities in the railway transport subsector of the transport and postal sector, including for the organization of protection of their employees in terms of construction, creation, and arrangement of civil defense structures, for the restoration of such facilities destroyed or damaged as a result of the armed aggression of the Russian Federation, as well as for the implementation of priority emergency repair work on railway infrastructure facilities and the repair of traction and rolling stock",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "marketUnsuccessful": {
        "title_uk": "Підпункт 16 пункту 13",
        "title_en": "Subparagraph 16 of paragraph 13",
        "description_uk": 'Закупівля із застосуванням електронного каталогу не відбулася або в електронному каталозі відсутній необхідний замовнику товар, якщо така закупівля була проведена відповідно до пункту 5 розпорядження Кабінету Міністрів України від 25 вересня 2019 р. № 846 "Про визначення державної установи "Професійні закупівлі" централізованою закупівельною організацією" (Офіційний вісник України, 2019 р., № 77, ст. 2660) - із змінами, внесеними постановою Кабінету Міністрів України від 16 травня 2023 р. № 491',
        "description_en": 'The purchase using the electronic catalog did not take place or the product required by the customer is not available in the electronic catalog, if such a purchase was made in accordance with paragraph 5 of the Resolution of the Cabinet of Ministers of Ukraine dated September 25, 2019, No. 846 "On the determination of the state institution "Professional Procurement" as a centralized procurement organization" (Official Gazette of Ukraine, 2019, No. 77, p. 2660) - as amended by Resolution of the Cabinet of Ministers of Ukraine No. 491 dated May 16, 2023',
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "RNBO": {
        "title_uk": "Підпункт 17 пункту 13",
        "title_en": "Subparagraph 17 of paragraph 13",
        "description_uk": "Здійснюється закупівля програмного забезпечення, засобів зв’язку, пристроїв та засобів мережевої безпеки та інших засобів захисту технічної та інформаційної інфраструктури Апаратом Ради національної безпеки і оборони України для забезпечення функціонування та розвитку Головного ситуаційного центру України у разі, коли інформація, що повинна бути оприлюднена в оголошенні про проведення відкритих торгів та/або в тендерній документації, є інформацією з обмеженим доступом або коли її розголошення під час дії правового режиму воєнного стану може нести загрозу національній безпеці",
        "description_en": "The National Security and Defense Council of Ukraine is procuring software, communications equipment, network security devices and other means of protecting technical and information infrastructure to ensure the functioning and development of Ukraine's Main Situation Center in cases where the information that must be disclosed in the announcement of open tenders and/or in the tender documentation is restricted or when its disclosure during the legal regime of martial law may pose a threat to national security",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "insurance": {
        "title_uk": "Підпункт 19 пункту 13",
        "title_en": "Subparagraph 19 of paragraph 13",
        "description_uk": "Здійснюється закупівля послуг, пов’язаних із створенням або залученням фінансових інструментів, гарантій, кредитів або грантів, а також послуг, пов’язаних із створенням інструментів страхування, перестрахування та/або відшкодування збитків від воєнних ризиків торгових суден, задіяних у перевезенні українських експортних товарів, суден технічного флоту (спеціалізованих суден), на яких встановлені газопоршневі та/або газотурбінні установки, призначені для виробництва електричної енергії",
        "description_en": "Services related to the creation or attraction of financial instruments, guarantees, loans, or grants, as well as services related to the creation of insurance, reinsurance, and/or compensation instruments for military risks of merchant ships involved in the transportation of Ukrainian export goods, technical fleet vessels (specialized vessels) equipped with gas piston and/or gas turbine units designed for the production of electricity",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "inclusivity": {
        "title_uk": "Абзац 40 пункту 13",
        "title_en": "Paragraph 40 of paragraph 13",
        "description_uk": "Придбання замовниками товарів і послуг, вартість яких становить або перевищує 100 тис. гривень та є меншою, ніж 200 тис. гривень, може здійснюватися шляхом укладення договору про закупівлю без застосування відкритих торгів та/або електронного каталогу для закупівлі товару у разі, коли закупівля товарів і послуг здійснюється у підприємства або організації, що засновані громадською організацією осіб з інвалідністю та отримали дозвіл на право користування пільгами з оподаткування відповідно до законодавства",
        "description_en": "The purchase by customers of goods and services whose value is equal to or exceeds UAH 100,000 and is less than UAH 200,000 may be carried out by concluding a procurement contract without open bidding and/or an electronic catalog for the procurement of goods in cases where the procurement of goods and services is carried out from an enterprise or organization established by a public organization of persons with disabilities and authorized to use tax benefits in accordance with the law",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "missingPersonsSearch": {
        "title_uk": "Абзац 2 пункту 9",
        "title_en": "Paragraph 2 of Clause 9",
        "description_uk": "Публічні закупівлі для здійснення заходів щодо пошуку осіб, зниклих безвісти за особливих обставин, та репатріації і повернення зниклих безвісти (військових, цивільних), що проводяться Мінреінтеграції та державними підприємствами, що належать до сфери його управління, а саме непромокальних фартухів, одноразових комбінезонів, захисних окулярів, рукавичок, резинових чобіт, мішків для тіл (останків) загиблих, нош, простирадл, пластикових пакетів, які застібаються на блискавку, з поверхнею, на якій можна писати, картонних коробок для скелетованих останків, наборів для забору зразків ДНК (на основі паперових фільтрів FTA/Whatman), брезентів/пластикових плівок, мотузок, кабельних стяжок розміром обхвату кісточок гомілки, бірок для тіл (останків) загиблих та рефрижераторів, здійснюються без застосування процедур закупівель/спрощених закупівель, визначених Законом та цими особливостями",
        "description_en": "Public procurement for the implementation of measures to search for persons missing under special circumstances and the repatriation and return of missing persons (military and civilian) carried out by the Ministry of Reintegration and state-owned enterprises under its management, namely waterproof aprons, disposable coveralls, protective goggles, gloves, rubber boots, bags for bodies (remains) of the deceased, stretchers, sheets, plastic bags with zippers and a writable surface, cardboard boxes for skeletal remains, DNA sampling kits (based on FTA/Whatman paper filters), tarpaulins/plastic films, ropes, cable ties the size of the ankle bones, tags for bodies (remains) of the deceased, and refrigerators, are carried out without the use of procurement/simplified procurement procedures defined by the Law and these special features",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "DUS": {
        "title_uk": "Абзац 3 пункту 9",
        "title_en": "Paragraph 3 of clause 9",
        "description_uk": "Публічні закупівлі товарів, робіт і послуг для забезпечення виконання завдань, покладених на Державне управління справами, в умовах правового режиму воєнного стану за рахунок коштів резервного фонду Державного бюджету України розпорядниками (одержувачами) бюджетних коштів, а також закупівлі бензину та дизельного пального Управлінням державної охорони України здійснюються без застосування процедур закупівель/спрощених закупівель, визначених Законом та цими особливостями",
        "description_en": "Public procurement of goods, works, and services to ensure the fulfillment of tasks assigned to the State Administration of Affairs, under the legal regime of martial law at the expense of the reserve fund of the State Budget of Ukraine by administrators (recipients) of budget funds, as well as the procurement of gasoline and diesel fuel by the State Security Service of Ukraine, shall be carried out without applying the procurement/simplified procurement procedures defined by the Law and these special provisions",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "experimentalUnitNext": {
        "title_uk": "Абзац 8 пункту 9",
        "title_en": "Paragraph 8 of clause 9",
        "description_uk": 'Публічні закупівлі товарів, робіт і послуг, необхідних для забезпечення експериментального підрозділу NEXT відповідно до Порядку випробувань та досліджень спеціальних інноваційних технологій Фондом розвитку інновацій у період дії правового режиму воєнного стану, затвердженого постановою Кабінету Міністрів України від 22 жовтня 2025 р. № 1354 "Деякі питання розвитку спеціальних інноваційних технологій", здійснюються Фондом розвитку інновацій без застосування процедур закупівель/спрощених закупівель, визначених Законом та цими особливостями, з урахуванням положень пункту 7 зазначеного Порядку',
        "description_en": 'Public procurement of goods, works, and services necessary to ensure the operation of the NEXT experimental unit, in accordance with the Procedure for testing and research of special innovative technologies by the Innovation Development Fund during the period of the legal regime of martial law, approved by the Resolution of the Cabinet of Ministers of Ukraine dated October 22, 2025 No. 1354 "Some issues of the development of special innovative technologies", shall be carried out by the Innovation Development Fund without applying procurement procedures/simplified procurements defined by the Law and these specifics, taking into account the provisions of paragraph 7 of the said Procedure',
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "UZ": {
        "title_uk": "Підпункт 20 пункту 13",
        "title_en": "Subparagraph 20 of paragraph 13",
        "description_uk": 'Здійснюється закупівля товарів, необхідних для проведення ремонту та відновлення техніки, на виконання договору про спільну діяльність, стороною якого виступає АТ "Укрзалізниця" та укладеного з метою підвищення обороноздатності держави на період дії правового режиму воєнного стану в Україні',
        "description_en": "The purchase of goods necessary for the repair and restoration of equipment is being carried out in accordance with a joint activity agreement between JSC Ukrzaliznytsia and concluded with the aim of enhancing the state's defense capabilities for the duration of the legal regime of martial law in Ukraine",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "defencePurchase": {
        "title_uk": "Підпункт 21 пункту 13",
        "title_en": "Subparagraph 21 of paragraph 13",
        "description_uk": "Здійснюється закупівля товарів, робіт та послуг, необхідних для забезпечення будівництва військових інженерно-технічних і фортифікаційних споруд, виконання мобілізаційних завдань (замовлень), заходів, пов’язаних з підготовкою і виконанням завдань територіальної оборони, виконання договорів, що містять інформацію з обмеженим доступом, якщо така закупівля здійснюється для нагальних потреб Збройних Сил, інших військових формувань, правоохоронних органів, ДСНС, вищих військових навчальних закладів на їх запит з подальшою передачею таких товарів, робіт та послуг на облік запитувача. Запит Збройних Сил, інших військових формувань, правоохоронних органів, ДСНС, вищих військових навчальних закладів погоджується (затверджується) їх уповноваженою службовою (посадовою) особою та повинен містити обґрунтування нагальності потреби у здійсненні закупівлі відповідно до цього підпункту",
        "description_en": "Procurement of goods, works, and services necessary to ensure the construction of military engineering and fortification structures, the fulfillment of mobilization tasks (orders), measures related to the preparation and fulfillment of territorial defense tasks, the fulfillment of contracts containing restricted access information, if such procurement is carried out for the urgent needs of the Armed Forces, other military formations, law enforcement agencies, the State Emergency Service, higher military educational institutions at their request, with the subsequent transfer of such goods, works, and services to the requester's account. Requests from the Armed Forces, other military formations, law enforcement agencies, the State Emergency Service, and higher military educational institutions shall be agreed upon (approved) by their authorized official (official) and shall contain a justification of the urgency of the need for the procurement in accordance with this subparagraph",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "quick": {
        "title_uk": "Підпункт 4 пункту 13",
        "title_en": "Subparagraph 4 of paragraph 13",
        "description_uk": "Існує нагальна потреба у здійсненні закупівлі у зв’язку з виникненням об’єктивних обставин, що унеможливлюють дотримання замовником строків для проведення закупівлі із застосуванням відкритих торгів та/або електронного каталогу, яка повинна бути документально підтверджена замовником",
        "description_en": "There is an urgent need to make a purchase due to the emergence of objective circumstances that make it impossible for the customer to comply with the deadlines for conducting a purchase using open tenders and/or an electronic catalog, which must be documented by the customer",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "additionalPurchase": {
        "title_uk": "Підпункт 7 пункту 13",
        "title_en": "Subparagraph 7 of paragraph 13",
        "description_uk": "Після укладення договору про закупівлю у замовника виникла необхідність у постачанні додаткового обсягу товару тим самим постачальником, якщо в разі зміни постачальника замовник буде вимушений придбати товар з іншими технічними характеристиками, що призведе до виникнення несумісності, пов’язаної з експлуатацією і технічним обслуговуванням, або у разі, коли така закупівля зумовлена змінами до галузевих стандартів у сфері охорони здоров’я. Закупівля додаткового обсягу товару в того самого постачальника здійснюється протягом трьох років після укладення договору про закупівлю, якщо загальна вартість такого постачання не перевищує 50 відсотків ціни договору про закупівлю",
        "description_en": "After concluding the procurement contract, the customer needed to purchase additional goods from the same supplier, since changing suppliers would require purchasing goods with different technical characteristics, which would lead to incompatibility related to operation and maintenance, or if such a purchase is due to changes in industry standards in the field of healthcare. The purchase of additional goods from the same supplier is carried out within three years after the conclusion of the procurement contract, if the total cost of such a supply does not exceed 50 percent of the price of the procurement contract",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "additionalConstruction": {
        "title_uk": "Підпункт 8 пункту 13",
        "title_en": "Subparagraph 8 of paragraph 13",
        "description_uk": "У замовника після укладення договору про закупівлю виникла необхідність у закупівлі додаткових робіт чи послуг, пов’язаних з предметом закупівлі основного договору, в того самого виконавця робіт/надавача послуг. Можливість і умови виконання таких додаткових робіт чи надання послуг можуть бути передбачені в основному договорі про закупівлю, укладеному за результатами проведення закупівлі. Закупівля додаткових робіт чи послуг у того самого виконавця робіт/надавача послуг здійснюється протягом трьох років після укладення договору про закупівлю, якщо загальна вартість таких робіт чи послуг не перевищує 50 відсотків ціни основного договору про закупівлю, укладеного за результатами проведення закупівлі",
        "description_en": "After concluding the procurement contract, the customer needed to purchase additional works or services related to the subject of the main contract from the same contractor/service provider. The possibility and conditions for performing such additional works or providing services may be provided for in the main procurement contract concluded based on the results of the procurement. The procurement of additional works or services from the same contractor/service provider shall be carried out within three years after the conclusion of the procurement contract, if the total cost of such works or services does not exceed 50 percent of the price of the main procurement contract concluded as a result of the procurement",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "stateLegalServices": {
        "title_uk": "Підпункт 10 пункту 13",
        "title_en": "Subparagraph 10 of paragraph 13",
        "description_uk": "Здійснюється закупівля юридичних послуг, пов’язаних із захистом прав та інтересів України, у тому числі з метою захисту національної безпеки і оборони, під час врегулювання спорів, розгляду в закордонних юрисдикційних органах справ за участю іноземного суб’єкта та України",
        "description_en": "Legal services related to the protection of Ukraine's rights and interests, including for the purpose of protecting national security and defense, are procured during the settlement of disputes and the consideration of cases involving foreign entities and Ukraine in foreign jurisdictions",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "artPurchase": {
        "title_uk": "Абзац 2 підпункту 5 пункту 13",
        "title_en": "Paragraph 2, subparagraph 5, clause 13",
        "description_uk": "Предмет закупівлі полягає у створенні або придбанні витвору мистецтва або художнього виконання",
        "description_en": "The subject of the procurement is the creation or acquisition of a work of art or artistic performance",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "contestWinner": {
        "title_uk": "Абзац 3 підпункту 5 пункту 13",
        "title_en": "Paragraph 3, subparagraph 5, clause 13",
        "description_uk": "Укладення договору про закупівлю з переможцем архітектурного або мистецького конкурсу",
        "description_en": "Conclusion of a procurement contract with the winner of an architectural or art competition",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "technicalReasons": {
        "title_uk": "Абзац 4 підпункту 5 пункту 13",
        "title_en": "Paragraph 4, subparagraph 5, clause 13",
        "description_uk": "Відсутність конкуренції з технічних причин, яка повинна бути документально підтверджена замовником",
        "description_en": "Absence of competition for technical reasons, which must be documented by the customer",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "intProperty": {
        "title_uk": "Абзац 5 підпункту 5 пункту 13",
        "title_en": "Paragraph 5, subparagraph 5, clause 13",
        "description_uk": "Необхідність захисту прав інтелектуальної власності",
        "description_en": "The need to protect intellectual property rights",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "hematopoieticStemCells": {
        "title_uk": "Пункт 21 частини 5 статті 3",
        "title_en": "Clause 21, Part 5, Article 3",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19/ed20251031#n823",
        "description_uk": "Гемопоетичні стовбурові клітини, роботи та послуги, що пов’язані з їх придбанням. За результатами такої закупівлі в електронній системі закупівлі замовник оприлюднює звіт про договір про закупівлю, укладений без використання електронної системи закупівлі",
        "description_en": "Hematopoietic stem cells, works, and services related to their acquisition. Based on the results of such a purchase in the electronic procurement system, the customer publishes a report on the procurement contract concluded without using the electronic procurement system",
        "scheme": "LAW922",
        "archive": False,
    },
    "lastHope": {
        "title_uk": "Абзац 6 підпункту 5 пункту 13",
        "title_en": "Paragraph 6, subparagraph 5, clause 13",
        "description_uk": 'Укладення договору про закупівлю з постачальником "останньої надії" або з постачальником універсальної послуги на постачання електричної енергії або природного газу',
        "description_en": 'Conclusion of a procurement contract with a "last resort" supplier or with a universal service provider for the supply of electricity or natural gas',
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "gasInstallations": {
        "title_uk": "Підпункт 25 пункту 13",
        "title_en": "Subparagraph 25 of paragraph 13",
        "description_uk": "Здійснюється закупівля суб’єктами ринку природного газу компресорних, газопоршневих та/або газотурбінних газоперекачувальних установок, у тому числі таких, що були у користуванні, а також послуг, необхідних для проведення їх оцінки. При цьому закупівля установок, що були у користуванні, проводиться за ціною, яка не перевищує їх вартість, визначену на підставі висновку експерта (експертного дослідження) або звіту про оцінку майна",
        "description_en": "Natural gas market participants purchase compressor, gas piston, and/or gas turbine gas pumping units, including those that have been in use, as well as the services necessary for their assessment. At the same time, the purchase of used units is carried out at a price that does not exceed their value, determined on the basis of an expert opinion (expert study) or a property appraisal report",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "stateDebtServices": {
        "title_uk": "Підпункт 26 пункту 13",
        "title_en": "Subparagraph 26 of paragraph 13",
        "description_uk": "Здійснюється закупівля юридичною особою, єдиним учасником (засновником) якої є держава, до 17 лютого 2026 р. послуг, необхідних для здійснення управління боргом, залучення, обслуговування і погашення запозичень, вчинення правочинів з борговими зобов’язаннями, що виникли внаслідок залучення запозичень з міжнародного ринку капіталу через інструменти кредитування, розміщення іноземних боргових цінних паперів на іноземній фондовій біржі, у тому числі шляхом обміну, випуску, купівлі, викупу та продажу боргових зобов’язань",
        "description_en": "Purchases are made by a legal entity whose sole participant (founder) is the state, until February 17, 2026 services necessary for debt management, borrowing, servicing and repayment of borrowings, performing legal acts with debt obligations arising from borrowing on the international capital market through lending instruments, placing foreign debt securities on a foreign stock exchange, including through exchange, issue, purchase, redemption, and sale of debt obligations",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "stateSupportForChildren": {
        "title_uk": "Підпункт 27 пункту 13",
        "title_en": "Subparagraph 27 of paragraph 13",
        "description_uk": "Здійснюється до 1 березня 2026 р. закупівля товарів, робіт та послуг, необхідних для надання державної підтримки, визначеної підпунктом 7 пункту 2 додатка 1 до Порядку використання коштів державного фонду декарбонізації та енергоефективної трансформації, затвердженого постановою Кабінету Міністрів України від 21 червня 2024 р. № 761 (Офіційний вісник України, 2024 р., № 63, ст. 3747), а саме закупівля та доставка для задоволення потреб дітей з інвалідністю підгрупи А портативних зарядних станцій орієнтовною ємністю 2 кВт•год",
        "description_en": "The procurement of goods, works, and services necessary for the provision of state support, as defined in subparagraph 7 of paragraph 2 of Appendix 1 to the Procedure for the Use of Funds from the State Fund for Decarbonization and Energy Efficiency Transformation, approved by Resolution of the Cabinet of Ministers of Ukraine No. 761 dated June 21, 2024 (Official Gazette of Ukraine, 2024, No. 63, p. 3747), namely the procurement and delivery of goods, works, and services necessary to meet the needs of children with disabilities, shall be carried out until March 1, 2026. No. 761 (Official Gazette of Ukraine, 2024, No. 63, p. 3747), namely the purchase and delivery of portable charging stations with an approximate capacity of 2 kWh to meet the needs of children with disabilities in subgroup A",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": True,
    },
    "energyCrisisRecovery": {
        "title_uk": "Підпункт 28 пункту 13",
        "title_en": "Subparagraph 28 of paragraph 13",
        "description_uk": "Здійснюється до 31 грудня 2026 р. закупівля парових турбін, газопоршневих установок, когенераційних установок, електрогенераторних установок, газових генераторів, газотурбінних установок та блочно-модульних котелень, теплових насосів, парових котлів, мобільних котелень, дизельних генераторів, зокрема складових та комплектуючих такого обладнання, силових трансформаторів, автотрансформаторів, трансформаторів тока, трансформаторів напруги, необхідних для подолання наслідків надзвичайної ситуації державного рівня в електроенергетичних системах",
        "description_en": "The purchase of steam turbines, gas piston units, cogeneration units, electric generator units, gas generators, gas turbine units, and modular boiler rooms, heat pumps, steam boilers, mobile boiler rooms, diesel generators, including components and accessories for such equipment, power transformers, autotransformers, current transformers, voltage transformers, necessary to overcome the consequences of a state-level emergency in the electric power systems",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "cancellationOfAboveThreshold": {
        "title_uk": "Пункт 86",
        "title_en": "Paragraph 86",
        "description_uk": "У разі коли відкриті торги, проведені відповідно до пункту 85 цих особливостей, було відмінено у зв’язку з неподанням жодної тендерної пропозиції для участі у відкритих торгах у строк, установлений замовником згідно з цими особливостями, придбання товарів, робіт і послуг може здійснюватися шляхом укладення договору про закупівлю без застосування відкритих торгів та/або електронного каталогу для закупівлі товару",
        "description_en": "Where open tendering procedures conducted in accordance with paragraph 85 of these Special Rules were cancelled due to the absence of any submitted tender proposals within the deadline set by the contracting authority, the procurement of goods, works, or services may be carried out by concluding a procurement contract without applying open tendering procedures and/or the electronic catalogue",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "cancellationOfPriceQuatation": {
        "title_uk": "Пункт 89",
        "title_en": "Paragraph 89",
        "description_uk": "Якщо запит пропозицій постачальників, проведений відповідно до пункту 88 цих особливостей, не відбувся у зв’язку з тим, що не було подано жодної ціни пропозиції, в такому випадку замовник може здійснити закупівлю шляхом укладення договору про закупівлю без застосування відкритих торгів та/або електронного каталогу для закупівлі товару та без застосування умов, передбачених пунктами 78 і 79 цих особливостей",
        "description_en": "If the request for proposals from suppliers, conducted in accordance with paragraph 88 of these specifications, did not take place due to the fact that no bid prices were submitted, in such a case, the customer may make a purchase by concluding a purchase agreement without applying open bidding and/or an electronic catalog for the purchase of goods and without applying the conditions provided for in paragraphs 78 and 79 of these specifications",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
    "reportingEligibilityException": {
        "title_uk": "Пункт 91",
        "title_en": "Paragraph 91",
        "description_uk": "Якщо під час закупівлі без застосування електронної системи закупівель відповідно до абзацу третього пункту 80 цих особливостей замовник не може виконати умови, визначені пунктами 78 або 79 цих особливостей, у такому випадку він здійснює таку закупівлю шляхом укладення договору про закупівлю без застосування електронної системи закупівель та без застосування умов, передбачених пунктами 78 і 79 цих особливостей",
        "description_en": "If, during procurement without the use of an electronic procurement system in accordance with the third paragraph of clause 80 of these special provisions, the customer is unable to fulfill the conditions specified in clauses 78 or 79 of these special provisions, in such a case, it shall carry out such procurement by concluding a procurement contract without using an electronic procurement system and without applying the conditions provided for in clauses 78 and 79 of these special provisions",
        "uri": "https://zakon.rada.gov.ua/laws/show/1178-2022-%D0%BF#n426",
        "scheme": "DECREE1178",
        "archive": False,
    },
}

PROCUREMENT_METHOD_TYPE_TO_FROZEN_CAUSE_DETAILS_MAPPING_ALL = {
    "reporting": FROZEN_CAUSE_DETAILS_REPORTING_ALL,
    "negotiation": FROZEN_CAUSE_DETAILS_NEGOTIATION_ALL,
    "negotiation.quick": FROZEN_CAUSE_DETAILS_NEGOTIATION_QUICK_ALL,
}
