POST /api/2.5/tenders/4b4ed03227c24f43b34f74183e3e0ca2/awards/995688bcf2a34c3db7650bb4693f0d8b/complaints/1739ae89d2cb4ef4b8c6c4db5ffc33ed/posts?acc_token=5aa2f8da0ab14a84bd8ce0d2f0b312c6 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Додано документ",
    "recipient": "aboveThresholdReviewers",
    "relatedPost": "e83d21fddc2247a990873ece59953c30",
    "documents": [
      {
        "title": "post_document_complaint.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ec7114e7cd2e43fdb1cbd02110225483?Signature=H0G8V%2FwNafpKNyvaXI%2FF2Bow6qZ%2BH%2FH5ThOfLGTCzI3vf1LwKfV0B%2BKVL6CxNRr%2FMitHMVmjYSIzkPMgRBb%2FCQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4b4ed03227c24f43b34f74183e3e0ca2/awards/995688bcf2a34c3db7650bb4693f0d8b/complaints/1739ae89d2cb4ef4b8c6c4db5ffc33ed/posts/96052263aedf435d868491247555ae81

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Додано документ",
    "documents": [
      {
        "confidentiality": "public",
        "hash": "md5:00000000000000000000000000000000",
        "title": "post_document_complaint.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ec7114e7cd2e43fdb1cbd02110225483?Signature=5zh6zYWRm0kr%2BlcCa%2FtPoc2NOWTCv43ArLgW%2BF%2FNZ6MwZddRhfNVH%2Bw05gfdTpugTwPghfUfqfGZKaqqFcuKAA%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "756b9b8dc5924908b66eab79264a5e35",
        "datePublished": "2023-10-10T01:00:03+03:00",
        "dateModified": "2023-10-10T01:00:03+03:00",
        "author": "complaint_owner"
      }
    ],
    "recipient": "aboveThresholdReviewers",
    "relatedPost": "e83d21fddc2247a990873ece59953c30",
    "id": "96052263aedf435d868491247555ae81",
    "datePublished": "2023-10-10T01:00:03+03:00",
    "author": "complaint_owner"
  }
}

