PATCH /api/2.5/tenders/4b4ed03227c24f43b34f74183e3e0ca2/awards/b2df0a3f487a401987b1cdf1170a93be?acc_token=5a55c72486d8489d95277757843eee3c HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "cancelled"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4b4ed03227c24f43b34f74183e3e0ca2/awards/22538da636d84b5b88ad4598942e3823

{
  "data": {
    "id": "b2df0a3f487a401987b1cdf1170a93be",
    "status": "cancelled",
    "date": "2023-10-10T01:00:03+03:00",
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "suppliers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro"
      }
    ],
    "bid_id": "c938a8780db146beaba184a25937b356",
    "lotID": "c94486b261084c09ac0c731b74d35c85",
    "complaintPeriod": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2023-10-10T01:00:03+03:00"
    },
    "documents": [
      {
        "confidentiality": "public",
        "documentType": "notice",
        "id": "3a3cec0135c941368e2555478368edbd",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "sign.p7s",
        "format": "sign/pkcs7-signature",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/47e460a9bd464a1d9c3f4145b7d055c7?Signature=G6TNHFcKK%2FgpgxkX%2FgaAiFWQ9DTj%2B%2ByIEMWx8n4VkRV7o0YOIUvcC7KooLwYlnNrS6eW3WR0Ictfg3COKwBbCQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:00:00+03:00",
        "author": "tender_owner",
        "language": "uk"
      }
    ],
    "period": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2023-10-18T00:00:00+03:00"
    },
    "qualified": true,
    "complaints": [
      {
        "id": "c823c3c9df2e45f1a4bcc72a8e1c5639",
        "complaintID": "UA-2023-10-10-000001-a.2",
        "date": "2023-10-10T01:00:03+03:00",
        "status": "resolved",
        "documents": [
          {
            "confidentiality": "public",
            "id": "84a2f466856343b8b33f0ec524c2321a",
            "datePublished": "2023-10-10T01:00:03+03:00",
            "hash": "md5:00000000000000000000000000000000",
            "title": "Complaint_Attachment.pdf",
            "format": "application/pdf",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4a2c835c20234675996acdb75895c85d?Signature=iHxmOhpjYq6HoLfeXXW9NG0%2Bj8YcKzwiehIwB6tN80u9XbtRgHkyE0rU82W0sRHgSnMD%2BE1lqCGU%2F%2BdGqAHlAA%3D%3D&KeyID=a8968c46",
            "documentOf": "tender",
            "dateModified": "2023-10-10T01:00:03+03:00",
            "author": "complaint_owner",
            "language": "uk"
          },
          {
            "confidentiality": "public",
            "id": "9b91b7d75ce2407f8014e694aa811bbb",
            "datePublished": "2023-10-10T01:00:03+03:00",
            "hash": "md5:00000000000000000000000000000000",
            "title": "ComplaintResolution.pdf",
            "format": "application/pdf",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/387779db79c3467fa8b929a750b5dbc6?Signature=%2B61%2FzHlwM2Do1rNjoS4OBZ2LnROIdHfx8JQuqiiwO%2FJNdUgC7MihOoc4rOQr7yJi7Ik%2BME2t4mPeEsuBYZRKCg%3D%3D&KeyID=a8968c46",
            "documentOf": "tender",
            "dateModified": "2023-10-10T01:00:03+03:00",
            "author": "aboveThresholdReviewers",
            "language": "uk"
          }
        ],
        "type": "complaint",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356",
        "author": {
          "name": "ДКП «Школяр»",
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          },
          "identifier": {
            "scheme": "UA-EDR",
            "uri": "http://www.sc.gov.ua/",
            "id": "00137256",
            "legalName": "ДКП «Школяр»"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "dateSubmitted": "2023-10-10T01:00:03+03:00",
        "objections": [
          {
            "id": "d2655b362ffe473ab4a214915da867c4",
            "title": "My objection",
            "description": "Test objection",
            "relatesTo": "award",
            "relatedItem": "46b5dff235cc48fb952fae6c72243c12",
            "classification": {
              "scheme": "violation_amcu",
              "id": "corruptionDescription",
              "description": "test classification"
            },
            "requestedRemedies": [
              {
                "id": "7e1fc95dcab744609f07130f17ebb65c",
                "type": "setAsideAward",
                "description": "test"
              }
            ],
            "arguments": [
              {
                "id": "be3f89d2bd3447bf9d1c50879468a42e",
                "description": "test argument"
              }
            ],
            "sequenceNumber": 1
          }
        ],
        "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно",
        "dateDecision": "2023-10-10T01:00:03+03:00",
        "acceptance": true,
        "dateAccepted": "2023-10-10T01:00:03+03:00",
        "reviewDate": "2023-10-10T01:00:03+03:00",
        "reviewPlace": "Place of review",
        "value": {
          "amount": 3000.0,
          "currency": "UAH"
        },
        "tendererActionDate": "2023-10-10T01:00:03+03:00"
      },
      {
        "id": "de1c41400ca748f591a6f43a39c7f2d8",
        "complaintID": "UA-2023-10-10-000001-a.3",
        "date": "2023-10-10T01:00:03+03:00",
        "status": "invalid",
        "type": "complaint",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356",
        "author": {
          "name": "ДКП «Школяр»",
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          },
          "identifier": {
            "scheme": "UA-EDR",
            "uri": "http://www.sc.gov.ua/",
            "id": "00137256",
            "legalName": "ДКП «Школяр»"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "dateSubmitted": "2023-10-10T01:00:03+03:00",
        "objections": [
          {
            "id": "f973452c0c2e4fbbb3051c7280b708a7",
            "title": "My objection",
            "description": "Test objection",
            "relatesTo": "award",
            "relatedItem": "46b5dff235cc48fb952fae6c72243c12",
            "classification": {
              "scheme": "violation_amcu",
              "id": "corruptionDescription",
              "description": "test classification"
            },
            "requestedRemedies": [
              {
                "id": "144f7dca4ab643709025e58f80ea5d17",
                "type": "setAsideAward",
                "description": "test"
              }
            ],
            "arguments": [
              {
                "id": "a50cce6ae63541fcad56986f13a79558",
                "description": "test argument"
              }
            ],
            "sequenceNumber": 1
          }
        ],
        "value": {
          "amount": 3000.0,
          "currency": "UAH"
        },
        "rejectReason": "alreadyExists",
        "dateDecision": "2023-10-10T01:00:03+03:00",
        "acceptance": false
      },
      {
        "id": "d58f559d160e45ceb91449d5adc67264",
        "complaintID": "UA-2023-10-10-000001-a.4",
        "date": "2023-10-10T01:00:03+03:00",
        "status": "declined",
        "type": "complaint",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356",
        "author": {
          "name": "ДКП «Школяр»",
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          },
          "identifier": {
            "scheme": "UA-EDR",
            "uri": "http://www.sc.gov.ua/",
            "id": "00137256",
            "legalName": "ДКП «Школяр»"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "dateSubmitted": "2023-10-10T01:00:03+03:00",
        "objections": [
          {
            "id": "388965a9e9044ae8bbce0f211ec91e90",
            "title": "My objection",
            "description": "Test objection",
            "relatesTo": "award",
            "relatedItem": "46b5dff235cc48fb952fae6c72243c12",
            "classification": {
              "scheme": "violation_amcu",
              "id": "corruptionDescription",
              "description": "test classification"
            },
            "requestedRemedies": [
              {
                "id": "13265495eb6841de85412bb1e4e871b4",
                "type": "setAsideAward",
                "description": "test"
              }
            ],
            "arguments": [
              {
                "id": "3de8a89f76ad442187b5369500108ab5",
                "description": "test argument"
              }
            ],
            "sequenceNumber": 1
          }
        ],
        "acceptance": true,
        "dateAccepted": "2023-10-10T01:00:03+03:00",
        "reviewDate": "2023-10-10T01:00:03+03:00",
        "reviewPlace": "Place of review",
        "value": {
          "amount": 3000.0,
          "currency": "UAH"
        },
        "dateDecision": "2023-10-10T01:00:03+03:00"
      },
      {
        "id": "c1b03223839a436e97c9aa8a3987c85e",
        "complaintID": "UA-2023-10-10-000001-a.5",
        "date": "2023-10-10T01:00:03+03:00",
        "status": "declined",
        "type": "complaint",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356",
        "author": {
          "name": "ДКП «Школяр»",
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          },
          "identifier": {
            "scheme": "UA-EDR",
            "uri": "http://www.sc.gov.ua/",
            "id": "00137256",
            "legalName": "ДКП «Школяр»"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "dateSubmitted": "2023-10-10T01:00:03+03:00",
        "objections": [
          {
            "id": "9a5c3a22375749cfbc1db119b9cf200b",
            "title": "My objection",
            "description": "Test objection",
            "relatesTo": "award",
            "relatedItem": "46b5dff235cc48fb952fae6c72243c12",
            "classification": {
              "scheme": "violation_amcu",
              "id": "corruptionDescription",
              "description": "test classification"
            },
            "requestedRemedies": [
              {
                "id": "f940f7062f494a8a8a10dc121edae2df",
                "type": "setAsideAward",
                "description": "test"
              }
            ],
            "arguments": [
              {
                "id": "897cc08bafa44401ac63933b97820693",
                "description": "test argument"
              }
            ],
            "sequenceNumber": 1
          }
        ],
        "acceptance": true,
        "dateAccepted": "2023-10-10T01:00:03+03:00",
        "reviewDate": "2023-10-10T01:00:03+03:00",
        "reviewPlace": "Place of review",
        "value": {
          "amount": 3000.0,
          "currency": "UAH"
        },
        "rejectReason": "tenderCancelled",
        "dateDecision": "2023-10-10T01:00:03+03:00"
      },
      {
        "id": "19276d51ed8e45bc9a79d274428918e0",
        "complaintID": "UA-2023-10-10-000001-a.6",
        "date": "2023-10-10T01:00:03+03:00",
        "status": "stopped",
        "type": "complaint",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356",
        "author": {
          "name": "ДКП «Школяр»",
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          },
          "identifier": {
            "scheme": "UA-EDR",
            "uri": "http://www.sc.gov.ua/",
            "id": "00137256",
            "legalName": "ДКП «Школяр»"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "dateSubmitted": "2023-10-10T01:00:03+03:00",
        "objections": [
          {
            "id": "036eb82d4399412795be618a78a23a54",
            "title": "My objection",
            "description": "Test objection",
            "relatesTo": "award",
            "relatedItem": "46b5dff235cc48fb952fae6c72243c12",
            "classification": {
              "scheme": "violation_amcu",
              "id": "corruptionDescription",
              "description": "test classification"
            },
            "requestedRemedies": [
              {
                "id": "0ff7e41f09474aa5a04474cb43e64c65",
                "type": "setAsideAward",
                "description": "test"
              }
            ],
            "arguments": [
              {
                "id": "3bb3a91c2484482c9e77be70bf6d68a3",
                "description": "test argument"
              }
            ],
            "sequenceNumber": 1
          }
        ],
        "decision": "Тендер скасовується замовником",
        "acceptance": true,
        "dateAccepted": "2023-10-10T01:00:03+03:00",
        "reviewDate": "2023-10-10T01:00:03+03:00",
        "reviewPlace": "Place of review",
        "value": {
          "amount": 3000.0,
          "currency": "UAH"
        },
        "rejectReason": "tenderCancelled",
        "dateDecision": "2023-10-10T01:00:03+03:00",
        "dateCanceled": "2023-10-10T01:00:03+03:00"
      },
      {
        "id": "6247c0279a314abe80d537174ab4750d",
        "complaintID": "UA-2023-10-10-000001-a.7",
        "date": "2023-10-10T01:00:03+03:00",
        "author": {
          "name": "ДКП «Школяр»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137256",
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "status": "answered",
        "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно",
        "resolutionType": "resolved",
        "dateAnswered": "2023-10-10T01:00:03+03:00",
        "dateSubmitted": "2023-10-10T01:00:03+03:00",
        "satisfied": true,
        "type": "claim",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356"
      },
      {
        "id": "80ca194ae2b94a51bac224454b75dfac",
        "complaintID": "UA-2023-10-10-000001-a.8",
        "date": "2023-10-10T01:00:03+03:00",
        "author": {
          "name": "ДКП «Школяр»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137256",
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "status": "answered",
        "resolution": "Вимога не відповідає предмету закупівлі",
        "resolutionType": "invalid",
        "dateAnswered": "2023-10-10T01:00:03+03:00",
        "dateSubmitted": "2023-10-10T01:00:03+03:00",
        "satisfied": false,
        "type": "claim",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356"
      },
      {
        "id": "1739ae89d2cb4ef4b8c6c4db5ffc33ed",
        "complaintID": "UA-2023-10-10-000001-a.9",
        "date": "2023-10-10T01:00:03+03:00",
        "status": "pending",
        "type": "complaint",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356",
        "author": {
          "name": "ДКП «Школяр»",
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          },
          "identifier": {
            "scheme": "UA-EDR",
            "uri": "http://www.sc.gov.ua/",
            "id": "00137256",
            "legalName": "ДКП «Школяр»"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "objections": [
          {
            "id": "6422d924c59b440c8ae4b5b11227e0ed",
            "title": "My objection",
            "description": "Test objection",
            "relatesTo": "award",
            "relatedItem": "46b5dff235cc48fb952fae6c72243c12",
            "classification": {
              "scheme": "violation_amcu",
              "id": "corruptionDescription",
              "description": "test classification"
            },
            "requestedRemedies": [
              {
                "id": "41881fd7fc064bfda4f2b94bba36ff35",
                "type": "setAsideAward",
                "description": "test"
              }
            ],
            "arguments": [
              {
                "id": "10aa1fae75794d02a42518c4c19d11d4",
                "description": "test argument"
              }
            ],
            "sequenceNumber": 1
          }
        ],
        "value": {
          "amount": 3000.0,
          "currency": "UAH"
        },
        "dateSubmitted": "2023-10-10T01:00:03+03:00",
        "posts": [
          {
            "title": "Уточнення по вимозі",
            "description": "Відсутній документ",
            "recipient": "complaint_owner",
            "relatedObjection": "6422d924c59b440c8ae4b5b11227e0ed",
            "id": "e83d21fddc2247a990873ece59953c30",
            "datePublished": "2023-10-10T01:00:03+03:00",
            "author": "aboveThresholdReviewers"
          },
          {
            "title": "Уточнення по вимозі",
            "description": "Додано документ",
            "documents": [
              {
                "confidentiality": "public",
                "hash": "md5:00000000000000000000000000000000",
                "title": "post_document_complaint.pdf",
                "format": "application/pdf",
                "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ec7114e7cd2e43fdb1cbd02110225483?Signature=5zh6zYWRm0kr%2BlcCa%2FtPoc2NOWTCv43ArLgW%2BF%2FNZ6MwZddRhfNVH%2Bw05gfdTpugTwPghfUfqfGZKaqqFcuKAA%3D%3D&KeyID=a8968c46",
                "documentOf": "tender",
                "language": "uk",
                "id": "287752d37a9a4459b3af40ffac65138c",
                "datePublished": "2023-10-10T01:00:03+03:00",
                "dateModified": "2023-10-10T01:00:03+03:00",
                "author": "complaint_owner"
              }
            ],
            "recipient": "aboveThresholdReviewers",
            "relatedPost": "e83d21fddc2247a990873ece59953c30",
            "relatedObjection": "6422d924c59b440c8ae4b5b11227e0ed",
            "id": "96052263aedf435d868491247555ae81",
            "datePublished": "2023-10-10T01:00:03+03:00",
            "author": "complaint_owner"
          },
          {
            "title": "Уточнення по вимозі",
            "description": "Відсутній документ",
            "recipient": "tender_owner",
            "relatedObjection": "6422d924c59b440c8ae4b5b11227e0ed",
            "id": "97d2f492ca5a44838affa1aeaab1076a",
            "datePublished": "2023-10-10T01:00:03+03:00",
            "author": "aboveThresholdReviewers"
          },
          {
            "title": "Уточнення по вимозі",
            "description": "Додано документ",
            "documents": [
              {
                "confidentiality": "public",
                "hash": "md5:00000000000000000000000000000000",
                "title": "post_document_tender.pdf",
                "format": "application/pdf",
                "url": "http://public-docs-sandbox.prozorro.gov.ua/get/faa222792cc44a93855e079e194d6eb6?Signature=4eO%2Fb%2B793LuLZpNP%2FLKPWbFkQkTLyKxpb2BqW83vGZdBPFho1pFqafwGYFJ8mhOebOLthrk8vTgLuVKaD4%2BrCg%3D%3D&KeyID=a8968c46",
                "documentOf": "tender",
                "language": "uk",
                "id": "e794daf5534e4d90b38d3d0dfbc4e18b",
                "datePublished": "2023-10-10T01:00:03+03:00",
                "dateModified": "2023-10-10T01:00:03+03:00",
                "author": "tender_owner"
              }
            ],
            "recipient": "aboveThresholdReviewers",
            "relatedPost": "97d2f492ca5a44838affa1aeaab1076a",
            "relatedObjection": "6422d924c59b440c8ae4b5b11227e0ed",
            "id": "2b40f4fd5f284473afad74cc7104b353",
            "datePublished": "2023-10-10T01:00:03+03:00",
            "author": "tender_owner"
          },
          {
            "title": "Пояснення до скарги",
            "description": "Була така необхідність",
            "relatedObjection": "6422d924c59b440c8ae4b5b11227e0ed",
            "id": "dbef3aa1d3064b8e9ec6ccefbb758c6a",
            "datePublished": "2023-10-10T01:00:03+03:00",
            "author": "tender_owner"
          }
        ]
      },
      {
        "id": "c3b46e2364504e909d2c67d3c6c50002",
        "complaintID": "UA-2023-10-10-000001-a.10",
        "date": "2023-10-10T01:00:03+03:00",
        "author": {
          "name": "ДКП «Школяр»",
          "identifier": {
            "scheme": "UA-EDR",
            "id": "00137256",
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
            "uri": "http://www.sc.gov.ua/"
          },
          "address": {
            "streetAddress": "вул. Островського, 33",
            "locality": "м. Вінниця",
            "region": "Вінницька область",
            "postalCode": "21100",
            "countryName": "Україна"
          },
          "contactPoint": {
            "name": "Сергій Олексюк",
            "email": "soleksuk@gmail.com",
            "telephone": "+380432216930"
          }
        },
        "title": "Недостатньо інформації",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
        "status": "claim",
        "type": "claim",
        "relatedLot": "c94486b261084c09ac0c731b74d35c85",
        "bid_id": "c938a8780db146beaba184a25937b356",
        "dateSubmitted": "2023-10-10T01:00:03+03:00"
      }
    ],
    "eligible": true
  }
}

