POST /api/2.5/tenders/0f776099eb8344b4a149200a8657a9df/awards/91ac65b9beb54606b75e117055a42ea4/complaints/42502fe8be604f908ba3527512f009cd/posts?acc_token=96bfac0a1ca0404cb31ad0d21207b764 HTTP/1.0
Authorization: Bearer broker
Content-Length: 668
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Додано документ",
    "recipient": "aboveThresholdReviewers",
    "relatedPost": "e9840eb79ef84f1fb249f049aaf89bfd",
    "documents": [
      {
        "title": "post_document_complaint.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1faeecd6b10d4e23a716730ee30d2778?Signature=4rsULtYSKSjXnrUw8B%2B7ALEO2UAyIwD50IFP97jKs%2BaIDRP25bnx0FnWkUcOCjDLh5JkzhCUBNAzYBVTzhpYAg%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0f776099eb8344b4a149200a8657a9df/awards/91ac65b9beb54606b75e117055a42ea4/complaints/42502fe8be604f908ba3527512f009cd/posts/2397f32026ad46b1af0c7cf6b6cf86b5

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Додано документ",
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "post_document_complaint.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1faeecd6b10d4e23a716730ee30d2778?Signature=Z10%2FC9W1hXiOGU1rT7UXOaQz85H1iXWKoK1JUwLUWQIL73NXj3hNj8jut1cK90gxe0usAHEBMjRMg1BZwQfoAQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "c24477d3b0e0456686574292c04e221b",
        "datePublished": "2023-01-01T00:00:03+02:00",
        "dateModified": "2023-01-01T00:00:03+02:00",
        "author": "complaint_owner"
      }
    ],
    "recipient": "aboveThresholdReviewers",
    "relatedPost": "e9840eb79ef84f1fb249f049aaf89bfd",
    "id": "2397f32026ad46b1af0c7cf6b6cf86b5",
    "datePublished": "2023-01-01T00:00:03+02:00",
    "author": "complaint_owner"
  }
}

