POST /api/2.5/tenders/4b4ed03227c24f43b34f74183e3e0ca2/awards/22538da636d84b5b88ad4598942e3823/complaints?acc_token=bcba1aa2011b40feb8e6c3ae4bd4fc35 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "title": "Недостатньо інформації",
    "status": "draft",
    "type": "complaint",
    "author": {
      "address": {
        "countryName": "Україна",
        "locality": "м. Вінниця",
        "postalCode": "21100",
        "region": "Вінницька область",
        "streetAddress": "вул. Островського, 33"
      },
      "contactPoint": {
        "email": "soleksuk@gmail.com",
        "name": "Сергій Олексюк",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "legalName": "ДКП «Школяр»",
        "id": "00137256",
        "uri": "http://www.sc.gov.ua/"
      },
      "name": "ДКП «Школяр»"
    },
    "objections": [
      {
        "title": "My objection",
        "description": "Test objection",
        "relatesTo": "award",
        "relatedItem": "8850d78aa8a94c148d6d245907f40d3e",
        "classification": {
          "scheme": "violation_amcu",
          "id": "corruptionDescription",
          "description": "test classification"
        },
        "requestedRemedies": [
          {
            "description": "test",
            "type": "setAsideAward"
          }
        ],
        "arguments": [
          {
            "description": "test argument"
          }
        ],
        "sequenceNumber": 1
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4b4ed03227c24f43b34f74183e3e0ca2/awards/22538da636d84b5b88ad4598942e3823/complaints/39df58db552846e58d5e16996582b329

{
  "data": {
    "author": {
      "name": "ДКП «Школяр»",
      "address": {
        "streetAddress": "вул. Островського, 33",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21100",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Сергій Олексюк",
        "email": "soleksuk@gmail.com",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "uri": "http://www.sc.gov.ua/",
        "id": "00137256",
        "legalName": "ДКП «Школяр»"
      }
    },
    "title": "Недостатньо інформації",
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "status": "draft",
    "type": "complaint",
    "objections": [
      {
        "id": "7b2198d26c724f3bad6317a7c68572a0",
        "title": "My objection",
        "description": "Test objection",
        "relatedItem": "8850d78aa8a94c148d6d245907f40d3e",
        "classification": {
          "scheme": "violation_amcu",
          "id": "corruptionDescription",
          "description": "test classification"
        },
        "requestedRemedies": [
          {
            "id": "5791e81deae241a4a8165f81295e4dca",
            "type": "setAsideAward",
            "description": "test"
          }
        ],
        "arguments": [
          {
            "id": "be70abde69b2426ea4e2f9dda93d6a87",
            "description": "test argument"
          }
        ],
        "sequenceNumber": 1,
        "relatesTo": "award"
      }
    ],
    "id": "39df58db552846e58d5e16996582b329",
    "date": "2023-10-10T01:00:03+03:00",
    "bid_id": "c938a8780db146beaba184a25937b356",
    "complaintID": "UA-2023-10-10-000001-a.11",
    "relatedLot": "c94486b261084c09ac0c731b74d35c85",
    "value": {
      "amount": 3000,
      "currency": "UAH"
    }
  },
  "access": {
    "token": "9b65b7d1489e46cea8ed523dc9bdff4b",
    "transfer": "dfde2a3a015b4f579ec9fe16f4531266"
  }
}

