PATCH /api/2.5/tenders/4b4ed03227c24f43b34f74183e3e0ca2/awards/b2df0a3f487a401987b1cdf1170a93be/complaints/19276d51ed8e45bc9a79d274428918e0 HTTP/1.0
Authorization: Bearer reviewer
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "decision": "Тендер скасовується замовником",
    "status": "stopped",
    "rejectReason": "tenderCancelled"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "19276d51ed8e45bc9a79d274428918e0",
    "complaintID": "UA-2023-10-10-000001-a.6",
    "date": "2023-10-10T01:00:03+03:00",
    "status": "stopped",
    "type": "complaint",
    "relatedLot": "c94486b261084c09ac0c731b74d35c85",
    "bid_id": "c938a8780db146beaba184a25937b356",
    "author": {
      "name": "ДКП «Школяр»",
      "address": {
        "streetAddress": "вул. Островського, 33",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21100",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Сергій Олексюк",
        "email": "soleksuk@gmail.com",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "uri": "http://www.sc.gov.ua/",
        "id": "00137256",
        "legalName": "ДКП «Школяр»"
      }
    },
    "title": "Недостатньо інформації",
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "dateSubmitted": "2023-10-10T01:00:03+03:00",
    "objections": [
      {
        "id": "036eb82d4399412795be618a78a23a54",
        "title": "My objection",
        "description": "Test objection",
        "relatesTo": "award",
        "relatedItem": "46b5dff235cc48fb952fae6c72243c12",
        "classification": {
          "scheme": "violation_amcu",
          "id": "corruptionDescription",
          "description": "test classification"
        },
        "requestedRemedies": [
          {
            "id": "0ff7e41f09474aa5a04474cb43e64c65",
            "type": "setAsideAward",
            "description": "test"
          }
        ],
        "arguments": [
          {
            "id": "3bb3a91c2484482c9e77be70bf6d68a3",
            "description": "test argument"
          }
        ],
        "sequenceNumber": 1
      }
    ],
    "decision": "Тендер скасовується замовником",
    "acceptance": true,
    "dateAccepted": "2023-10-10T01:00:03+03:00",
    "reviewDate": "2023-10-10T01:00:03+03:00",
    "reviewPlace": "Place of review",
    "value": {
      "amount": 3000.0,
      "currency": "UAH"
    },
    "rejectReason": "tenderCancelled",
    "dateDecision": "2023-10-10T01:00:03+03:00",
    "dateCanceled": "2023-10-10T01:00:03+03:00"
  }
}

