POST /api/2.5/tenders/0f776099eb8344b4a149200a8657a9df/awards/ea8449205ea44154a82fc91e01bb162b/complaints/4450f77623cd4fa1bd42d766563485ed/posts?acc_token=596d2a1c0b3f4932bf4d825bfc8c24f2 HTTP/1.0
Authorization: Bearer broker
Content-Length: 665
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Додано документ",
    "recipient": "aboveThresholdReviewers",
    "relatedPost": "eb126a328c1e4f9690630391c2eedfe9",
    "documents": [
      {
        "title": "post_document_tender.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1658394562ef49b8a00da93cccbef54a?Signature=7OZNrzAjddinrTaR58UdTD9CBHNVOUEXU7SWpUze%2FD1R0yLWiCBB98GG4Zi%2BTDUoLEsrQksZm1nql8rNex0nAw%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0f776099eb8344b4a149200a8657a9df/awards/ea8449205ea44154a82fc91e01bb162b/complaints/4450f77623cd4fa1bd42d766563485ed/posts/f0bebfaea3754a6b8b9d4cca0bd6fe8e

{
  "data": {
    "id": "f0bebfaea3754a6b8b9d4cca0bd6fe8e",
    "title": "Уточнення по вимозі",
    "description": "Додано документ",
    "documents": [
      {
        "id": "f67b391286bc482c97a738585694aad1",
        "hash": "md5:00000000000000000000000000000000",
        "title": "post_document_tender.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1658394562ef49b8a00da93cccbef54a?Signature=MK0mEshJldlfLibdoXVsQFsuOcM0QzA%2FzItzgU7qbcKLTbJ1SfO30%2FNjXhpdY0tsSvVRzio4SQHUbddd9QAxDw%3D%3D&KeyID=a8968c46",
        "datePublished": "2023-01-01T00:00:03+02:00",
        "dateModified": "2023-01-01T00:00:03+02:00",
        "author": "tender_owner",
        "documentOf": "tender"
      }
    ],
    "author": "tender_owner",
    "recipient": "aboveThresholdReviewers",
    "datePublished": "2023-01-01T00:00:03+02:00",
    "relatedPost": "eb126a328c1e4f9690630391c2eedfe9"
  }
}

