PATCH /api/2.5/tenders/9056b6881e5c4accadfcaa96d4409069/cancellations/fcbd87c46f7d49e3a21f70b1a0b85f6a/complaints/f1dcc4a59bc54974bcab49c81f5df20e HTTP/1.0
Authorization: Bearer bot
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "pending"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "f1dcc4a59bc54974bcab49c81f5df20e",
    "complaintID": "UA-2023-01-01-000001-a.1",
    "date": "2023-01-01T00:00:00+02:00",
    "documents": [
      {
        "id": "81d032fcca0f4f60bbdb3c79db0c5c8a",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Complaint_Attachment.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/aa98df708233490483f06801174bea5a?Signature=WTozQKCjSit%2BDI6jh5evsVb9Q6f6VMcnSq9NWRdKc4qW%2B%2BTDZxDcQUOOXRSM1EJKOyLG7EO33%2Bp1NIO80KEFCg%3D%3D&KeyID=a8968c46",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00",
        "author": "complaint_owner",
        "documentOf": "tender"
      }
    ],
    "author": {
      "name": "ДКП «Школяр»",
      "address": {
        "streetAddress": "вул. Островського, 33",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21100",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Сергій Олексюк",
        "email": "soleksuk@gmail.com",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00137256",
        "legalName": "ДКП «Школяр»",
        "uri": "http://www.sc.gov.ua/"
      }
    },
    "title": "Недостатньо інформації",
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "dateSubmitted": "2023-01-01T00:00:00+02:00",
    "value": {
      "amount": 2000.0,
      "currency": "UAH"
    },
    "status": "pending",
    "type": "complaint"
  }
}

