POST /api/2.5/tenders/19a5d9d36c2143d8bfb8c1dfbabc14ef/cancellations/508bf010ec78469eb7980c819aa5e330/complaints/29850e30101948638336551fe20febd6/posts?acc_token=a1a7e55de16a424b9af1ea3b061e1353 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Відповідь до пояснення",
    "description": "Відсутній документ",
    "recipient": "aboveThresholdReviewers",
    "relatedObjection": "0378b17f35534138837a906d4f43828a",
    "relatedPost": "b1965e334db84fa4a1b3ee2449c6a82d"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "relatedPost",
      "description": [
        "forbidden to answer to explanations"
      ]
    }
  ]
}

