POST /api/2.5/tenders/1a08c0c252064a9a8cf24c8264e29e6d/complaints HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "title": "Недостатньо інформації",
    "status": "draft",
    "type": "complaint",
    "author": {
      "address": {
        "countryName": "Україна",
        "locality": "м. Вінниця",
        "postalCode": "21100",
        "region": "Вінницька область",
        "streetAddress": "вул. Островського, 33"
      },
      "contactPoint": {
        "email": "soleksuk@gmail.com",
        "name": "Сергій Олексюк",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "legalName": "ДКП «Школяр»",
        "id": "00137256",
        "uri": "http://www.sc.gov.ua/"
      },
      "name": "ДКП «Школяр»"
    },
    "objections": [
      {
        "title": "My objection",
        "description": "Test objection",
        "relatesTo": "tender",
        "relatedItem": "1a08c0c252064a9a8cf24c8264e29e6d",
        "classification": {
          "scheme": "violation_amcu",
          "id": "corruptionDescription",
          "description": "test classification"
        },
        "requestedRemedies": [
          {
            "description": "test",
            "type": "setAsideAward"
          }
        ],
        "arguments": [
          {
            "description": "test argument"
          }
        ],
        "sequenceNumber": 1
      }
    ]
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/1a08c0c252064a9a8cf24c8264e29e6d/complaints/9999852c01ec4b2ea774bf6da3320959

{
  "data": {
    "author": {
      "name": "ДКП «Школяр»",
      "address": {
        "streetAddress": "вул. Островського, 33",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21100",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Сергій Олексюк",
        "email": "soleksuk@gmail.com",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "uri": "http://www.sc.gov.ua/",
        "id": "00137256",
        "legalName": "ДКП «Школяр»"
      }
    },
    "title": "Недостатньо інформації",
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "status": "draft",
    "type": "complaint",
    "objections": [
      {
        "id": "ff4de431f3814528a53e6fd7e4184da4",
        "title": "My objection",
        "description": "Test objection",
        "relatedItem": "1a08c0c252064a9a8cf24c8264e29e6d",
        "classification": {
          "scheme": "violation_amcu",
          "id": "corruptionDescription",
          "description": "test classification"
        },
        "requestedRemedies": [
          {
            "id": "334db67b9ffa4e43bdfee9f3e4a350e9",
            "type": "setAsideAward",
            "description": "test"
          }
        ],
        "arguments": [
          {
            "id": "6e6475e6604e4bec9141cb57c6f88850",
            "description": "test argument"
          }
        ],
        "sequenceNumber": 1,
        "relatesTo": "tender"
      }
    ],
    "id": "9999852c01ec4b2ea774bf6da3320959",
    "date": "2027-01-01T00:00:00+02:00",
    "complaintID": "UA-2027-01-01-000001-a.a1",
    "value": {
      "amount": 2000,
      "currency": "UAH"
    }
  },
  "access": {
    "token": "2575026f204748be90caf9bf72b08149",
    "transfer": "1e3e1443f5cb4ab3bfeaba842a174790"
  }
}

