GET /api/2.5/tenders/a90905bbe0c24a6387f3ecde4e87bcb4/complaints/3db50ebc52124424812681187e5ee06d?acc_token=7daa558cb4b042b3a1c9e4d6f7d2a8be HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "3db50ebc52124424812681187e5ee06d",
    "complaintID": "UA-2027-01-01-000001-a.a1",
    "date": "2027-01-01T00:00:00+02:00",
    "status": "satisfied",
    "type": "complaint",
    "author": {
      "name": "ДКП «Школяр»",
      "address": {
        "streetAddress": "вул. Островського, 33",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21100",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Сергій Олексюк",
        "email": "soleksuk@gmail.com",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "uri": "http://www.sc.gov.ua/",
        "id": "00137256",
        "legalName": "ДКП «Школяр»"
      }
    },
    "title": "Недостатньо інформації",
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "dateSubmitted": "2027-01-01T00:00:00+02:00",
    "objections": [
      {
        "id": "dcf93dd326fa4ad0b5120d7859cd83ff",
        "title": "My objection",
        "description": "Test objection",
        "relatesTo": "tender",
        "relatedItem": "a90905bbe0c24a6387f3ecde4e87bcb4",
        "classification": {
          "scheme": "violation_amcu",
          "id": "corruptionDescription",
          "description": "test classification"
        },
        "requestedRemedies": [
          {
            "id": "db315e09065a482c86b8272e798609be",
            "type": "setAsideAward",
            "description": "test"
          }
        ],
        "arguments": [
          {
            "id": "fdaeb63728c346cbb60069c75b0b005f",
            "description": "test argument"
          }
        ],
        "sequenceNumber": 1
      }
    ],
    "acceptance": true,
    "dateAccepted": "2027-01-01T00:00:00+02:00",
    "reviewDate": "2027-01-01T00:00:00+02:00",
    "reviewPlace": "Place of review",
    "value": {
      "amount": 2000.0,
      "currency": "UAH"
    },
    "dateDecision": "2027-01-01T00:00:00+02:00",
    "appeals": [
      {
        "id": "857ebcc410d44368aa53f1c51ab2a748",
        "description": "test",
        "documents": [
          {
            "confidentiality": "public",
            "id": "ad9b247573e54576a42da6567b94be85",
            "datePublished": "2027-01-01T00:00:00+02:00",
            "hash": "md5:00000000000000000000000000000000",
            "title": "name.doc",
            "format": "application/msword",
            "url": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/tenders/a90905bbe0c24a6387f3ecde4e87bcb4/complaints/3db50ebc52124424812681187e5ee06d/appeals/857ebcc410d44368aa53f1c51ab2a748/documents/ad9b247573e54576a42da6567b94be85?download=20514262a4564559910de135ff1f0d3e",
            "documentOf": "tender",
            "dateModified": "2027-01-01T00:00:00+02:00",
            "author": "complaint_owner",
            "language": "uk"
          }
        ],
        "proceeding": {
          "dateProceedings": "2025-06-10T10:00:00+03:00",
          "proceedingNumber": "1234567890"
        },
        "legislation": {
          "version": "2020-04-19",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19#n1284"
          },
          "type": "NATIONAL_LEGISLATION",
          "article": "18.23"
        },
        "author": "complaint_owner",
        "dateCreated": "2027-01-01T00:00:00+02:00",
        "datePublished": "2027-01-01T00:00:00+02:00"
      },
      {
        "description": "Test appeal",
        "id": "48cf8532081f42a79fd6eb54c29e29f0",
        "dateCreated": "2027-01-01T00:00:00+02:00",
        "datePublished": "2027-01-01T00:00:00+02:00",
        "legislation": {
          "version": "2020-04-19",
          "type": "NATIONAL_LEGISLATION",
          "article": "18.23",
          "identifier": {
            "id": "922-VIII",
            "legalName": "Закон України \"Про публічні закупівлі\"",
            "uri": "https://zakon.rada.gov.ua/laws/show/922-19#n1284"
          }
        },
        "author": "tender_owner",
        "documents": [
          {
            "confidentiality": "public",
            "hash": "md5:00000000000000000000000000000000",
            "title": "sign.p7s",
            "format": "application/pkcs7-signature",
            "url": "http://public-api-sandbox.prozorro.gov.ua/api/2.5/tenders/a90905bbe0c24a6387f3ecde4e87bcb4/complaints/3db50ebc52124424812681187e5ee06d/appeals/48cf8532081f42a79fd6eb54c29e29f0/documents/4530e91182cb47959efaab81113a86ac?download=c66f59fb078741349f4858931c45b847",
            "documentOf": "tender",
            "language": "uk",
            "id": "4530e91182cb47959efaab81113a86ac",
            "datePublished": "2027-01-01T00:00:00+02:00",
            "dateModified": "2027-01-01T00:00:00+02:00",
            "author": "tender_owner"
          }
        ]
      }
    ]
  }
}

