PATCH /api/2.5/tenders/b696346c4c21448992ec590d044c2b5c/complaints/3e9fa4304ddc4e36966c56bd986b4db6?acc_token=79b1f65ea5944d6aa16734423bddd897 HTTP/1.0
Authorization: Bearer broker
Content-Length: 566
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "objections": [
      {
        "title": "My objection",
        "description": "Test objection",
        "relatesTo": "tender",
        "relatedItem": "b696346c4c21448992ec590d044c2b5c",
        "classification": {
          "scheme": "violation_amcu",
          "id": "corruptionDescription",
          "description": "test classification"
        },
        "requestedRemedies": [
          {
            "description": "test",
            "type": "setAsideAward"
          }
        ],
        "arguments": [
          {
            "description": "test argument",
            "evidences": [
              {
                "title": "Evidence",
                "description": "Test evidence",
                "relatedDocument": "df202e6470d44ee6901d7a8ae43fe0b8"
              }
            ]
          }
        ],
        "id": "f3c3ca1bad594b31b5ec79c7cafd6f2e"
      }
    ]
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "3e9fa4304ddc4e36966c56bd986b4db6",
    "complaintID": "UA-2023-10-10-000001-a.2",
    "date": "2023-10-10T01:00:00+03:00",
    "status": "draft",
    "documents": [
      {
        "id": "df202e6470d44ee6901d7a8ae43fe0b8",
        "datePublished": "2023-10-10T01:00:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Evidence_Attachment.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/31f24c650bf0450a9e351fcadad42d8f?Signature=Dn3KrTtqhhnkZg99w0%2B3e5lNXoGMTo0KYi1TMWQofS9n5JGPueLURYUn80rNe2L4bT7qY4PQX1q8VaLSbQk1DA%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:00:00+03:00",
        "author": "complaint_owner",
        "language": "uk"
      }
    ],
    "type": "complaint",
    "author": {
      "name": "ДКП «Школяр»",
      "address": {
        "streetAddress": "вул. Островського, 33",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21100",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Сергій Олексюк",
        "email": "soleksuk@gmail.com",
        "telephone": "+380432216930"
      },
      "identifier": {
        "scheme": "UA-EDR",
        "uri": "http://www.sc.gov.ua/",
        "id": "00137256",
        "legalName": "ДКП «Школяр»"
      }
    },
    "title": "Недостатньо інформації",
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.",
    "objections": [
      {
        "id": "f3c3ca1bad594b31b5ec79c7cafd6f2e",
        "title": "My objection",
        "description": "Test objection",
        "relatesTo": "tender",
        "relatedItem": "b696346c4c21448992ec590d044c2b5c",
        "classification": {
          "scheme": "violation_amcu",
          "id": "corruptionDescription",
          "description": "test classification"
        },
        "requestedRemedies": [
          {
            "id": "6384300c78eb40b0889c4d8ae444c66c",
            "type": "setAsideAward",
            "description": "test"
          }
        ],
        "arguments": [
          {
            "id": "0b32676e845b4658919092f8adfdb4a3",
            "description": "test argument",
            "evidences": [
              {
                "id": "11f02fd2af124e5f9d9addbd1f447052",
                "title": "Evidence",
                "description": "Test evidence",
                "relatedDocument": "df202e6470d44ee6901d7a8ae43fe0b8"
              }
            ]
          }
        ]
      }
    ],
    "value": {
      "amount": 2000.0,
      "currency": "UAH"
    }
  }
}

