PATCH /api/2.5/tenders/c40b88933aa34b83827c2e6d3c688c18/complaints/6ca341317b4f4b3cabda3a8f39db58e2/appeals/efae0bce199b49b5a609ca0b66969e79?acc_token=7daa558cb4b042b3a1c9e4d6f7d2a8be HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "proceeding": {
      "dateProceedings": "2025-06-10T10:00:00+03:00",
      "proceedingNumber": "1234567890"
    }
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "efae0bce199b49b5a609ca0b66969e79",
    "description": "test",
    "documents": [
      {
        "confidentiality": "public",
        "id": "94a2a62a51424b6b925f866770509be7",
        "datePublished": "2027-01-01T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "name.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/20514262a4564559910de135ff1f0d3e?Signature=PKiu5y12CIoOKw6b2loFUvBodaAAMT1mRNn8%2BzWhSU14eazJY7eOZ1iZXPXOmKKTmKq2qofpTWILjk4o64IVDg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2027-01-01T00:00:00+02:00",
        "author": "complaint_owner",
        "language": "uk"
      }
    ],
    "proceeding": {
      "dateProceedings": "2025-06-10T10:00:00+03:00",
      "proceedingNumber": "1234567890"
    },
    "legislation": {
      "version": "2020-04-19",
      "identifier": {
        "id": "922-VIII",
        "legalName": "Закон України \"Про публічні закупівлі\"",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19#n1284"
      },
      "type": "NATIONAL_LEGISLATION",
      "article": "18.23"
    },
    "author": "complaint_owner",
    "dateCreated": "2027-01-01T00:00:00+02:00",
    "datePublished": "2027-01-01T00:00:00+02:00"
  }
}

