POST /api/2.5/tenders/d816e417c06e4dc4a33d89a4478b102f/qualifications/e41f8f4ec0b241e1809528a96186e78b/complaints/7069590959c74949846193af98eddde7/posts HTTP/1.0
Authorization: Bearer reviewer
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Відсутній документ",
    "recipient": "complaint_owner"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/d816e417c06e4dc4a33d89a4478b102f/qualifications/e41f8f4ec0b241e1809528a96186e78b/complaints/7069590959c74949846193af98eddde7/posts/1fbeaf3065e04d2e839259e8f5e1536a

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Відсутній документ",
    "recipient": "complaint_owner",
    "id": "1fbeaf3065e04d2e839259e8f5e1536a",
    "datePublished": "2023-10-10T01:00:01+03:00",
    "author": "aboveThresholdReviewers"
  }
}

