POST /api/2.5/tenders/f5ad0e5f677645ba9b8a94bc11be4fe1/qualifications/2d78f58e5c164ddf82bfdc25666fd652/complaints/5b669a6114ef4a78a9f5a2d8d7489d6d/documents?acc_token=72ce97a3f67b4f5280d57ba22f0e597a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "post_document_tender.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a450311edb8e418082d4746c150e309c?Signature=ie%2FvZJ5uVGGOPp5i7ipeO75tMkkY1EkeumZK2C77mwjIjkJjPRqQKbu7EWFWHeQX3k8hrz2e3rzpLLn0qdFtBg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf",
    "documentOf": "post",
    "relatedItem": "81d946c2e8884da9a8b5f2b3d054309c"
  }
}


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "url",
      "name": "role",
      "description": "Can add document to post only by post author"
    }
  ]
}

