POST /api/2.5/tenders/53abca43c14f4515b7f912c00c37cbd4/qualifications/be777a5b462c47b4a57628796c466162/complaints/24a8411af17b41d895fa8c698d266e0c/posts HTTP/1.0
Authorization: Bearer reviewer
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Відсутній документ",
    "recipient": "tender_owner"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/53abca43c14f4515b7f912c00c37cbd4/qualifications/be777a5b462c47b4a57628796c466162/complaints/24a8411af17b41d895fa8c698d266e0c/posts/e7750a94134a4b869dfc1cde5cdcc44d

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Відсутній документ",
    "recipient": "tender_owner",
    "id": "e7750a94134a4b869dfc1cde5cdcc44d",
    "datePublished": "2023-10-10T01:00:01+03:00",
    "author": "aboveThresholdReviewers"
  }
}

