POST /api/2.5/tenders/197ab221daff4d87b98cf8e0d03cb393/qualifications/2d78f58e5c164ddf82bfdc25666fd652/complaints/43b369b101664c48be3959cdb9926838/posts HTTP/1.0
Authorization: Bearer reviewer
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Відсутній документ",
    "recipient": "complaint_owner",
    "relatedObjection": "e424fd9b73c046268255bd219f528456"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/197ab221daff4d87b98cf8e0d03cb393/qualifications/2d78f58e5c164ddf82bfdc25666fd652/complaints/43b369b101664c48be3959cdb9926838/posts/602a27ce4e40424098c0c1702e16994a

{
  "data": {
    "title": "Уточнення по вимозі",
    "description": "Відсутній документ",
    "recipient": "complaint_owner",
    "relatedObjection": "e424fd9b73c046268255bd219f528456",
    "id": "602a27ce4e40424098c0c1702e16994a",
    "datePublished": "2027-01-01T00:00:01+02:00",
    "author": "aboveThresholdReviewers"
  }
}

