PATCH /api/2.5/tenders/ee8464b688974d51b379fe16104cce62/bids/c58478830ccc441d84deb25d61992ffd?acc_token=e821726838304fff98409ab63dc9e230 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "requirementResponses": []
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

null

