PATCH /api/2.5/tenders/ee8464b688974d51b379fe16104cce62/bids/c58478830ccc441d84deb25d61992ffd/documents/02388451ca6c47bda1da134ec86ac4c6?acc_token=e821726838304fff98409ab63dc9e230 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "confidentiality": "buyerOnly",
    "confidentialityRationale": "Only our company sells badgers with pink hair."
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "confidentiality": "buyerOnly",
    "confidentialityRationale": "Only our company sells badgers with pink hair.",
    "id": "02388451ca6c47bda1da134ec86ac4c6",
    "datePublished": "2027-01-01T00:00:00+02:00",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Proposal_top_secrets.pdf",
    "format": "application/pdf",
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee8464b688974d51b379fe16104cce62/bids/c58478830ccc441d84deb25d61992ffd/documents/02388451ca6c47bda1da134ec86ac4c6?download=68a6b3e65371402492995faa5acc2582",
    "documentOf": "tender",
    "dateModified": "2027-01-01T00:00:00+02:00",
    "language": "uk"
  }
}

