PATCH /api/2.5/tenders/0c99535af6024017bcbdec7b4a5c49da/qualifications/2896d1591f314d42865277bf08da65ea?acc_token=c09bfd8bd3964ff4a95d9cb9477f7dfd HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "unsuccessful"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "2896d1591f314d42865277bf08da65ea",
    "bidID": "ec61ff4dff6e4acc8d78e1f819212cb9",
    "lotID": "d9c1c86a51294d9f9e128b780416b344",
    "status": "unsuccessful",
    "date": "2027-01-01T00:03:00+02:00",
    "qualified": false,
    "eligible": false
  }
}

