POST /api/2.5/tenders/d9668d8fd5d14779905c208c929e49bc/cancellations/0ed8230efb644787a9f78ad666e4034b/documents?acc_token=c09bfd8bd3964ff4a95d9cb9477f7dfd HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "sign.p7s",
    "documentType": "cancellationReport",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9bfbd7c54ff346ddb088143da736acd4?Signature=88sht3Uqm0TgjTGNzO6hmV%2B3FEAyzL6KqG53xygqDL2jcg6du8LeIgIlXx2P0d8AFYRFuiOoPHuIkzEUwP%2FsCA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pkcs7-signature"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/d9668d8fd5d14779905c208c929e49bc/cancellations/0ed8230efb644787a9f78ad666e4034b/documents/f593872d1386447daf94edcf5dde2907

{
  "data": {
    "confidentiality": "public",
    "documentType": "cancellationReport",
    "hash": "md5:00000000000000000000000000000000",
    "title": "sign.p7s",
    "format": "application/pkcs7-signature",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9bfbd7c54ff346ddb088143da736acd4?Signature=f3vjAlDaulX6cKfNmiIBRA3h6qNIrL8X%2BfrOGUguAh5jfJfbk3N2V4BhIgArmsJeqvS%2FeXQeaZxgkh49grHiCw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "f593872d1386447daf94edcf5dde2907",
    "datePublished": "2023-10-10T01:03:00+03:00",
    "dateModified": "2023-10-10T01:03:00+03:00"
  }
}

