POST /api/2.5/tenders/d825f322bda5487a8c8e5d9c1e58fd9e/awards/c0a45c00adaa490dafd6b7ee6f3329ef/documents?acc_token=3d5baa5d82af4c94a467591dfe699af2 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "sign.p7s",
    "documentType": "notice",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8da5085d80584bccaaefd08c89405d6e?Signature=FnwTeFXVLluO3ComKSkGBx1DLJQR9P0Ng4aTlB%2BcR8EoHx%2BUQCzIDTDX7buIJEd9Vh4uCNSvhVRG3nsFqtDkCg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "sign/pkcs7-signature"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/d825f322bda5487a8c8e5d9c1e58fd9e/awards/c0a45c00adaa490dafd6b7ee6f3329ef/documents/c333b74453694eb0b206d36094d46169

{
  "data": {
    "confidentiality": "public",
    "documentType": "notice",
    "hash": "md5:00000000000000000000000000000000",
    "title": "sign.p7s",
    "format": "sign/pkcs7-signature",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8da5085d80584bccaaefd08c89405d6e?Signature=GnjI7gFtVXKF3lndjVzOdNu6QMPbkSlvKl3AHAJQb8P%2F%2FHrBS58TPvv107%2FFqDmkM%2BZcVdJHi1dIlODlSMEvDw%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "c333b74453694eb0b206d36094d46169",
    "datePublished": "2023-10-16T01:15:06+03:00",
    "dateModified": "2023-10-16T01:15:06+03:00",
    "author": "tender_owner"
  }
}

