POST /api/2.5/tenders/137bba901398466a9aa1880da2ade9a6/documents?acc_token=76e7037e0a9a445f8bfe44a967308c41 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Notice.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d990d4897b1a47a19bf707544e0c8c39?Signature=Cnqgf4baRhlPGfZI3oqbgFwtYRe5cF%2FIteSCxhLKf3ZQ5ONP%2BGtbffmOvR4UcfVPekxZBVKiw21PlNvpBhqkAw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/137bba901398466a9aa1880da2ade9a6/documents/0eb8412a31bf4fb495e2d50c6a0876d5

{
  "data": {
    "confidentiality": "public",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d990d4897b1a47a19bf707544e0c8c39?Signature=Odg7g4lnQq9K23uhoeviII9%2BTeGyK%2BZebhgl5aO%2FJj1M4qGN5N%2Fq0TCVhB39EYEVdlWkc0V%2B3rnS%2FDb4w%2Fd7Bg%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "0eb8412a31bf4fb495e2d50c6a0876d5",
    "datePublished": "2023-10-10T01:00:01+03:00",
    "dateModified": "2023-10-10T01:00:01+03:00",
    "author": "tender_owner"
  }
}

