GET /api/2.5/agreements/144de8e79e64488a967c57cebaacb0d3 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "agreementID": "UA-2023-10-10-000001",
    "frameworkID": "5bbf44a4849d4cb8a80c469d8d91231e",
    "agreementType": "internationalFinancialInstitutions",
    "status": "active",
    "period": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "endDate": "2024-12-03T01:00:00+03:00"
    },
    "procuringEntity": {
      "name": "Державне управління справами",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00037256",
        "legalName": "Назва організації"
      },
      "address": {
        "countryName": "Україна",
        "streetAddress": "вул. Банкова, 11, корпус 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220"
      },
      "contactPoint": {
        "name": "Державне управління справами",
        "telephone": "+0440000000",
        "email": "aa@aa.com"
      },
      "kind": "general"
    },
    "classification": {
      "description": "Mustard seeds",
      "scheme": "ДК021",
      "id": "03111600-8"
    },
    "additionalClassifications": [
      {
        "scheme": "ДК003",
        "id": "17.21.1",
        "description": "папір і картон гофровані, паперова й картонна тара"
      }
    ],
    "contracts": [
      {
        "id": "0024966553564a8f812f84689d34148c",
        "qualificationID": "da120b087f8c42f18d4c12b374cdf2eb",
        "submissionID": "78e643e7c5c94f6c9e686ffa9c723713",
        "status": "active",
        "suppliers": [
          {
            "name": "Державне управління справами",
            "name_en": "State administration",
            "scale": "micro",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "12345678",
              "legalName_en": "dus.gov.ua",
              "uri": "http://www.dus.gov.ua/",
              "legalName": "Державне управління справами"
            },
            "address": {
              "countryName": "Україна",
              "streetAddress": "вул. Банкова, 11, корпус 1",
              "locality": "м. Київ",
              "region": "м. Київ",
              "postalCode": "01220"
            },
            "contactPoint": {
              "name": "Державне управління справами",
              "name_en": "State administration",
              "telephone": "+0440000000",
              "email": "aa@aa.com"
            }
          }
        ],
        "milestones": [
          {
            "id": "00464c7636ce464bb05b8504af6f9d9b",
            "status": "scheduled",
            "type": "activation",
            "dueDate": "2024-12-03T01:00:00+03:00",
            "dateModified": "2023-10-10T01:00:00+03:00"
          }
        ],
        "date": "2023-10-10T01:00:00+03:00",
        "dateModified": "2023-10-10T01:00:00+03:00"
      },
      {
        "id": "71493e93a3804e8b8c23cfcc21d838cf",
        "qualificationID": "93225b64f2dc409292bfe706bf11b712",
        "submissionID": "73c23c0a23454500a3a406ef0b592b69",
        "status": "active",
        "suppliers": [
          {
            "name": "Державне управління справами",
            "name_en": "State administration",
            "scale": "micro",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "12345679",
              "legalName_en": "dus.gov.ua",
              "uri": "http://www.dus.gov.ua/",
              "legalName": "Державне управління справами"
            },
            "address": {
              "countryName": "Україна",
              "streetAddress": "вул. Банкова, 11, корпус 1",
              "locality": "м. Київ",
              "region": "м. Київ",
              "postalCode": "01220"
            },
            "contactPoint": {
              "name": "Державне управління справами",
              "name_en": "State administration",
              "telephone": "+0440000000",
              "email": "aa@aa.com"
            }
          }
        ],
        "milestones": [
          {
            "id": "f09b253e29ee403a93db4be0fc9c4d54",
            "status": "scheduled",
            "type": "activation",
            "dueDate": "2024-12-03T01:00:00+03:00",
            "dateModified": "2023-10-10T01:00:00+03:00"
          }
        ],
        "date": "2023-10-10T01:00:00+03:00",
        "dateModified": "2023-10-10T01:00:00+03:00"
      },
      {
        "id": "a4ff7ab0a7794f20af93e8f54678b8f6",
        "qualificationID": "1de5a50bb22b483baf5812ade87f8d0a",
        "submissionID": "65b9f9a60a1d4d82998ca065a810da81",
        "status": "active",
        "suppliers": [
          {
            "name": "Державне управління справами",
            "name_en": "State administration",
            "scale": "micro",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "12345671",
              "legalName_en": "dus.gov.ua",
              "uri": "http://www.dus.gov.ua/",
              "legalName": "Державне управління справами"
            },
            "address": {
              "countryName": "Україна",
              "streetAddress": "вул. Банкова, 11, корпус 1",
              "locality": "м. Київ",
              "region": "м. Київ",
              "postalCode": "01220"
            },
            "contactPoint": {
              "name": "Державне управління справами",
              "name_en": "State administration",
              "telephone": "+0440000000",
              "email": "aa@aa.com"
            }
          }
        ],
        "milestones": [
          {
            "id": "6cb16718fd5c44beb4a3d0fc3a6323ed",
            "status": "scheduled",
            "type": "activation",
            "dueDate": "2024-12-03T01:00:00+03:00",
            "dateModified": "2023-10-10T01:00:00+03:00"
          }
        ],
        "date": "2023-10-10T01:00:00+03:00",
        "dateModified": "2023-10-10T01:00:00+03:00"
      }
    ],
    "owner": "broker",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "date": "2023-10-10T01:00:00+03:00",
    "next_check": "2024-12-03T01:00:00+03:00",
    "dateCreated": "2023-10-10T01:00:00+03:00",
    "id": "144de8e79e64488a967c57cebaacb0d3"
  },
  "config": {
    "restricted": false
  }
}

