POST /api/2.5/tenders/99b2cdff172144fea50cc5ac1ee1d29b/ownership HTTP/1.0
Authorization: Bearer broker1
Content-Length: 100
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "id": "bf6462080e6f4c9b8d67bee3ba214bcb",
    "transfer": "2e4e62ddc11d4d5f824a5099431067e0"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "title": "футляри до державних нагород",
    "date": "2021-03-16T00:00:00+02:00",
    "dateModified": "2021-03-16T00:00:00+02:00",
    "tenderID": "UA-2021-03-16-000001",
    "owner": "broker1",
    "mainProcurementCategory": "goods",
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "type": "financing",
        "code": "prepayment",
        "percentage": 45.55,
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 0
      },
      {
        "id": "3819cefcbac247baa8a18425cad35a02",
        "title": "deliveryOfGoods",
        "type": "financing",
        "code": "postpayment",
        "percentage": 54.45,
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 0
      }
    ],
    "procurementMethod": "open",
    "awardCriteria": "lowestCost",
    "submissionMethod": "electronicAuction",
    "status": "active.enquiries",
    "items": [
      {
        "id": "88bf832747044d909dc6c026f8f1fad9",
        "description": "футляри до державних нагород",
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ],
        "unit": {
          "name": "item",
          "code": "44617100-9"
        },
        "quantity": 5.0,
        "deliveryDate": {
          "startDate": "2021-03-18T00:00:00+02:00",
          "endDate": "2021-03-21T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "classification": {
          "description": "Cartons",
          "scheme": "ДК021",
          "id": "44617100-9"
        }
      }
    ],
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "enquiryPeriod": {
      "startDate": "2021-03-16T00:00:00+02:00",
      "endDate": "2021-03-23T00:00:00+02:00"
    },
    "tenderPeriod": {
      "startDate": "2021-03-23T00:00:00+02:00",
      "endDate": "2021-03-30T00:00:00+02:00"
    },
    "procuringEntity": {
      "name": "Державне управління справами",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00037256",
        "legalName": "Державне управління справами",
        "uri": "http://www.dus.gov.ua/"
      },
      "address": {
        "streetAddress": "вул. Банкова, 11, корпус 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Державне управління справами",
        "telephone": "0440000000"
      },
      "kind": "general"
    },
    "minimalStep": {
      "amount": 15.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "procurementMethodType": "belowThreshold",
    "id": "99b2cdff172144fea50cc5ac1ee1d29b",
    "next_check": "2021-03-23T00:00:00+02:00",
    "numberOfBids": 0
  }
}

