POST /api/2.5/agreements/5f2c362583984e0daed42cb21777cee3/ownership HTTP/1.0
Authorization: Bearer broker
Content-Length: 100
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "id": "6ec536f272c54558b4d6a4eac61a6f9e",
    "transfer": "5bcbde1909154f09bf5d7c4632cc21f7"
  }
}


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "url",
      "name": "accreditation",
      "description": "Owner Accreditation level does not permit ownership change"
    }
  ]
}

