POST /api/2.5/agreements/5f2c362583984e0daed42cb21777cee3/ownership HTTP/1.0
Authorization: Bearer broker3
Content-Length: 100
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "id": "2a02430274e84ecf96ac807e69027304",
    "transfer": "500a8aa113a8452abc838adf2114f767"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "owner": "broker3",
    "id": "5f2c362583984e0daed42cb21777cee3"
  }
}

