POST /api/2.5/transfers HTTP/1.0
Authorization: Bearer broker3
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {}
}


HTTP/1.0 201 Created
Content-Type: application/json

{
  "data": {
    "date": "2023-10-10T01:00:00+03:00",
    "id": "4db8f3cce0ae45d1a8d25aa5c2e746ac"
  },
  "access": {
    "token": "32361d0d17084bedb9fcbca9b4d30c34",
    "transfer": "52beb4650cae480ba5cfc92a16b90b03"
  }
}

