POST /api/2.5/transfers HTTP/1.0
Authorization: Bearer broker1
Content-Length: 12
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {}
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "transfer": "6109ccb1b9d44715876fcef5701b3260", 
    "token": "6827cd0ece6f4891a00cf118b33268e3"
  }, 
  "data": {
    "date": "2020-05-15T01:00:00+03:00", 
    "id": "cfd9e57ce9704ad2a954a79cbfe78d21"
  }
}

