POST /api/2.5/transfers HTTP/1.0
Authorization: Bearer broker3
Content-Length: 12
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {}
}


HTTP/1.0 201 Created
Content-Type: application/json

{
  "data": {
    "date": "2023-10-10T01:00:00+03:00",
    "id": "2a02430274e84ecf96ac807e69027304"
  },
  "access": {
    "token": "5dd784d6228c4abb9d509c3d86c604ca",
    "transfer": "ac8fe7e20bac48f1b43ac294f28f6148"
  }
}

