POST /api/2.5/transfers HTTP/1.0
Authorization: Bearer broker1
Content-Length: 12
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {}
}


HTTP/1.0 201 Created
Content-Type: application/json

{
  "data": {
    "date": "2023-01-01T00:00:00+02:00",
    "id": "427c7cffd9bb4f1db70399d857501ca5"
  },
  "access": {
    "token": "59c78f8d7a9f4dd9ba83db1835329029",
    "transfer": "ce2b8807a617410aa8a7f2746707ee31"
  }
}

