POST /api/2.5/transfers HTTP/1.0
Authorization: Bearer broker3
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {}
}


HTTP/1.0 201 Created
Content-Type: application/json

{
  "data": {
    "date": "2023-10-10T01:00:00+03:00",
    "id": "0a30abb09f71439fa89d9a4c5bb50ea4"
  },
  "access": {
    "token": "08f1d49be1284d93b4a95928f9028b33",
    "transfer": "9763efce634449088e1683021b9db077"
  }
}

