GET /api/2.5/transfers/6db42685af9a45eda91d17077009fee7 HTTP/1.0
Authorization: Bearer broker3
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "date": "2020-09-08T01:00:00+03:00",
    "usedFor": "/agreements/0c6c916713f643eb91c4fa2ddea54cc7",
    "id": "6db42685af9a45eda91d17077009fee7"
  }
}

