GET /api/2.5/transfers/d1ef34a0f35740e5961646fccef522e4 HTTP/1.0
Authorization: Bearer broker3
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "date": "2021-03-16T00:00:00+02:00",
    "usedFor": "/contracts/2b264b733b7546749561d03ffa5e7971",
    "id": "d1ef34a0f35740e5961646fccef522e4"
  }
}

