PATCH /api/2.5/agreements/35990a4bc5c748a68bd8970a17f938de?acc_token=8f09214cf01c4a27a7403459607d4a6c HTTP/1.0
Authorization: Bearer broker3
Content-Length: 71
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "terminationDetails": "broker3 now can change the contract"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "agreementID": "UA-2018-07-30-000001-afe4b1ed046845bcae5d675b0b8ca5aa1", 
    "status": "active", 
    "contracts": [
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 100.0, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "1662b0e1d59f4e2f8e2c5bd48e03a7bc"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ], 
        "bidID": "0a292b6466274139ad3d973fd64830ff", 
        "date": "2018-07-30T17:40:15.471158+03:00", 
        "awardID": "d7406b07c05b4796bb168a7c47ee7d31", 
        "id": "d6cd8c3188d74e1481a9cebb57fd9329"
      }, 
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 100.0, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "1662b0e1d59f4e2f8e2c5bd48e03a7bc"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ], 
        "bidID": "d85ef51272f14087abb2eed535340493", 
        "date": "2018-07-30T17:40:15.471207+03:00", 
        "awardID": "cdb6da320600480d8eaabd8eaa920872", 
        "id": "c8ef8c0d1cb74528b13335a623225762"
      }, 
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 100.0, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "1662b0e1d59f4e2f8e2c5bd48e03a7bc"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ], 
        "bidID": "fc02090c338a477f8013156a4fa2da10", 
        "date": "2018-07-30T17:40:15.471264+03:00", 
        "awardID": "a915a07f7f0b4dafa583cce119bf1823", 
        "id": "d925d6c6124447d581f2ae5f52ba710f"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "1662b0e1d59f4e2f8e2c5bd48e03a7bc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "dateSigned": "2020-05-15T01:00:00+03:00", 
    "id": "35990a4bc5c748a68bd8970a17f938de", 
    "numberOfContracts": 3, 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }, 
      "contactPoint": {
        "name_en": "State administration", 
        "name": "Державне управління справами", 
        "availableLanguage": "uk", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "dus.gov.ua", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name_en": "State administration"
    }, 
    "terminationDetails": "broker3 now can change the contract", 
    "owner": "broker3", 
    "dateModified": "2020-05-15T01:00:00+03:00", 
    "tender_id": "f0dce4b8a8954b28ba318663bb91b15b"
  }
}

