PATCH /api/2.5/plans/f0b2403cba3040acaaf3d6d45dc953be?acc_token=6827cd0ece6f4891a00cf118b33268e3 HTTP/1.0
Authorization: Bearer broker1
Content-Length: 72
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "budget": {
      "description": "broker1 now can change the plan"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "scheduled", 
    "buyers": [
      {
        "kind": "general", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "111983", 
          "legalName": "ДП Державне Управління Справами"
        }, 
        "name": "ДУС", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "classification": {
      "scheme": "ДК021", 
      "description": "Seeds", 
      "id": "03111000-2"
    }, 
    "items": [
      {
        "description": "Насіння гірчиці", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Mustard seeds", 
          "id": "03111600-8"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "01.11.92", 
            "description": "Насіння гірчиці"
          }
        ], 
        "deliveryDate": {
          "startDate": "2020-05-17T01:00:00+03:00", 
          "endDate": "2020-05-20T01:00:00+03:00"
        }, 
        "id": "3b769e31f1b34febb698f583d5e264cd", 
        "unit": {
          "code": "KGM", 
          "name": "кг"
        }, 
        "quantity": 1000.0
      }, 
      {
        "description": "Насіння соняшнику", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Sunflower seeds", 
          "id": "03111300-5"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "01.11.95", 
            "description": "Насіння соняшнику"
          }
        ], 
        "deliveryDate": {
          "startDate": "2020-05-17T01:00:00+03:00", 
          "endDate": "2020-05-20T01:00:00+03:00"
        }, 
        "id": "88433532a143404988f063275f2a32a2", 
        "unit": {
          "code": "KGM", 
          "name": "кг"
        }, 
        "quantity": 2000.0
      }, 
      {
        "description": "Насіння бавовнику", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cotton seeds", 
          "id": "03111400-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "01.11.84", 
            "description": "Насіння бавовнику"
          }
        ], 
        "deliveryDate": {
          "startDate": "2020-05-17T01:00:00+03:00", 
          "endDate": "2020-05-20T01:00:00+03:00"
        }, 
        "id": "70f99b652a404d8e861f7c06543dd125", 
        "unit": {
          "code": "KGM", 
          "name": "кг"
        }, 
        "quantity": 3000.0
      }
    ], 
    "planID": "UA-P-2020-05-15-000001", 
    "budget": {
      "breakdown": [
        {
          "title": "other", 
          "description": "Breakdown other description.", 
          "value": {
            "currency": "UAH", 
            "amount": 1500.0
          }, 
          "id": "73d48f06e2124fbdbffe23cb37a0c417"
        }
      ], 
      "amountNet": 12222.0, 
      "description": "broker1 now can change the plan", 
      "period": {
        "startDate": "2020-01-01T00:00:00+02:00", 
        "endDate": "2020-12-31T00:00:00+02:00"
      }, 
      "project": {
        "id": "123", 
        "name": "proj_name"
      }, 
      "currency": "UAH", 
      "amount": 10000.0, 
      "id": "12303111000-2"
    }, 
    "datePublished": "2020-05-15T01:00:00+03:00", 
    "tender": {
      "procurementMethod": "open", 
      "procurementMethodType": "belowThreshold", 
      "tenderPeriod": {
        "startDate": "2020-05-22T01:00:00+03:00"
      }
    }, 
    "additionalClassifications": [
      {
        "scheme": "КЕКВ", 
        "id": "1", 
        "description": "-"
      }
    ], 
    "procuringEntity": {
      "kind": "general", 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "111983", 
        "legalName": "ДП Державне Управління Справами"
      }, 
      "name": "ДУС", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker1", 
    "dateModified": "2020-05-15T01:00:00+03:00", 
    "id": "f0b2403cba3040acaaf3d6d45dc953be"
  }
}

