PATCH /api/2.5/tenders/13ebe09f71f241dcbda5bef5669bc60c/bids/8a026030cc98450eb55797d1ccd65d16?acc_token=d0908b985b6c4aac9713a43acb56303b HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "telephone": "+380950000000",
          "email": "example@email.com",
          "iban": "111111111111111",
          "authorizedBy": "Статут компанії",
          "position": "Генеральний директор"
        }
      }
    ],
    "status": "draft",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "lotValues": [
      {
        "value": {
          "amount": 500
        },
        "relatedLot": "043d36ce0feb4d0db21e430faa9019a2"
      }
    ],
    "items": [
      {
        "id": "ffffffffffffffffffffffffffffffff",
        "description": "футляри до державних нагород",
        "description_en": "Cases with state awards",
        "description_ru": "футляры к государственным наградам",
        "unit": {
          "name": "кілограм",
          "value": {
            "amount": 7,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 4
      }
    ]
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "lotValues": [
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "043d36ce0feb4d0db21e430faa9019a2",
        "status": "pending",
        "date": "2023-10-10T01:00:00+03:00"
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "email": "example@email.com",
          "telephone": "+380950000000",
          "iban": "111111111111111",
          "position": "Генеральний директор",
          "authorizedBy": "Статут компанії"
        }
      }
    ],
    "status": "draft",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "id": "8a026030cc98450eb55797d1ccd65d16",
    "date": "2023-10-10T01:00:00+03:00",
    "items": [
      {
        "id": "ffffffffffffffffffffffffffffffff",
        "description": "футляри до державних нагород",
        "description_en": "Cases with state awards",
        "description_ru": "футляры к государственным наградам",
        "unit": {
          "name": "кілограм",
          "value": {
            "amount": 7.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 4.0
      }
    ]
  }
}

