PATCH /api/2.5/tenders/3f5ff57c43ca4ba6b3a1d0619b7a14c3/awards/d51b0b66a19642af8d821963a6f06861?acc_token=312a92a0096444fa9b9761b0af134205 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active",
    "qualified": false
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "qualified",
      "description": [
        "Can't update award to active status with not qualified"
      ]
    }
  ]
}

