GET /api/2.5/tenders/f2ffdfd3a21b4081841738915486b18b/bids/8d8c35d315ec458aa2bf51fdcef0717b?acc_token=79216c37bfd34cdbbe3d8690f78639cb HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "status": "active",
    "id": "8d8c35d315ec458aa2bf51fdcef0717b",
    "date": "2023-10-16T01:00:02+03:00",
    "lotValues": [
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "b670ed4c0ed845cab0b7eb532fe4fe3f",
        "status": "active",
        "date": "2023-10-16T01:00:02+03:00",
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/f2ffdfd3a21b4081841738915486b18b_b670ed4c0ed845cab0b7eb532fe4fe3f?key_for_bid=8d8c35d315ec458aa2bf51fdcef0717b"
      }
    ],
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/20d128e9e0d94b378f0d20eff02ff88a?Signature=QS7hf8dU8Isr0Gx2mdwGuwjLDNmtMoB5LiUhr9Tr9YS6ojYM4GK8efB0rqFu%2FXzy7Uma7Qi50c5nWl%2BFVfzqDQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "020bda3b235b4a65a9b4b1b37d7a162a",
        "confidentiality": "public",
        "datePublished": "2023-10-16T01:00:02+03:00",
        "dateModified": "2023-10-16T01:00:02+03:00"
      }
    ]
  }
}

