GET /api/2.5/tenders/3f5ff57c43ca4ba6b3a1d0619b7a14c3/bids/9a6691c52a6e40478d3057022922c776?acc_token=db886e7c3bb649edb5893b47afcb0f05 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-IPN",
          "id": "00137226",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр 2»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Андрій Олексюк",
          "email": "aagt@gmail.com",
          "telephone": "+380322916930"
        },
        "scale": "sme"
      }
    ],
    "status": "draft",
    "documents": [
      {
        "confidentiality": "public",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cf174abb36e944eb8ca48f1afe8eb4d2?Signature=nhY11nzZvoAKjFc3a%2FPpyp9%2BxrzoIXCWAYyrTlcJ%2FVzF6BLISq%2FmFK7mkqMFMxpbHQrYyJ%2B0DcVJExrJdvE1DA%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "b57bff4881434c139ba83f203f41d9dc",
        "datePublished": "2023-10-16T01:15:06+03:00",
        "dateModified": "2023-10-16T01:15:06+03:00"
      },
      {
        "confidentiality": "public",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fa5035ab921b4fb2888800987217ada4?Signature=9meqwsW99XL5YpmHvnJQjExFMu2X6to3Wor7h88g%2F%2FV5eb6%2FfKI%2B872U0tVny68LXkJ0GMTjT2raZPL%2BOC%2BXAQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "language": "uk",
        "id": "6dedbd358d08409eac7efb40cb71f63d",
        "datePublished": "2023-10-16T01:15:06+03:00",
        "dateModified": "2023-10-16T01:15:06+03:00"
      }
    ],
    "items": [
      {
        "id": "ffffffffffffffffffffffffffffffff",
        "description": "папір",
        "unit": {
          "value": {
            "amount": 0.6,
            "currency": "UAH",
            "valueAddedTaxIncluded": true
          },
          "code": "KGM"
        },
        "quantity": 5.0
      }
    ],
    "lotValues": [
      {
        "status": "pending",
        "value": {
          "amount": 499.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "987404b67a4c4d888112d4e9755edefc",
        "date": "2023-10-16T01:15:06+03:00",
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/3f5ff57c43ca4ba6b3a1d0619b7a14c3_987404b67a4c4d888112d4e9755edefc?key_for_bid=9a6691c52a6e40478d3057022922c776"
      }
    ],
    "id": "9a6691c52a6e40478d3057022922c776",
    "date": "2023-10-16T01:15:06+03:00"
  }
}

