GET /api/2.5/tenders/63fbe5f55ec14294b590969e4ec72af6/questions/f937991b12f343b89e5bae6b87080cdb HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "f937991b12f343b89e5bae6b87080cdb",
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2023-01-01T00:00:01+02:00",
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
    "questionOf": "tender",
    "dateAnswered": "2023-01-01T00:00:01+02:00"
  }
}

