PATCH /api/2.5/tenders/a7b9a682e7474cf7841bf6a8139238cc?acc_token=ae6fe916e0db4b65966bad37e333cadb HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderPeriod": {
      "startDate": "2023-10-20T01:00:00+03:00",
      "endDate": "2023-10-25T01:00:00+03:00"
    }
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "funders": [
      {
        "name": "Глобальний фонд",
        "identifier": {
          "scheme": "XM-DAC",
          "id": "47045",
          "legalName": "Глобальний Фонд для боротьби зі СНІДом, туберкульозом і малярією"
        },
        "address": {
          "streetAddress": "Global Health Campus, Chemin du Pommier 40",
          "locality": "Geneva",
          "region": "Grand-Saconnex",
          "postalCode": "1218",
          "countryName": "Швейцарська Конфедерація"
        },
        "contactPoint": {
          "name": "",
          "email": "ccm@theglobalfund.org",
          "telephone": "+41587911700",
          "faxNumber": "+41 44 580 6820",
          "url": "https://www.theglobalfund.org/en/"
        }
      }
    ],
    "date": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "dateCreated": "2023-10-10T01:00:00+03:00",
    "tenderID": "UA-2023-10-10-000001-a",
    "status": "active.enquiries",
    "owner": "broker",
    "title": "футляри до державних нагород",
    "mainProcurementCategory": "goods",
    "inspector": {
      "name": "Компанія Контролер",
      "identifier": {
        "scheme": "XM-DAC",
        "id": "47045",
        "legalName": "Глобальний Фонд для боротьби зі СНІДом, туберкульозом і малярією"
      },
      "address": {
        "streetAddress": "Global Health Campus, Chemin du Pommier 40",
        "locality": "Geneva",
        "region": "Grand-Saconnex",
        "postalCode": "1218",
        "countryName": "Швейцарська Конфедерація"
      },
      "contactPoint": {
        "name": "",
        "email": "ccm@theglobalfund.org",
        "telephone": "+41587911700",
        "faxNumber": "+41 44 580 6820",
        "url": "https://www.theglobalfund.org/en/"
      }
    },
    "reviewRequests": [
      {
        "id": "6b0f5c1e8c1641348b8107d2c3ec1e06",
        "tenderStatus": "active.enquiries",
        "dateCreated": "2023-10-10T01:00:00+03:00"
      }
    ],
    "procurementMethod": "open",
    "submissionMethod": "electronicAuction",
    "awardCriteria": "lowestCost",
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "minimalStep": {
      "amount": 15.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderPeriod": {
      "startDate": "2023-10-20T01:00:00+03:00",
      "endDate": "2023-10-25T01:00:00+03:00"
    },
    "items": [
      {
        "id": "ffffffffffffffffffffffffffffffff",
        "description": "футляри до державних нагород",
        "description_en": "Cases with state awards",
        "description_ru": "футляры к государственным наградам",
        "unit": {
          "name": "кілограм",
          "value": {
            "amount": 6.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": true
          },
          "code": "KGM"
        },
        "quantity": 5.0,
        "classification": {
          "description": "Cartons",
          "scheme": "ДК021",
          "id": "44617100-9"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ]
      }
    ],
    "lots": [
      {
        "title": "lot title",
        "description": "lot description",
        "status": "active",
        "id": "c5688ea55ff244c7815a7c00dcf5f23c",
        "date": "2023-10-10T01:00:00+03:00",
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "minimalStep": {
          "amount": 15.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        }
      }
    ],
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "type": "financing",
        "code": "prepayment",
        "percentage": 45.55,
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 0
      },
      {
        "id": "0683f2311f1642cab50f792f4f48d0df",
        "title": "deliveryOfGoods",
        "type": "financing",
        "code": "postpayment",
        "percentage": 54.45,
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 0
      }
    ],
    "procurementMethodType": "belowThreshold",
    "procuringEntity": {
      "name": "Державне управління справами",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "00037256",
        "uri": "http://www.dus.gov.ua/"
      },
      "address": {
        "streetAddress": "вул. Банкова, 11, корпус 1",
        "locality": "м. Київ",
        "region": "м. Київ",
        "postalCode": "01220",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Державне управління справами",
        "telephone": "+0440000000"
      },
      "kind": "general"
    },
    "enquiryPeriod": {
      "startDate": "2023-10-10T01:00:00+03:00",
      "clarificationsUntil": "2023-10-19T00:00:00+03:00",
      "endDate": "2023-10-17T00:00:00+02:00"
    },
    "id": "a7b9a682e7474cf7841bf6a8139238cc"
  },
  "config": {
    "hasAuction": true,
    "hasAwardingOrder": true,
    "hasValueRestriction": true,
    "valueCurrencyEquality": true,
    "hasPrequalification": false,
    "minBidsNumber": 1,
    "hasPreSelectionAgreement": false,
    "hasTenderComplaints": false,
    "hasAwardComplaints": false,
    "hasCancellationComplaints": false,
    "hasQualificationComplaints": false,
    "restricted": false
  }
}

