PATCH /api/2.5/tenders/65a98054143d45088661b24539750092?acc_token=817d29c5555b4faebb97e579705ba8d7 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "description": "Оновлений опис"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "With unanswered review request can be patched only ('tenderPeriod',) fields"
    }
  ]
}

