POST /api/2.5/tenders/f135bade563d49fc9233e1f1d37fdcf0/bids HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Вінниця",
          "postalCode": "21100",
          "region": "Вінницька область",
          "streetAddress": "вул. Островського, 33"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "name": "Сергій Олексюк",
          "telephone": "+380432216930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Школяр»",
        "scale": "micro",
        "signerInfo": {
          "name": "Test Testovich",
          "telephone": "+380950000000",
          "email": "example@email.com",
          "iban": "111111111111111",
          "authorizedBy": "Статут компанії",
          "position": "Генеральний директор"
        }
      }
    ],
    "status": "draft",
    "items": [
      {
        "quantity": 5,
        "description": "папір",
        "id": "ffffffffffffffffffffffffffffffff",
        "unit": {
          "code": "KGM",
          "value": {
            "amount": 1500,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          }
        }
      }
    ],
    "lotValues": [
      {
        "value": {
          "amount": 500
        },
        "relatedLot": "d6fba8716672449f87efa3a5781c7760"
      }
    ]
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "items",
      "description": "Total amount of unit values can't be greater than bid.lotValues.value.amount"
    }
  ]
}

