PATCH /api/2.5/tenders/a7b9a682e7474cf7841bf6a8139238cc/review_requests/6b0f5c1e8c1641348b8107d2c3ec1e06 HTTP/1.0
Authorization: Bearer inspector
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "approved": true
  }
}


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Disallowed re-patching review request"
    }
  ]
}

