GET /api/2.5/tenders/f2ffdfd3a21b4081841738915486b18b/contracts/d2abf7a11c2f41dcb848fb5f3f85841f/documents HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "contract_first_document.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e0a6ba4e927a4b37a419f00d99d0e1e2?Signature=FFuxQi4SZOran3sYI4B5RwlM7yntAVrvYMb9zm1GR%2FN1d9BMuK%2FTMdTj10USzad1sVWV11XuVnCjZ5DwmQvMBw%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "8df1b1464a774b09a31c7ff0b79a2907",
      "datePublished": "2023-01-01T00:00:03+02:00",
      "dateModified": "2023-01-01T00:00:03+02:00"
    }
  ]
}

