GET /api/2.5/tenders/3f5ff57c43ca4ba6b3a1d0619b7a14c3/documents HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "confidentiality": "public",
      "documentType": "notice",
      "id": "61f2dae4bb484ed293654ea67264f529",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "hash": "md5:00000000000000000000000000000000",
      "title": "sign.p7s",
      "format": "sign/pkcs7-signature",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cdb6e7cdd13c424ca6d701372a9e7de1?Signature=%2B4SXU9Ao9xR1zTNFK4AzMIh%2BFZN4b25SfjdO69%2FfmaM8%2FcKMeDB0Xa2jCG%2FgA25Q5u3c5StwiOD10dl8ZqyEAw%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "dateModified": "2023-10-10T01:00:00+03:00",
      "author": "tender_owner",
      "language": "uk"
    },
    {
      "confidentiality": "public",
      "documentType": "technicalSpecifications",
      "description": "змінений опис документа",
      "description_en": "document description modified",
      "relatedItem": "ffffffffffffffffffffffffffffffff",
      "id": "dcc28f9e5b0a4475ae1511c9195924ba",
      "datePublished": "2023-10-10T01:00:01+03:00",
      "hash": "md5:00000000000000000000000000000000",
      "title": "Notice.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6d5acc9f6744445090ee6163719b792e?Signature=sgMJT6uclURHXV1QkzMq700s6436i6ynr4LaZyZf5B4O1Sn6ed7A8ogX5x1LCHhuC5HKuPrXHgPRYIyDC6H%2BDg%3D%3D&KeyID=a8968c46",
      "documentOf": "item",
      "dateModified": "2023-10-10T01:03:03+03:00",
      "author": "tender_owner",
      "language": "uk"
    },
    {
      "confidentiality": "public",
      "hash": "md5:00000000000000000000000000000000",
      "title": "AwardCriteria.pdf",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8b660719e71c4e3b80ac24648fac52c2?Signature=KztTkrH3lsmZaP%2BWO8J%2BbI7PYNNV%2FDEQjh%2BizLUhw8aULUu%2BxQgMmxFapPOUaK4nNViYOHS8wZXvQIukYB2EAg%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "9e36c772ea13480da2398a2c2bd63fe5",
      "datePublished": "2023-10-10T01:06:04+03:00",
      "dateModified": "2023-10-10T01:06:04+03:00",
      "author": "tender_owner"
    }
  ]
}

