POST /api/2.5/tenders/f2ffdfd3a21b4081841738915486b18b/contracts/eba027869cb94b11a905524a11ee7efd/documents?acc_token=b8bbe7f96c0a4205be28146aec83c55b HTTP/1.0
Authorization: Bearer broker
Content-Length: 343
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "contract_second_document.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/05425e3b32d940e3a6517b4a76c6318f?Signature=Qzl9WJq8T8ceul6BsXjCyQlf2I%2F3wpM6tNBgij3fHh1H4tc33cIkSUyIWiQk7sv8pWJjlOF%2F7DLdnkbxRriCBw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f2ffdfd3a21b4081841738915486b18b/contracts/eba027869cb94b11a905524a11ee7efd/documents/89ac9d103b734029abf03372b8a7ba4d

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "contract_second_document.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/05425e3b32d940e3a6517b4a76c6318f?Signature=%2FYRZ%2B%2BRtFSyc1fRd7U3XC1JzzD8NRsKvmiPxbIxu3tC2RImeoRJr9W%2FiDeEO2nWheF2%2BuWjigqJR0CMp8ltlBg%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "id": "89ac9d103b734029abf03372b8a7ba4d",
    "datePublished": "2023-01-01T00:00:03+02:00",
    "dateModified": "2023-01-01T00:00:03+02:00"
  }
}

