POST /api/2.5/tenders/39a36a1c01d8459faf619c1481e2d5b1/bids/33057dbe122b47bdbc75209e460404d9/documents?acc_token=b8e62cbf0dbb4c1cbb370a089a061b39 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Proposal.p7s",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/836c459581154a94a5724e8a9d1bd2d7?Signature=2Er4aTPTpSnS7m84A%2FnGIDuvxIssZq%2FuPYCOhbPkQKyxkond6h0NPVxEIHb9F3auZOMItN9f3D0zdERF8dobCQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "sign/p7s",
    "documentType": "proposal"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/39a36a1c01d8459faf619c1481e2d5b1/bids/33057dbe122b47bdbc75209e460404d9/documents/95bd28be87764822baa30b2c3b49cff1

{
  "data": {
    "confidentiality": "public",
    "documentType": "proposal",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Proposal.p7s",
    "format": "sign/p7s",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/836c459581154a94a5724e8a9d1bd2d7?Signature=aCHxPA7NTD6PoCedHE%2F0avor7ALdbQ8Q0%2FoMn0NwRLy2s7ejC%2Bg0BS%2FfkLolAchWSbcOuDNHVIAmCU2%2BzuNpCA%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "95bd28be87764822baa30b2c3b49cff1",
    "datePublished": "2027-01-07T00:14:06+02:00",
    "dateModified": "2027-01-07T00:14:06+02:00"
  }
}

