GET /api/2.5/tenders/1e1c35ea6a97449c857edabef72e7225/bids/3b5a43dccff7435e8804725da791748a?acc_token=c817e0e9fb944e688d38ad4112e954d0 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "value": {
      "amount": 499.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "telephone": "+380322916930",
          "name": "Андрій Олексюк"
        },
        "scale": "sme"
      }
    ],
    "status": "draft",
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4723ad37c9a04058983e5acc8d0ce9f4?Signature=0ZVrM3IuFoNW6QI1eBPPulKeh2ywRON%2Fwp8nKbq7KJPS8w5gx4Tod6BQpwOwiAudl9IK%2BZ7ql7%2BA0kcRAeLjBg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "id": "6318870c769043a0befb2bafefa8235f",
        "datePublished": "2021-03-16T00:00:01+02:00",
        "dateModified": "2021-03-16T00:00:01+02:00"
      },
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/200d1dfb2afc4cf791ec2fea005cefde?Signature=vYRIxu%2F3oNjZ5mS1jHC3LFWwaYWC6jkFS4ilfqT%2B3cs75hjSzwVqfOXfYkKe0maf4S88STYJeupj6X%2FfGDMDDg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "id": "b3119f062b234153a2492ff927fcb365",
        "datePublished": "2021-03-16T00:00:01+02:00",
        "dateModified": "2021-03-16T00:00:01+02:00"
      }
    ],
    "id": "3b5a43dccff7435e8804725da791748a",
    "date": "2021-03-16T00:00:01+02:00",
    "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/1e1c35ea6a97449c857edabef72e7225?key_for_bid=3b5a43dccff7435e8804725da791748a"
  }
}

