PATCH /api/2.5/tenders/1e1c35ea6a97449c857edabef72e7225/documents/31d47ffc884f4127b55eba8f3bad8f3e?acc_token=2ad39bcd6fe242ed8dec876c5c6130cf HTTP/1.0
Authorization: Bearer broker
Content-Length: 58
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "document description modified"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "documentType": "technicalSpecifications",
    "description": "document description modified",
    "id": "31d47ffc884f4127b55eba8f3bad8f3e",
    "datePublished": "2023-01-01T00:00:01+02:00",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ae50ebf41e54463faca2b20961cec265?Signature=vwVV5yBxoQF9tqHPeCmryD53w8gnll1fHTDbd5zeJaxFY0yt9pqIso9lPTh6uoOq9oM42i%2FfziR1dRPW08mAAQ%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "dateModified": "2023-01-01T00:00:01+02:00",
    "author": "tender_owner"
  }
}

