PATCH /api/2.5/tenders/6e437e5d477a451f955ef1f9ad2cca7c/bids/fca5f46a77484fe09b1038555f0e2bb2?acc_token=00ae749dfd5e4e55bfc9726e32db2c93 HTTP/1.0
Authorization: Bearer token
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 422 Unprocessable Entity
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "requirementResponses",
      "description": [
        "Inside criteria must be answered only one requirement group"
      ]
    }
  ]
}

