PATCH /api/2.5/tenders/28620043ada5424cbbfbdc7f6246096f/criteria/1d3d0c833904401a9c378e7e171c68ba/requirement_groups/2d2d30613e824b4fb3651404df351f4b/requirements/d3a5444cc18b4a1b822b83397b2b7d5f?acc_token=b00ba6728a854f2aa3959cc53ebab5d8 HTTP/1.0
Authorization: Bearer broker
Content-Length: 726
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "eligibleEvidences": [
      {
        "title": "Документальне підтвердження",
        "description": "Довідка в довільній формі",
        "type": "document"
      },
      {
        "title": "Документальне підтвердження",
        "description": "Довідка в довільній формі",
        "type": "statement"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "d3a5444cc18b4a1b822b83397b2b7d5f",
    "title": "Updated title",
    "dataType": "boolean",
    "eligibleEvidences": [
      {
        "id": "8d6ce4abf8d44164843866b82f99fb86",
        "title": "Документальне підтвердження",
        "description": "Довідка в довільній формі",
        "type": "document"
      },
      {
        "id": "cc0ffe22dcc149eb8eeefc746c61d967",
        "title": "Документальне підтвердження",
        "description": "Довідка в довільній формі",
        "type": "statement"
      }
    ],
    "expectedValue": "true",
    "status": "active",
    "datePublished": "2021-03-16T00:00:00+02:00"
  }
}

