PATCH /api/2.5/tenders/24660b6d159d42adb6aaba9d978575c7/bids/9e2ee09e73b94c1aab0be7ed1f2c9bd9?acc_token=f0760e708e124c8fb9f34e562dbf59cf HTTP/1.0
Authorization: Bearer token
Content-Length: 3612
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "requirementResponses": [
      {
        "requirement": {
          "id": "53f799fd59d04ff18875d7d7c32a20ca", 
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        }, 
        "evidences": [
          {
            "type": "document", 
            "relatedDocument": {
              "id": "edd9dc8d53004504a450acdf5953472f", 
              "title": "name.doc"
            }, 
            "title": "Requirement response"
          }
        ], 
        "description": "some description", 
        "value": "True", 
        "title": "Requirement response 1"
      }, 
      {
        "requirement": {
          "id": "2f00406edaa743e59b4fab4e22cceea4", 
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        }, 
        "evidences": [
          {
            "type": "document", 
            "relatedDocument": {
              "id": "edd9dc8d53004504a450acdf5953472f", 
              "title": "name.doc"
            }, 
            "title": "Requirement response"
          }
        ], 
        "description": "some description", 
        "value": "True", 
        "title": "Requirement response 2"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "draft", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "bid_owner", 
        "language": "uk", 
        "title": "name.doc", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/24660b6d159d42adb6aaba9d978575c7/bids/9e2ee09e73b94c1aab0be7ed1f2c9bd9/documents/edd9dc8d53004504a450acdf5953472f?download=9eb943ac564f4a18a54c4020b0a02370", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2020-09-08T01:00:00+03:00", 
        "id": "edd9dc8d53004504a450acdf5953472f", 
        "dateModified": "2020-09-08T01:00:00+03:00", 
        "confidentiality": "public"
      }
    ], 
    "id": "9e2ee09e73b94c1aab0be7ed1f2c9bd9", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "requirementResponses": [
      {
        "requirement": {
          "id": "53f799fd59d04ff18875d7d7c32a20ca", 
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        }, 
        "description": "some description", 
        "title": "Requirement response 1", 
        "value": "True", 
        "evidences": [
          {
            "title": "Requirement response", 
            "type": "document", 
            "relatedDocument": {
              "id": "edd9dc8d53004504a450acdf5953472f", 
              "title": "name.doc"
            }, 
            "id": "4e431408a75448aea6225750a67fabf8"
          }
        ], 
        "id": "8c594ce61a2a455dacb061dc35ae71c0"
      }, 
      {
        "requirement": {
          "id": "2f00406edaa743e59b4fab4e22cceea4", 
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        }, 
        "description": "some description", 
        "title": "Requirement response 2", 
        "value": "True", 
        "evidences": [
          {
            "title": "Requirement response", 
            "type": "document", 
            "relatedDocument": {
              "id": "edd9dc8d53004504a450acdf5953472f", 
              "title": "name.doc"
            }, 
            "id": "a8dd645e36a54ed688ac59322f2dff89"
          }
        ], 
        "id": "59eea6bd3e674a169055f680e77023a4"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2020-09-08T01:00:00+03:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "selfQualified": true
  }
}

