POST /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "items": [
      {
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "description": "Послуги шкільних їдалень",
        "deliveryDate": {
          "startDate": "2023-10-30T00:00:00+02:00",
          "endDate": "2023-11-29T00:00:00+02:00"
        },
        "deliveryAddress": {
          "countryName": "Україна",
          "postalCode": "79000",
          "region": "м. Київ",
          "locality": "м. Київ",
          "streetAddress": "вул. Банкова 1"
        },
        "classification": {
          "description": "Послуги з харчування у школах",
          "id": "55523100-3",
          "scheme": "ДК021"
        },
        "unit": {
          "code": "KGM",
          "name": "папір",
          "value": {
            "amount": 10
          }
        },
        "quantity": 1
      }
    ],
    "procurementMethod": "limited",
    "procurementMethodType": "reporting",
    "status": "draft",
    "procuringEntity": {
      "kind": "special",
      "address": {
        "countryName": "Україна",
        "locality": "м. Вінниця",
        "postalCode": "21027",
        "region": "Вінницька область",
        "streetAddress": "вул. Стахурського. 22"
      },
      "contactPoint": {
        "name": "Куца Світлана Валентинівна",
        "telephone": "+380432465302",
        "url": "http://sch10.edu.vn.ua/"
      },
      "identifier": {
        "id": "21725150",
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\"",
        "scheme": "UA-EDR"
      },
      "name": "ЗОСШ #10 м.Вінниці",
      "signerInfo": {
        "name": "Test Testovich",
        "telephone": "+380950000000",
        "email": "example@email.com",
        "iban": "111111111111111",
        "authorizedBy": "Статут компанії",
        "position": "Генеральний директор"
      }
    },
    "value": {
      "amount": 500000,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "title": "Послуги шкільних їдалень",
    "title_en": "Services in school canteens",
    "title_ru": "Услуги школьных столовых",
    "description_en": "Services in school canteens",
    "description_ru": "Услуги школьных столовых",
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "code": "prepayment",
        "type": "financing",
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 1,
        "percentage": 45.55
      },
      {
        "title": "deliveryOfGoods",
        "code": "postpayment",
        "type": "financing",
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 2,
        "percentage": 54.45
      }
    ],
    "mainProcurementCategory": "services"
  },
  "config": {
    "hasAuction": false,
    "hasAwardingOrder": true,
    "hasValueRestriction": true,
    "valueCurrencyEquality": true,
    "hasPrequalification": false,
    "minBidsNumber": 1,
    "hasPreSelectionAgreement": false,
    "hasTenderComplaints": false,
    "hasAwardComplaints": false,
    "hasCancellationComplaints": false,
    "hasValueEstimation": true,
    "hasQualificationComplaints": false,
    "tenderComplainRegulation": 0,
    "qualificationComplainDuration": 0,
    "awardComplainDuration": 0,
    "cancellationComplainDuration": 0,
    "clarificationUntilDuration": 0,
    "qualificationDuration": 0,
    "minTenderingDuration": 0,
    "hasEnquiries": false,
    "minEnquiriesDuration": 0,
    "enquiryPeriodRegulation": 0,
    "restricted": false
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "cause",
      "description": [
        "This field is required."
      ]
    }
  ]
}

