PATCH /api/2.5/tenders/378a1443b2704a2e9f13816acfe5898f/cancellations/6054bd855b294491819137282bde25e8?acc_token=31c9e71e63b64c82b49271b02ebc3c7b HTTP/1.0
Authorization: Bearer broker
Content-Length: 41
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "dateViolation"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "6054bd855b294491819137282bde25e8",
    "reason": "cancellation reason",
    "date": "2021-03-16T00:00:00+02:00",
    "status": "draft",
    "cancellationOf": "tender",
    "reasonType": "dateViolation"
  }
}

