POST /api/2.5/tenders/88931568088f426f904ce068a0ddb436/cancellations?acc_token=7237424e038245daa54b2314ed11748f HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reason": "cancellation reason",
    "reasonType": "noDemand",
    "status": "draft"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/88931568088f426f904ce068a0ddb436/cancellations/502423358d1e4268877befdb0880d619

{
  "data": {
    "status": "draft",
    "reasonType": "noDemand",
    "reason": "cancellation reason",
    "id": "502423358d1e4268877befdb0880d619",
    "date": "2027-01-01T00:00:00+02:00",
    "cancellationOf": "tender"
  }
}

