PATCH /api/2.5/tenders/07a9d2daabfe4268a5b3f6db5a7e1287/contracts/7c82c25de63348eea5afb981c0fc2f54?acc_token=63a33032ef0d47108bdada9cf1f0dde0 HTTP/1.0
Authorization: Bearer broker
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "7c82c25de63348eea5afb981c0fc2f54",
    "awardID": "9781a8bdca8d4bd0bb7eb110bb33f809",
    "contractID": "UA-2023-01-01-000001-a-1",
    "status": "active",
    "value": {
      "amount": 475000.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": false,
      "amountNet": 475000.0
    },
    "items": [
      {
        "id": "7e6d418b001e4a0fbe86d048f86ba39a",
        "description": "Послуги шкільних їдалень",
        "classification": {
          "description": "Послуги з харчування у школах",
          "scheme": "ДК021",
          "id": "55523100-3"
        },
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "unit": {
          "name": "папір",
          "value": {
            "amount": 10.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          },
          "code": "KGM"
        },
        "quantity": 1.0,
        "deliveryDate": {
          "startDate": "2023-01-21T00:00:00+02:00",
          "endDate": "2023-02-20T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        }
      }
    ],
    "suppliers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "date": "2023-01-01T00:00:01+02:00",
    "dateSigned": "2023-01-01T00:00:01+02:00"
  }
}

GET /api/2.5/tenders/07a9d2daabfe4268a5b3f6db5a7e1287 HTTP/1.0
Authorization: Bearer chronograph
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "title": "Послуги шкільних їдалень",
    "title_en": "Services in school canteens",
    "title_ru": "Услуги школьных столовых",
    "description_en": "Services in school canteens",
    "description_ru": "Услуги школьных столовых",
    "date": "2023-01-01T00:00:01+02:00",
    "dateCreated": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:01+02:00",
    "tenderID": "UA-2023-01-01-000001-a",
    "owner": "broker",
    "mainProcurementCategory": "services",
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "type": "financing",
        "code": "prepayment",
        "percentage": 45.55,
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 0
      },
      {
        "id": "815b7f7b04234cc6874087884f004952",
        "title": "deliveryOfGoods",
        "type": "financing",
        "code": "postpayment",
        "percentage": 54.45,
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 0
      }
    ],
    "value": {
      "amount": 500000.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": false
    },
    "procurementMethod": "limited",
    "procuringEntity": {
      "name": "ЗОСШ #10 м.Вінниці",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "21725150",
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      },
      "address": {
        "streetAddress": "вул. Стахурського. 22",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21027",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Куца Світлана Валентинівна",
        "telephone": "+380432465302",
        "url": "http://sch10.edu.vn.ua/"
      },
      "kind": "special"
    },
    "status": "active",
    "items": [
      {
        "id": "7e6d418b001e4a0fbe86d048f86ba39a",
        "description": "Послуги шкільних їдалень",
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "quantity": 1.0,
        "classification": {
          "description": "Послуги з харчування у школах",
          "scheme": "ДК021",
          "id": "55523100-3"
        },
        "unit": {
          "name": "папір",
          "code": "KGM",
          "value": {
            "amount": 10.0,
            "currency": "UAH",
            "valueAddedTaxIncluded": false
          }
        },
        "deliveryDate": {
          "startDate": "2023-01-21T00:00:00+02:00",
          "endDate": "2023-02-20T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        }
      }
    ],
    "awards": [
      {
        "id": "9781a8bdca8d4bd0bb7eb110bb33f809",
        "status": "active",
        "date": "2023-01-01T00:00:00+02:00",
        "value": {
          "amount": 475000.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": false
        },
        "suppliers": [
          {
            "name": "ДКП «Школяр»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137256",
              "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 33",
              "locality": "м. Вінниця",
              "region": "Вінницька область",
              "postalCode": "21100",
              "countryName": "Україна"
            },
            "contactPoint": {
              "name": "Сергій Олексюк",
              "email": "soleksuk@gmail.com",
              "telephone": "+380432216930"
            },
            "scale": "micro"
          }
        ],
        "qualified": true,
        "complaintPeriod": {
          "startDate": "2023-01-01T00:00:00+02:00",
          "endDate": "2023-01-01T00:00:00+02:00"
        }
      }
    ],
    "contracts": [
      {
        "id": "7c82c25de63348eea5afb981c0fc2f54",
        "awardID": "9781a8bdca8d4bd0bb7eb110bb33f809",
        "contractID": "UA-2023-01-01-000001-a-1",
        "status": "active",
        "value": {
          "amount": 475000.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": false,
          "amountNet": 475000.0
        },
        "items": [
          {
            "id": "7e6d418b001e4a0fbe86d048f86ba39a",
            "description": "Послуги шкільних їдалень",
            "classification": {
              "description": "Послуги з харчування у школах",
              "scheme": "ДК021",
              "id": "55523100-3"
            },
            "additionalClassifications": [
              {
                "scheme": "ДКПП",
                "id": "17.21.1",
                "description": "Послуги шкільних їдалень"
              }
            ],
            "unit": {
              "name": "папір",
              "value": {
                "amount": 10.0,
                "currency": "UAH",
                "valueAddedTaxIncluded": false
              },
              "code": "KGM"
            },
            "quantity": 1.0,
            "deliveryDate": {
              "startDate": "2023-01-21T00:00:00+02:00",
              "endDate": "2023-02-20T00:00:00+02:00"
            },
            "deliveryAddress": {
              "streetAddress": "вул. Банкова 1",
              "locality": "м. Київ",
              "region": "м. Київ",
              "postalCode": "79000",
              "countryName": "Україна"
            }
          }
        ],
        "suppliers": [
          {
            "name": "ДКП «Школяр»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137256",
              "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 33",
              "locality": "м. Вінниця",
              "region": "Вінницька область",
              "postalCode": "21100",
              "countryName": "Україна"
            },
            "contactPoint": {
              "email": "soleksuk@gmail.com",
              "telephone": "+380432216930",
              "name": "Сергій Олексюк"
            },
            "scale": "micro"
          }
        ],
        "date": "2023-01-01T00:00:01+02:00",
        "dateSigned": "2023-01-01T00:00:01+02:00"
      }
    ],
    "cause": "twiceUnsuccessful",
    "causeDescription": "оригінальний тендер не вдався двічі",
    "causeDescription_en": "original tender has failed twice",
    "causeDescription_ru": "оригинальный тендер не получился дважды",
    "procurementMethodType": "negotiation",
    "cancellations": [
      {
        "id": "d66237cadae943499e9ee25d42e319f3",
        "reason": "cancellation reason",
        "date": "2023-01-01T00:00:00+02:00",
        "status": "draft",
        "cancellationOf": "tender",
        "reasonType": "dateViolation"
      }
    ],
    "id": "07a9d2daabfe4268a5b3f6db5a7e1287"
  }
}

