GET /api/2.5/tenders/16238a7e94e64b3a8b53106493d5d424/awards/f44436fd825440d78a99dd57365363a3/documents?acc_token=9147c49d3e8844889bffab7629a63b5b HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "award_first_document.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2727941c3c1d4b398e0ef21c294d50f8?Signature=XVdH%2BLOTsgYF3J849jqk9w0Oivjv96KP1vF11T2pawV8wnAcIPzqxWiQWkKBo6SZdysuzHcTtpSV3ETS4xHUAw%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "id": "467528027f7041d499db9c6c497d16d4",
      "datePublished": "2021-03-16T00:00:00+02:00",
      "dateModified": "2021-03-16T00:00:00+02:00",
      "author": "tender_owner"
    }
  ]
}

