GET /api/2.5/tenders/5fb29c8fb65c4a12b69dd3531cfe7bce/contracts/ec50d5084bd940d68482479c4834cdf4/documents?acc_token=bc6711b5ba434b92bbba26699dca3104 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "contract_second_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9cbf3639b1054b08946d4963ae55c81a?KeyID=a8968c46&Signature=YCY%2F5pIEAiXIdjd8%2FMoAkiE8ySMTWf9xxuorJsHT9JKfKsCIIDlLdebCoAhHLE6r9ovrsDrBaX64t9gz%252BDwfAQ%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2020-09-08T01:00:00+03:00", 
      "id": "a97a3aab3de4465e97b86b892893b2f8", 
      "dateModified": "2020-09-08T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/62e7892bbb7740cc8d1a962adc84d0ba?KeyID=a8968c46&Signature=dLqTpEmPJwXwVdM%252BQVd695CVyMPPYUZobxFsw9qyojz%2FKybpRnvjnP4%252BwC%2FTzSgZMSQOr4WewZOpp9ywjAoeDg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2020-09-08T01:00:00+03:00", 
      "id": "248897d1f75b4416b132a29aa703ee18", 
      "dateModified": "2020-09-08T01:00:00+03:00"
    }
  ]
}

