PATCH /api/2.5/tenders/26b780552e084bbcb2b53c5383a6e976/contracts/0b3c1a9fcf054fa98d15801d166c4c87?acc_token=df3d7d3c62c74918a4905630dbce126b HTTP/1.0
Authorization: Bearer broker
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2020-06-04T00:00:00+02:00", 
          "endDate": "2020-07-04T00:00:00+02:00"
        }, 
        "id": "08b6cc454279495f8d2a561b50d74611", 
        "quantity": 1.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "Вінницька область", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "amountNet": 475000.0, 
      "valueAddedTaxIncluded": false
    }, 
    "dateSigned": "2020-05-15T01:00:01+03:00", 
    "date": "2020-05-15T01:00:01+03:00", 
    "awardID": "25e94c29b961421a9128a267c2ffe263", 
    "id": "0b3c1a9fcf054fa98d15801d166c4c87", 
    "contractID": "UA-2020-05-15-000001-1"
  }
}

