GET /api/2.5/tenders/df26af14d20e44a4a11a7ad4d6758698/awards/f0f6882a0f564c38b776539e79ef3928/documents?acc_token=876109ab3fbf46ca81bae8f2e668687a HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "award_first_document.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a150b81d16504ae88167cb5c3cec719f?Signature=VyqNcmitdo%2BX1ROzZI%2BCiQeLLKhcAI6HyxGzEY%2B8MLH1k%2FV6%2BGyLywy3C8rwBiRTWU2cJK8Csm4tIv7OkwMvCA%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "a493e5b62b5f4e8bbbe0f9dba391a5de",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "dateModified": "2023-10-10T01:00:00+03:00",
      "author": "tender_owner"
    },
    {
      "hash": "md5:00000000000000000000000000000000",
      "title": "award_second_document.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4b2e689a0efb48e09297e8f0781145df?Signature=0K0looxslsU82Br8cYEXz%2BfTVToPT1EghT2hkvYmOjQEXndfnbeD%2BYMkV5jHBzmhrM9WTCuD%2BG5auL%2FLjydTAA%3D%3D&KeyID=a8968c46",
      "documentOf": "tender",
      "language": "uk",
      "id": "98943c8094fd4cc2960414cf77695b46",
      "datePublished": "2023-10-10T01:00:00+03:00",
      "dateModified": "2023-10-10T01:00:00+03:00",
      "author": "tender_owner"
    }
  ]
}

