GET /api/2.5/contracts/fcd03c2cc2be4b7693e4c710c31582e1/documents/64d727edf7a24a9d89031cf8fc890238?download=1 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Document download forbidden."
    }
  ]
}

