POST /api/2.5/tenders/f8573404c1ff4e8bac25fc817a2b68c0/cancellations/e69d23d2cdd74a2897b262e00d4c375d/documents?acc_token=b1e5d31cae12404789b524b2c946715f HTTP/1.0
Authorization: Bearer broker
Content-Length: 322
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Notice.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6b637535099e452b890198556efb7f70?Signature=z4vCl%2FLtbJ2RpGjssq1HKcQ4DzZJ4QSBdeYcMkt2AzLZUmI8TfP9Hp5fNqcBkQcWjYqnejjnfO4b9mMl%2Foy2BA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f8573404c1ff4e8bac25fc817a2b68c0/cancellations/e69d23d2cdd74a2897b262e00d4c375d/documents/e09d8f26c3b74f8d8aa1f5fbbbc18c9f

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "Notice.pdf",
    "format": "application/pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6b637535099e452b890198556efb7f70?Signature=Gb0uMtev6EiVhDG%2FUzbdh5NxU8ZGf5XusY8RY9n0C9HplAxVHIPVZ8%2FV5X8I0XUCOjzFPqSAe9CiguZlHkj2CA%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "id": "e09d8f26c3b74f8d8aa1f5fbbbc18c9f",
    "datePublished": "2023-01-01T00:00:01+02:00",
    "dateModified": "2023-01-01T00:00:01+02:00"
  }
}

