POST /api/2.5/tenders/5fb29c8fb65c4a12b69dd3531cfe7bce/documents?acc_token=bc6711b5ba434b92bbba26699dca3104 HTTP/1.0
Authorization: Bearer broker
Content-Length: 142
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5fb29c8fb65c4a12b69dd3531cfe7bce/documents/d6cff84aa766456a998fd7b354b06706
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d38950e3904c437ea5542ab4f272f9e5?KeyID=a8968c46&Signature=CWRFAzSBsUmm8gWC8lO2fYmLYoqT3BBE1IUk5T3gCKPGTk6iwaVeMH5zCGIq1q%252Blr8UHfPdkPMj0SIREF0j6BQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2020-09-08T01:00:00+03:00", 
    "id": "d6cff84aa766456a998fd7b354b06706", 
    "dateModified": "2020-09-08T01:00:00+03:00"
  }
}

