from openprocurement.tender.cfaua.tests.qualification import TenderQualificationBaseTestCase
from openprocurement.tender.core.tests.qualification_milestone import TenderQualificationMilestone24HMixin


class TenderQualificationMilestoneTestCase(TenderQualificationMilestone24HMixin, TenderQualificationBaseTestCase):
    context_name = "qualification"
