PATCH /api/2.5/tenders/1f63b71c7e6b459eb5823bed9bdb72ab/bids/05957e6390bc4da3a9f794c1ee62fa78?acc_token=5a417c184679473a9d257692b980c461 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "pending"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "documents",
      "description": "Document with type 'proposal' and format pkcs7-signature is required"
    }
  ]
}

