PATCH /api/2.5/tenders/78eb313fd0774c058c130df95e66f061/questions/c8d5a9b58f3640dcaf60868ef735dfbb?acc_token=1ce7204d96e84cd78d475fddc5220b8d HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "c8d5a9b58f3640dcaf60868ef735dfbb",
    "author": {
      "hash": "ccbdd3020ced0cb059da296b5ccfa5d7"
    },
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2027-01-01T00:00:00+02:00",
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
    "questionOf": "tender",
    "dateAnswered": "2027-01-01T00:00:00+02:00"
  }
}

