PATCH /api/2.5/tenders/7f818311963440f0b49ba53c35a0f971/awards/d9a2f7f8061d4bfa8a112ccd22984a6b?acc_token=e24ebb78f89c43e0aa508fd9d7839e4d HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "unsuccessful"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "qualified",
      "description": [
        "Can't update award to unsuccessful status when qualified/eligible isn't set to False"
      ]
    }
  ]
}

