PATCH /api/2.5/tenders/c429ff66bfe7408592ede2909ac98702/awards/df962b46ac6e4f5ba2694eb98ccff633?acc_token=f3668c9a0c9b4eb28c46968fd261494e HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active",
    "qualified": true,
    "eligible": true
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "df962b46ac6e4f5ba2694eb98ccff633",
    "status": "active",
    "date": "2023-10-10T01:05:01+03:00",
    "value": {
      "amount": 499.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "suppliers": [
      {
        "name": "Школяр",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        },
        "scale": "micro"
      }
    ],
    "bid_id": "7334046d9fc046358e61bf8dc7d2cd18",
    "lotID": "9d95d7c5f19f4d24b17d650fe94a42f5",
    "documents": [
      {
        "confidentiality": "public",
        "documentType": "notice",
        "id": "c969c3d08140411fa4991b79c9e5165c",
        "datePublished": "2023-10-10T01:05:01+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "sign.p7s",
        "format": "sign/pkcs7-signature",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/47f26718f2584993a8910c17097b9d6f?Signature=hgldKkKQF809R%2Fp%2B1wmMvRYcMJDI7Dt7FPG%2B8SpZ6ID4qB7cndmNDZ5aRAJhWe%2BVMpafw59iHM2OaeW8HvFLDg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "dateModified": "2023-10-10T01:05:01+03:00",
        "author": "tender_owner",
        "language": "uk"
      }
    ],
    "period": {
      "startDate": "2023-10-10T01:05:01+03:00",
      "endDate": "2023-10-18T00:00:00+03:00"
    },
    "qualified": true,
    "eligible": true,
    "complaintPeriod": {
      "startDate": "2023-10-10T01:05:01+03:00",
      "endDate": "2023-10-21T00:00:00+03:00"
    }
  }
}

