POST /api/2.5/tenders/78eb313fd0774c058c130df95e66f061/bids/052d2aa3db724254aec98633d9673cf5/documents?acc_token=020478c21ae24a1e8677c088dc7584e5 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Proposal.p7s",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dfdbc256001345cdbc55087b0629daa4?Signature=lRtb%2BQmwTBykTpQA%2B2APT7OPofj1o7SnhgMc7vRqqFfw2nWANQ1u%2B23ML2H%2F2m3bxgRVILXeSNAmzlkkrwi%2BAQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "sign/p7s",
    "documentType": "proposal"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/78eb313fd0774c058c130df95e66f061/bids/052d2aa3db724254aec98633d9673cf5/documents/4d759e3733374818b6aa57f97151c718

{
  "data": {
    "confidentiality": "public",
    "documentType": "proposal",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Proposal.p7s",
    "format": "sign/p7s",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dfdbc256001345cdbc55087b0629daa4?Signature=Vv4I4H6%2B56pEfHdP5KTHGOONf1WYAJCQX9Dd103a6bDOxVvXQB6k9y8fiygdT5HwaZbjwx%2FFDo3CvXv3cVImAQ%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "4d759e3733374818b6aa57f97151c718",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00"
  }
}

