PATCH /api/2.5/tenders/7d3cf7fb349c41a38c1e3c8e94f03fdc/bids/d3e614b4092744cf9875c56f45ae93f9?acc_token=fde267da13974c2782fd1e5539862cd5 HTTP/1.0
Authorization: Bearer broker
Content-Length: 14504
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "94a6568385094e5fbe59d66bfd596bdc",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "82f25a3c92f9422d90cf218fd80c3401",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "18fa5f4c893a41ba9d32e52182ef8d30",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "971a49e7ac36476cb3270a7ce0c5d8d8",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "37c437a354f74645ab44d027a2c1555f",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "68af25c5e194468ba7878612fc94d5e3",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "80a59f2469284b748a094ff2cd56ee3a",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a7a4085e747049db99cab8d6a1b72a34",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "7d25261d603c4868bb6a21b33c718bf2",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "8be770645f5a4274a873ecbf03d1a267",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": true
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "22f75b3dad174e2f8801aa47d4109043",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": true
      }
    ]
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirementResponses": [
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "94a6568385094e5fbe59d66bfd596bdc",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True",
        "id": "6f5bb6f39be8461a9081dc198473d0a9"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "82f25a3c92f9422d90cf218fd80c3401",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True",
        "id": "fccc0e5c78054f97b43b768326325c32"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "18fa5f4c893a41ba9d32e52182ef8d30",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True",
        "id": "dca99c2d03c74021b89f487c6fca796e"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "971a49e7ac36476cb3270a7ce0c5d8d8",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True",
        "id": "3884302763cd4ec5af77009efdd75280"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "37c437a354f74645ab44d027a2c1555f",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True",
        "id": "6fd0a734c5c742379b33987552392dce"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "68af25c5e194468ba7878612fc94d5e3",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True",
        "id": "b36deafb80a04e3ca90b40b29523568f"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "80a59f2469284b748a094ff2cd56ee3a",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True",
        "id": "dabdcfaa5ed047f3a856becd47579c52"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a7a4085e747049db99cab8d6a1b72a34",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True",
        "id": "458c26d13f8b40b194f7ccc8bcad4611"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "7d25261d603c4868bb6a21b33c718bf2",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True",
        "id": "845b395fa41a4ebdac3ea1fe99c3a9ed"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "8be770645f5a4274a873ecbf03d1a267",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True",
        "id": "e30d933127d54c498aecbf445ca78d94"
      },
      {
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "22f75b3dad174e2f8801aa47d4109043",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True",
        "id": "4cfcc6f4d58441ec9179283e71103a1f"
      }
    ],
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "scale": "micro",
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        }
      }
    ],
    "status": "draft",
    "id": "d3e614b4092744cf9875c56f45ae93f9",
    "date": "2023-10-10T01:00:00+03:00",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "lotValues": [
      {
        "value": {
          "amount": 500.0,
          "currency": "UAH",
          "valueAddedTaxIncluded": true
        },
        "relatedLot": "f593b0ce6a334393bfba269562fa3ac9",
        "status": "pending",
        "date": "2023-10-10T01:00:00+03:00"
      }
    ],
    "selfQualified": true
  }
}

