POST /api/2.5/tenders/d919e3a12bf04f32b88a651dc10270d1/documents?acc_token=e81ca7deac284bc5bbfb6eaacbdd43af HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "sign.p7s",
    "documentType": "notice",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fb4d6f7c2411498eb3fade1a9d587f7d?Signature=vod5xm%2FkK%2FtTuEvVsD%2BT6aRIWQAqM5Qqh7qJCU6qhVSJPypMoHGJZGVbxcjJT1PKD5psrpZeCTzUTl5VwqgQCQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "sign/pkcs7-signature"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/d919e3a12bf04f32b88a651dc10270d1/documents/c46a978eb91f40d49957b8374d1ec13d

{
  "data": {
    "documentType": "notice",
    "hash": "md5:00000000000000000000000000000000",
    "title": "sign.p7s",
    "format": "sign/pkcs7-signature",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fb4d6f7c2411498eb3fade1a9d587f7d?Signature=wVyfX02YUKRN61o8BccbMXyMs4h8oHRTdCko8DMv6V7Nk7SInt3PyNNcQrkTFz%2BZFkBJbk5KLGkPRr3Nxx4vCg%3D%3D&KeyID=a8968c46",
    "documentOf": "tender",
    "language": "uk",
    "id": "c46a978eb91f40d49957b8374d1ec13d",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "author": "tender_owner"
  }
}

