PATCH /api/2.5/tenders/8ec937684cc1428ebb753f5aaf7485fd/questions/49b92c7234b942f08136d6a6843e8b81?acc_token=f9bc18b159e04780b8d9655605688317 HTTP/1.0
Authorization: Bearer broker
Content-Length: 162
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2020-05-01T01:00:00+03:00", 
    "title": "Калорійність", 
    "date": "2020-05-01T01:00:00+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "49b92c7234b942f08136d6a6843e8b81", 
    "questionOf": "tender"
  }
}

