PATCH /api/2.5/tenders/32d3b5becccb479ea62a23dc50237f60/qualifications/2a4dcba975ce403c96c8b940e1eff5ac?acc_token=e81ca7deac284bc5bbfb6eaacbdd43af HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active",
    "qualified": true,
    "eligible": true
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "2a4dcba975ce403c96c8b940e1eff5ac",
    "bidID": "317e5711549a4f41a8ebee089db0884a",
    "lotID": "d1d81f5863c1460c8a7d2e9c9dfeb30d",
    "status": "active",
    "date": "2027-01-01T00:03:00+02:00",
    "qualified": true,
    "eligible": true
  }
}

