POST /api/2.5/tenders/3380abd6dac247a394ea054cfe23249b/awards/02e73dd649794aeaa7214ad1005d1272/complaints/67b03226839f4fa9817557eb4595c4d1/posts?acc_token=6b1e01a840d34d3484155add920d0c67 HTTP/1.0
Authorization: Bearer broker
Content-Length: 672
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "recipient": "aboveThresholdReviewers", 
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ae162bbbae31456dbdee61913d853c24?KeyID=a8968c46&Signature=SucN%2FAeTzILA%2FvO6VEqFjFM%2BDOGLdvWfAoYlSe96tlat9Kq1ljoEIBSM6GfHLJHexiPd4QCl3%2FwyaNZO1pUfDA%3D%3D", 
        "title": "post_document_complaint.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "relatedPost": "fa82f901aaa94c63b031b23555844f4e", 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/3380abd6dac247a394ea054cfe23249b/awards/02e73dd649794aeaa7214ad1005d1272/complaints/67b03226839f4fa9817557eb4595c4d1/posts/496118a621b14940ad0b75ee34880c33
{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "post_document_complaint.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ae162bbbae31456dbdee61913d853c24?KeyID=a8968c46&Signature=SucN%2FAeTzILA%2FvO6VEqFjFM%2BDOGLdvWfAoYlSe96tlat9Kq1ljoEIBSM6GfHLJHexiPd4QCl3%2FwyaNZO1pUfDA%3D%3D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2020-05-01T01:00:01+03:00", 
        "id": "d727d5e2b77542bdb4a69ef7be9c3c5c", 
        "dateModified": "2020-05-01T01:00:01+03:00"
      }
    ], 
    "description": "Додано документ", 
    "title": "Уточнення по вимозі", 
    "author": "complaint_owner", 
    "datePublished": "2020-05-01T01:00:01+03:00", 
    "relatedPost": "fa82f901aaa94c63b031b23555844f4e", 
    "recipient": "aboveThresholdReviewers", 
    "id": "496118a621b14940ad0b75ee34880c33"
  }
}

