GET /api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/fc8e2476624d4425ac818176664ccdd0?acc_token=9b28879d9dd2400fbaa84969d33ba7b4 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Андрій Олексюк",
          "email": "aagt@gmail.com",
          "telephone": "+380 (322) 91-69-30"
        },
        "scale": "sme"
      }
    ],
    "date": "2021-01-22T00:00:00+02:00",
    "id": "fc8e2476624d4425ac818176664ccdd0",
    "value": {
      "amount": 499.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/5d65b887e53f4c0d97374b32fe5c6b8a?key_for_bid=fc8e2476624d4425ac818176664ccdd0",
    "requirementResponses": [
      {
        "id": "bdfcd35bec1e4f1e8ad2f742cc9857b3",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "453a0ea0ec004d82b812ea55f723be78",
          "title": "Фізична особа, яка є учасником процедури закупівлі, не була засуджена за злочин, учинений з корисливих мотивів (зокрема, пов'язаний з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
        },
        "value": "True"
      },
      {
        "id": "d808689ab34748d6ba01c324c4579b90",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "2e23ea3e6c6745ae9c550b201790848f",
          "title": "Суб'єкт господарювання (учасник) протягом останніх трьох років не притягувався до відповідальності за порушення, передбачене пунктом 4 частини другої статті 6, пунктом 1 статті 50 Закону України \"Про захист економічної конкуренції\", у вигляді вчинення антиконкурентних узгоджених дій, що стосуються спотворення результатів тендерів"
        },
        "value": "True"
      },
      {
        "id": "e0e1421115e5472fad457e4050ea30e5",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "be1628db3f8546d4851a3e01a29363fd",
          "title": "Відомості про юридичну особу, яка є учасником процедури закупівлі, не внесено до Єдиного державного реєстру осіб, які вчинили корупційні або пов'язані з корупцією правопорушення"
        },
        "value": "True"
      },
      {
        "id": "cc07d34611ad4bb3b33e66413828f6c3",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "21c176f46364481c8a4477d2fdebdf95",
          "title": "Службову (посадову) особу учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення корупційного правопорушення або правопорушення, пов'язаного з корупцією"
        },
        "value": "True"
      },
      {
        "id": "aade09303cea47b5863dbd808ba19946",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "291698c3901f4b22910a440d5ae96f6c",
          "title": "Службова (посадова) особа учасника процедури закупівлі, яку уповноважено учасником представляти його інтереси під час проведення процедури закупівлі, фізичну особу, яка є учасником, не було притягнуто згідно із законом до відповідальності за вчинення правопорушення, пов'язаного з використанням дитячої праці чи будь-якими формами торгівлі людьми"
        },
        "value": "True"
      },
      {
        "id": "c6b973a9cb424031817007e7cec8121f",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "3d7bfc86fcb34c399744c3bcd91037a2",
          "title": "Він не має заборгованості зі сплати податків і зборів (обов'язкових платежів)"
        },
        "value": "True"
      },
      {
        "id": "08062163687849989cf7fd82b80587ba",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "5a18753a75bf4a23a74dfe4e7045ab83",
          "title": "Учасник процедури закупівлі не визнаний у встановленому законом порядку банкрутом та стосовно нього не відкрита ліквідаційна процедура"
        },
        "value": "True"
      },
      {
        "id": "557cbadce8f648a5923ec09ee81c30cf",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "4d4da113e25442998cb0377d7f420747",
          "title": "У Єдиному державному реєстрі юридичних осіб, фізичних осіб - підприємців та громадських формувань присутня інформація, передбачена пунктом 9 частини другої статті 9 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб - підприємців та громадських формувань\" (крім нерезидентів)"
        },
        "value": "True"
      },
      {
        "id": "b63fc6f0f43342cf8aa8ec2feff83f0d",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "5df568d1d5ff4d69ad66905dffbd5417",
          "title": "Юридична особа, яка є учасником процедури закупівлі (крім нерезидентів), має антикорупційну програму чи уповноваженого з реалізації антикорупційної програми, якщо вартість закупівлі товару (товарів), послуги (послуг) або робіт дорівнює чи перевищує 20 мільйонів гривень (у тому числі за лотом)"
        },
        "value": "True"
      },
      {
        "id": "103d0f1cb0554abcaa17c45e6ebe8681",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "a1bcc23a25ee47d2a8d35b68d973a22f",
          "title": "Учасник процедури закупівлі не є особою, до якої застосовано санкцію у вигляді заборони на здійснення у неї публічних закупівель товарів, робіт і послуг згідно із Законом України \"Про санкції\""
        },
        "value": "True"
      },
      {
        "id": "36ea66819f64458e8a181e04bcff9477",
        "title": "Requirement response",
        "description": "some description",
        "requirement": {
          "id": "4528ae0fa936462899d6605c280bab48",
          "title": "Мова тендерної пропозиції українська"
        },
        "value": "True"
      }
    ],
    "selfQualified": true,
    "status": "active"
  }
}

