PATCH /api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/7b97714f142c430b98dd609d94a9e441?acc_token=1faa8b766a674147a2f29548b26c1b55 HTTP/1.0
Authorization: Bearer broker
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "value": {
      "amount": 500.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "identifier": {
          "uri": "http://www.sc.gov.ua/",
          "scheme": "UA-EDR",
          "id": "00137256"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930",
          "name": "Сергій Олексюк"
        },
        "scale": "micro"
      }
    ],
    "id": "7b97714f142c430b98dd609d94a9e441",
    "date": "2021-03-16T00:00:00+02:00",
    "subcontractingDetails": "ДКП «Орфей», Україна",
    "documents": [
      {
        "id": "9c6c487bd8474272aeeef2b98848640e",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/7b97714f142c430b98dd609d94a9e441/documents/9c6c487bd8474272aeeef2b98848640e?download=3436c5b74fae4a6396cb495b38c4a7bf",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      },
      {
        "id": "28852cb33d7e4d0d8175cc86f80283da",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_top_secrets.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/7b97714f142c430b98dd609d94a9e441/documents/28852cb33d7e4d0d8175cc86f80283da?download=396144e95a5f4abb8c1d2fd408ff4d72",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "confidentiality": "buyerOnly",
        "confidentialityRationale": "Only our company sells badgers with pink hair.",
        "language": "uk"
      }
    ],
    "financialDocuments": [
      {
        "id": "8e02e8f62e594ef89dd5e2217abe653a",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/7b97714f142c430b98dd609d94a9e441/financial_documents/8e02e8f62e594ef89dd5e2217abe653a?download=83d40b8f44aa42e8834777e83d65136a",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      },
      {
        "id": "9db719cc857747bbb8e8626d70bc7a85",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc2.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/7b97714f142c430b98dd609d94a9e441/financial_documents/9db719cc857747bbb8e8626d70bc7a85?download=c3ae1eb4787a4dca98285ad72a6c6df1",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      }
    ],
    "eligibilityDocuments": [
      {
        "id": "248bc5542a1f4f8fb36288792bf74e38",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "eligibility_doc.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/7b97714f142c430b98dd609d94a9e441/eligibility_documents/248bc5542a1f4f8fb36288792bf74e38?download=9f525265f9f844849fd1b50c43dfd6c1",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      }
    ],
    "qualificationDocuments": [
      {
        "id": "1289a50765c744afb22ca3e8886f9646",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "qualification_document.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/7b97714f142c430b98dd609d94a9e441/qualification_documents/1289a50765c744afb22ca3e8886f9646?download=89a25b5566bc4df98cc4c64c21ce9d8a",
        "documentOf": "tender",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "confidentiality": "public",
        "language": "uk"
      }
    ],
    "selfQualified": true,
    "status": "pending"
  }
}

