POST /api/2.5/tenders/71c0e0ebf297470aa18a89c42f80fb55/complaints/06ef5a30aba04b5db7c0b44f95a3e046/documents HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 155
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/71c0e0ebf297470aa18a89c42f80fb55/complaints/06ef5a30aba04b5db7c0b44f95a3e046/documents/9948d3a4ae4f4c53ab956d4f334e084a
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6d95394d4a9b4bda95b79c1e60d33705?KeyID=a8968c46&Signature=D3iGcpkKa1Ksbw%252Bet40OVtAQ6FSwrAa%252BL5f1sR3etxY6roKN24YGPGGtJOM6P1xLanYQT6pdfxNAdzD41Zv9CA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2020-05-01T01:00:00+03:00", 
    "id": "9948d3a4ae4f4c53ab956d4f334e084a", 
    "dateModified": "2020-05-01T01:00:00+03:00"
  }
}

