PATCH /api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a?acc_token=a18895cc933048798f66084924c3fdf5 HTTP/1.0
Authorization: Bearer broker
Content-Length: 60
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "title": "Послуги шкільних їдалень",
    "date": "2021-03-16T00:00:00+02:00",
    "dateModified": "2021-03-16T00:00:00+02:00",
    "tenderID": "UA-2021-03-16-000001",
    "owner": "broker",
    "mainProcurementCategory": "services",
    "milestones": [
      {
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "title": "signingTheContract",
        "type": "financing",
        "code": "prepayment",
        "percentage": 45.55,
        "duration": {
          "days": 2,
          "type": "banking"
        },
        "sequenceNumber": 0
      },
      {
        "id": "a869e97a691b43a7a2a55935bdc6b316",
        "title": "deliveryOfGoods",
        "type": "financing",
        "code": "postpayment",
        "percentage": 54.45,
        "duration": {
          "days": 900,
          "type": "calendar"
        },
        "sequenceNumber": 0
      }
    ],
    "procurementMethod": "open",
    "submissionMethod": "electronicAuction",
    "value": {
      "amount": 501.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "minimalStep": {
      "amount": 5.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "questions": [
      {
        "id": "5f49b5e5bcc747da96370e2681a16e19",
        "title": "Калорійність",
        "description": "Просимо додати таблицю потрібної калорійності харчування",
        "date": "2021-03-16T00:00:00+02:00",
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"",
        "questionOf": "tender",
        "dateAnswered": "2021-03-16T00:00:00+02:00"
      }
    ],
    "guarantee": {
      "amount": 8.0,
      "currency": "USD"
    },
    "awardCriteria": "lowestCost",
    "procurementMethodType": "aboveThresholdEU",
    "title_en": "Services in school canteens",
    "enquiryPeriod": {
      "startDate": "2021-02-13T00:00:00+02:00",
      "endDate": "2021-03-06T00:00:00+02:00",
      "clarificationsUntil": "2021-03-12T00:00:00+02:00",
      "invalidationDate": "2021-03-16T00:00:00+02:00"
    },
    "tenderPeriod": {
      "startDate": "2021-02-13T00:00:00+02:00",
      "endDate": "2021-03-16T00:00:00+02:00"
    },
    "auctionPeriod": {
      "shouldStartAfter": "2021-03-21T00:00:00+02:00"
    },
    "documents": [
      {
        "id": "e6ff11e4796a4e45a0afd771fb72dff0",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Notice.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ab8a494e9c2f4449ad1f1f14a64c979a?Signature=IBm7WuwOafrXpvyGqFn15E31vKrct3sveUDatq5YZeQuze4ghY4Xn9WwttCh5Gd7%2BpLoP5%2FbzoHhSMpZv2tECQ%3D%3D&KeyID=a8968c46",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "author": "tender_owner",
        "documentOf": "tender",
        "language": "uk"
      },
      {
        "id": "c648fc26ab1041c193f63ba2b43e95c8",
        "hash": "md5:00000000000000000000000000000000",
        "title": "AwardCriteria.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4458395daa9043c28cff954a8ae6c3c8?Signature=JJukztJJJMPOV6hP%2B7NpAKlbergt5OhiQQlf01nmjZt3hmkgqTz%2BMCxYaDBG6KTCnXXgbLdaOXpN07uPqfBcDg%3D%3D&KeyID=a8968c46",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "author": "tender_owner",
        "documentOf": "tender",
        "language": "uk"
      },
      {
        "id": "c648fc26ab1041c193f63ba2b43e95c8",
        "hash": "md5:00000000000000000000000000000000",
        "title": "AwardCriteria-2.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/88b8e9b475364501a41d908978a4ea7c?Signature=hQJxsry6FmzQ2YR7TCSH9OO9SKNZSkeAWwksJJnJvIu4Wabk6cqrYmx21lkfuIwD9Nd4SGZ%2BfZI9oRfXFFTdBA%3D%3D&KeyID=a8968c46",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00",
        "author": "tender_owner",
        "documentOf": "tender",
        "language": "uk"
      }
    ],
    "items": [
      {
        "id": "c2eff2b9323c40a8a017e4f2fe8af8a3",
        "description": "Послуги шкільних їдалень",
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "quantity": 1.0,
        "classification": {
          "description": "Test",
          "scheme": "ДК021",
          "id": "37810000-9"
        },
        "unit": {
          "name": "кілограм",
          "code": "KGM"
        },
        "deliveryDate": {
          "startDate": "2021-04-05T00:00:00+02:00",
          "endDate": "2021-05-05T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "description_en": "Services in school canteens"
      },
      {
        "id": "7d309b62d3314959ad7a563221df232c",
        "description": "Послуги шкільних їдалень",
        "additionalClassifications": [
          {
            "scheme": "ДКПП",
            "id": "17.21.1",
            "description": "Послуги шкільних їдалень"
          }
        ],
        "quantity": 1.0,
        "classification": {
          "description": "Test",
          "scheme": "ДК021",
          "id": "37810000-9"
        },
        "unit": {
          "name": "упаковка",
          "code": "PK"
        },
        "deliveryDate": {
          "startDate": "2021-04-05T00:00:00+02:00",
          "endDate": "2021-05-05T00:00:00+02:00"
        },
        "deliveryAddress": {
          "streetAddress": "вул. Банкова 1",
          "locality": "м. Київ",
          "region": "м. Київ",
          "postalCode": "79000",
          "countryName": "Україна"
        },
        "description_en": "Services in school canteens"
      }
    ],
    "procuringEntity": {
      "name": "ЗОСШ #10 м.Вінниці",
      "name_en": "School #10 of Vinnytsia",
      "identifier": {
        "scheme": "UA-EDR",
        "id": "21725150",
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\"",
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\""
      },
      "address": {
        "streetAddress": "вул. Стахурського. 22",
        "locality": "м. Вінниця",
        "region": "Вінницька область",
        "postalCode": "21027",
        "countryName": "Україна"
      },
      "contactPoint": {
        "name": "Куца Світлана Валентинівна",
        "telephone": "+380432465302",
        "url": "http://sch10.edu.vn.ua/",
        "name_en": "Kutsa Svitlana V.",
        "availableLanguage": "uk"
      },
      "kind": "general"
    },
    "bids": [
      {
        "tenderers": [
          {
            "name": "ДКП «Школяр»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137256",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 33",
              "locality": "м. Вінниця",
              "region": "Вінницька область",
              "postalCode": "21100",
              "countryName": "Україна"
            },
            "contactPoint": {
              "name": "Сергій Олексюк",
              "email": "soleksuk@gmail.com",
              "telephone": "+380432216930"
            },
            "scale": "micro"
          }
        ],
        "id": "7b97714f142c430b98dd609d94a9e441",
        "documents": [
          {
            "id": "9c6c487bd8474272aeeef2b98848640e",
            "hash": "md5:00000000000000000000000000000000",
            "title": "Proposal.pdf",
            "format": "application/pdf",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3436c5b74fae4a6396cb495b38c4a7bf?Signature=xb6zEhLUtq25zw4gaPuLWfObN9WzWu8L0bT1AeU9fbbc85DYWxTWoUVERSTcq7ZE4RhUSV8MsAENb59z0a8XDA%3D%3D&KeyID=a8968c46",
            "datePublished": "2021-03-16T00:00:00+02:00",
            "dateModified": "2021-03-16T00:00:00+02:00",
            "documentOf": "tender",
            "confidentiality": "public",
            "language": "uk"
          },
          {
            "id": "28852cb33d7e4d0d8175cc86f80283da",
            "hash": "md5:00000000000000000000000000000000",
            "title": "Proposal_top_secrets.pdf",
            "format": "application/pdf",
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5d65b887e53f4c0d97374b32fe5c6b8a/bids/7b97714f142c430b98dd609d94a9e441/documents/28852cb33d7e4d0d8175cc86f80283da?download=396144e95a5f4abb8c1d2fd408ff4d72",
            "datePublished": "2021-03-16T00:00:00+02:00",
            "dateModified": "2021-03-16T00:00:00+02:00",
            "documentOf": "tender",
            "confidentialityRationale": "Only our company sells badgers with pink hair.",
            "confidentiality": "buyerOnly",
            "language": "uk"
          }
        ],
        "eligibilityDocuments": [
          {
            "id": "248bc5542a1f4f8fb36288792bf74e38",
            "hash": "md5:00000000000000000000000000000000",
            "title": "eligibility_doc.pdf",
            "format": "application/pdf",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9f525265f9f844849fd1b50c43dfd6c1?Signature=V%2F7y4dUu4zh25Zo1ksIOnDNae%2Bwf4jlhggthgc2Pa%2BZt2g23oFrHVP7jvR4CZuxIh1mrmWQchZO7N6kUzznKAQ%3D%3D&KeyID=a8968c46",
            "datePublished": "2021-03-16T00:00:00+02:00",
            "dateModified": "2021-03-16T00:00:00+02:00",
            "documentOf": "tender",
            "confidentiality": "public",
            "language": "uk"
          }
        ],
        "status": "active"
      },
      {
        "tenderers": [
          {
            "name": "ДКП «Книга»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137226",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 34",
              "locality": "м. Львів",
              "region": "Львівська область",
              "postalCode": "79013",
              "countryName": "Україна"
            },
            "contactPoint": {
              "name": "Андрій Олексюк",
              "email": "aagt@gmail.com",
              "telephone": "+380322916930"
            },
            "scale": "sme"
          }
        ],
        "id": "a7b50823159d46bface66972e91c6682",
        "status": "active"
      },
      {
        "tenderers": [
          {
            "name": "ДКП «Книга»",
            "identifier": {
              "scheme": "UA-EDR",
              "id": "00137226",
              "uri": "http://www.sc.gov.ua/"
            },
            "address": {
              "streetAddress": "вул. Островського, 34",
              "locality": "м. Львів",
              "region": "Львівська область",
              "postalCode": "79013",
              "countryName": "Україна"
            },
            "contactPoint": {
              "name": "Андрій Олексюк",
              "email": "aagt@gmail.com",
              "telephone": "+380322916930"
            },
            "scale": "sme"
          }
        ],
        "id": "6a292c9f2bb64ba3b38e5547f0bbc9e7",
        "selfQualified": true,
        "status": "unsuccessful"
      }
    ],
    "qualifications": [
      {
        "id": "f984c4d8c38945cfb64a12d897b96a02",
        "bidID": "7b97714f142c430b98dd609d94a9e441",
        "status": "active",
        "date": "2021-03-16T00:00:00+02:00",
        "qualified": true,
        "eligible": true
      },
      {
        "id": "5dd12d6c68734a0eb646e3b067240ae5",
        "bidID": "a7b50823159d46bface66972e91c6682",
        "status": "active",
        "date": "2021-03-16T00:00:00+02:00",
        "qualified": true,
        "eligible": true
      },
      {
        "id": "ba21d9fecde24b49be6aa9738bb54899",
        "bidID": "6a292c9f2bb64ba3b38e5547f0bbc9e7",
        "status": "unsuccessful",
        "date": "2021-03-16T00:00:00+02:00",
        "qualified": false,
        "eligible": false
      }
    ],
    "qualificationPeriod": {
      "startDate": "2021-03-16T00:00:00+02:00",
      "endDate": "2021-03-21T00:00:00+02:00"
    },
    "status": "active.pre-qualification.stand-still",
    "id": "5d65b887e53f4c0d97374b32fe5c6b8a",
    "next_check": "2021-03-21T00:00:00+02:00",
    "numberOfBids": 2,
    "complaintPeriod": {
      "startDate": "2021-02-13T00:00:00+02:00",
      "endDate": "2021-03-12T00:00:00+02:00"
    }
  }
}

