POST /api/2.5/tenders/96c58765139d4dfb9ff274018c231eb8/qualifications/cf7bbdde988d4552abc9d7e4ad268ff0/complaints/e2bb9e424e8d416286d6061fd06621c6/posts HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 281
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "recipient": "complaint_owner", 
    "description": "Відсутній документ", 
    "title": "Уточнення по вимозі"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/96c58765139d4dfb9ff274018c231eb8/qualifications/cf7bbdde988d4552abc9d7e4ad268ff0/complaints/e2bb9e424e8d416286d6061fd06621c6/posts/a5f196c4879c4c31b40e34ab515c5335
{
  "data": {
    "description": "Відсутній документ", 
    "title": "Уточнення по вимозі", 
    "author": "aboveThresholdReviewers", 
    "datePublished": "2020-05-01T01:00:01+03:00", 
    "recipient": "complaint_owner", 
    "id": "a5f196c4879c4c31b40e34ab515c5335"
  }
}

