POST /api/2.5/tenders/b68a79fc566a4d49b80369c0ed01748d/bids HTTP/1.0
Authorization: Bearer broker
Content-Length: 2538
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderers": [
      {
        "address": {
          "countryName": "Україна",
          "locality": "м. Львів",
          "postalCode": "79013",
          "region": "Львівська область",
          "streetAddress": "вул. Островського, 34"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "name": "Андрій Олексюк",
          "telephone": "+380322916930"
        },
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "name": "ДКП «Книга»",
        "scale": "sme"
      }
    ],
    "value": {
      "amount": 499
    },
    "documents": [
      {
        "title": "Proposal_part1.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a3862b2b1ae843528accfedd051cdef2?Signature=kOfup3pB8MgawevnUdAkeOwJQglwNRxR8McQBrUPl4Yoo615JDO5%2BdzUDosq8s%2Bbl3hgUsYGyFhT%2FcgPEGHoBg%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      },
      {
        "title": "Proposal_part2.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9ff17557b8d74a169916ccc5653c0a2d?Signature=4YcSEz6Ym6q%2Fd9wGPdcD4%2Bviepfv68vZ0zHMxPBB%2FkJkN8mwJSGu4Jc1yklR0YsXWPjCUFgEUM%2BIv8pV%2FXVNAQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "eligibilityDocuments": [
      {
        "title": "eligibility_doc.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/07d313e6717642fcb43032920da39ac2?Signature=XyP5QmXNy4NE1Ag6%2FvxsxTlY5CGxa1nglhNDlt3GoRDO2e%2FjvgK2Qk0ch2BzjQpzr0KyM5GG3%2FGdSHnV%2BPJVCw%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "financialDocuments": [
      {
        "title": "financial_doc.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6a165adbf494490aa6eb016b0331685a?Signature=Lj9KmVznpxlFA7erpu2X0YRZ%2FKzl68%2FIeg8mRK0PX7dqazP4VbNuU%2BsjeGz2YQm8mtR8oTjkZWpo286CXLCLBA%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "qualificationDocuments": [
      {
        "title": "qualification_document.pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/90d1707c32b34547bc5034dbe547c2a6?Signature=SK1BbItUzyxbymWxOoNOVB2p0N%2Br9g9818s1201LW9hU15XtKbOlUT0oRKuVDsr0H2nMMx12tHjJ4V2q7RUKAA%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/pdf"
      }
    ],
    "selfQualified": true,
    "status": "draft"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b68a79fc566a4d49b80369c0ed01748d/bids/9e105e3974f848e9a49d76e4c620a612
X-Content-Type-Options: nosniff
{
  "data": {
    "value": {
      "amount": 499.0,
      "currency": "UAH",
      "valueAddedTaxIncluded": true
    },
    "tenderers": [
      {
        "name": "ДКП «Книга»",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137226",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 34",
          "locality": "м. Львів",
          "region": "Львівська область",
          "postalCode": "79013",
          "countryName": "Україна"
        },
        "contactPoint": {
          "email": "aagt@gmail.com",
          "telephone": "+380322916930",
          "name": "Андрій Олексюк"
        },
        "scale": "sme"
      }
    ],
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part1.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a3862b2b1ae843528accfedd051cdef2?Signature=20QWJzodvNP2bfpedho6U%2F3T71yvMI4I9TJc%2BEnhF0dpky1H0Vf5vI4rq2Y99B3uZ0gMXJlKhd95jr3qwCmKAQ%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "7d415de836e14d7abd3a63f77ca82822",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00"
      },
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "Proposal_part2.pdf",
        "format": "application/pdf",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9ff17557b8d74a169916ccc5653c0a2d?Signature=%2Fnd7a4Qcr76Y3KpZhMCbiqTIOMY19FWObhcn1heyrRicUirKAuXYO1se0bRvbNoKASFDuCf2PDlveoPLCS4nCg%3D%3D&KeyID=a8968c46",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "6aefa54bc9cb4f7f952f69e76059fe1b",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00"
      }
    ],
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "financial_doc.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b68a79fc566a4d49b80369c0ed01748d/bids/9e105e3974f848e9a49d76e4c620a612/financial_documents/c0efa46716014e9089fbe198ee5c470d?download=6a165adbf494490aa6eb016b0331685a",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "c0efa46716014e9089fbe198ee5c470d",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00"
      }
    ],
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "eligibility_doc.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b68a79fc566a4d49b80369c0ed01748d/bids/9e105e3974f848e9a49d76e4c620a612/eligibility_documents/e23ff43a3e8b46a8b2c578de4331230e?download=07d313e6717642fcb43032920da39ac2",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "e23ff43a3e8b46a8b2c578de4331230e",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00"
      }
    ],
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000",
        "title": "qualification_document.pdf",
        "format": "application/pdf",
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b68a79fc566a4d49b80369c0ed01748d/bids/9e105e3974f848e9a49d76e4c620a612/qualification_documents/cc7ba409bb184b078ffb3f1aff63cdb6?download=90d1707c32b34547bc5034dbe547c2a6",
        "documentOf": "tender",
        "confidentiality": "public",
        "language": "uk",
        "id": "cc7ba409bb184b078ffb3f1aff63cdb6",
        "datePublished": "2021-03-16T00:00:00+02:00",
        "dateModified": "2021-03-16T00:00:00+02:00"
      }
    ],
    "selfQualified": true,
    "status": "draft",
    "id": "9e105e3974f848e9a49d76e4c620a612",
    "date": "2021-03-16T00:00:00+02:00"
  },
  "access": {
    "token": "3085ea896ff84f978f3e3f35244501ee",
    "transfer": "2b9ff1676ce341438358fb9b0ac242f5"
  }
}

