GET /api/2.5/agreements/1746cfba69864f7d996e4bd000858884/documents?acc_token=aab65e490788430f8cce6e18e011268f HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "id": "609409e8a6d7475f93a90e94375fb2f2",
      "hash": "md5:00000000000000000000000000000000",
      "title": "agreement_changes.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/711ea6b2fbaf40dca24dafb911e13fc8?Signature=VrEO7RUi2UqTpzKbB75Ae9qBzTyi6n4VMCF7wdNZ%2FJUTns%2BpGDcEFHcaKPlvHeEuPOsk7tczI4Lq10IHYJ%2FuDA%3D%3D&KeyID=a8968c46",
      "datePublished": "2023-01-01T00:00:00+02:00",
      "dateModified": "2023-01-01T00:00:00+02:00",
      "relatedItem": "12f43718ecbf474886b7f3545a7debe5",
      "documentOf": "change"
    },
    {
      "id": "533dbc0fa33e4847b0347a4214060ced",
      "hash": "md5:00000000000000000000000000000000",
      "title": "agreement.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/37d18c5759474877a074f9fd73d9f309?Signature=QXkoGo7r0SD7Miz0uW75JY5%2BEDXR4J%2Bi7z6UGnP9MoVt0qnwHASpN7g8gs81ZBpbhNUec%2BH2FzjdXySRUaZtCQ%3D%3D&KeyID=a8968c46",
      "datePublished": "2023-01-01T00:00:00+02:00",
      "dateModified": "2023-01-01T00:00:00+02:00",
      "documentOf": "agreement"
    }
  ]
}

