PATCH /api/2.5/agreements/1746cfba69864f7d996e4bd000858884/changes/eb59804a712942e89f57217f6537364e?acc_token=2f325f620dd24a4d8dd8c5aca839a7cc HTTP/1.0
Authorization: Bearer broker
Content-Length: 73
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active",
    "dateSigned": "2023-01-01T00:00:00+02:00"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "eb59804a712942e89f57217f6537364e",
    "status": "active",
    "date": "2023-01-01T00:00:00+02:00",
    "rationale": "Друга і третя поставка має бути розфасована",
    "rationale_en": "Agreement change cause",
    "dateSigned": "2023-01-01T00:00:00+02:00",
    "rationaleType": "taxRate",
    "modifications": [
      {
        "itemId": "cefbff4fb3e846ee8eecfdb05932afa1",
        "factor": 0.1605
      }
    ]
  }
}

