POST /api/2.5/agreements/1746cfba69864f7d996e4bd000858884/documents?acc_token=aab65e490788430f8cce6e18e011268f HTTP/1.0
Authorization: Bearer broker
Content-Length: 172
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua

-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="agreement_additional_docs.doc"
Content-Type: application/msword

additional info
-----BOUNDARY--



HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/agreements/1746cfba69864f7d996e4bd000858884/documents/b8a98c5d73aa49f0a0fc11f670517f55

{
  "data": {
    "id": "b8a98c5d73aa49f0a0fc11f670517f55",
    "hash": "md5:00000000000000000000000000000000",
    "title": "agreement_additional_docs.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/236e52bfd0544af3a63b07325306ef15?Signature=xb3aZmBRE7gbJkxQEN%2FABaUPvwJDHQK8opyRkU5wKogWbwz5pf%2FMc0IsWKc36HYyXYOgWW%2Bk8h8rPKTNvJMCCA%3D%3D&KeyID=a8968c46",
    "datePublished": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:00+02:00",
    "documentOf": "agreement"
  }
}

