GET /api/2.5/contracts/78fd8d7877d74b0dbc9c605462545e1c/documents?acc_token=05e4dac70d1f462296b4d441345fbc83 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "confidentiality": "public",
      "id": "434095e42ea546f0994b6d0eedf9ed76",
      "hash": "md5:00000000000000000000000000000000",
      "title": "contract_first_document.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/aeb5683d801a4ca0a00dc9beea56edae?Signature=L0%2FMA5VkFhoc3IFP%2FFQjWKYoLASwDHn7k%2FLcij0D%2Fy6ialug64%2FJRf%2BA5PsiaJkSZLgK2x0G2XkM5V%2FkIpJYAg%3D%3D&KeyID=a8968c46",
      "documentOf": "contract",
      "datePublished": "2027-01-01T00:00:00+02:00",
      "dateModified": "2027-01-01T00:00:00+02:00"
    },
    {
      "confidentiality": "public",
      "id": "4c26e5cbbc3247deaa337a70dcc5dbdc",
      "hash": "md5:00000000000000000000000000000000",
      "title": "contract_second_document.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fd1f95fb92a645cd81df5a257c93be77?Signature=BgoHw951wjSo7fx4cUUzr3ri6rSlVzcyzQGLu8%2FXbYqa%2BHRgd1SrEkSjpbJe9MJjN9hpgLN8WVJtCDbWMz%2BLCA%3D%3D&KeyID=a8968c46",
      "documentOf": "contract",
      "datePublished": "2027-01-01T00:00:00+02:00",
      "dateModified": "2027-01-01T00:00:00+02:00"
    },
    {
      "confidentiality": "public",
      "relatedItem": "eb794cf51a174e5ab8caa0dd717624a5",
      "id": "8287e847137047e982ef13a48b3d8807",
      "hash": "md5:00000000000000000000000000000000",
      "title": "contract_changes.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/55f3fe2b7a644d97b28c15afd5c2d4e3?Signature=fpE2QVkFunOW8tnugXB%2FFoWd44R1tJ%2BLCUgkreBKisHQo2ehaWahgQsCJ5pk60%2FDv9uiW9PWkRql1QJpzJTvBg%3D%3D&KeyID=a8968c46",
      "documentOf": "change",
      "datePublished": "2027-01-01T00:00:00+02:00",
      "dateModified": "2027-01-01T00:00:00+02:00"
    },
    {
      "confidentiality": "public",
      "hash": "md5:00000000000000000000000000000000",
      "title": "contract.doc",
      "format": "application/pdf",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9ca42f137ebb429db8641d20bc0a4c16?Signature=wPZ4KHyoICeWU3esYpUFCySGfw7TCMwmZfQ2vccE%2BkPVtTych8bpbii6rJv3XUrHSc5ql09D78v9oj8Y0LkGBg%3D%3D&KeyID=a8968c46",
      "documentOf": "contract",
      "id": "2fbed46a899e494894f6224492348ac6",
      "datePublished": "2027-01-01T00:00:00+02:00",
      "dateModified": "2027-01-01T00:00:00+02:00"
    }
  ]
}

