PUT /api/2.5/contracts/78fd8d7877d74b0dbc9c605462545e1c/buyer/signer_info?acc_token=05e4dac70d1f462296b4d441345fbc83 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "name": "Test Testovich",
    "telephone": "+380950000000",
    "email": "example@email.com",
    "iban": "111111111111111",
    "authorizedBy": "Статут компанії",
    "position": "Генеральний директор"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

null

