GET /api/2.5/contracts/05870adde49c424db6a2dba280ea90ab/documents?acc_token=9e4e9f4da0514309b6c79bbafb5b59c3 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "author": "contract_owner", 
      "title": "contract_changes.doc", 
      "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/05870adde49c424db6a2dba280ea90ab/documents/951905d76d2341e088917e1430c9f41c?download=0eb459624a8b4586998c3b1fc94dfebf", 
      "format": "application/msword", 
      "documentOf": "change", 
      "datePublished": "2020-09-08T01:00:01+03:00", 
      "id": "951905d76d2341e088917e1430c9f41c", 
      "relatedItem": "b43b7e72488d4394883aea3331d71f51", 
      "dateModified": "2020-09-08T01:00:01+03:00"
    }, 
    {
      "author": "contract_owner", 
      "title": "contract.doc", 
      "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/05870adde49c424db6a2dba280ea90ab/documents/acd30b77ef8243858cd33aeee5e6518d?download=bdfe22301a624a34bd8be9ca5b6496ca", 
      "format": "application/msword", 
      "documentOf": "contract", 
      "datePublished": "2020-09-08T01:00:01+03:00", 
      "id": "acd30b77ef8243858cd33aeee5e6518d", 
      "dateModified": "2020-09-08T01:00:01+03:00"
    }
  ]
}

