GET /api/2.5/contracts/05870adde49c424db6a2dba280ea90ab/documents?acc_token=9e4e9f4da0514309b6c79bbafb5b59c3 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "author": "contract_owner", 
      "title": "contract.doc", 
      "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/05870adde49c424db6a2dba280ea90ab/documents/241f0a4a253f465799d8ca6bbc6ea406?download=621fa39568a9418698e5f5c9f131187c", 
      "format": "application/msword", 
      "documentOf": "contract", 
      "datePublished": "2020-09-08T01:00:01+03:00", 
      "id": "241f0a4a253f465799d8ca6bbc6ea406", 
      "dateModified": "2020-09-08T01:00:01+03:00"
    }, 
    {
      "author": "contract_owner", 
      "title": "contract_changes.doc", 
      "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/05870adde49c424db6a2dba280ea90ab/documents/a7bf4e4e2e994700a5f998fe7e9c0cd6?download=7b1e68d6f18f488f86d17aa35f1913b9", 
      "format": "application/msword", 
      "documentOf": "change", 
      "datePublished": "2020-09-08T01:00:01+03:00", 
      "id": "a7bf4e4e2e994700a5f998fe7e9c0cd6", 
      "relatedItem": "b43b7e72488d4394883aea3331d71f51", 
      "dateModified": "2020-09-08T01:00:01+03:00"
    }
  ]
}

