GET /api/2.5/contracts/b5ed3fde090742bcbe39b1c05b8bf17e/changes/90238f35b68a4a7ebeb6a5632b1b0d9a HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "90238f35b68a4a7ebeb6a5632b1b0d9a",
    "status": "pending",
    "date": "2021-03-16T00:00:01+02:00",
    "rationale": "Опис причини змін контракту",
    "rationale_en": "Contract change cause",
    "rationaleTypes": [
      "volumeCuts",
      "priceReduction"
    ]
  }
}

