PATCH /api/2.3/tenders/92ad8804586d4edbb98cdb5c7c79412f/cancellations/2efc2a6437da43d0958cb542044e99c2?acc_token=415d188e59964730bee17aae7ed1f7ab HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a592a276e6a54d829e5516b351b63c7f?KeyID=1b00d854&Signature=sMfPVNKjC6rzYSvyIuWAl9EbZZJxYSpbm6I7zz32SA7cjC23ThUjm8DDPIRsAFQzv%2FH2lcLGRWMvLcni3u%252B8Cg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-21T17:05:39.410616+03:00", 
        "id": "59838452f64543dea56c62521d090fb3", 
        "dateModified": "2017-06-21T17:05:39.410655+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/7822c0d4870041d1ac4b354ad2987ca2?KeyID=1b00d854&Signature=48I4FJveITGi97RM2ycTYpCHrwguXCuFQw9ju%2FqkZLWSUsk3sVC1jCJYfInEAIsDy4x%252BnTUlv2KBB1nA416xCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-21T17:05:39.410616+03:00", 
        "id": "59838452f64543dea56c62521d090fb3", 
        "dateModified": "2017-06-21T17:05:39.754851+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2017-06-21T17:05:39.949827+03:00", 
    "cancellationOf": "tender", 
    "id": "2efc2a6437da43d0958cb542044e99c2"
  }
}

