PATCH /api/2.4/tenders/29fb21ea52a64dc8a1614d1f312ec395/cancellations/e7df956af99e492e908b03e58f234c62?acc_token=84e5e22d17d74352873a558633d2a07a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/3bafb51579454800a103636bc770952d?KeyID=369e79af&Signature=%252BgnOtnzdUItrboJnAtuQIPlhe2xwlLTwUPH3oTPct2TKwy7kktR%252B1oUInliQQ1lq447pi7COalHhPvsy3Ha8Aw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-28T09:56:41.233368+03:00", 
        "id": "5f2915a8ec49453a8ae7715c6e9d83c7", 
        "dateModified": "2018-09-28T09:56:41.233382+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/35db9c3d08f74ef4bfa35044aa293d33?KeyID=369e79af&Signature=Ga53bBud2ZirG%2FW9yOPos5tAIGiqSgzqxNYDy9h%2FvDaavIm3lxYX%2Fa75eMdVO%2FP6lQGVGM1%2FxLn9Y14sIdttBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-28T09:56:41.233368+03:00", 
        "id": "5f2915a8ec49453a8ae7715c6e9d83c7", 
        "dateModified": "2018-09-28T09:56:41.564516+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2018-09-28T09:56:41.741060+03:00", 
    "cancellationOf": "tender", 
    "id": "e7df956af99e492e908b03e58f234c62"
  }
}

