POST /api/2.3/contracts/5202ba63c8984cba89150812ad45e70d/documents?acc_token=ea84637bf71b4be28b616cd205ea5ab0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 197
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy37739950925$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/contracts/5202ba63c8984cba89150812ad45e70d/documents/aa0b0af7a54d41ccb81a96df535f73af
{
  "data": {
    "title": "contract_changes.doc", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/contracts/5202ba63c8984cba89150812ad45e70d/documents/aa0b0af7a54d41ccb81a96df535f73af?download=f17a5e0a8ac841d5ac06eaf7b084d717", 
    "format": "application/msword", 
    "documentOf": "contract", 
    "datePublished": "2016-05-20T17:45:14.116305+03:00", 
    "id": "aa0b0af7a54d41ccb81a96df535f73af", 
    "dateModified": "2016-05-20T17:45:14.116362+03:00"
  }
}

