PATCH /api/0.12/tenders/f39af08cc23e4c35b379efc4ff14f410/questions/6eba8a27d5094421852013e3ffa8ba2d?acc_token=8b8af9b643084e4fb87fbc94c678049c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-02-04T18:43:59.300170+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "6eba8a27d5094421852013e3ffa8ba2d", 
    "questionOf": "tender"
  }
}

