PATCH /api/2.0/tenders/c5218c4f746f440bb451180039f080c3/questions/d321e4dcf97e43fe8e3513a831c8d46e?acc_token=0c71d8bb6a2b426f9143740c95463e3e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-03-16T14:19:27.047915+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "d321e4dcf97e43fe8e3513a831c8d46e", 
    "questionOf": "tender"
  }
}

