PATCH /api/2.3/contracts/d85316fca03a448cabc556f6367726e2/changes/3ba8592459904c73bf05d7bc48e7083c?acc_token=54ff017bad3549e995208fde9d41da29 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "dateSigned": "2016-10-06T11:41:16.243354+03:00"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "rationaleTypes": [
      "volumeCuts", 
      "priceReduction"
    ], 
    "rationale_en": "Contract change cause", 
    "dateSigned": "2016-10-06T11:41:16.243354+03:00", 
    "rationale": "Друга і третя поставка має бути розфасована", 
    "date": "2016-10-06T11:41:16.269024+03:00", 
    "id": "3ba8592459904c73bf05d7bc48e7083c"
  }
}

