PATCH /api/2.0/tenders/875bccb8079448419db42ee024419900/qualifications/5e5c8a792d324f79a617e04595306b88?acc_token=5b38bae696d94227a71156cc736054d2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "id": "5e5c8a792d324f79a617e04595306b88", 
    "bidID": "38b0fc1d75df41c8ae0ac8d8c5cffdca"
  }
}

