PATCH /api/2.0/tenders/dd420d3036f04ebc8e6f12d0a0bf86ba/qualifications/fbee000a8a9944ebabaaf5a3e3c83974?acc_token=77ac0f0854f241f3a0c18ae04d2052f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "id": "fbee000a8a9944ebabaaf5a3e3c83974", 
    "bidID": "f0e4d6ac87ba446aaca1718e3ad3bf35"
  }
}

