PATCH /api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/qualifications/7d8e806d908044799be09c56caf03c35?acc_token=76496a084e5940338d92505c66df2c0d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "id": "7d8e806d908044799be09c56caf03c35", 
    "bidID": "3fcb1802c01a4643b2bc25dfb4ccafab"
  }
}

