PATCH /api/2.4/tenders/3f8dc71b13c046bea46f983700625cfa/qualifications/ecb4f5f04ca141fab5cbae7d89bd8b73?acc_token=d7c3b74a85b64c7e9a382bfbea960829 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "d5757bc712564f4a8e9ffa8792b966a6", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "3b7eecbc90854bdfbf2054ceae212850", 
    "date": "2018-11-23T19:06:55.459733+02:00", 
    "id": "ecb4f5f04ca141fab5cbae7d89bd8b73"
  }
}

