PATCH /api/2.1/tenders/2ae0a6552587422eb802cd052f41dd5d/qualifications/522aef4cfb93417c8731376e08223cf4?acc_token=60c300bf069847ba9e627fb5a5c5b4a0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "bidID": "92c65a77a24e4017b544214602e4e240", 
    "qualified": true, 
    "id": "522aef4cfb93417c8731376e08223cf4", 
    "eligible": true
  }
}

