GET /api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.auction", 
    "complaintPeriod": {
      "startDate": "2016-02-04T19:44:39.985627+02:00", 
      "endDate": "2016-03-02T19:44:39.985627+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/aa6128fa6a7a43e58bba316b9102ee69", 
    "enquiryPeriod": {
      "startDate": "2016-02-04T19:44:39.985627+02:00", 
      "endDate": "2016-02-25T19:44:39.985627+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "id": "7d8e806d908044799be09c56caf03c35", 
        "bidID": "3fcb1802c01a4643b2bc25dfb4ccafab"
      }, 
      {
        "status": "active", 
        "id": "0725e091aafd4ee8ab6f2aaf619d8d76", 
        "bidID": "b905232c5e3f4d518f6a71412667a42d"
      }, 
      {
        "status": "unsuccessful", 
        "id": "f0e090a7d7ea463faa911ec23ee862dd", 
        "bidID": "9b35789aa7474389be1cfc4c535c2976"
      }
    ], 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-03-16T20:20:39.985627+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-03-16T19:44:55.479446+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "4273044d9c45436eaa64a471460521f1", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "aa6128fa6a7a43e58bba316b9102ee69", 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/documents/9a74d798b62c4995b15cd3570d6592f0?download=ea5e8898090f45f6b58897e5c4194642", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T19:44:54.856435+02:00", 
        "id": "9a74d798b62c4995b15cd3570d6592f0", 
        "dateModified": "2016-03-16T19:44:54.856489+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/documents/8a2b76ed7fd24056bf3105bc627b8920?download=2923b6e23b484b0dadf242e483ce470a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T19:44:55.036597+02:00", 
        "id": "8a2b76ed7fd24056bf3105bc627b8920", 
        "dateModified": "2016-03-16T19:44:55.036645+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/documents/8a2b76ed7fd24056bf3105bc627b8920?download=93774b9d2bf54a9397f6d7f55931e6cc", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T19:44:55.036597+02:00", 
        "id": "8a2b76ed7fd24056bf3105bc627b8920", 
        "dateModified": "2016-03-16T19:44:55.298022+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2016-03-06T19:44:39.985627+02:00", 
      "endDate": "2016-03-16T19:44:39.985627+02:00"
    }, 
    "tenderID": "UA-2016-03-16-000001", 
    "dateModified": "2016-03-16T19:45:01.429574+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2016-02-04T19:44:39.985627+02:00", 
      "endDate": "2016-03-06T19:44:39.985627+02:00"
    }, 
    "auctionPeriod": {
      "startDate": "2016-03-16T19:44:39.985627+02:00", 
      "shouldStartAfter": "2016-03-16T19:44:39.985627+02:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "ccaf50470f9a4047bbfb7ed45dc98786", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "f7f27900035749c8ab4979773778a1bb", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/bids/3fcb1802c01a4643b2bc25dfb4ccafab/documents/ded1caab112e460181616963dcef1a5a?download=df68c9dcbb7a4b63870b81126663083a", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2016-03-16T19:44:56.664438+02:00", 
            "id": "ded1caab112e460181616963dcef1a5a", 
            "dateModified": "2016-03-16T19:44:56.664486+02:00"
          }, 
          {
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "Proposal_top_secrets.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/bids/3fcb1802c01a4643b2bc25dfb4ccafab/documents/dd8fdfbb432a40dc94c841ad7b54baba?download=1c4a0f9097a347fdaf9904e518813d64", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2016-03-16T19:44:56.861175+02:00", 
            "id": "dd8fdfbb432a40dc94c841ad7b54baba", 
            "dateModified": "2016-03-16T19:44:56.861212+02:00"
          }
        ], 
        "id": "3fcb1802c01a4643b2bc25dfb4ccafab"
      }, 
      {
        "status": "active", 
        "id": "b905232c5e3f4d518f6a71412667a42d"
      }, 
      {
        "status": "unsuccessful", 
        "id": "9b35789aa7474389be1cfc4c535c2976"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

