GET /api/2.1/tenders/4bafba9f3e5d4ea68be29833767557ff HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2016-03-06T11:18:03.231818+02:00", 
      "endDate": "2016-03-20T11:18:03.231818+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/4bafba9f3e5d4ea68be29833767557ff", 
    "enquiryPeriod": {
      "startDate": "2016-03-06T11:18:03.231818+02:00", 
      "endDate": "2016-03-20T11:18:03.231818+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-03-22T11:54:03.231818+02:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-03-22T11:18:19.785410+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "af6853c88a5343ce89a129b5020c7885", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "4bafba9f3e5d4ea68be29833767557ff", 
    "documents": [
      {
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/4bafba9f3e5d4ea68be29833767557ff/documents/9e968b370e094b868ec7fee215e79562?download=b20463de176e481bae6de4efddf7d948", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-22T11:18:19.093571+02:00", 
        "id": "9e968b370e094b868ec7fee215e79562", 
        "dateModified": "2016-03-22T11:18:19.093604+02:00"
      }, 
      {
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/4bafba9f3e5d4ea68be29833767557ff/documents/0e5c697965764e1986450f305f8c2359?download=88a26c8d7e2b4cad95e0a3f30cdc77c0", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-22T11:18:19.324182+02:00", 
        "id": "0e5c697965764e1986450f305f8c2359", 
        "dateModified": "2016-03-22T11:18:19.324210+02:00"
      }, 
      {
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/4bafba9f3e5d4ea68be29833767557ff/documents/0e5c697965764e1986450f305f8c2359?download=5c9bfc6543c746bfaa9c999d4c8a5ab1", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-22T11:18:19.324182+02:00", 
        "id": "0e5c697965764e1986450f305f8c2359", 
        "dateModified": "2016-03-22T11:18:19.552683+02:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2016-03-22-000001", 
    "dateModified": "2016-03-22T11:18:22.531130+02:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2016-03-06T11:18:03.231818+02:00", 
      "endDate": "2016-03-22T11:18:03.231818+02:00"
    }, 
    "auctionPeriod": {
      "startDate": "2016-03-22T11:18:03.231818+02:00", 
      "shouldStartAfter": "2016-03-22T11:18:03.231818+02:00"
    }, 
    "procurementMethodType": "aboveThresholdUA.defense", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-03-24T11:18:03.232872+02:00", 
          "endDate": "2016-03-27T11:18:03.232872+03:00"
        }, 
        "id": "e7d26014b9164f988e5da301f543d6d9", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }
  }
}

