PATCH /api/2.3/tenders/bedc169a4a1144ee970c8c19b37b8a09/awards/77d597e0fe0841be96a9b89d6c614f75/complaints/6164f4b8030f485496dabf9ef9564a59?acc_token=c7c33604df654f22b7835cfb8fb3197a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2017-06-19T18:35:38.672536+03:00", 
    "complaintID": "UA-2017-06-19-000001.9", 
    "date": "2017-06-19T18:35:38.686920+03:00", 
    "type": "claim", 
    "id": "6164f4b8030f485496dabf9ef9564a59"
  }
}

