GET /api/2.3/tenders/e564a943c46a443497a81bcdac928861/awards/13e739fca10d4715839fb7544af40491/complaints/c272a954052d4a93a04ad483b84213d2 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2017-09-14T19:40:38.129870+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/e564a943c46a443497a81bcdac928861/awards/13e739fca10d4715839fb7544af40491/complaints/c272a954052d4a93a04ad483b84213d2/documents/349f815d819b481d8bd0dcffd5221681?download=27cb1024cf30489fafd038a7c33a036f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-14T19:40:30.809507+03:00", 
        "id": "349f815d819b481d8bd0dcffd5221681", 
        "dateModified": "2017-09-14T19:40:30.809589+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/e564a943c46a443497a81bcdac928861/awards/13e739fca10d4715839fb7544af40491/complaints/c272a954052d4a93a04ad483b84213d2/documents/40f22dba904e4c5f99100696ae06d89a?download=a2cc1e313e87436a8c9a61d24ffb8be5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-14T19:40:37.372683+03:00", 
        "id": "40f22dba904e4c5f99100696ae06d89a", 
        "dateModified": "2017-09-14T19:40:37.372766+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2017-09-14T19:40:34.443145+03:00", 
    "dateSubmitted": "2017-09-14T19:40:31.233167+03:00", 
    "complaintID": "UA-2017-09-14-000001.1", 
    "date": "2017-09-14T19:40:38.158723+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "c272a954052d4a93a04ad483b84213d2"
  }
}

