PATCH /api/2.3/tenders/e564a943c46a443497a81bcdac928861/awards/13e739fca10d4715839fb7544af40491?acc_token=0b47211b46614b86b9023205c630966f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2017-09-14T19:40:29.857664+03:00", 
      "endDate": "2017-09-14T19:40:41.117472+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-09-14T19:40:41.146437+03:00", 
    "qualified": true, 
    "complaints": [
      {
        "status": "satisfied", 
        "dateDecision": "2017-09-14T19:40:38.129870+03:00", 
        "documents": [
          {
            "author": "complaint_owner", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/e564a943c46a443497a81bcdac928861/awards/13e739fca10d4715839fb7544af40491/complaints/c272a954052d4a93a04ad483b84213d2/documents/349f815d819b481d8bd0dcffd5221681?download=27cb1024cf30489fafd038a7c33a036f", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-09-14T19:40:30.809507+03:00", 
            "id": "349f815d819b481d8bd0dcffd5221681", 
            "dateModified": "2017-09-14T19:40:30.809589+03:00"
          }, 
          {
            "author": "aboveThresholdReviewers", 
            "title": "ComplaintResolution.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/e564a943c46a443497a81bcdac928861/awards/13e739fca10d4715839fb7544af40491/complaints/c272a954052d4a93a04ad483b84213d2/documents/40f22dba904e4c5f99100696ae06d89a?download=a2cc1e313e87436a8c9a61d24ffb8be5", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-09-14T19:40:37.372683+03:00", 
            "id": "40f22dba904e4c5f99100696ae06d89a", 
            "dateModified": "2017-09-14T19:40:37.372766+03:00"
          }
        ], 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateAccepted": "2017-09-14T19:40:34.443145+03:00", 
        "dateSubmitted": "2017-09-14T19:40:31.233167+03:00", 
        "complaintID": "UA-2017-09-14-000001.1", 
        "date": "2017-09-14T19:40:38.158723+03:00", 
        "acceptance": true, 
        "type": "complaint", 
        "id": "c272a954052d4a93a04ad483b84213d2"
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2017-09-14T19:40:33.775939+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": false, 
        "dateSubmitted": "2017-09-14T19:40:31.646817+03:00", 
        "complaintID": "UA-2017-09-14-000001.2", 
        "date": "2017-09-14T19:40:33.806846+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "998c6a513f1a47d480ef6daf2bbe9cfd"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2017-09-14T19:40:38.853200+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2017-09-14T19:40:35.271319+03:00", 
        "dateSubmitted": "2017-09-14T19:40:32.103369+03:00", 
        "complaintID": "UA-2017-09-14-000001.3", 
        "date": "2017-09-14T19:40:38.880192+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "0978221c423947ca9098f709c5646ffb"
      }, 
      {
        "status": "accepted", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2017-09-14T19:40:35.945168+03:00", 
        "dateSubmitted": "2017-09-14T19:40:32.596679+03:00", 
        "complaintID": "UA-2017-09-14-000001.4", 
        "date": "2017-09-14T19:40:35.983874+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "9b496a6845ab4817ac3b41ec54ebd194"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2017-09-14T19:40:39.594409+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "dateCanceled": "2017-09-14T19:40:39.594451+03:00", 
        "dateAccepted": "2017-09-14T19:40:36.667273+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2017-09-14T19:40:33.151856+03:00", 
        "complaintID": "UA-2017-09-14-000001.5", 
        "date": "2017-09-14T19:40:39.625276+03:00", 
        "type": "complaint", 
        "id": "a09e5e8360774ba1b78aac98c10196cd"
      }
    ], 
    "id": "13e739fca10d4715839fb7544af40491"
  }
}

