PATCH /api/2.3/tenders/26088e6631ba4910a4ac84197a700dd4/awards/e6a0e20f54694b6d85727649a5c95cae/complaints/5c937c5a9f2a4f869d6deff875bbf06d?acc_token=2fe49c2f5a39469eaf9a08c04e1655cf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 361
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2017-06-21T16:19:05.053750+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/26088e6631ba4910a4ac84197a700dd4/awards/e6a0e20f54694b6d85727649a5c95cae/complaints/5c937c5a9f2a4f869d6deff875bbf06d/documents/618aaf4bc75546118cea23f5eb10bd11?download=ea7b6fdd4795428b8d8845da461641a5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-21T16:19:03.304257+03:00", 
        "id": "618aaf4bc75546118cea23f5eb10bd11", 
        "dateModified": "2017-06-21T16:19:03.304302+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/26088e6631ba4910a4ac84197a700dd4/awards/e6a0e20f54694b6d85727649a5c95cae/complaints/5c937c5a9f2a4f869d6deff875bbf06d/documents/565727d4ad834bb09f716a0fa578a85c?download=67e2c73c20394cae957efe27f811beba", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-21T16:19:04.872275+03:00", 
        "id": "565727d4ad834bb09f716a0fa578a85c", 
        "dateModified": "2017-06-21T16:19:04.872325+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "tendererActionDate": "2017-06-21T16:19:06.136112+03:00", 
    "dateSubmitted": "2017-06-21T16:19:03.413486+03:00", 
    "complaintID": "UA-2017-06-21-000001.1", 
    "date": "2017-06-21T16:19:06.144044+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "5c937c5a9f2a4f869d6deff875bbf06d", 
    "dateAccepted": "2017-06-21T16:19:04.231870+03:00"
  }
}

