PATCH /api/0.12/tenders/8eeb974a14fc4416b03c6686da567954/awards/d9acef10e3c8450488ba6d940c70ab14/complaints/c4b8d8c98c9f469bbe7611c5b92269f8 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2016-03-07T12:56:07.762880+02:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/8eeb974a14fc4416b03c6686da567954/awards/d9acef10e3c8450488ba6d940c70ab14/complaints/c4b8d8c98c9f469bbe7611c5b92269f8/documents/4c3f9f7e0c164739a440455e73be8116?download=c25c5c2ae03546c3a3a49bff4542df5c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-07T12:56:05.972272+02:00", 
        "id": "4c3f9f7e0c164739a440455e73be8116", 
        "dateModified": "2016-03-07T12:56:05.972322+02:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/8eeb974a14fc4416b03c6686da567954/awards/d9acef10e3c8450488ba6d940c70ab14/complaints/c4b8d8c98c9f469bbe7611c5b92269f8/documents/0fe59354d0864228b54841fe4b1c6771?download=28402304eb0b4b7faffa5b508d398150", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-07T12:56:07.520369+02:00", 
        "id": "0fe59354d0864228b54841fe4b1c6771", 
        "dateModified": "2016-03-07T12:56:07.520419+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2016-03-07T12:56:07.026961+02:00", 
    "dateSubmitted": "2016-03-07T12:56:06.152446+02:00", 
    "complaintID": "UA-2016-03-07-000001.1", 
    "date": "2016-03-07T12:56:05.556690+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "c4b8d8c98c9f469bbe7611c5b92269f8"
  }
}

