PATCH /api/2.4/tenders/d274b60ebac849478795fab82829fb55/awards/fedb5884989c4b91ac353ece0f790a1d/complaints/301f1d4f61db4e73928436cb9c01d9e8?acc_token=503981fb68864ca5ad2e952c36af74a9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "ddb35dd0e9904726aafd18baed24863a", 
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2018-11-30T16:38:18.664702+02:00", 
    "complaintID": "UA-2018-11-30-000001.9", 
    "date": "2018-11-30T16:38:18.676818+02:00", 
    "type": "claim", 
    "id": "301f1d4f61db4e73928436cb9c01d9e8"
  }
}

