GET /api/2.0/tenders/56f06c8af40d4726be8ec769dae616d2/awards/e0ae14fd258a4f939fb77c063eddec0c/complaints/dbff01d7955f4fbfbad9f13dc3404a0a HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-03-16T12:38:11.584987+02:00", 
    "tendererActionDate": "2016-03-16T12:38:12.153914+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "dbff01d7955f4fbfbad9f13dc3404a0a", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2016-03-16T12:38:09.664434+02:00", 
    "complaintID": "UA-2016-03-16-000001.1", 
    "date": "2016-03-16T12:38:09.017494+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/56f06c8af40d4726be8ec769dae616d2/awards/e0ae14fd258a4f939fb77c063eddec0c/complaints/dbff01d7955f4fbfbad9f13dc3404a0a/documents/7ba220dfdc4c4f6683dce6711f653f79?download=3aaf24f467d04ffd81c0f91d72d05846", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T12:38:09.411064+02:00", 
        "id": "7ba220dfdc4c4f6683dce6711f653f79", 
        "dateModified": "2016-03-16T12:38:09.411102+02:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/56f06c8af40d4726be8ec769dae616d2/awards/e0ae14fd258a4f939fb77c063eddec0c/complaints/dbff01d7955f4fbfbad9f13dc3404a0a/documents/3cccf6e941d04e6aa2ee2a473312fc8e?download=2166026092254c3193dc3a3bb133a2fc", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T12:38:11.310776+02:00", 
        "id": "3cccf6e941d04e6aa2ee2a473312fc8e", 
        "dateModified": "2016-03-16T12:38:11.310814+02:00"
      }
    ], 
    "dateAccepted": "2016-03-16T12:38:10.677370+02:00"
  }
}

