GET /api/2.1/tenders/f3b249bbb97446378e73dc251059a798/awards/f0c50abb296241c4985548c0fa6871ea/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2016-03-24T13:17:24.532351+02:00", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/f3b249bbb97446378e73dc251059a798/awards/f0c50abb296241c4985548c0fa6871ea/complaints/d2c41e8e47cd43c696a058cd75682918/documents/110f13476abb4f1a8556c2c4858332db?download=6a416e4866cb440c9f2844c2a6d27b00", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-24T13:17:22.708879+02:00", 
          "id": "110f13476abb4f1a8556c2c4858332db", 
          "dateModified": "2016-03-24T13:17:22.708920+02:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/f3b249bbb97446378e73dc251059a798/awards/f0c50abb296241c4985548c0fa6871ea/complaints/d2c41e8e47cd43c696a058cd75682918/documents/45b4319a01164a7693e2e7536ea56d0c?download=c2dcf0de64d64263ad698fd7b4840834", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-24T13:17:24.293640+02:00", 
          "id": "45b4319a01164a7693e2e7536ea56d0c", 
          "dateModified": "2016-03-24T13:17:24.293692+02:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "tendererAction": "Умови виправлено", 
      "tendererActionDate": "2016-03-24T13:17:25.017372+02:00", 
      "dateSubmitted": "2016-03-24T13:17:22.943390+02:00", 
      "complaintID": "UA-2016-03-24-000001.1", 
      "date": "2016-03-24T13:17:22.502010+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "d2c41e8e47cd43c696a058cd75682918", 
      "dateAccepted": "2016-03-24T13:17:23.829711+02:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2016-03-24T13:17:23.621863+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2016-03-24T13:17:23.176583+02:00", 
      "complaintID": "UA-2016-03-24-000001.2", 
      "date": "2016-03-24T13:17:23.175185+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "78fc5c7ecf5a44b780e844d80caf60ec"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2016-03-24T13:17:24.768704+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2016-03-24T13:17:24.064442+02:00", 
      "dateSubmitted": "2016-03-24T13:17:23.420760+02:00", 
      "complaintID": "UA-2016-03-24-000001.3", 
      "date": "2016-03-24T13:17:23.419370+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "7f5e0b62270741fb916d706f167b69c2"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2016-03-24T13:17:25.502896+02:00", 
      "dateSubmitted": "2016-03-24T13:17:25.253186+02:00", 
      "complaintID": "UA-2016-03-24-000001.4", 
      "date": "2016-03-24T13:17:25.251826+02:00", 
      "type": "complaint", 
      "id": "6e9d383325684719b292314f46d39e08"
    }
  ]
}

