GET /api/2.0/tenders/1ab41f6499f64046abdda33d155de8c9/awards/606e0f0a4e884569acf42e14def6d029/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "satisfied", 
      "dateDecision": "2016-04-15T12:37:02.236982+03:00", 
      "documents": [
        {
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/1ab41f6499f64046abdda33d155de8c9/awards/606e0f0a4e884569acf42e14def6d029/complaints/f5ed8f50082c44e9b9204b5b2fd4c755/documents/95aaf18d02154ff39727642f7142192d?download=4102f5b5c1db4e299fc4204949e7e3b9", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-04-15T12:36:57.466802+03:00", 
          "id": "95aaf18d02154ff39727642f7142192d", 
          "dateModified": "2016-04-15T12:36:57.466848+03:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/1ab41f6499f64046abdda33d155de8c9/awards/606e0f0a4e884569acf42e14def6d029/complaints/f5ed8f50082c44e9b9204b5b2fd4c755/documents/7a82207e7ed64a5b9275ed377248e070?download=94675a9fec3b4c91a848366201174575", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-04-15T12:37:01.978151+03:00", 
          "id": "7a82207e7ed64a5b9275ed377248e070", 
          "dateModified": "2016-04-15T12:37:01.978203+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2016-04-15T12:37:00.740692+03:00", 
      "dateSubmitted": "2016-04-15T12:36:57.890130+03:00", 
      "complaintID": "UA-2016-04-15-000001.1", 
      "date": "2016-04-15T12:36:56.726628+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "f5ed8f50082c44e9b9204b5b2fd4c755"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2016-04-15T12:37:00.199921+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2016-04-15T12:36:58.358190+03:00", 
      "complaintID": "UA-2016-04-15-000001.2", 
      "date": "2016-04-15T12:36:58.356248+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "4966b5403b8642cea941a79792f7aefc"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2016-04-15T12:37:02.488641+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2016-04-15T12:37:00.988053+03:00", 
      "dateSubmitted": "2016-04-15T12:36:58.704238+03:00", 
      "complaintID": "UA-2016-04-15-000001.3", 
      "date": "2016-04-15T12:36:58.702234+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "1a3f3c87afac47eeb5bf236261d299f3"
    }, 
    {
      "status": "accepted", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2016-04-15T12:37:01.232158+03:00", 
      "dateSubmitted": "2016-04-15T12:36:59.173345+03:00", 
      "complaintID": "UA-2016-04-15-000001.4", 
      "date": "2016-04-15T12:36:59.171436+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "23a53b93d38946c1acaf4e226701651e"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2016-04-15T12:37:02.770274+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2016-04-15T12:37:02.770312+03:00", 
      "dateAccepted": "2016-04-15T12:37:01.501265+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2016-04-15T12:36:59.635448+03:00", 
      "complaintID": "UA-2016-04-15-000001.5", 
      "date": "2016-04-15T12:36:59.630443+03:00", 
      "type": "complaint", 
      "id": "b80d1defdd3c485089554dcef8c2b4d0"
    }
  ]
}

