PATCH /api/2.3/tenders/efb3367838164580a7d7bed1707e496c/awards/be8d5b1db89249c38257ba25de041ad6/complaints/c089cd7169964147aa60f6d9fd54aa58?acc_token=f974f5ba5f6d47749691c6fcd5b96a97 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "satisfied": false
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "invalid", 
    "type": "claim", 
    "title": "Недостатньо інформації", 
    "satisfied": false, 
    "dateAnswered": "2017-06-19T19:52:38.016580+03:00", 
    "dateSubmitted": "2017-06-19T19:52:37.808119+03:00", 
    "complaintID": "UA-2017-06-19-000001.7", 
    "date": "2017-06-19T19:52:38.028092+03:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "c089cd7169964147aa60f6d9fd54aa58"
  }
}

