PATCH /api/2.3/tenders/69d7bfc4f2764d528025eb51b18e4ea2/awards/1b7920063c5843118839b3f455bebf79/complaints/0790ec3c70b94b6fa63dbf2f0b0a485b HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "accepted", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69d7bfc4f2764d528025eb51b18e4ea2/awards/1b7920063c5843118839b3f455bebf79/complaints/0790ec3c70b94b6fa63dbf2f0b0a485b/documents/ea3ad032acc949c5b69314f991ec4e67?download=a44eaf741ee04bc1b5763af466262d5e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-04-25T14:46:47.016143+03:00", 
        "id": "ea3ad032acc949c5b69314f991ec4e67", 
        "dateModified": "2016-04-25T14:46:47.016182+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2016-04-25T14:46:48.479064+03:00", 
    "dateSubmitted": "2016-04-25T14:46:47.200019+03:00", 
    "complaintID": "UA-2016-04-25-000001.1", 
    "date": "2016-04-25T14:46:46.656214+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "0790ec3c70b94b6fa63dbf2f0b0a485b"
  }
}

