POST /api/2.3/tenders/efb3367838164580a7d7bed1707e496c/awards/4b0f75a5cc5e4931bb4b059777640b5a/complaints?acc_token=e5c5dac720e54075884b1e63f95af6a8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1682
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/efb3367838164580a7d7bed1707e496c/awards/4b0f75a5cc5e4931bb4b059777640b5a/complaints/0e47b12784e248a88c1a5e6a1485040b
{
  "access": {
    "token": "49cfaacec4a540d9901ffafcc070d3eb"
  }, 
  "data": {
    "status": "draft", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "complaintID": "UA-2017-06-19-000001.9", 
    "date": "2017-06-19T19:52:42.732407+03:00", 
    "type": "claim", 
    "id": "0e47b12784e248a88c1a5e6a1485040b"
  }
}

