GET /api/0.12/tenders/0d15ad4f13aa4a8e853e499fbc03d2e5/awards/a690e83e266740418225dcea5b8689a2/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2016-03-10T16:54:24.788142+02:00", 
      "tendererActionDate": "2016-03-10T16:54:25.356514+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "061ddd96ef544a96a38cd9eedab6de20", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2016-03-10T16:54:22.799593+02:00", 
      "complaintID": "UA-2016-03-10-000001.1", 
      "date": "2016-03-10T16:54:22.164585+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/0d15ad4f13aa4a8e853e499fbc03d2e5/awards/a690e83e266740418225dcea5b8689a2/complaints/061ddd96ef544a96a38cd9eedab6de20/documents/f506902e18124ffda153fce541425d45?download=e62aacb0e2c74b4aaefe73f208d188cc", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-10T16:54:22.553756+02:00", 
          "id": "f506902e18124ffda153fce541425d45", 
          "dateModified": "2016-03-10T16:54:22.553796+02:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/0d15ad4f13aa4a8e853e499fbc03d2e5/awards/a690e83e266740418225dcea5b8689a2/complaints/061ddd96ef544a96a38cd9eedab6de20/documents/c7a8441873d64c79a5d3c29b804bb078?download=94af0a2f9c204334acc5dee064a05fcd", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-10T16:54:24.512818+02:00", 
          "id": "c7a8441873d64c79a5d3c29b804bb078", 
          "dateModified": "2016-03-10T16:54:24.512872+02:00"
        }
      ], 
      "dateAccepted": "2016-03-10T16:54:23.822085+02:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2016-03-10T16:54:23.530863+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2016-03-10T16:54:23.041860+02:00", 
      "complaintID": "UA-2016-03-10-000001.2", 
      "date": "2016-03-10T16:54:23.038175+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "4185a4936d5445088d45c843caeb1a13"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2016-03-10T16:54:25.053624+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2016-03-10T16:54:24.211270+02:00", 
      "dateSubmitted": "2016-03-10T16:54:23.275540+02:00", 
      "complaintID": "UA-2016-03-10-000001.3", 
      "date": "2016-03-10T16:54:23.274033+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "bffe648114924da8b7ea6cfbd6ebd019"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2016-03-10T16:54:25.890762+02:00", 
      "dateSubmitted": "2016-03-10T16:54:25.633715+02:00", 
      "complaintID": "UA-2016-03-10-000001.4", 
      "date": "2016-03-10T16:54:25.632317+02:00", 
      "type": "complaint", 
      "id": "128c7c7e518349938419edc410506044"
    }
  ]
}

