GET /api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/729c141818264b82860033ad69ca2f63?acc_token=b01e9a57fe644451be4f0a48dbd0843e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/729c141818264b82860033ad69ca2f63/documents/3dc90454f6544828a17bf04884ecaec8?download=dc3d0bc858bd4b7097d3f907489c8c00", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:10.493115+03:00", 
        "id": "3dc90454f6544828a17bf04884ecaec8", 
        "dateModified": "2017-09-05T14:44:10.493150+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/729c141818264b82860033ad69ca2f63/documents/34612db2fa584d91a7c15aa90337eb2f?download=fab0aa61a20b467fab3e92ab7253b1ce", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:10.554146+03:00", 
        "id": "34612db2fa584d91a7c15aa90337eb2f", 
        "dateModified": "2017-09-05T14:44:10.554164+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/729c141818264b82860033ad69ca2f63/eligibility_documents/592e2460b0ee4d23bd5f3c52d81c29a1?download=2eb5ceb4f2e44bf4a2778c155fde224f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:10.858189+03:00", 
        "id": "592e2460b0ee4d23bd5f3c52d81c29a1", 
        "dateModified": "2017-09-05T14:44:10.858206+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "729c141818264b82860033ad69ca2f63", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/729c141818264b82860033ad69ca2f63/financial_documents/6e43f05a20cc4ee48e9974d0bce9880b?download=3a9f6b6b62aa4ff4ad421bd90105ac14", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:10.696435+03:00", 
        "id": "6e43f05a20cc4ee48e9974d0bce9880b", 
        "dateModified": "2017-09-05T14:44:10.696468+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/729c141818264b82860033ad69ca2f63/financial_documents/a32fbbd65d184fd9a794f9761209f9c2?download=b469204fae194ecba11825899bd89542", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:10.769345+03:00", 
        "id": "a32fbbd65d184fd9a794f9761209f9c2", 
        "dateModified": "2017-09-05T14:44:10.769374+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-09-05T14:44:10.381301+03:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/729c141818264b82860033ad69ca2f63/qualification_documents/1644a6adcef546f1abb5dba96974cc43?download=c0b7a86339b6473cbb25df7b9aab82b6", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:10.967611+03:00", 
        "id": "1644a6adcef546f1abb5dba96974cc43", 
        "dateModified": "2017-09-05T14:44:10.967641+03:00"
      }
    ]
  }
}

