GET /api/2.0/tenders/875bccb8079448419db42ee024419900/bids/38b0fc1d75df41c8ae0ac8d8c5cffdca/financial_documents?acc_token=e0cf11d98894440da940f658bf0ebd15 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "confidentiality": "public", 
      "language": "uk", 
      "title": "financial_doc.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/875bccb8079448419db42ee024419900/bids/38b0fc1d75df41c8ae0ac8d8c5cffdca/financial_documents/4cf09f4e72884cc698ab1876636ed952?download=d9b9e2777bd8434084260bca6a9986f7", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-03-18T17:08:19.894301+02:00", 
      "id": "4cf09f4e72884cc698ab1876636ed952", 
      "dateModified": "2016-03-18T17:08:19.894338+02:00"
    }, 
    {
      "confidentiality": "public", 
      "language": "uk", 
      "title": "financial_doc2.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/875bccb8079448419db42ee024419900/bids/38b0fc1d75df41c8ae0ac8d8c5cffdca/financial_documents/76dde4d9437f41de8e06b7e0c93f9d9e?download=4ff39d5dc997407a8d93f609a38282cf", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-03-18T17:08:20.107880+02:00", 
      "id": "76dde4d9437f41de8e06b7e0c93f9d9e", 
      "dateModified": "2016-03-18T17:08:20.107927+02:00"
    }
  ]
}

