GET /api/2.0/tenders/67832b95357c4428aa90a1f80d5a7241/bids/5a9c56bafe7b4e3d8af0bd8fbc365d34?acc_token=e0d3b728ced04172ac91ad21693fc5cc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2016-03-16T12:38:26.316012+02:00", 
    "id": "5a9c56bafe7b4e3d8af0bd8fbc365d34", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/67832b95357c4428aa90a1f80d5a7241?key_for_bid=5a9c56bafe7b4e3d8af0bd8fbc365d34"
  }
}

