PATCH /api/0.12/tenders/30a1cf2907c64f058d80dfadaedb4eec/bids/28b7c5d82fef4562a3e7ef192846e5e3?acc_token=e08f67854d2f4cc6b6c5753e7edcd08d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/30a1cf2907c64f058d80dfadaedb4eec/bids/28b7c5d82fef4562a3e7ef192846e5e3/documents/1496b304217a44c0b2a7701133620d8d?download=7ca58a5d102947429322c6f8ea4dca98", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-10T16:54:36.657392+02:00", 
        "id": "1496b304217a44c0b2a7701133620d8d", 
        "dateModified": "2016-03-10T16:54:36.657432+02:00"
      }, 
      {
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "title": "Proposal_top_secrets.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/30a1cf2907c64f058d80dfadaedb4eec/bids/28b7c5d82fef4562a3e7ef192846e5e3/documents/0551a196ebd744978805eb28bc31eb1c?download=18f8041e25b14e6180601e2b5e9775d2", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-10T16:54:36.851023+02:00", 
        "id": "0551a196ebd744978805eb28bc31eb1c", 
        "dateModified": "2016-03-10T16:54:36.851060+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/30a1cf2907c64f058d80dfadaedb4eec/bids/28b7c5d82fef4562a3e7ef192846e5e3/eligibility_documents/ad8671f4376e483691766741572821cf?download=9a10f42b25e24251b716772b364fd74e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-10T16:54:37.893064+02:00", 
        "id": "ad8671f4376e483691766741572821cf", 
        "dateModified": "2016-03-10T16:54:37.893102+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "28b7c5d82fef4562a3e7ef192846e5e3", 
    "financialDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/30a1cf2907c64f058d80dfadaedb4eec/bids/28b7c5d82fef4562a3e7ef192846e5e3/financial_documents/0eec65f760254edf91dcfb7e06f28dfa?download=40a8228ebf5d41dca9dba922662d6d82", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-10T16:54:37.337949+02:00", 
        "id": "0eec65f760254edf91dcfb7e06f28dfa", 
        "dateModified": "2016-03-10T16:54:37.337988+02:00"
      }, 
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/30a1cf2907c64f058d80dfadaedb4eec/bids/28b7c5d82fef4562a3e7ef192846e5e3/financial_documents/4fc49d63e4664a1885d67d1f71075992?download=a33e21baf6ea4111abc47bd0a7e8dfb8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-10T16:54:37.577404+02:00", 
        "id": "4fc49d63e4664a1885d67d1f71075992", 
        "dateModified": "2016-03-10T16:54:37.577445+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-03-10T16:54:36.433593+02:00", 
    "qualificationDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/30a1cf2907c64f058d80dfadaedb4eec/bids/28b7c5d82fef4562a3e7ef192846e5e3/qualification_documents/b2979c69a56e4cbb92a037cee2c55fb4?download=a794fd13b25b4f3cbf170bb011dd25d1", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-10T16:54:38.131013+02:00", 
        "id": "b2979c69a56e4cbb92a037cee2c55fb4", 
        "dateModified": "2016-03-10T16:54:38.131053+02:00"
      }
    ]
  }
}

