PATCH /api/0.12/tenders/e3e16eb63b584378b75d9eb01dc2f8b9/bids/c41709780fa8434399c62a1facf369cb?acc_token=d0d0cebbaeba447da04fe765210a4ee8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/e3e16eb63b584378b75d9eb01dc2f8b9/bids/c41709780fa8434399c62a1facf369cb/documents/a05aff4e91c942bbad7e49e551399ec7?download=d0984048f149465699fd402bfe20881c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-24T14:13:36.127526+02:00", 
        "id": "a05aff4e91c942bbad7e49e551399ec7", 
        "dateModified": "2016-02-24T14:13:36.127580+02:00"
      }, 
      {
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "title": "Proposal_top_secrets.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/e3e16eb63b584378b75d9eb01dc2f8b9/bids/c41709780fa8434399c62a1facf369cb/documents/9cbec3ead89e45759aaba28804487010?download=6e95380008fc4b569d25e46a3b5e78b2", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-24T14:13:36.297950+02:00", 
        "id": "9cbec3ead89e45759aaba28804487010", 
        "dateModified": "2016-02-24T14:13:36.298001+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/e3e16eb63b584378b75d9eb01dc2f8b9/bids/c41709780fa8434399c62a1facf369cb/eligibility_documents/33338aec1d664df48683849a2eafcebd?download=8aed6f5b0ffb4bfab11fc377c235a5bb", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-24T14:13:37.031482+02:00", 
        "id": "33338aec1d664df48683849a2eafcebd", 
        "dateModified": "2016-02-24T14:13:37.031532+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "c41709780fa8434399c62a1facf369cb", 
    "financialDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/e3e16eb63b584378b75d9eb01dc2f8b9/bids/c41709780fa8434399c62a1facf369cb/financial_documents/7519d21b32af432396acd6e2c9e18ee5?download=5db59ae05361427b84c4caddb0b6d92b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-24T14:13:36.625252+02:00", 
        "id": "7519d21b32af432396acd6e2c9e18ee5", 
        "dateModified": "2016-02-24T14:13:36.625290+02:00"
      }, 
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/e3e16eb63b584378b75d9eb01dc2f8b9/bids/c41709780fa8434399c62a1facf369cb/financial_documents/05ae13720e6448728c2e635362ecee20?download=0cb6bca324c84c338e38eba05535f15b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-24T14:13:36.790331+02:00", 
        "id": "05ae13720e6448728c2e635362ecee20", 
        "dateModified": "2016-02-24T14:13:36.790370+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-02-24T14:13:35.941621+02:00", 
    "qualificationDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/e3e16eb63b584378b75d9eb01dc2f8b9/bids/c41709780fa8434399c62a1facf369cb/qualification_documents/00b29d1cf4c840efad26c90108baecb7?download=262d73f49ac64c89a40a99d1b85320f8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-24T14:13:37.233941+02:00", 
        "id": "00b29d1cf4c840efad26c90108baecb7", 
        "dateModified": "2016-02-24T14:13:37.233992+02:00"
      }
    ]
  }
}

