GET /api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76?acc_token=9ef2a88bc6aa4242bcc332fc3d2cc81a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "25ac7a23a2c2469a89730fdc082d6c76"
  }
}

