GET /api/2.4/tenders/0eba7509160946dd8439ca46baa56801/bids/8136c8ad133a440b8c220815122c1eff?acc_token=12b78e802c374448afb6b8af27537352 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/10eda34f45804b9ab0427aec6e0fa21f?KeyID=2a9e5e2d&Signature=QfxL4u5pYaF5Bn3L9pmubFG8IOE4TXsR4uUB6RN5%2FY4eqlGYDFyVy2SkiqWaY2MQuQ3VBWipzrIV3YDwZV9dAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-05T14:24:27.927755+03:00", 
        "id": "0e854c216d2344fab4b73a2cbf727b2b", 
        "dateModified": "2018-09-05T14:24:27.927769+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0eba7509160946dd8439ca46baa56801/bids/8136c8ad133a440b8c220815122c1eff/documents/00216379918448898094a9cc8df0913c?download=a2b2d0556623472e8e0ab08efe2236f2", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-05T14:24:27.928175+03:00", 
        "id": "00216379918448898094a9cc8df0913c", 
        "dateModified": "2018-09-05T14:24:27.928189+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/f7e7396434f54ac8b4f47cfc5e30c04b?KeyID=2a9e5e2d&Signature=cSuKLPA%252BjcMKUmDTk1yql656j9OYxn1SMj0PsG%252BiIen%252B860CU7RsvdVQn3vHVsG5%252B91WzkCmVubgUg0WCMqxBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-05T14:24:27.929019+03:00", 
        "id": "b3c873dcbe5848e6a7e41ed209ce4896", 
        "dateModified": "2018-09-05T14:24:27.929032+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "8136c8ad133a440b8c220815122c1eff", 
    "lotValues": [
      {
        "relatedLot": "f70782e4693042cca51ec2dda36d5f15", 
        "date": "2018-09-05T14:24:27.929791+03:00", 
        "status": "active", 
        "value": {
          "currency": "UAH", 
          "amount": 5.0, 
          "valueAddedTaxIncluded": true
        }, 
        "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/0eba7509160946dd8439ca46baa56801_f70782e4693042cca51ec2dda36d5f15?key_for_bid=8136c8ad133a440b8c220815122c1eff"
      }
    ], 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0eba7509160946dd8439ca46baa56801/bids/8136c8ad133a440b8c220815122c1eff/financial_documents/d062a2a519d64057a594968df52cd86a?download=da93456ddbc94b00b6fa0a50715756ee", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-05T14:24:27.928601+03:00", 
        "id": "d062a2a519d64057a594968df52cd86a", 
        "dateModified": "2018-09-05T14:24:27.928614+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-09-05T14:24:27.927377+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0eba7509160946dd8439ca46baa56801/bids/8136c8ad133a440b8c220815122c1eff/qualification_documents/4fcf2468f267416090ea75ee0d97e18f?download=ddb92030fe014a999d4ac16a6c7a7cd2", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-05T14:24:27.929428+03:00", 
        "id": "4fcf2468f267416090ea75ee0d97e18f", 
        "dateModified": "2018-09-05T14:24:27.929442+03:00"
      }
    ]
  }
}

