PATCH /api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76?acc_token=9ef2a88bc6aa4242bcc332fc3d2cc81a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76/documents/75f708e5e327471d889880518d130be2?download=1bcb94b7212646faa54389f6a11ed869", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:24.916629+02:00", 
        "id": "75f708e5e327471d889880518d130be2", 
        "dateModified": "2018-11-30T16:38:24.916644+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76/documents/1ea08abf3f87461eabb43cc19537d3af?download=07bc54de91224fa6b1c3ad1a7568f105", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:24.990333+02:00", 
        "id": "1ea08abf3f87461eabb43cc19537d3af", 
        "dateModified": "2018-11-30T16:38:24.990354+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76/eligibility_documents/e2e7ecf7b3214e979833d774fbbfea16?download=8d9bafe0b86d4752a10894677b473b26", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:25.459777+02:00", 
        "id": "e2e7ecf7b3214e979833d774fbbfea16", 
        "dateModified": "2018-11-30T16:38:25.459791+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "25ac7a23a2c2469a89730fdc082d6c76", 
    "lotValues": [
      {
        "relatedLot": "ddb35dd0e9904726aafd18baed24863a", 
        "date": "2018-11-30T16:38:24.769391+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76/financial_documents/97b604aa79594468ab0d6d4bcfd46be3?download=987e8a265cf14fe9a235e8d0a9efbc59", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:25.181514+02:00", 
        "id": "97b604aa79594468ab0d6d4bcfd46be3", 
        "dateModified": "2018-11-30T16:38:25.181529+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76/financial_documents/84b17fa242004f309fc5bc39c69531c0?download=febf37605b9649bba6b5978fdc41ddd6", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:25.354452+02:00", 
        "id": "84b17fa242004f309fc5bc39c69531c0", 
        "dateModified": "2018-11-30T16:38:25.354467+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-11-30T16:38:24.769050+02:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76/qualification_documents/5d9bc313501345358844075dc44f9adb?download=2bfb3896fec04980ad414cd9510df964", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:25.544681+02:00", 
        "id": "5d9bc313501345358844075dc44f9adb", 
        "dateModified": "2018-11-30T16:38:25.544696+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4e095f899aea431dade658804787b2aa/bids/25ac7a23a2c2469a89730fdc082d6c76/qualification_documents/5d9bc313501345358844075dc44f9adb?download=53923497284c45bf8fc595a106aeacf6", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:25.544681+02:00", 
        "id": "5d9bc313501345358844075dc44f9adb", 
        "dateModified": "2018-11-30T16:38:25.639513+02:00"
      }
    ]
  }
}

