GET /api/2.3/tenders/97dd0ca9a0f741a6ad5628c6873d1de9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2017-06-21T15:53:20.003863+03:00", 
      "endDate": "2017-07-07T15:53:06.068679+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2017-06-21T15:53:20.003863+03:00", 
      "clarificationsUntil": "2017-07-03T15:53:06.068679+03:00", 
      "endDate": "2017-06-27T15:53:06.068679+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2017-06-21T15:53:20.003863+03:00", 
      "endDate": "2017-07-03T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2017-06-21T15:53:20.034093+03:00", 
    "next_check": "2017-07-07T15:53:06.068679+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-07-08T00:00:00+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2017-06-21T15:53:20.038399+03:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-07-11T15:53:06.068598+03:00", 
          "endDate": "2017-08-10T15:53:06.068650+03:00"
        }, 
        "id": "fc733ce56c434220bb9e7418b0de6162", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "97dd0ca9a0f741a6ad5628c6873d1de9", 
    "tenderID": "UA-2017-06-21-000001"
  }
}

