GET /api/2.4/tenders/29fb21ea52a64dc8a1614d1f312ec395 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "draft", 
    "procurementMethod": "selective", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2018-09-29T09:56:35.860440+03:00", 
      "endDate": "2018-10-12T09:56:35.860440+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "a93d95632cac485ca6dca149ce24be57", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-30T09:56:35.860440+03:00", 
          "endDate": "2018-10-03T09:56:35.860440+03:00"
        }, 
        "id": "1662b0e1d59f4e2f8e2c5bd48e03a7bc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "closeFrameworkAgreementSelectionUA", 
    "value": {
      "currency": "UAH", 
      "amount": 600.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2018-09-28T09:56:36.594441+03:00", 
    "dateModified": "2018-09-28T09:56:36.599548+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2018-09-28T09:56:36.594375+03:00", 
      "endDate": "2018-09-29T09:56:35.860440+03:00"
    }, 
    "owner": "broker", 
    "agreements": [
      {
        "id": "9aa744f37d10468685a77be968bfe979"
      }
    ], 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 600.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2018-09-28T09:56:36.594441+03:00", 
        "id": "a93d95632cac485ca6dca149ce24be57"
      }
    ], 
    "id": "29fb21ea52a64dc8a1614d1f312ec395", 
    "tenderID": "UA-2018-09-28-000001"
  }
}

