PATCH /api/2.0/tenders/21a336eb47ba46639e13dc36d064e863/complaints/db29ed2503e8480493e14df995453549?acc_token=38bc9c69990a42a58be5a467c6fbf61c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "dateAnswered": "2016-03-16T12:38:16.233163+02:00", 
    "dateSubmitted": "2016-03-16T12:38:15.305243+02:00", 
    "complaintID": "UA-2016-03-16-000001.2", 
    "date": "2016-03-16T12:38:15.303832+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "db29ed2503e8480493e14df995453549"
  }
}

