GET /api/2.1/tenders/8111c86d9f664af2ba3726682e15954f/complaints/35d6ab39661a4db98eaf08a74dacaf1f HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-03-28T12:23:27.561466+03:00", 
    "tendererActionDate": "2016-03-28T12:23:28.052235+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "35d6ab39661a4db98eaf08a74dacaf1f", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2016-03-28T12:23:25.401029+03:00", 
    "complaintID": "UA-2016-03-28-000001.1", 
    "date": "2016-03-28T12:23:24.094629+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/8111c86d9f664af2ba3726682e15954f/complaints/35d6ab39661a4db98eaf08a74dacaf1f/documents/6831d719c6164f4d828f582699b88040?download=2558a3edd8d84cc3b993638aa9eac4df", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-28T12:23:24.284491+03:00", 
        "id": "6831d719c6164f4d828f582699b88040", 
        "dateModified": "2016-03-28T12:23:24.284533+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/8111c86d9f664af2ba3726682e15954f/complaints/35d6ab39661a4db98eaf08a74dacaf1f/documents/da4553dea7614408a85696668931e657?download=c88010d9cdf4438f8546c344e89cbe17", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-28T12:23:27.328948+03:00", 
        "id": "da4553dea7614408a85696668931e657", 
        "dateModified": "2016-03-28T12:23:27.328987+03:00"
      }
    ], 
    "dateAccepted": "2016-03-28T12:23:26.906369+03:00"
  }
}

