PATCH /api/2.0/tenders/0432ebc2181a42efaf9feb1c6969a531/complaints/d88840431213447b9dfe71978c31b5a4 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "accepted", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/0432ebc2181a42efaf9feb1c6969a531/complaints/d88840431213447b9dfe71978c31b5a4/documents/b78bfea8499d4547b7ef9a98b395bc97?download=e64321b00440460e9a207b3eb9a2e6d9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T17:30:42.000195+02:00", 
        "id": "b78bfea8499d4547b7ef9a98b395bc97", 
        "dateModified": "2016-03-16T17:30:42.000234+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2016-03-16T17:30:43.682029+02:00", 
    "dateSubmitted": "2016-03-16T17:30:42.721715+02:00", 
    "complaintID": "UA-2016-03-16-000001.1", 
    "date": "2016-03-16T17:30:41.867865+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "d88840431213447b9dfe71978c31b5a4"
  }
}

