GET /api/2.4/tenders/5edb7347341b4620b034f3b85522c7a2/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2017-10-03T11:17:49.443194+03:00", 
      "tendererActionDate": "2017-10-03T11:17:49.873211+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "dd0b2ac5565642f58531284d4c0cbd0c", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2017-10-03T11:17:47.930461+03:00", 
      "complaintID": "UA-2017-10-03-000001.1", 
      "date": "2017-10-03T11:17:49.880002+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/08edaae0300e4539bc97530ab4fcfbe8?KeyID=9a183b93&Signature=z2af9H2G23rRweea5FZKAMVEHnYdmYXUzZEcYUswenZKlwbQcWXFU6oiOKYGjH8PxkJdVtn5XH9wg1CjW7VQBA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-10-03T11:17:47.499921+03:00", 
          "id": "71a09cf26e1b43e6ae03c56fbe6b1a8c", 
          "dateModified": "2017-10-03T11:17:47.499962+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/e41ffe81961a4ea095b3876ac82381ae?KeyID=9a183b93&Signature=q4FeiJWxdmMQNrtlMBjKlbcZGggK%252BNLfcubR3zE6bRa%252B%252BVb3CqWQHLE0seGJJS42hFswrHtMJ2EhGfVWs6XwBA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-10-03T11:17:49.296936+03:00", 
          "id": "fc1e848a61ec47dbaf3a1cfc78addd5c", 
          "dateModified": "2017-10-03T11:17:49.296967+03:00"
        }
      ], 
      "dateAccepted": "2017-10-03T11:17:48.811203+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2017-10-03T11:17:48.031472+03:00", 
      "dateSubmitted": "2017-10-03T11:17:47.656142+03:00", 
      "complaintID": "UA-2017-10-03-000001.2", 
      "date": "2017-10-03T11:17:48.242512+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "7f4af07d62d04a42b06eb2c4bcebc58d"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2017-10-03T11:17:49.582286+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2017-10-03T11:17:48.932970+03:00", 
      "dateSubmitted": "2017-10-03T11:17:47.739747+03:00", 
      "complaintID": "UA-2017-10-03-000001.3", 
      "date": "2017-10-03T11:17:49.589094+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "1bb1214c8a2242dbae20a203f1478b44"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2017-10-03T11:17:48.677038+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2017-10-03T11:17:48.343600+03:00", 
      "dateAnswered": "2017-10-03T11:17:48.132400+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-10-03T11:17:47.828265+03:00", 
      "complaintID": "UA-2017-10-03-000001.4", 
      "date": "2017-10-03T11:17:48.683736+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "f7ae68c0fc044307b8823c8e2fdb09cf"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-10-03T11:17:49.721145+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2017-10-03T11:17:49.721175+03:00", 
      "dateAccepted": "2017-10-03T11:17:49.055819+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-10-03T11:17:48.447565+03:00", 
      "complaintID": "UA-2017-10-03-000001.5", 
      "date": "2017-10-03T11:17:49.728147+03:00", 
      "type": "complaint", 
      "id": "e3efcd2396004720a61392460fd9f69b"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-10-03T11:17:50.166914+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2017-10-03T11:17:50.023612+03:00", 
      "dateAccepted": "2017-10-03T11:17:49.177455+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-10-03T11:17:48.555320+03:00", 
      "complaintID": "UA-2017-10-03-000001.6", 
      "date": "2017-10-03T11:17:50.173747+03:00", 
      "type": "complaint", 
      "id": "b57a6e60aa3d4f98a2d27b85dee8c933"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2017-10-03T11:17:50.458496+03:00", 
      "complaintID": "UA-2017-10-03-000001.7", 
      "date": "2017-10-03T11:17:50.465897+03:00", 
      "type": "claim", 
      "id": "08a7d864f6c24400806e4f01b49b6b52"
    }
  ]
}

