PATCH /api/2.4/tenders/b9b2e5c85dd34318b8d5aa47657184f8/complaints/5b7420f5212e484ea73a7474826b3d5f HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "invalid"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "dateDecision": "2017-09-28T15:01:07.063737+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "invalid", 
    "type": "complaint", 
    "acceptance": false, 
    "satisfied": false, 
    "dateEscalated": "2017-09-28T15:01:06.716652+03:00", 
    "dateAnswered": "2017-09-28T15:01:06.506558+03:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2017-09-28T15:01:06.192303+03:00", 
    "complaintID": "UA-2017-09-28-000001.4", 
    "date": "2017-09-28T15:01:07.070939+03:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "5b7420f5212e484ea73a7474826b3d5f"
  }
}

