PATCH /api/2.4/tenders/2aa86d67fce04133bc5b09bd2b3036ec/complaints/6df6864fc3bd4984ad5fb73a3c54d624?acc_token=e0b88625479245cba484fb586ea76019 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2018-11-23T19:06:44.226413+02:00", 
    "complaintID": "UA-2018-11-23-000001.7", 
    "date": "2018-11-23T19:06:44.242703+02:00", 
    "type": "claim", 
    "id": "6df6864fc3bd4984ad5fb73a3c54d624"
  }
}

