PATCH /api/2.0/tenders/cb21e4074e2648b2a9b0bd645249e139/complaints/ffff0d3f510b45949e27566ee14892b1 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2016-03-18T17:08:15.122584+02:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/cb21e4074e2648b2a9b0bd645249e139/complaints/ffff0d3f510b45949e27566ee14892b1/documents/bd0f166ac0da47f0ae34cab63a981087?download=31bfb1adfb524c8dbe4478f2f72b3a31", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-18T17:08:12.850487+02:00", 
        "id": "bd0f166ac0da47f0ae34cab63a981087", 
        "dateModified": "2016-03-18T17:08:12.850525+02:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/cb21e4074e2648b2a9b0bd645249e139/complaints/ffff0d3f510b45949e27566ee14892b1/documents/b398baef077640a2a8583e0058fa53fd?download=7a23343bf13248ae8a8a5b145fcabaae", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-18T17:08:14.963980+02:00", 
        "id": "b398baef077640a2a8583e0058fa53fd", 
        "dateModified": "2016-03-18T17:08:14.964020+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2016-03-18T17:08:14.668217+02:00", 
    "dateSubmitted": "2016-03-18T17:08:13.616768+02:00", 
    "complaintID": "UA-2016-03-18-000001.1", 
    "date": "2016-03-18T17:08:12.753981+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "ffff0d3f510b45949e27566ee14892b1"
  }
}

