PATCH /api/2.3/tenders/95406b89097549e48c364931fcf50fc9/complaints/049ab535aeb84789a56318014a00aade HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2017-06-21T16:09:22.935844+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/95406b89097549e48c364931fcf50fc9/complaints/049ab535aeb84789a56318014a00aade/documents/88ccb2488c7841dcaf11779a9e473ea8?download=22c9c8df023f406db6807e4bd52e52e9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-21T16:09:20.845593+03:00", 
        "id": "88ccb2488c7841dcaf11779a9e473ea8", 
        "dateModified": "2017-06-21T16:09:20.845635+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/95406b89097549e48c364931fcf50fc9/complaints/049ab535aeb84789a56318014a00aade/documents/31361a5b20df4ea89e93a039d03ae6e1?download=b28963f5442449f1906c0e5a4c652380", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-21T16:09:22.693125+03:00", 
        "id": "31361a5b20df4ea89e93a039d03ae6e1", 
        "dateModified": "2017-06-21T16:09:22.693163+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2017-06-21T16:09:22.170148+03:00", 
    "dateSubmitted": "2017-06-21T16:09:21.262859+03:00", 
    "complaintID": "UA-2017-06-21-000001.1", 
    "date": "2017-06-21T16:09:22.943907+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "049ab535aeb84789a56318014a00aade"
  }
}

