GET /api/2.3/tenders/95406b89097549e48c364931fcf50fc9/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2017-06-21T16:09:22.935844+03:00", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/95406b89097549e48c364931fcf50fc9/complaints/049ab535aeb84789a56318014a00aade/documents/88ccb2488c7841dcaf11779a9e473ea8?download=22c9c8df023f406db6807e4bd52e52e9", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-06-21T16:09:20.845593+03:00", 
          "id": "88ccb2488c7841dcaf11779a9e473ea8", 
          "dateModified": "2017-06-21T16:09:20.845635+03:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/95406b89097549e48c364931fcf50fc9/complaints/049ab535aeb84789a56318014a00aade/documents/31361a5b20df4ea89e93a039d03ae6e1?download=b28963f5442449f1906c0e5a4c652380", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-06-21T16:09:22.693125+03:00", 
          "id": "31361a5b20df4ea89e93a039d03ae6e1", 
          "dateModified": "2017-06-21T16:09:22.693163+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "tendererAction": "Умови виправлено", 
      "tendererActionDate": "2017-06-21T16:09:23.393951+03:00", 
      "dateSubmitted": "2017-06-21T16:09:21.262859+03:00", 
      "complaintID": "UA-2017-06-21-000001.1", 
      "date": "2017-06-21T16:09:23.401604+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "049ab535aeb84789a56318014a00aade", 
      "dateAccepted": "2017-06-21T16:09:22.170148+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2017-06-21T16:09:21.367705+03:00", 
      "complaintID": "UA-2017-06-21-000001.2", 
      "date": "2017-06-21T16:09:21.577072+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "0373c139d1164fa3afd41a4677e13bda"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2017-06-21T16:09:23.082207+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2017-06-21T16:09:22.300593+03:00", 
      "dateSubmitted": "2017-06-21T16:09:21.071199+03:00", 
      "complaintID": "UA-2017-06-21-000001.3", 
      "date": "2017-06-21T16:09:23.089894+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "be4b982fe88a48b494da7d4582392508"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2017-06-21T16:09:22.029842+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2017-06-21T16:09:21.683137+03:00", 
      "dateAnswered": "2017-06-21T16:09:21.468456+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "complaintID": "UA-2017-06-21-000001.4", 
      "date": "2017-06-21T16:09:22.037489+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "e276da503cc64421b95e2384b04a2905"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-06-21T16:09:23.232954+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2017-06-21T16:09:23.232993+03:00", 
      "dateAccepted": "2017-06-21T16:09:22.432463+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-06-21T16:09:21.786661+03:00", 
      "complaintID": "UA-2017-06-21-000001.5", 
      "date": "2017-06-21T16:09:23.240517+03:00", 
      "type": "complaint", 
      "id": "336a83354d5c4aaa8e04848540ef1289"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-06-21T16:09:23.702289+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2017-06-21T16:09:23.547765+03:00", 
      "dateAccepted": "2017-06-21T16:09:22.563554+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-06-21T16:09:21.900854+03:00", 
      "complaintID": "UA-2017-06-21-000001.6", 
      "date": "2017-06-21T16:09:23.711258+03:00", 
      "type": "complaint", 
      "id": "b94097c8f3b747ecbec7cc86b4cbb0b0"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2017-06-21T16:09:24.020699+03:00", 
      "complaintID": "UA-2017-06-21-000001.7", 
      "date": "2017-06-21T16:09:24.029153+03:00", 
      "type": "claim", 
      "id": "f2cabe6d19dd473bb09750ce13c72e86"
    }
  ]
}

