PATCH /api/0.12/tenders/2124973b187d454ea5bba0fa8d049b6e/complaints/f2bf82b959d0400b845224166aa45e43 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "accepted", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/2124973b187d454ea5bba0fa8d049b6e/complaints/f2bf82b959d0400b845224166aa45e43/documents/9b0b2405f8b74d2a9a38c11a5b97a7e6?download=0e9d359ccbc840c6897ab25a72a1a1cf", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-07T12:47:31.604117+02:00", 
        "id": "9b0b2405f8b74d2a9a38c11a5b97a7e6", 
        "dateModified": "2016-03-07T12:47:31.604166+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2016-03-07T12:47:33.251249+02:00", 
    "dateSubmitted": "2016-03-07T12:47:32.337354+02:00", 
    "complaintID": "UA-2016-03-07-000001.1", 
    "date": "2016-03-07T12:47:31.492376+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "f2bf82b959d0400b845224166aa45e43"
  }
}

