PATCH /api/2.3/tenders/d3dba9240047439492b162acda141abd/awards/e3d40093a1cf4f438eb0915fbd77f847?acc_token=4d2022f0685446d6ab06c53b51e10410 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2017-06-21T16:09:27.228895+03:00", 
      "endDate": "2017-07-07T00:00:00+03:00"
    }, 
    "bid_id": "3a603e289a1b4c06ad023bd5705e03a2", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2017-06-21T16:09:27.418164+03:00", 
    "id": "e3d40093a1cf4f438eb0915fbd77f847"
  }
}

