PATCH /api/2.0/tenders/70d0ba2a1b064d1184fe606b7d74f36d/awards/77b1f9067dfe4da6b3cd382ac273ea8a?acc_token=cde3cb8ddf9a4842b5d7d8f1cb3ca510 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-04-15T12:37:31.681337+03:00", 
      "endDate": "2016-04-25T12:37:32.472869+03:00"
    }, 
    "bid_id": "dcbea377778848738d5953d013fb4371", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2016-04-15T12:37:31.681833+03:00", 
    "id": "77b1f9067dfe4da6b3cd382ac273ea8a"
  }
}

