PATCH /api/2.0/tenders/e2b439a8a7a5473b9b0bb65a8f97b74a/awards/aa131b60e3b2433aa588681e89cd87ef?acc_token=598d0fba58f349ab822741755b3d45ce HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-03-21T15:54:34.679098+02:00", 
      "endDate": "2016-03-31T15:54:34.919257+02:00"
    }, 
    "bid_id": "6eeb76cd75b54d49a141dc90e835bf61", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2016-03-21T15:54:34.679564+02:00", 
    "id": "aa131b60e3b2433aa588681e89cd87ef"
  }
}

