GET /api/2.3/contracts/2b96ac8412b94512a3db4613143b7150/documents?acc_token=df4891826c6d4e4eabd56e02b6540e49 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "title": "contract.doc", 
      "url": "http://api-sandbox.openprocurement.org/api/2.3/contracts/2b96ac8412b94512a3db4613143b7150/documents/7dd48b2d4fa144118abae6cb0a6e863c?download=36b9133e1182494a908e2328afcc0b10", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2016-05-10T20:18:01.776394+03:00", 
      "id": "7dd48b2d4fa144118abae6cb0a6e863c", 
      "dateModified": "2016-05-10T20:18:01.776434+03:00"
    }
  ]
}

