GET /api/2.3/tenders/817f808830d84ae4b5f5b1406287df5e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "complete", 
    "awardPeriod": {
      "startDate": "2016-05-10T17:45:06.445682+03:00", 
      "endDate": "2016-05-10T17:45:06.445682+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2016-04-25T17:45:06.445682+03:00", 
      "endDate": "2016-05-02T17:45:06.445682+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "817f808830d84ae4b5f5b1406287df5e", 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2016-05-20-000001", 
    "dateModified": "2016-05-20T17:45:11.622522+03:00", 
    "numberOfBids": 1, 
    "tenderPeriod": {
      "startDate": "2016-05-02T17:45:06.445682+03:00", 
      "endDate": "2016-05-09T17:45:06.445682+03:00"
    }, 
    "contracts": [
      {
        "status": "active", 
        "items": [
          {
            "description": "футляри до державних нагород", 
            "classification": {
              "scheme": "CPV", 
              "description": "Cartons", 
              "id": "44617100-9"
            }, 
            "additionalClassifications": [
              {
                "scheme": "ДКПП", 
                "id": "17.21.1", 
                "description": "папір і картон гофровані, паперова й картонна тара"
              }
            ], 
            "deliveryAddress": {
              "postalCode": "79000", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "deliveryDate": {
              "startDate": "2016-05-22T17:45:06.445682+03:00", 
              "endDate": "2016-05-25T17:45:06.445682+03:00"
            }, 
            "id": "da7f6394f251459dba2a2cbd773c054a", 
            "unit": {
              "code": "44617100-9", 
              "name": "item"
            }, 
            "quantity": 5
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ], 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateSigned": "2016-05-20T17:45:11.615401+03:00", 
        "date": "2016-05-20T17:45:11.615350+03:00", 
        "awardID": "48ecfe1c29894bbca9570c0c97e19a66", 
        "id": "5202ba63c8984cba89150812ad45e70d", 
        "contractID": "UA-2016-05-20-000001-1"
      }
    ], 
    "auctionPeriod": {
      "startDate": "2016-05-09T17:45:06.445682+03:00", 
      "endDate": "2016-05-10T17:45:06.445682+03:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "awards": [
      {
        "status": "active", 
        "complaintPeriod": {
          "startDate": "2016-05-20T17:45:10.955789+03:00", 
          "endDate": "2016-05-20T17:45:10.955789+03:00"
        }, 
        "suppliers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ], 
        "bid_id": "8ecd4f7a12dc41249c6941ab1f3cbcb2", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2016-05-20T17:45:11.140719+03:00", 
        "id": "48ecfe1c29894bbca9570c0c97e19a66"
      }
    ], 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-05-22T17:45:06.445682+03:00", 
          "endDate": "2016-05-25T17:45:06.445682+03:00"
        }, 
        "id": "da7f6394f251459dba2a2cbd773c054a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "bids": [
      {
        "date": "2016-05-20T17:45:10.648644+03:00", 
        "id": "8ecd4f7a12dc41249c6941ab1f3cbcb2", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

