GET /api/2.4/tenders/3c9f0ba3810346ad895f5da76bf91287/questions/bba3355d666f4c9a9f22e7c4cf0012e4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-09-04T16:14:09.373787+03:00", 
    "title": "Калорійність", 
    "date": "2018-09-04T16:14:09.257795+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "bba3355d666f4c9a9f22e7c4cf0012e4", 
    "questionOf": "tender"
  }
}

