GET /api/0.12/tenders/1861a4241d1a4781a17ec0689782b64e/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "date": "2016-03-10T16:24:44.095957+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "a416dc8747e6462bb19941cea0d3b213", 
      "questionOf": "tender"
    }
  ]
}

