PATCH /api/2.3/tenders/d3dba9240047439492b162acda141abd?acc_token=4d2022f0685446d6ab06c53b51e10410 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-07-06T16:09:34.900823+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2017-06-21T16:09:24.755173+03:00", 
      "endDate": "2017-07-06T16:09:34.900823+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2017-06-21T16:09:24.755173+03:00", 
      "clarificationsUntil": "2017-07-05T16:09:34.900823+03:00", 
      "endDate": "2017-07-03T16:09:34.900823+03:00", 
      "invalidationDate": "2017-06-21T16:09:24.966118+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2017-06-21T16:09:24.755173+03:00", 
      "endDate": "2017-07-04T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA.defense", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2017-06-21T16:09:24.792303+03:00", 
    "next_check": "2017-07-06T16:09:34.900823+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "kind": "defense", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-07-07T00:00:00+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2017-06-21T16:09:24.969226+03:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-07-11T16:09:10.869776+03:00", 
          "endDate": "2017-08-10T16:09:10.869828+03:00"
        }, 
        "id": "088c06079114432a868884642967dd98", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "d3dba9240047439492b162acda141abd", 
    "tenderID": "UA-2017-06-21-000001"
  }
}

