PATCH /api/0.12/tenders/2cb1b7f3e1fa4c98b5280eddf376b99c/cancellations/3e274123ad3144feaec0ee89818847ad/documents/2473ebb7bac5499fbf81adbde3166840?acc_token=1d05531f91d541f68e88ec5e344a1c0f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/2cb1b7f3e1fa4c98b5280eddf376b99c/cancellations/3e274123ad3144feaec0ee89818847ad/documents/2473ebb7bac5499fbf81adbde3166840?download=2af73eebf78345009ea85811b12d95fc", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-02-02T19:24:07.895086+02:00", 
    "id": "2473ebb7bac5499fbf81adbde3166840", 
    "dateModified": "2016-02-02T19:24:07.895124+02:00"
  }
}

