PATCH /api/2.1/tenders/11bebb5333a6417fbba49e95735be407/cancellations/694a67dd014d49b7a53876d959174bdf/documents/32342ce04dbc4a61941397072c3bb4df?acc_token=8dbeca7d38464057a84101f8cf67cd53 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/11bebb5333a6417fbba49e95735be407/cancellations/694a67dd014d49b7a53876d959174bdf/documents/32342ce04dbc4a61941397072c3bb4df?download=83959a6e4bae41198ac2fff301e1f327", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-28T17:22:49.017795+03:00", 
    "id": "32342ce04dbc4a61941397072c3bb4df", 
    "dateModified": "2016-03-28T17:22:49.017848+03:00"
  }
}

