POST /api/2.0/tenders/758613fb1d0b422bbadfc845623d06d8/cancellations?acc_token=796b39c16dee4bbf94bdc8b95e95a65e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/758613fb1d0b422bbadfc845623d06d8/cancellations/27a888ff42a848ad9b27b7249b9b566b
{
  "data": {
    "date": "2016-03-16T11:40:15.210249+02:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "27a888ff42a848ad9b27b7249b9b566b"
  }
}

