POST /api/0.12/tenders/8f40d7fc24494459a147760c9876612f/cancellations?acc_token=aafe82ed826d484ba0a326dba75116bf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/8f40d7fc24494459a147760c9876612f/cancellations/e3848622b96a4856b0b4462433dfa5dc
{
  "data": {
    "date": "2016-02-29T14:50:51.698064+02:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "e3848622b96a4856b0b4462433dfa5dc"
  }
}

