POST /api/2.4/tenders/909a83c7074941309af7770523938496/qualifications/ad7c7763251a494aa83b860f7103c3a3/complaints?acc_token=f368e0f3aad74ea4aad59b099e630483 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1701
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "claim", 
    "title": "Недостатньо інформації", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/909a83c7074941309af7770523938496/qualifications/ad7c7763251a494aa83b860f7103c3a3/complaints/d3ebea28c6eb4bc3a009b1d11d35795c
{
  "access": {
    "token": "5745bde63016484681f1a66e5f66e308"
  }, 
  "data": {
    "relatedLot": "90c2d26254824897b0edf34d662fb010", 
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "c007c59650d74adab08e4c2fb3229059", 
    "dateSubmitted": "2018-11-21T18:16:20.365192+02:00", 
    "complaintID": "UA-2018-11-21-000001.6", 
    "date": "2018-11-21T18:16:20.364918+02:00", 
    "type": "claim", 
    "id": "d3ebea28c6eb4bc3a009b1d11d35795c"
  }
}

