GET /api/2.3/tenders/c91cc0e7dffc4bc7b59cf53d9bbfd0bf/bids?acc_token=1c073921ab5f4a30a693936b569bfa3b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/b5573ee1dc47405994ec4b7ab2646989?KeyID=ee3bcdd8&Signature=uoFBnWjqoDkldsS1zX6VtjaSpxUGKGtvz4woqmh8soCMUrgXXm5cv5O52J%2FIDEemrhyKTTodTmh00F0igyfLBA%253D%253D", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2017-06-21T17:05:14.833011+03:00", 
          "id": "f4cbc5957f3943f0941fd002dae1b1d3", 
          "dateModified": "2017-06-21T17:05:14.833044+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "DescriptiveProposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/c91cc0e7dffc4bc7b59cf53d9bbfd0bf/bids/2b73ea4bdef34b6481601d7f4049d3f0/documents/95baea1455bb4178956a1a19c2463961?download=ee55a3ff10ab4477a1d631c7b597ea74", 
          "format": "application/pdf", 
          "isDescriptionDecision": true, 
          "documentOf": "tender", 
          "datePublished": "2017-06-21T17:05:14.951905+03:00", 
          "id": "95baea1455bb4178956a1a19c2463961", 
          "dateModified": "2017-06-21T17:05:14.951937+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/c91cc0e7dffc4bc7b59cf53d9bbfd0bf/bids/2b73ea4bdef34b6481601d7f4049d3f0/documents/c16e3628164f4949b130b3f1d5fef9a3?download=7a1b1b88795a4716b72af39eefe0cd9b", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2017-06-21T17:05:15.194576+03:00", 
          "id": "c16e3628164f4949b130b3f1d5fef9a3", 
          "dateModified": "2017-06-21T17:05:15.194609+03:00"
        }
      ], 
      "id": "2b73ea4bdef34b6481601d7f4049d3f0", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "99d190d9f85547d0af5ecb28779f5ec2", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "selfEligible": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "selfQualified": true, 
      "id": "b017ee1976de45118f59fd0e27b3ecf1"
    }, 
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/0eba44f9b85c4c2ab0a628ef8b358dcb?KeyID=ee3bcdd8&Signature=J7Wx1vhPZEFdmwOZicW9lzLjpsY4AfEUIHIvf0oFPq1DkIxcF7ukP0EaqsLU%252BFxvbjmrv2EFAEXVLbOTkcswCA%253D%253D", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2017-06-21T17:05:16.360844+03:00", 
          "id": "170d3b5f86d8410eb5bc4aa6751dc015", 
          "dateModified": "2017-06-21T17:05:16.360890+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/c91cc0e7dffc4bc7b59cf53d9bbfd0bf/bids/7918119aa7584a10b19cfa71e47b1288/documents/f54d567c1aaa448ebe4ac0939f96471c?download=a8d02f05d73a4f72801a8223580e87c9", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2017-06-21T17:05:16.362131+03:00", 
          "id": "f54d567c1aaa448ebe4ac0939f96471c", 
          "dateModified": "2017-06-21T17:05:16.362174+03:00"
        }
      ], 
      "id": "7918119aa7584a10b19cfa71e47b1288", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Карпенко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137228", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Кенгуру»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Коцюбинського, 15", 
            "region": "м. Запоріжжя", 
            "locality": "м. Запоріжя"
          }
        }
      ]
    }
  ]
}

