GET /api/2.4/tenders/7a02bad8eb4f4f7fb33fa5ff0f536b4c/qualifications/68a5f98b716f4fa4bf3be70c91d28fd7/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2017-10-11T17:20:46.900354+03:00", 
      "tendererActionDate": "2017-10-11T17:20:47.850564+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "8e04096aa1b248c49fac8357fffe0e2f", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2017-10-11T17:20:39.075599+03:00", 
      "complaintID": "UA-2017-10-11-000001.1", 
      "date": "2017-10-11T17:20:47.886716+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/7b37a9d317b64f6f9db12bcc0d36d1b7?KeyID=ed8fe224&Signature=iOzSNlOXB1ihlKn8iv1Ta95Noc2HwRib4Sd%2FlpNzDOaiCRw9dykOUEDXigkYUZc%252BlWsWee331ZVO767dbTurAQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-10-11T17:20:38.863853+03:00", 
          "id": "8a36b28f33324d849d58d61d5f2dac60", 
          "dateModified": "2017-10-11T17:20:38.863903+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/637ff4e2a6774114888af07308a9245e?KeyID=ed8fe224&Signature=IsBPekVww%252B2JtuPvNdE8Tq2rq34z5XgCH9HxY3aqA%2FaF0s9WQKkQxFsW%2F9E3x%2FqCGrKMCRdbj9JJ5bw%252B7TvBCg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-10-11T17:20:46.585372+03:00", 
          "id": "b1cfe511ad384ecea1a54efedfc2f369", 
          "dateModified": "2017-10-11T17:20:46.585407+03:00"
        }
      ], 
      "dateAccepted": "2017-10-11T17:20:45.403957+03:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2017-10-11T17:20:45.113845+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2017-10-11T17:20:39.464065+03:00", 
      "complaintID": "UA-2017-10-11-000001.2", 
      "date": "2017-10-11T17:20:45.147849+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "3069755a8f2d41c2a44bee44852de828"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2017-10-11T17:20:47.212802+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2017-10-11T17:20:45.701571+03:00", 
      "dateSubmitted": "2017-10-11T17:20:39.675185+03:00", 
      "complaintID": "UA-2017-10-11-000001.3", 
      "date": "2017-10-11T17:20:47.248182+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "89d12c298ab2423f8d703663569c460c"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-10-11T17:20:48.488202+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2017-10-11T17:20:48.166686+03:00", 
      "dateAccepted": "2017-10-11T17:20:45.993733+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-10-11T17:20:39.892675+03:00", 
      "complaintID": "UA-2017-10-11-000001.4", 
      "date": "2017-10-11T17:20:48.523947+03:00", 
      "type": "complaint", 
      "id": "7055dda839e14991a8a552e14dbea1a5"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-10-11T17:20:47.526727+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2017-10-11T17:20:47.526761+03:00", 
      "dateAccepted": "2017-10-11T17:20:46.287876+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-10-11T17:20:40.131221+03:00", 
      "complaintID": "UA-2017-10-11-000001.5", 
      "date": "2017-10-11T17:20:47.562733+03:00", 
      "type": "complaint", 
      "id": "1df412392527488ebfef89f1b267a5dd"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "bid_id": "196fa18058da455f96e7b27e5a9bfd72", 
      "dateAnswered": "2017-10-11T17:20:40.647674+03:00", 
      "dateSubmitted": "2017-10-11T17:20:40.369964+03:00", 
      "complaintID": "UA-2017-10-11-000001.6", 
      "date": "2017-10-11T17:20:40.682455+03:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "732cfde262584514b266e067ce2af1a2"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "claim", 
      "satisfied": false, 
      "bid_id": "196fa18058da455f96e7b27e5a9bfd72", 
      "dateAnswered": "2017-10-11T17:20:41.595209+03:00", 
      "dateSubmitted": "2017-10-11T17:20:41.254212+03:00", 
      "complaintID": "UA-2017-10-11-000001.7", 
      "date": "2017-10-11T17:20:41.640764+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "9bf4ba960f534c67b1493d7fa3e8fbbb"
    }, 
    {
      "status": "claim", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "196fa18058da455f96e7b27e5a9bfd72", 
      "dateSubmitted": "2017-10-11T17:20:42.557651+03:00", 
      "complaintID": "UA-2017-10-11-000001.8", 
      "date": "2017-10-11T17:20:42.592509+03:00", 
      "type": "claim", 
      "id": "321a20f3c1664d3ab8f2a9fc45d4de5d"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "196fa18058da455f96e7b27e5a9bfd72", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2017-10-11T17:20:44.385432+03:00", 
      "complaintID": "UA-2017-10-11-000001.9", 
      "date": "2017-10-11T17:20:44.420650+03:00", 
      "type": "claim", 
      "id": "d269913ce4a849b881f86b2ee6177e72"
    }
  ]
}

