GET /api/0.12/tenders/873425a6097c41e9989714458f2dfee2/qualifications/564c391824634978964dcae6a798eb7e/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2016-03-07T12:56:19.352399+02:00", 
      "tendererActionDate": "2016-03-07T12:56:19.822135+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "991f4ac6948b488d8bbdd17af076451c", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2016-03-07T12:56:17.478486+02:00", 
      "complaintID": "UA-2016-03-07-000001.1", 
      "date": "2016-03-07T12:56:17.166417+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/873425a6097c41e9989714458f2dfee2/qualifications/564c391824634978964dcae6a798eb7e/complaints/991f4ac6948b488d8bbdd17af076451c/documents/eeed472de38748149b7d1926f2989d71?download=2044be62d46b40899a435fd0e29cd69e", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-07T12:56:17.310175+02:00", 
          "id": "eeed472de38748149b7d1926f2989d71", 
          "dateModified": "2016-03-07T12:56:17.310215+02:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/873425a6097c41e9989714458f2dfee2/qualifications/564c391824634978964dcae6a798eb7e/complaints/991f4ac6948b488d8bbdd17af076451c/documents/21e9360253df40cbb584f58acc22074e?download=00008e4317194430bad4f265e7f9d0b7", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-07T12:56:19.105519+02:00", 
          "id": "21e9360253df40cbb584f58acc22074e", 
          "dateModified": "2016-03-07T12:56:19.105566+02:00"
        }
      ], 
      "dateAccepted": "2016-03-07T12:56:18.651435+02:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2016-03-07T12:56:18.425186+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2016-03-07T12:56:17.628862+02:00", 
      "complaintID": "UA-2016-03-07-000001.1", 
      "date": "2016-03-07T12:56:17.626928+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "52a0debaf34b40e38b32c64d83d5ab5a"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2016-03-07T12:56:19.585167+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2016-03-07T12:56:18.890353+02:00", 
      "dateSubmitted": "2016-03-07T12:56:17.813239+02:00", 
      "complaintID": "UA-2016-03-07-000001.1", 
      "date": "2016-03-07T12:56:17.811651+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "05c35188b4c54de7b0e68c71ccc490af"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2016-03-07T12:56:18.215772+02:00", 
      "dateSubmitted": "2016-03-07T12:56:18.002140+02:00", 
      "complaintID": "UA-2016-03-07-000001.1", 
      "date": "2016-03-07T12:56:18.000087+02:00", 
      "type": "complaint", 
      "id": "06a571b3372f44b09fd740dcfeccc218"
    }
  ]
}

