GET /api/2.4/tenders/5a4381eb16f44f1c814eb5a091374398/qualifications/a3751657f0db4189837d63baa61fee39/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2017-09-28T18:39:31.799472+03:00", 
      "tendererActionDate": "2017-09-28T18:39:32.791921+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "f66251429c9e4ce6991ac756072f4818", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2017-09-28T18:39:24.913689+03:00", 
      "complaintID": "UA-2017-09-28-000001.1", 
      "date": "2017-09-28T18:39:32.819087+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/4d0acbac36514b9c83dce78956b9dbc5?KeyID=0416881c&Signature=1XP9VQpodw5rEw%252BfDlroZATaogly1tAqiDLxJ1Njk%2FtySFlisvvMGlqa1OM1RvrYFfFSwxC8f3ncM9HbX%2FCOAg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-09-28T18:39:24.708702+03:00", 
          "id": "b6114f3620624288a45d57b944c891b9", 
          "dateModified": "2017-09-28T18:39:24.708739+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/40da5c0a7d6740e2adbd3f090fb9d26f?KeyID=0416881c&Signature=LUWGjPl9iv5oO%252BUWzGCVPGs8XGOCHBID6AMa1jhswqHqVt%252B1CHGB3ybvmfE9g5yEaV1IPQcAVZHCNJ6STNC9Bw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-09-28T18:39:31.518160+03:00", 
          "id": "bf8688f48eff4f6d8e2333415a1c4f06", 
          "dateModified": "2017-09-28T18:39:31.518203+03:00"
        }
      ], 
      "dateAccepted": "2017-09-28T18:39:30.474004+03:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2017-09-28T18:39:30.207167+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2017-09-28T18:39:25.077108+03:00", 
      "complaintID": "UA-2017-09-28-000001.2", 
      "date": "2017-09-28T18:39:30.234763+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "d6249973d6694bc2bc11e5049dcd1a78"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2017-09-28T18:39:32.074697+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2017-09-28T18:39:30.738211+03:00", 
      "dateSubmitted": "2017-09-28T18:39:25.578338+03:00", 
      "complaintID": "UA-2017-09-28-000001.3", 
      "date": "2017-09-28T18:39:32.102474+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "6be6bb577a084e528d7298ae69650283"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-09-28T18:39:33.362621+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2017-09-28T18:39:33.071667+03:00", 
      "dateAccepted": "2017-09-28T18:39:31.003726+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-09-28T18:39:25.763990+03:00", 
      "complaintID": "UA-2017-09-28-000001.4", 
      "date": "2017-09-28T18:39:33.389717+03:00", 
      "type": "complaint", 
      "id": "a55fe50cda254780a23f839735fce078"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-09-28T18:39:32.499165+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2017-09-28T18:39:32.499194+03:00", 
      "dateAccepted": "2017-09-28T18:39:31.258337+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-09-28T18:39:25.949706+03:00", 
      "complaintID": "UA-2017-09-28-000001.5", 
      "date": "2017-09-28T18:39:32.527801+03:00", 
      "type": "complaint", 
      "id": "b6ae9b04dd3b4ceab4fab10900a891d0"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "bid_id": "5ba9d1c26eb64257824215e8001a33ef", 
      "dateAnswered": "2017-09-28T18:39:26.974319+03:00", 
      "dateSubmitted": "2017-09-28T18:39:26.158255+03:00", 
      "complaintID": "UA-2017-09-28-000001.6", 
      "date": "2017-09-28T18:39:26.999791+03:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "8ba6075271614328a36dcc2bec83bfeb"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "claim", 
      "satisfied": false, 
      "bid_id": "5ba9d1c26eb64257824215e8001a33ef", 
      "dateAnswered": "2017-09-28T18:39:28.716294+03:00", 
      "dateSubmitted": "2017-09-28T18:39:28.456811+03:00", 
      "complaintID": "UA-2017-09-28-000001.7", 
      "date": "2017-09-28T18:39:28.742207+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "3dd5888e9ec74d598f191f510a02fbe1"
    }, 
    {
      "status": "claim", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "5ba9d1c26eb64257824215e8001a33ef", 
      "dateSubmitted": "2017-09-28T18:39:29.422018+03:00", 
      "complaintID": "UA-2017-09-28-000001.8", 
      "date": "2017-09-28T18:39:29.448373+03:00", 
      "type": "claim", 
      "id": "bdaa5fe691a5422586aa7294db2201ac"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "5ba9d1c26eb64257824215e8001a33ef", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2017-09-28T18:39:29.950599+03:00", 
      "complaintID": "UA-2017-09-28-000001.9", 
      "date": "2017-09-28T18:39:29.977447+03:00", 
      "type": "claim", 
      "id": "533f7fa39b2b4c0a82337ec7c3a066b5"
    }
  ]
}

