PATCH /api/0.12/tenders/b208d7193afc4c2aadec95ba97347972/qualifications/867a9200d46048589147382daf4fede4/complaints/3cb147119a5f43e487d49f53adbdc0da?acc_token=6ff61a653e0b4b1096ca32b4262a9401 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2016-03-09T13:57:26.572247+02:00", 
    "dateSubmitted": "2016-03-09T13:57:26.325644+02:00", 
    "complaintID": "UA-2016-03-09-000001.4", 
    "date": "2016-03-09T13:57:26.324211+02:00", 
    "type": "complaint", 
    "id": "3cb147119a5f43e487d49f53adbdc0da"
  }
}

