GET /api/2.3/tenders/1d20995ed5284e04af2a300ca3d6c106/bids?acc_token=21c9b9907e0046e982f060fa94d6e1a2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/1d20995ed5284e04af2a300ca3d6c106/bids/f14a1354e4214936961609808b0e8de8/documents/21d41829ca56405187e3ef34e768abc7?download=8217498f60754db1a62fd40216d519b3", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2016-10-12T02:41:32.275867+03:00", 
          "id": "21d41829ca56405187e3ef34e768abc7", 
          "dateModified": "2016-10-12T02:41:32.275890+03:00"
        }, 
        {
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "DescriptiveProposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/1d20995ed5284e04af2a300ca3d6c106/bids/f14a1354e4214936961609808b0e8de8/documents/46ebb31c24e94f2b8c4d51bffeebc3f1?download=40c3690d78234df0a1fc3b602b149de8", 
          "format": "application/pdf", 
          "isDescriptionDecision": true, 
          "documentOf": "tender", 
          "datePublished": "2016-10-12T02:41:32.344078+03:00", 
          "id": "46ebb31c24e94f2b8c4d51bffeebc3f1", 
          "dateModified": "2016-10-12T02:41:32.344099+03:00"
        }, 
        {
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "Proposal_top_secrets.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/1d20995ed5284e04af2a300ca3d6c106/bids/f14a1354e4214936961609808b0e8de8/documents/c9fc4b2edbf24102a23a8d9ff4e7d4d4?download=b9c9c7aa849c473096a7a98aa7e13ee9", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2016-10-12T02:41:32.473873+03:00", 
          "id": "c9fc4b2edbf24102a23a8d9ff4e7d4d4", 
          "dateModified": "2016-10-12T02:41:32.473893+03:00"
        }
      ], 
      "id": "f14a1354e4214936961609808b0e8de8", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "c8ebe9bb7c054587b765e64f0f17e004", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "selfEligible": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "selfQualified": true, 
      "id": "9626a8e7e7424625918640c0cde8bdaf"
    }, 
    {
      "status": "active", 
      "id": "8ce20b31a959425383ada76447a39284", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Карпенко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137228", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Кенгуру»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Коцюбинського, 15", 
            "region": "м. Запоріжжя", 
            "locality": "м. Запоріжя"
          }
        }
      ]
    }
  ]
}

