GET /api/2.4/tenders/f6fb66b5bd02434d9e44744c9ad6d07c/qualifications/85378ee38bc94fe18ea30dcd3b6ccb90/complaints/7976584ec78c4ca5b1adc3daa2d9a344 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "ddb35dd0e9904726aafd18baed24863a", 
    "status": "resolved", 
    "dateDecision": "2018-11-30T16:38:42.389809+02:00", 
    "tendererActionDate": "2018-11-30T16:38:42.928686+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "7976584ec78c4ca5b1adc3daa2d9a344", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2018-11-30T16:38:39.294574+02:00", 
    "complaintID": "UA-2018-11-30-000001.1", 
    "date": "2018-11-30T16:38:42.938869+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/1bb8cdb97346450c81477fdbd79db0cb?KeyID=6c5d599a&Signature=y4vR0hnc8rt%252BCT0sLjHox72%252BnEvUMgf6snOfzNoJ%2FN8wGjix6W%252Bbcm%2FHlKTOg4gjR4ZRObDH8ro6nlOoGDTfBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:39.196657+02:00", 
        "id": "c30a233bd6c3435b820451db22f7d0e9", 
        "dateModified": "2018-11-30T16:38:39.196674+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a7f344cc5ce04864b0b11ee280f61e39?KeyID=6c5d599a&Signature=PlWi8yBk5XvQ94hYJP%2FzlQ%252BjqlrB3hwFX5OzaOUg6LerHgLqhisJZju9bmUiCJNPEAUxYVFYXtwFNsoNIbmSAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-11-30T16:38:42.201673+02:00", 
        "id": "e6d61d3e965349469480ad31e790bb61", 
        "dateModified": "2018-11-30T16:38:42.201692+02:00"
      }
    ], 
    "dateAccepted": "2018-11-30T16:38:41.509565+02:00"
  }
}

