POST /api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 935
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "value": {
      "contractDuration": {
        "years": 12
      }, 
      "yearlyPaymentsPercentage": 0.85, 
      "annualCostsReduction": [
        2500, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900, 
        900
      ]
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids/062a6f48cb6c440daf82dad30cc3a894
{
  "access": {
    "token": "4769546090f94d6080bfd9826405954e"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "value": {
      "amountPerfomance": 1174.6200911956682, 
      "yearlyPaymentsPercentage": 0.85, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 11089.123287671233, 
      "contractDuration": {
        "days": 0, 
        "years": 12
      }, 
      "annualCostsReduction": [
        2500.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0
      ]
    }, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-09-28T15:01:13.673213+03:00", 
    "id": "062a6f48cb6c440daf82dad30cc3a894"
  }
}

