POST /api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2772
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/5252cc01a35448ccb3de1bedeffc3fc6?KeyID=faa11b27&Signature=VMGUH2Guq%2FMtaSKgUwtZyNsvDAgR2QO40OWYtPekOpHY2%2BtVBxXa6%2Fj7SoqVH5NuGvzyzfXDFxXA0GHPUGviBQ%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "title": "Proposal_part2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/cd6b1a6d6ba74f43b76ebbb55080943c?KeyID=faa11b27&Signature=T%2FxxGS65oH7pEkW3qUIRzhWKZOOxbZgzYgl%2FwWdXQBKld%2Bf4dJ%2FkYaLfdVCmbMBtvb%2BkocWb1y7Sk07cUzR2DA%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/61203db3eccb4ce8bdc32cf15da8ed2b?KeyID=faa11b27&Signature=FcHYTjbzPOra54QSK1H76TMLKTa2AOSfOK2afc%2BkIUureKCyu6RFGHPFT9yGu4jFp9A%2FiIc%2FpSizrUuEBfG8Bw%3D%3D", 
        "title": "eligibility_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "contractDuration": {
        "days": 40, 
        "years": 13
      }, 
      "yearlyPaymentsPercentage": 0.86, 
      "annualCostsReduction": [
        4000, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800
      ]
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/d0aa7a278e0e403384b0c3fd3d76d836?KeyID=faa11b27&Signature=PbkZRgQxljejeK1hoZkSK0CsemtFcbrrnhSccFP6QR76nS%2Fhhy0zlTLxILT1fQfIw7EAMWbW0Ed7BNybcdVyDg%3D%3D", 
        "title": "financial_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко", 
          "email": "fake@mail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 35", 
          "locality": "м. Львів"
        }
      }
    ], 
    "qualificationDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/2a2e723c282f4d1fbbec9b6bf0e01839?KeyID=faa11b27&Signature=b95hmk9JWOxcE4f3wOo2iGLqn9Fg19AYjnXrYjomOq4zkkKVOAxN65r2aECUqvt3J4X6mMKSmOw1mf9OLaIvBA%3D%3D", 
        "title": "qualification_document.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids/04a807a9df5f481b8c6f4245b0ed0e8a
{
  "access": {
    "token": "8f27fcd520794d559b6b9cd973cd6f15"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids/04a807a9df5f481b8c6f4245b0ed0e8a/documents/86489a0f7d854693b07fafb9e0e80a68?download=5252cc01a35448ccb3de1bedeffc3fc6", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-28T15:01:13.897599+03:00", 
        "id": "86489a0f7d854693b07fafb9e0e80a68", 
        "dateModified": "2017-09-28T15:01:13.897626+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids/04a807a9df5f481b8c6f4245b0ed0e8a/documents/e23d9b33aa074e2a8eb895dedaef73ee?download=cd6b1a6d6ba74f43b76ebbb55080943c", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-28T15:01:13.898422+03:00", 
        "id": "e23d9b33aa074e2a8eb895dedaef73ee", 
        "dateModified": "2017-09-28T15:01:13.898450+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids/04a807a9df5f481b8c6f4245b0ed0e8a/eligibility_documents/01dee734d230485d806b3703dc3fabad?download=61203db3eccb4ce8bdc32cf15da8ed2b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-28T15:01:13.900095+03:00", 
        "id": "01dee734d230485d806b3703dc3fabad", 
        "dateModified": "2017-09-28T15:01:13.900123+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "04a807a9df5f481b8c6f4245b0ed0e8a", 
    "value": {
      "amountPerfomance": 1169.4092069673368, 
      "yearlyPaymentsPercentage": 0.86, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 12265.249315068493, 
      "contractDuration": {
        "days": 40, 
        "years": 13
      }, 
      "annualCostsReduction": [
        4000.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0
      ]
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids/04a807a9df5f481b8c6f4245b0ed0e8a/financial_documents/34e3bebc6b204a78b06028cb0425eb71?download=d0aa7a278e0e403384b0c3fd3d76d836", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-28T15:01:13.899269+03:00", 
        "id": "34e3bebc6b204a78b06028cb0425eb71", 
        "dateModified": "2017-09-28T15:01:13.899296+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-09-28T15:01:13.896789+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0bade97aaaa44e198ec7bb7b7b8d7af8/bids/04a807a9df5f481b8c6f4245b0ed0e8a/qualification_documents/7ab6cee1c86e41b080a701b4fcf01616?download=2a2e723c282f4d1fbbec9b6bf0e01839", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-28T15:01:13.900926+03:00", 
        "id": "7ab6cee1c86e41b080a701b4fcf01616", 
        "dateModified": "2017-09-28T15:01:13.900953+03:00"
      }
    ]
  }
}

