POST /api/0.12/tenders/a98e830539804bb19ffb2cdd7ec84be8/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 704
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/a98e830539804bb19ffb2cdd7ec84be8/bids/ecdc15b5c32547e08586678d1207e010
{
  "access": {
    "token": "72057950b92c4b879b3e78e1a9c093dc"
  }, 
  "data": {
    "date": "2016-02-02T12:04:15.787626+02:00", 
    "status": "pending", 
    "id": "ecdc15b5c32547e08586678d1207e010", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

