POST /api/2.4/tenders/8d1a850940624e01919e551968148f75/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 824
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "draft", 
    "lotValues": [
      {
        "relatedLot": "94140aedad4b4b53b66d4ae85967f7f8", 
        "value": {
          "amount": 500
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "Bid is not a member of agreement", 
      "location": "body", 
      "name": "data"
    }
  ]
}

