POST /api/2.4/tenders/5a12aa2342aa4042bf6980a62d52669b/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1107
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "draft", 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "contractDuration": {
        "days": 74, 
        "years": 10
      }, 
      "yearlyPaymentsPercentage": 0.9, 
      "annualCostsReduction": [
        500, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000, 
        1000
      ]
    }, 
    "subcontractingDetails": "ДКП «Орфей», Україна"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/5a12aa2342aa4042bf6980a62d52669b/bids/90968d627c5844b5bfbfb37fd1e8267f
{
  "access": {
    "token": "1ab5d30c28ca485cb0d7dba5d46aa131"
  }, 
  "data": {
    "status": "draft", 
    "value": {
      "yearlyPaymentsPercentage": 0.9, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 9432.74, 
      "contractDuration": {
        "days": 74, 
        "years": 10
      }, 
      "amountPerformance": 865.24, 
      "annualCostsReduction": [
        500.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0
      ]
    }, 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-10-11T17:20:18.389185+03:00", 
    "id": "90968d627c5844b5bfbfb37fd1e8267f"
  }
}

