POST /api/2.4/tenders/a894be5c781148189cd720b6b8c83a9d/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1696
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/bffdcfced77a475bba4edba60519121c?KeyID=8e008c82&Signature=LxtPxwuW%2FrWgfCnI%2BPhsvXmQpVSLUCIsyCxruxLrlM%2BF60DeTZqYBQ9QcrcZeuEEMBZ2%2F6YUga8jfiVMut7aAQ%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/b6890a2a479f48a3b3514d29cdf1bf99?KeyID=8e008c82&Signature=wyv%2FH1GPZ%2B6kWOVk9H5ctKQPIiNi431sDaxotoQuw04kgPCXkXcG2NSyxS3XSAdVlwMl%2FTsf%2FvOQaMe7qz59Dw%3D%3D", 
        "title": "Proposal_part2.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "lotValues": [
      {
        "relatedLot": "452029a0046446d0811541dd6cc10485", 
        "value": {
          "amount": 499
        }
      }
    ], 
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "value": 0.1
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "value": 0.1
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037257", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/a894be5c781148189cd720b6b8c83a9d/bids/9bbc29a9170f42e69d349bfc11749aed

{
  "access": {
    "token": "d2bee408aba64ff1a106b98d72758500"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/a894be5c781148189cd720b6b8c83a9d/bids/9bbc29a9170f42e69d349bfc11749aed/documents/68c12c572e2e4b8596d0fa28d367717f?download=bffdcfced77a475bba4edba60519121c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-25T15:48:23.192989+02:00", 
        "id": "68c12c572e2e4b8596d0fa28d367717f", 
        "dateModified": "2019-01-25T15:48:23.193033+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/a894be5c781148189cd720b6b8c83a9d/bids/9bbc29a9170f42e69d349bfc11749aed/documents/9001b35c013a4421903e1d88363e83b6?download=b6890a2a479f48a3b3514d29cdf1bf99", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-25T15:48:23.194737+02:00", 
        "id": "9001b35c013a4421903e1d88363e83b6", 
        "dateModified": "2019-01-25T15:48:23.194803+02:00"
      }
    ], 
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "value": 0.1
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "value": 0.1
      }
    ], 
    "lotValues": [
      {
        "relatedLot": "452029a0046446d0811541dd6cc10485", 
        "date": "2019-01-25T15:48:23.190724+02:00", 
        "value": {
          "currency": "UAH", 
          "amount": 499.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037257", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "date": "2019-01-25T15:48:23.191482+02:00", 
    "id": "9bbc29a9170f42e69d349bfc11749aed"
  }
}

