POST /api/2.3/tenders/9796c1eae0ea423990752b84b4b42136/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2584
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/307c1a94314b4d1486c05dbd86a8fa5c?KeyID=17b2e1e5&Signature=gSNt%2F0%2BP4ubinwn%2FQ0Y7Jbr98W2rOegWiYxJ%2B5gCqx1nZ2xDmtOLufK4lST3iSRhhcZaACHUbAdpzAZX4S%2BXAg%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "title": "Proposal_part2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/019699e5307e4a60aa7345d9b3f605da?KeyID=17b2e1e5&Signature=f%2FTzPsnr%2B%2FNX%2BY3G45cwqPn7dh4P29nAei0MC4IDpuAP7QpNfGBnENhXEs0R8dHzzgj5Zm%2BYhVakKKOJ26gVAQ%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/4c27287ec95f4a53b59b696876f5bcbf?KeyID=17b2e1e5&Signature=hhJ%2Fsh8hV19iBLi7rFJ4TFGI4YFbAFW3CvK6%2FxUSz2zfSXQFVnxloifvmLA1RG3F50OtnckknXg0ZFbk9%2BzmAQ%3D%3D", 
        "title": "eligibility_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "amount": 5
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/e78e2199724942ff993516e302879ced?KeyID=17b2e1e5&Signature=lht5rr2CINha3IRDoastKwKeVtXf6bCtZ7S5Qj7UKD7mBKNa7%2FNdE5mp2lprZ3uaxPcCIgSQamFsl4sL1nbMDw%3D%3D", 
        "title": "financial_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко", 
          "email": "fake@mail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 35", 
          "locality": "м. Львів"
        }
      }
    ], 
    "qualificationDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/0543206813be4f48a34f96b893414e8f?KeyID=17b2e1e5&Signature=VWTKB5AWwSDn6buW%2BakmnOvmThRGtXZfuqgz992A9s%2BYBkzKiUxrZ%2B4RizRP7S30eOJ4z7bWxpJmPMm%2FC3aNAw%3D%3D", 
        "title": "qualification_document.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/9796c1eae0ea423990752b84b4b42136/bids/f94a9c030c4e40128343b6a2f6e86733
{
  "access": {
    "token": "924996d1c8a34e48b61a32c24877e3a3"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/9796c1eae0ea423990752b84b4b42136/bids/f94a9c030c4e40128343b6a2f6e86733/documents/6bd10f85ecda4dd5a753d7c76a7e49f7?download=307c1a94314b4d1486c05dbd86a8fa5c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-19T19:46:24.424610+03:00", 
        "id": "6bd10f85ecda4dd5a753d7c76a7e49f7", 
        "dateModified": "2017-06-19T19:46:24.424641+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/9796c1eae0ea423990752b84b4b42136/bids/f94a9c030c4e40128343b6a2f6e86733/documents/201243582a2d476fb22520aa72ee51f8?download=019699e5307e4a60aa7345d9b3f605da", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-19T19:46:24.425547+03:00", 
        "id": "201243582a2d476fb22520aa72ee51f8", 
        "dateModified": "2017-06-19T19:46:24.425578+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/9796c1eae0ea423990752b84b4b42136/bids/f94a9c030c4e40128343b6a2f6e86733/eligibility_documents/4d0fcd93a9f748a8b2c4c5e6c8a0af02?download=4c27287ec95f4a53b59b696876f5bcbf", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-19T19:46:24.427475+03:00", 
        "id": "4d0fcd93a9f748a8b2c4c5e6c8a0af02", 
        "dateModified": "2017-06-19T19:46:24.427507+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "f94a9c030c4e40128343b6a2f6e86733", 
    "value": {
      "currency": "UAH", 
      "amount": 5.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/9796c1eae0ea423990752b84b4b42136/bids/f94a9c030c4e40128343b6a2f6e86733/financial_documents/c24aa41909d64aaf8e9da79412adf00f?download=e78e2199724942ff993516e302879ced", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-19T19:46:24.426516+03:00", 
        "id": "c24aa41909d64aaf8e9da79412adf00f", 
        "dateModified": "2017-06-19T19:46:24.426548+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-06-19T19:46:24.423480+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/9796c1eae0ea423990752b84b4b42136/bids/f94a9c030c4e40128343b6a2f6e86733/qualification_documents/efdf5086add746e783db96e16c78a62c?download=0543206813be4f48a34f96b893414e8f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-19T19:46:24.428421+03:00", 
        "id": "efdf5086add746e783db96e16c78a62c", 
        "dateModified": "2017-06-19T19:46:24.428453+03:00"
      }
    ]
  }
}

