GET /api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/c4d18256e9424d9c86295587b4a5105b?acc_token=3c7e3a5c241644e3ad10cd43ffa5bcdb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/77f727ee1c1f4da7a630d95008d3ec33?KeyID=b5549f61&Signature=Q%2FXsx1pmLTEbT7JgXb6Ng0VLInDR4AN5nYZ6Zf6yxNYswqb9O7v903tpmxOMMjfUjNKTUWHrdEjm0PtHLGLhDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:11.737269+03:00", 
        "id": "42f898da333f4da5a6b18025ecc4a1cd", 
        "dateModified": "2017-09-05T14:44:11.737301+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/bids/c4d18256e9424d9c86295587b4a5105b/documents/ebaf8ffec786492f8b01e630583efa11?download=a93afd1e029442daacced30f664d17ff", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:11.738242+03:00", 
        "id": "ebaf8ffec786492f8b01e630583efa11", 
        "dateModified": "2017-09-05T14:44:11.738273+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/366eb55ba1684fe2a39fddde91023fb0?KeyID=b5549f61&Signature=5Uf1GurmUjZASK2Ril6M2aGhXPwnvQq5nhtzsDP6CiQqxD%2FcNQUoBrO7Ay3XJC998r25mPfpN%252Bf%252BLkCw%252B1wwDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-09-05T14:44:11.740238+03:00", 
        "id": "718c84aea56c469d803420b1cb44b3c3", 
        "dateModified": "2017-09-05T14:44:11.740270+03:00"
      }
    ], 
    "selfEligible": true, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "id": "c4d18256e9424d9c86295587b4a5105b"
  }
}

