PATCH /api/2.0/tenders/875bccb8079448419db42ee024419900/qualifications/d29f48be0f8042d7a796df51645d19ef?acc_token=5b38bae696d94227a71156cc736054d2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "id": "d29f48be0f8042d7a796df51645d19ef", 
    "bidID": "8cdfca0a69764a88b93d1f99d9e1c669"
  }
}

