PATCH /api/2.0/tenders/8fc0196e093e451692e674e2996ed0b3/qualifications/a9c4144348724e5cbeff9c6a33f09fee?acc_token=8c015522cc604d2485b82abb6e1162d2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "id": "a9c4144348724e5cbeff9c6a33f09fee", 
    "bidID": "b5ad8d15b7434eb9806e55c8139d83b3"
  }
}

