PATCH /api/2.3/tenders/d5dae9eea0214f8f94a5f95c9f2dc8a0/qualifications/645bef67e3f640568acdcb3514a45400?acc_token=3c7e3a5c241644e3ad10cd43ffa5bcdb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "c4d18256e9424d9c86295587b4a5105b", 
    "date": "2017-09-05T14:44:12.805227+03:00", 
    "id": "645bef67e3f640568acdcb3514a45400"
  }
}

