PATCH /api/2.4/tenders/98627a1dc8d44177b7024f4ee0630a21/lots/90c2d26254824897b0edf34d662fb010?acc_token=e6c08842d01c46f2bf536f628ded9d97 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-01-26T00:00:00+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-11-21T18:15:50.021042+02:00", 
    "id": "90c2d26254824897b0edf34d662fb010", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }
  }
}

