GET /api/2.1/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.1/tenders?offset=2016-03-24T13%3A46%3A28.273606%2B02%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.1/tenders?offset=2016-03-24T13%3A46%3A28.273606%2B02%3A00", 
    "offset": "2016-03-24T13:46:28.273606+02:00"
  }, 
  "data": [
    {
      "id": "3c70cdab10a342a48973fb96f5fb6d08", 
      "dateModified": "2016-03-24T13:46:28.273606+02:00"
    }
  ]
}

