POST /api/2.3/tenders/37d76fe5ae1c4543b1b7e3be3c479293/awards?acc_token=10c3effe74934c74bb9dedd02b14f1fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1284
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "date": "2016-01-14T18:07:00.628073+02:00", 
    "status": "pending", 
    "suppliers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "id": "d373338bc3324f14b8b3d4af68922773", 
    "value": {
      "currency": "UAH", 
      "amount": 475000, 
      "valueAddedTaxIncluded": "true"
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/37d76fe5ae1c4543b1b7e3be3c479293/awards/2b0084bf3ebb4d60b2b197661dc19c0d
{
  "data": {
    "status": "pending", 
    "complaintPeriod": {
      "startDate": "2017-09-14T19:40:54.427729+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-09-14T19:40:54.419827+03:00", 
    "id": "2b0084bf3ebb4d60b2b197661dc19c0d"
  }
}

