PATCH /api/0.12/tenders/732634d9870e427094d43b0c833c8866/contracts/824af4b0c49b4c9188008b482a3b1f51?acc_token=4e2565ce4dd04253876b6fbc677d415d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "awardID": "609e6a907d6b48d0b536dc52c3b5142b", 
    "id": "824af4b0c49b4c9188008b482a3b1f51"
  }
}

