POST /api/0.12/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2079
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2016-03-27T11:05:17.015145+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "id": "37810000-9", 
          "description": "Test"
        }, 
        "quantity": 1
      }
    ], 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21027", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Стахурського. 22", 
        "locality": "м. Вінниця"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/58e80d5cc52e4eb28cb9e2c5dcbd171c
{
  "access": {
    "token": "7c8bc7315f954186a385e1bd234a2c15"
  }, 
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-03-11-000002", 
    "tenderPeriod": {
      "startDate": "2016-03-11T11:05:37.971435+02:00", 
      "endDate": "2016-03-27T11:05:17.015145+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-03-27T11:05:17.015145+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-03-11T11:05:37.971435+02:00", 
      "endDate": "2016-03-23T11:05:17.015145+02:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "enquiryPeriod": {
      "startDate": "2016-03-11T11:05:37.971435+02:00", 
      "endDate": "2016-03-17T11:05:17.015145+02:00"
    }, 
    "next_check": "2016-03-27T12:05:17.015145+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "959bb94e60804b7080e70bd141bf1e8c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "owner": "broker", 
    "dateModified": "2016-03-11T11:05:38.137053+02:00", 
    "id": "58e80d5cc52e4eb28cb9e2c5dcbd171c", 
    "awardCriteria": "lowestCost"
  }
}

