PATCH /api/2.4/tenders/29fb21ea52a64dc8a1614d1f312ec395/documents/27aaac33cf53470ab9d215a8f1744144?acc_token=84e5e22d17d74352873a558633d2a07a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "document description modified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description modified", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/ea507d5bee4e4dd9b11ef1c0757e1450?KeyID=369e79af&Signature=IJCdSRQrT53UAbukeoTmYJrtQv5pz0jxxLqTFrxj2m%2Fjsxnjo6M3NzBOkRh98OHre7O683e%2F4Q6t6AXPyKTHDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-09-28T09:56:37.454151+03:00", 
    "author": "tender_owner", 
    "documentType": "technicalSpecifications", 
    "id": "27aaac33cf53470ab9d215a8f1744144", 
    "dateModified": "2018-09-28T09:56:37.454166+03:00"
  }
}

