PATCH /api/2.4/tenders/898e921c72d042e4af3df6253abb1678/contracts/880b08b810fa42039ccf97119bf8e98e?acc_token=f329278573ee4e2fbdc52652e338a673 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "dateSigned": "2017-10-03T11:17:59.449801+03:00"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "896096667a4146ae990a6f6872fa66e5", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "1484c360c4f446e08fb8b563c4dae36d", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "yearlyPaymentsPercentage": 0.9, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 9413.013698630137, 
      "contractDuration": {
        "days": 74, 
        "years": 10
      }, 
      "amountPerformance": 930.6233519809404, 
      "annualCostsReduction": [
        500.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0
      ]
    }, 
    "dateSigned": "2017-10-03T11:17:59.449801+03:00", 
    "awardID": "79e40d1c2b8c4626a0194ea9fb8b4317", 
    "id": "880b08b810fa42039ccf97119bf8e98e", 
    "contractID": "UA-2017-10-03-000001-1"
  }
}

