PATCH /api/2.0/tenders/dd420d3036f04ebc8e6f12d0a0bf86ba/contracts/bf3ce5f7ade045c4b11d3564aacd8b08/documents/380b9f43576c4d768bbc7bb3ed90a1f3?acc_token=77ac0f0854f241f3a0c18ae04d2052f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "title_en": "Title of Document", 
    "language": "en", 
    "description_en": "Description of Document"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "language": "en", 
    "title": "contract_second_document.doc", 
    "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/dd420d3036f04ebc8e6f12d0a0bf86ba/contracts/bf3ce5f7ade045c4b11d3564aacd8b08/documents/380b9f43576c4d768bbc7bb3ed90a1f3?download=f39a72e1825a46ea95ac6bdf12aa45b2", 
    "format": "application/msword", 
    "title_en": "Title of Document", 
    "description_en": "Description of Document", 
    "datePublished": "2016-03-16T17:32:28.431740+02:00", 
    "documentOf": "tender", 
    "id": "380b9f43576c4d768bbc7bb3ed90a1f3", 
    "dateModified": "2016-03-16T17:32:28.431790+02:00"
  }
}

