GET /api/0.12/tenders?opt_pretty=1 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/0.12/tenders?offset=2016-02-02T12%3A04%3A13.820451%2B02%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/0.12/tenders?offset=2016-02-02T12%3A04%3A13.820451%2B02%3A00", 
    "offset": "2016-02-02T12:04:13.820451+02:00"
  }, 
  "data": [
    {
      "id": "a98e830539804bb19ffb2cdd7ec84be8", 
      "dateModified": "2016-02-02T12:04:13.820451+02:00"
    }
  ]
}

