POST /api/2.3/tenders/0f67d0af4cdb47f2bab36b37e33bd84a/awards?acc_token=62e6766aacb942c481ff5833e5f1274a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1284
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "date": "2016-01-14T18:07:00.628073+02:00", 
    "status": "pending", 
    "suppliers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "id": "d373338bc3324f14b8b3d4af68922773", 
    "value": {
      "currency": "UAH", 
      "amount": 475000, 
      "valueAddedTaxIncluded": "true"
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/0f67d0af4cdb47f2bab36b37e33bd84a/awards/13926fdfd30c4e2e939e9b7529fb0edd
{
  "data": {
    "status": "pending", 
    "complaintPeriod": {
      "startDate": "2017-06-19T20:02:33.589328+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-06-19T20:02:33.587469+03:00", 
    "id": "13926fdfd30c4e2e939e9b7529fb0edd"
  }
}

