PATCH /api/2.1/tenders/1d91eb0b469947d18921f02e1d767d9e/awards/5cdb0640b75c4e47a09ed6411ce7a97b?acc_token=35a8eb46a7154037922423e312183957 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "award_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/1d91eb0b469947d18921f02e1d767d9e/awards/5cdb0640b75c4e47a09ed6411ce7a97b/documents/2ecd0cc755b84313a953138c89d4b41d?download=f3bb4a46097a4fcda1ea2c93faa5b623", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-21T12:46:39.590893+02:00", 
        "id": "2ecd0cc755b84313a953138c89d4b41d", 
        "dateModified": "2016-03-21T12:46:39.590934+02:00"
      }, 
      {
        "title": "award_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/1d91eb0b469947d18921f02e1d767d9e/awards/5cdb0640b75c4e47a09ed6411ce7a97b/documents/b87190c4ff3d497e931046e7e4ffc2c8?download=afcd1046f04e42b5be1261d7ae500764", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-21T12:46:39.824583+02:00", 
        "id": "b87190c4ff3d497e931046e7e4ffc2c8", 
        "dateModified": "2016-03-21T12:46:39.824626+02:00"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-21T12:46:39.371007+02:00", 
    "id": "5cdb0640b75c4e47a09ed6411ce7a97b"
  }
}

