POST /api/2.0/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2477
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2016-04-06T15:54:17.581774+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "id": "37810000-9", 
          "description": "Test"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-04-10T15:54:17.581675+02:00", 
          "endDate": "2016-05-10T15:54:17.581740+02:00"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21027", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Стахурського. 22", 
        "locality": "м. Вінниця"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/d86df479d20b409c9a8e3b9c63f22c02
{
  "access": {
    "token": "ac48ad2164414d4bb0cf7cf4ef9e7d63"
  }, 
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-03-21-000002", 
    "tenderPeriod": {
      "startDate": "2016-03-21T15:54:37.829400+02:00", 
      "endDate": "2016-04-06T15:54:17.581774+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2016-03-21T15:54:37.829400+02:00", 
      "endDate": "2016-03-27T15:54:17.581774+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-03-21T15:54:37.829400+02:00", 
      "endDate": "2016-04-02T15:54:17.581774+02:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-04-06T16:54:17.581774+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-04-06T15:54:17.581774+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2016-03-21T15:54:37.942821+02:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-04-10T15:54:17.581675+02:00", 
          "endDate": "2016-05-10T15:54:17.581740+02:00"
        }, 
        "id": "3cef1bea2fb14b1b9d55fadadf61d9ce", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "d86df479d20b409c9a8e3b9c63f22c02", 
    "awardCriteria": "lowestCost"
  }
}

