GET /api/2.3/tenders/223852eccea04e92926bcc49032f04b8/documents?acc_token=6ecc159e1942403f88015bfe0bd2220e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/46b198f7ff3649ea81167946edd9d149?KeyID=a71957a7&Signature=EgNgE8tHkvduxLO%2FOY87cMKOUceKZNd6eAfEJQY7c%252BMk3jwuMQjq1%2F9gWdXuNoIlkfRe%252BkFz3TOKmSQXSrmwBA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-06-20T12:33:41.321896+03:00", 
      "id": "8be1f13dc0a047a2b987b5751db79029", 
      "dateModified": "2017-06-20T12:33:41.321938+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/864201d0598c44e48eea5262f6427793?KeyID=a71957a7&Signature=SsP6ajNKUzC3G36wwaeiqk22PMultYyhZRj1EMEhyEhdnuMxd%252Bl5jQVXZEH%252BayXzVOC1cWV369y2ZGdyrVRuBA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-06-20T12:33:41.427340+03:00", 
      "id": "b15939424cc2494aa7bd96b66b182f2f", 
      "dateModified": "2017-06-20T12:33:41.427373+03:00"
    }
  ]
}

