POST /api/2.3/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2504
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2016-05-14T13:07:02.139044+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "id": "37810000-9", 
          "description": "Test"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-05-18T13:07:02.138959+03:00", 
          "endDate": "2016-06-17T13:07:02.139011+03:00"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "procurementMethodType": "aboveThresholdUA.defense", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "kind": "defense", 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21027", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Стахурського. 22", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/49948f59df824ababddf23761c90688a
{
  "access": {
    "token": "e943d7eef49948cb98f1de2815265f72"
  }, 
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-04-28-000002", 
    "tenderPeriod": {
      "startDate": "2016-04-28T13:07:26.403769+03:00", 
      "endDate": "2016-05-14T13:07:02.139044+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2016-04-28T13:07:26.403769+03:00", 
      "clarificationsUntil": "2016-05-17T00:00:00+03:00", 
      "endDate": "2016-05-12T00:00:00+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-04-28T13:07:26.403769+03:00", 
      "endDate": "2016-05-12T13:07:02.139044+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA.defense", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-05-14T13:07:02.139044+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "defense", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-05-14T13:07:02.139044+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2016-04-28T13:07:26.519139+03:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-05-18T13:07:02.138959+03:00", 
          "endDate": "2016-06-17T13:07:02.139011+03:00"
        }, 
        "id": "a2380fcd22ee4d18a2679b23508ecf4a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "49948f59df824ababddf23761c90688a", 
    "awardCriteria": "lowestCost"
  }
}

