GET /api/2.1/tenders/9d8028bfafde454ba40131c6974de5f4/contracts/4abcf05654244e9c8cb7a1eb0c57c565/documents?acc_token=117bc31601454af1bdee99a9064b78a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "title": "contract_first_document.doc", 
      "url": "http://api-sandbox.openprocurement.org/api/2.1/tenders/9d8028bfafde454ba40131c6974de5f4/contracts/4abcf05654244e9c8cb7a1eb0c57c565/documents/141ac23bba414cdb84b75ba3e6898abd?download=dc7e10e15bf74e5db469aa352cfe8d03", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2016-03-28T18:03:37.424481+03:00", 
      "id": "141ac23bba414cdb84b75ba3e6898abd", 
      "dateModified": "2016-03-28T18:03:37.424522+03:00"
    }
  ]
}

