PATCH /api/0.12/tenders/fd002ab62dc14a21a5f4b5b881a90643?acc_token=8dc013d938cc4e04a0f5aef8c8fb3f00 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2016-03-24T18:09:58.326677+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "documents": [
      {
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/fd002ab62dc14a21a5f4b5b881a90643/documents/dc8d28af5f3f4c86961ae7d95fe95577?download=5e8df95b2e9a49858097ec228eb7ab04", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T18:09:57.350654+02:00", 
        "id": "dc8d28af5f3f4c86961ae7d95fe95577", 
        "dateModified": "2016-03-16T18:09:57.350700+02:00"
      }, 
      {
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/fd002ab62dc14a21a5f4b5b881a90643/documents/08afcdea4b6f4280a0c3e2cc8e2856b5?download=f6cdce3b6fdd4c2dba443f0f16f17994", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T18:09:57.516858+02:00", 
        "id": "08afcdea4b6f4280a0c3e2cc8e2856b5", 
        "dateModified": "2016-03-16T18:09:57.516903+02:00"
      }, 
      {
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/fd002ab62dc14a21a5f4b5b881a90643/documents/08afcdea4b6f4280a0c3e2cc8e2856b5?download=419fe0d442464d13948cc8943b42e47f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T18:09:57.516858+02:00", 
        "id": "08afcdea4b6f4280a0c3e2cc8e2856b5", 
        "dateModified": "2016-03-16T18:09:57.678097+02:00"
      }
    ], 
    "tenderID": "UA-2016-03-16-000001", 
    "tenderPeriod": {
      "startDate": "2016-03-03T18:09:58.081578+02:00", 
      "endDate": "2016-03-24T18:09:58.326677+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "startDate": "2016-03-18T18:09:58.081578+02:00", 
      "shouldStartAfter": "2016-03-24T18:09:58.326677+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-03-03T18:09:58.081578+02:00", 
      "endDate": "2016-03-20T18:09:58.326677+02:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "enquiryPeriod": {
      "startDate": "2016-03-03T18:09:58.081578+02:00", 
      "endDate": "2016-03-14T18:09:58.326677+02:00"
    }, 
    "next_check": "2016-03-24T18:09:58.326677+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-03-16T18:09:57.815775+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "fded597457c04cbf8a621b3a88f586bc", 
        "questionOf": "tender"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "ead80900ac77421793ea3c0a47ccda96", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "owner": "broker", 
    "dateModified": "2016-03-16T18:09:58.424383+02:00", 
    "id": "fd002ab62dc14a21a5f4b5b881a90643", 
    "awardCriteria": "lowestCost"
  }
}

