PUT /api/2.4/tenders/3c9f0ba3810346ad895f5da76bf91287/documents/948587a2914c415f9390d88d78f3a776?acc_token=f987ed45c62b484e8d186aba73e3c749 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy863771055037$
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/a3d84ae8504b4a02b77ddab93d9b1ef2?KeyID=b5374f91&Signature=juP6%2FMeH4jNdZAGbETLen0mBcjHDyAb8d5sF3UAnDzFQ4HmRoJDXj6vmXhkYICvsCELPzUtrfjG%252Bu5%2FtcxPoBQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-09-04T16:14:09.131946+03:00", 
    "id": "948587a2914c415f9390d88d78f3a776", 
    "dateModified": "2018-09-04T16:14:09.195336+03:00"
  }
}

