PATCH /api/2.4/tenders/4e095f899aea431dade658804787b2aa/cancellations/d576ef2b283e4c968b6e8a3ec4ab6724?acc_token=8a38796ad4814abcaf75da2c44b5c6cc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2018-11-30T16:38:34.991435+02:00", 
    "cancellationOf": "tender", 
    "id": "d576ef2b283e4c968b6e8a3ec4ab6724"
  }
}

