PUT /api/2.3/tenders/ecc90314cd2e42198d4effc825696a97/documents/a0d6c53b95744260acc6dab57d74f6ae?acc_token=d2d5e9957a024ac2a7edb7cfddef84d3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy478459350982$
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "title": "AwardCriteria-2.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/ecc90314cd2e42198d4effc825696a97/documents/a0d6c53b95744260acc6dab57d74f6ae?download=f27312e2649e4e7a87f72974c7d3de84", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-04-25T14:47:00.541552+03:00", 
    "id": "a0d6c53b95744260acc6dab57d74f6ae", 
    "dateModified": "2016-04-25T14:47:00.777672+03:00"
  }
}

