POST /api/2.3/tenders/157627ed1f20474eaf6b7135e6aff687/bids/ac725ca7be874d2a836bc9e4474a0b6e/documents?acc_token=040e082f270b4b82b4f4345d513a53f9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 188
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy665538307175$
Host: api-sandbox.openprocurement.org


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/157627ed1f20474eaf6b7135e6aff687/bids/ac725ca7be874d2a836bc9e4474a0b6e/documents/a4a2ba69cebf43988c6a87063cf30dc8
{
  "data": {
    "confidentiality": "public", 
    "language": "uk", 
    "title": "Proposal.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/157627ed1f20474eaf6b7135e6aff687/bids/ac725ca7be874d2a836bc9e4474a0b6e/documents/a4a2ba69cebf43988c6a87063cf30dc8?download=e50f1345c5fa4f6a8c0fd33a42571fa0", 
    "format": "application/pdf", 
    "isDescriptionDecision": false, 
    "documentOf": "tender", 
    "datePublished": "2016-08-17T11:56:57.085493+03:00", 
    "id": "a4a2ba69cebf43988c6a87063cf30dc8", 
    "dateModified": "2016-08-17T11:56:57.085510+03:00"
  }
}

