POST /api/2.3/tenders/d014500a9769491a81f3f1cecc1004f3/documents?acc_token=0b5ecdd3b42e4a3eb9f4c05235bdbbfa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy874375825392$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/d014500a9769491a81f3f1cecc1004f3/documents/044d16f393de429eae172417f669ec8d
{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d014500a9769491a81f3f1cecc1004f3/documents/044d16f393de429eae172417f669ec8d?download=b6ee0b7a85e44144a03c5683d32ceaf3", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-09-14T19:39:51.977554+03:00", 
    "id": "044d16f393de429eae172417f669ec8d", 
    "dateModified": "2017-09-14T19:39:51.977633+03:00"
  }
}

