POST /api/2.0/tenders/875bccb8079448419db42ee024419900/bids/38b0fc1d75df41c8ae0ac8d8c5cffdca/qualification_documents?acc_token=e0cf11d98894440da940f658bf0ebd15 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 202
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy678409393179$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/875bccb8079448419db42ee024419900/bids/38b0fc1d75df41c8ae0ac8d8c5cffdca/qualification_documents/75549d1e9d3f4dcda9c1801a5d589726
{
  "data": {
    "confidentiality": "public", 
    "language": "uk", 
    "title": "qualification_document.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/875bccb8079448419db42ee024419900/bids/38b0fc1d75df41c8ae0ac8d8c5cffdca/qualification_documents/75549d1e9d3f4dcda9c1801a5d589726?download=0fa3dc1dd0154e028eaf935925534f3c", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-18T17:08:20.550823+02:00", 
    "id": "75549d1e9d3f4dcda9c1801a5d589726", 
    "dateModified": "2016-03-18T17:08:20.550862+02:00"
  }
}

