POST /api/0.12/tenders/d1986ba116d4496fb5c3061794bc28f9/documents HTTP/1.0
Authorization: Basic dG9rZW46
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy569765196309$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/d1986ba116d4496fb5c3061794bc28f9/documents/7ef3553dbf934fa999a1a16ebc63b8ab
{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/d1986ba116d4496fb5c3061794bc28f9/documents/7ef3553dbf934fa999a1a16ebc63b8ab?download=7da4b38ff32846daa01c5f2124c8e44f", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-01-26T15:51:35.792588+02:00", 
    "id": "7ef3553dbf934fa999a1a16ebc63b8ab", 
    "dateModified": "2016-01-26T15:51:35.792619+02:00"
  }
}

