POST /api/2.3/tenders/9a3fe3666dbb4679aed131a85372f4af/bids/868c11ee64324f9daf0ae7fdbaab2f3c/eligibility_documents?acc_token=db56c50d42c646edb71f8bbc98402cae HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 195
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy199385668041$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/9a3fe3666dbb4679aed131a85372f4af/bids/868c11ee64324f9daf0ae7fdbaab2f3c/eligibility_documents/c58d255d3b0442d1ac2a8d166d715a93
{
  "data": {
    "confidentiality": "public", 
    "language": "uk", 
    "title": "eligibility_doc.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/9a3fe3666dbb4679aed131a85372f4af/bids/868c11ee64324f9daf0ae7fdbaab2f3c/eligibility_documents/c58d255d3b0442d1ac2a8d166d715a93?download=dca52aabff7b40eaa3622d8e8378ca2f", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-04-25T15:45:03.812081+03:00", 
    "id": "c58d255d3b0442d1ac2a8d166d715a93", 
    "dateModified": "2016-04-25T15:45:03.812121+03:00"
  }
}

