POST /api/2.4/tenders/98627a1dc8d44177b7024f4ee0630a21/bids/9f4f492eb1044677b9fa0194d7420ec4/financial_documents?acc_token=1cfe43c11620440d8a57f0f8dda79bc8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 245
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy896215621459$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/98627a1dc8d44177b7024f4ee0630a21/bids/9f4f492eb1044677b9fa0194d7420ec4/financial_documents/e59625744f1e4171a502d7f7dac91bf5
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "prices.xlsx", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/bea5c045f3994fdba85614290fa87598?KeyID=25173212&Signature=U4TLwGj2ZIuOUO4O%252BNt8unK8hz%2Ff9FSNsE6UHiIRFlJom9m1T5Gc%252BKTKobSidxOad1eYpSfv1AxD%252Bax%2FhJuFBg%253D%253D", 
    "format": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", 
    "documentOf": "tender", 
    "datePublished": "2018-11-21T18:16:08.028723+02:00", 
    "id": "e59625744f1e4171a502d7f7dac91bf5", 
    "dateModified": "2018-11-21T18:16:08.028762+02:00"
  }
}

