POST /api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/bids/3fcb1802c01a4643b2bc25dfb4ccafab/documents?acc_token=45bcbe22ec5243c9b05a6bc9868a6b60 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 202
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy0517844931572$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/bids/3fcb1802c01a4643b2bc25dfb4ccafab/documents/dd8fdfbb432a40dc94c841ad7b54baba
{
  "data": {
    "confidentiality": "public", 
    "language": "uk", 
    "title": "Proposal_top_secrets.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/aa6128fa6a7a43e58bba316b9102ee69/bids/3fcb1802c01a4643b2bc25dfb4ccafab/documents/dd8fdfbb432a40dc94c841ad7b54baba?download=1c4a0f9097a347fdaf9904e518813d64", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-16T19:44:56.861175+02:00", 
    "id": "dd8fdfbb432a40dc94c841ad7b54baba", 
    "dateModified": "2016-03-16T19:44:56.861212+02:00"
  }
}

