GET /api/2.3/contracts/5e58f434fe5245a785b8db082e578e05/changes/06d8fc7770a94ebe93cd60e3c258d2c4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "rationaleTypes": [
      "volumeCuts", 
      "priceReduction"
    ], 
    "rationale_en": "Contract change cause", 
    "rationale": "Опис причини змін контракту", 
    "date": "2016-05-26T19:12:28.298428+03:00", 
    "id": "06d8fc7770a94ebe93cd60e3c258d2c4"
  }
}

