GET /api/2.3/contracts/5cceaf781c3f4b6893cc4e8766f79200/changes/ad59e18b89aa4ff2b4d4de1f4f98091d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "rationaleType": "volumeCuts", 
    "rationale_en": "Contract change cause", 
    "rationale": "Опис причини змін контракту", 
    "date": "2016-05-20T19:52:53.772902+03:00", 
    "id": "ad59e18b89aa4ff2b4d4de1f4f98091d"
  }
}

