PATCH /api/2.5/submissions/f68c222b077f4657a6df8f51de0ae451?acc_token=1c07e7429eb84a03b6a99c4111be48e8 HTTP/1.0
Authorization: Bearer broker
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "qualificationID": "edc70fc4b64f479e998cb3c808454f27",
    "frameworkID": "86396c65e9154359a2329bfc7dddd3eb",
    "dateModified": "2023-01-17T00:00:00+02:00",
    "date": "2023-01-17T00:00:00+02:00",
    "datePublished": "2023-01-17T00:00:00+02:00",
    "owner": "broker",
    "status": "active",
    "submissionType": "electronicCatalogue",
    "tenderers": [
      {
        "name": "ДКП «Школяр»",
        "scale": "micro",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»",
          "uri": "http://www.sc.gov.ua/"
        },
        "address": {
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100",
          "countryName": "Україна"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "email": "soleksuk@gmail.com",
          "telephone": "+380432216930"
        }
      }
    ],
    "id": "f68c222b077f4657a6df8f51de0ae451"
  }
}

