PATCH /api/2.5/submissions/307a5eb4da8948faa46564921a9facf6?acc_token=680e74861490448a9177bf199cb6395b HTTP/1.0
Authorization: Bearer broker
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "deleted"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "tenderers": [
      {
        "name": "НАЗВА",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "00137256",
          "uri": "http://www.sc.gov.ua/",
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»"
        },
        "address": {
          "countryName": "Україна",
          "streetAddress": "вул. Островського, 33",
          "locality": "м. Вінниця",
          "region": "Вінницька область",
          "postalCode": "21100"
        },
        "contactPoint": {
          "name": "Сергій Олексюк",
          "telephone": "+380432216930",
          "email": "soleksuk@gmail.com"
        },
        "scale": "micro"
      }
    ],
    "documents": [
      {
        "id": "90016b13615145eb89f20331f5935d66",
        "datePublished": "2023-10-26T01:00:00+03:00",
        "hash": "md5:00000000000000000000000000000000",
        "title": "submission_docs.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d9006a35da3b4389bf1be5cd34a3071a?Signature=i8SHbMgp8F%2BDTPKCmPFxk0f7CTww8xsbmAdwhOky%2FgyFcAIuTveMDAT69TBjFyLOOYgdCosl%2FL%2FQ6JWzoPq%2BCA%3D%3D&KeyID=a8968c46",
        "dateModified": "2023-10-26T01:00:00+03:00",
        "language": "uk"
      }
    ],
    "frameworkID": "78d4ab4039c8441d8cac856e90e3b82b",
    "status": "deleted",
    "dateModified": "2023-10-26T01:00:00+03:00",
    "date": "2023-10-26T01:00:00+03:00",
    "owner": "broker",
    "submissionType": "electronicCatalogue",
    "id": "307a5eb4da8948faa46564921a9facf6"
  },
  "config": {}
}

