GET /api/2.5/frameworks/19554516edc64b80ad4a2834f4505fbe/documents/d220eb62f60a4ae88103b7369be80fdb?acc_token=5f94ccea4dfb4cdebd5de69ecd449013 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "d220eb62f60a4ae88103b7369be80fdb",
    "hash": "md5:00000000000000000000000000000000",
    "title": "framework_additional_docs.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f0c1e419fc8f4a92b7a4d02d6bc44504?Signature=QwHlQqaj1YoV9Hj13rib4fRT3TA85dvzgEobHEOxSJ59%2FROoBNsLtX1wv91KhTzDuNWjbiWjfvopEEu1Cj5VAA%3D%3D&KeyID=a8968c46",
    "datePublished": "2023-01-01T00:00:00+02:00",
    "dateModified": "2023-01-01T00:00:00+02:00",
    "previousVersions": [
      {
        "id": "d220eb62f60a4ae88103b7369be80fdb",
        "hash": "md5:00000000000000000000000000000000",
        "title": "framework_additional_docs.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9391730d81504cb1a89d902205585047?Signature=GckTmK4GCug67LIfPCU5zhGbAKD24V4ie%2BSNl6gGpSA6PRHJFj58oE%2F4pKEWp2r4%2FeKKYwu4Ir4lH3kk%2Bbv5CQ%3D%3D&KeyID=a8968c46",
        "datePublished": "2023-01-01T00:00:00+02:00",
        "dateModified": "2023-01-01T00:00:00+02:00"
      }
    ]
  }
}

