GET /api/2.5/submissions/19973fee87084fe7a00db94ad14f0c0d/documents HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "submission_docs.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7cf748c0eeba401bad6a536957058f28?KeyID=a8968c46&Signature=SauFQRp9WIIuZj995VWk4iBo7ocqk8JecJLXIoZGCboc4Pr2xae3%2FWt4O2k7Zd8k7TJfxVKXkdboHDBVHx5xAQ%253D%253D", 
      "format": "application/msword", 
      "datePublished": "2020-09-24T01:00:00+03:00", 
      "id": "30adbb19270a4fd985abbea82946aa03", 
      "dateModified": "2020-09-24T01:00:00+03:00"
    }
  ]
}

