GET /api/2.5/qualifications/6fce332a98dc49939a6a6f0dc2fa33c6 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "frameworkID": "2e17a7116854417a9ce9709b87369783",
    "submissionID": "3b382cf2e93241ecbc760c66c18bcfd6",
    "qualificationType": "electronicCatalogue",
    "status": "pending",
    "date": "2027-01-17T00:00:00+02:00",
    "dateModified": "2027-01-17T00:00:00+02:00",
    "id": "6fce332a98dc49939a6a6f0dc2fa33c6"
  },
  "config": {
    "restricted": false,
    "qualificationComplainDuration": 0
  }
}

