POST /api/2.5/frameworks/1b70e498d27e4c1dba8838d6807dac0c/documents?acc_token=797fdae523914449922546561e43242f HTTP/1.0
Authorization: Bearer broker
Content-Length: 326
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "framework.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e38e94f4fbab44ecb6f74b90a27e6181?Signature=S4ZIJmRAPa9iDj895YM90wsfSUlBfNExiNKevl9fJdtqw9PkVqhLZP4i7c8sxPSUlRFaQu7puJZzjJwxAF%2BfBg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/frameworks/1b70e498d27e4c1dba8838d6807dac0c/documents/7137fa5d73c64e8ba56d6ea099e6059c

{
  "data": {
    "hash": "md5:00000000000000000000000000000000",
    "title": "framework.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e38e94f4fbab44ecb6f74b90a27e6181?Signature=eYTcMLrU9pbzXw3zQawemAR2B5P4wH7q9Oi%2BaSrfd8yz0GREYrG3PD2aGzaBcLE443%2FXz7h48KBhMQ9rMl8HDw%3D%3D&KeyID=a8968c46",
    "language": "uk",
    "id": "7137fa5d73c64e8ba56d6ea099e6059c",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "dateModified": "2023-10-10T01:00:00+03:00"
  }
}

