POST /api/2.5/submissions/7c37a548e4db48a0ac3c1b4d9ead2c5f/documents?acc_token=680e74861490448a9177bf199cb6395b HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "specs.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/755dcc02111848bfaccb0f24edc68253?Signature=fnpGjdlcPG9nmaBNuOQOHKWdEjDrZWrnqz421atOUWtbg9xWrUqT2lrJ%2BxiG0HXYdYLER47rtRbX8CRi7BLICw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword",
    "documentType": "technicalSpecifications",
    "confidentiality": "buyerOnly",
    "confidentialityRationale": "Дуже конфіденційний файл, треба приховати"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/submissions/7c37a548e4db48a0ac3c1b4d9ead2c5f/documents/29d3b10680d242959acdfc88d5a205c5

{
  "data": {
    "documentType": "technicalSpecifications",
    "hash": "md5:00000000000000000000000000000000",
    "title": "specs.doc",
    "format": "application/msword",
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/submissions/7c37a548e4db48a0ac3c1b4d9ead2c5f/documents/29d3b10680d242959acdfc88d5a205c5?download=755dcc02111848bfaccb0f24edc68253",
    "language": "uk",
    "confidentiality": "buyerOnly",
    "confidentialityRationale": "Дуже конфіденційний файл, треба приховати",
    "id": "29d3b10680d242959acdfc88d5a205c5",
    "datePublished": "2023-10-26T01:00:00+03:00",
    "dateModified": "2023-10-26T01:00:00+03:00"
  }
}

