POST /api/2.5/frameworks/40b48e4878534db1bf228d5928f8f1d9/documents?acc_token=7c6a46e300bb41438ef626232028950b HTTP/1.0
Authorization: Bearer broker
Content-Length: 172
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="framework_additional_docs.doc"
Content-Type: application/msword

additional info
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/frameworks/40b48e4878534db1bf228d5928f8f1d9/documents/0be832c754934419844dba2e1db51f63
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "framework_owner", 
    "title": "framework_additional_docs.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4605a66669e84bc293040c5bbeb8d6b1?KeyID=a8968c46&Signature=lqy%252Bhwfsx2YbgHA6HRJm1tJ8aebCAOUP1rYdqi8DjsydegsFrU7a8YRpLgkd0uJ4MIkpQT59IBdKLTuuPZTkBA%253D%253D", 
    "format": "application/msword", 
    "datePublished": "2020-09-08T01:00:00+03:00", 
    "id": "0be832c754934419844dba2e1db51f63", 
    "dateModified": "2020-09-08T01:00:00+03:00"
  }
}

