from openprocurement.tender.openeu.tests.qualification import TenderQualificationBaseTestCase
from openprocurement.tender.core.tests.qualification_milestone import TenderQualificationMilestone24HMixin


class TenderQualificationMilestoneTestCase(TenderQualificationMilestone24HMixin, TenderQualificationBaseTestCase):
    pass
