from openprocurement.tender.openeu.tests.qualification import TenderQualificationBaseTestCase
from openprocurement.tender.core.tests.qualification_milestone import TenderQualificationMilestoneMixin


class TenderQualificationMilestoneTestCase(TenderQualificationMilestoneMixin, TenderQualificationBaseTestCase):
    pass
